### ISSUE TITLE
Remove React.memo() anytime a react element is accepted

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#10]
While the default strategy should be to not use `React.memo()` unless there is a good reason to use it cc @eps1lon, looking at the codebase, there is a quick win on the problem. In 99% of the cases, anytime a React element is accepted as a prop, `React.memo()` is a waste of CPU cycles (unless [this babel plugin](https://babeljs.io/docs/en/babel-plugin-transform-react-constant-elements) kicks in, which is not frequent).

Components we can make faster be removing memo:

- https://github.com/mui-org/material-ui-x/blob/fb5af45b5d74ca818fc6945af17400cec0ee21a2/packages/grid/src/components/row.tsx#L13
- https://github.com/mui-org/material-ui-x/blob/fb5af45b5d74ca818fc6945af17400cec0ee21a2/packages/grid/src/components/sticky-container.tsx#L4

**Comment by m4theushw** [comment]
I looked the entire codebase and I couldn't any useless `React.memo` still being used. The two examples mentioned in the description were already fixed a long time ago.
