### ISSUE TITLE
Uncaught TypeError: onPageChange is not a function at handleNextButtonClick (TablePaginationActions.js:69)

### ISSUE THREAD

**Issue by CMKavyashree** [mui-org/material-ui-x#1018]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

On click of next page icon, getting error onPageChange is not a function.

## Expected Behavior 🤔

On click of next page icon, should call the passed function.

## Steps to Reproduce 🕹

`      <DataGrid rows={this.props.rowsData} 
                columns={this.props.columnsData} 
                sortModel={[
                  {
                    field: 'id',
                    sort: 'asc',
                  },
                ]}
                pagination
                pageSize={5}
                rowCount={100}
                paginationMode="server"
                onPageChange={(params) => {
                  console.log("===params===",params);
                }}
                loading={this.state.loading}
                />`

Steps:

1. import { DataGrid } from '@material-ui/data-grid'
2. For onPageChange pass the function as (params) => {
                  console.log("===params===",params);
                }
3. Load the application, table renders fine.
4. OnClick of next page Icon getting the error - Uncaught TypeError: onPageChange is not a function
    at handleNextButtonClick (TablePaginationActions.js:69)

## Context 🔦

I'm trying to add pagination to DataGrid component and table is rendering fine with the data passed, but on click of next page I'm getting the above mentioned error. 

codesandbox example - https://codesandbox.io/s/currying-meadow-embvh?file=/src/App.js

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
```

```
    System:
    OS: macOS Mojave 10.14.6
  Binaries:
    Node: 10.23.0 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 88.0.4324.150
  npmPackages:
    @emotion/react: ^11.1.4 => 11.1.4 
    @emotion/styled: ^11.0.0 => 11.0.0 
    @material-ui/core: ^5.0.0-alpha.23 => 5.0.0-alpha.23 
    @material-ui/data-grid: ^4.0.0-alpha.17 => 4.0.0-alpha.17 
    @material-ui/icons: ^4.11.2 => 4.11.2 
    @material-ui/lab: ^4.0.0-alpha.57 => 4.0.0-alpha.57 
    @material-ui/styled-engine:  5.0.0-alpha.23 
    @material-ui/styles: ^4.0.0-rc.0 => 4.10.0 
    @material-ui/system:  5.0.0-alpha.23 
    @material-ui/types:  5.1.0 
    @material-ui/unstyled:  5.0.0-alpha.23 
    @material-ui/utils:  4.10.2 
    @types/react:  16.9.36 
    react: ^17.0.1 => 17.0.1 
    react-dom: ^16.13.1 => 16.13.1

**Comment by DanailH** [comment]
Hi, @CMKavyashree thanks for reporting this. I saw that you are using `@material-ui/data-grid@4.0.0.-alpha.17` with `@material-ui/core@5.0.0.-alpha.23`. We provided support for v5 in `@material-ui/data-grid@4.0.0.-alpha.18` that's why your setup is not working. If you want to use a version of `DataGrid` prior to `v4.0.0.-alpha.18` you would have to use it with core v4. Hope that helps.
