### ISSUE TITLE
[DataGrid] Unify publishing events params

### ISSUE THREAD

**Issue by dtassone** [mui-org/material-ui-x#1036]
## Summary 💡

We currently have descrepancies between all the events params. Therefore this issue is about unifying all those events params.

link in #885 

> onPageChange should have two arguments (event, page). It shouldn't include unrelated state, like pageCount, pageSize,

## Examples 🌈
`onPageChange`
`onCellClick`

## Motivation 🔦

Unify the usage of the grid.

**Comment by m4theushw** [comment]
I'm closing this one because the example of `onPageChange` will be fixed once #2099 is merged. All other situations that I can imagine we kinda already solved when `useGridControlState` was implemented. We can keep #1301 to discuss the params as it has more information.
