### ISSUE TITLE
[docs] Improve customization documentation

### ISSUE THREAD

**Issue by dtassone** [mui-org/material-ui-x#1037]
## Summary 💡

Create a page that explains how to leverage the grid state, and the apiRef together to extend and customize the grid.

Move these sections:

- https://material-ui.com/components/data-grid/rendering/#components-prop
- https://material-ui.com/components/data-grid/rendering/#customization-example

Under a new page: https://material-ui.com/components/data-grid/customization, with the follow structure

```
# Data Grid - Customization

## Components
## Toolbar
## Footer
## Loading overlay
## No rows overlay
## Ant Design
```

**Comment by bryyytl** [comment]
I wanted to add a few suggestions/ideas regarding the customization documentation improvements. I think it would be great to have additional documentation within the rendering section showing how to easily customize the styling of GridPanel, FilterPanel, ColumnsPanel, and other related components. Currently, it is not clear (based on just reading the documentation alone) whether the easiest way to customize these inner panel classes is by creating custom slots and passing a className to these custom slots or if there is another way to easily overwrite some of the inner panel classes.

Here are a few potential ideas that I think would help to improve this (a few of these ideas have been mentioned in other related posts):
- Provide an example of how to customize the ColumnsPanel or FilterPanel component similar to https://material-ui.com/components/data-grid/rendering/#styling-header
- Provide CSS documentation for the panel classes similar to https://material-ui.com/api/x-grid/#css
- Create a separate page for giving a brief overview about the GridSlotsComponent. I appreciate the direct link in the API documentation to how this works, but it would be helpful to combine some of the slot resources together and possibly separate it out of the rendering documentation for the sake of clarity (like in the case of the toolbar and overlay documentation). 
- Include more documentation about the GridSlotsComponentProps API

**Comment by oliviertassinari** [comment]
A pain to solve in this effort: https://github.com/mui-org/material-ui-x/issues/1370#issuecomment-819399886
