### ISSUE TITLE
in version 4.0.0-alpha.20,  @material-ui/data-grid has no exported member SelectionChangeParams and onSelectionChange

### ISSUE THREAD

**Issue by brantsrasmus** [mui-org/material-ui-x#1065]
There seems to be a bug with the lastest version. When importing DataGrid the onSelectionChange property does not seem to be exported by the module. Also SelectionChangeParams is not found. Its found by typescript but not by the compiler.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Now the compiler can't find these member of the DataGrid module. 

## Expected Behavior 🤔

Should be exported as members from the module.

## Steps to Reproduce 🕹

Steps:

1. Upgrade to latest version
2. Try use onSelectionChange with SelectionChangeParams

` onSelectionChange={(param: SelectionChangeParams) => {}}`

## Your Environment 🌎

  System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 15.5.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.3.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 88.0.4324.150
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @material-ui/core: ^4.11.2 => 4.11.3
    @material-ui/data-grid: ^4.0.0-alpha.20=> 4.0.0-alpha.20
    @material-ui/icons: ^4.11.2 => 4.11.2
    @material-ui/lab: ^4.0.0-alpha.57 => 4.0.0-alpha.57
    @material-ui/pickers: ^3.2.10 => 3.2.10
    @material-ui/styles:  4.11.3
    @material-ui/system:  4.11.3
    @material-ui/types:  5.1.0
    @material-ui/utils:  4.11.2
    @types/react: ^16.9.53 => 16.14.4
    react: ^17.0.1 => 17.0.1
    react-dom: ^17.0.1 => 17.0.1
    typescript: ^4.0.3 => 4.1.5
</details>

**Comment by dtassone** [comment]
We have made some breaking changes in our last release, check out the release page https://github.com/mui-org/material-ui-x/releases

- `onSelectionChange` was renamed to `onSelectionChange`
- `SelectionChangeParams ` was renamed to `SelectionModelChangeParams `

```diff
-<DataGrid onSelectionChange={selectionChangeHandler} />
+<DataGrid onSelectionModelChange={onSelectionModelChangeHandler} />
```

**Comment by brantsrasmus** [comment]
> We have made some breaking changes in our last release, check out the release page https://github.com/mui-org/material-ui-x/releases
> 
> * `onSelectionChange` was renamed to `onSelectionChange`
> * `SelectionChangeParams ` was renamed to `SelectionModelChangeParams `
> 
> ```diff
> -<DataGrid onSelectionChange={selectionChangeHandler} />
> +<DataGrid onSelectionModelChange={onSelectionModelChangeHandler} />
> ```

Oh sorry! Missed that. Will close the issue. Have confirmed its working

**Comment by virgil9306** [comment]
This has been changed to `GridSelectionModelChangeParams` for now -- see https://stackoverflow.com/questions/66399667/material-ui-datagrid-checkbox-row-selection-is-not-working for example
