### ISSUE TITLE
[DataGrid] Documentation: logger, logLevel, icons props

### ISSUE THREAD

**Issue by emily-ellevation** [mui-org/material-ui-x#1072]
Hello! I'm wondering about documentation/examples for the (free) DataGrid's `logger`, `logLevel` and `icons` props. For logging, I've tracked down [this code](https://github.com/mui-org/material-ui-x/blob/6764e8051003ff4a3d800d64428badac91f79ea5/packages/grid/_modules_/grid/GridComponent.tsx#L66) but seems as though custom logger, logLevel would only be propagated via an options prop which is not in the official API docs (I've seen this prop in older SO posts so possible deprecated?). Also looking for clarity on the `icons` prop -- is this deprecated in favor of passing Icons via the `components` prop or is it something else altogether?

- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Motivation 🔦

Making thorough DataGrid docs even better 👍 
Thank you so much for any help and for the awesome work that you do.

**Comment by oliviertassinari** [comment]
> Looking for clarity on the icons prop -- is this deprecated in favor of passing Icons via the components prop

@emily-ellevation Yes

> logger, logLevel

Do you have a specific use case in mind? So far, I didn't document this feature so 1. we can consider it, allowing us to remove it without it being a breaking change 2. forcing developers to come up with a solid problem that this feature could solve.

**Comment by emily-ellevation** [comment]
Thanks so much for a speedy reply! 
Re:#2 I was really just running through the API to spec out all of our potential options for functionality and trying to understand how I _might_ use the logging props so definitely non-blocking for us and more of a documentation/visibility question. FWIW if uses cases are low and its largely private, I think hiding it from Docs is a good solution to avoid confusion 👍

**Comment by oliviertassinari** [comment]
@emily-ellevation Oh ok, so it was simply asking for clarification. I'm closing for now then. Let's wait for developers asking for the feature :)
