### ISSUE TITLE
[XGrid] Remove sort icon when sortOrder is null

### ISSUE THREAD

**Issue by alexdanilowicz** [mui-org/material-ui-x#1073]
- [X] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate. 

*However, it's eerily similar to https://github.com/mui-org/material-ui/issues/12561 but that's for a different component and a different repo.*

## Current Behavior 😯

When sorting is disable and a column is right aligned, there is still a space for the icon, making the alignment look off.

Screenshot:
![Screen Shot 2021-02-17 at 10 45 30 AM](https://user-images.githubusercontent.com/29822597/108263306-ed582f80-711a-11eb-86cf-a7266b8ab39a.png)

## Expected Behavior 🤔

No space for the sorting icon when I see a column that is not sortable in the XGrid.

## Steps to Reproduce 🕹

https://codesandbox.io/s/material-demo-forked-inj71?file=/demo.tsx:215-216

## Context 🔦

Trying to get the XGrid to look good. Seems weird that it's `align: right` but there's a space for a non present icon!

## Your Environment 🌎
 

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Browsers:
    Chrome: 88.0.4324.150
    Edge: Not Found
    Firefox: Not Found
    Safari: 14.0.3
  npmPackages:
    @material-ui/core:  4.9.14
    @material-ui/icons:  5.0.0-alpha.24
    @material-ui/lab:  4.0.0-alpha.53
    @material-ui/styles:  4.9.14
    @material-ui/system:  4.9.14
    @material-ui/types:  5.1.0
    @material-ui/utils:  4.10.2
    @material-ui/x-grid:  4.0.0-alpha.20
    @material-ui/x-license:  4.0.0-alpha.20
    @types/react:  16.9.55
    react: ~16.13.0 => 16.13.1
    react-dom: ^16.0.0 => 16.14.0
 ```
</details>

## Order id 💳

**Order #20020**

**Comment by dtassone** [comment]
try setting headerAlign to right in your column definition
```tsx
   {
      field: "unique_records",
      headerName: "Test",
      align: "right",
      headerAlign: "right"
  }
```

**Comment by oliviertassinari** [comment]
I'm confused. Why is `align` not setting `headerAlign` too?

**Comment by dtassone** [comment]
At the moment, if you want to align the header one way, you need to set the headerAlign.
One could set the header center and the content to the right...

**Comment by oliviertassinari** [comment]
@dtassone Ok, so do you agree that we should change the logic? (have `headerAlign` defaults to the value of `align` unless provided)

**Comment by alexdanilowicz** [comment]
@dtassone and @oliviertassinari Totally agree a user may want to have `headerAlign` and `align` be different values, as Damien said. So perhaps it is worthwhile to change the logic (have headerAlign defaults to the value of align unless provided). In the meantime, I've open a [PR](https://github.com/mui-org/material-ui-x/pull/1074) to make the docs clearer that `align` is separate from `headerAlign`.

Thank you for the prompt responses extremely helpful and really appreciate the support. 🚀

**Comment by dtassone** [comment]
@oliviertassinari we don't need 3 values. 
We can have headerAlign defaults to the value of align unless provided, or we can leave it this way as it's a low priority improvement. Maybe a clearer doc could avoid any confusion...

**Comment by oliviertassinari** [comment]
OK, I think that we can start with the documentation. If we still get issues opened like this one, then I think that it would be the signal that the logic needs to change.
