### ISSUE TITLE
[DataGrid] Missing translation for key filterOperatorAfter

### ISSUE THREAD

**Issue by Tollwood** [mui-org/material-ui-x#1075]
main~493df0b3.564e0e3faf705a28a8b6.bundle.js:1 Material-UI: GridComponent - An unexpected error occurred. Error: Missing translation for key filterOperatorAfter..  Error: Missing translation for key filterOperatorAfter.

- [x ] The issue is present in the latest release.
- [ x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Filtering a Table of type date causes an error due to missing translations.

## Expected Behavior 🤔

Filtering a Table of type date causes no errors. If translation is missing, translation key is used, but the table works as expected.

## Steps to Reproduce 🕹

Steps:

1. open https://material-ui-x.netlify.app/storybook/?path=/story/x-grid-demos-playground--commodity-500
2. filter date column ( Created On or Updated On)

## Context 🔦

I am offering a data grid that supports date columns. I cant no longer filter them. 

## Your Environment 🌎
Issue on Chrome and Firefox.
<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Browsers:
    Chrome: 88.0.4324.150
    Edge: Not Found
    Firefox: 84.0.2
    Safari: 14.0.2
  npmPackages:
    @material-ui/core: ^4.11.3 => 4.11.3 
    @material-ui/data-grid: 4.0.0-alpha.20 => 4.0.0-alpha.20 
    @material-ui/icons: ^4.11.2 => 4.11.2 
    @material-ui/lab: ^4.0.0-alpha.57 => 4.0.0-alpha.57 
    @material-ui/pickers: ^3.2.10 => 3.2.10 
    @material-ui/styles:  4.11.3 
    @material-ui/system:  4.11.3 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @types/react: ^16.9.0 => 16.14.4 
    react: 17.0.1 => 17.0.1 
    react-dom: 17.0.1 => 17.0.1 
    typescript: ^3.9.5 => 3.9.9 </details>

## Order id 💳

Not yet available. First I want to play around before switching to the pro plan :)

**Comment by oliviertassinari** [comment]
I can reproduce in the date column of https://material-ui.com/components/data-grid/filtering/#column-types too.

**Comment by oliviertassinari** [comment]
Once this is fixed, we should be able to: rebase #1079, merge, then rebase #1077, and merge.
