### ISSUE TITLE
The license instructions are confusing in EULA vs the repository's README - need clarification

### ISSUE THREAD

**Issue by Sd100** [mui-org/material-ui-x#1078]
Goal:
Trying to see if using data grid from material-ui-x for production is legally allowed or not.

Groundwork:
In store, it shows the license as EULA: 
https://material-ui.com/store/items/material-ui-x/
https://docs.google.com/document/d/1nkd5JP5wCefo6UwpVi6PnbTaw8DxhstkCZlfHV5ZgfI/edit?usp=sharing

But in readme of this repo, it shows datagrid - MIT license and x-grid - Commercial license, 

Query:
so when i import material-ui-x - does it mean i am allowed to use Data-grid in production environment of my project (saleable to customers)
OR 
are they available freely for development and learning purposes only.
Can someone help clarify/confirm urgently?

Raised as issue, since new users to license agreement's complex terms the readme kind of is throwing me in doubt. So after above answer, can somone also update the readme or else once i get an answer i can try to raise a PR to update the same for clarity to developers/consmers.

Thanks in advance.

**Comment by oliviertassinari** [comment]
See the license in the npm package you are importing:

- https://unpkg.com/@material-ui/data-grid@4.0.0-alpha.20/LICENSE => MIT
- https://unpkg.com/@material-ui/x-grid@4.0.0-alpha.20/LICENSE.md => Commercial, the [EULA](https://docs.google.com/document/d/1nkd5JP5wCefo6UwpVi6PnbTaw8DxhstkCZlfHV5ZgfI/edit?usp=sharing) is temporarily stored in google docs.
