### ISSUE TITLE
[DataGrid] Create boolean column type

### ISSUE THREAD

**Issue by dtassone** [mui-org/material-ui-x#1095]
## Summary 💡

Provide an easy way to handle boolean column type out of the box.
What renderer should we use? A quick poll

- 🎉 Checkbox

<img width="290" alt="Screenshot 2021-02-24 at 12 44 10" src="https://user-images.githubusercontent.com/3165635/108995917-0a05e180-769e-11eb-8323-e6ada914c50a.png">

https://airtable.com/tblm0fonTDgR8J0Wa/viwaWyVCsQBSvRde7?blocks=hide

<img width="187" alt="Screenshot 2021-02-24 at 12 40 49" src="https://user-images.githubusercontent.com/3165635/108995568-949a1100-769d-11eb-9cfe-9a57386da8fc.png">

https://www.telerik.com/kendo-react-ui/components/grid/get-started/

- ❤️ Tick/Cross icon

<img width="103" alt="Screenshot 2021-02-24 at 12 39 20" src="https://user-images.githubusercontent.com/3165635/108995420-63214580-769d-11eb-9c10-83a2c475afa6.png">

https://ag-grid.com/example.php

- 🚀 Yes/No

**Comment by giq-re** [comment]
checkbox

**Comment by oliviertassinari** [comment]
I have updated the issue's description to give some examples of what the rendered content could look like, as well as allowing people to vote for the option they prefer. I would personally vote for a checkbox-like UI (🎉) as it's closer to what we will use for the editable mode.

**Comment by dtassone** [comment]
We could render a tick and cross in view mode and a checkbox in edit mode.
