### ISSUE TITLE
Use translation in tooltip on filterbutton hover

### ISSUE THREAD

**Issue by SecretUnicorn** [mui-org/material-ui-x#1098]
- [X] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

I translated everything in the english example to german and imported it with the localeText prop like so:

`localeText={{...GERMAN_GRID_TRANSLATION}}`

The translation is used for pretty much everything but the filter says the english filter text when hovering the filter button. 

![image](https://user-images.githubusercontent.com/24612112/108724324-7dd0ae80-7525-11eb-88f7-e0aa5fbb4ffe.png)

## Examples 🌈

`<field_name> <translation(fitler_mode)> <filter_value>`

## Motivation 🔦

I don't know how to translate that bit.

**Comment by oliviertassinari** [comment]
@dtassone Did you consider keeping the content of the tooltip to its minimum? Would saying "1 filter" be enough?

**Comment by dtassone** [comment]
Well we could do but it should be easy to translate .

**Comment by oliviertassinari** [comment]
@SecretUnicorn If you have the time, it would be awesome to share the translations back into https://github.com/mui-org/material-ui-x/tree/master/packages/grid/_modules_/grid/locales so they can be shared with the communty.
