### ISSUE TITLE
[DataGrid] Pagination localization

### ISSUE THREAD

**Issue by quocanh176** [mui-org/material-ui-x#1107]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Currently of the footer of the table look like this while using pagination:
![108724352-83c68f80-7525-11eb-84ff-af8a01f825b6](https://user-images.githubusercontent.com/18285366/108974514-d0c17780-7685-11eb-9ed4-3fb714a0559c.png)

The word "of" is somehow not changeable and it affects the localization of the DataGrid when implementing it on another language.

## Context 🔦

I am trying to implement a DataGrid with Pagination on German. Everything seems fine until this small issue.

**Comment by DanailH** [comment]
It's missing `labelDisplayedRows`. I'll add it now so that it is available from the next release. @quocanh176 thanks for catching it 😉

**Comment by oliviertassinari** [comment]
it's more than `labelDisplayedRows`, there are also aria-labels for the icons.

**Comment by DanailH** [comment]
We can apply the same approach as the `columnHeaderFiltersTooltipActive` -> pass in a method that returns a translation.

**Comment by oliviertassinari** [comment]
The points I wonder about:

1. Do we need to duplicate the translation keys for the components? Do developers need to translate a `<TablePagination>` differently in the context of a data grid?
2. Should we ignore the translation of the core components and ask developers to configure them independently?
3. Should the data grid work in isolation, importing its translation from the core package, avoiding the need for 2?

**Comment by DanailH** [comment]
I think for now we can go with 3. and revise it later. Step 3 makes the mental model of localizing the grid easier IMO since if you pass in the translations for the grid the `TablePagination` will also be translated. Either way, I'm opened to suggestions 🙂

**Comment by oliviertassinari** [comment]
I personally think the following:

1. Leaning toward no duplication in the API. I think that we can wait for developers to come up with a good reason. If they really need to, they can render a custom Pagination. It's not very easy, but it's simple.
2. No duplication, this one is I think important. It's already complex enough. We don't need to maintain two different sets of translations.
3. or 4. No strong point of view. I like how 3. exposes this to the developers, but it makes the installation step a bit harder.

**Comment by DanailH** [comment]
Ok, the reason why I'm leaning towards 3. is that we already have used a similar approach for the `labelRowsPerPage` prop of the `TablePagination` component. I can open a draft PR to discuss the approach there.

**Comment by oliviertassinari** [comment]
> Ok, the reason why I'm leaning towards 3.

Then we don't have the same understanding of what option 3. is. The draft PR is: duplicating the API, duplicating the translations, not solving the problem with the documentation. It's the exact opposite of what I have tried to describe.

**Comment by dtassone** [comment]
I'm up for 3 as well. 
Users should be able to install the data-grid translations together or independently of the core translations.

**Comment by oliviertassinari** [comment]
> Users should be able to install the data-grid translations together

@dtassone Ok, this answer 3. vs. 4. so you prefer 4. over 3. of https://github.com/mui-org/material-ui-x/issues/1107#issuecomment-785033361. What's your take on 1. and 2? These are independent questions.

**Comment by oliviertassinari** [comment]
How about this solution?

1. We remove the `footerPaginationRowsPerPage` translation key of the data grid.
2. We import the translations of the table pagination from the core for each locale exposed by the data grid?

The pros:

- match Damien's concern about not documenting the import of locales from the core package
- no need to maintain the translation for 6 text x 100 locales
- makes it simpler in the future to be more granular about the bundle size cost of translating the components in the UI.

**Comment by DanailH** [comment]
It's a nice middle ground, I'll update the draft to see how it looks in practice.

**Comment by oliviertassinari** [comment]
I'm reopening per [@quocanh176](https://github.com/mui-org/material-ui-x/pull/1109#issuecomment-786688123) and [@MoiseScalzo](https://github.com/mui-org/material-ui-x/pull/1109#issuecomment-824128140). It seems that fixing the default translation is not enough. We also need to document the translation of the core components.

**Comment by scottbasgaard** [comment]
Is this possible? Also trying to localize these in DataGrid:
![image](https://user-images.githubusercontent.com/91581/121059432-c30da900-c7c1-11eb-8ec5-2eeb3680e3bd.png)

**Comment by oliviertassinari** [comment]
@scottbasgaard Yes, it's possible. See the source to find how the default locales handles the problem. As for having a more detailed answer: https://github.com/mui-org/material-ui-x/issues/1107#issuecomment-824163178.
