### ISSUE TITLE
[DataGrid] onMouseEnter and onMouseLeave events

### ISSUE THREAD

**Issue by 1106nanda** [mui-org/material-ui-x#1108]
Unable to use the onMouseEnter and onMouseLeave events on the rows of the DataGrid. even though we have onRowHover event it is only useful to set the state on hovering over the row, but I want to setState on hovering out of the row.

- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

when the mouse hovers over the row and also when the mouse hovers out of the row, we should be able to setState.

**Comment by oliviertassinari** [comment]
There are two differents approaches to solve this problem:

1. We can either allow to spread all the props on slots

```jsx
<DataGrid
  componnents={{ Row }}
  componentsProps={{ row: { onClick, onDbClick, onMouseOver, onMouseEnter } }}
>
```

2. Or we can add new flat props, as we see use cases for them:

- onRowMouseEnter
- onRowMouseLeave
- …
- …
- …
- …
- onCellMouseEnter
- onCellMouseLeave
- …
- …
- …
