### ISSUE TITLE
[DataGrid] Column header "Column Selection" not translatable / localizable

### ISSUE THREAD

**Issue by LarsKumbier** [mui-org/material-ui-x#1112]
The headerName for the "Column Selection" in the Column Selection Toolbar / GridToolbar is not translatable through the [localization constant file](https://github.com/mui-org/material-ui-x/blob/HEAD/packages/grid/_modules_/grid/constants/localeTextConstants.ts).

I would expect to be able to easily translate it there.

Instead, I use this workaround Functional Component, which patches the appropriate field:

```javascript
const TranslatedGridToolbar = (props) => {
  const el = props.columns.find(e => e.field === '__check__')
  if (el) {
    el.headerName = XGridLocale.toolbarColumnsHeaderName || el.headerName
  }

  return (<GridToolbar {...props} />)
}
```

But I'd like to see this having an easier solution. 

Last checked version: DataGrid / X-Grid 4.0.0-alpha.20

**Comment by oliviertassinari** [comment]
@LarsKumbier Do you have a live reproduction we can have a look at?

**Comment by LarsKumbier** [comment]
@oliviertassinari sorry for being unclear.

![grafik](https://user-images.githubusercontent.com/647850/109300226-8c290e00-7836-11eb-8f2b-7e1754abd7b8.png)

This column is automatically added, when the `checkboxSelection` attribute of `XGrid` or `DataGrid` is being set. But the columnHeader of this column is not easily translatable, since it's automatically added. For all developer-provided column definitions, the `headerName` is accessible and can be translated by the developer.

To solve this, I propose to add the header title for this column to the localization constant file.

**Comment by oliviertassinari** [comment]
@LarsKumbier Thanks for the extra details. On a side note, if you want to contribute the German translations, it would be great :)

**Comment by LarsKumbier** [comment]
@oliviertassinari sure thing - here you go: https://github.com/mui-org/material-ui-x/pull/1117

**Comment by oliviertassinari** [comment]
> To solve this, I propose to add the header title for this column to the localization constant file.

This sounds like a great idea. We could apply this translation at render time.

**Comment by LarsKumbier** [comment]
@oliviertassinari Essentialy what my workaround does - I guess you already have standard functionality in place for the rest of the file, so should be as much as wrapping it in `_(...)`.
