### ISSUE TITLE
[DataGrid] GridToolbar is not forwarding props

### ISSUE THREAD

**Issue by LarsKumbier** [mui-org/material-ui-x#1116]
The `GridToolbar` of a DataGrid or XGrid does not allow styles injections via `className`, so it cannot be styled through `makeStyles`.

- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Motivation 🔦

This is the only way I found to style the GridToolbar:

```js
const GridToolbarStyle = createMuiTheme({
  overrides: {
    MuiButton: {
      textSizeSmall: {
        padding: '10px 16px'
      }
    }
  }
})

const StyledGridToolbar = () => (
  <ThemeProvider theme={GridToolbarStyle}>
    <GridToolbar />
  </ThemeProvider>
)
```

This solution does not allow to reference any global settings in the application-wide MuiTheme. I'd rather overwrite the settings through `makeStyles()` and classes:

```js
const useStyles = makeStyles((theme) => {
  root: {
    padding: theme.spacing(3)
  }
})

const StyledGridToolbar = () => (
  const classes = useStyles()
  <GridToolbar className={classes.root} />
)
```

## Order id 💳

Not at hand right now.

**Comment by DanailH** [comment]
Hi, @LarsKumbier thanks for reporting this.

The `GridToolbar` is just a wrapper to make the OTB usage of the toolbar easier. if you want to customize it you can compose it yourself like this for example ->

```jsx
const useStyles = makeStyles((theme) => ({
    root: {
      padding: theme.spacing(9)
    }
  }));

  const StyledGridToolbar = () => {
    const classes = useStyles();

    return (
      <GridToolbarContainer className={classes.root}>
        <GridColumnsToolbarButton />
        <GridFilterToolbarButton />
      </GridToolbarContainer>
    );
  }
```

and then pass in the `StyledGridToolbar` to the grid

```jsx
<DataGrid
  components={{
    Toolbar: StyledGridToolbar,
  }}
/>
```

**Comment by LarsKumbier** [comment]
Yes, but I could not find the menu component for the row spacing?

**Comment by oliviertassinari** [comment]
This looks like a bug, all exported components of Material-UI are supposed to comply with the `describeConformance` testing helper (were some parts can be disabled, when they don't make sense, e.g. here the default props could be overkill.

In any case, not forwarding the red or the props is definitely breaking the conformance. 

https://github.com/mui-org/material-ui-x/blob/cad4f90b160f5847cebea9ba67c87c8786741dfa/packages/grid/_modules_/grid/components/toolbar/GridToolbar.tsx#L12

@LarsKumbier do you want to submit a pull request to fix this? :)
