### ISSUE TITLE
[DataGrid] Filter does not work in conjunction with valueFormatter

### ISSUE THREAD

**Issue by bobsys-mfleischer** [mui-org/material-ui-x#1118]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The column filter does not work if the value of the column was changed by the valueFormatter.
The search is still based on the field value.

## Expected Behavior 🤔

Values should be searched after valueFormatter.
A possibility to change the search would also be good if cells are specially rendered.

## Steps to Reproduce 🕹

https://codesandbox.io/s/vibrant-surf-2sq09?file=/src/demo.js
Try to search for the values A,B or C.

**Comment by oliviertassinari** [comment]
@bobsys-mfleischer The current behavior is the expected one. The value formatter should definitely not be used for filtering. The value formatter always returns a string, why the filtering is perform on the value, which can be boolean, number, etc.

Now, I think that can start by improving the documentation, we should explain which data is used for applying the filters, it's important.

Could you explain what problem you are trying to solve? At this point, I don't think that we have enough information on the pain to determin the best solution.

**Comment by bobsys-mfleischer** [comment]
My model includes statis like 'Open', 'Closed' or 'Aborted' as numeric values. (1,2,3)
 
But I want to display the corresponding text to the end user.
The end user should also be able to filter these values.

As a workaround I can add this text to my JavaScript object but the value is only for display to the end user and is not needed further.

A function to influence the search would be very helpful here.
Also when searching within a checkbox / boolean, currently the user must search for 0 or 1. More intuitive would be Yes or No or similar.

**Comment by oliviertassinari** [comment]
> My model includes states like 'Open', 'Closed' or 'Aborted' as numeric values. (1,2,3)

Maybe we should have an enum type, where you can use `valueGetter` to convert the number to the correct value of the enum 🤔.

Maybe we should have a prop to covert a value into a filterable one, and use for the global quick filter that we can implement in the future.

For boolean, we explore a native support in #1095, filtering should likely be part of it.

**Comment by dtassone** [comment]
We might need to store the value formatted in the state for perf reason or memoize the valueFormatter function

**Comment by oliviertassinari** [comment]
@dtassone Before talking about how we would implement it, I think that we should talk about the problem, and what product solution we want to put in place.

As far as the discussion went, it seems that we had two problems:

1. Confusion in the documentation. Filter should be performed on the value, not the formatted one. e.g consider a date. Developer can customize the filtering otherwise. The solution could be to improve the docs.
2. A missing column type. The user is looking for an enum column type, it seems tk be his root problem. The solution could be to add this column type.

**Comment by m4theushw** [comment]
I wouldn't remove `valueFormatter`. If the user wants just to apply a mask on a value it's easier to use it than to create a custom cell renderer. To prevent users from defining a formatter on a custom rendered cell we can have different `GridColDef`.

**Comment by oliviertassinari** [comment]
@m4theushw I fail to see how `valueFormatter` is easier than `renderCell`. However, I suspect that we will have a real use case for `valueFormatter` in the future with the grouping feature.

**Comment by m4theushw** [comment]
@oliviertassinari Using `renderCell` the user has return an element instead of a string.

```jsx
{
  field: "price",
  valueFormatter: params => `${params.value} USD`
}
```

```jsx
{
  field: "price",
  renderCell: params => <>{params.value} USD</>
}
```

**Comment by dtassone** [comment]
We had a chat about this one and we see potential edge cases with value formatters and filters.

1. Percentage columns or rates.
Usually percentage are stored between 0-1 for calculation purposes, but displayed in percentage ie 0-100%. Our commodity grid has the filled quantity column that illustrate this. A percentage value could be reused to in a value getter to calculate a price for example... 
ATM, to filter the filled Quantity column, you have to type the value not the percentage so 0.6 will work but not 60%

2. Price columns 
Prices use formatters, ie in the uk 1000 is 1 ,000; in france 1 000. Therefore should the filter work for 1,000? 
this is discussable as you cannot input the , in the filter input for numeric, but one could easily customize that...

**Comment by oliviertassinari** [comment]
> Using renderCell the user has to return an element instead of a string.

@m4theushw Well spotted, the type looks wrong. Wouldn't it be better with?

```diff
diff --git a/packages/grid/_modules_/grid/components/cell/GridCell.tsx b/packages/grid/_modules_/grid/components/cell/GridCell.tsx
index 6e43b7a0..e3be3bd3 100644
--- a/packages/grid/_modules_/grid/components/cell/GridCell.tsx
+++ b/packages/grid/_modules_/grid/components/cell/GridCell.tsx
@@ -36,7 +36,7 @@ export interface GridCellProps {
   value?: GridCellValue;
   width: number;
   cellMode?: GridCellMode;
-  children: React.ReactElement | null;
+  children: React.ReactNode;
   tabIndex: 0 | -1;
 }

diff --git a/packages/grid/_modules_/grid/components/cell/GridRowCells.tsx b/packages/grid/_modules_/grid/components/cell/GridRowCells.tsx
index 360f7a7d..7e97a39b 100644
--- a/packages/grid/_modules_/grid/components/cell/GridRowCells.tsx
+++ b/packages/grid/_modules_/grid/components/cell/GridRowCells.tsx
@@ -87,7 +87,7 @@ export const GridRowCells = React.memo((props: RowCellsProps) => {
     }

     const editCellState = editRowState && editRowState[column.field];
-    let cellComponent: React.ReactElement | null = null;
+    let cellComponent: React.ReactNode = null;

     if (editCellState == null && column.renderCell) {
       cellComponent = column.renderCell(cellParams);
diff --git a/packages/grid/_modules_/grid/models/colDef/gridColDef.ts b/packages/grid/_modules_/grid/models/colDef/gridColDef.ts
index ee3b7d18..987abe50 100644
--- a/packages/grid/_modules_/grid/models/colDef/gridColDef.ts
+++ b/packages/grid/_modules_/grid/models/colDef/gridColDef.ts
@@ -96,12 +96,12 @@ export interface GridColDef {
    * Allows to override the component rendered as cell for this column.
    * @param params
    */
-  renderCell?: (params: GridCellParams) => React.ReactElement;
+  renderCell?: (params: GridCellParams) => React.ReactNode;
   /**
    * Allows to override the component rendered in edit cell mode for this column.
    * @param params
    */
-  renderEditCell?: (params: GridCellParams) => React.ReactElement;
+  renderEditCell?: (params: GridCellParams) => React.ReactNode;
   /**
    * Class name that will be added in the column header cell.
    */
@@ -110,7 +110,7 @@ export interface GridColDef {
    * Allows to render a component in the column header cell.
    * @param params
    */
-  renderHeader?: (params: GridColumnHeaderParams) => React.ReactElement;
+  renderHeader?: (params: GridColumnHeaderParams) => React.ReactNode;
   /**
    * Header cell element alignment.
    */
```

> we see potential edge cases with value formatters and filters

@dtassone It would be great to benchmark what the others solutions are doing. Case 2. seems already solved by filtering on the value. For Case 1. I could find a [`numberParser`](https://ag-grid.com/react-grid/filter-number/#custom-number-support) option on AG Grid that seems to handle this problem.

**Comment by dtassone** [comment]
Add `GridColDef.valueParser` similar to ag-grid https://www.ag-grid.com/react-grid/filter-number/#custom-number-support

This feature should work with edit cells as well.

User should always input 10 for 10% instead of 0.1. Underlying value should be 0.1.

**Comment by manoharreddyporeddy** [comment]
As of today / Nov 2022:
Assumption was `search & filter` will use `valueFormatter` to search after caching data, etc.
But after using `valueFormatter`, both `search & filter` does not work
Work around is to update the `rows` data, then pass to `@mui/x-data-grid`'s DataGrid
