### ISSUE TITLE
[DataGrid] If data has field id, getRowId doesn't work

### ISSUE THREAD

**Issue by me82852578** [mui-org/material-ui-x#1119]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.
- [x] The issue is present in the latest release.

## Current Behavior 😯

If origin data has the field `id`, `getRowId` doesn't work. So if field `id` isn't unique will get the warning.

![MarineGEO circle logo](https://i.imgur.com/IDOIhcVh.png)

## Expected Behavior 🤔

Use new id which I need.

## Steps to Reproduce 🕹

 - Use this sample code to reproduce
```javascript
import React from 'react'
import { DataGrid } from '@material-ui/data-grid'

const BasicGrid = props => {
    const handleGetRowId = (e) => {
        return e.uniId
    }
    return (
        <DataGrid
            columns={[
                { field: 'uniId', width: 200 },
                { field: 'id', width: 200 },
                { field: 'name', width: 200 },
            ]}
            rows={[
                { id: 'company-ta-tb-id', name: 'TA-TB-XXXX', uniId: 'euald4541ajwndd1', },
                { id: 'company-ta-tb-id', name: 'TA-TB-YYYY', uniId: 'eakf4455anfw44dc', },
            ]}
            getRowId={handleGetRowId} />
    )
}

export default BasicGrid
``` 

## Context 🔦

In my project, the data set I got has used field `id` as part of the data, and the field `id` is not a unique identification code, the unique identification code is the field `uniId`.

I don't know why the company designed it this way, but this is a situation I face. 

I used the new API `getRowId` to work on this case, but I got the warning `index.js:1 Warning: Encountered two children with the same key`,  because If origin data have id already, `getRowId` dosen't work. 

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Browser: Chrome, Version 88.0.4324.150 (Official Build) (64-bit)
  System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
  Browsers:
    Chrome: 88.0.4324.150
    Firefox: 85.0.1
  npmPackages:
    @material-ui/core: ^4.11.3 => 4.11.3 
    @material-ui/data-grid: ^4.0.0-alpha.20 => 4.0.0-alpha.20 
    @material-ui/icons: ^4.11.2 => 4.11.2 
    @material-ui/lab: ^4.0.0-alpha.57 => 4.0.0-alpha.57 
    @material-ui/styles:  4.11.3 
    @material-ui/system:  4.11.3 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @material-ui/x-grid: ^4.0.0-alpha.20 => 4.0.0-alpha.20 
    @material-ui/x-grid-data-generator: ^4.0.0-alpha.20 => 4.0.0-alpha.20 
    @material-ui/x-license:  4.0.0-alpha.20 
    @types/react:  17.0.2 
    react: ^17.0.1 => 17.0.1 
    react-dom: ^17.0.1 => 17.0.1 
```
</details>

**Comment by dtassone** [comment]
This issue occurs because getRowId is used to compute the id and store it in an `id` field so having an id on the row confuses everything.
All we need to do is rename the computed `id` field to some kind of private field, maybe `_rowId_`?

**Comment by oliviertassinari** [comment]
The alternative option is to introduce two different objects row model / row data.

**Comment by dtassone** [comment]
Or as mentioned before, we remove the requirement for the id in the row itself, we have it stored in the state key mapping so we don't need it on the row. The refactoring is a bit bigger but nicer as we had the row model and row data before, and I remove it to keep the structure flat and avoid to store state in separate objects.

**Comment by me82852578** [comment]
I agree .
>This issue occurs because getRowId is used to compute the id and store it in an id field so having an id on the row confuses everything.

I try to edit function `addGridRowId` :
from 
```javascript
export function addGridRowId(rowData: GridRowData, getRowId?: GridRowIdGetter): GridRowModel {
  return getRowId == null ? (rowData as GridRowModel) : { id: getRowId(rowData), ...rowData };
}
```
to
```javascript
export function addGridRowId(rowData: GridRowData, getRowId?: GridRowIdGetter): GridRowModel {
  return getRowId == null ? (rowData as GridRowModel) : { ...rowData, id: getRowId(rowData) };
}
```
The changes can solve this issue(#1119), but will cause other problems, such as:
If there is the `id` field in the data, it will be overwritten.

**Comment by m4theushw** [comment]
> Or as mentioned before, we remove the requirement for the id in the row itself, we have it stored in the state key mapping so we don't need it on the row. The refactoring is a bit bigger but nicer as we had the row model and row data before, and I remove it to keep the structure flat and avoid to store state in separate objects.

@oliviertassinari @dtassone Do you agree to go with the refactor? It will require a lot of work but also fixes the object cloning bug

**Comment by dtassone** [comment]
> > Or as mentioned before, we remove the requirement for the id in the row itself, we have it stored in the state key mapping so we don't need it on the row. The refactoring is a bit bigger but nicer as we had the row model and row data before, and I remove it to keep the structure flat and avoid to store state in separate objects.
> 
> @oliviertassinari @dtassone Do you agree to go with the refactor? It will require a lot of work but also fixes the object cloning bug

Yes happy to discuss it if anything unclear. 
As mentioned above, it's all about removing the `id` field of `rowData`, which would remove the need to clone the object...
We will keep the `getRowId` function.

**Comment by pkit** [comment]
@m4theushw @dtassone I'm not sure why it's closed?
I don't really see a resolution in both mentioned PRs.
Nobody can rely on "id" field **not** existing in some random data pulled from SQL server, for example.
Nobody can rely on some "id"-like field to be truly unique, again, if pulled from a random dataset.
So what are the steps to make it work?

**Comment by m4theushw** [comment]
@pkit Could you open another issue describing better the problem? I didn't understand what you said. In the past, we had some usages of `row.id` in the codebase that were replaced by accessing the ID from another key. The mentioned PRs changed to call `getRowId` and storing the ID in this new key.
