### ISSUE TITLE
[DataGrid] fail to count width

### ISSUE THREAD

**Issue by liesislukas** [mui-org/material-ui-x#1137]
![image](https://user-images.githubusercontent.com/2733862/109418583-d98db280-79d1-11eb-9e2a-2844362921e1.png)

this error is removed when `disableExtendRowFullWidth` is set to true

```js
        <DataGrid
          loading={isLoading}
          autoHeight
          disableExtendRowFullWidth
          hideFooter
          getRowId={(row) => row.commitId}
          onRowSelected={(param) => console.log(`#20215914184355 param: `, param)}
          rows={rows}
          columns={columns}
          pageSize={25}
          checkboxSelection
          density={'compact'}
        />
```

maybe width in % is related, would be cool if console would warn about that instead if so

```js
  const columns = [
    {field: 'message', headerName: 'Message', width: '70%'},
    {field: 'changesCount', headerName: 'Changes'},
    {
      field: 'createdAt',
      headerName: 'Created',
      valueGetter: (params) => {
        // return params.getValue('createdAt');
        return `aaa`;
      },
    },
  ];

```

**Comment by oliviertassinari** [comment]
@liesislukas Do you have a reproduction? I can't see the issue in https://codesandbox.io/s/material-demo-forked-itbpx?file=/demo.tsx.

**Comment by dtassone** [comment]
`width` is of type number in TS. Not enforced in JS

**Comment by oliviertassinari** [comment]
@liesislukas I have cleaned the issue description so it can be used by other developers [to search](https://github.com/mui-org/material-ui-x/search?q=Warning%3A+NaN+is+an+invalid+value+for+the+width+css+style+property.&type=issues) and find the answer.

@dtassone is right, you get a TypeScript error when using the above:

<img width="612" alt="Screenshot 2021-03-06 at 23 02 01" src="https://user-images.githubusercontent.com/3165635/110222086-0ceba800-7ed0-11eb-8f3b-c3da10077184.png">

---

If you are a developer reading these lines after facing the error:

> Warning: NaN is an invalid value for the width css style property.

and you want us to add a runtime warning in development, please upvote the [issue's description](https://github.com/mui-org/material-ui-x/issues/1137#issue-818196284). I think that if we get more complaints like this, we can add a custom warning in development for non TypeScript users.
