### ISSUE TITLE
[core] Improve packages folder?

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#114]
@dtassone What about we:

- Rename `packages/license` folder -> `packages/x-license-pro` to match package name
- Flatten the `packages/grid` folder to make it easier to navigate the codebase?

**Comment by dtassone** [comment]
> Rename packages/license folder -> packages/x-license to match package name?

Yes.

> Flatten the packages/grid folder to make it easier to navigate the codebase?

I would prefer to keep everything related only to the grid in this folder. So when we add another component, we can do a similar approach. X-license can stay out as it is common to all components.
Storybook should probably go in as it will only be for the grid

**Comment by oliviertassinari** [comment]
> I would prefer to keep everything related only to the grid in this folder.

The reason I find it interesting is that flattening would make it easier to navigate the codebase. The more nested items are, the harder they can be found. No strong preference.

> So when we add another component, we can do a similar approach

I was wondering about that and how it would grow in 6 months. Say we have the TreeView component on the main repository side, and we want to build enterprise features. Where should we put these two? (same reasoning with the data grid, date picker)

- Keeping both in the MIT repository is at odd with the tradeoff to split MIT and enterprise into two different repositories to not have enterprise change the spirit of the MIT core.
- Keeping both in enterprise repository is at odd with the tradeoff to split MIT and enterprise into two different repositories to leverage the benefit of MIT.
- Having them in two repositories makes it a mess to keep them in sync and work on them.

One way to resolve the conflict is to move material-ui-x inside material-ui. A second way is to default to material-ui-x anytime there is such a conflict, a third way is to accept the split of the repository. A hard problem.

> Storybook should probably go in as it will only be for the grid

So we would have one storybook per component? It could make sense. However, wouldn't it be painful to have to start a new docs site anytime you have to review a pull request on a different component?

**Comment by oliviertassinari** [comment]
Another element that came to my attention:

`packages/x-license` vs `packages/material-ui-x-license` as per Babel or the main repository.

**Comment by oliviertassinari** [comment]
Moving the discussion to #2749.
