### ISSUE TITLE
[DataGrid] ColumnMenu does not open when DataGrid is rendered inside Dialog

### ISSUE THREAD

**Issue by FunctionalHacker** [mui-org/material-ui-x#1140]
The ColumnMenu of the DataGrid component is not opening when the component resides inside a Dialog component

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The ColumnMenu does not open

## Expected Behavior 🤔

The ColumnMenu opens

## Steps to Reproduce 🕹

https://codesandbox.io/s/material-ui-issue-latest-forked-5n715?file=/src/Demo.js

I have created two DataGrid components in this example, one outside of the Dialog, one inside the Dialog.

Steps:

1. Try opening the ColumnMenu in the DataGrid visible without opening the dialog (it works)
2. Open the dialog
3. Try opening the ColumnMenu in the DataGrid inside the dialog (it does not work)

## Context 🔦

I want to use the DataGrid component within a m-ui Dialog

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  ```
    System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
    Memory: 1.87 GB / 15.52 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.21.0 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.11 - /usr/bin/npm
  Managers:
    Apt: 2.0.4 - /usr/bin/apt
    Gradle: 4.4.1 - /usr/bin/gradle
    Maven: 3.6.3 - /usr/bin/mvn
    RubyGems: 3.1.2 - /usr/bin/gem
  Utilities:
    Make: 4.2.1 - /usr/bin/make
    GCC: 9.3.0 - /usr/bin/gcc
    Git: 2.25.1 - /usr/bin/git
    Subversion: 1.13.0 - /usr/bin/svn
    FFmpeg: 4.2.4 - /usr/bin/ffmpeg
  Servers:
    Apache: 2.4.41 - /usr/sbin/apachectl
  Virtualization:
    Docker: 20.10.3 - /usr/bin/docker
    VirtualBox: 6.1.16 - /usr/bin/vboxmanage
  IDEs:
    Nano: 4.8 - /usr/bin/nano
    VSCode: 1.53.2 - /snap/bin/code
    Vim: 0.4.3 - /usr/bin/vim
  Languages:
    Bash: 5.0.17 - /usr/bin/bash
    Java: 11.0.10 - /usr/bin/javac
    Perl: 5.30.0 - /usr/bin/perl
    Python3: 3.8.5 - /usr/bin/python3
    Ruby: 2.7.0 - /usr/bin/ruby
  Databases:
    SQLite: 3.31.1 - /usr/bin/sqlite3
  Browsers:
    Chrome: 88.0.4324.182
    Firefox: 86.0
  ```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>
I used Chrome 88.0.4324.182


## Order id 💳

<!--
  The Pro plan comes with priority over the Community/MIT plan.
  Providing your order id will help us give your problem the attention it deserves.
-->
Not applicable, using the MIT version

**Comment by FunctionalHacker** [comment]
Based on [this question in StackOverFlow](https://stackoverflow.com/questions/66343142/material-ui-x-grid-datagrid-default-columnmenu-not-showing) it is a problem with `z-index`. However, I could not find a value for my Dialog that would allow the DataGrid ColumnMenu to be visible

**Comment by FunctionalHacker** [comment]
Duplicate of #844

**Comment by oliviertassinari** [comment]
@FunctionalHacker Feel free to send a pull request with the z-index fix.

**Comment by FunctionalHacker** [comment]
@oliviertassinari I was able to get the ColumnMenu to show up with this CSS:

```
[role='tooltip'],
.MuiDataGridMenu-root,
.MuiDataGridPanel-root {
    z-index: 1300;
}
```

But now the last problem is that all text fields inside of the menu cannot gain focus. For example: opening columnmenu, clicking filter, clicking on the filter value text field, nothing seems to happen. All other inputs, like select dropdowns seem to work. Do you have any ideas on what could be the cause?

**Comment by oliviertassinari** [comment]
> I was able to get the ColumnMenu to show up with this CSS

@FunctionalHacker this solution https://github.com/mui-org/material-ui-x/issues/844#issuecomment-759404094 should be simpler in case you want to contribute it.

> all text fields inside of the menu cannot gain focus

Upgrade to Material-UI v5
