### ISSUE TITLE
[DataGrid] CSV export incorrect if cell data contains comma

### ISSUE THREAD

**Issue by zj9495** [mui-org/material-ui-x#1143]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
![image](https://user-images.githubusercontent.com/17064586/109619518-d3373c00-7b73-11eb-9d46-d91c355d5a37.png)
![image](https://user-images.githubusercontent.com/17064586/109619801-24dfc680-7b74-11eb-9b8b-5ce7205a5f7d.png)

## Expected Behavior 🤔
![image](https://user-images.githubusercontent.com/17064586/109619689-0c6fac00-7b74-11eb-9e45-5f8f18013073.png)

## Steps to Reproduce 🕹

Steps:

1.open https://codesandbox.io/s/material-demo-forked-zdvow?file=/demo.tsx
2.click `Export` -> `Download as CSV`

**Comment by DanailH** [comment]
Hey @zj9495 thanks for catching this, I'll take a look.
