### ISSUE TITLE
[DataGrid] autoPageSize still shows a small vertical scrollbar 

### ISSUE THREAD

**Issue by Tollwood** [mui-org/material-ui-x#1144]
Switching from 4.0.0-alpha.19 to 4.0.0-alpha.21 i noticed that the horizontal + vertical Scrollbar is always shown.

- [x ] The issue is present in the latest release.
- [x ] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

using autoPageSize still shows a really small vertical scrollbar

## Expected Behavior 🤔

Same as in 4.0.0-alpha.19 :) using autoPageSize should not show a scrollbar

## Steps to Reproduce 🕹

Steps:

1. open https://material-ui-x.netlify.app/storybook/?path=/story/x-grid-demos-playground--commodity-500
2. select autoPageSize to true
3. Scroll bar is still visible

## Context 🔦

I want to display data-grid without vertical scrollbar.

## Your Environment 🌎
tested in chrome
<details>
  <summary>`npx @material-ui/envinfo`</summary>

  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Browsers:
    Chrome: 88.0.4324.192
    Edge: Not Found
    Firefox: 84.0.2
    Safari: 14.0.2
  npmPackages:
    @material-ui/core: ^4.11.3 => 4.11.3 
    @material-ui/data-grid: 4.0.0-alpha.21 => 4.0.0-alpha.21 
    @material-ui/icons: ^4.11.2 => 4.11.2 
    @material-ui/lab: ^4.0.0-alpha.57 => 4.0.0-alpha.57 
    @material-ui/pickers: ^3.2.10 => 3.2.10 
    @material-ui/styles:  4.11.3 
    @material-ui/system:  4.11.3 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @types/react: ^16.9.0 => 16.14.4 
    react: 17.0.1 => 17.0.1 
    react-dom: 17.0.1 => 17.0.1 
    typescript: ^3.9.5 => 3.9.9 
</details>

**Comment by oliviertassinari** [comment]
We can see it too in https://material-ui.com/components/data-grid/pagination/#auto-size.

**Comment by oliviertassinari** [comment]
It was broken in v4.0.0-alpha.21.

**Comment by oliviertassinari** [comment]
It was broken in #1071

**Comment by dtassone** [comment]
that a simple one to catch with the argos test
