### ISSUE TITLE
Provide way to pass custom type props to CustomToolBar (avoid any type)

### ISSUE THREAD

**Issue by Javaman44** [mui-org/material-ui-x#1149]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡
When i set a custom toolbar with custom props eslint complain about typing. 

```
    export function CustomToolbar(props: GridBaseComponentProps & { isVisible: boolean }) {
        const classes = useToolbarStyles();
       
        return (
            <Collapse in={props.isVisible}>
                <GridToolbarContainer className={classes.root}>
                    <GridColumnsToolbarButton />
                    <GridFilterToolbarButton />
                    <GridDensitySelector />
                    <GridToolbarExport />
                </GridToolbarContainer>
            </Collapse>
        );
     }
```
![image](https://user-images.githubusercontent.com/9351983/109789061-37a7d900-7c10-11eb-9d70-686e217dd362.png)

When i pass an any type, it works but i think it will better to avoid any type in this case:

```
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function CustomToolbar(props: any) { 
    const classes = useToolbarStyles();
    const propsTyped = props as GridBaseComponentProps & { isVisible: boolean };
  
    return (
        <Collapse in={propsTyped.isVisible}>
            <GridToolbarContainer className={classes.root}>
                <GridColumnsToolbarButton />
                <GridFilterToolbarButton />
                <GridDensitySelector />
                <GridToolbarExport />
            </GridToolbarContainer>
        </Collapse>
    );
}
```

## Motivation 🔦
To be able to hide / show toolbar with transition

**Comment by DanailH** [comment]
Hi @Javaman44 thanks for raising this. I quickly checked the code and it seems that this is a problem all component slots have. @oliviertassinari @dtassone we would need to allow the passing of custom props in the component slots.

**Comment by dtassone** [comment]
If you make `isVisible` optional it should work.

**Comment by Javaman44** [comment]
> If you make `isVisible` optional it should work.

Thanks, i confirm it work. But it look like a little bit hacky :), no ? (i am not an typescript expert)

**Comment by dtassone** [comment]
Well it's convenient. Otherwise we would have had to use generics in `GridSlotsComponent` 🤔

**Comment by oliviertassinari** [comment]
In the core components, we solve this problem by leaving the accepted props blank:

https://github.com/mui-org/material-ui/blob/7381da75a2a7eb9625bca698a783993cfaa528e6/packages/material-ui-unstyled/src/SliderUnstyled/SliderUnstyled.d.ts#L80

Developers can provide whatever they want. Not a great solution either.
