### ISSUE TITLE
[DataGrid] First page ignored/no longer shown when using pagination

### ISSUE THREAD

**Issue by consDev** [mui-org/material-ui-x#1152]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

I am working with the latest material-ui data-grid package alongside with the custom pagination provided by material-ui and bundling them together as [the tutorial](https://material-ui.com/components/data-grid/rendering/#footer) suggests.
I found a bug that is present in the [tutorial example](https://codesandbox.io/s/kezzb).
 The problem is that you can not view first part of your data injected to the grid when using pagination. Consider our rows are like:
`
const rows = [{name: 'Jack'}, {name: "Mike"}, {name: "James"}, {name: "Jim"}]
`
and `pageSize` prop sent to `DataGrid` is `2`.

In this case, Jack and Mike will be shown first time around you see the rendered table and the moment you manipulate pagination(change page) they are no longer visible/available.

I guess that root of the bug is ` props: { state: { pagination: { page }}}` that is starting from zero.
## Expected Behavior 🤔
First part of chunked data shouldn't get disappeared forever when using pagination.

## Steps to Reproduce 🕹
I hope above description explains the problem.

## Your Environment 🌎
System:
OS: Linux Ubuntu 20.04.2

Binaries:
Node: 14.15.4 

Browsers:
Google Chrome: Version 88.0.4324.182 (Official Build) (64-bit)

**Comment by dtassone** [comment]
Page starts at 0 now, it's 0 index based

**Comment by consDev** [comment]
Alright but the problem still persists.

**Comment by oliviertassinari** [comment]
@consDev Do you want to fix the demo in the documentation?

```diff
diff --git a/docs/src/pages/components/data-grid/rendering/CustomPaginationGrid.tsx b/docs/src/pages/components/data-grid/rendering/CustomPaginationGrid.tsx
index f6e27f79..f99b799c 100644
--- a/docs/src/pages/components/data-grid/rendering/CustomPaginationGrid.tsx
+++ b/docs/src/pages/components/data-grid/rendering/CustomPaginationGrid.tsx
@@ -18,9 +18,9 @@ function CustomPagination(props: GridBaseComponentProps) {
     <Pagination
       className={classes.root}
       color="primary"
-      page={state.pagination.page}
+      page={state.pagination.page + 1}
       count={state.pagination.pageCount}
-      onChange={(event, value) => api.current.setPage(value)}
+      onChange={(event, value) => api.current.setPage(value - 1)}
     />
   );
 }
```

**Comment by consDev** [comment]
@oliviertassinari Thanks for the solution. We are using the combination for a demo product and this solves the issue.

**Comment by oliviertassinari** [comment]
@consDev Cool, I have added a "good first issue" label, in case somebody wants to make a first contribution to the documentation.

**Comment by consDev** [comment]
@oliviertassinari I'll be more than happy to do the contribution and embark on the journey if that's Ok.
