### ISSUE TITLE
[DataGrid]  Module has no exported member 'useGridApiRef'.

### ISSUE THREAD

**Issue by efreethy** [mui-org/material-ui-x#1160]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Module build error: Mode has no exported member 'useGridApiRef'.

## Expected Behavior 🤔

No errors

## Steps to Reproduce 🕹
**Important** - you must import the distribution of x-grid published on npm - not your local development copy

Ensure package.json contains
```    "@material-ui/x-grid": "4.0.0-alpha.20",```

Then attempt to import _and use_
```import { XGrid, useGridApiRef } from '@material-ui/x-grid';```

**Comment by efreethy** [comment]
This is resolved in version `4.0.0-alpha.21`

**Comment by oliviertassinari** [comment]
Duplicate of #1164
