### ISSUE TITLE
[XGrid] Disable reordering on a specific column

### ISSUE THREAD

**Issue by efreethy** [mui-org/material-ui-x#1161]
First off: great work with this product. 

I have a custom checkbox column - I am not using the checkbox built ins. This column should not be reorderable, however there is no ColDef option to specify that. The other areas of column functionality are optional (resizable, sortable, etc). It makes sense to also have a "reorderable"  col def option.

**Comment by DanailH** [comment]
Hi, @efreethy thanks for raising this. When we were working on the column reorder feature we were considering that case. Our argument of now adding it was that even if you make one column not reorderable you could still reorder the columns around it which will indirectly move your non-reordarable column so it won't truly be non-reorderable.

I'm interested to hear your thoughts on this?

**Comment by efreethy** [comment]
thanks for the quick response @DanailH 

I imagine a non-reorderable column as essentially a pinned column. When such a column is involved as a subject in a reorder - its ordinal position is not allowed to change, therefore the ordinal positions of all the other columns would rotate around it.

**Comment by oliviertassinari** [comment]
> even if you make one column not reorderable you could still reorder the columns around it which will indirectly move your non-reordarable column so it won't truly be non-reorderable.

@DanailH We should be cautious here. There are two different concepts. 1. Is the column draggable? 2. Is the position of the column fixed? ag-Grid [illustrates](https://ag-grid.com/documentation/javascript/column-moving/#suppress-movable--lock-position-example) the notion well.

**Comment by oliviertassinari** [comment]
As far as I understand the pain:

- We can update the column def with:

```tsx
  /**
   * If `true`, the column cannot be dragged for reordering.
   */
  disableReorder?: boolean;
  ```
  
  Its name matches the name of the global flag: `disableColumnReorder`.
  
- We can update the column def with:

```tsx
  /**
   * If `true`, the position of the column is locked. Reordering can't change it.
   */
  lockPosition?: boolean;
  ```
  
This should both impact the header dragging feature and the column selector reorder: #839.

**Comment by oliviertassinari** [comment]
> I am not using the checkbox built-in

@efreethy Out of curiosity, why?
