### ISSUE TITLE
[DataGrid] The CSS customization section is misleading

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#1163]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

1. The "implementation of the component style " link in https://material-ui.com/api/data-grid/#css is a 404
2. The data grid fails the classes prop conformance: https://codesandbox.io/s/material-demo-forked-6n2eu?file=/demo.tsx

<img width="552" alt="Screenshot 2021-03-04 at 11 00 24" src="https://user-images.githubusercontent.com/3165635/109946727-d7309e80-7cd8-11eb-9f2e-85e015017bd7.png">

## Expected Behavior 🤔

1. A working link
2. A working classes prop

## Context 🔦

The issue was reported by a user under the wrong channel (x@material-ui.com).

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

## Order id 💳

21793

**Comment by holdenmatt** [comment]
I also just hit this trying to add `classes` to a `DataGrid` and found this issue.

I'll use global CSS as a workaround for now, but am otherwise using CSS modules so having a working `classes` prop would be great!

**Comment by oliviertassinari** [comment]
@holdenmatt We only plan to include `classes.root` as the data grid relies heavily on one level descendant CSS selectors. Would it work for you?

**Comment by holdenmatt** [comment]
I'm adding some CSS to customize a few classes like `.MuiDataGrid-cell` and `.MuiDataGrid-columnSeparator`.
AFAIK, I can't do that using only `className` or `classes.root`?

I ended up using a global SCSS file with nested selectors, which works fine. Slight preference for having a method that would let me define scoped styles with my component rather than globally. But if not, this works fine.

**Comment by oliviertassinari** [comment]
@holdenmatt Correct. If you are used to CSS modules, you could still apply the root class name to the root of the data grid, and then, use global descendant CSS selectors to target what you need. For instance, to get something like this at the end:

```css
.a12vt .MuiDataGrid-cell {
  background-color: red;
}
```

```jsx
<DataGrid className="a12vt" />
```

**Comment by oliviertassinari** [comment]
I have added the "good to take" label as the solution should be as simple as

1. Replacing https://github.com/mui-org/material-ui-x/blob/master/packages/grid/_modules_/grid/components/styled-wrappers/GridRootStyles.ts with the correct URL.
1. Adding a `classes` prop with a single root key. This is for consistency with the other components.
