### ISSUE TITLE
[XGrid] useApiRef documentation codesandbox crashes: xGrid.useApiRef is not a function

### ISSUE THREAD

**Issue by bryyytl** [mui-org/material-ui-x#1164]
## Current Behavior 😯
After trying both Chrome (88.0.4324.190) and Firefox (85.0.2), I have noticed that the Codesandbox for https://material-ui.com/components/data-grid/rows/#apiref appears to be broken. The console error that I'm currently seeing says 
"TypeError: (0 , _xGrid.useApiRef) is not a function"

![Material demo - CodeSandbox - Google Chrome 3_4_2021 8_17_19 AM](https://user-images.githubusercontent.com/78176335/109969693-30d99e80-7cc2-11eb-9d0c-bf2bcd1b81be.png)

## Expected Behavior 🤔
Example on Codesandbox should be able to load and display a live example of the demo listed on the website.

![Data Grid - Rows - Material-UI - Google Chrome 3_4_2021 8_14_19 AM](https://user-images.githubusercontent.com/78176335/109969413-dd675080-7cc1-11eb-8d12-0d4d0137f3d9.png)

**Comment by efreethy** [comment]
@bryyytl are you passing `apiRef` into the GridComponent?

**Comment by bryyytl** [comment]
The example imports useGridApiRef from '@material-ui/x-grid', instantiates a reference to it (the example refers to it as "apiRef"), and then passes "apiRef" to the XGrid component.

For ease of reference, here's the code provided by the Codesandbox example found https://material-ui.com/components/data-grid/rows/#apiref:

```javascript
import * as React from 'react';
import { XGrid, useGridApiRef } from '@material-ui/x-grid';
import { interval } from 'rxjs';
import { randomInt, randomUserName } from '@material-ui/x-grid-data-generator';

const columns = [
  { field: 'id' },
  { field: 'username', width: 150 },
  { field: 'age', width: 80, type: 'number' },
];

const rows = [
  { id: 1, username: randomUserName(), age: randomInt(10, 80) },
  { id: 2, username: randomUserName(), age: randomInt(10, 80) },
  { id: 3, username: randomUserName(), age: randomInt(10, 80) },
  { id: 4, username: randomUserName(), age: randomInt(10, 80) },
];

export default function ApiRefRowsGrid() {
  const apiRef = useGridApiRef();

  React.useEffect(() => {
    const subscription = interval(200).subscribe(() => {
      apiRef.current.updateRows([
        {
          id: randomInt(1, 4),
          username: randomUserName(),
          age: randomInt(10, 80),
        },
        {
          id: randomInt(1, 4),
          username: randomUserName(),
          age: randomInt(10, 80),
        },
      ]);
    });

    return () => {
      subscription.unsubscribe();
    };
  }, [apiRef]);

  return (
    <div style={{ height: 400, width: '100%' }}>
      <XGrid rows={rows} columns={columns} apiRef={apiRef} />
    </div>
  );
}
```

I think the issue may have to do with how useGridApiRef() is exported from @material-ui/x-grid.

**Comment by oliviertassinari** [comment]
@bryyyt See the breaking changes introduced in v4.0.0-alpha.21: https://github.com/mui-org/material-ui-x/releases/tag/v4.0.0-alpha.21. Codesandbox has a cache, you were using v4.0.0-alpha.20.
