### ISSUE TITLE
[DataGrid] Implementation of isEmpty and DoesNotContain filters

### ISSUE THREAD

**Issue by jamintz** [mui-org/material-ui-x#1165]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡
Add default functionality to filter search operators to perform isEmpty / isNotEmpty and DoesNotContain, similar to Airtable behavior.

## Examples 🌈
<img width="420" alt="Screen Shot 2021-03-04 at 10 13 48 AM" src="https://user-images.githubusercontent.com/3538254/109985062-5d95b200-7cd2-11eb-93ce-e2157198f6db.png">

## Motivation 🔦

Commonly used filter in Airtable, especially helpful to be able to filter empty/null cells

## Order id 💳
21172

**Comment by oliviertassinari** [comment]
@jamintz Note that we document how to customize the string filter to support this: https://material-ui.com/components/data-grid/filtering/#custom-filter-operator.

```jsx
import * as React from "react";
import {
  DataGrid,
  getGridStringOperators,
  GridFilterItem,
  GridColDef,
  GridPreferencePanelsValue,
  GridFilterInputValue
} from "@material-ui/data-grid";
import { useDemoData } from "@material-ui/x-grid-data-generator";

const filterModel = {
  items: [{ columnField: "name", value: "Andrew", operatorValue: "noContain" }]
};

export default function ExtendNumericOperator() {
  const { data } = useDemoData({ dataSet: "Employee", rowLength: 100 });
  const columns = [...data.columns];

  if (columns.length > 0) {
    const ratingColIndex = columns.findIndex((col) => col.field === "name");

    columns[ratingColIndex] = {
      ...columns[ratingColIndex],
      filterOperators: [
        ...getGridStringOperators(),
        {
          value: "noContain",
          getApplyFilterFn: (
            filterItem: GridFilterItem,
            column: GridColDef
          ) => {
            if (
              !filterItem.columnField ||
              !filterItem.value ||
              !filterItem.operatorValue
            ) {
              return null;
            }

            const filterRegex = new RegExp(filterItem.value, "i");
            return (params): boolean => {
              const rowValue = column.valueGetter
                ? column.valueGetter(params)
                : params.value;
              return !filterRegex.test(rowValue?.toString() || "");
            };
          },
          InputComponent: GridFilterInputValue
        }
      ]
    };
  }
  return (
    <div style={{ height: 400, width: "100%" }}>
      <DataGrid
        rows={data.rows}
        columns={columns}
        localeText={{
          "filterOperatorNoContain": "does not contain"
        }}
        filterModel={filterModel}
        state={{
          preferencePanel: {
            open: true,
            openedPanelValue: GridPreferencePanelsValue.filters
          }
        }}
      />
    </div>
  );
}

```

https://codesandbox.io/s/material-demo-forked-kl0er?file=/demo.tsx

However, @dtassone, I have found the following pains in the process:

1. I had to extend the types of `localeText`. However, TypeScript doesn't allow me to. Should we update the type to accept extra keys?
2. Developers have to redo the `valueGetter` logic. This doesn't seem right.
3. `if (!filterItem.columnField || !filterItem.value || !filterItem.operatorValue) {` is repeated 17 times in the codebase. Why is the not shared between all the filter operators?

**Comment by jamintz** [comment]
@m4theushw @oliviertassinari the implementation of this is great, thank you – but could it be added for all filter types? Currently it works for strings and dates, but is not available for numbers. Thanks!

**Comment by oliviertassinari** [comment]
@jamintz Please provide a reproduction, AFAIK it works with numbers: https://material-ui.com/components/data-grid/columns/#column-types

**Comment by oliviertassinari** [comment]
> AFAIK it works with numbers

Arf no, it's something else, we had a regression.

**Comment by oliviertassinari** [comment]
The issue can be reproduced on https://material-ui.com/components/data-grid/columns/#column-types

<img width="570" alt="Capture d’écran 2021-07-29 à 16 31 42" src="https://user-images.githubusercontent.com/3165635/127510705-29b8f343-9fcb-40d0-8499-2ce2e4c246ed.png">

vs. 

<img width="432" alt="Capture d’écran 2021-07-29 à 16 32 46" src="https://user-images.githubusercontent.com/3165635/127510884-f4e861b7-5d41-406e-8ff6-964780ae15a3.png">

**Comment by AlopezGraph** [comment]
Hi Guys, I would like to know if in the latest MUI version is this localeText type available: 

- filterOperatorIsNullOrNot

![Screen Shot 2022-05-19 at 15 29 02](https://user-images.githubusercontent.com/85120593/169407737-cd0c84a9-560a-4b21-8e52-8170a902d95f.png)

since I'm getting the error above.

I'm using MUI data grid version: ^5.11.0

Hope you guys help me with that. Thanks

**Comment by flaviendelangle** [comment]
Hi, no we  don't have a key named `filterOperatorIsNullOrNot`
Where did you find this key ?

**Comment by flaviendelangle** [comment]
> I have another issue after create the custom operator, should create a new issue ticket explaning the error?

Yes please

___

For this issue, was your problem that the grid crashes when trying to access the locale of a custom operator ?
If so, I have the same problem in #4208, I think it's weird to have the typing saying that the `label` property of the operator is  optional but everything will likely crash when you don't provide it.

**Comment by AlopezGraph** [comment]
@flaviendelangle not exactly, the grid still working after a custom operator has been added, I created my issue [here](https://github.com/mui/mui-x/issues/4951)
