### ISSUE TITLE
<DataGrid/> onSelectionChange won't pass it to the state when selecting check boxes @material-ui/data-grid 4.0.0-alpha.21 

### ISSUE THREAD

**Issue by eralpkor** [mui-org/material-ui-x#1166]
4.0.0-alpha.21 version of data-grid onSelectionChange won't render with selected check boxes.

- [ ] The issue is present in the latest release.
- [ ] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

```jsx
onSelectionChange={(newSelection) => {
                setData(newSelection.rowIds);
              }}
              {...data}
```

Selections are not added to the `data` array. 

## Expected Behavior 🤔
Multiple or single row selection should be able to added to the state so user can take action with.

## Steps to Reproduce 🕹

https://codesandbox.io/s/mat-ui-datagrid-ochjr?file=/src/App.js
Steps:

1. Install Material-UI core, @material-ui/data-grid ^4.0.0-alpha.21 latest
2. Create sample data
3. Render the `DateGrid` as seen on the codesandbox and pass checkboxes to state
4. I don't see this issue with `^4.0.0-alpha.13`

## Context 🔦
I was trying to collect checkbox elements to as state and delete checked rows.

## Your Environment 🌎
 

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 12.18.2 - C:\Program Files\nodejs\node.EXE       
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 88.0.4324.182
    Edge: Spartan (44.19041.423.0), Chromium (88.0.705.81)
  npmPackages:
    @material-ui/core: ^4.11.2 => 4.11.2
    @material-ui/data-grid: ^4.0.0-alpha.21 => 4.0.0-alpha.21
    @material-ui/icons: ^4.11.2 => 4.11.2
    @material-ui/styles:  4.11.2
    @material-ui/system:  4.11.2
    @material-ui/types:  5.1.0
    @material-ui/utils:  4.11.2
    @types/react:  17.0.0
    react: ^17.0.1 => 17.0.1
    react-dom: ^17.0.1 => 17.0.1
```
</details>

**Comment by tarochipz** [comment]
`onSelectionChange` prop has been renamed to `onSelectionModelChange` : https://github.com/mui-org/material-ui-x/pull/986

**Comment by oliviertassinari** [comment]
@tarochipz Thanks for the help. Yes, it's documented in https://material-ui.com/components/data-grid/selection/#controlled-selection. https://codesandbox.io/s/mat-ui-datagrid-forked-uv130?file=/package.json:236-250
