### ISSUE TITLE
[DataGrid] onRowClick and onCellClick fired when the cell text selected through click and drag

### ISSUE THREAD

**Issue by AnoopChillayi** [mui-org/material-ui-x#1172]
The click events are fired when a cell item simply selected for copy-pasting purposes. 
Please see the below image. If a release the mouse then the click event will fired
![issue](https://user-images.githubusercontent.com/6807834/110081138-7de86e00-7db1-11eb-80b4-f748217e0edf.png)

**Comment by oliviertassinari** [comment]
A reproductin: https://codesandbox.io/s/material-demo-forked-1iq76?file=/demo.tsx. This is how a native click event behaves. It's expected. What are you looking for building as an interaction?

**Comment by oliviertassinari** [comment]
I'm closing as it's a generic question with the web platform. As a workaround, you can check `window.getSelection().type`. If it's `'Range'`, ignore the event.
