### ISSUE TITLE
useApiRef dissapeared/renamed between v4.0.0-alpha.20 & v4.0.0-alpha.20

### ISSUE THREAD

**Issue by jamshally** [mui-org/material-ui-x#1190]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

It seems like a breaking change was introduced. useApiRef is no longer available. I note that there is a useGridApiRef which I assume can be used it its place. If this is the only different, then possibly just the documentation needs updating. 

## Context 🔦

Using the apiRef to set selected checkboxes in a grid

## Your Environment 🌎

  System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 15.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.0.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 88.0.4324.190
    Edge: Spartan (44.18362.449.0)
  
## Other Things
XGrid is a fantastic component. Keep up the good work

**Comment by oliviertassinari** [comment]
@jamshally The the migration path in #1069. ~useApiRef~ -> useGridApiRef is indeed correct.
