### ISSUE TITLE
[DataGrid] getRowId causes an object clone

### ISSUE THREAD

**Issue by bobsys-mfleischer** [mui-org/material-ui-x#1200]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

If getRowId is used, object clones are returned in the events.

## Expected Behavior 🤔

Original objects should be returned.

## Steps to Reproduce 🕹

Behavior with getRowId:
https://codesandbox.io/s/fragrant-cloud-qb5j8?file=/src/App.tsx

Behavior without getRowId
https://codesandbox.io/s/busy-heyrovsky-wtn1z?file=/src/App.tsx

When a row is clicked, the array is searched for the rowData object.
In the case of getRowId nothing is found.

**Comment by oliviertassinari** [comment]
It's also related to #1119.
