### ISSUE TITLE
XGrid scrolling on mobile crashes.

### ISSUE THREAD

**Issue by bluefeversoft** [mui-org/material-ui-x#1242]
XGrid scrolling on mobile crashes.

Hi, I'm not sure if this is the right place as I could not find the support contact.

## Order id 21686

I'm using:
"@material-ui/core": "^4.11.3",
"@material-ui/data-grid": "^4.0.0-alpha.20",
"@material-ui/icons": "^4.11.2",
"@material-ui/lab": "^4.0.0-alpha.57",
"@material-ui/x-grid": "^4.0.0-alpha.20",
"react": "^17.0.1",

I load a table with 11 rows into XGrid, with fixed width columns.

When I use the app on a mobile device or in the browser, it crashes when scrolling. It happens on my Nokia 7.2, iPhone 7, and iPhone 6 emulator in Firefox.

It does not happen on an iPad.

Here is a video of the error:

https://user-images.githubusercontent.com/36438496/111279466-04674000-863b-11eb-8069-88bb5cbabdd2.mp4

Thank you.

**Comment by bluefeversoft** [comment]
To follow up on the above, I've noticed the issue is only in tables with cells where I make a custom render.

This makes me think I've made an error with that.

**Comment by bluefeversoft** [comment]
Ok, it was my fault not using a custom component correctly in the renderCell() part of the columns definitions. Sorry about that!

**Comment by oliviertassinari** [comment]
@bluefeversoft Thanks for the update. If you have a reproduction, we could potentially look into how to improve the error message. It sounds be clearer what's the origin of the issue.
