### ISSUE TITLE
[DataGrid] Last row cut with autoHeight=true, density="comfortable"

### ISSUE THREAD

**Issue by Nallefjant** [mui-org/material-ui-x#1243]
If you set autoHeight = true and density = "comfortable" the last row will not be fully visible (using 27 rows).

`@material-ui/data-grid@4.0.0-alpha.22`

**Comment by oliviertassinari** [comment]
@Nallefjant Do you mean that the scrollbar cuts the last row? 

I can reproduce this in https://codesandbox.io/s/material-demo-forked-j0n7x?file=/demo.tsx

<img width="381" alt="Screenshot 2021-03-16 at 22 55 57" src="https://user-images.githubusercontent.com/3165635/111385271-d28dc200-86aa-11eb-98e0-6e4390e80cc1.png">
