### ISSUE TITLE
[DataGrid] Remove onAction from apiRef (not from props)

### ISSUE THREAD

**Issue by dtassone** [mui-org/material-ui-x#1244]
## Summary 💡

It feels redundant to put handlers on `apiRef` as well as on the component props. 
I suggest we remove all those handlers of `apiRef`.
And we set handlers using props. 

If you need to do something more exotic, then you can use apiRef to subscribe to an event as below

```
apiRef.current.subscribeEvent(eventName, handler);
```

## Motivation 🔦

Avoid redundant api.

**Comment by oliviertassinari** [comment]
@dtassone Could you expand on the public API implications? The issue has a "breaking change" label, but doesn't explain how it's a breaking change.

**Comment by dtassone** [comment]
it's a breaking change as we will remove api methods. Probably not that used as you would use the prop instead.
ie `onRowSelected`

Today you can add handlers to onRowSelected in 2 ways
```tsx
useEffect(()=> {
  apiRef.current.onRowSelected(doSomething);
}, [apiRef]);
<XGrid onRowSelected={doSomething} />

```tsx
If we do this change and remove handlers on apiRef, you'll have only 1 easy way left
```
<XGrid onRowSelected={doSomething} />

```
But you could also do, in really special cases.
```tsx
useEffect(()=> {
  apiRef.current.subscribeEvent('rowSelected', doSomething);
}, [apiRef]);
```
So you can still do the same but we avoid the maintenance cost of the handlers on apiRef. ATM we are inconsistent, with the props.
2. ApiRef lets you manipulate the grid so we are still in this vision.
3. Main advantage is to save on maintenance costs and avoid inconsistencies.

**Comment by oliviertassinari** [comment]
1. Ok so to summarize the developers implication is:

```diff
-React.useEffect(()=> {
-  apiRef.current.onRowSelected(doSomething);
-}, [apiRef]);
+apiRef.current.subscribeEvent(GRID_ROW_SELECTED, doSomething);

<XGrid onRowSelected={doSomething} />
```

Much better, they were definition two different ways to do the exact same thing 👍

**Comment by oliviertassinari** [comment]
I have added it the proposal to the beta milestone as it seems we need to resolve this discussion for such milestone.
