### ISSUE TITLE
hiding a column will cause the page to scroll to the bottom

### ISSUE THREAD

**Issue by jessq** [mui-org/material-ui-x#1245]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
When you toggle column visibility from the toolbar, the screen will suddenly jump to the bottom of the page.

## Expected Behavior 🤔
It should not jump, and the page should remain anchored.

## Steps to Reproduce 🕹

Steps:

1. Go to https://material-ui.com/components/data-grid/filtering/#toolbar
2. Click on "Columns" in the toolbar
3. Toggle one of the columns to be hidden
I can reproduce locally as well.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

**Comment by dtassone** [comment]
duplicate #1148

**Comment by oliviertassinari** [comment]
@dtassone GitHub has a very matter matching trigger for labeling duplicates. With the following, the bot, should automatically handle the label:

**Comment by oliviertassinari** [comment]
Duplicate of #1148
