### ISSUE TITLE
[DataGrid] Modules we missed in #169

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#1260]
I have found a few modules that we seem to have missed in #169. I have found them in #1212 (listing the public API).

## Current Behavior 😯

- ColumnHeaderSortIconProps -> GridColumnHeaderSortIconProps
- ColumnMenuState -> GridColumnMenuState
- ColumnReorderState -> GridColumnReorderState
- ComponentsApi -> GridComponentsApi
- ElementSize -> should be private?
- FilterInputValueProps -> GridFilterInputValueProps
- FilterItemProps -> GridFilterItemProps
- FilterModelState -> GridFilterModelState
- InternalGridRowsState -> should be private?
- KeyboardState -> GridKeyboardState
- MenuProps -> GridMenuProps
- ObjectWithId -> GridObjectWithId
- PaginationState -> GridPaginationState
- RowProps -> GridRowProps
- TypeFilterInputValueProps -> GridTypeFilterInputValueProps
- TranslationKeys -> GridTranslationKeys
- PaginationActions -> GridPaginationActions

## Expected Behavior 🤔

A global namespace

**Comment by DanailH** [comment]
I need to check. I didn't rename all of them, only the ones that were exported/listed as public API.

**Comment by oliviertassinari** [comment]
I have rebased #1212 on master. To see what could be left. I have noticed:

- `ElementSize`, maybe we should prefix with Grid or Internal
- `FilterColumnLookup`
- `Localization`, won't this conflict with the other components?

Can't find anythingelse
