### ISSUE TITLE
Server side pagination not working in IE and MS Edge

### ISSUE THREAD

**Issue by yfkoenig** [mui-org/material-ui-x#1278]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Second page not loading in IE 11 and MS Edge, but in chrome it works.

## Expected Behavior 🤔

Pagination should work correctly in IE 11 and MS Edge too

## Steps to Reproduce 🕹

https://github.com/mui-org/material-ui-x/blob/master/docs/src/pages/components/data-grid/pagination/ServerPaginationGrid.tsx

https://github.com/mui-org/material-ui-x/issues/568

https://github.com/mui-org/material-ui-x/issues/639

Steps:

1. Use create-react-app template to create a new react project
2. Copy ServerPaginationGrid.tsx file into the project and add this component ServerPaginationGrid under App directly
3. Run npm install, run build and then start the app
4. The first page of example data displays correctly in IE 11 and MS Edge, click on next button, the second page isn't loading. Error message displays in browser console.

![Second page not loading in IE and Edge](https://user-images.githubusercontent.com/81202276/112080401-39671b80-8b82-11eb-8c04-0c6733835a90.JPG)

## Context 🔦

![App](https://user-images.githubusercontent.com/81202276/112080854-f8233b80-8b82-11eb-9c33-3990fa7b4e42.JPG)

## Your Environment 🌎

4.0.0-alpha.22

IE 11 and Microsoft Edge

**Comment by oliviertassinari** [comment]
*I'm answering as it wasn't for over 24h.*

@yfkoenig We don't support IE 11 for new components, see https://next.material-ui.com/getting-started/supported-platforms/#ie-11. We support Edge from v85 and above. Which version did you use to test?

**Comment by yfkoenig** [comment]
@oliviertassinari I'm using an office workstation so the Edge version is old. But thank you for reminding me that info.

**Comment by oliviertassinari** [comment]
Thanks for the clarification
