### ISSUE TITLE
SCRIPT438: Object doesn't support property or method 'closest'

### ISSUE THREAD

**Issue by rusaym** [mui-org/material-ui-x#1285]
On the IE11 `DataGrid` renders not correctly and there are errors on the console. 

## Current Behavior 😯

![image](https://user-images.githubusercontent.com/17137916/112306660-18511880-8cb1-11eb-8ae9-62c087ec504e.png)

## Expected Behavior 🤔

![image](https://user-images.githubusercontent.com/17137916/112306761-3454ba00-8cb1-11eb-920c-fc1734f8fce3.png)

## Steps to Reproduce 🕹

Steps:

1. Create new react-app
2. Add `import 'core-js'` to your index.js
3. Add `DataGrid` component from examples
4. Run your app

## Your Environment 🌎
IE 11

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  npx: installed 2 in 5.46s

  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.90
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.57)
  npmPackages:
    @material-ui/core: ^4.11.3 => 4.11.3
    @material-ui/data-grid: ^4.0.0-alpha.21 => 4.0.0-alpha.21
    @material-ui/icons: ^4.11.2 => 4.11.2
    @material-ui/lab: ^4.0.0-alpha.57 => 4.0.0-alpha.57
    @material-ui/pickers: ^3.3.10 => 3.3.10
    @material-ui/styles: ^4.11.3 => 4.11.3
    @material-ui/system:  4.11.3
    @material-ui/types:  5.1.0
    @material-ui/utils:  4.11.2
    @types/react:  17.0.3
    react: ^17.0.1 => 17.0.1
    react-dom: ^17.0.1 => 17.0.1
```
</details>

**Comment by dtassone** [comment]
We don't support IE 11 for new components, see the policy in https://next.material-ui.com/getting-started/supported-platforms/#ie-11. We support Edge from v85 and above.
