### ISSUE TITLE
[DataGrid] Remove disableClickEventBubbling,  as you can use event.stopPropagation

### ISSUE THREAD

**Issue by dtassone** [mui-org/material-ui-x#1296]
We can now remove this prop as it is only useful for clicks and it does not really scale for all the other events. 
If you want to stop the click propagation, you can call `event.stopPropagation`

```diff
-<DataGrid disableClickEventBubbling />
+<DataGrid onCellClick={(event)=> event.stopPropagation}/>
```

relate #947

**Comment by oliviertassinari** [comment]
onCellClick no?

**Comment by oliviertassinari** [comment]
A counter-proposal: #1403
