### ISSUE TITLE
[DataGrid] disableColumnSelector should also remove "Hide" MenuItem

### ISSUE THREAD

**Issue by lvauvillier** [mui-org/material-ui-x#1306]
## Current Behavior 😯

When disableColumnSelector is set, the column menu still has a "Hide" item.
If we hide a column, there is no way to make it shown again.

## Expected Behavior 🤔

When disableColumnSelector is set, the "Hide" item is also removed from the column menu.

## Reproduction

https://codesandbox.io/s/material-demo-forked-fu2wb?file=/demo.tsx

## Version

4.0.0-alpha.23

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

**Comment by zehawki** [comment]
Yes, it would be good if this is fixed - its a minor annoyance to have a hide without a corresponding unhide.

**Comment by oliviertassinari** [comment]
@lvauvillier Thanks for reporting the issue. Do you want to work on a fix? It should be as simple as:

```diff
diff --git a/packages/grid/_modules_/grid/components/menu/columnMenu/HideGridColMenuItem.tsx b/packages/grid/_modules_/grid/components/menu/columnMe
nu/HideGridColMenuItem.tsx
index 606d20f2..1be0b650 100644
--- a/packages/grid/_modules_/grid/components/menu/columnMenu/HideGridColMenuItem.tsx
+++ b/packages/grid/_modules_/grid/components/menu/columnMenu/HideGridColMenuItem.tsx
@@ -1,10 +1,13 @@
 import * as React from 'react';
 import MenuItem from '@material-ui/core/MenuItem';
+import { useGridSelector } from '../../../hooks/features/core/useGridSelector';
+import { optionsSelector } from '../../../hooks/utils/optionsSelector';
 import { GridApiContext } from '../../GridApiContext';
 import { FilterItemProps } from './FilterItemProps';

 export const HideGridColMenuItem: React.FC<FilterItemProps> = ({ column, onClick }) => {
   const apiRef = React.useContext(GridApiContext);
+  const options = useGridSelector(apiRef, optionsSelector);
   const timeoutRef = React.useRef<any>();

   const toggleColumn = React.useCallback(
@@ -21,7 +24,7 @@ export const HideGridColMenuItem: React.FC<FilterItemProps> = ({ column, onClick
     return () => clearTimeout(timeoutRef.current);
   }, []);

-  if (!column) {
+  if (options.disableColumnSelector) {
     return null;
   }
```

**Comment by nemonemi** [comment]
@oliviertassinari,
I see the same issue in the DataGrid.

I'll happily make the same change for the DataGrid, but I would appreciate it if you could point me in the correct direction where to make these changes.
