### ISSUE TITLE
Please consider not displaying columns in filter/col selector that are hidden from code

### ISSUE THREAD

**Issue by zehawki** [mui-org/material-ui-x#1307]
## Summary 💡

Columns hidden from the code should not even be shown to the user in the UI. The user should be able to filter or select only from the *visible* set of columns.

## Motivation 🔦

I am unable to turn on filtering and column selector on the toolbar due to the absence of this feature.

Some columns may need to be present in the table for functionality but need to be hidden from the user, eg an ID column with some random string etc. I'm proposing that these not be shown in the UI under filter / column selector since they may lead to needless confusion for the lay user.

Thus there is a difference between "hiding" from the code (dev-land), vs "hiding" from the UI (this is user-land). Perhaps a new config key can be created called "dontShow" or some such. https://material-ui.com/components/data-grid/columns/#column-headers

**Comment by oliviertassinari** [comment]
I personally think that we should label this issue "won't fix". You can use the `getRowId` for the use case you are describing.

**Comment by dtassone** [comment]
FYI you don't need to add an id column in the column set. Just need to provide an id in the set of rows.

**Comment by zehawki** [comment]
Yup, I was going about this wrong. All good now, thanks.
