### ISSUE TITLE
[docs] Cover how to parse string to a different type

### ISSUE THREAD

**Issue by Bluefitdev** [mui-org/material-ui-x#1313]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Using `datetime` or `date` column type does not work as expected. Filter is not working, also it shows as raw data from db. 

For instance, my json api request:
`created_at: 2021-03-23T06:23:44.000000Z`

## Expected Behavior 🤔

I suspected that you only expect `Date` type of value in the cell (as it shown in every example in the website), but after inspecting the commit [here](https://github.com/mui-org/material-ui-x/pull/411/commits/3dc2b24846d15cee60ebec082ad5abe24db77a26), apparently filter should also accept string.

Also I thought date should be type should be formatted if taken in `Date` object of js? Right now i'm solving it like this:

```
    {
      field: "created_at",
      headerName: "Requested day",
      type: "date",
      valueFormatter: (params) => dayjs(params.value).format("DD MMM YYYY"),
      filterable: false,
    },
```

However filter is still not working

## Steps to Reproduce 🕹

Here's the [sandbox](https://codesandbox.io/s/datagrid-bug-demo-3tmw7?file=/src/App.js), however I'm using XGrid. I don't want to put my license in the sandbox so i used datagrid instead.

## Your Environment 🌎
Browser: Chrome

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
npx: installed 2 in 4.577s

  System:
    OS: macOS 11.2.3
  Binaries:
    Node: 12.20.0 - ~/.nvm/versions/node/v12.20.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.20.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.20.0/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Edge: Not Found
    Firefox: 76.0.1
    Safari: 14.0.3
  npmPackages:
    @material-ui/core: ^4.11.2 => 4.11.2
    @material-ui/icons: ^4.11.2 => 4.11.2
    @material-ui/lab: ^4.0.0-alpha.57 => 4.0.0-alpha.57
    @material-ui/pickers: 3.2.10 => 3.2.10
    @material-ui/styles:  4.11.2
    @material-ui/system:  4.11.2
    @material-ui/types:  5.1.0
    @material-ui/utils:  4.11.2
    @material-ui/x-grid: ^4.0.0-alpha.23 => 4.0.0-alpha.23
    @material-ui/x-license:  4.0.0-alpha.21
    @types/react:  17.0.0
    react: ^17.0.1 => 17.0.1
    react-dom: ^17.0.1 => 17.0.1
    styled-components: ^5.1.1 => 5.2.1
    typescript:  3.9.7
```
</details>

## Order id 💳
I have purchased the XGrid license as well, order: #23091

Thanks guys

**Comment by oliviertassinari** [comment]
The column type is documented at https://material-ui.com/components/data-grid/columns/#column-types. It only works if the JavaScript value of a cell is of the correct type. So in your case, you need to cast the ISO string into a JavaScript date object.

I think that we should update the documentation to cover the value casting aspect. Unless you are using graphQL or a custom fetch parser, you will get a string back form the database.

**Comment by Bluefitdev** [comment]
ah i didn't know that it should be a date object. I thought if its type string then it would be passed to the Date constructor object automatically

Thanks for the clarification. I didn't know that there's a work around with `valueGetter`.

**Comment by oliviertassinari** [comment]
> Thanks for the clarification.

Yes, this is exactly this potential confusion that we should cover in the documentation 👍 . Regarding the type casting with new Date. Be very careful to include the timezone, otherwise, you will get surprises: https://github.com/mui-org/material-ui/pull/23475.
