### ISSUE TITLE
[XGrid] GridColumnsToolbarButton in GridToolbar doesn't keep state like GridFilterToolbarButton or GridDensitySelector

### ISSUE THREAD

**Issue by Javaman44** [mui-org/material-ui-x#1317]
I have a button to show or to hide GridToolbar

show
![image](https://user-images.githubusercontent.com/9351983/112851236-15886600-90ab-11eb-84dc-b07b4513f730.png)
hide
![image](https://user-images.githubusercontent.com/9351983/112851282-1faa6480-90ab-11eb-92ac-fb007b65e511.png)

I am using this code to open/hide:
```
export function CustomToolbar(props: GridBaseComponentProps & { isVisible?: boolean }) {
    return (
        <Collapse in={props.isVisible}>
            <GridToolbar />
        </Collapse>
    );
    }
```

Everything works well except for column selection. When i hide menu i lost my selection. for example if i choose to see 'id' column, the column is shown like this:

![image](https://user-images.githubusercontent.com/9351983/112851863-a95a3200-90ab-11eb-85e9-14b5febf792f.png)

but if i hide menu the column 'Id' disappear. For other menu (density and filter) selection are kept 
![image](https://user-images.githubusercontent.com/9351983/112851916-b7a84e00-90ab-11eb-8455-f296f4581e47.png)

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce 🕹
Please see sandbox example: https://codesandbox.io/s/kind-almeida-39gsp?file=/src/App.tsx
1 - click on 'Show Menu' button
2 - hide a column
3- click on 'Show Menu' Button
4- column reappear

## Context 🔦
I want to be able to hide or show toolbar

## Your Environment 🌎

  System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 15.0.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.0.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: latest versoin
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @emotion/react: latest => 11.1.5
    @emotion/styled: latest => 11.1.5
    @material-ui/core: latest => 4.11.3
    @material-ui/icons: ^4.11.2 => 4.11.2
    @material-ui/lab: ^4.0.0-alpha.57 => 4.0.0-alpha.57
    @material-ui/styles:  4.11.3
    @material-ui/system:  4.11.3
    @material-ui/types:  5.1.0
    @material-ui/utils:  4.11.2
    @material-ui/x-grid: 4.0.0-alpha.23 => 4.0.0-alpha.23
    @material-ui/x-license:  4.0.0-alpha.21
    @types/react: ^16.9.53 => 16.14.2
    react: latest => 17.0.1
    react-dom: latest => 17.0.1
    typescript: ^4.0.3 => 4.1.3

**Comment by dtassone** [comment]
Put your columns and rows in `useState()` so they don't recreated at each render as this is resetting the columns...
Grid is based on immutablyility

**Comment by Javaman44** [comment]
Thanks a lot for your super quick reply ;)
And thanks for this great lib, i think il will take paid Version soon ;)

**Comment by oliviertassinari** [comment]
Duplicate of #970
