### ISSUE TITLE
[DataGrid] Create select column type

### ISSUE THREAD

**Issue by dtassone** [mui-org/material-ui-x#1320]
String extension type that allows displaying a select options component in filters, and edit mode.

The first version can be only client-side. And should work with a memoized selector that get all distinct value of a column for better performance.

### Benchmark

-  <img src="https://user-images.githubusercontent.com/936978/113061032-b5301c00-91b1-11eb-8fff-6e04b9535c0c.png" width="366" />

**Comment by DanailH** [comment]
A follow up on that ticket will be to handle multiple selection and support `GridCellValue` of type `Array`.
