### ISSUE TITLE
[DataGrid] Cell selection isn't selecting the correct one

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#1323]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Cell selection is no working when scrolling.

## Expected Behavior 🤔

Cell selection is working when scrolling.

## Steps to Reproduce 🕹

1. Open https://master--material-ui-x.netlify.app/components/data-grid/#commercial-version
2. 

https://user-images.githubusercontent.com/3165635/113157672-66c75f80-923b-11eb-95d6-ef7b989a2ba0.mp4

This regression isn't released yet. It comes from #1253 (I have tested with a `git revert 575f10a24a3818580a16a8b6700bd50c1f6efb22` from HEAD)

**Comment by dtassone** [comment]
this is fixed in #1319, it's due to an issue with rowIndex
