### ISSUE TITLE
[DataGrid] Rename sortModel to sortBy

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#133]
This change aims to make the objective of the prop easier to grab and memorize. It's pretty similar to what most ORMs have, matching the [`ORDER BY`](https://en.wikipedia.org/wiki/Order_by) command of SQL. First discussed in https://github.com/mui-org/material-ui-x/pull/130#discussion_r463001587.

**Comment by dtassone** [comment]
For this issue, we should also consider the corresponding event names.
For sorting, we currently have `sortModel` and `onSortModelChange`
What would be the event name for if we rename the `sortModel` to `sortBy`?

**Comment by oliviertassinari** [comment]
> What would be the event name if we rename sortModel to sortBy?

To match the conversion of exposed states: `onSortByChange`?

**Comment by dtassone** [comment]
It literally doesn't sound nice in english I think.

How about `onSortingChange`, `onGroupingChange`,  `onFilteringChange` or `onSortChange`, `onGroupChange`, or `onFilterChange`... 
versus `onGroupByChange` or `onFilterByChange`

**Comment by oliviertassinari** [comment]
> It literally doesn't sound nice in english I think.

Time to bring in @mbrookes 👀 😄
