### ISSUE TITLE
Unable to call a function from inside renderCell

### ISSUE THREAD

**Issue by sajidfrommerqata** [mui-org/material-ui-x#1362]
I'm unable to call the function from inside the renderCell. 

**My Code looks like this:**
```
  {
    field: "business_name",
    headerName: "Vendor",
    width: 170,
    type: "string",
    renderCell: (params) => getUser(params.row.id),
  },
```

**Error:** Call to undefined function getUser();

**Expected Result:** I should be able to call functions from inside renderCell

**Comment by sajidfrommerqata** [comment]
Here it is: https://codesandbox.io/s/material-demo-forked-pb36i

**Comment by oliviertassinari** [comment]
@sajidfrommerqata What's the issue. The reproduction seems to behave correctly.

**Comment by dtassone** [comment]
Closing for now as it seems to be working.
Please @sajidfrommerqata  reopen if you  still have an issue

**Comment by oliviertassinari** [comment]
@dtassone sounds great. So far, we have been usually snoozing issues without enough information for 2-3 days (waiting for the feedback from the author) before closing.
