### ISSUE TITLE
[DataGrid] Set the correct `id` and `labelledby` on the column menu

### ISSUE THREAD

**Issue by DanailH** [mui-org/material-ui-x#1365]
When opening the column menu make sure that the `id` and `labelledby` are correctly set.

This was first mentioned here https://github.com/mui-org/material-ui-x/pull/1289#discussion_r602158285

- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Currently, the `id` and the `labelledby` are stored in the state. The problem is that this does not scale very well and if you try and open the column menu using another interaction, for example when pressing `Enter` then those values would not be set correctly.

## Motivation 🔦

We need a solution for this for accessibility reasons.

**Comment by oliviertassinari** [comment]
To make it short and developer-centric. The problem/objective is to fix the developers API:

```diff
/**
 * Display the column menu under the field column.
 * @param field
-* @param id
-* @param labelledby
 */
-apiRef.current.showColumnMenu(field: string, id: string, labelledby: string) => void
+apiRef.current.showColumnMenu(field: string) => void
```

**Comment by dtassone** [comment]
As discussed the column id would need to be stored in the state.
