### ISSUE TITLE
Ability to Customize Footer with custom components

### ISSUE THREAD

**Issue by tarochipz** [mui-org/material-ui-x#1370]
We want to be able to customize the XGrid footer with some action buttons that the user can take on the selected rows.

We have an existing custom footer component we can use with the grid component slot, but we also want to take advantage of the pagination component and functionality that belongs to the XGrid footer rather than build our own. 

1.  Is there a way for us customize the XGrid footer and put custom components (i.e. buttons or icon buttons) in there ?
2. If no to 1, is there currently a way for us to use the Pagination component outside of the XGrid footer and just put it into our own footer component ?

- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Examples 🌈

For example, the end result will be something like:
![image](https://user-images.githubusercontent.com/38901400/113779433-94505500-96e2-11eb-99d8-c8db73e577ec.png)

**Comment by dtassone** [comment]
You can already customize the footer using the `components` prop
check the doc page https://material-ui.com/components/data-grid/rendering/#customization-example

**Comment by tarochipz** [comment]
> You can already customize the footer using the `components` prop
> check the doc page https://material-ui.com/components/data-grid/rendering/#customization-example

But this replaces the _entire_ footer with a custom one, which means we also have to add our own pagination component ? 
We want to be able to customize the existing XGrid footer while retaining other components and features (like pagination and rows selected).

**Comment by m4theushw** [comment]
You can reuse the pagination component in your footer, it's exported as `GridPagination`. The components used internally are also exported if you need to compose another layout.

**Comment by kzviagina** [comment]
How to render custom pagination in `XGrid` Footer?
We are moving from `DataGrid` to `XGrid` and I faced the problem, that I'm unable to access `state` and `api` props, inside `GridFooterContainer` component as it was done for `DataGrid`:
```
const { state, api } = props;
...
api.current.setPage(value)
```

**Comment by kzviagina** [comment]
Found, that `useGridSlotComponentProps` hook can be used for those purposes.

**Comment by oliviertassinari** [comment]
@kzviagina Which state are you specifically looking for?

**Comment by kzviagina** [comment]
@oliviertassinari grid state and grid api. But as I mentioned in a later comment, I already found a solution.

**Comment by oliviertassinari** [comment]
@kzviagina Interesting, so that also resonates with https://github.com/mui-org/material-ui-x/issues/1401#issuecomment-818306986 and the idea to expose a hook to access the apiRef (which hold everything).

**Comment by tarochipz** [comment]
we have a custom composed layout using the exported `GridPagination` component, but the pagination component does not affect the data displayed in the table-- it always shows all rows instead of the specified pageSize. Is there something that I'm missing ? Couldn't find anything obvious in docs https://material-ui.com/components/data-grid/pagination/.

Example:

![image](https://user-images.githubusercontent.com/38901400/116289856-b8cea880-a747-11eb-93bc-092d321e06df.png)

**Comment by cjauvin** [comment]
Hi @tarochipz, I'm also struggling with this exact same issue, would you mind sharing your code please, as it looks that you have found an interesting way to do it?

My only solution so far is to redefine my own version of the `GridFooter`, in order to be able to insert my own custom child in its list of children (`rowCountElement` and `paginationElement`). I'd like an easier solution if possible. Thanks!

**Comment by cherylcarpenter** [comment]
> Hi @tarochipz, I'm also struggling with this exact same issue, would you mind sharing your code please, as it looks that you have found an interesting way to do it?
> 
> My only solution so far is to redefine my own version of the `GridFooter`, in order to be able to insert my own custom child in its list of children (`rowCountElement` and `paginationElement`). I'd like an easier solution if possible. Thanks!

Please share code thanks.

**Comment by cherylcarpenter** [comment]
> ~we have a custom composed layout using the exported `GridPagination` component, but the pagination component does not affect the data displayed in the table-- it always shows all rows instead of the specified pageSize. Is there something that I'm missing ? Couldn't find anything obvious in docs https://material-ui.com/components/data-grid/pagination/.~
> 
> Nvm :) just have to pass pagination as a prop to the grid
> 
> Example:
> 
> ![image](https://user-images.githubusercontent.com/38901400/116289856-b8cea880-a747-11eb-93bc-092d321e06df.png)

Please share code thanks.

**Comment by TamirCode** [comment]
> You can reuse the pagination component in your footer. It's exported as `GridPagination`. The components used internally are also exported if you need to compose another layout.



> You can reuse the pagination component in your footer. It's exported as `GridPagination`. The components used internally are also exported if you need to compose another layout.

how do I find the name of the default components that come with datagrid / datagrid-pro?
in the docs there is no example of how to access these, but for customizing the toolbar the docs include example with the proper component names https://mui.com/x/react-data-grid/components/#toolbar

when customizing footer, if I want for example the dropdown for rows per page then idk how to get that

**Comment by TamirCode** [comment]
> You can reuse the pagination component in your footer. It's exported as `GridPagination`. The components used internally are also exported if you need to compose another layout.

hello, how do i import the total rows selected component which I want to include in my custom footer layout

**Comment by TamirCode** [comment]
I want to reuse this part specifically for my own custom pagination, do i need to do the calculations myself or does anyone know how to get it as component or with the useGridSelector ? thanks
![image](https://user-images.githubusercontent.com/66864667/201527218-7f9a1570-c40c-4484-afa3-1638836cab38.png)

**Comment by TamirCode** [comment]
> I want to reuse this part specifically for my own custom pagination, do i need to do the calculations myself or does anyone know how to get it as component or with the useGridSelector ? thanks ![image](https://user-images.githubusercontent.com/66864667/201527218-7f9a1570-c40c-4484-afa3-1638836cab38.png)
> 
> i tried gridPaginationRowRangeSelector but its useless

ended up calculating it myself
```js
	const paginationInfo = useGridSelector(apiRef, gridPaginationSelector) // gives: page (currentPage - 1) pageCount (amount of pages generated) pageSize rowCount

	// calculate the current viewable rows range: 
	let currentPage = paginationInfo.page + 1
	let startingIndex = ((currentPage - 1) * paginationInfo.pageSize) + 1
	let endingIndex = startingIndex + paginationInfo.pageSize - 1
	if (paginationInfo.rowCount < 1) { startingIndex = 0 }
	if (endingIndex > paginationInfo.rowCount) { endingIndex = paginationInfo.rowCount }
```

**Comment by yonusbakhshi** [comment]
> ~we have a custom composed layout using the exported `GridPagination` component, but the pagination component does not affect the data displayed in the table-- it always shows all rows instead of the specified pageSize. Is there something that I'm missing ? Couldn't find anything obvious in docs https://material-ui.com/components/data-grid/pagination/.~
> 
> Nvm :) just have to pass pagination as a prop to the grid
> 
> Example:
> 
> ![image](https://user-images.githubusercontent.com/38901400/116289856-b8cea880-a747-11eb-93bc-092d321e06df.png)

Hi @tarochipz, could you please share the code with us here!

**Comment by maartenpeels** [comment]
For the ones looking for this, here is what I did:
```
components={{
  Footer: () => (
    <>
      <GridPagination />
      <Box sx={{ p: 1, display: "flex" }}>Your custom footer stuff</Box>
    </>
  ),
}}
```

**Comment by manurg** [comment]
For the ones getting the deprecation warning for using `components` prop, this is an example using `slots` instead:

```
 slots={{
  footer: () => (
    <>
      <GridPagination />
      <Box sx={{ p: 1, display: "flex" }}>Your custom footer stuff</Box>
    </>
  ),
}}
```
