### ISSUE TITLE
[DataGrid] The `api.commitCellChange` does not trigger a change in a custom `renderEditCell` component

### ISSUE THREAD

**Issue by angelsvirkov** [mui-org/material-ui-x#1381]
I believe that whenever the Grid has a custom component registered with the `renderEditCell` then the actual `api.commitCellChange` does not trigger any change to the component that is currently in an edit mode unless we trigger the cell view mode by `esc` , `blur` or by `api.setCellMode(id, field, 'view');`

I am currently evaluating the possibility for my team to use DataGrid or XGrid and I needed to try out your newest features that are not officially documented. I used the following examples
- https://deploy-preview-1287--material-ui-x.netlify.app/components/data-grid/editing/#customization from #1287

- [x] The issue is present in the latest release.
**Note:** I think the issue will be present in the latest release of the new feature Cell Editing #203.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When I click to change a cell value (custom rating), the UI does not really change to the value I have selected

## Expected Behavior 🤔

The value I have selected changes and the UI shows this new value without the need to switch the cell mode to `view`

## Steps to Reproduce 🕹

I have created an example repo by taking the code used in the [cell editing documentation#customization example](https://deploy-preview-1287--material-ui-x.netlify.app/components/data-grid/editing/#customization) and commenting out the `api.setCellMode` function call

- https://codesandbox.io/s/material-demo-forked-h17qb

Steps:

1. Go to any Rating Cell and enter the edit cell mode (by clicking on the cell, for example)
2. Switch the rating to a new value.
3. Do NOT exit the edit mode.

## Context 🔦

Here is what I am trying to accomplish with my general use case.
- I would like to use DataGrid or XGrid to to render a table of editable checkboxes ( e.g. 50 rows by 5 columns)
- I would like to use a button to switch between edit / view mode of **ALL** cells at once. This is achievable with the `apiRef`
- I would then like to edit multiple cells without following any pattern logic such as all rows to true or all columns to follows
- I would then like to click on save, which triggers the `view` mode of the table
- Ideally I would like to receive the edited row model, which is also possible with the provided props

The problem where I got stuck is the the `api.commitCellChange` (triggered from within a custom `renderEditCell`) because it does not really do anything to my table unless I leave the `edit` cell mode, which I do not want to do before I have edited let's say 10 cells.

This is a typical use case in an administration tool where some users would have only read access to the table and others would be able to click `unlock` and then edit multiple cells at once and later click `save`.

## Your Environment 🌎

Using chrome and the sandbox given here https://codesandbox.io/s/material-demo-forked-h17qb

P.S. Thank you for the amazing features around MUI DataGrid and XGrid, which are already released and about to be released. It is always pleasant and satisfying to use MUI packages

**Comment by dtassone** [comment]
`commitCellChange` allows to update the underlying cell value, you commit the change and it is saved in the rows state.

What you are trying to do here, is update the edit input component.
This can be done in several ways. 
- you could use react state in the input component that you initialise with the value passed in props
```tsx
const [valueState, setValueState] = React.useState(value);
const handleChange = React.useCallback(
    (event) => {
      setValueState(Number(event.target.value));
}, [])
...
return <Rating value={valueState} />
```
- you could use apiRef and call `setEditCellProps` which lets you pass props to the edit input component. 
```tsx
  const handleChange = React.useCallback(
    (event) => {
      const editProps = {
        value: Number(event.target.value), anotherProp: true
      };
      api.setEditCellProps({
        id,
        field,
        props: editProps
      });
    },
    [api, field, id]
  );
 console.log(props.anotherProp) // true after 1 change
```
It made me realize that I have to improve the type and add a generic for the edit input prop type that would be based on GridCellParams 🤔

**Comment by angelsvirkov** [comment]
Thank you, the `api.setEditCellProps` helped me.

**Comment by oliviertassinari** [comment]
@angelsvirkov If you could share the final solution with a codesandbox, it would be awesome, it will likely help the rest of the community.

So to summarize, and based on thz section in "Context 🔦", 

1. renderCell to render checkboxes
2. use the API and call `setCellMode` on all the cells to turn them into edit mode.
3. preventDefault to disable the built-in exit mode events as in [the demo](https://deploy-preview-1287--material-ui-x.netlify.app/components/data-grid/editing/#StartEditButtonGrid.tsx)
4. use the API and call `setCellMode` on all the cells to turn them back into view mode.
5. use the `editRowsModel` prop or `setEditCellProps` to receive updates

**Comment by angelsvirkov** [comment]
Yes, I will do once ready 👍

**Comment by angelsvirkov** [comment]
@oliviertassinari , here is my final solution in codesandbox and the repository behind it
 - https://codesandbox.io/s/mutable-brook-wkz27
 - https://github.com/angelsvirkov/material-ui-x-grid-edit-example

**Comment by oliviertassinari** [comment]
@angelsvirkov Awesome, thanks.

@dtassone Looking at the example, the `event.stopPropagation()` approach feels counterintuitive to me. I think that we should look for better alternatives. Why should the propagation of the event to the parent of the data grid have any impact on how the component handles the event? Intuitively, I think that developers will expect `event.stopPropagation()` to only impact the parent, not the children **nor the element it listens on** ⚠️. If we were calling [stopImmediagePropagation](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopImmediatePropagation) it would be clearer but it's not available.

https://next.material-ui.com/components/autocomplete/#events has more or less the same flaw, to one difference. `event.preventDefault()` has an immediate impact, while `stopPrapgation()` should only concern the parents.

A proposal: we replace `event.stopPropagation()` to leverage `event.defaultMuiPrevented` instead. It solves 1. the parent vs. immediate element it listens to confusion. 2. It increases consistency with the Autocomplete, reducing the learning curve. 3. it plays nicely with https://css-tricks.com/dangers-stopping-event-propagation/.

Thoughts? cc @angelsvirkov I can open an RFC.

**Comment by keso003** [comment]
found the answer using this [https://github.com/mui/mui-x/issues/8037#issuecomment-1446245154](https://github.com/mui/mui-x/issues/8037#issuecomment-1446245154)
