### ISSUE TITLE
[RFC] Event naming conventions

### ISSUE THREAD

**Issue by m4theushw** [mui-org/material-ui-x#1383]
## Summary 💡

This RFC proposes a set of rules on how events emitted by components and hooks should be named.

## Motivation 🔦

- The current [constants file](https://github.com/mui-org/material-ui-x/blob/master/packages/grid/_modules_/grid/constants/eventsConstants.ts) lacks consistency as different approaches are taken to name similar events, e.g. `GRID_CELL_DOUBLE_CLICK` and `GRID_CELL_KEYDOWN`.
- New events got to be introduced in the last refactorings, but depending on who created them, different conventions were adopted. https://github.com/mui-org/material-ui-x/pull/1289#discussion_r606541465 and https://github.com/mui-org/material-ui-x/pull/1380#discussion_r610614068.
- Facilitates the usage of the API as it's easier to guess the purpose of an event when it's named consistently.

## Proposed Solution 🧾

Based on my understanding and the discussions we had I summarised the following rules:

### 1. Prefix who publishes it

- When published by a component, use the name of the component as prefix, not the feature it was created for:

```diff
- export const GRID_COLUMN_REORDER_DRAG_OVER = 'columnReorderDragOver';
+ export const GRID_COLUMN_HEADER_DRAG_OVER = 'columnHeaderDragOver';
``` 

- The feature name should be used when emitted by a hook, e.g. `GRID_COLUMN_ORDER_CHANGE` and `GRID_COLUMN_RESIZE_STOP`. `GRID_PAGE_CHANGE` and `GRID_PAGE_SIZE_CHANGE` are exceptions as it's very clear what they do.

### 2. Use the event handler as suffix

When the event is published by a React [event handler](https://reactjs.org/docs/events.html) (`onMouseUp`, `onKeyDown`, `onDoubleClick`), the prop name should be used as suffix by converting it to uppercase and removing the "on". 

Prop name | Event constant
------------ | ----------------
`onDragOver` | `GRID_COLUMN_HEADER_DRAG_OVER`
`onClick` | `GRID_COLUMN_HEADER_CLICK`
`onDoubleClick` | `GRID_ROW_DOUBLE_CLICK`

### 3. Avoid abbreviations

```diff
- export const GRID_COL_RESIZE_START = 'colResizeStart';
+ export const GRID_COLUMN_RESIZE_START = 'columnResizeStart';
``` 

### 4. Present tense always

```diff
- export const GRID_PAGE_CHANGED = 'pageChanged';
+ export const GRID_PAGE_CHANGE = 'pageChange';

- export const GRID_CELL_EDIT_PROPS_CHANGE_COMMITTED = 'cellEditPropsChangeCommitted';
+ export const GRID_CELL_EDIT_PROPS_CHANGE_COMMIT = 'cellEditPropsChangeCommit';
```

### 5. Constant name and value should match

The constant name is reserved for internal use only. In all demos and docs, the value of the constant is what users will be encouraged to use. In this context, the constant value should be the camelCase version of the constant name without "GRID". 

```js
export const GRID_COLUMN_HEADER_CLICK = 'columnHeaderClick';
export const GRID_SORT_MODEL_CHANGE = 'sortModelChange';
export const GRID_MULTIPLE_KEY_PRESS_CHANGE = 'multipleKeyPressChange';
```

## Unresolved Questions ❓

In rule n. 2 should the prop name (`onMouseUp`) or the DOM event (`mouseup`) be used as suffix?

**Comment by oliviertassinari** [comment]
@m4theushw Awesome, great job

> Unresolved Questions ❓

I guess we have 4 options, taking the key down event example. The order I would vote for them:

- Option 1. Use the name of the handler. Meaning: If we listen to a synthetic React event, use its name. If we listen to a dom event, use its name. So we could have events with `_KEY_DOWN` and others with `_KEYDOWN`. This would reduce confusion on what the event is.
- Option 2. Use the name of the React handler systematically. `_KEY_DOWN` only. I like this approach as React developers mostly use the synthetic system.
- Option 3. Use the DOM event name
- Option 4. YOLO

> 3. Avoid abbreviations

I would almost say the same thing for all written conversations. More importantly, never on the documentation. I have added it in https://www.notion.so/Communication-8382c02477c948dba808ca0ca89004a6#b60c57d91e41470c99ccc1b127a72a25. cc @dtassone as I have seen you use them frequently.

**Comment by dtassone** [comment]
GRID_CELL_KEY_DOWN
GRID_CELL_KEY_UP
GRID_CELL_MOUSE_DOWN
GRID_CELL_DOUBLE_CLICK
GRID_CELL_CLICK

GRID_CELL_EDIT_KEY_DOWN
GRID_CELL_EDIT_KEY_UP

GRID_COLUMN_HEADER_WIDTH_CHANGE
GRID_ROWS_UPDATED

GRID_ROW_SELECTED => GRID_ROW_SELECTION_CHANGE
GRID_ROWS_UPDATED => GRID_ROWS_UPDATE

relate #1301

**Comment by oliviertassinari** [comment]
OK, so we are going with the React's handlers name, even is if the event is native. This is option 2. It sounds fair.
