### ISSUE TITLE
[XGrid] Expose a column size change event

### ISSUE THREAD

**Issue by randalpinto** [mui-org/material-ui-x#1400]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Grids can usually be refreshed in the background and when this happens the state of the grid is lost. With the current observers (page size, page number, sort order, filter order) it is possible to persist most of the state but the width of the columns still gets reset when the grid gets updated. In order to control this state we need an onColumnSizeModelChange event that indicates the width of each of the columns when they get resized and then a columnSizeModel property that allows this to be set.

## Examples 🌈

N/A

## Motivation 🔦

See description in the summary,

**Comment by oliviertassinari** [comment]
> the state of the grid is lost.

Related to #820

**Comment by DanailH** [comment]
This can also be closed since now there are options on the grid itself that developers can hook on to (`onColumnResize` and `onColumnResizeCommitted`).

**Comment by oliviertassinari** [comment]
If we coido have a demo of it working, it would be 👌 (link to the docs or a codesandbox) so we can close. I also wonder if a onStateChange with a state reducer can not also cover this use case.

**Comment by dtassone** [comment]
`onStateChange` can cover every use case as every action updates the state.
However, the recommended way of doing this is by using `onColumnResize`. 

BTW there is/was a typo with `onColumnResizeCommitted` in the api doc, not sure we fixed it.

**Comment by oliviertassinari** [comment]
```jsx
import * as React from "react";
import { XGrid } from "@material-ui/x-grid";
import { useDemoData } from "@material-ui/x-grid-data-generator";

export default function XGridDemo() {
  const { data } = useDemoData({
    dataSet: "Commodity",
    rowLength: 1000
  });

  return (
    <div style={{ height: 520, width: "100%" }}>
      <XGrid
        {...data}
        loading={data.rows.length === 0}
        rowHeight={38}
        checkboxSelection
        onColumnResize={({ width }) => {
          console.log("move", width);
        }}
        onColumnResizeCommitted={({ width }) => {
          console.log("end", width);
        }}
      />
    </div>
  );
}
```

https://codesandbox.io/s/material-demo-forked-fvhs5?file=/demo.tsx:0-664

**Comment by oliviertassinari** [comment]
> BTW there is/was a typo with onColumnResizeCommitted in the api doc, not sure we fixed it.

Yeah, true, 

https://github.com/mui-org/material-ui-x/blob/fda80d885bda00999a43d7053d9bc4b81431708d/packages/grid/_modules_/grid/constants/eventsConstants.ts#L71

**Comment by m4theushw** [comment]
> BTW there is/was a typo with onColumnResizeCommitted in the api doc, not sure we fixed it.

The typo in the docs was fixed by #1563. What is still misspelled is the event constant.

**Comment by dtassone** [comment]
it seems that there is a typo in the code 🤔 

`onColumnSizeChange` seems more like our name convention

**Comment by DanailH** [comment]
I'll handle this now
