### ISSUE TITLE
[docs] Better document how to disable row selection

### ISSUE THREAD

**Issue by sajidfrommerqata** [mui-org/material-ui-x#1406]
No information in the documentation for completing disabling row selection:

Screenshot: https://prnt.sc/11bw7ud

**Comment by tifosiblack** [comment]
You can use disableSelectionOnClick : https://material-ui.com/api/data-grid/

**Comment by oliviertassinari** [comment]
i'm reopening as the issue is about the lack of a section in the docs

**Comment by dtassone** [comment]
I would say fix the docs as it's there 
https://material-ui.com/components/data-grid/selection/#disable-selection-on-click

**Comment by oliviertassinari** [comment]
@dtassone So update this demo from `disableClickEventBubbling` to `disableSelectionOnClick`? Which is related to #1296.

**Comment by dtassone** [comment]
Changes should be done.
https://material-ui.com/components/data-grid/selection/#disable-selection-on-click
