### ISSUE TITLE
[DataGrid] Allow to control column visibility

### ISSUE THREAD

**Issue by tusharchutani** [mui-org/material-ui-x#1412]
I have a requirment to show or hide a column based on click of button. On the click of the button I am setting the hide property to true or false of the columns (which is in a state).

I have set up a CodeSandbox to show case this: https://codesandbox.io/s/material-demo-forked-l004j?file=/demo.tsx

I am not sure if this is supported yet if it is not is there a work around this?

**Comment by m4theushw** [comment]
The [columns definitions](https://material-ui.com/components/data-grid/columns/#column-definitions) should never change after the first mount. Storing them in a state and updating it has no effect. The XGrid provides the method `apiRef.current.updateColumn` to update the columns at any time. I've updated your example showing how to use this API.

**Comment by oliviertassinari** [comment]
Should we close? I'm not sure how we could leverage this feedback in any way to improve the docs or the product.

Well, unless we want to freeze the provided props, but it might be a bit extreme?

**Comment by m4theushw** [comment]
A warning when the `columns` prop changes between renders sounds enough. What do you think?

**Comment by tusharchutani** [comment]
@m4theushw the apiRef functionality is not available on DataGrid right (only on XGrid) right?

**Comment by m4theushw** [comment]
`apiRef` is only available in XGrid. Storing the columns in a state variable is not recommended because each time it's updated, the reference changes, which causes another rerender.

**Comment by oliviertassinari** [comment]
> A warning when the columns prop changes between renders sounds enough. What do you think?

@m4theushw We have allowed developers to change the `columns` prop, sure it will reset a few states, but this is working. If in the future, they even control the state, they could mitigate the side-effects, I personally think that it's fine.

IMHO the issue with the author is that he mutates he data structure, this is wrong in the first place, it breaks react principles

**Comment by oliviertassinari** [comment]
@tusharchutani please don't edit the original reproduction with the proposed fix. It's makes it hard for us to find root cause solutions.

**Comment by dtassone** [comment]
ATM the hide attribute is tightly binded to the column definition model so the only way to hide a column programmatically would be by using the react state and resetting the column prop of the Data-Grid component, as below (copied from codesandbox)

``` tsx
export default function ApiRefRowsGrid() {
  const [columns, setColumns] = useState(defaultColumns);

  const change = () => {
    defaultColumns[2].hide = !columns[2].hide;
    setColumns([...defaultColumns]);
  };
  return (
    <div style={{ height: 400, width: "100%" }}>
      <button onClick={change}>Change</button>
      <DataGrid rows={defaultRows} columns={columns} />
    </div>
  );
} 
```

To avoid that, we could approach the hiding feature as the selection feature, and create a separate plugin (hook) for it.
So we would have a new `hiddenColumnModel` react prop which would take an array of column fields.
```tsx
      <DataGrid rows={defaultRows} columns={columns} hiddenColumnModel={{['age']}} />
```

**Comment by tusharchutani** [comment]
@oliviertassinari sorry about changing the original codesandbox. I reverted it back. I am a little confused about this statement 
>  the reproduction mutates the data structure

In the newest code sandbox where I am resetting the columns with `setColumns([...defaultColumns]);` the data is not mutating but rather is being reset.

**Comment by oliviertassinari** [comment]
A benchmark reference regarding controlling the column visibility with props: https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/column-visibility/.

**Comment by davidroman-hub** [comment]
@oliviertassinari  the last features are available also on Xgrid?

**Comment by oliviertassinari** [comment]
@davidroman-hub ?

**Comment by davidroman-hub** [comment]
@oliviertassinari  sorry to don't be very specific , i mean,   i wanted to know if i can use this component also on Xgrid:

`
import {
  Grid,
  Table,
  TableHeaderRow,
  ColumnChooser,
  TableColumnVisibility,
  Toolbar,
} from '@devexpress/dx-react-grid-material-ui';
`
Because i'm using dataXgrid for my projects, and with this features maybe i can show & hide columns in better way, because i had to use magic to use DataXgrid in the way that i wanted,  more for show & hide columns and catch different events when a column is close or not.

**Comment by oliviertassinari** [comment]
@davidroman-hub Thanks for the clarification. I agree with the general proposal made by @dtassone in https://github.com/mui-org/material-ui-x/issues/1412#issuecomment-819697826. 

We could have a controllable prop:

```jsx
export default function ApiRefRowsGrid() {
  const [visibleColumns, setVisibleColumns] = useState(null);

  const change = () => {
    defaultColumns[2].hide = !columns[2].hide;
    setColumns([...defaultColumns]);
  };
  return (
    <div style={{ height: 400, width: "100%" }}>
      <button onClick={change}>Change</button>
      <DataGrid
        rows={defaultRows}
        columns={columns}
        visibleColumns={visibleColumns}
        onVisibleColumnsChange={(params) => setVisibleColumns(params.visibleColumns)}
      />
    </div>
  );
} 
```

(I have used `visibleColumns` for the state as what matters most is what's visible, not hidden, and matches the internal state).

The current workaround is to reproduce was the column selector panel does: 

https://github.com/mui-org/material-ui-x/blob/40ebf9b4079dd7433200b7de00b6959fd25a50ec/packages/grid/_modules_/grid/components/panel/GridColumnsPanel.tsx#L50

See: https://codesandbox.io/s/material-demo-forked-1rf53?file=/demo.tsx

**Comment by davidroman-hub** [comment]
Thanks ! Is really nice to have this, I used redux to control props also apiRef to update the table, but with this feature , I can use less code and it will be more clean. Thanks for the feature.

**Comment by flaviendelangle** [comment]
@oliviertassinari we already have an api method called `getVisibleColumns` which returns the `GridColDef` of the visible columns

```ts
  /**
   * Returns the currently visible columns.
   * @returns {GridColDef[]} An array of [[GridColDef]].
   */
  getVisibleColumns: () => GridColumns;
```

If we create a `visibleColumns` prop for controlling the visible columns, I suppose it will be an array of string, each string being the field of a visible column.
The `setVisibleColumns` would have the following signature `(model: string[]) => void`

That would create an inconstancy between `getVisibleColumns` and `setVisibleColumns`

I think the easiest solution would be to name the new prop `visibleColumnsModel` even if it's quite verbose.
Alternatively we can rename `getVisibleColumns` into `getVisibleColumnsDef` but it would not be 100% consistent with `getAllColumns` which also returns the definition.



____


How do you want to handle the `hide` field of `GridColDef` ?

We would not use it in our internal codebase, but we need to either link it to the new system (by updating the `visibleColumns` state) or drop it.

Remove it ?
Update the `visibleColumns` state whenever an input column `hide` attribute changes ?

**Comment by oliviertassinari** [comment]
@flaviendelangle I had a look at the current usage of `getVisibleColumns()` in the codebase. They can all be migrated based on the proposal "I suppose it will be an array of string, each string being the field of a visible column". Developers can always call getColumn(field) if they need the details. 

> How do you want to handle the `hide` field of GridColDef?

I suppose we could drop it?

**Comment by flaviendelangle** [comment]
That would be two breaking changes but I suppose it's worth clearly breaking it to have a clean model afterward.

https://github.com/mui-org/material-ui-x/pull/2241#issuecomment-890372515

To continue the discussion here

> I think that it's all about can we remove the code? Can developers create their own grid without?
>
> If we envision the column visibility as a feature on its own (can be removed), then /hooks/features/columnVisibility/, like column > resizing, column rendering. I don't think that there is a debate do have around it.
> If we don't envision this as different features, I would personally keep everything under /hooks/features/columns/, but we can split too.
> I would raise the same question regarding column width, does it need to be controlled?

If we envision that we could remove `useGridColumnsVisibility`, then the hook must not handle the generic methods like `getColumnsMeta` which are used pretty much everywhere in the codebase.
But in that case, these selectors must be in `useGridColumns` folder an we have a circular import `allGridColumnsSelector` => `visibleGridColumnsSelector` => `gridColumnsMetaSelector`.
Except if we create a `useGridColumnsGetters` or something similar for those generic methods but it seems wrong.

____

As for the question "should we do it ?"
I think the callback rework I totally worth it for https://github.com/mui-org/material-ui-x/issues/2198
And the introduction of the `visibleColumns` prop is an interesting feature I think. But it would be delayed and still rely on the `columns[number].hide` at first.

**Comment by oliviertassinari** [comment]
> That would be two breaking changes but I suppose it's worth clearly breaking it to have a clean model afterward.

@flaviendelangle At this point, I think that it should happen after the stable release, with a deprecation. We are about to cut beta.

> As for the question "should we do it ?"

:+1: for keeping things simple even if they break the existing API

**Comment by designbyadrian** [comment]
I was hoping to be able to trigger visibility using `apiRef?.current?.setColumnVisibility(field, !!hide);`, but nothing seems to happen. `onColumnVisibilityChange` is triggered, though, so I wonder what's missing?

**Comment by m4theushw** [comment]
@designbyadrian Could you provide a [CodeSandbox](https://material-ui.com/r/issue-template) with an example? We use this method internally and it changes the visibility of the column as soon it's called.

https://github.com/mui-org/material-ui-x/blob/609248ea030cf6ca657bfae92f23bea3ba868c2b/packages/grid/_modules_/grid/components/menu/columnMenu/HideGridColMenuItem.tsx#L19

**Comment by designbyadrian** [comment]
@m4theushw I can't right now, as I'm generally struggling with using apiRef in another component. I want to have a custom filter in a sidebar and seem to have issues with race conditions. It's most likely my implementation that's questionable.
