### ISSUE TITLE
[DataGrid] valueFormatter does not format the value as expected 

### ISSUE THREAD

**Issue by zj9495** [mui-org/material-ui-x#1424]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
![image](https://user-images.githubusercontent.com/17064586/114968871-d1b69e80-9ea9-11eb-96bc-a70a82bb3f65.png)
`value` is `-1`

## Expected Behavior 🤔
`value` is `0` 

## Steps to Reproduce 🕹
https://codesandbox.io/s/material-demo-forked-m8se1?file=/demo.tsx:41-49

**Comment by dtassone** [comment]
Small issue, as 0 is falsy it renders the original value.
Workaround, do a `toString()` in `valueFormatter`

Fix in `GridCell.ts`:

```diff
-  const valueToRender = formattedValue || value;
+  const valueToRender = formattedValue == null ? value : formattedValue;
```
