### ISSUE TITLE
[DataGrid] Select all checkboxes doesn't support keyboard

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#1431]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The <kbd>Enter</kbd> and <kbd>Space</kbd> key on the column header don't have any action, space is swallowed.

## Expected Behavior 🤔

The <kbd>Enter</kbd> and <kbd>Space</kbd> key on the column header triggers the select all feature

## Steps to Reproduce 🕹

1. Open https://material-ui.com/components/data-grid/#mit-version
1. Use <kbd>Tab</kbd> to reach a data grid
1. Use the arrow to focus the checkbox all selection
1. Use <kbd>Enter</kbd> or <kbd>Space</kbd>, nothing happens

## Context

This is a follow-up on https://github.com/mui-org/material-ui-x/pull/1289.

## Your Environment 🌎

v4.0.0-alpha.25

**Comment by alexfauquette** [comment]
This problem does not occur anymore for <kbd>Space</kbd>. I'm adding tests to prevent from this regression #3262

For <kbd>Enter</kbd> I do not think it should work. checkbox selection natively works with <kbd>Space</kbd> and not <kbd>Enter</kbd>

**Comment by oliviertassinari** [comment]
> For Enter I do not think it should work. checkbox selection natively works with Space and not Enter

@alexfauquette Yeah, ok, agree a checkbox is not a button. https://www.w3.org/TR/wai-aria-practices-1.1/#grid seems to support what we have implemented.
