### ISSUE TITLE
[DataGrid] Enable/disable selection on certain rows with custom function

### ISSUE THREAD

**Issue by Neonin** [mui-org/material-ui-x#1434]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡
Enable/disable selection on certain rows with custom function. Returns true if not provided.

## Examples 🌈
https://codesandbox.io/s/github/gregnb/mui-datatables?file=/examples/selectable-rows/index.js

## Motivation 🔦
The first variation: in my table there are two types of entities, the first of them has the option of choosing the other not.
The second option: when we select one entity, the other is automatically unavailable for selection.

## Order id 💳
19652

**Comment by oliviertassinari** [comment]
@Neonin This issue description is not clear. Here is what I understand. There are multiple selection features in the grid, I have to assume you are talking about the checkbox selection. So why is the controlled mode note enough? https://material-ui.com/components/data-grid/selection/#controlled-selection

**Comment by Neonin** [comment]
@oliviertassinari Sorry for the confusing explanation.
I am developing a system for accounting for passengers on the bus. We have a seat with a passenger and the seat is empty.
When choosing a passenger place for an action, for example, sending messages, I have to check the validity of the data every time (whether this space is occupied), and it turns out that the click should not work like this other object, it looks more like a bug.
And if you immediately block another entity, it will be more convenient and understandable for the user.

**Comment by oliviertassinari** [comment]
@Neonin Why is the controllable API not enough to solve this issue?

**Comment by oliviertassinari** [comment]
@Neonin Ok, I see. Are you looking for something in this order?

<img width="359" alt="Screenshot 2021-04-20 at 16 26 22" src="https://user-images.githubusercontent.com/3165635/115413103-326d1080-a1f5-11eb-9258-0a1e41ade969.png">

A hidden checkbox or a disabled one? Did you consider rendering your own column with checkboxes?

**Comment by Neonin** [comment]
@oliviertassinari Yes 👌, I need to block a specific checkbox depending on the condition.
Next time I will provide more information 😇.

**Comment by dtassone** [comment]
We could add a prop `isRowSelectable: (params)=> boolean` as we did for `isCellEditable`, it seems like a pretty common usecase 🤔

**Comment by dtassone** [comment]
Actually we can call it `isSelectable(params)` so it stays agnostic of the selection mode, ie cell or row.

**Comment by dtassone** [comment]
Checkbox should be disabled, as well selection with keyboard, and click

**Comment by snekse** [comment]
In case this helps anyone else, if you want to "hide" the disabled checkboxes that this `isRowSelectable` selects, this `sx` worked well enough for my purposes. 

```
const sx = {
  '& .MuiDataGrid-cellCheckbox .Mui-disabled ': {
    // "hide" disabled checkboxes by making same color as background
    color: 'white', 
  },
}
```

**Comment by matthew-h-wang** [comment]
> '& .MuiDataGrid-row .MuiDataGrid-cellCheckbox .Mui-disabled ': {
>     // "hide" disabled checkboxes by making it translucent
>     color: 'rgba(0, 0, 0, 0.00)', 
>   },

This was very helpful for my case, although I used `display: 'none'` instead of `color`
