### ISSUE TITLE
[DataGrid] Remove gridKeyboardMultipleKeySelector in useGridSelection

### ISSUE THREAD

**Issue by m4theushw** [mui-org/material-ui-x#1437]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

`useGridSelection` relays in the state to detect if a multiple key is pressed (Shift or CTRL). This could be read from the event. There's an opportunity for an enhancement here that was raised in https://github.com/mui-org/material-ui-x/pull/1422#discussion_r614878834. 

## Motivation 🔦

Use the event as single source of truth.

**Comment by oliviertassinari** [comment]
It's what @joshwooding did as well on the TreeView to implement the multi selection, with the keyboard. As far as I know, it was already technically proven that it can work and that is will remove code in the grid.

**Comment by ZeeshanTamboli** [comment]
@m4theushw @oliviertassinari I have linked this issue in #1813
