### ISSUE TITLE
[DataGrid] Rows are not rendered when previous rows were scrolled down

### ISSUE THREAD

**Issue by kzviagina** [mui-org/material-ui-x#1444]
When rows data changes, so the amount of new rows is smaller than previous, rows are not rendered. This seem to reproduce only if new amount of rows is less than 10.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Updated rows are not rendered (not added to DOM)

## Expected Behavior 🤔

Updated rows are added to DOM and visible

## Steps to Reproduce 🕹

Code sandbox:
https://codesandbox.io/s/not-rendered-items-rl2v0?file=/demo.tsx

Steps:

1. Press button to show 100 rows
2. Scroll down scrolls to the middle of the list
3. Press button to show 9 rows
4. Rows are not visible and not even added to DOM, but pagination shows that there are 9 items.
5. Press button to show 100 rows
6. Scroll down scrolls to the middle of the list
7. Press button to show 10 rows
8. Rows are visible.

## Context 🔦

We display search results in grid. When search criteria is updated and new data is fetched, rows are not visible in case the amount of items is less than 10.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  System:
    OS: macOS 10.15.4
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 89.0.4389.128
  npmPackages:
    @material-ui/core: ^4.11.3 => 4.11.3 
    @material-ui/data-grid: ^4.0.0-alpha.22 => 4.0.0-alpha.22 
    @material-ui/icons: ^4.11.2 => 4.11.2 
    @material-ui/pickers: ^3.2.10 => 3.2.10 
    @material-ui/styles:  4.11.3 
    @material-ui/system:  4.11.3 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @material-ui/x-grid: ^4.0.0-alpha.24 => 4.0.0-alpha.24 
    @material-ui/x-license:  4.0.0-alpha.21 
    @types/react: ^17.0.2 => 17.0.2 
    react: ^17.0.1 => 17.0.1 
    react-dom: ^17.0.1 => 17.0.1 
    typescript: ^4.2.2 => 4.2.2 
```
</details>

## Order id 💳
23597

**Comment by kzviagina** [comment]
Hey @dtassone! Do you know the root cause of this issue or workaround?

**Comment by oliviertassinari** [comment]
@kzviagina This is a regression from 4.0.0-alpha.24. It works in 4.0.0-alpha.23. More specifically it was broken in #1253.

@dtassone I would encourage us to explore how we can remove the `isVirtualized` branching. It seems to only partially solve the problem, e.g. #414 is still present. And it seems to have lead to this regression and #1334. I personally fail to understand why we fork the rendering and even more why inside useGridContainerProps not useGridVirtualRows.

**Comment by dtassone** [comment]
@kzviagina  Bug fixed. We are planning to release today :)

**Comment by kzviagina** [comment]
@dtassone @oliviertassinari thank you for the fix and clarification! :)
