### ISSUE TITLE
Datagrid Selection Bugs/Issues

### ISSUE THREAD

**Issue by sajidfrommerqata** [mui-org/material-ui-x#1455]
I'm using Datagrid and facing some issues which I want to list in this description one by one. I already opened some of them separately but the issues are either marked as a bug or the solutions provided in the issues threads are not helping me enough. 

I want to track these all from this one place so that we don't get lost. 

1. **1st Issue:** I have a textbox inside the cell. When I click inside the textbox and press the BackSpace button then the whole value from the textbox removes. The Expected behavior is it should clear the very last character from the textbox value.

2. **2nd Issue:** when I focus on one cell and then click in the textbox which is inside another cell and start typing. Something unexpected happens. The mouse control/cursor automatically jumps to the last selected cell. The Expected behavior is the cursor should stay in the textbox and allow me to type. 

3. **3rd Issue:** The 1st issue is also with the delete button.

4. **4th Issue:**  When I click the BackSpace it clears the textbox as I explained in the 2nd Issue. But this is not the only issue. It clears the textbox but not calling the onChange event which updates mine react state. So, the textbox clears but the state has still value. 

5. **5th Issue:** If use disableClickEventBubbling: true & disableSelectionOnClick: true then this means the cell/row is not selectable right? then why I can see a blue border with a cell when I click on it?

5. **6th Issue:** This sixth is not like an issue but it's something related to the documentation. The documentation has clearly shown that how we can show disableClickEventBubbling [Screenshot](https://prnt.sc/11ux2zm) with columns. But there is no information in the documentation which can show us that how we can use disableSelectionOnClick. I'm not sure we should use disableSelectionOnClick with rows, columns, or tables. Like disableSelectionOnClick, we use columns.

**REASON WHICH I POSTED ISSUES LIKE THIS:** Because these are very important to me and I need their fix urgent as soon as possible.

**Comment by oliviertassinari** [comment]
> Because these are very important to me and I need their fix urgent as soon as possible.

@sajidfrommerqata we can't guarantee any resolution delay. It could take months.

**Comment by oliviertassinari** [comment]
I'm closing as no reproduction was provided an unrelated issues are bundled together
