### ISSUE TITLE
[docs] Data grid Feature comparison is outdated

### ISSUE THREAD

**Issue by nemonemi** [mui-org/material-ui-x#1462]
Hi, this question is pretty business specific, so I'm not sure if it should go to the Stackoverflow, here or through some other channel. Sorry in advance.

I'm evaluating XGrid for the project I'm working on, and I believe the feature comparison is not up to date.
https://material-ui.com/components/data-grid/getting-started/#feature-comparison

For example, there's documentation for the Cell editing, which should mean that it already exists, however the table where the features are compared shows that it is still in the works.

Is the table not up to date, or is my assumption incorrect?

Also, some of the links are broken. For example [Components](https://material-ui.com/components/data-grid/rendering/#components).

**Comment by oliviertassinari** [comment]
>  there's documentation for the Cell editing, which should mean that it already exists, however the table where the features are compared shows that it is still in the works.

@nemonemi Thanks for raising. We forgot to update this table in #1287

<img width="593" alt="Screenshot 2021-04-24 at 18 17 48" src="https://user-images.githubusercontent.com/3165635/115965397-63b54b80-a529-11eb-85ab-6aa45b09bcf2.png">

@dtassone do you want to fix it?

**Comment by dtassone** [comment]
Yes I will do ;)

**Comment by imsuvesh** [comment]
Fixed and created PR - https://github.com/mui-org/material-ui-x/pull/1516 🙂

**Comment by nemonemi** [comment]
While on the topic of this screen, I've also just noticed that the [Components](https://material-ui.com/components/data-grid/rendering/#components) link is broken.
It should actually lead to this one https://material-ui.com/components/data-grid/components/.
