### ISSUE TITLE
Data Grid Maximum depth exceeded

### ISSUE THREAD

**Issue by ReangeloJ** [mui-org/material-ui-x#1490]
Passing a function which setState to a component rendered in the renderCell property, causes an infinite loop.

The error I get is: "Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops."

For example when trying to open a rendered menu the error will occur.
 
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
Opening the menu causes an infinite loop 
 
## Expected Behavior 🤔
Should open the menu without an infinite loop
 
## Steps to Reproduce 🕹

```jsx
import React, {useState} from 'react';
import {DataGrid, GridCellParams, GridColDef, GridRowsProp} from '@material-ui/data-grid';
import {ListItem, ListItemIcon, ListItemText, Menu} from "@material-ui/core";
import {Delete, MoreHoriz} from "@material-ui/icons";

export default function Grid(props) {
    const [anchorEl, setAnchorEl] = useState();
    const open = Boolean(anchorEl);

    const handleMenuOpen = (e) => {
        setAnchorEl(e.target)
        console.log("When opening the menu I render an error")
    };

    const handleMenuClose = () => {
        setAnchorEl(null);
    }

    const menu = (params: GridCellParams) => {
        return (
            <>
                <MoreHoriz onClick={(event => handleMenuOpen(event))}/>
                <Menu
                    id="long-menu"
                    anchorEl={anchorEl}
                    keepMounted
                    open={open}
                    onClose={handleMenuClose}
                >
                    <ListItem button onClick={() => alert(JSON.stringify(params.row))}>
                        <ListItemIcon>
                            <Delete/>
                        </ListItemIcon>
                        <ListItemText primary="Gevelelement verwijderen"/>
                    </ListItem>
                </Menu>
            </>
        )
    }

    const rows: GridRowsProp = [
        {id: 1, col1: 'Hello', col2: 'World'},
        {id: 2, col1: 'XGrid', col2: 'is Awesome'},
        {id: 3, col1: 'Material-UI', col2: 'is Amazing'},
    ];

    const columns: GridColDef[] = [
        {field: 'col1', headerName: 'Column 1', width: 150},
        {field: 'col2', headerName: 'Column 2', width: 150},
        {
            field: "",
            headerName: "Acties",
            sortable: false,
            width: 120,
            disableClickEventBubbling: true,
            renderCell: (params) => menu(params)
        },
    ];

    return (
        <>
            <DataGrid rows={rows} columns={columns} pageSize={5} checkboxSelection/>
        </>
    );
}
```

https://codesandbox.io/s/material-demo-forked-migln?file=/demo.tsx

**Comment by dtassone** [comment]
I don't see any error in your codesandbox

**Comment by ReangeloJ** [comment]
@dtassone Yeah it's weird in codesandbox it doesnt error. But locally in my nextjs environment it does.

![image](https://user-images.githubusercontent.com/25207023/116075966-e9eda100-a693-11eb-8215-2e02fc01068e.png)

Thats the error I get when I copy my codesandbox and run it locally.

**Comment by Flodgar** [comment]
I have problem with Data Grid too, and it's really weird.
In my case i have simple Data Grid:
`<DataGrid rows={rows} columns={columns} autoHeight={true} />`

I also have Button in Appbar to open a Drawer
Everything works fine, but when i click on one of Data Grid column cells (it gets dotted border and changes sorting) and then I click on my button to open the Drawer, I get 2x Maximum depth exceeded error. (Drawer now opens/closes with delay)
I can click on grid cells, change maximum rows per page, or even do stuff with column menu or click on ASC DESC arrow in the column and it works without problem. Only when i click directly on the cell the problem starts and it disappears when component with Data Grid unmounts.
I don't even dare to replicate this, but can someone suggest a way to find out what is the source of the update loop?

**Comment by ryantomaselli** [comment]
I am seeing the exact same set of errors when rendering a Popover element inside renderCell

**Comment by ryantomaselli** [comment]
Got some good news (I think). Turns out if you set the **disableEnforceFocus** option (inherited from Modal) on the Popover the error doesn't come into play.
