### ISSUE TITLE
[DataGrid] AutoPageSize not resizing properly

### ISSUE THREAD

**Issue by houtblok** [mui-org/material-ui-x#1492]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When resizing the screen height, the bottom three rows will not move to the next page even though they do not fit on the current page. This means the bottom three rows are not accessible in that case. The rows only move to the next page when 4 or more rows no longer fit. This issue is present since Alpha.25. The issue does not appear in Alpha.23.

## Expected Behavior 🤔

The bottom rows should move to the next page accordingly when resizing the height.

## Steps to Reproduce 🕹

Code sandbox: https://codesandbox.io/s/youthful-brook-t664d?file=/src/Demo.tsx

Steps:

1. Have a dataGrid with rows and AutoPageSize on true. (See code Sandbox)
2. Resize your screen height so the bottom rows should no longer fit in the grid.
3. The bottom three rows do not move to the next page until more than 3 rows are not visible.

## Context 🔦

I am trying to make a responsive dataGrid for my application.

## Your Environment 🌎

<details>
  <summary>System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.906.0), Chromium (90.0.818.46)
  npmPackages:
    @material-ui/core: ^4.11.3 => 4.11.3
    @material-ui/data-grid: 4.0.0-alpha.23 => 4.0.0-alpha.23
    @material-ui/icons: ^4.11.2 => 4.11.2
    @material-ui/styles: ^4.11.3 => 4.11.3
    @material-ui/system:  4.11.3
    @material-ui/types:  5.1.0
    @material-ui/utils:  4.11.2
    @types/react:  17.0.3
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2</summary>
  
Browser: Google Chrome 90.
</details>

**Comment by dtassone** [comment]
I'm not able to reproduce it.
![image](https://user-images.githubusercontent.com/936978/116098714-938c5c80-a6ab-11eb-9317-58ae698c0c74.png)

Can someone else have a play? @m4theushw @DanailH @oliviertassinari

**Comment by houtblok** [comment]
Have you tried resizing it so 8 rows fit on the first page and 1 row on the second page? For me the rows only move to the next page at a minimum of 6 on the first page.

![image](https://user-images.githubusercontent.com/10481522/116100641-693b9e80-a6ad-11eb-8c3c-e79bb5e62714.png)

In this screenshot it has 9 rows on the first page, even though only 7 rows are visible. It will work as normal when smaller.

**Comment by dtassone** [comment]
Ok got it!

Thanks.

For the reproduction, it has to be done from a height that fit all rows on one page first, to 8 rows.

**Comment by oliviertassinari** [comment]
I have updated the reproduction so we can see the issue without depending on the screen height. I have also frozen the versions so if we need to come back to it in the future (after we release a fix), the reproduction will still show the bug.
