### ISSUE TITLE
[DataGrid] Triggering re-render in state change callbacks causes recursion/crash

### ISSUE THREAD

**Issue by jeffmccormick** [mui-org/material-ui-x#1498]
## Current Behavior 😯

If a re-render is triggered in a callback for one of the state change lifecycle handlers, the result is a recursive call that will eventually crash the tab. The callbacks in question are (at least) `onStateChange` and `onFilterModelChange`. For example, calling `setMyState(myNewState)` where `const [myState, setMyState] = React.useState({})` in one of these methods does really bad things.

## Expected Behavior 🤔

Recursion/crash does not occur or another API is provided that gracefully handles renders in callbacks.

## Steps to Reproduce 🕹

Minimal repro using the basic Filtering demo: https://codesandbox.io/s/jovial-architecture-9cziw

## Context 🔦

I would like to be able to update some state external to the data grid when the user interacts with the filters or sorting. This is the most straightforward way to do this with the current API and seems to be the intended use from https://github.com/mui-org/material-ui-x/pull/1113

## Your Environment 🌎

Details in the codesandbox. This has been reproduced in FF and Chrome.

**Comment by dtassone** [comment]
The grid is built on the immutability principle so every time you change the state, you cause the component to rerender, as you create a model and a handler every time you render, and update the state in the handler, it creates an infinite loop.

Refactor as below for your demo to work
```tsx
export default function BasicFilteringGrid() {
  const { data } = useDemoData({
    dataSet: "Commodity",
    rowLength: 100,
    maxColumns: 6
  });

  const [test, setTest] = React.useState(true);
  const handleFilterChange = React.useCallback((params) => {
    console.log("filter changed", params);
    // Uncomment me to crash!
    setTest((prev) => !prev);
  }, []);

  return (
    <div style={{ height: 400, width: "100%" }}>
      <DataGrid
        {...data}
        filterModel={{
          items: [
            {
              columnField: "commodity",
              operatorValue: "contains",
              value: "rice"
            }
          ]
        }}
        // Same problem for onStateChange
        // onStateChange={(model) => {
        onFilterModelChange={handleFilterChange}
      />
    </div>
  );
}
```

**Comment by jeffmccormick** [comment]
@dtassone Understood, thank you for the quick response. Did I miss this note in the docs somewhere? Along those lines, is it recommended that all props be memoized?

````js
const initialFilterModel = React.useMemo(() => ({ items: [ ... ] }));
````
