### ISSUE TITLE
setState leak after unmount

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#150]
@dtassone The issue was caught in the CI (Karma), something is calling setState after the component is unmounted. It leaks.

<img width="1327" alt="Capture d’écran 2020-08-05 à 00 32 02" src="https://user-images.githubusercontent.com/3165635/89351880-2ff07800-d6b3-11ea-83de-0027409929db.png">

---

@eps1lon this makes me think that we might have an improvement opportunity in the CI, shouldn't we fail if a component call console.warn or console.error during the tests? I believe it works when we run the tests in JSDOM, but not with Karma. I don't know why yet. The data grid might be an exception as all JSDOM tests are skipped (require layout).

**Comment by oliviertassinari** [comment]
@eps1lon Actually, I think that it's a regression from https://github.com/mui-org/material-ui/pull/21581.

1. `test/utils/init.js` runs for karma and jsdom
2. `test/utils/setup.js` runs for jsdom only

We moved the console throw logic from 1. to 2.

**Comment by eps1lon** [comment]
> We moved the console throw logic from 1. to 2. hence left karma without coverage

If karma had no warn/error logic then every test using toWarnDev/toErrorDev would throw.

Why would code from the main repo affect code in this repo?

**Comment by eps1lon** [comment]
Yeah so I had to investigate this more since you didn't communicate what you discovered: It's about unexpected calls not covering console warn/error, right? We should move this around, yes. PRs welcome.

**Comment by oliviertassinari** [comment]
@eps1lon I will look into it :)

**Comment by oliviertassinari** [comment]
Fixed in https://github.com/mui-org/material-ui/pull/22075
