### ISSUE TITLE
X Grid: Hidden & Rearranged Columns Do Not Maintain State Thru Re-render

### ISSUE THREAD

**Issue by jerry-sorrells** [mui-org/material-ui-x#1501]
I am using a licensed version of X-Grid in a UI with data updating at ~1Hz. When the page re-renders, columns that have been hidden or rearranged do not maintain state, i.e. hidden columns re-appear and rearranged columns return to their default positions. I believe the intent is for the user's changes to be retained through re-renders. I have searched the API documentation and support pages and do not see any mention of this behavior. Is there something I need to set to have the user changes maintain state through re-renders?

**Comment by dtassone** [comment]
Columns should be memoized in state. If you create a new array at each render it will reset the columns. The grid is based on immutability principle.
Please provide a codesandbox if you have a real issue.

https://material-ui.com/components/data-grid/columns/
As stated in the doc
```
The columns prop should keep the same reference between two renders. The columns are designed to be definitions, to never change once the component is mounted. Otherwise, you take the risk of losing the column width state (if resized). You can create the array outside of the render function or memoize it.
```

**Comment by jerry-sorrells** [comment]
Damien,

Thank you for the timely response. The issue (my issue) has been resolved. The documentation is clear; I obviously overlooked this. Thanks again.

**Comment by oliviertassinari** [comment]
Duplicate of #970
