### ISSUE TITLE
[DataGrid] Focus isn't set on the textbox

### ISSUE THREAD

**Issue by dtassone** [mui-org/material-ui-x#1502]
Focus isn't set on the textbox:

![bug 2](https://user-images.githubusercontent.com/3165635/114765997-25b86a80-9d66-11eb-8a27-bb03cc54a931.gif)

**Comment by oliviertassinari** [comment]
This issue is specific to this demo: https://material-ui.com/components/data-grid/editing/#edit-using-external-button
