### ISSUE TITLE
[DataGrid] Focus isn't set on the input type radio

### ISSUE THREAD

**Issue by dtassone** [mui-org/material-ui-x#1503]
Focus isn't set on the input type radio

![bug 3](https://user-images.githubusercontent.com/3165635/114766171-5ef0da80-9d66-11eb-805a-c3d81e5c850d.gif)

**Comment by oliviertassinari** [comment]
I believe it's only an issue with the documentation.

**Comment by ZeeshanTamboli** [comment]
Was trying to fix this but did not understand what's the issue here.

**Comment by oliviertassinari** [comment]
@dtassone Looking at https://github.com/mui-org/material-ui-x/issues/1503#issue-868683109 2 months later, it took me some guesswork to make sure I found the right way to reproduce. Please ALWAYS provide a reproduction when you open a bug.
