### ISSUE TITLE
[docs] Fill WIP section in the docs

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#1508]
This is self explanatory:

<img width="382" alt="Screenshot 2021-04-28 at 01 06 18" src="https://user-images.githubusercontent.com/3165635/116323280-f53ceb80-a7bd-11eb-9c76-2d9257572af3.png">

https://material-ui.com/components/data-grid/filtering/#controlled-filtering

**Comment by ThomasJanUta** [comment]
@oliviertassinari  Does WIP mean the controlled filtering functionality is already implemented and only the docs are missing?

Do I understand the controlled filtering functionality correctly?

- User clicks a chechbox which is located outside the table, for example: "red" ✔️
- controlled filtering kicks of a filter in the table: only red items are shown

I need to implement this controlled filter behavior for my project. I would like to contribute to the docs while doing this. I just need some basic pointers where I can find the functionality in the MUI code base and how to use it. 

I think I can figure the rest out myself and document it. 👍 

Thanks!

**Comment by oliviertassinari** [comment]
@ThomasJanUta As far as I know, we only miss the documentation. The controlled state is the state of the filter in the UI. ⚠️ It's independent of the action of filtering the rows.

- If you are using `filterMode="client"` (default), then the filter state of the UI will also be used to filter the rows.
- If you are using `filterMode="server"`, then the rows are left alone, you can do the transformation you wish.

Actually, this makes me think about the autocomplete and a point that @dtassone raised about how we could improve the filter state UI <-> rows state, as well as sorting state UI <-> rows state. In https://next.material-ui.com/components/autocomplete/#search-as-you-type, we give the developers a function to implement the filtering as they wish. Maybe this could replace `filterMode` 🤷‍♂️ .

From what I understand, #1378 should be closed. stopPropagation doesn't work, per the use case that @ThomasJanUta has raised:

> User clicks a chechbox which is located outside the table, for example: "red" ✔️

**Comment by dtassone** [comment]
@ThomasJanUta I think that the easiest way to do the feature you want would be by using the filter api.

```tsx
apiRef.current.upsertFilter: (item: GridFilterItem) => void
apiRef.current.applyFilters: () => void;
```

**Comment by flaviendelangle** [comment]
I'm closing this, we don't have any `WIP` on the doc anymore.
