### ISSUE TITLE
[DataGrid] How does custom sorting comparators work?

### ISSUE THREAD

**Issue by sajidfrommerqata** [mui-org/material-ui-x#1511]
It's quite clear that how we can create a custom comparator based on the numeric column as shown on this page:

[https://material-ui.com/components/data-grid/sorting/#custom-comparator](https://material-ui.com/components/data-grid/sorting/#custom-comparator).

**Code Example:**
`sortComparator: (v1, v2, param1, param2) => param1.row.age - param2.row.age,`

Can you reproduce this Code Example for the string column? For Example, I have a column in which I display full name and age(like Sajid Javed - 30) and I want to sort based on Full name.

This info is missing in the documentation.

You can reply with the new code sample here on Github. I think It will be just one line of code as above

Thank You

**Comment by m4theushw** [comment]
We have a custom sort comparator for a string column in this page: https://material-ui.com/components/data-grid/columns/#value-getter.

It would be something like that:

```js
sortComparator: (v1, v2, param1, param2) => `${param1.getValue('fullName')}`.localeCompare(param2.getValue('fullName')),
```

**Comment by oliviertassinari** [comment]
@m4theushw Is the idea to explicit each column type sortComparator in this demo https://material-ui.com/components/data-grid/sorting/#custom-comparator?

**Comment by sajidfrommerqata** [comment]
@m4theushw  @oliviertassinari  thank you for your response. The solution provided by @m4theushw is working but I will suggest adding demos of custom-comparators of all type to one page in the documantation

**Comment by m4theushw** [comment]
@oliviertassinari I don't know if we need to explicit them for each column type. We need to improve the docs on how the comparator works internally. Why it needs to return an integer? That's not clear. [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#description) has an extensive description of the sort function that we could leverage. A paragraph explaining how to use `localeCompare` could also be added.

@sajidfrommerqata Sure, we'll take your feedback into consideration to improve the documentation.

**Comment by oliviertassinari** [comment]
@m4theushw You are right, explaining the concept of sorting would be much better. My bad.

**Comment by oliviertassinari** [comment]
> and somewhere along the way it seems this api has changed.

@emily-ellevation A breaking change was introduced in #1513. 

@dtassone Maybe we could:

- Remove `hasFocus`, `cellMode`, and `tabIndex` from the output of `getBaseCellParams`. It doesn't seem to make any sense to provide them to the developers when they use the `valueGetter` property.
- Remove `getValue` from the output of `getBaseCellParams`, it creates an infinite loop when used. Already reported in #1564.
- Add the `getBaseCellParams()` output to the params (including `row`). We need to call it anyway to get the value, it won't impact performance at all.

**Comment by jessq** [comment]
can you please add `row` back so it's backward compatible? this is a breaking change for our team as well

**Comment by dtassone** [comment]
We should now be able to get rid of `GridSortCellParams` and just use `GridCellParams` as originally intended. `GridSortCellParams` was introduced to fix some perf issues but now perf should be optimal with `GridCellParams`

**Comment by oliviertassinari** [comment]
@dtassone A breaking change?

**Comment by dtassone** [comment]
I don't think so as `GridSortCellParams` should be interchangeable with `GridCellParams`, as `GridCellParams ` has more props
