### ISSUE TITLE
XGrid desktop resize not responding

### ISSUE THREAD

**Issue by Bidrman** [mui-org/material-ui-x#1554]
Hey, at desktop our Xgrid is not resizing properly and there is not enough space to display all columns it jsut starts hiding them from the last, but no scrollbar appears, sadly we got actions in the last column, so we cant control the grid when this happens

unfortunately I cant provide more then imagee just for now, but any idea, why this is happening would be great. I already spent several hours on solving this on my own and no luck.

![image](https://user-images.githubusercontent.com/31826605/116886536-7dd9e280-ac29-11eb-8e17-077366c3f217.png)

**Comment by Bidrman** [comment]
Apparently this has something to do with the fact, that last column doesnt have set width strictly and its width his fluid, due to unknown number of icons, that are gonna be inside.

**Comment by dtassone** [comment]
> Apparently this has something to do with the fact, that last column doesnt have set width strictly and its width his fluid, due to unknown number of icons, that are gonna be inside.

Interesting! It would be great to have a basic codesandbox so we can have a look and fix it asap.

**Comment by Bidrman** [comment]
> > Apparently this has something to do with the fact, that last column doesnt have set width strictly and its width his fluid, due to unknown number of icons, that are gonna be inside.
> 
> Interesting! It would be great to have a basic codesandbox so we can have a look and fix it asap.

will try to make it

**Comment by oliviertassinari** [comment]
Closing as there is no reproduction. Without a reproduction we can't iterate on it
