### ISSUE TITLE
[DataGrid] setSelectionModel(id) won't change current page for paginated grid

### ISSUE THREAD

**Issue by dngconsulting** [mui-org/material-ui-x#1555]
Hi,

My usecase is very straightforward but except by making expensive calculations I don't find any way to make it happen.
When I insert a new row in a paginated grid I want to highlight the newly inserted row. But if my grid is in page 1, it should automatically go to the page corresponding to setSelectionModel(id). For now, the row is selected but the page is not changed. Is it something feasible without playing with apiRef or calculating the target page ?

Thanks

**Comment by oliviertassinari** [comment]
You control the rows, so you should be able to control the `page` and set the one you need. As for using the apiRef, you can retrieve the position of the row ID in the list if you have left sorting or filtering up to the data grid to handle.
