### ISSUE TITLE
Loading/No Rows Elements Positioning is Off

### ISSUE THREAD

**Issue by shoxter** [mui-org/material-ui-x#1556]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The loading indicator and the now rows indicator are positioned incorrectly.

## Expected Behavior 🤔

They should be positioned at the center of the body of the table.

## Your Environment 🌎
<details>
  <summary>`npx @material-ui/envinfo`</summary>
  Google Chrome 89.0.4389.90
  System:
    OS: Linux 4.9 Manjaro Linux
  Binaries:
    Node: 8.16.1 - ~/.nvm/versions/node/v8.16.1/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v8.16.1/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.16.1/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @material-ui/core: ^4.11.3 => 4.11.3 
    @material-ui/icons: ^4.11.2 => 4.11.2 
    @material-ui/lab: ^4.0.0-alpha.57 => 4.0.0-alpha.57 
    @material-ui/styles:  4.11.3 
    @material-ui/system:  4.11.3 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @material-ui/x-grid: ^4.0.0-alpha.27 => 4.0.0-alpha.27 
    @material-ui/x-license:  4.0.0-alpha.25 
    @types/react:  17.0.4 
    react: ^17.0.1 => 17.0.1 
    react-dom: ^17.0.1 => 17.0.1 

</details>

## Code
```
<Card
  raised={true}
  className={clsx("flex")}
>
  <Divider/>
  <br/>
  <Typography variant="h6">Shopping Cart</Typography>
  <br/>
  <XGrid
    columns={columns}
    rows={[]}
    disableColumnMenu={true}
    disableColumnSelector={true}
    disableMultipleSelection={true}
    disableSelectionOnClick={true}
    hideFooter={true}
    loading={cartLoading}
  >
  </XGrid>
</Card>
```
## Images

![image](https://user-images.githubusercontent.com/19478126/116901234-aa7d0280-ac07-11eb-8e49-74a099245eb4.png)
![image](https://user-images.githubusercontent.com/19478126/116901312-c2ed1d00-ac07-11eb-864a-070fa3842376.png)

## Order id 💳
23151

**Comment by dtassone** [comment]
It seems like an issue while integrating with a card.

Would it be possible to get a code sandbox of the issue?

**Comment by shoxter** [comment]
> It seems like an issue while integrating with a card.
> 
> Would it be possible to get a code sandbox of the issue?

Here you are: https://codesandbox.io/s/x-grid-bug-jqy64

**Comment by shoxter** [comment]
@oliviertassinari Is this not a bug?

**Comment by oliviertassinari** [comment]
@shoxter It's a support request. I leave it to @dtassone to link the right documentation section.

**Comment by dtassone** [comment]
It seems like an issue with the dimensions of the grid due to the CardContent style...
I believe this part of the doc should help
https://material-ui.com/components/data-grid/layout/

**Comment by oliviertassinari** [comment]
👍 

> By default, the grid has no intrinsic dimensions. It occupies the space its parent leaves.

**Comment by shoxter** [comment]
> It seems like an issue with the dimensions of the grid due to the CardContent style...
> I believe this part of the doc should help
> https://material-ui.com/components/data-grid/layout/



> > By default, the grid has no intrinsic dimensions. It occupies **the space its parent leaves**.

Thank you both very much. After applying flex classes to the parents and grid, all is well.

I didn't realize the `DataGrid` docs applied to the `XGrid` component. That's good to know! Thanks again!
