### ISSUE TITLE
Ability to disable Export button in Toolbar

### ISSUE THREAD

**Issue by jamintz** [mui-org/material-ui-x#1557]
I'm using the GridToolbar component for the columns / filters / density adjustment capabilities. It seems like an export button was recently added in a new update. We expressly don't want this functionality for security reasons (people should be able to view and use the data with the features we provide via the table, but should not be able to download it). I looked at the Toolbar API documentation and didn't see the ability to hide this feature.

Did I miss this functionality, or if it doesn't exist could it be added in?

- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Order id 💳
21172

**Comment by dtassone** [comment]
you can recompose your toolbar
https://material-ui.com/components/data-grid/components/#toolbar
