### ISSUE TITLE
XGrid is re rendering every second or so 

### ISSUE THREAD

**Issue by peppermint-juli** [mui-org/material-ui-x#1558]
Hey everyone! 
My eng team and I are trying to manage the app state `on visibility change`, meaning when a column is hidden or shown we need to call a method that saves this state. First of all there isn't even a native method to the XGrid that allows developers to manage this, so this might be a separate issue in the near future, but for now we found a way around it and tried using `onStateChange` that has a `params` object that we could use to track it but this method gets fired every second or so, which affects performance and memory. So all this to ask, why is XGrid re rendering every second or so? How can we prevent this? The hidden columns get shown again (meaning the grid state lost) out of the blue, because XGrid decides to re render out of nowhere. 

Here's a Code SandBox link. I basically altered the code from the XGrid demo with the `onStateChange` and the browser window freezes and I have to close it. 
https://codesandbox.io/s/material-demo-forked-sb1h1?file=/demo.tsx

Thanks in advance!

## Order ID 💳 
 # 18479

**Comment by dtassone** [comment]
closing as its related to #1560

**Comment by oliviertassinari** [comment]
> XGrid is re rendering every second or so

@peppermint-juli The codesandbox you have provided doesn't demonstrate this. It's invalid.

**Comment by peppermint-juli** [comment]
You probably didn't even see the console. It logs almost 20 times for each action you take with the XGrid. Scroll, open vertical menus, virtually anything.

**Comment by peppermint-juli** [comment]
Yeah! Definitely looks like #569
