### ISSUE TITLE
[DataGrid] Expose onColumnVisibilityChange prop

### ISSUE THREAD

**Issue by dtassone** [mui-org/material-ui-x#1565]
We had issues created whereby users require to get the updated columns when their visibility changes

- [ ] Add prop `onColumnVisibilityChange`
- [ ] Add `apiRef.current.setColumnVisibility(field: string, value: boolean)`
- [ ] Add demo in the doc

relate to #1507 , #1441 , #1412, #1560

**Comment by oliviertassinari** [comment]
to detail on the linked issue:

- #1507 the root cause: export data of the table
- #1441 the root cause: #820 "when we reload the page, we still show the same view"
- #1412 I don't understand, how is the problem or even the solution similar?

**Comment by dtassone** [comment]
https://github.com/mui-org/material-ui-x/issues/1412#issuecomment-819697826

**Comment by DanailH** [comment]
> [#1412 (comment)](https://github.com/mui-org/material-ui-x/issues/1412#issuecomment-819697826)

I will start working on this. I went through the linked issues and the discussions but there is one thing that I need to clarify. In the linked comment there is a mention of adding a prop `hiddenColumnModel`. Do we still need it? I'm asking because it isn't listed in the ticket description.

**Comment by dtassone** [comment]
Thanks for raising the `hiddenColumnModel` question.

so we have 2 ways.

1. We keep the `hide` prop in `ColDef`, straightforward change, just add the option, and api method
 - Issue useColumns comes with hide option by default, tightly coupled.
 
2. We make it an independent feature, and add a model, its own hook, api, state, and handler
 - So ultimately, you can remove the feature independently of the columns
 - it would be easier for users to show/hide columns
 - It would be probably easier to maintain as it would be in its own unit of work


I think at this stage, we should go for 1., and maybe refactor at some point later.

**Comment by oliviertassinari** [comment]
On the naming, if we call the callback `onColumnVisibilityChange` shouldn't we name the state `columnVisibility` for consistency?

**Comment by dtassone** [comment]
if we go for 1. there would not be a new visibility state at this stage.

**Comment by oliviertassinari** [comment]
@dtassone 👍 for solving #1412 (option 1) after the stable release. It doesn't seem required now

**Comment by DanailH** [comment]
Alright, thanks for clearing it up @dtassone. I will proceed with option 1. We can discuss the detains in the PR once its opened 😉

**Comment by piotrdytkowski** [comment]
Event is fired when a single column visibility changes (when using hide and using menu show columns), but it seems it's not triggered, when using `show all` and `hide all`. Is there a way to get a handler to these events?

**Comment by oliviertassinari** [comment]
@piotrdytkowski I have added this bug into https://github.com/mui-org/material-ui-x/issues/1412#issuecomment-860935241
