### ISSUE TITLE
Weird interaction with apollo-client

### ISSUE THREAD

**Issue by byF** [mui-org/material-ui-x#1568]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

This is an odd esoteric issue , I know. I'm using `apollo-client` which has its own set of problems but essentially:

We have multiple tabs, when you change a tab we fetch different data. This causes the table to re-render. The subscription is established on the initial mount and its TCP connection should stay open.

When `XGrid` (or `DataGrid`) is present in the component, unmounting the component causes apollo-client subscription to prematurely close. Then it's able to reconnect after the second(!) time when it's mounted again. This happens if when I move the subscription into the parent component.

I reimplemented the whole `useSubscription` hook of apollo-client just to make sure it does happen only when `XGrid` is present. More details in the context.

## Expected Behavior 🤔

It doesn't happen :)

## Steps to Reproduce 🕹

I tried various combinations, but this seems like a minimal example

```react
import React from 'react'
import { useSubscription } from '@apollo/client'

const MyComponent = ({subscriptionQuery, variables}) => {
    const { data: subscriptionData, error: subscriptionError } = useSubscription(subscriptionQuery, {
      variables,
      shouldResubscribe: true, // doesn't matter
      fetchPolicy: 'network-only', // doesn't matter
    })
    
    // This causes websocket to close on unmount (both logLevel and logger doesn't matter)
    // return <XGrid logLevel="debug" logger={console} columns={[]} rows={[]} />

    // This doesn't
    return <div>{JSON.stringify(variables)}</div>
}
```

## Context 🔦

apollo-client uses zen-observable underneath.

I wonder is there anything XGrid does on unmount which might somehow interact with that library? Maybe it throws some error which wrecks some mayhem? or some global space pollution? I don't know, this is mega weird 🤷🏻‍♂️

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
System:
    OS: Linux 4.19 Ubuntu 18.04.5 LTS (Bionic Beaver) on WSL2; Windows 10.0.19043 Build 19043
  Binaries:
    Node: 14.16.1 - /tmp/fnm_multishell_5978_1620217744258/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.12 - /tmp/fnm_multishell_5978_1620217744258/bin/npm
  Browsers:
    Firefox: 88.0.1
```
</details>

## Order id 💳
17499 @fsommers

**Comment by dtassone** [comment]
That sounds weird.

No we don't throw errors or touch the global space.
We actually don't do anything special besides clearing all events listeners that are attached to the grid for memory leaks...
We are also clearing all event listeners that are attached to the apiRef event emitter.

These tasks should be isolated from the apollo subscription. Not sure what is happening TBH, I would need to debug. Is there any way you could provide a codesandbox so we can take a look

**Comment by oliviertassinari** [comment]
> Is there any way you could provide a codesandbox so we can take a look

I would reinforce this point. We close issues after a few days if we can't reproduce them.

**Comment by byF** [comment]
We decided to solve this another way, it wasn't possible to determine the root cause 🤷🏻‍♂️

**Comment by oliviertassinari** [comment]
@byF My guess would be a timeout that a heavy component that XGrid triggers (a lot of JS blocking time).
