### ISSUE TITLE
[XGrid] Rename apiRef methods

### ISSUE THREAD

**Issue by dtassone** [mui-org/material-ui-x#1569]
No need of `fromField` as `field` is the id of a column
Similarly for rows, no need of `fromId` 

```diff
- getColumnFromField: (field: string) => GridColDef;
+ getColumn: (field: string) => GridColDef;
```

```diff
- getRowFromId: (id: GridRowId) => GridRowModel;
+ getRow: (id: GridRowId) => GridRowModel;
```

We have left `getRowIdFromRowIndex` which makes more sense 🤔

**Comment by oliviertassinari** [comment]
> We have left getRowIdFromRowIndex which makes more sense 🤔

It looks like `getDisplayedRowAtIndex` that AG Grid has but it's not clear if it's the same. What is the index relative to?

**Comment by dtassone** [comment]
> > We have left getRowIdFromRowIndex which makes more sense 🤔
> 
> It looks like `getDisplayedRowAtIndex` that AG Grid has but it's not clear if it's the same. What is the index relative to?

Yes it's the same except that we return the id instead of the row model.
`getDisplayedRowAtIndex` => better name. I think we should refactor to this name and change the return type as well.

**Comment by m4theushw** [comment]
> I think we should refactor to this name and change the return type as well.

This change won't be transparent. Because there's the `getRowId` prop we can't get the id from `row.id`. Related to #1377.
