### ISSUE TITLE
[Datagrid] Lag and Performance Issues using [Autocomplete] component with RenderCell

### ISSUE THREAD

**Issue by reygj** [mui-org/material-ui-x#1576]
The issue is present in the latest release.
 I have searched the issues of this repository and believe that this is not a duplicate.

### Current Behavior
Using material ui Datagrid with RenderCell with Autocomplete component the page starts lagging too much.

### Expected Behavior
I didnt expect this lag and it does not happen usually on the example datagrids. It works without lagging

### Steps to Reproduce
Steps:

Visit https://codesandbox.io/s/material-demo-forked-fqigr
Try to move from left to right on the datagrid
The datagrid will lag a lot

Code example of the custom column:
```javascript

{
    field: "lastName",
    headerName: "lastName1",
    disableClickEventBubbling: true,
    width: 200,
    renderCell: (params1) => {
      return (
        <Autocomplete
          options={["1", "2"]}
          defaultValue={params1.getValue("lastName")}
          getOptionLabel={(option) => option}
          style={{ width: "100%", paddingTop: 20 }}
          renderInput={(params) => (
            <TextField
              {...params}
              defaultValue={params1.getValue("lastName")}
            />
          )}
        />
      );
    }
  }

```

**Comment by oliviertassinari** [comment]
@reygj The reproduction is invalid, please cleanup the error first. e.g. "Warning: Encountered two children with the same key, `lastName`"

**Comment by oliviertassinari** [comment]
Also a bit similar to https://github.com/mui-org/material-ui-x/issues/569#issuecomment-808727136

> It seems that TextField is simply too slow for this use case.

**Comment by dtassone** [comment]
I suggest we take a look at this issue after we merge #1513

**Comment by oliviertassinari** [comment]
I'm closing as the reproduction is not valid (https://github.com/mui-org/material-ui-x/issues/1576#issuecomment-833457320)
