### ISSUE TITLE
[DataGrid] onColumnResize rename to onColumnSizeChange

### ISSUE THREAD

**Issue by dtassone** [mui-org/material-ui-x#1581]
follow up from https://github.com/mui-org/material-ui-x/pull/1574#issuecomment-833554471

Discussion around renaming
- onColumnResizeCommitted =>  onColumnSizeChange
- onColumnResize => becomes an event as it's a secondary use case. Debates to onColumnSizeChangeCommitted / afterChange...

**Comment by flaviendelangle** [comment]
Relates to #1967 

https://github.com/mui-org/material-ui-x/pull/1967

Do will still want to rename it that way after this PR #1967 
The naming would be a bit confusing for me:

- `onColumnWidthChange` triggers at the end of a resize process
- `onColumnSizeChange` triggers several times during the resize process
