### ISSUE TITLE
[DataGrid] Fix width calc for fluid column on resize 

### ISSUE THREAD

**Issue by dtassone** [mui-org/material-ui-x#1582]
Just need to hook to resize event to trigger a new calculation of column width when the grid resize

Discussed in #1574 

issue explained in #1554

**Comment by oliviertassinari** [comment]
This GitHub issue doesn't seem ready to be worked on. We haven't finished the discussion on #1574 yet. The best illustration is this issue's description not containing any details on 1. the problem nor 2. the solution considered, 3. nor the actual solution we are going with.
