### ISSUE TITLE
X-Grid maximum depth exceeded (onStateChange)

### ISSUE THREAD

**Issue by yevgenypats** [mui-org/material-ui-x#1584]
When using `onStateChange` and for example triggering `setState` (inside the callback) this will trigger onStateChange recursively because the component will re-render. which makes `onStateChange` pretty unusable or maybe only if you want to print it to the console but usually you want to set it in your own state to use it later.

## Current Behavior 😯

As above

## Expected Behavior 🤔

I'd expect `onStateChange` not to be called on first render.

**Comment by oliviertassinari** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://material-ui.com/r/issue-template) _may_ be a good starting point. Thank you!
