### ISSUE TITLE
[DataGrid]  hide column header and disable cells sorting of specific columns

### ISSUE THREAD

**Issue by thomas-topway-it** [mui-org/material-ui-x#1612]
- [ x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

DataGrid is missing an option to hide the header of specific columns.
Because often not all columns are expected to be sorted, and because
columns with actions do not require an header, this appears to be
a critical feature.

(see screenshot below: all columns are sortable and this is not
the wanted behavior)

![datagrid_screenshot](https://user-images.githubusercontent.com/46287689/117575647-c561e200-b0f3-11eb-9693-ceb3183880c9.jpg)

**Comment by DanailH** [comment]
Hi, @thomas-topway-it thanks for raising this. Did you try this regarding disabling the column sorting https://material-ui.com/components/data-grid/sorting/#disable-sorting? 

Regarding the second problem about removing the header - a possible workaround would be to add `headerName` in the column definition and empty space as a value. You can check it here https://codesandbox.io/s/material-demo-forked-n385u?file=/demo.js

**Comment by thomas-topway-it** [comment]
Hello DanailH,
my fault, I did not see that option.
And is there an option to hide the  header divider ?

![Screenshot from 2021-05-10 12-26-15_cropped_arrow](https://user-images.githubusercontent.com/46287689/117631918-c9dad900-b18d-11eb-9d36-18d2ba564fc8.png)
