### ISSUE TITLE
[DataGrid] horizontal scroll behavior is different between light mode and dark mode

### ISSUE THREAD

**Issue by trfv** [mui-org/material-ui-x#1613]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

DataGrid horizontal scroll behavior is different between light mode and dark mode.

https://user-images.githubusercontent.com/35182743/117580602-aa16c700-b133-11eb-8d1b-27ccf870a3a0.mov

## Expected Behavior 🤔

Dark mode behavior should be the same as light mode one.

## Steps to Reproduce 🕹

You can try it here.
https://material-ui.com/components/data-grid/components/

## Context 🔦

I tried to implement dark mode, and found this bug.
The difference may come from here.
https://github.com/mui-org/material-ui-x/blob/master/packages/grid/_modules_/grid/components/containers/GridRootStyles.ts#L331-L363

## Your Environment 🌎
macOS Big Sur version 11.2.3
Google Chrome 90.0.4430.93（Official Build） （x86_64）

**Comment by oliviertassinari** [comment]
Interesting, yeah, we know about this when we picked the current implementation: https://github.com/mui-org/material-ui-x/issues/660#issuecomment-737898772

**Comment by oliviertassinari** [comment]
@trfv Could you provide an isolated codesandbox that reproduces the issue? I have removed the docs label as it's not specific to our docs.

**Comment by dtassone** [comment]
> I have removed the "docs" label as it's not specific to our docs (it's only one way to reproduce it). We can create the same reproduction in codesandbox simply by enabling the dark mode: https://codesandbox.io/s/material-demo-forked-pt05q?file=/demo.tsx.

I don't see a horizontal scrollbar on this codesandbox 🤔

**Comment by dtassone** [comment]
Yes I have the auto setting.

![image](https://user-images.githubusercontent.com/936978/117685808-8fd1fd00-b1b6-11eb-8961-186be52066a6.png)

🤔

**Comment by socramm** [comment]
Are there any plans to change this behavior in the future? My customer is not pleased that a horizontal scrollbar is visible when not clearly needed.

I am currently looking for a workaround. Is it maybe possible to always use the default scrollbar regardless of dark or light mode?

A other solution that I am thinking of in the moment is to check programmatically if a header is overflowing and hide the scrollbar based on that.

**Comment by Primajin** [comment]
Also we have the issue that the scrollbars in dark mode don't automatically read the global theme colors but rather have some colors and borders hardcoded.

Our normal scrollbars in dark mode on Windows vs the ones in datagrid:
<img src="https://user-images.githubusercontent.com/1742115/119114855-d16c6e80-ba26-11eb-93e3-d4197e61d510.png" /><img src="https://user-images.githubusercontent.com/1742115/119114852-d0d3d800-ba26-11eb-8428-4f12046d8d2f.png" />

Relates to: https://github.com/mui-org/material-ui/issues/25016

**Comment by oliviertassinari** [comment]
Interesting. In mui-org/material-ui#25016 , I was proposing to expose `darkScrollbar` so developers could override other scroll containers, like the one of this component.

In your case, we might need to have a dedicated theme variable. But maybe we can be smart about it and start from the background color.

**Comment by oliviertassinari** [comment]
I have opened #1805 to use the opportunity found by Matheus.
