### ISSUE TITLE
Localization - deDE - wrong translation of "hide" - should be "Ausblenden"

### ISSUE THREAD

**Issue by klinge27** [mui-org/material-ui-x#1621]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Click on the column header of the data grid to hide a column. The "hide" string of localization "deDE" is "Verstecken" but should be "Ausblenden". 

## Expected Behavior 🤔

The expected translation should be "Ausblenden".

## Steps to Reproduce 🕹

Steps:

1. Set the localization of the theme to "deDE"
2. Set up a datagrid with some columns
3. Click on a column to hide the column
4. The "hide" translation is incorrect

## Context 🔦

Localization - deDE

## Your Environment 🌎

+-- @material-ui/data-grid@4.0.0-alpha.27

## Order id 💳

None

**Comment by DanailH** [comment]
Hi, @klinge27 thanks for catching this. Would you like to open a PR with the fix? 😊

```diff
--- a/packages/grid/_modules_/grid/locales/deDE.ts
+++ b/packages/grid/_modules_/grid/locales/deDE.ts
@@ -61,7 +61,7 @@ const deDEGrid: Partial<GridLocaleText> = {
   columnMenuLabel: 'Menu',
   columnMenuShowColumns: 'Zeige alle Spalten',
   columnMenuFilter: 'Filter',
-  columnMenuHideColumn: 'Verstecken',
+  columnMenuHideColumn: 'Ausblenden',
   columnMenuUnsort: 'Sortierung deaktivieren',
   columnMenuSortAsc: 'Sortiere aufsteigend',
   columnMenuSortDesc: 'Sortiere absteigend',
