### ISSUE TITLE
[docs] Improve commodity to add edition on columns

### ISSUE THREAD

**Issue by dtassone** [mui-org/material-ui-x#1625]
How about we do desk as not editable, and all the rest editable? 

Filled quantity can be sort of slider...
Currency can be a dropdown same for status
IsFilled boolean column type

**Comment by dtassone** [comment]
We could then add an `editable:boolean` option in `useDemoData` that would be false by default

**Comment by oliviertassinari** [comment]
@dtassone this sounds great
