### ISSUE TITLE
Running "npm run start" fails to compile

### ISSUE THREAD

**Issue by DanailH** [mui-org/material-ui-x#163]
I pulled the latest changes and after running the project locally it fails to compile. Running the build also doesn't work.

The issue I'm getting is related to missing `next` folder inside the `docs` folder.

The commit from which this problem started is this one -> https://github.com/mui-org/material-ui-x/pull/144

PS: If this is not the right way to create issues please point it out and I'll update it.

**Comment by dtassone** [comment]
Thanks for raising it. Not sure about the format of the issues.
But I think it would be very helpful if you could add the error you're getting, as well as the steps to reproduce the issue.

**Comment by oliviertassinari** [comment]
> PS: If this is not the right way to create issues please point it out and I'll update it.
> Not sure about the format of the issues.

Assuming that we will only host the enterprise components here (moving the MIT DataGrid to the main repo), how we handle issues for the commercial licenses could diverge from how we handle issues for the MIT licenses if we find interesting things to leverage.

A quick benchmark:

- ag-grid: 
community: GitHub issues / StackOverflow https://stackoverflow.com/questions/tagged/ag-grid
enterprise: Zendesk https://ag-grid.com/javascript-grid-set-license/
- Kendo: custom made https://www.telerik.com/account/support-tickets/my-support-tickets
- Synfustion: custom made https://www.syncfusion.com/support/directtrac/incidents
- Ignite: custom made https://www.infragistics.com/my-account/submit-support-request/android
- Sencha: custom made https://www.sencha.com/support/
- DevExpress: custom made https://supportcenter.devexpress.com/ticket/list

Maybe we could start with a GitHub only approach, starting from [these issues templates](https://github.com/mui-org/material-ui/tree/next/.github/ISSUE_TEMPLATE), and see how that goes?

**Comment by oliviertassinari** [comment]
Do we need to keep the "start" commands in the packages? For instance, what if we remove?

https://github.com/mui-org/material-ui-x/blob/2895d51186cc18ac903b6be37c552dc40a43baa4/packages/license/package.json#L40
