### ISSUE TITLE
alpha25+ requires ECMAScript 2018 

### ISSUE THREAD

**Issue by john-shaffer** [mui-org/material-ui-x#1630]
https://github.com/mui-org/material-ui-x/commit/348a6731494faebeedebf48266c576d8e353da3e introduced the use of Unicode property escapes in a regular expression. This change means that projects using DataGrid/XGrid have to be compiled to ES9 or later, whereas in v4.0.0-alpha24 ES5 seems to work fine. Considering the widespread usage of Material UI and the drastic change in compatibility, this could be a problem for a lot of projects.

I couldn't find any information on what versions Material UI intends to be compatible with or if this would be considered a bug, so this issue can help document those things as well.

**Comment by oliviertassinari** [comment]
> I couldn't find any information on what versions Material UI intends to be compatible with or if this would be considered a bug, so this issue can help document those things as well.

https://next.material-ui.com/getting-started/supported-platforms/#browser

**Comment by oliviertassinari** [comment]
vs. https://caniuse.com/mdn-javascript_builtins_regexp_property_escapes it looks like we are good.

**Comment by oliviertassinari** [comment]
> I couldn't find any information on what versions Material UI intends to be compatible with or if this would be considered a bug, so this issue can help document those things as well.

This also resonates with #50. In the core, we use [.browserslistrc](https://github.com/mui-org/material-ui/blob/next/.browserslistrc) with Babel to transpile what we need, a feature TypeScript doesn't support: https://github.com/microsoft/TypeScript/issues/19183
