### ISSUE TITLE
Helper types for @material-ui/data-grid are not being exported in v4.0.0-alpha.28

### ISSUE THREAD

**Issue by maryschmidt** [mui-org/material-ui-x#1654]
The following types are not currently exported in v4.0.0-alpha.28: 

`import { Columns, RowModel, SortModelParams, ValueFormatterParams } from '@material-ui/data-grid';`

It's helpful having access to these when typing our components.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The types listed above are not exported.

## Expected Behavior 🤔

The types are exported.

## Steps to Reproduce 🕹

https://codesandbox.io/s/typescript-playground-export-forked-s3poj?file=/index.ts

Steps:

1. Check out the import line in the Code Sandbox

## Context 🔦

We have been importing these types in our components to strongly type the params we send to the DataGrid component

## Your Environment 🌎

Chrome browser
  
```
System:
    OS: macOS 11.2.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 812.81 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.5.1 - ~/.nvm/versions/node/v15.5.1/bin/node
    npm: 7.3.0 - ~/.nvm/versions/node/v15.5.1/bin/npm
```

```json
{
  "compilerOptions": {
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "strictBindCallApply": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "alwaysStrict": true,
    "esModuleInterop": true,
    "declaration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "target": "ES2017",
    "jsx": "react",
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```
</details>

**Comment by dtassone** [comment]
we prefixed every types with `Grid` now to avoid conflicts with other components

**Comment by oliviertassinari** [comment]
For the others that will wonder how to handle the breaking change, and which version to revert to: https://github.com/mui-org/material-ui-x/releases/tag/v4.0.0-alpha.21.
