### ISSUE TITLE
Up to date row props not available for cell editing

### ISSUE THREAD

**Issue by jamintz** [mui-org/material-ui-x#1658]
I'm not sure if this is a bug or working as expected and I'm doing something wrong… I also posted on StackOverflow here: https://stackoverflow.com/questions/67511218/material-ui-datagrid-row-prop-not-updating-with-editable-cell and there's a replication of the issue here: https://codesandbox.io/s/material-demo-forked-tkwji?file=/demo.js

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When accessing the "row" props for a rendered editable cell, the props reflect the initial values of the row, NOT the current values after updates are made

## Expected Behavior 🤔
Props should be the current values of the row, not the initial value (or there should be a way to access them in the location I'm logging from in the example), but again entirely possible I'm doing something wrong and this is working as expected.

## Steps to Reproduce 🕹
https://codesandbox.io/s/material-demo-forked-tkwji?file=/demo.js

Steps:

1. Change firstname/lastname/fullname in any row by double-clicking and entering a new name
2. Change the rating for that row
3. In the console, observe that the row data logged is of the initial row, not the updated one

## Context 🔦
Making use of custom rendered cells and new editability features and trying to tie the two together, however I need to do some actions on editing based on not just the single-cell value but other (current) values from other cells in the row

## Your Environment 🌎
 System:
    OS: macOS 11.2.1
  Binaries:
    Node: 15.8.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Edge: Not Found
    Firefox: 84.0.1
    Safari: 14.0.3
  npmPackages:
    @material-ui/core: ^4.11.4 => 4.11.4 
    @material-ui/data-grid: ^4.0.0-alpha.27 => 4.0.0-alpha.27 
    @material-ui/icons: ^4.11.2 => 4.11.2 
    @material-ui/lab: ^4.0.0-alpha.58 => 4.0.0-alpha.58 
    @material-ui/styles:  4.11.4 
    @material-ui/system:  4.11.3 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @material-ui/x-grid: ^4.0.0-alpha.27 => 4.0.0-alpha.27 
    @material-ui/x-grid-data-generator: ^4.0.0-alpha.19 => 4.0.0-alpha.19 
    @material-ui/x-license:  4.0.0-alpha.25 
    @types/react:  17.0.1 
    react: ^17.0.0 => 17.0.0 
    react-dom: ^17.0.0 => 17.0.0 
    styled-components: ^5.0.0 => 5.2.1 

## Order id 💳
21172

**Comment by jamintz** [comment]
@dtassone to confirm – this is a bug? Expected behavior is what I wrote above?

**Comment by dtassone** [comment]
You forgot to add `row` in your dependency array of the `handleChange` function, for the `RatingEditInputCell` component.

```tsx
function RatingEditInputCell(props) {
  const { id, value, api, field, row } = props;

  const handleChange = React.useCallback(
    (event) => {
      console.log("row",row)
      const editProps = {
        value: Number(event.target.value),
      };

      api.commitCellChange({ id, field, props: editProps });
      api.setCellMode(id, field, 'view');
    },
    [api, field, id, row], // <= here is the fix
  );

  return (
    <div>
      <Rating value={Number(value)} onChange={handleChange} />
    </div>
  );
}
```

**Comment by jamintz** [comment]
…thank you

**Comment by oliviertassinari** [comment]
Actually, since the reproduction is coming from https://material-ui.com/components/data-grid/editing/#custom-edit-component and the useCallback adds nothing to the demo (arguable open doors for bugs and complexity), I would suggest we remove it in a follow up.

@jamintz did you fall into this trap because you copied this demo and didn't configure the eslint rule of hooks?

**Comment by jamintz** [comment]
@oliviertassinari correct
