### ISSUE TITLE
Switching to XGrid breaks DataGrid 

### ISSUE THREAD

**Issue by EdmundsEcho** [mui-org/material-ui-x#1670]
I just upgraded to the `XGrid` because the `DataGrid` stopped providing the flexible column-size feature.  I was expecting to be able to swap-out the components and experience the same layout and behavior, other than now having the additional features.

When I made the swap, the following stopped rendering as expected:

1. page size
2. page count
3. classNames in the overrides no-longer work (i.e., I have to find where I lost the ref)

Below I detail the page size issue:

### Before
```jsx
  //----------------------------------------------------------------------------
  // Data grid options
  // See the theme overrides for other formatting options
  const options = {
    headerHeight: 25,
    rowHeight: 35,
    hideFooterSelectedRowCount: true,
    components: {},
    onColumnHeaderClick: handleToggleAll,
  };

  return (
    <DataGrid
      className={clsx('EtlUnit-ValueGrid')}
      rows={rows}
      columns={columns}
      pageSize={5}
      onCellClick={handleToggleValue}
      disableColumnMenu={false}
      disableColumnSelector
      checkboxSelection
      autoHeight
      selectionModel={selectionModel}
      {...options}
      {...rest}
    />
  );
```
... renders a page size of 5 records with the page count at the bottom of the page.

### After
... renders all of the values.

### Suspected issue
The `autoHeight` works differently || the way the grid responds to the parent size is different.

**Comment by oliviertassinari** [comment]
> the DataGrid stopped providing the flexible column-size feature

This wasn't intended. Do you have more details?

**Comment by EdmundsEcho** [comment]
Sure.  Here is one thing I seemed to have found.  My `overrides` prop for `MuiDataGrid` is printed below.  Before getting to it, the only "take-away" is that it is nested and relies on a consistent layout.  I noticed in the `inspector` (Firefox-dev) the `MuiDataGrid-footer` is wrapped with an **extra** `<div>..</div>`.  It is empty and does not seem to do anything.  That div is not something I can work around because it does not have a classname.

Here is the the overrides:

```js
    //--------------------------------------------------------------------------
    /* DataGrid */
    MuiDataGrid: {
      root: {
        fontSize: '0.8rem',
        lineHeight: '0.8rem',
        fontFamily: 'Rubik',
        cursor: 'pointer',
        border: `none`,
        padding: '0',
        margin: '0',
        // DataGrid className
        '&.EtlUnit-ValueGrid': {
          // root and another class
          '& .MuiDataGrid-row': {
            opacity: '0.5',
            '&.Mui-selected': {
              opacity: '1',
              backgroundColor: 'inherit',
            },
          },

          // root and another class
          '& .MuiDataGrid-checkboxInput': {
            '& .MuiSvgIcon-root': {
              width: '1.0rem',
              height: '1.0rem',
            },
          },
          // root and another class
          '& .MuiDataGrid-footer': {    <<<< seems to break here due to extra div
            minHeight: '20px',
            maxHeight: '25px',
            // margin: `${spacingFn(3)}`,
            padding: `${spacingFn(0)}`,
            margin: `${spacingFn(2)} 0px`,
            backgroundColor: palette.grey[100],
            '& .MuiTablePagination-root': {
              '& .MuiTablePagination-toolbar': {
                minHeight: '20px',
              },
              '& .MuiToolbar-root': {
                '& .MuiTypography-body2': {
                  fontSize: '0.7rem',
                  lineHeight: '0.7rem',
                },
                '& .MuiTablePagination-actions': {
                  '& .MuiButtonBase-root': {
                    fontSize: '0.8rem',
                    lineHeight: '0.8rem',
                    padding: '3px',
                    '& .MuiIconButton-label': {
                      '& .MuiSvgIcon-root': {
                        fontSize: '1.2rem',
                      },
                    },
                  },
                },
              },
            },
          },

          // class tag
          '& .EtlUnit-CardHeader-TextField': {},
        },
      },
    },
```

**Comment by oliviertassinari** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://material-ui.com/r/issue-template) _may_ be a good starting point. Thank you!

**Comment by EdmundsEcho** [comment]
... have you heard of the adage: ask the right question, you likely have the answer?  Providing the minimal reproduction test is the equivalent of asking the right question :)).  I'll post the right question when I figure out that is.

**Comment by EdmundsEcho** [comment]
I think the most expeditious way to solve this is to get advice on what option I can use to set the classname of the footer and other components where the ref no-longer points to anything.  I'll look into in the docs.

**Comment by EdmundsEcho** [comment]
The solution I'm going with for now is to use both versions of the grid.  Fortunately, where I need the detailed control over formatting, I don't need the extra features the x-grid provides.

To the degree my experience has revealed a design consideration, and that I'm using the component as intended, here are some rough, top of mind thoughts.

* It is likely too constraining for you all to provide a version of the grid with extra functionality *without* having additional tags and wrappers as needed. Only you all know how much the features involve additional sub-components.

* If so, there are two options:
   1. Publish a separate set of classname tags, ideally mapped from MIT -> EULA license
   2. Maintain the "more advanced" set of tags in both versions using "dummy/id" placeholders; this of course could be frustrating for you all and inherently limiting at this early stage of the product development

All this to say, it is understandable that going from MIT -> EULA will brake some of the formatting, especially if it enables a faster iteration cycle.

If option 1 makes the most sense, I suspect that supporting additional `override` options is the most expeditious way to address the issue.  The reason my override code is so nested, is because where "I start" is determined/limited by the overrides that are recognized/supported by the Mui-theme provider.  The more that are supported, the more I can target starting at a root that is closer to the component of interest.

Finally, this approach would require a way to tag the subcomponents of the grid accordingly.  For instance, to "reach" the fontsize of the footer, given what combination of the supported overrides AND what I can tag when rending the grid:

```js
    MuiDataGrid: {
      root: {   // ...supported by the theme provider
        '&.Custom-ValueGrid-01': {     // custom selector: MuiDataGrid AND Custom-ValueGrid-01
          '& .MuiDataGrid-footer': {     // child of...
            '& .MuiTablePagination-root': {
              '& .MuiToolbar-root': {
                '& .MuiTypography-body2': {
                    fontSize: `0.7rem`   // 🎉 
```

Designing the two versions in-line with the overrides and grid-options for the classname tagging may:

1. obviate the need to support the above inherently fragile code 
2. enable a much more unified, if not perfectly so, methodology for formatting the sub-components of each version without constraining the ability to use different sub-components in each version; just "contract" to the overrides/options pairing to reach the contracted access points.

I hope this helps.  

Hands down, I really appreciate what the material-ui team provides to the community.

**Comment by oliviertassinari** [comment]
I'm closing as we have no reproduction and the information provided is not actionable. Thanks for taking the time.

**Comment by EdmundsEcho** [comment]
Here is the demo that demonstrates the issue.  What do you think?
[Sandbox](https://codesandbox.io/s/dank-dust-s5m3u?file=/src/Demo.tsx)

**Comment by oliviertassinari** [comment]
@EdmundsEcho The codesandbox is empty, did you save it?

**Comment by EdmundsEcho** [comment]
... now I did :))

**Comment by oliviertassinari** [comment]
@EdmundsEcho Thanks for the reproduction. The difference of behavior comes from the `pagination` prop. DataGrid has it set to true, while XGrid has it set to false.

**Comment by EdmundsEcho** [comment]
Fantastic.  I'm glad the fix was so easy to find at your end.  

Should I expect the formatting to work between the two?

**Comment by oliviertassinari** [comment]
> Should I expect the formatting to work between the two?

What do you mean?
