### ISSUE TITLE
[XGrid] Disable checkbox column resizing

### ISSUE THREAD

**Issue by elyesbenabdelkader** [mui-org/material-ui-x#1672]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Shouldn't the checkbox column width be fixed by default? and if not, how can we change it?

## Examples 🌈

This is a screenshot of what the user should not be able to do as it does not make any sense.
![](https://i.ibb.co/m4KGCYY/Screenshot-from-2021-05-15-18-16-20.jpg)
## Motivation 🔦

The checkbox column has fixed content and so it should not be resizable by default.

**Comment by oliviertassinari** [comment]
Agree, it doesn't seem to make sense to allow resizing the checkbox. This should be easy to fix.

Regarding customizing it, you can import this column, add it manually to the column definitions and override the resizing property.

**Comment by ZeeshanTamboli** [comment]
@oliviertassinari Why this issue did not get closed? Is it because related PR #1682 got merged in `next` branch?

**Comment by dtassone** [comment]
> @oliviertassinari Why this issue did not get closed? Is it because related PR #1682 got merged in `next` branch?

Fixed.
