### ISSUE TITLE
data grid - can't be horizontally scrolled when using it under element with dir="rtl" attribute 

### ISSUE THREAD

**Issue by shmuelhizmi** [mui-org/material-ui-x#1673]
when using the nonpremium data grid component under a parent element with the dir attribute set to "rlt" the grid can't be horizontally scrolled

- [x ] The issue is present in the latest release.
- [ x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

data grid can't be horizontally scrolled

## Expected Behavior 🤔

data grid to be be horizontally scrolled

## Steps to Reproduce 🕹

Steps:

1. install "@material-ui/core": "4.11.4"
2. create a parent div element with the dir attribute set to "rtl"
3. under it create a horizontally scrollable data grid
4. try to scroll it from right to left

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  System:
    OS: Linux 5.3 Debian GNU/Linux 10 (buster) 10 (buster)
  Binaries:
    Node: 14.9.0 - ~/.nvm/versions/node/v14.9.0/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 7.7.6 - ~/.nvm/versions/node/v14.9.0/bin/npm
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: 78.0.2
  npmPackages:
    @emotion/styled:  10.0.27 
    @material-ui/core: ^4.11.4 => 4.11.4 
    @material-ui/data-grid: * => 4.0.0-alpha.28 
    @material-ui/icons: ^4.11.2 => 4.11.2 
    @material-ui/styles:  4.11.4 
    @material-ui/system:  4.11.3 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @types/react: ^17.0.0 => 17.0.5 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.1.2 => 4.2.4
```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

**Comment by oliviertassinari** [comment]
Is it a duplicate of #230? I mean, what do you expect for the direction of the data grid?

**Comment by shmuelhizmi** [comment]
yeep, this is the same issue, sorry :)
