### ISSUE TITLE
[DataGrid] Does Not Properly Render Until Set Focus.

### ISSUE THREAD

**Issue by gvanriper** [mui-org/material-ui-x#1689]
I am setting a loading effect on a button when clicked on the row. This should then end the loading effect once the loading is set to false. The loading effect does not render until focus is set back to the DataGrid.

## Current Behavior 😯

I am setting a loading variable to disable the button and use the CircularProgress to let the user know it's loading. This gets stuck on disabled and the CircularProgress once it completes.

## Expected Behavior 🤔

Once the loading variable is set, Circular Progress and disabled should go away.

## Steps to Reproduce 🕹

See link for example:
https://codesandbox.io/s/datagrid-focus-issue-4nuvc

You'll notice that the the button does not go back to original state until there is a click event inside the grid. Note: I put a 3 second delay. You'll have to wait at least 3 seconds.

## Context 🔦

I'm trying to get the button to render without clicking inside the grid.

## Your Environment 🌎

  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 12.19.0 - C:\Program Files\nodejs\node.EXE      
    Yarn: Not Found
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.906.0), Chromium (90.0.818.62)

I am using Chrome myself. Not sure why it says Chrome not found.

**Comment by oliviertassinari** [comment]
@gvanriper check your operators and the notion of immutable array manipulation.

**Comment by oliviertassinari** [comment]
Please submit support requests and questions to StackOverflow using the tag [material-ui](http://stackoverflow.com/tags/material-ui). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/callemall/material-ui/blob/master/CONTRIBUTING.md).

**Comment by gvanriper** [comment]
@oliviertassinari , as far as I can tell, it is a bug which is why I reported it. Stacked Overflow typically is not helpful with the DataGrid.

I switched to slice and that appears to work. Thanks.
