### ISSUE TITLE
[XGrid] Updating rowCount on data fetch from remote API

### ISSUE THREAD

**Issue by PraveenPeri** [mui-org/material-ui-x#1698]
I am using XGrid to display data fetched from a REST API. I initially set the rowCount to 25 but trying to update it with the actual count(other than 25) once the API fetch is resolved which is not happening. The paginationMode is set to 'server'

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
rowCount displays the initial set value and only updates when interacted with the controls in the pagination bar

## Expected Behavior 🤔
rowCount is updated with the actual total returned by the API

## Steps to Reproduce 🕹

Steps:

1. Setup an XGrid to load data from an API with pagination mode set to 'server'
2. Try to set the rowCount to the "total" value returned by the API when resolving the promise

## Context 🔦

This setup is going to be most common scenario in our application where the data to the grid is being fed from APIs. So, we need the paging to reflect the actual count instead of skewed numbers.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  System:
    OS: Linux 4.14 Amazon Linux 2
  Binaries:
    Node: 14.15.4 - /usr/bin/node
    Yarn: Not Found
    npm: 7.10.0 - /usr/bin/npm
  Browsers:
    Edge
  npmPackages:
    @material-ui/core: ^4.11.3 => 4.11.3 
    @material-ui/data-grid: ^4.0.0-alpha.25 => 4.0.0-alpha.25 
    @material-ui/icons: ^4.11.2 => 4.11.2 
    @material-ui/lab: * => 4.0.0-alpha.58 
    @material-ui/pickers:  3.3.10 
    @material-ui/styles:  4.11.3 
    @material-ui/system:  4.11.3 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @material-ui/x-grid: * => 4.0.0-alpha.26 
    @material-ui/x-license:  4.0.0-alpha.25 
    @types/react: ^17.0.3 => 17.0.3 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    typescript: ^4.2.4 => 4.2.4 
```
</details>

**Comment by oliviertassinari** [comment]
**D**uplicate

**Comment by oliviertassinari** [comment]
@dtassone the upper case D is also important.
