### ISSUE TITLE
[XGrid]Disable filter operators in the toolbar

### ISSUE THREAD

**Issue by PraveenPeri** [mui-org/material-ui-x#1699]
This might not be a bug per se but I did not find any help or documentation on this anywhere. I have setup an XGrid getting data from a REST API. Since the API only supports 'equals' filtering, I would like to disable other operators like contains/starts with/ends with in the toolbar. With the filter mode is set to 'server', how can I accomplish that?

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
Couldn't find a way to disable the unnecessary operators.

## Expected Behavior 🤔
Unsupported operators can be disabled/hidden in the filters

## Steps to Reproduce 🕹

Steps:

1. Setup an XGrid/Datagrid with remote API and filter mode set to 'server'
2. Configure it to disable the operators not supported by the API

## Context 🔦
This could be really important for better user experience. Users trying to use filters should not be thrown off by the operators that are not supported by the APIs.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  System:
    OS: Linux 4.14 Amazon Linux 2
  Binaries:
    Node: 14.15.4 - /usr/bin/node
    Yarn: Not Found
    npm: 7.10.0 - /usr/bin/npm
  Browsers:
    Edge
  npmPackages:
    @material-ui/core: ^4.11.3 => 4.11.3 
    @material-ui/data-grid: ^4.0.0-alpha.25 => 4.0.0-alpha.25 
    @material-ui/icons: ^4.11.2 => 4.11.2 
    @material-ui/lab: * => 4.0.0-alpha.58 
    @material-ui/pickers:  3.3.10 
    @material-ui/styles:  4.11.3 
    @material-ui/system:  4.11.3 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @material-ui/x-grid: * => 4.0.0-alpha.26 
    @material-ui/x-license:  4.0.0-alpha.25 
    @types/react: ^17.0.3 => 17.0.3 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    typescript: ^4.2.4 => 4.2.4 
```
</details>

**Comment by dtassone** [comment]
https://material-ui.com/components/data-grid/filtering/

look at the `Custom column type.` demo code

**Comment by PraveenPeri** [comment]
That worked! Appreciate your help! Thanks!
