### ISSUE TITLE
[DataGrid] customizable aria-label or aria-labelledby field

### ISSUE THREAD

**Issue by slayybelle** [mui-org/material-ui-x#1700]
Current DataGrid doesn't seem to have a way to receive a user defined aria-label or aria-labelledby reference.  This is needed for accessibility.

- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Most components need a descriptive label for screen readers to identify them to users.  Current implementation of DataGrid seems to hardcode the label to "grid":

<img width="548" alt="Screen Shot 2021-05-18 at 1 12 10 PM" src="https://user-images.githubusercontent.com/32496958/118717304-c02f2200-b7da-11eb-8bef-86c48230e3e3.png">

<img width="596" alt="Screen Shot 2021-05-18 at 1 13 21 PM" src="https://user-images.githubusercontent.com/32496958/118717487-fd93af80-b7da-11eb-9b2f-fec4c780f0d6.png">

## Examples 🌈
Here's a devTool screenshot of this WAI aria page demonstrating accessible tables:  
https://www.w3.org/TR/wai-aria-practices/examples/grid/dataGrids.html

<img width="513" alt="Screen Shot 2021-05-18 at 1 16 45 PM" src="https://user-images.githubusercontent.com/32496958/118717786-56634800-b7db-11eb-9046-223cc21b3983.png">

## Motivation 🔦
a11y compliance

**Comment by oliviertassinari** [comment]
Related to #1290.

**Comment by ZeeshanTamboli** [comment]
So after we remove the `aria-label` attribute does this mean we could support an `aria-label` prop in DataGrid or they can set attribute via `ref`?
Also it is used in other components eg: `GridColumnHeaderSortIcon` etc

**Comment by oliviertassinari** [comment]
@ZeeshanTamboli Ideally, we would spread all the props on the root element. If it adds too much complexity, we could whitelist the relevant aria attributes. (aria-label, aria-labelledby, aria-describedby, id, etc)
