### ISSUE TITLE
[XGrid] onFilterModelChange is not called when changing the link operator

### ISSUE THREAD

**Issue by wjdwndud0114** [mui-org/material-ui-x#1701]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The `onFilterModelChange` callback is not called when you change the link operator on the filter.
This is a bug because when you have the `filterMode="server"` attribute, you rely on the callback to trigger updated requests to the server.

## Expected Behavior 🤔

The `onFilterModelChange` callback should be called with the updated filter model if you change the link operator on the filter.

## Steps to Reproduce 🕹

https://codesandbox.io/s/material-demo-forked-2nrlb

Steps:

1. Change the filter by adding another multi filter. This should change the "last filter change" ISO string shown below the table.
2. Change the link operator on the filter. This will not change the ISO string shown below the table.

## Context 🔦

Using the `filterMode="server" onFilterModelChange={onFilterChange}` attributes, data is fetched with the new filter model in `onFilterChange`. Changing the link operator results in an invalid state of data where the presented data does not match what is shown in the filter model.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  System:
    OS: macOS 11.0.1
  Binaries:
    Node: 16.1.0 - ~/.n/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.11.2 - ~/.n/bin/npm
  Browsers:
    Chrome: 90.0.4430.212 *** Used Chrome ***
    Edge: Not Found
    Firefox: Not Found
    Safari: 14.0.1
  npmPackages:
    @emotion/react: ^11.4.0 => 11.4.0
    @material-ui/core: ^4.11.0 => 4.11.2
    @material-ui/icons: ^4.5.1 => 4.11.2
    @material-ui/lab: ^4.0.0-alpha.57 => 4.0.0-alpha.57
    @material-ui/pickers: ^3.2.7 => 3.2.10
    @material-ui/styles:  4.11.2
    @material-ui/system:  4.11.2
    @material-ui/types:  5.1.0
    @material-ui/utils: ^4.10.2 => 4.11.2
    @material-ui/x-grid: ^4.0.0-alpha.27 => 4.0.0-alpha.28
    @material-ui/x-license:  4.0.0-alpha.28
    @types/react:  17.0.6
    react: 16.14.0 => 16.14.0
    react-dom: ~16.9.0 => 16.9.0
    typescript:  3.9.7
```
</details>

## Order id 💳

[Order #25281] (May 25, 2021)

**Comment by wjdwndud0114** [comment]
Hi @dtassone thank you for taking this issue. Can we escalate this issue as well as #1145 ? Purchased the pro plan and updated the issue description with the order ID.

**Comment by oliviertassinari** [comment]
@wjdwndud0114 #1706 will fix this issue
