### ISSUE TITLE
[docs] The description of apiRef is grammatically incorrect

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#1705]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

https://github.com/mui-org/material-ui-x/blob/e96be53e62d6a7f469a57f72cf3af3225972f012/packages/grid/_modules_/grid/models/api/gridParamsApi.ts#L9

https://github.com/mui-org/material-ui-x/blob/e96be53e62d6a7f469a57f72cf3af3225972f012/packages/grid/_modules_/grid/models/api/gridCsvExportApi.ts#L11

## Expected Behavior 🤔

```diff
-* Get the cell value of a row and field. 
+* Returns the cell value of a row and field. 
```

```diff
-* Export the grid data as CSV.
+* Exports the grid data as CSV.
```

## Context 🔦

This issue was spotted in #1620. @m4theushw has done it correctly which surfaces the inconsistency and consequently how the previous approach was not correct.

**Comment by oliviertassinari** [comment]
On a related now, with miss the `Grid` prefix in:

https://github.com/mui-org/material-ui-x/blob/e96be53e62d6a7f469a57f72cf3af3225972f012/packages/grid/_modules_/grid/models/api/columnMenuApi.ts#L4

**Comment by mbrookes** [comment]
"_done_ it correctly"
"On a related _now_"
" _with miss_ the Grid prefix"

Under the circumstances, should I mention them, correct them, or ignore them? 😅

**Comment by oliviertassinari** [comment]
@mbrookes Thanks, I have raised the issue as a low-priority because the descriptions will be visible once we complete: #1529.

**Comment by mbrookes** [comment]
> I could look careless

You could indeed 😆 

My comment was a joke about grammatical errors in the response to an issue about grammatical errors. I'll mark the whole exchange as off-topic. 😅
