### ISSUE TITLE
[DataGrid] `onPageChange` doesn't update the `page` when a pagination button is clicked

### ISSUE THREAD

**Issue by mattcarlotta** [mui-org/material-ui-x#1711]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

With the update to [4.0.0-alpha.29](https://github.com/mui-org/material-ui-x/releases/tag/v4.0.0-alpha.29), the `onPageChange` function no longer increment/decrements the `page`.

## Expected Behavior 🤔

Prior to v4.0.0-alpha.29 the `page` parameter from the `onPageChange` function would increment/decrement when a pagination button is clicked.

## Steps to Reproduce 🕹

Repo [here](https://github.com/mattcarlotta/datagrid-jsdom-bug/tree/pagination).

Instructions can be found [here](https://github.com/mattcarlotta/datagrid-jsdom-bug/blob/pagination/README.md).

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
System:
    OS: Linux 5.8 Linux Mint 20.1 (Ulyssa)
  Binaries:
    Node: 14.17.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 6.14.13 - /usr/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 88.0.1
  npmPackages:
    @emotion/react: ^11.4.0 => 11.4.0 
    @emotion/styled: ^11.3.0 => 11.3.0 
    @material-ui/core: ^4.11.4 => 4.11.4 
    @material-ui/data-grid: ^4.0.0-alpha.29 => 4.0.0-alpha.29 
    @material-ui/styles:  4.11.4 
    @material-ui/system:  4.11.3 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @types/react:  17.0.4 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.2.4 => 4.2.4
```
</details>

**Comment by m4theushw** [comment]
The same bug is happening in [this](https://material-ui.com/components/data-grid/pagination/#controlled-pagination) demo. If the `page` prop is not set (uncontrolled mode), it works.

I suppose the problem is in the following function. In controlled mode, the prop value is always used instead of the state.

https://github.com/mui-org/material-ui-x/blob/9953f25ca0f5d0c60777e2717dd8d11d4ea0249b/packages/grid/_modules_/grid/hooks/features/pagination/useGridPagination.ts#L16-L25

**Comment by oliviertassinari** [comment]
The reproduction provided by @mattcarlotta looks expected at `page={0}` is forced. However, the demo we have in the documentation looks broken.

**Comment by mattcarlotta** [comment]
@oliviertassinari The `page={0}` shouldn't matter whether its hard corded or coming from state because clicking the "Next page" pagination button, the `page` should still be incremented to 1 in the `handlePageChange` callback. For example, here's a revert to [alpha28](https://github.com/mattcarlotta/datagrid-jsdom-bug/tree/alpha28) where the page is properly incremented/decremented.

**Comment by oliviertassinari** [comment]
This line https://github.com/mattcarlotta/datagrid-jsdom-bug/blob/bb98ce74fea6772bfcbba81fa4d57a1923c32e59/src/components/Layout/Table/index.tsx#L175 is telling the data grid to ALWAYS stay on the first page.

**Comment by mattcarlotta** [comment]
@oliviertassinari Yes, but even if the were coming from a controllable state variable, for example `page={state.page}`, it still couldn’t be updated because the page change callback isn’t incrementing nor decrementing the `page` parameter on this [line](https://github.com/mattcarlotta/datagrid-jsdom-bug/blob/alpha28/src/components/Layout/Table/index.tsx#L94)

**Comment by dtassone** [comment]
yes the issue is in the callback...
