### ISSUE TITLE
[DataGrid] Changing `Rows per page` is not working 

### ISSUE THREAD

**Issue by ZeeshanTamboli** [mui-org/material-ui-x#1713]
- [X] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
Changing rows per page is not working.

## Expected Behavior 🤔
Changing rows per page should work.

## Steps to Reproduce 🕹

Can be found in this [demo](https://material-ui.com/components/data-grid/pagination/#page-size)

Steps:

1. Go to the linked `Page Size` demo.
2. Click on `rows per page` dropdown.
3. Change per page size. It does not work.

**Comment by oliviertassinari** [comment]
I believe that there are indeed multiple problems:

- [ ] 1. There is flash when trying to change the page size:

![flash](https://user-images.githubusercontent.com/3165635/119140926-fe2f7e80-ba44-11eb-84ea-c2925f58a07a.gif)

- [ ] 2. The demo in https://material-ui.com/components/data-grid/pagination/#page-size should either use `defaultPageSize` or control the page size with the `pageSize`/`onPageSizeChange` duo, as raised in #1725.

**Comment by 21Ovi** [comment]
you need to pass this prop:
`handleChangeRowsPerPage={handleChangeRowsPerPage}`

in DataGrid and and function like this:
```

  const handleChangeRowsPerPage = (event) => {
    setRowsPerPage(parseInt(event.target.value, 10));
    setPage(0);
  };
```
