### ISSUE TITLE
[DataGrid] Page size control still renders even with pageSize prop

### ISSUE THREAD

**Issue by Haaxor1689** [mui-org/material-ui-x#1725]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When I set the `pageSize` prop to one of values from `rowsPerPageOptions`, the page size control still renders even without `onPageSizeChange`.

## Expected Behavior 🤔

If `pageSize` prop is provided with no `onPageSizeChange` callback, I would expect that the page change control won't be rendered even if the page size matches one of onPageSizeChange.
Also since providing `pageSize` should change the behavior to controlled mode, rendering the control breaks this behavior since you can change the internal page size with it while the provided pageSize prop stays the same.

## Steps to Reproduce 🕹

Steps:

1. https://codesandbox.io/s/silly-leaf-s15rz?file=/src/index.tsx
2. check out 4 provided demo instance with different `pageSize` and `rowsPerPageOptions`

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 2.79 GB / 15.92 GB
  Binaries:
    Node: 15.2.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
  Managers:
    Maven: 3.6.3 - C:\Projects\_Tools\apache-maven-3.6.3\bin\mvn.CMD
    pip3: 20.2.3 - C:\Python39\Scripts\pip3.EXE
  Utilities:
    CMake: 3.15.4 - /c/Program Files/CMake/bin/cmake
    Git: 2.31.0. - /cmd/git
  Virtualization:
    Docker: 20.10.5 - C:\Program Files\Docker\Docker\resources\bin\docker.EXE
  IDEs:
    VSCode: 1.56.2 - C:\Users\betko\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD   
    Visual Studio: 16.3.29324.140 (Visual Studio Community 2019)
  Languages:
    Java: javac 11 - /c/Projects/_Tools/jdk-11/bin/javac
    Perl: 5.32.1 - C:\Program Files\Git\usr\bin\perl.EXE
    PHP: 7.4.10 - C:\Users\betko\AppData\Roaming\php-7.4.10-Win32-vc15-x64\php.EXE
    Python: 3.9.0 - /c/Python39/python
  Browsers:
    Chrome: 90.0.4430.212
    Edge: Spartan (44.19041.964.0), Chromium (90.0.818.66)
    Internet Explorer: 11.0.19041.1
</details>

**Comment by oliviertassinari** [comment]
> When I set the pageSize prop to one of values from rowsPerPageOptions, the page size control still renders even without onPageSizeChange.

@Haaxor1689 This is already the expected behavior. The visibility of the control is unrelated to the state.

**Comment by santiagocerrutti** [comment]
You can try using the useState hook and the onPageSizeChange event:
`  const [pageSize, setPageSize] = useState(25);`
`...`
`        <DataGrid`
`          onPageSizeChange={(newPageSize) => setPageSize(newPageSize)}`
`          pageSize={pageSize}`
`          rowsPerPageOptions={[10, 25, 50, 100]}`
`        />`
