### ISSUE TITLE
[DataGrid] The drag event on head should be ignored when `disableColumnReorder`

### ISSUE THREAD

**Issue by sajidfrommerqata** [mui-org/material-ui-x#1762]
I set disableColumnReorder to true but I can reorder the columns of the table.

Video: https://drive.google.com/file/d/15TAR8d_aED1OVNETtdPkSml4IKRfSt4w/view
SandBox: https://codesandbox.io/s/material-demo-forked-7hvfc

**Comment by oliviertassinari** [comment]
I have raised the same bug in #1579.

**Comment by ZeeshanTamboli** [comment]
@oliviertassinari The user is mentioning it is in DataGrid for which we do not support column reordering. Did you check the provided codesandbox link and video? I cannot reproduce it there.

**Comment by oliviertassinari** [comment]
@ZeeshanTamboli I could reproduce the issue with the codesandbox of this issue.
