### ISSUE TITLE
[DataGrid] Build failing with message "expected atom at position 4"

### ISSUE THREAD

**Issue by sam-n-bell** [mui-org/material-ui-x#1766]
- [X] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
I recently started using Material UI and the data-grid packages in a project. Everything functions fine when running the local dev server, but when I try to build, I get an error message 

> Failed to compile.
> 
> ./node_modules/@material-ui/data-grid/dist/index-esm.js
> SyntaxError: Expected atom at position 4
>     ^(\p{L}|\p{M}\
>             ^

## Context 🔦

I've tried upgrading and downgrading to different versions with no success of resolving it. I've removed and reinstalled node_modules as well. 

## Your Environment 🌎

>   System:
    OS: macOS 10.15.7
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.11 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Edge: Not Found
    Firefox: Not Found
    Safari: 14.1
  npmPackages:
    @material-ui/core: ^4.11.4 => 4.11.4 
    @material-ui/data-grid: ^4.0.0-alpha.27 => 4.0.0-alpha.27 
    @material-ui/icons: ^4.11.2 => 4.11.2 
    @material-ui/styles:  4.11.4 
    @material-ui/system:  4.11.3 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @types/react: 16.8.24 => 16.8.24 
    react: ^16.9.0 => 16.10.2 
    react-dom: ^16.9.0 => 16.10.2 
    styled-components: ^5.2.1 => 5.2.1 
    typescript: ^4.2.4 => 4.2.4 

tsconfig.json

> {
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve",
    "noImplicitAny": true
  },
  "include": ["src"]
}

package.json

> {
  "name": "ui",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@material-ui/core": "^4.11.4",
    "@material-ui/data-grid": "^4.0.0-alpha.27",
    "@material-ui/icons": "^4.11.2",
    "@nebula.gl/edit-modes": "^0.16.0",
    "@nebula.gl/layers": "^0.16.0",
    "@nebula.gl/overlays": "^0.16.0",
    "@turf/area": "6.0.1",
    "@turf/center": "^6.0.1",
    "@turf/difference": "6.0.1",
    "@turf/turf": "^5.1.6",
    "axios": "^0.21.1",
    "bootstrap": "^4.3.1",
    "classnames": "^2.2.6",
    "colorsys": "^1.0.22",
    "deck.gl": "^7.2.4",
    "export-to-csv": "^0.2.1",
    "http-proxy-middleware": "^0.20.0",
    "jquery": "^3.6.0",
    "keyboardjs": "^2.5.1",
    "lodash": "^4.17.21",
    "moment": "^2.29.1",
    "react": "^16.9.0",
    "react-beautiful-dnd": "^11.0.5",
    "react-bootstrap": "1.0.0-beta.12",
    "react-data-table-component": "7.0.0-alpha-5",
    "react-datetime-picker": "^2.7.1",
    "react-dom": "^16.9.0",
    "react-icons": "^4.1.0",
    "react-redux": "^7.1.1",
    "react-router-bootstrap": "^0.25.0",
    "react-router-dom": "^5.0.1",
    "react-scripts": "3.0.1",
    "react-select": "^3.0.4",
    "react-use": "^13.10.0",
    "redux": "^4.0.4",
    "redux-observable": "^1.1.0",
    "rxjs": "^6.5.3",
    "shortid": "^2.2.15",
    "styled-components": "^5.2.1",
    "typesafe-actions": "^4.4.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "eject": "react-scripts eject",
    "ci": "CI=true react-scripts test --passWithNoTests --ci --reporters=default --reporters=jest-junit --collectCoverage",
    "test": "react-scripts test --watchAll --runInBand"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "resolutions": {
    "@turf/difference": "6.0.1"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@testing-library/react": "^11.2.6",
    "@types/axios": "^0.14.0",
    "@types/classnames": "^2.2.9",
    "@types/enzyme": "^3.10.3",
    "@types/faker": "^4.1.5",
    "@types/jest": "^24.0.16",
    "@types/keyboardjs": "^2.4.1",
    "@types/lodash": "^4.14.168",
    "@types/node": "12.6.8",
    "@types/react": "16.8.24",
    "@types/react-beautiful-dnd": "^11.0.3",
    "@types/react-dom": "16.8.5",
    "@types/react-redux": "^7.1.2",
    "@types/react-router-bootstrap": "^0.24.5",
    "@types/react-router-dom": "^4.3.5",
    "@types/react-select": "^3.0.4",
    "@types/shortid": "0.0.29",
    "enzyme": "^3.10.0",
    "enzyme-adapter-react-16": "^1.14.0",
    "enzyme-to-json": "^3.4.0",
    "faker": "^4.1.0",
    "jest-junit": "^10.0.0",
    "node-sass": "^4.14.1",
    "prettier": "^1.19.1",
    "ts-jest": "^24.1.0",
    "typescript": "^4.2.4"
  },
  "jest-junit": {
    "output": "~/ui/coverage/junit/results.xml"
  }
}

**Comment by dtassone** [comment]
Have you tried targeting ES6? 

if you target es5, I believe you should use the cjs version of the grid.

**Comment by sam-n-bell** [comment]
@dtassone Thanks for your reply. Forgive me if this isn't the brightest question (I'm still learning a lot of this stuff), but to target ES6, is that just altering the target in tsconfig? I updated the target there, tried a build again (and reinstalled my modules just in case), but the error is still present.

**Comment by dtassone** [comment]
Try to play with the tsconfig. You can always try to get it right in codesandbox first, or in a smaller project. Please open a question on StackOverflow as it is not an issue with the datagrid.

try that 
```json
compilerOptions": {
    "target": "es6",
    "module": "esnext",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    // Already tested with eslint
    "noUnusedLocals": false,
    "jsx": "react", <--- might fix it
...
}
```

**Comment by oliviertassinari** [comment]
Duplicate of #1630

**Comment by oliviertassinari** [comment]
@dtassone I looks very much like a bug in TypeScript' JS compiler: https://github.com/microsoft/TypeScript/issues/32214. More details in #1630. I'm saying this because the line it fails on is where we have a RegExp unicode property escapes. We increase the minimum target from ES5 to ES9 in #1409.

**Comment by engelmav** [comment]
I have this issue as well @oliviertassinari @dtassone - I can't decipher if there is a resolution in this issue or #1630  (if it is mentioned). Downgrading to alpha.24 I at least manage to work around it (thanks @john-shafer).

Interestingly, it compiles fine in storybook. Probably a subtle babel config or plugin version issue.
