### ISSUE TITLE
[XGrid] Disable checkbox column draggable

### ISSUE THREAD

**Issue by y2b1** [mui-org/material-ui-x#1768]
The checkbox column is draggable and it shouldn't be. Is there any config on the table that may prevent this? I see it happening in the demo as well so I'm guessing its an issue with XGrid and not my setup. You can see the column being dragged here, using the same code for the table configs.

https://codesandbox.io/s/gttt1?file=/demo.tsx

Thanks!

**Comment by oliviertassinari** [comment]
It looks like we can solve this the same way as #1672.

**Comment by DanailH** [comment]
> It looks like we can solve this the same way as #1672.

We are discussing that before. We could add the option to disable dragging for specific columns by adding a flag in the column definition.

**Comment by oliviertassinari** [comment]
@DanailH #1161
