### ISSUE TITLE
[DataGrid] Deselect row in non checkboxSelection grid

### ISSUE THREAD

**Issue by Haaxor1689** [mui-org/material-ui-x#1770]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

DataGrid with `checkboxSelection={false}` by default allows you to select one row by clicking on it. Once you selected a row, clicking on it again does nothing except for calling `onRowSelected` if provided (with same arguments as before).

I would expect that if I click on selected row it will be deselected (just like it behaves with checkboxSelection). With multiple selection of Xgrid you can deselect single row by holding `Ctrl` which does not work in DataGrid. Now after you select a row there is no way of going back to having no rows selected.

## Examples 🌈

Current behavior: https://codesandbox.io/s/gifted-wind-xg84s?file=/src/Demo.tsx
Deselecting with XGrid: https://material-ui.com/components/data-grid/selection/#multiple-row-selection

## Motivation 🔦

Without providing my own controlled `selectionModel` I see no way of implementing this really basic feature. It would be nice to provide a flag that allows deselection when clicking selected row that would trigger a `onRowSelected` with params with `isSelected: false`.

**Comment by oliviertassinari** [comment]
@dtassone Why did you add the "bug" label? Please provide some rationale on what you have identified when you apply a label on a new issue.

---

@Haaxor1689 The current behavior is identical to https://next.material-ui.com/components/tree-view/. However, it does seems like we could have <kbd>Ctrl</kbd> and <kbd>Shift</kbd> to deselect when using the single selection mode. It would make is consistent with the multi-selection. It also seems to be what [AG Grid did](https://ag-grid.com/react-grid/row-selection/).

> I would expect that if I click on selected row it will be deselected

Why? What's your use case? A controlled `selectionModel` is meant to allow developers to cover the long tail of use cases without us adding new props for each stubble variations.

> Once you selected a row, clicking on it again does nothing except for calling onRowSelected

@Haaxor1689 This looks like a bug, it doesn't make sense for `onRowSelected` to fire twice on the same value.
A reproduction for the test case: https://codesandbox.io/s/material-demo-forked-pgw0t
A fix:

```diff
diff --git a/packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts b/packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts
index cb8456da..550a33de 100644
--- a/packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts
+++ b/packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts
@@ -56,39 +56,44 @@ export const useGridSelection = (apiRef: GridApiRef): void => {
         return;
       }

-      if (!apiRef.current.isInitialised) {
-        setGridState((state) => {
-          const selectionState: GridSelectionState = {};
-          selectionState[id] = id;
-          return { ...state, selection: selectionState };
-        });
-        return;
-      }
-
       logger.debug(`Selecting row ${id}`);

+      const previousSelection = apiRef!.current!.getState<GridSelectionState>('selection');
+
       const allowMultiSelect =
         allowMultipleOverride || allowMultipleSelectionKeyPressed.current || checkboxSelection;

       if (allowMultiSelect) {
+        const isRowSelected =
+          !allowMultiSelect || isSelected == null
+            ? previousSelection[id] === undefined
+            : isSelected;
+
+        if ((isRowSelected && previousSelection[id]) || (!isRowSelected && previousSelection[id])) {
+          return;
+        }
+
         setGridState((state) => {
           // eslint-disable-next-line prefer-object-spread
-          const selectionState: GridSelectionState = Object.assign({}, state.selection);
-          const isRowSelected =
-            !allowMultiSelect || isSelected == null ? selectionState[id] === undefined : isSelected;
+          const selection: GridSelectionState = { ...state.selection };

           if (isRowSelected) {
-            selectionState[id] = id;
+            selection[id] = id;
           } else {
-            delete selectionState[id];
+            delete selection[id];
           }
-          return { ...state, selection: selectionState };
+
+          return { ...state, selection };
         });
       } else {
+        if (previousSelection[id]) {
+          return;
+        }
         setGridState((state) => {
-          const selectionState: GridSelectionState = {};
-          selectionState[id] = id;
-          return { ...state, selection: selectionState };
+          const selection: GridSelectionState = {};
+          selection[id] = id;
+
+          return { ...state, selection };
         });
       }
       forceUpdate();
@@ -100,10 +105,10 @@ export const useGridSelection = (apiRef: GridApiRef): void => {
         data: row,
         isSelected: selectionState[id] !== undefined,
       };
+      apiRef.current.publishEvent(GRID_ROW_SELECTED, rowSelectedParam);
       const selectionChangeParam: GridSelectionModelChangeParams = {
         selectionModel: Object.values(selectionState),
       };
-      apiRef.current.publishEvent(GRID_ROW_SELECTED, rowSelectedParam);
       apiRef.current.publishEvent(GRID_SELECTION_CHANGED, selectionChangeParam);
     },
     [isRowSelectable, apiRef, logger, checkboxSelection, forceUpdate, setGridState],
```

**Comment by dtassone** [comment]
Well as describe in the issue, in Xgrid, you can deselect single row by holding Ctrl which does not work in DataGrid. 
It should work, I believe it's a regression from the change with the refactoring of the multi selection, with `event. ctrlKey`

**Comment by oliviertassinari** [comment]
OK great, this is really helpful. If we could make it a habit it would be perfect.

**Comment by Haaxor1689** [comment]
@oliviertassinari in my use case, on selecting of a row I add `s=${row.id}` to the query string of current page and show "details" of that row on the side of the table. So clicking the row again is supposed to close the side details panel. This way it's persistent and shareable in link. But now that I think of it this use case would be better to implement with controlled state which would be derived from that query string.

Enabling ctrl click to deselect would be definitely most consistent solution.
