### ISSUE TITLE
[Datagrid] The Grid flickers as it continuously resizes itself 

### ISSUE THREAD

**Issue by Praetorss** [mui-org/material-ui-x#1775]
Issue can be triggered after getting the resolution just right for the condition to take place.
In result the grid can be seen extending and shrinking horizontally non stop. After inspection of the source we can see JavaScript realigning width and min-width on a number of DOM Elements.

Experienced on both 4.0.0-alpha.28 and 4.0.0-alpha.29 versions and possibly on others.
Sometimes difficult to replicate, other times happens all the time. To try to replicate make window smaller and resize until you get scrollbar to show. It will likely disappear shortly after resizing. Now change the zoom level in and out - at some point the issue will occur. If it does not resize the window to a different size and try the steps again.

Any help, suggestions are really appreciated.

Attached GIF demonstrating the issue.

![CPT2105271230-2181x702](https://user-images.githubusercontent.com/18535200/119818701-6c61be80-bee7-11eb-8c87-902533a0c521.gif)

**Comment by Praetorss** [comment]
@dtassone forgot to mention that this issue causes extreme CPU consumption and can lead to the whole browser tab freezing.

**Comment by Praetorss** [comment]
@dtassone are you aware of any steps that could be taken to mitigate this? Also, do you know if there is a version of data grid that might not suffer from this issue?

**Comment by oliviertassinari** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://material-ui.com/r/issue-template) _may_ be a good starting point. Thank you!

**Comment by Praetorss** [comment]
I have managed to resolve the issue and narrow down the cause.

Issue is caused by putting the data grid inside material grid when that has spacing attribute set on it. in my case I had spacing set to 2. Looking at how spacing is applied it recalculates the width by doing calc(100% + x number of pixels) which is taking the width over 100% width. That in turn causes the data grid to misbehave.

Looks to me like this is a valid issue for the data grid which will occur when container the grid is in is stretched out. it might not be a very common scenario to take place hence the low priority on this seems right to me.

Sorry, I don't have much time right now to put an example together on sandbox.

**Comment by oliviertassinari** [comment]
Ok, if you can reproduce, that would be great, I have tried something in https://codesandbox.io/s/material-demo-forked-lx9j6?file=/demo.tsx but couldn't. I will close next week if we don't manage to make progress on the reproduction part.

**Comment by Praetorss** [comment]
Aligned with my setup:
https://codesandbox.io/s/material-demo-forked-6cme3?file=/demo.tsx
Hard to reproduce. But managed to get flickering to occur for second ish and then it stopped.

If you cannot reproduce might be a very very niche thing that was happening to me.

**Comment by bzuu-ic** [comment]
I am experiencing the exact same issue as described above. Indeed it only happens at very specific conditions.

I can reproduce it with the following sample code:
```
import * as React from "react";
import { DataGrid } from "@mui/x-data-grid";

export default function BasicColumnsGrid() {
  return (
    <div style={{ height: "116px", width: "100%" }}>
      <DataGrid
        hideFooter
        // autoHeight
        columns={[
          { field: "username1", flex: 1 },
          { field: "username2", flex: 1 },
          { field: "username3", flex: 1 },
          { field: "username4", flex: 1 },
          { field: "username5", flex: 1 },
          { field: "username6", flex: 1 },
          { field: "username7", flex: 1 },
          { field: "age", width: 50 }
        ]}
        rows={[
          {
            id: 1,
            username1: "@MaterialUI",
            username2: "@MaterialUI",
            username3: "@MaterialUI",
            username4: "@MaterialUI",
            username5: "@MaterialUI",
            username6: "@MaterialUI",
            username7: "@MaterialUI",
            age: 20
          }
        ]}
      />
    </div>
  );
}
```
Available as a sandbox here:
https://codesandbox.io/s/basiccolumnsgrid-material-demo-forked-y26g5
The issue occurs when you have a screen size around 1732 pixels (and many others).

**Comment by flaviendelangle** [comment]
Noted, my current implementation does not fix it.

> One hypothesis is, since flex columns are used, it's not supposed to have scrollbars. However, when this method gets called, hasScrollX evaluates to true, which changes the size of the viewport, and triggers the columns to resize to the new size. Then, once the columns are resized, columnsTotalWidth is now false, triggering a new resize, which starts the cycle again.

I have the same feeling about the cause, I will have a look

**Comment by flaviendelangle** [comment]
@bzuu-ic could you confirm me that on the codesandbox with list (in my previous message) you can't reproduce your bug ?

**Comment by bzuu-ic** [comment]
@flaviendelangle it seems the fix works. Great work 👍

**Comment by igortas** [comment]
@flaviendelangle Still exists with v7. I have the flickering resize issue when switching between tabs. I have flex: 1 for all columns. Because per tab the number of columns differs, when the number of columns i smaller then the previous tab, the flickering starts.
