### ISSUE TITLE
[DataGrid] Density selector not working

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#1776]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The density selector is not rendering correctly.

## Expected Behavior 🤔

The density selector is rendering correctly.

## Steps to Reproduce 🕹

Steps:

1. Open https://codesandbox.io/s/9fzgz
2. 

https://user-images.githubusercontent.com/3165635/119833881-c5d5e780-beff-11eb-9772-905f71346aee.mp4

## Context 🔦

Noticed on https://material-ui.com/components/data-grid/demo/

## Your Environment 🌎

v4.0.0-alpha.29

**Comment by lpke** [comment]
This is a frustrating issue I am also facing. It seems that when the density changes, the row's `min-height`/`max-height` properties are updating instantly, but the cells retain the previous values for these properties. Interacting with the grid in any way updates the cells' CSS and everything "catches up".

As a workaround, it works to force `.MuiDataGrid-cell` min and max height to `100%`. Cell contents appear to be cantered by `line-height`, which is tied to the height values that aren't updating, so the text will not be centred. To get around this, set the display of `.MuiDataGrid-cell` to `flex`. The only drawback with this is that the `text-overflow: ellipsis` doesn't work when applied to a flex container.

I have yet to find a better (performant) way to handle this bug, so I've settled for the forced height and flex centring solution. Would love to see a fix for this bug soon, given how dramatically it affects the presentation of the grid as a whole.

**Comment by oliviertassinari** [comment]
I could pinpoint the origin of the regression to #1513. It sounds like we miss a dependency, somewhere.
