### ISSUE TITLE
[DataGrid] The column menu filtering UX is K.O.

### ISSUE THREAD

**Issue by m4theushw** [mui-org/material-ui-x#1777]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When filtering multiple columns, if I click in the Filter button of a column that has an active filter an empty filter is added. It doesn't occur in the column that is the last in the filter list.

![duplicate-filter](https://user-images.githubusercontent.com/42154031/119914891-ad81bf00-bf37-11eb-9f44-7b634d5ca376.gif)

## Expected Behavior 🤔

It shouldn't add an filter if there's already one for the same field. 

## Steps to Reproduce 🕹

Steps:

1. Navigate to https://material-ui.com/components/data-grid/filtering/#multi-column-filtering
2. Open the menu of the Commodity column.
3. Click in the Filter button

I suppose the fix is simple. We have to change the logic to check if there's a filter added for the same field in the whole list and not just the last item:

https://github.com/mui-org/material-ui-x/blob/0cd94899863a2827ee31718105733fbca63b841a/packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts#L216-L224

**Comment by DanailH** [comment]
I found the same while working on the Infinite loader. Actually, there is another problem - the `GRID_FILTER_MODEL_CHANGE` is fired when the modal to create a filter opens and then fires again when the actual filter is created.

Also when you load the grid the `items` array in the  `GridFilterModel` is employed but if you add a filter and then remove it there is still an `item` with no value (the array is not empty even tho there are no filters). The same happens if you just open and close the filter modal.

**Comment by oliviertassinari** [comment]
1. I would propose we remove the ambiguity by changing the content of the column menu. We could do:

```diff
-<menu-item>Filter</menu-item>
+<menu-item>Add filter</menu-item>
+<menu-item>Show filters</menu-item>
```

The current logic is a hybrid between the two that doesn't really work. Developers could decide to remove `<menu-item>Show filters</menu-item>` if they leverage the toolbar.

---

2. I would propose we go one step further, the argument is lying. To do what it describes, it should add a new filter even if there is already one on the column or if the existing one is empty, it currently doesn't.

```diff
diff --git a/packages/grid/_modules_/grid/models/api/gridFilterApi.ts b/packages/grid/_modules_/grid/models/api/gridFilterApi.ts
index 7ef77ab5..2b9bbfbd 100644
--- a/packages/grid/_modules_/grid/models/api/gridFilterApi.ts
+++ b/packages/grid/_modules_/grid/models/api/gridFilterApi.ts
@@ -7,10 +7,10 @@ import { GridFilterItem, GridLinkOperator } from '../gridFilterItem';
  */
 export interface GridFilterApi {
   /**
-   * Shows the filter panel. If `targetColumnField` is given, a filter for this field is also added.
+   * Shows the filter panel.
    * @param {string} targetColumnField The column field to add a filter.
    */
-  showFilterPanel: (targetColumnField?: string) => void;
+  showFilterPanel: () => void;
   /**
    * Hides the filter panel.
    */
```

---

3. I would propose we add a new method on the apiRef:

```diff
diff --git a/packages/grid/_modules_/grid/models/api/gridFilterApi.ts b/packages/grid/_modules_/grid/models/api/gridFilterApi.ts
index 7ef77ab5..94e92cf8 100644
--- a/packages/grid/_modules_/grid/models/api/gridFilterApi.ts
+++ b/packages/grid/_modules_/grid/models/api/gridFilterApi.ts
@@ -11,6 +11,11 @@ export interface GridFilterApi {
    * @param {string} targetColumnField The column field to add a filter.
    */
   showFilterPanel: (targetColumnField?: string) => void;
+  /**
+   * Add a new filter for the column field provided.
+   * @param {string} columnField The column field.
+   */
+  addFilterColumnField: (columnField?: string) => void;
   /**
    * Hides the filter panel.
    */
```

**Comment by dtassone** [comment]
> When filtering multiple columns, if I click in the Filter button of a column that has an active filter an empty filter is added. It doesn't occur in the column that is the last in the filter list.

The logic should be.

Given I add a filter on the commodity column with a value 'rice'
When I click away of the panel
Then the filter panel is hidden

When I click the filter button in the column menu of the commodity column
Then the panel is displayed again and no new filter should be added. 

When I click the filter button in the column menu of the desk column
Then the panel is displayed again and a new filter on the desk column should be added. 

When I click the filter button in the column menu of the commodity column
Then the panel is displayed again and a new filter on the commodity column should be added. 

So you should add filter if the previous filter is different to the one that you are trying to open.

**Comment by oliviertassinari** [comment]
@dtassone It seems that you are describing the current behavior. So If I understand you correctly, you are saying that the current behavior is correct? 

I personally think that we can improve the UX. https://airtable.com/ behaves significantly differently to this proposal. The proposal in https://github.com/mui-org/material-ui-x/issues/1777#issuecomment-850300615 was aiming to be a transcription of it.

How about we freeze this discussion until Danilo provides guidance on which direction we should take for the UX?

**Comment by oliviertassinari** [comment]
I'm changing the title of the issue because the issue is broader. Multiple aspects of the UX are not great. For instance, on the`DataGrid`, if you open the filter view on a different column, wouldn't you expect the filtering preconfigured?

https://user-images.githubusercontent.com/3165635/127520070-32435e00-3c96-410c-ac44-4765525131b5.mp4

**Comment by flaviendelangle** [comment]
Does this issue relates with #670 
Do we want to "just" improve the current UI or change the approach ?

**Comment by oliviertassinari** [comment]
We could also involve @danilo-leal, as it's about UX 😁
