### ISSUE TITLE
[DataGrid] Allow to disable virtualization

### ISSUE THREAD

**Issue by IgnacioFDM** [mui-org/material-ui-x#1781]
It should be possible to disable row virtualization.

Reasons why you would want to disable row virtualization:

1. It introduces *microstutter* when scrolling, especially on mobile
2. It breaks <kbd>Ctrl</kbd>+<kbd>F</kbd> for users
3. It doesn't provide much benefit if the page size is small

**Comment by oliviertassinari** [comment]
Regarding 1. it's probably an issue we want to fix on its own.
Regarding 3. so it's fine.

In https://github.com/mui-org/material-ui-x/issues/1519#issuecomment-830863415, we talk about a 4. value proposition for a prop to disable virtualization: it allows to test the data grid in [jsdom](https://github.com/jsdom/jsdom).

**Comment by embeddedt** [comment]
@oliviertassinari Given that this issue is still open, I assume it is currently not possible to disable virtualization in its current implementation? Any idea when this might be available? I'd be happy to try and help with the implementation.

**Comment by oliviertassinari** [comment]
@embeddedt It's not currently available but help is definitely welcome. Do you have a specific use case in mind?

As for when or how it will happen. I have no idea, help is welcome.

**Comment by embeddedt** [comment]
My use case is https://github.com/mui-org/material-ui-x/issues/1103#issuecomment-849090389. I have no way of reliably scrolling to rows as virtualization means that not every row is in the DOM at the time that I use `querySelector`.

At the moment I'm reading through the DataGrid code to try and understand where virtualization is enabled; it seems like a complex system as it's combined with pagination.
