### ISSUE TITLE
[DataGrid] Rows are not rendered

### ISSUE THREAD

**Issue by bobsys-mfleischer** [mui-org/material-ui-x#1784]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
Sometimes the rows are not rendered.

## Steps to Reproduce 🕹
https://codesandbox.io/s/determined-haibt-ikjl1?file=/src/demo.js
The problem does not always occur. I have tried to reproduce it via codesandbox.

Open the example and refresh the browser.

![image](https://user-images.githubusercontent.com/78475623/120043016-7e3c8200-c00b-11eb-9009-acff1e3f0953.png)

## Context 🔦
In my application, I use Redux in conjunction with a web service. The first two renderings pass an empty array to the DataGrid, the third rendering contains the data.
When this happens very fast it happens again and again that I get empty rows.

I have tried to break it down as far as possible in the example.

## Order id 💳

#23119

**Comment by IgnacioFDM** [comment]
Can confirm, downgrading to alpha 28 fixes the issue.

**Comment by oliviertassinari** [comment]
I can pinpoint the origin of the regression to #1686. In

https://github.com/mui-org/material-ui-x/blob/7baf6b8e6d4a337900a0b95ff9c5a5f3ecb180fb/packages/grid/_modules_/grid/hooks/root/useGridContainerProps.ts#L233

and the reproduction provided, it fires with 2, then 0. 0 shouldn't be here.

**Comment by cmhernandezdel** [comment]
Can confirm, currently using material ui 4.11.4 and data-grid 4.0.0-alpha.29 this happens as well. 

In my case the steps to reproduce are just create a datagrid and fill it, I won't see the render. However, something bizarre happens, if I resize the window the rows will be shown. Also, I don't seem to get the issue on mobile, just on desktop.

**Comment by StewartThomson** [comment]
I also see the same behaviour as @cmhernandezdel 

However, thankfully, usually some other part of the page (sidebar, or something else) triggers that resize and causes the rows to render properly

**Comment by Scott-HangarA** [comment]
Same problem here. Downgrading to alpha 26 solved it for me.

**Comment by oliviertassinari** [comment]
@Scott-HangarA Could you give this version of the package a try, see if it fixes your issue? 

`https://pkg.csb.dev/mui-org/material-ui-x/commit/c400961e/@material-ui/data-grid`

**Comment by aardvarkk** [comment]
I believe I'm still running into this issue on the 4.0.0 version of DataGrid. I can only reproduce it occasionally, but it's very frustrating. In my case, I'm using React Router and **cannot** reproduce it if I remove the "Private Route" protection (Auth). Once I wrap the DataGrid inside their suggested Auth/Private Route code, I see this behaviour sometimes. The wrapping code look like this:

```
    <Route
      {...rest}
      render={({ location }) => {
        if (auth.currentUser) {
          return <Layout>{children}</Layout>;
        } else {
          return <Redirect to={{ pathname: "/", state: { from: location } }} />;
        }
      }}
    />
```

If I comment out the <Redirect/> business, I don't seem to run into this. I will try to write some kind of reproducible thing in Codesandbox, but I make no promises!
