### ISSUE TITLE
[DataGrid] Remove custom dark mode scrollbar in v5

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#1805]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

The current custom dark mode scrollbar implementation suffers from the same issue as https://github.com/mui-org/material-ui/issues/23520. It forces a width on the scrollbar on macOS, it also doesn't respect the native dark mode style. 
A better solution was found in https://github.com/mui-org/material-ui/issues/25016#issuecomment-849659928.

## Motivation 🔦

We should remove:

https://github.com/mui-org/material-ui-x/blob/40ebf9b4079dd7433200b7de00b6959fd25a50ec/packages/grid/_modules_/grid/components/containers/GridRootStyles.ts#L353-L378

once https://github.com/mui-org/material-ui/issues/25016 is fixed and we have updated the repo to dependant on v5. 

See #1613 for a related issue.

**Comment by m4theushw** [comment]
mui-org/material-ui#25016 was fixed. This issue is now unblocked. Anybody feel free to submit a PR.
