### ISSUE TITLE
[DataGrid] Preferences Panel should not exceed Grid height

### ISSUE THREAD

**Issue by sebastianfrey** [mui-org/material-ui-x#1808]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When a user opens a preference panel (columns panel or filter panel) and the grids height is lower than the preference panels height and equals the browser windows total height, the UI jumping shown in the video below occurs. This effect also occurs, when the grid is positioned at the bottom of the browser window, with a total grid height lower than 550px.

![mui-xgrid-preferences-panel](https://user-images.githubusercontent.com/15965420/120441799-3b6d0800-c385-11eb-8d22-85f3f4368a51.gif)

## Expected Behavior 🤔

The preferences panel height should not exceed the grids current height in order to avoid the above shown UI jumping.

## Steps to Reproduce 🕹

Steps:

1. Go to https://codesandbox.io/s/mui-preferences-panel-forked-vzsqe?file=/src/Demo.tsx:0-972
2. Resize the browser window, so that total height is lower than 550px
3. Open the columns preference panel.
4. Open the filters preference panel and add filters until the panels height exceeds the grids height.

## Order id 💳

22075

**Comment by oliviertassinari** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://material-ui.com/r/issue-template) _may_ be a good starting point. Thank you!

**Comment by sebastianfrey** [comment]
I have updated the issue with a minimal reproduction test case.

**Comment by oliviertassinari** [comment]
@sebastianfrey Thanks for the update. Yes, it sounds like something we can easily fix. In the core, we set a max height to the popup to something close to 100vh, we can leverage the same solution.

**Comment by sebastianfrey** [comment]
@oliviertassinari I just noticed that when the grid is contained by an element which is pinned to the bottom of the browser window and this wrapping element has a height lower than `550px`, the proposed solution seems not applicable. Please have a look at this sandbox example: https://codesandbox.io/s/mui-preferences-panel-forked-um9u4

So I would propose a different solution, where the `max-height` of the preferences panel is derived from the sum of the height of the `MuiDataGrid-window` element and the height of the `MuiDataGrid-footer` element

Then the following behaviour could be leveraged:

![mui-xgrid-preferences-panel-2](https://user-images.githubusercontent.com/15965420/121013743-85952580-c799-11eb-8cbd-af16a291ebb9.gif)

A problem that comes to my mind with this solution is, when the grid is positioned at the top of the browser viewport instead of the bottom. Then my proposed solution seems not desireable, since there might be more space to display the preferences panel.

In order to meet all these criteria, a global data grid property for tweaking the preferences panel might be considerable. For example something like this:

`restrictPreferencesPanelMaxHeightTo = "viewport" | "grid"` .

 - `"viewport"` => `max-height` is set to `100vh`
 - `"grid"` => `max-height` is computed from the sum of the height of the `MuiDataGrid-window` element and the height of the `MuiDataGrid-footer` element

How do you think about this?

**Comment by oliviertassinari** [comment]
The following seems to fix the issue for some screen width:

```diff
diff --git a/packages/grid/_modules_/grid/components/panel/GridPanel.tsx b/packages/grid/_modules_/grid/components/panel/GridPanel.tsx
index aabcf364..29e0f93b 100644
--- a/packages/grid/_modules_/grid/components/panel/GridPanel.tsx
+++ b/packages/grid/_modules_/grid/components/panel/GridPanel.tsx
@@ -17,6 +17,8 @@ const useStyles = makeStyles(
   (theme: Theme) => ({
     root: {
       zIndex: theme.zIndex.modal,
+      maxHeight: 'calc(100% - 32px)',
+      display: 'flex',
     },
     paper: {
       backgroundColor: theme.palette.background.paper,
diff --git a/packages/grid/_modules_/grid/components/panel/GridPanelContent.tsx b/packages/grid/_modules_/grid/components/panel/GridPanelContent.tsx
index 03d78117..98bb5ccb 100644
--- a/packages/grid/_modules_/grid/components/panel/GridPanelContent.tsx
+++ b/packages/grid/_modules_/grid/components/panel/GridPanelContent.tsx
@@ -10,6 +10,8 @@ const useStyles = makeStyles(
       overflow: 'auto',
       flex: '1 1',
       maxHeight: 400,
+      // Add iOS momentum scrolling for iOS 12.0
+      WebkitOverflowScrolling: 'touch',
     },
   }),
   { name: 'MuiDataGridPanelContent' },
```

<img width="348" alt="Capture d’écran 2021-06-08 à 01 11 15" src="https://user-images.githubusercontent.com/3165635/121098583-75f7fa00-c7f6-11eb-8142-7d1545ed82f9.png">

**Comment by dtassone** [comment]
you have to consider a min size as what if the grid has a total height of 80px?

**Comment by oliviertassinari** [comment]
@sebastianfrey For the positioning issue, I would personally search deeper into popper.js. For now, I think that we can solve https://github.com/mui-org/material-ui-x/issues/1808#issuecomment-856320397 and move along.

**Comment by sebastianfrey** [comment]
@oliviertassinari 

Thanks for the popper.js hint. It seems I can solve my max height problem using the
`preventOverflow` modifier.

If Ok, I am willing to provide a PR for your suggested solution.

**Comment by oliviertassinari** [comment]
@sebastianfrey I have made some progress too on this issue. I have updated your codesandbox so it also reproduces on our Next.js environment with a plain copy & paste. It's not getting better with Popper v2 (core v5).

The only viable solution I can find is: https://codesandbox.io/s/mui-preferences-panel-forked-ex4h9?file=/src/Demo.tsx:0-1402.

```jsx
import * as React from "react";
import { makeStyles } from "@material-ui/core/styles";
import {
  XGrid,
  GridPanel,
  GridPanelProps,
  GridToolbar
} from "@material-ui/x-grid";
import { useDemoData } from "@material-ui/x-grid-data-generator";

const useStyles = makeStyles({
  "@global": {
    "html, body, #__next": {
      height: "100%",
      margin: 0
    }
  }
});

const MyPanel = React.forwardRef<HTMLDivElement, GridPanelProps>(
  function MyPanel(props, ref) {
    return (
      <GridPanel
        ref={ref}
        {...props}
        modifiers={{
          flip: {
            enabled: false
          },
          preventOverflow: {
            boundariesElement: "viewport"
          }
        }}
      />
    );
  }
);

/**
 * how you used the components
 */
export default function Demo() {
  useStyles();
  const { loading, data } = useDemoData({
    dataSet: "Commodity",
    rowLength: 1000,
    maxColumns: 20
  });

  return (
    <div
      style={{ height: 400, position: "absolute", bottom: 0, width: "100%" }}
    >
      <div style={{ display: "flex", height: "100%" }}>
        <div style={{ flexGrow: 1 }}>
          <XGrid
            {...data}
            components={{
              Toolbar: GridToolbar,
              Panel: MyPanel
            }}
            loading={loading}
            checkboxSelection
          />
        </div>
      </div>
    </div>
  );
}
```

And a bit of patch-up for the type, and we should be good:

```diff
diff --git a/packages/grid/_modules_/grid/components/panel/GridPanel.tsx b/packages/grid/_modules_/grid/components/panel/GridPanel.tsx
index c7c74f89..e2970c55 100644
--- a/packages/grid/_modules_/grid/components/panel/GridPanel.tsx
+++ b/packages/grid/_modules_/grid/components/panel/GridPanel.tsx
@@ -3,11 +3,11 @@ import { Theme } from '@material-ui/core/styles';
 import { makeStyles } from '@material-ui/styles';
 import ClickAwayListener from '@material-ui/core/ClickAwayListener';
 import Paper from '@material-ui/core/Paper';
-import Popper from '@material-ui/core/Popper';
+import Popper, { PopperProps } from '@material-ui/core/Popper';
 import { useGridApiContext } from '../../hooks/root/useGridApiContext';
 import { isEscapeKey, isMuiV5, createTheme } from '../../utils';

-export interface GridPanelProps extends React.HTMLAttributes<HTMLDivElement> {
+export interface GridPanelProps extends Omit<PopperProps, 'children'> {
   children?: React.ReactNode;
   open: boolean;
 }
```

**Comment by sebastianfrey** [comment]
@oliviertassinari Thanks for your update. I've also think the best approach to self the problem is a custom panel component.

In addition to your changes, I have made the GridPanelProps extending the MUI `StandardProps` interface and passed the grid panel props to `useStyles()`. This allows to extend/override the grid panels classes to apply custom styles to the panel component.

```diff
diff --git a/packages/grid/_modules_/grid/components/panel/GridPanel.tsx b/packages/grid/_modules_/grid/components/panel/GridPanel.tsx
index aabcf364..72e74424 100644
--- a/packages/grid/_modules_/grid/components/panel/GridPanel.tsx
+++ b/packages/grid/_modules_/grid/components/panel/GridPanel.tsx
@@ -1,13 +1,16 @@
 import * as React from 'react';
 import { Theme } from '@material-ui/core/styles';
 import { makeStyles } from '@material-ui/styles';
+import { StandardProps } from '@material-ui/core';
 import ClickAwayListener from '@material-ui/core/ClickAwayListener';
 import Paper from '@material-ui/core/Paper';
 import Popper from '@material-ui/core/Popper';
 import { GridApiContext } from '../GridApiContext';
 import { isEscapeKey, isMuiV5, createTheme } from '../../utils';
 
-export interface GridPanelProps extends React.HTMLAttributes<HTMLDivElement> {
+export type GridPanelClassKey = 'root' | 'theme';
+
+export interface GridPanelProps extends StandardProps<React.HTMLAttributes<HTMLDivElement>, GridPanelClassKey> {
   children?: React.ReactNode;
   open: boolean;
 }
@@ -33,7 +36,7 @@ export const GridPanel = React.forwardRef<HTMLDivElement, GridPanelProps>(functi
   ref,
 ) {
   const { children, open, ...other } = props;
-  const classes = useStyles();
+  const classes = useStyles(other);
   const apiRef = React.useContext(GridApiContext);
```

In the custom panel I can do then the following

```jsx
import * as React from "react";
import { makeStyles } from "@material-ui/core/styles";
import {
  XGrid,
  GridPanel,
  GridPanelProps,
  GridToolbar
} from "@material-ui/x-grid";
import { useDemoData } from "@material-ui/x-grid-data-generator";

const useStyles = makeStyles({
  "@global": {
    "html, body, #__next": {
      height: "100%",
      margin: 0
    }
  }
});

const useMyPanelStyles = makeStyles((theme) => ({
  paper: ({ height }) => ({
    maxHeight: height ? height + 32 : 450,
  }),
}));

const MyPanel = React.forwardRef<HTMLDivElement, GridPanelProps>(
  const apiRef = React.useContext(GridApiContext);
  const classes = useMyPanelStyles({
    height: apiRef!.current?.windowRef.current?.offsetHeight
  });

  function MyPanel(props, ref) {
    return (
      <GridPanel
        ref={ref}
        {...props}
        classes={{
          paper: classes.paper
        }}
        modifiers={{
          flip: {
            enabled: false
          },
          preventOverflow: {
            boundariesElement: "viewport"
          }
        }}
      />
    );
  }
);

/**
 * how you used the components
 */
export default function Demo() {
  useStyles();
  const { loading, data } = useDemoData({
    dataSet: "Commodity",
    rowLength: 1000,
    maxColumns: 20
  });

  return (
    <div
      style={{ height: 400, position: "absolute", bottom: 0, width: "100%" }}
    >
      <div style={{ display: "flex", height: "100%" }}>
        <div style={{ flexGrow: 1 }}>
          <XGrid
            {...data}
            components={{
              Toolbar: GridToolbar,
              Panel: MyPanel
            }}
            loading={loading}
            checkboxSelection
          />
        </div>
      </div>
    </div>
  );
}
```
