### ISSUE TITLE
Why does Material-UI datagrid select button not selecting any row

### ISSUE THREAD

**Issue by abhibhaw** [mui-org/material-ui-x#1820]
I have really simple data-grid component:
`<DataGrid
          rows={rows}
          columns={columns}
          pageSize={25}
          autoHeight
          onRowSelected={(x) => {
            setSelectedRow(x.api.current.getSelectedRows());
          }}
          checkboxSelection
        />`
The select all button of data-grid is not selecting any row. even clicking it again isn't deselecting.

Error in Console only after adding checkboxSelection prop:
`index.js:1 Material-UI: A component is changing the controlled checked state of SwitchBase to be uncontrolled.
Elements should not switch from uncontrolled to controlled (or vice versa).
Decide between using a controlled or uncontrolled SwitchBase element for the lifetime of the component.
The nature of the state is determined during the first render. It's considered controlled if the value is not undefined.`

Documentations says that the default behaviour of the data grid should be multi select but without using checkboxSelection, it's supporting only single selection.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
checkboxSelection prop is throwing error and not working as given in docs.
## Expected Behavior 🤔
Should select and deselect row on click

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
  Binaries:
    Node: 14.17.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 7.11.1 - ~/github/gepton/bat/client/node_modules/.bin/npm
  Browsers:
    Chrome: 91.0.4472.77
    Firefox: 88.0.1
  npmPackages:
    @emotion/react: ^11.1.5 => 11.1.5 
    @emotion/styled: ^11.1.5 => 11.3.0 
    @material-ui/core: ^5.0.0-alpha.28 => 5.0.0-alpha.32 
    @material-ui/data-grid: ^4.0.0-alpha.27 => 4.0.0-alpha.27 
    @material-ui/icons: ^5.0.0-alpha.28 => 5.0.0-alpha.29 
    @material-ui/styled-engine:  5.0.0-alpha.26 
    @material-ui/styles: ^4.10.0 => 4.11.3 
    @material-ui/system:  5.0.0-alpha.31 
    @material-ui/types:  6.0.0 
    @material-ui/unstyled:  5.0.0-alpha.32 
    @material-ui/utils:  5.0.0-alpha.31 
    @types/react:  17.0.3 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
```
</details>

**Comment by dtassone** [comment]
Please provide minimum reproduction of the issue in a codesandbox.

Also please check https://material-ui.com/components/data-grid/selection/ to learn how to achieve the selection
