### ISSUE TITLE
[DataGrid] Fix renderCell false-ish value rendering

### ISSUE THREAD

**Issue by cswan-log** [mui-org/material-ui-x#1849]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Using `formattedValue` in a custom `renderCell` will render nothing on a boolean typed cell.

## Expected Behavior 🤔

Should render a ❌ or ✔ based on the value. Other value formatters are working correctly (date, dateTime). See example.

## Steps to Reproduce 🕹

https://codesandbox.io/s/bitter-forest-sd9tp?file=/src/index.tsx

Steps:

1. Add custom `renderCell` function to column definition which renders via `params.formattedValue`
2. Add boolean type to column definition
3. Add data

## Context 🔦

I want to change the rendering of a given cell, but want to use the default formatting in it.

Also tried to use the "old" `renderCell` function of the given column but this also renders nothing.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  System:
    OS: macOS 11.3.1
  Binaries:
    Node: 14.17.0 - /usr/local/opt/node@14/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/opt/node@14/bin/npm
  Browsers:
    Chrome: 91.0.4472.77
    Edge: Not Found
    Firefox: Not Found
    Safari: 14.1
  npmPackages:
    @material-ui/core: ^4.11.4 => 4.11.4 
    @material-ui/icons: ^4.11.2 => 4.11.2 
    @material-ui/lab: ^4.0.0-alpha.58 => 4.0.0-alpha.58 
    @material-ui/styles:  4.11.4 
    @material-ui/system:  4.11.3 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @material-ui/x-grid: ^4.0.0-alpha.30 => 4.0.0-alpha.30 
    @material-ui/x-license:  4.0.0-alpha.30 
    @types/react: ^17.0.6 => 17.0.6 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    styled-components: ^5.3.0 => 5.3.0 
    typescript: ^4.2.4 => 4.2.4 

```

Tested on latest chrome and firefox dev
</details>

**Comment by oliviertassinari** [comment]
@cswan-log It's not very clear what you are trying. You mention "Should render a ❌ or ✔ based on the value." but you render a boolean instead. Could you provide more details on the problem you are facing and comment on what's bellow ⬇️ ? Thanks

---

In any case, I had a look at the issue and noticed a couple of interesting things. First, the logic is failing in the classical false-ish boolean comparison trap. Consider:

```jsx
import { DataGrid } from "@material-ui/data-grid";
import * as React from "react";
import ReactDOM from "react-dom";

const rootElement = document.getElementById("root");

ReactDOM.render(
  <div style={{ display: "flex", height: "100%" }}>
    <div style={{ flexGrow: 1 }}>
      <div>Foobar</div>
      <DataGrid
        autoHeight
        columns={[
          {
            field: "loading",
            headerName: "Loading",
            type: "boolean",
            flex: 1,
            renderCell: (params) => {
              return 0;
            }
          }
        ]}
        rows={[
          {
            id: 1,
            loading: false
          },
          {
            id: 2,
            loading: true
          }
        ]}
      />
    </div>
  </div>,
  rootElement
);
```

https://codesandbox.io/s/mystifying-morning-zyh5l?file=/src/index.tsx:0-793

Why is it rendering `true`/`false`? Wrong, it should render `0`. This would fix it:

```diff
diff --git a/packages/grid/_modules_/grid/components/cell/GridCell.tsx b/packages/grid/_modules_/grid/components/cell/GridCell.tsx
index 2cde4e64..e7dc84b7 100644
--- a/packages/grid/_modules_/grid/components/cell/GridCell.tsx
+++ b/packages/grid/_modules_/grid/components/cell/GridCell.tsx
@@ -174,7 +174,7 @@ export const GridCell = React.memo((props: GridCellProps) => {
       tabIndex={tabIndex}
       {...eventsHandlers}
     >
-      {children || valueToRender?.toString()}
+      {children != null ? children : valueToRender?.toString()}
     </div>
   );
 });
```

Second, it does seem to make sense to have a value formatter:

```diff
diff --git a/packages/grid/_modules_/grid/models/colDef/gridBooleanColDef.tsx b/packages/grid/_modules_/grid/models/colDef/gridBooleanColDef.tsx
index 1a26ea9a..8c8c03d4 100644
--- a/packages/grid/_modules_/grid/models/colDef/gridBooleanColDef.tsx
+++ b/packages/grid/_modules_/grid/models/colDef/gridBooleanColDef.tsx
@@ -1,15 +1,24 @@
 import { GRID_STRING_COL_DEF } from './gridStringColDef';
 import { GridColTypeDef } from './gridColDef';
+import { GridCellValue } from '../gridCell';
 import { renderBooleanCell } from '../../components/cell/GridBooleanCell';
 import { renderEditBooleanCell } from '../../components/cell/GridEditBooleanCell';
 import { gridNumberComparer } from '../../utils/sortingUtils';
 import { getGridBooleanOperators } from './gridBooleanOperators';

+export function gridBooleanFormatter({ value }: { value: GridCellValue }) {
+  if (typeof value === 'boolean') {
+    return value.toString();
+  }
+  return value;
+}
+
 export const GRID_BOOLEAN_COL_DEF: GridColTypeDef = {
   ...GRID_STRING_COL_DEF,
   type: 'boolean',
   align: 'center',
   headerAlign: 'center',
+  valueFormatter: gridBooleanFormatter,
   renderCell: renderBooleanCell,
   renderEditCell: renderEditBooleanCell,
   sortComparator: gridNumberComparer,
```

to fix the codesandbox provided in the issue: https://codesandbox.io/s/thirsty-dewdney-sbvek

**Comment by cswan-log** [comment]
@oliviertassinari Looking at the docs here (https://material-ui.com/components/data-grid/columns/#column-types) setting the type of a column to "boolean" it will render a checkmark or cross accordingly. 
![grafik](https://user-images.githubusercontent.com/63999494/121852191-66454d80-ccef-11eb-86e7-9232b8129a47.png)

Thus I assumed using the "formattedValue" for rendering the cell would yield the same behaviour rendering a checkmark / cross.

**Comment by dtassone** [comment]
> @cswan-log It's not very clear what you are trying. You mention "Should render a ❌ or ✔ based on the value." but you render a boolean instead. Could you provide more details on the problem you are facing and comment on what's bellow ⬇️ ? Thanks
> 
> In any case, I had a look at the issue and noticed a couple of interesting things. First, the logic is failing in the classical false-ish boolean comparison trap. Consider:
> 
> ```js
> import { DataGrid } from "@material-ui/data-grid";
> import * as React from "react";
> import ReactDOM from "react-dom";
> 
> const rootElement = document.getElementById("root");
> 
> ReactDOM.render(
>   <div style={{ display: "flex", height: "100%" }}>
>     <div style={{ flexGrow: 1 }}>
>       <div>Foobar</div>
>       <DataGrid
>         autoHeight
>         columns={[
>           {
>             field: "loading",
>             headerName: "Loading",
>             type: "boolean",
>             flex: 1,
>             renderCell: (params) => {
>               return 0;
>             }
>           }
>         ]}
>         rows={[
>           {
>             id: 1,
>             loading: false
>           },
>           {
>             id: 2,
>             loading: true
>           }
>         ]}
>       />
>     </div>
>   </div>,
>   rootElement
> );
> ```
> 
> https://codesandbox.io/s/mystifying-morning-zyh5l?file=/src/index.tsx:0-793
> 
> <img alt="Capture d’écran 2021-06-13 à 22 32 47" width="166" src="https://user-images.githubusercontent.com/3165635/121821136-4b46ef00-cc97-11eb-8a76-25fa072681a8.png">
> 
> Why is it rendering `true`/`false`? Wrong, it should render `0`. This would fix it:
> 
> ```diff
> diff --git a/packages/grid/_modules_/grid/components/cell/GridCell.tsx b/packages/grid/_modules_/grid/components/cell/GridCell.tsx
> index 2cde4e64..e7dc84b7 100644
> --- a/packages/grid/_modules_/grid/components/cell/GridCell.tsx
> +++ b/packages/grid/_modules_/grid/components/cell/GridCell.tsx
> @@ -174,7 +174,7 @@ export const GridCell = React.memo((props: GridCellProps) => {
>        tabIndex={tabIndex}
>        {...eventsHandlers}
>      >
> -      {children || valueToRender?.toString()}
> +      {children != null ? children : valueToRender?.toString()}
>      </div>
>    );
>  });
> ```
> 
> Second, it does seem to make sense to have a value formatter:
> 
> ```diff
> diff --git a/packages/grid/_modules_/grid/models/colDef/gridBooleanColDef.tsx b/packages/grid/_modules_/grid/models/colDef/gridBooleanColDef.tsx
> index 1a26ea9a..8c8c03d4 100644
> --- a/packages/grid/_modules_/grid/models/colDef/gridBooleanColDef.tsx
> +++ b/packages/grid/_modules_/grid/models/colDef/gridBooleanColDef.tsx
> @@ -1,15 +1,24 @@
>  import { GRID_STRING_COL_DEF } from './gridStringColDef';
>  import { GridColTypeDef } from './gridColDef';
> +import { GridCellValue } from '../gridCell';
>  import { renderBooleanCell } from '../../components/cell/GridBooleanCell';
>  import { renderEditBooleanCell } from '../../components/cell/GridEditBooleanCell';
>  import { gridNumberComparer } from '../../utils/sortingUtils';
>  import { getGridBooleanOperators } from './gridBooleanOperators';
> 
> +export function gridBooleanFormatter({ value }: { value: GridCellValue }) {
> +  if (typeof value === 'boolean') {
> +    return value.toString();
> +  }
> +  return value;
> +}
> +
>  export const GRID_BOOLEAN_COL_DEF: GridColTypeDef = {
>    ...GRID_STRING_COL_DEF,
>    type: 'boolean',
>    align: 'center',
>    headerAlign: 'center',
> +  valueFormatter: gridBooleanFormatter,
>    renderCell: renderBooleanCell,
>    renderEditCell: renderEditBooleanCell,
>    sortComparator: gridNumberComparer,
> ```
> 
> to fix the codesandbox provided in the issue: https://codesandbox.io/s/thirsty-dewdney-sbvek

I think the usage of rendercell is wrong here, it should return a ReactElement. If you would like to override the value, you should use valuegetter or if you need to format it then valueFormatter

**Comment by oliviertassinari** [comment]
> it should return a ReactElement

@dtassone Why? It accepts a node for flexibility. 

> not sure why you need gridBooleanFormatter as the grid should call toString() automatically

Because React doesn't render boolean. But @cswan-log has just invalidated this idea with his previous comment. So it's only about the first problem of https://github.com/mui-org/material-ui-x/issues/1849#issuecomment-860266414

**Comment by siriwatknp** [comment]
[This PR](https://github.com/mui-org/material-ui-x/pull/2242) fixes @oliviertassinari comment but not related to what @cswan-log describe. I suggest next time @oliviertassinari should open a new issue instead of renaming, it confused me at first.

**Comment by oliviertassinari** [comment]
@siriwatknp Yeah, the feedback of @cswan-log is not actionable for us, AFAIK. At its core, it was a question for something we already document. We could have closed and opened a new issue for the opportunity we found diving into the logic.
