### ISSUE TITLE
[DataGrid] api missing disableDensitySelector

### ISSUE THREAD

**Issue by Vixata32** [mui-org/material-ui-x#1851]
On the XGrid api page  - https://material-ui.com/api/x-grid/ is missing the disableDensitySelector, which is available in the code as I see it here: https://github.com/mui-org/material-ui-x/blob/f5642ae7fe19ed8b8998182c1a6f49c2ff7bb149/packages/grid/_modules_/grid/components/toolbar/GridDensitySelector.tsx
    // Disable the button if the corresponding is disabled    if (options.disableDensitySelector) {      return null;    }

This is also for the disableColumnFilter.

**Comment by oliviertassinari** [comment]
We will fix the root cause in https://github.com/mui-org/material-ui-x/issues/1211 until then, we can update the docs manually.
