### ISSUE TITLE
Data Grid not render rows at another page than 1 - client

### ISSUE THREAD

**Issue by na5tyk** [mui-org/material-ui-x#1853]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

In client pagination not render rows. it's empty. 

## Expected Behavior 🤔

Should render rows on antoher pages.

## Steps to Reproduce 🕹

Steps:

1. Load data from backend by link https://dev.giap.pl/api/v1/boleslawiec/map_portal/?filter_empty=true&page=1&page_size=2
2. Change page
3. After change page take data from backend by link https://dev.giap.pl/api/v1/boleslawiec/map_portal/?filter_empty=true&page=2&page_size=2

## Context 🔦
-
## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  System:

    OS: Linux 4.15 Linux Mint 19.2 (Tina)

  Binaries:

    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node

    Yarn: 1.22.5 - /usr/bin/yarn

    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm

  Browsers:

    Chrome: 89.0.4389.90

    Firefox: 86.0.1

  npmPackages:

    @material-ui/core: ^4.11.4 => 4.11.4 

    @material-ui/data-grid: 4.0.0-alpha.30 => 4.0.0-alpha.30 

    @material-ui/icons: ^4.11.2 => 4.11.2 

    @material-ui/styles:  4.11.4 

    @material-ui/system:  4.11.3 

    @material-ui/types:  5.1.0 

    @material-ui/utils:  4.11.2 

    @types/react: ^17.0.5 => 17.0.6 

    react: 17.0.2 => 17.0.2 

    react-dom: 17.0.2 => 17.0.2 

    styled-components: ^5.3.0 => 5.3.0 

    typescript: ^4.2.4 => 4.2.4 

</details>

**Comment by dtassone** [comment]
your links don't work. They are being redirected

**Comment by na5tyk** [comment]
I have updated the links

**Comment by oliviertassinari** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://material-ui.com/r/issue-template) _may_ be a good starting point. Thank you!
