### ISSUE TITLE
[DataGrid] Wildcard char in filters crashes

### ISSUE THREAD

**Issue by pthomas931** [mui-org/material-ui-x#1857]
Filtering a column using contains `*` FireFox throws a `SyntaxError: nothing to repeat` error. 

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When doing a column filter for Contains * on a string type column the browser throws an error.

<img width="477" alt="image" src="https://user-images.githubusercontent.com/606946/121212080-08c28400-c84b-11eb-9ebc-8ca608768d44.png">

Firefox Error:
<img width="462" alt="image" src="https://user-images.githubusercontent.com/606946/121212173-1aa42700-c84b-11eb-9b85-4d0e1771219a.png">

Chrome Error:
<img width="512" alt="image" src="https://user-images.githubusercontent.com/606946/121213971-b8e4bc80-c84c-11eb-8455-f4ff8a7f4060.png">

## Expected Behavior 🤔

String Column contains `*` should either be treated as a wild card or return no results.

## Steps to Reproduce 🕹

Using the data grid demo on sandbox: https://codesandbox.io/s/7vhnz

Steps:

1. Select First Name column's "Filter" option
2. In the Filter Pane select Contains option with a Value of *
- <img width="477" alt="image" src="https://user-images.githubusercontent.com/606946/121212080-08c28400-c84b-11eb-9ebc-8ca608768d44.png">

## Context 🔦

I was attempting to filter for non-empty strings in a column and attempted `*` as a sort of wild card character. 

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Unable to provide
```
</details>

Repeatable on the Material-UI provided demo:  https://codesandbox.io/s/7vhnz?file=/index.tsx

Browsers: Firefox and Chrome

**Comment by dtassone** [comment]
Good point!
Have you tried \*? 
Handling wildcard would be a great enhancement to filters, but we already operators that allow a lot of similar operation.
ie `soy*` = starts with soy 

At least it should not crash so that's an issue

**Comment by pthomas931** [comment]
Considering the filters trigger the RegEx onChange instead of onBlur this is actually an issue with most of the RegEx characters. Attempting to type `\*` will bomb on the `\` as an invalid regex.

**Comment by dtassone** [comment]
I see yes, we should definitely sort that out. Thanks for raising

**Comment by oliviertassinari** [comment]
Maybe with an escape of the regexp input?

```diff
diff --git a/packages/grid/_modules_/grid/models/colDef/gridStringOperators.ts b/packages/grid/_modules_/grid/models/colDef/gridStringOperators.ts
index c2139e7c..11113604 100644
--- a/packages/grid/_modules_/grid/models/colDef/gridStringOperators.ts
+++ b/packages/grid/_modules_/grid/models/colDef/gridStringOperators.ts
@@ -2,6 +2,10 @@ import { GridFilterInputValue } from '../../components/panel/filterPanel/GridFil
 import { GridFilterItem } from '../gridFilterItem';
 import { GridFilterOperator } from '../gridFilterOperator';

+function escapeRegExp(text) {
+  return text.replace(/[-[\]{}()*+?.,\\^$|#\s]/g, '\\$&');
+}
+
 export const getGridStringOperators: () => GridFilterOperator[] = () => [
   {
     value: 'contains',
@@ -10,7 +14,7 @@ export const getGridStringOperators: () => GridFilterOperator[] = () => [
         return null;
       }

-      const filterRegex = new RegExp(filterItem.value, 'i');
+      const filterRegex = new RegExp(escapeRegExp(filterItem.value), 'i');
       return ({ value }): boolean => {
         return filterRegex.test((value && value.toString()) || '');
       };
@@ -40,7 +44,7 @@ export const getGridStringOperators: () => GridFilterOperator[] = () => [
         return null;
       }

-      const filterRegex = new RegExp(`^${filterItem.value}.*$`, 'i');
+      const filterRegex = new RegExp(`^${escapeRegExp(filterItem.value)}.*$`, 'i');
       return ({ value }): boolean => {
         return filterRegex.test((value && value.toString()) || '');
       };
@@ -54,7 +58,7 @@ export const getGridStringOperators: () => GridFilterOperator[] = () => [
         return null;
       }

-      const filterRegex = new RegExp(`.*${filterItem.value}$`, 'i');
+      const filterRegex = new RegExp(`.*${escapeRegExp(filterItem.value)}$`, 'i');
       return ({ value }): boolean => {
         return filterRegex.test((value && value.toString()) || '');
       };
```

or a `.toLowerCase()` on the string to do a direct comparison 🤷‍♂️

**Comment by dtassone** [comment]
Yes we should escape the chars, the `i` is fo invariant which means that it's not case sensitive

**Comment by rajjasoliya** [comment]
### Filter in all columns of Mui Datagrid Free

https://codesandbox.io/s/mui-x-issue-template-forked-dj2z4t?file=/src/App.tsx:1670-1682
