### ISSUE TITLE
[DataGrid] Extend selection with Shift + click

### ISSUE THREAD

**Issue by m4theushw** [mui-org/material-ui-x#1858]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Selecting rows while pressing <kbd>Shift</kbd> should select all rows between the last selected and the clicked one.

## Examples 🌈

https://marmelab.com/react-admin-demo/

<img width="550" src="https://user-images.githubusercontent.com/42154031/121238429-792ecc80-c86e-11eb-8d03-d617ea38b4d4.gif" alt="Ze0AFwvmb0" style="max-width:100%;">

## Motivation 🔦

https://github.com/mui-org/material-ui-x/pull/1813#discussion_r646925340

**Comment by oliviertassinari** [comment]
I would also add that it can be cumulative (there can be discontinued set of rows selected) and that it's not dependent on the checkbox selection (to clarify the video recording example).

**Comment by m4theushw** [comment]
About the discontinued set of rows, if shift + click is always based on the last selected they will be allowed.

**Comment by sebastianfrey** [comment]
In addition to the proposed `shift + click` range selection, how about supporting the following shortcuts as well:

`strg + click` - extend an existing range selection by the clicked row
`strg + shift + click` - extend an existing range selection by another range selection

**Comment by oliviertassinari** [comment]
> ctrl + click - extend an existing range selection by the clicked row

@sebastianfrey Isn't this already supported: https://material-ui.com/components/data-grid/selection/#multiple-row-selection.

> ctrl + shift + click - extend an existing range selection by another range selection

I'm not aware of any common multi-selection interface that implements this shortcut. I don't understand the use case. Extending an existing section can be done with ctrl + click and then shift + click.

**Comment by sebastianfrey** [comment]
>  >ctrl + click - extend an existing range selection by the clicked row
> 
> @sebastianfrey Isn't this already supported: https://material-ui.com/components/data-grid/selection/#multiple-row-selection?

You're right, this case seems already to be supported.

> ctrl + shift + click - extend an existing range selection by another range selection

> > I'm not aware of any common multi-selection interface that implements this shortcut. I don't understand the use case. We should already be able to extend an existing section with ctrl + click and then shift + click. It seems simpler.

I was refering to this kind of multi-selection shortcut available in windows explorer or for example in nautilus file manager on ubuntu:

![mui-xgrid-extend-selection](https://user-images.githubusercontent.com/15965420/121859226-bf18e400-ccf7-11eb-857a-153f0ae9fd94.gif)

You might notice, that `ctrl + click` and than `shift + click` will clear the previous range selection and you would have to use you would have to use `ctrl + shift + click` for multiple range selections.

Hower, when this component will support multiple range selections by `ctrl + click` and `shift-click` I am happy with that. =)

**Comment by oliviertassinari** [comment]
> I was refering to this kind of multi-selection shortcut available in windows explorer or for example in nautilus file manager on ubuntu:

Interesting, I'm on macOS, it behaves differently.
