### ISSUE TITLE
[DataGrid] Filter and check all Checkbox selects all items

### ISSUE THREAD

**Issue by phettz** [mui-org/material-ui-x#1863]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
When I filter the items in the grid and use the select all checkbox it selects the items thats filtered out too. It seems to work correctly if the filter only return a couple of items. 

## Expected Behavior 🤔

selectionModel should only have items from the filtered items when I use the select all checkbox.

## Steps to Reproduce 🕹

```javascript
import * as React from "react";
import { DataGrid } from "@material-ui/data-grid";
import { useDemoData } from "@material-ui/x-grid-data-generator";

export default function DisableClickSelectionGrid() {
  const { data } = useDemoData({
    dataSet: "Commodity",
    rowLength: 300,
    maxColumns: 6
  });

  return (
    <div style={{ height: 400, width: "100%" }}>
      <DataGrid
        checkboxSelection
        disableSelectionOnClick
        {...data}
        onSelectionModelChange={(selection) => {
          console.log("selection", selection);
        }}
      />
    </div>
  );
}
```
[https://codesandbox.io/s/material-demo-forked-3d6n8?file=/demo.tsx](https://codesandbox.io/s/material-demo-forked-3d6n8?file=/demo.tsx)

Steps:

1. Click the Desk colum filter, filter on "D-1"
2. Check the select all checkbox
3. The console will log 300, expected 31

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

## Order id 💳
22396

**Comment by oliviertassinari** [comment]
@mui-org/x The issue has been left abandoned for 10 days. Please use the ["status: needs triage"](https://github.com/mui-org/material-ui-x/labels/status%3A%20needs%20triage) label to find the issues that need to receive attention.

---

@phettz We cover this problem in point 3. of https://github.com/mui-org/material-ui-x/issues/1141#issuecomment-850977514. #1879 is fixing the issue
