### ISSUE TITLE
[XGrid] Column sorting in the grid toolbar does not do anything

### ISSUE THREAD

**Issue by StewartThomson** [mui-org/material-ui-x#1867]
Column sorting in the grid toolbar does not do anything

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
The "sorting" ui element of the column button in the toolbar is not functional

## Expected Behavior 🤔
Based on the UI element, it should be re-orderable

## Steps to Reproduce 🕹
https://codesandbox.io/s/pedantic-voice-s10il

Steps:

1. Click "Columns"
2. Attempt to drag around columns with the six-dot UI element

## Context 🔦
Trying to use the ui element

## Your Environment 🌎
<details>
  <summary>`npx @material-ui/envinfo`</summary>
  System:
    OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
  Binaries:
    Node: 16.0.0 - ~/.config/nvm/16.0.0/bin/node
    Yarn: Not Found
    npm: 7.10.0 - ~/.config/nvm/16.0.0/bin/npm
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 89.0
  npmPackages:
    @emotion/react: ^11.4.0 => 11.4.0 
    @emotion/styled: ^11.3.0 => 11.3.0 
    @material-ui/core: 5.0.0-alpha.34 => 5.0.0-alpha.34 
    @material-ui/data-grid:  4.0.0-alpha.31 
    @material-ui/icons: 5.0.0-alpha.34 => 5.0.0-alpha.34 
    @material-ui/lab: 5.0.0-alpha.34 => 5.0.0-alpha.34 
    @material-ui/private-theming:  5.0.0-alpha.33 
    @material-ui/styled-engine:  5.0.0-alpha.34 
    @material-ui/styles:  5.0.0-alpha.33 
    @material-ui/system: 5.0.0-alpha.34 => 5.0.0-alpha.34 
    @material-ui/types:  6.0.0 
    @material-ui/unstyled:  5.0.0-alpha.34 
    @material-ui/utils:  5.0.0-alpha.33 
    @material-ui/x-grid: 4.0.0-alpha.31 => 4.0.0-alpha.31 
    @material-ui/x-license:  4.0.0-alpha.31 
    @types/react:  17.0.6 
    react: ^17.0.1 => 17.0.2 
    react-dom: ^17.0.1 => 17.0.2 
    typescript: ^4.3.2 => 4.3.2 

</details>

## Order id 💳
Order #25141

**Comment by oliviertassinari** [comment]
@StewartThomson Well spotted, we forgot to add the feature flag to hide these icons. I'm amazed it went unnoticed for 7 months. I would propose this fix:

```diff
diff --git a/packages/grid/_modules_/grid/components/panel/GridColumnsPanel.tsx b/packages/grid/_modules_/grid/components/panel/GridColumnsPanel.tsx
index 6063cef6..8282d960 100644
--- a/packages/grid/_modules_/grid/components/panel/GridColumnsPanel.tsx
+++ b/packages/grid/_modules_/grid/components/panel/GridColumnsPanel.tsx
@@ -8,6 +8,7 @@ import { makeStyles } from '@material-ui/styles';
 import { allGridColumnsSelector } from '../../hooks/features/columns/gridColumnsSelector';
 import { useGridSelector } from '../../hooks/features/core/useGridSelector';
 import { optionsSelector } from '../../hooks/utils/optionsSelector';
+import { GRID_EXPERIMENTAL_ENABLED } from '../../constants/envConstants';
 import { GridApiContext } from '../GridApiContext';
 import { GridDragIcon } from '../icons/index';
 import { GridPanelContent } from './GridPanelContent';
@@ -117,7 +118,7 @@ export function GridColumnsPanel() {
                 }
                 label={column.headerName || column.field}
               />
-              {!disableColumnReorder && (
+              {!disableColumnReorder && GRID_EXPERIMENTAL_ENABLED && (
                 <IconButton
                   draggable
                   className={classes.dragIcon}
```
