### ISSUE TITLE
[XGrid] Columns resizing doesn't work

### ISSUE THREAD

**Issue by MiladNazeri** [mui-org/material-ui-x#1875]
- [x ] The issue is present in the latest release.
- [x ] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
In X-Grid, columns are not able to be adjusted.  

## Expected Behavior 🤔
Columns should be able to adjust like what you are showing on the X-Grid demo page.  Every other X-Grid feature is working.

## Steps to Reproduce 🕹
I'm not sure how else to explain this reproduction.  I load up X-Grid and can't resize the columns.  The pointer to move between the columns does not show up.  

## Context 🔦
This was the major reason we spent the money to get the upgrade and if it's not working as expected, we would appreciate a refund.

## Your Environment 🌎
<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.6.0 - D:\ROLC_AdventureLab\O\repos\platform\host_schedule\adventure-lab_host-scheduling\node_m
odules\.bin\npm.CMD
  Browsers:
    Chrome: 91.0.4472.101
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.41)
  npmPackages:
    @material-ui/core: ^4.11.3 => 4.11.3
    @material-ui/data-grid: ^4.0.0-alpha.20 => 4.0.0-alpha.20
    @material-ui/icons: ^4.11.2 => 4.11.2
    @material-ui/lab: ^4.0.0-alpha.57 => 4.0.0-alpha.57
    @material-ui/pickers: ^3.2.10 => 3.2.10
    @material-ui/styles:  4.11.3
    @material-ui/system:  4.11.3
    @material-ui/types:  5.1.0
    @material-ui/utils:  4.11.2
    @material-ui/x-grid: ^4.0.0-alpha.29 => 4.0.0-alpha.29
    @material-ui/x-license:  4.0.0-alpha.29
    @types/react:  17.0.2
    react: ^17.0.1 => 17.0.1
    react-dom: ^17.0.1 => 17.0.1

Latest stable version of Chrome

</details>

## Order id 💳
25359

If I can think of a way to fill in the sandbox that makes sense, I'll update this.

**Comment by dtassone** [comment]
Have you had a look at the documentation?
https://material-ui.com/components/data-grid/columns/#resizing

Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://material-ui.com/r/issue-template) _may_ be a good starting point. Thank you!

**Comment by MiladNazeri** [comment]
Yes I have, and the main thing it states is "By default, XGrid allows all columns to be resized by dragging the right portion of the column separator.".  I have not put any resize false in.

Like I said, I'm not sure I can reproduce it on the sandbox if it's just going to show like how your demo does.  It's simply XGrid with columns and data used normally, especially when compared to your demo.  I'll revisit this later today when I can.

**Comment by MiladNazeri** [comment]
This is the video of it btw - https://mindeyemilad-gmail.tinytake.com/tt/NTQ0NjMzOF8xNzAyNzQ4Nw

**Comment by dtassone** [comment]
I can clearly see on your video that the separator is not there.
So either you do some css or tricks to hide it or you are using `<DataGrid />` instead of `<XGrid />`

**Comment by MiladNazeri** [comment]
I'm definitely using XGrid.  Every other function is working like multiple filters.  

I don't know what possible css tricks I would be doing to hide it.  What could you even do to do that?  I'll review, but insight there would be very helpful.

**Comment by MiladNazeri** [comment]
This is the specific Component code

```const columns = [
    { width: 120, field: 'status', headerName: 'status', description: 'status', renderCell: (GridCellParams) => {
        return (<>{GridCellParams.value}{GridCellParams.row.recurringShow ? <Repeat fontSize="small"></Repeat> : ""}</>)
    }, resizable: true },
    {width: 120, field: 'tickets', headerName: 'tickets', description: 'tickets', type: 'number', resizable: true },
    {resizable: true,width: 150, field: 'date', headerName: 'date', description: 'date', type: 'string' },
    {resizable: true, width: 120, field: 'time', headerName: 'time', description: 'time' },
    {resizable: true, width: 120, field: 'roomCode', headerName: 'roomCode', description: 'roomCode'},
    {resizable: true, width: 120, field: 'price', headerName: '$', description: 'price', type: 'number' },
    {resizable: true, width: 160, field: 'experience', headerName: 'experience', description: 'experience' },
    {resizable: true, width: 160, field: 'additionalNote', headerName: 'Notes', description: 'additional note'},
    {resizable: true, width: 145, field: 'showtime', headerName: 'showtime', description: 'showtime' },
    {resizable: true, width: 150, field: 'recurringShow', headerName: 'recurringShow', description: 'recurringShow'},
];```

```                <XGrid
                    autoHeight
                    className={classes.showsTable}
                    rows={newShowsRows} 
                    disableColumnResize={false}
                    columns={[...columns, ...(user.isAdmin ? adminColumns: [])]} 
                    components={{
                        Toolbar: GridToolbar
                    }}
                    // disableSelectionOnClick
                    showCellRightBorder
                    loading={newShowsRows.length <= 0}
                    sortModel={[
                        {
                            field: 'showtime',
                            sort: 'asc'
                        }
                    ]}
                    onRowClick={handleRowClicked}
                    filterModel={
                        {
                            items: (selectedDaysKeys.length > 0 
                                ?
                                    Object.keys(selectedDays).map(day => ({
                                        columnField: 'date', 
                                        operatorValue: 'contains', 
                                        value: day
                                    }))
                                :
                                []),
                            linkOperator: GridLinkOperator.Or
                        }
                    }
                />```

```    showsTable: {
        width: '100%',
    },```

I only put those resizable true just to see.  I've also tried removing the widths and it is the same.

**Comment by MiladNazeri** [comment]
What would that middle column resize indicator show up as if I looked in inspector?

**Comment by MiladNazeri** [comment]
![image](https://user-images.githubusercontent.com/11789978/121741032-ce5b2000-cab2-11eb-89f3-7f817d1a9749.png)
Guessing this is it

**Comment by oliviertassinari** [comment]
Closing as no reproduction have been provided.
