### ISSUE TITLE
@material-ui/x-grid-data-generator error: 'withStyles' is not exported from '@material-ui/core/styles'

### ISSUE THREAD

**Issue by jmgomezdev** [mui-org/material-ui-x#1878]
Material-UI 5.0.0-alpha.35 or higher is not compatible with x-grid-data-generator, since withStyles is not longer in @material-ui/core.

This is the specific error:
```
./node_modules/@material-ui/x-grid-data-generator/node_modules/@material-ui/lab/esm/Rating/Rating.js
Attempted import error: 'withStyles' is not exported from '@material-ui/core/styles'.

```

**Comment by oliviertassinari** [comment]
@jmgomezdev Do you have a reproduction? As far as I know, if you update the packages to the latest version, the issue will be gone.

**Comment by jmgomezdev** [comment]
This is the example of the web, but with the latest existing dependencies:
https://codesandbox.io/s/material-demo-forked-nb03i?file=/index.js
Thanks you for your attention

**Comment by jmgomezdev** [comment]
This is the example of the web, but with the latest existing dependencies:
https://codesandbox.io/s/example-x-grid-o2ie5
Thanks you for your attention

**Comment by oliviertassinari** [comment]
@jmgomezdev Thanks. It's basically the same issue as #1414. One solution would be to have 

```diff
diff --git a/packages/grid/x-grid-data-generator/package.json b/packages/grid/x-grid-data-generator/package.json
index 634684d9..4081edea 100644
--- a/packages/grid/x-grid-data-generator/package.json
+++ b/packages/grid/x-grid-data-generator/package.json
@@ -22,8 +22,6 @@
     "build": "cd ../ && rollup --config rollup.x-grid-data-generator.config.js"
   },
   "dependencies": {
-    "@material-ui/icons": "^4.9.1",
-    "@material-ui/lab": "^4.0.0-alpha.54",
     "@types/chance": "^1.1.0",
     "chance": "^1.1.6",
     "clsx": "^1.0.4",
@@ -35,6 +33,8 @@
   },
   "peerDependencies": {
     "@material-ui/core": "^4.9.12 || ^5.0.0-alpha.34",
+    "@material-ui/icons": "^4.9.1 || ^5.0.0-alpha.34",
+    "@material-ui/lab": "^4.0.0-alpha.54 || ^5.0.0-alpha.34",
     "react": "^17.0.0"
   },
   "setupFiles": [
```

only during the time where we support v4 and v5, then revert once we drop v5, alongside removing this section:

https://github.com/mui-org/material-ui-x/blob/ef1ea4be12d9b776e4cababf18b8e4e70fb5f677/docs/pages/_app.js#L54-L58
