### ISSUE TITLE
[DataGrid] Allow to hide the "Select All" checkbox

### ISSUE THREAD

**Issue by satoi8080** [mui-org/material-ui-x#1904]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

If it is true, then the 'Select All' checkbox will disappear.

https://material-ui.com/components/data-grid/selection/#checkbox-selection

## Examples 🌈

It just disappears.
## Motivation 🔦

I'm building a medical app so that users should't select all items at once instead of selecting them one by one carefully. So that the 'Select All' checkbox should be hidden.

**Comment by dtassone** [comment]
So it seems that you just want to individual checkbox without the header one.
Have you considered hiding the select all checkbox using css?

**Comment by oliviertassinari** [comment]
Have you also consider rendering a custom column with its own checkboxes (instead of using the `checkboxSelection` prop)?

**Comment by satoi8080** [comment]
> So it seems that you just want the individual checkboxes without the header one.
> Have you considered hiding the select all checkbox using css?
@dtassone 
I tried to set the following lines in css but it didn't work (but background-color: black did work in that header cell)
```
.MuiDataGrid-columnHeaderCheckbox{
    display: none;
}
```

**Comment by dtassone** [comment]
@satoi8080 you might need to be more specific with your selector.
try 
```
.MuiDataGrid-root .MuiDataGrid-columnHeaderCheckbox .MuiDataGrid-columnHeaderTitleContainer {
    display: none;
}
```

**Comment by satoi8080** [comment]
@dtassone Thanks! It works! Shall we add it to the documents or add the feature I described? I think there will be probabaly someone having multiple DataGrids in one component and need some header checkbox hidden and some shown. It would help a lot if there were a prop to hide the checkbox. (of course some work arounds may work though)

**Comment by satoi8080** [comment]
> @satoi8080 Have you also consider rendering a custom column with its own checkboxes (instead of using the `checkboxSelection` prop)?

@oliviertassinari Thanks for your reply, but I've already done a lot about selectionModel and isRowSelectable in my app. It would need a lot of refactoring then.

**Comment by oliviertassinari** [comment]
Then, I would propose we close with this answer https://github.com/mui-org/material-ui-x/issues/1904#issuecomment-862240433.

```jsx
import * as React from "react";
import { DataGrid } from "@material-ui/data-grid";
import { makeStyles } from "@material-ui/core/styles";
import { useDemoData } from "@material-ui/x-grid-data-generator";

const useStyles = makeStyles((theme) => ({
  root: {
    "& .MuiDataGrid-columnHeaderCheckbox .MuiDataGrid-columnHeaderTitleContainer": {
      display: "none"
    }
  }
}));

export default function SizePaginationGrid() {
  const classes = useStyles();
  const { data } = useDemoData({
    dataSet: "Commodity",
    rowLength: 100,
    maxColumns: 6
  });

  return (
    <div style={{ height: 400, width: "100%" }}>
      <DataGrid className={classes.root} checkboxSelection {...data} />
    </div>
  );
}
```

https://codesandbox.io/s/material-demo-forked-hddwp?file=/demo.tsx:0-713

<img width="346" alt="Capture d’écran 2021-06-17 à 02 42 52" src="https://user-images.githubusercontent.com/3165635/122313028-c1588980-cf15-11eb-8629-95788fdfff4e.png">

**Comment by satoi8080** [comment]
@oliviertassinari Thank you so much for your friendly help!

**Comment by dtassone** [comment]
Should we add`disableSelectAllCheckbox` prop 👍 ? Or happy with the solution above 👎 ?

```tsx
   <DataGrid  {...data}  checkboxSelection disableSelectAllCheckbox />
```

**Comment by oliviertassinari** [comment]
@dtassone If we have a doubt, we could close and leave the 
<img width="120" alt="Capture d’écran 2021-06-18 à 00 50 20" src="https://user-images.githubusercontent.com/3165635/122481548-2b813500-cfcf-11eb-95db-ef3637957e62.png">

label to gather feedback.

**Comment by oliviertassinari** [comment]
I have added the `waiting for users upvotes` tag. I'm closing the issue as we are not sure enough people are looking for such capability. So please upvote this issue if you are. We will prioritize our effort based on the number of upvotes.

**Comment by jmmwangi007** [comment]
Was this ever added?

**Comment by ak-mid** [comment]
@oliviertassinari I wonder if this issue did drop out of sight because the comment of dtassone has already 32 upvotes and it looks like a simple feature to me.

**Comment by guicara** [comment]
I hope the `disableSelectAllCheckbox` prop will be added soon. It's a must-have feature!

In the meantime, as stated above, CSS can be used to hide the column checkbox. Based on  @oliviertassinari's answer, here is an updated and simpler version for the current version of MUI:

```
  <DataGrid
    ...
    sx={{
      "& .MuiDataGrid-columnHeaderCheckbox .MuiDataGrid-columnHeaderTitleContainer": {
        display: "none"
      }
    }}
  />
```

**Comment by BryceMehring** [comment]
This feature should be added. Even with hiding the the select all checkbox via CSS you can still navigate to that empty column via tab navigation on keyboard

**Comment by serban-condrea** [comment]
You can use a custom header renderer to remove the checkbox from the DOM

```
const columns = [
    {
      ...GRID_CHECKBOX_SELECTION_COL_DEF,
      renderHeader: () => <></>,
    },
    ...otherColumns
]
```

https://mui.com/x/react-data-grid/row-selection/#custom-checkbox-column

**Comment by marcosquixada** [comment]
how to make the title column next then to get the released space from the gone checkbox like a colSpan={2}?
