### ISSUE TITLE
[DataGrid] Improve support of cursor-based pagination

### ISSUE THREAD

**Issue by tobiasbueschel** [mui-org/material-ui-x#1906]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Hi all,

Thanks for your work with this great library - the `DataGrid` component is a bliss to work with. On the same note, I stumbled upon an improvement idea in regards to cursor-based pagination.

At the moment, the `DataGrid` API mainly caters to page-based pagination using page numbers. For this a consumer of the component would use the `onPageChange` handler to re-fetch data from the API using the new page number the user navigated to. While this works for page-based pagination, it's less ideal for cursor-based pagination as we don't know (without additional checks) whether the user has navigate forward or backward in the `DataGrid` `onPageChange` handler.

**Hence, I propose that we create two additional event handlers:**
- `onNextPageChange` - called when a user navigates to the next page
- `onPreviousPageChange` - called when a user navigates to the previous page

#### Before

```tsx
  const [currentPageIndex, setCurrentPageIndex] = useState(0)
  const { data, fetchNextPage, fetchPreviousPage } = useSomeData(pageSize) // fetching data using react-query

  const handlePageChange = (params: GridPageChangeParams) => {
    // If we navigate FORWARD in our pages, i.e. the new page number is higher than current page
    if (params.page > currentPageIndex) {
      fetchNextPage()
    }
    // If we navigate BACKWARD in our pages, i.e. the new page number is lower than current page
    else {
      fetchPreviousPage()
    }
    setCurrentPageIndex(params.page)
  }

  const rows = data?.pages[currentPageIndex]?.edges?.map(({ node }) => node)

  return (
    <Page>
      {rows && rows.length > 0 ? (
        <Card>
          <DataGrid
            autoHeight
            pagination
            pageSize={10}
            page={currentPageIndex}
            rowCount={data?.pages[currentPageIndex]?.totalCount}
            paginationMode="server"
            rowsPerPageOptions={[10, 20, 50]}
            onPageChange={handlePageChange}
            rows={rows}
            columns={columns}
          />
        </Card>
      ) : null}
    </Page>
  )
```

#### After

```tsx
  const [currentPageIndex, setCurrentPageIndex] = useState(0)
  const { data, fetchNextPage, fetchPreviousPage } = useSomeData(pageSize) // fetching data using react-query

  const rows = data?.pages[currentPageIndex]?.edges?.map(({ node }) => node)

  return (
    <Page>
      {rows && rows.length > 0 ? (
        <Card>
          <DataGrid
            autoHeight
            pagination
            pageSize={10}
            page={currentPageIndex}
            rowCount={data?.pages[currentPageIndex]?.totalCount}
            paginationMode="server"
            rowsPerPageOptions={[10, 20, 50]}
            onPageChange={(param: GridPageChangeParams) => setCurrentPageIndex(params.page)}
            onNextPageChange={fetchNextPage}
            onPreviousPageChange={fetchPreviousPage}
            rows={rows}
            columns={columns}
          />
        </Card>
      ) : null}
    </Page>
  )
```

## Motivation 🔦

This addition would make it a bit easier to use the `DataGrid` component for cursor-based pagination.

**Comment by dtassone** [comment]
Well, in my experience, a server query just returns a set of rows, without caring about the previous state.
It should be agnostic of the direction, therefore I don't think your approach would make the experience easier for the wider community.

That being said, thanks a lot for sharing and taking the time to open the issue.

**Comment by tobiasbueschel** [comment]
No problem 🙏  Thanks for your swift reply!

For offset-based pagination what you refer to about "not caring about the previous state" is true. However, for cursor-based pagination, many APIs would typically return three things:

1. the data the client is asking for
2. the cursor for the next page
3. the cursor for the previous page

Here's a small article about it: https://medium.com/@ignaciochiazzo/paginating-requests-in-apis-d4883d4c1c4c

----

With that said, having an event handler that knows about whether the user is moving forward or backward in the `DataGrid` would make the API for cursor-based pagination usage simpler.

**Comment by oliviertassinari** [comment]
I agree with @tobiasbueschel, cursored pagination is not a niche use case. It's actually important with a large number of records, as well as UUID-based storage: https://graphql.org/learn/pagination/#pagination-and-edges.

<img width="696" alt="Capture d’écran 2021-06-16 à 00 27 31" src="https://user-images.githubusercontent.com/3165635/122131585-aadd0000-ce39-11eb-9205-511891e6df95.png">

I would propose we solve this problem the exact same way that we talk about solving #1803: adding a `reason` argument that further qualify the origin of the event.

**Comment by tobiasbueschel** [comment]
Thanks @oliviertassinari I think your suggestion with the `reason` property could work well.

However, if someone has a dashboard with many `DataGrid` components, they would need to wrap the component so to not duplicate the `handlePageChange` functions everywhere, e.g.,

```js
// ...

const handlePageChange = (params: GridPageChangeParams) => {
  if (params.reason === 'nextPage') {
    props.handleNextPage()
  } else if (params.reason === 'previousPage') {
    props.handlePreviousPage()
  }
}
```

That's perfectly fine as in this way consumers of the component can customize according to their needs. However, I also like the idea of supporting cursor based pagination out of the box, so that one doesn't need to wrap the component and can just do:  
  
  ```jsx
<DataGrid
    pagination
    pageSize={pageSize}
    page={currentPageIndex}
    rowCount={data.pages[currentPageIndex]?.totalCount} // the GraphQL query returns the total amount of records, which is helpful for the DataGrid to know the max amount of pages
    paginationMode="server"
    onPageSizeChange={handlePageSizeChange}
    onNextPageChange={fetchNextPage}
    onPreviousPageChange={fetchPreviousPage}
    rows={rows}
    columns={columns}
/>
```

Would be happy to raise a PR for either implementation, but might need some guidance as I'm not yet familiar with the codebase :) 

Happy Friday!

**Comment by oliviertassinari** [comment]
@tobiasbueschel Thanks for the suggestion, but no, it won't happen.

**Comment by tobiasbueschel** [comment]
> @tobiasbueschel Thanks for the suggestion, but no, it won't happen.

No worries, thanks! Then for our use case we would wrap it as have a 10+ DataGrids all using cursor-based pagination :)

**Comment by dtassone** [comment]
let's do a section in the pagination page doc to explain how you could achieve this fetch next/previous page by comparing the page with the current page state using onPageChange
