### ISSUE TITLE
[DataGrid] rowsPerPage selection dropdown is not shown

### ISSUE THREAD

**Issue by tobiasbueschel** [mui-org/material-ui-x#1907]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When rendering a `DataGrid` component, the rows per page dropdown selection is not shown.

```jsx
      <DataGrid
        pageSize={pageSize}
        onPageSizeChange={handlePageSizeChange}
        rowsPerPageOptions={[5, 10, 20]}
        pagination
        {...data}
      />
```

This also happens when I look at the Code Sandbox of the official MUI example shown here:

- https://material-ui.com/components/data-grid/pagination/#page-size
- https://codesandbox.io/s/o1iep?file=/demo.tsx

![image](https://user-images.githubusercontent.com/13087421/121983511-040a4c80-cdc4-11eb-80cd-11794265d909.png)

## Expected Behavior 🤔

![image](https://user-images.githubusercontent.com/13087421/121983561-1b493a00-cdc4-11eb-9719-ef8b6337ac9e.png)

## Steps to Reproduce 🕹

https://codesandbox.io/s/o1iep?file=/demo.tsx

## Context 🔦

It doesn't allow us to dynamically change the page size.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  System:
    OS: macOS 11.4
  Binaries:
    Node: 16.2.0 - ~/.nvm/versions/node/v16.2.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.14.0 - ~/Development/project/node_modules/.bin/npm
  Browsers:
    Chrome: 91.0.4472.101
    Edge: Not Found
    Firefox: Not Found
    Safari: 14.1.1
  npmPackages:
    @material-ui/core: ~4.11.4 => 4.11.4
    @material-ui/data-grid: ~4.0.0-alpha.30 => 4.0.0-alpha.31
    @material-ui/icons: ~4.11.2 => 4.11.2
    @material-ui/lab: ~4.0.0-alpha.58 => 4.0.0-alpha.58
    @material-ui/pickers: ~3.3.10 => 3.3.10
    @material-ui/styles:  4.11.4
    @material-ui/system:  4.11.3
    @material-ui/types:  5.1.0
    @material-ui/utils:  4.11.2
    @types/react: ^17.0.0 => 17.0.5
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    styled-components: ~5.3.0 => 5.3.0
    typescript: ~4.2.4 => 4.2.4
```
</details>

**Comment by m4theushw** [comment]
By default, the dropdown is only visible if the current breakpoint is `md` (960px) or higher. You can remove this custom styling using the `componentsProps`. The downside is that in smaller resolutions a scrollbar may appear.

```jsx
<DataGrid
  // ...
  componentsProps={{
    pagination: { classes: null }
  }}
/>
```

**Comment by oliviertassinari** [comment]
This looks close to #847. Maybe we should encourage CSS customizations in this context?

**Comment by dtassone** [comment]
We could also think of a new UX for smaller screens, for example, displaying an icon that allows to open a small panel where you configure the pagination maybe even the density 🤔

**Comment by oliviertassinari** [comment]
To unlock @tobiasbueschel https://codesandbox.io/s/material-demo-forked-wvp96?file=/demo.tsx

```jsx
const useStyles = makeStyles((theme) => ({
  root: {
    "& .MuiTablePagination-caption[id]": {
      [theme.breakpoints.up("sm")]: {
        display: "block"
      }
    },
    "& .MuiTablePagination-input": {
      [theme.breakpoints.up("sm")]: {
        display: "block"
      }
    }
  }
}));
```

Based on https://github.com/mui-org/material-ui-x/issues/1907#issuecomment-861888562. The case where is not flying is with our documentation because the TOCs stay in on sm with size. 

I would propose the following: 

- We make the hypothesis that most developers will display the data grid full-width on smaller screen width. This mean. that we move forward with the diff of https://github.com/mui-org/material-ui-x/issues/1907#issuecomment-861888562. 
- Once this has enough adoption: https://caniuse.com/css-container-queries, we use it.

**Comment by tobiasbueschel** [comment]
Thanks everyone for your swift reply and feedback! I quite like @dtassone's idea - in this way the data grid toolbar / pagination icons would be accessible on small screens and users can use horizontal scrolling to go through the rest of the table.

> We make the hypothesis that most developers will display the data grid full-width on smaller screen width (our docs don't). This mean. that we move forward with the diff of #1907 (comment).

👍  that sounds good as well @oliviertassinari - I've been waiting for container queries for a while, but I suppose it will still take a bit until we get wider adoption.

---

With that said, I just realized that the reason why the "Rows per page" selector didn't show up for me wasn't due to a small viewport, but instead due to a mismatch between `pageSize` and `rowsPerPageOptions`.

I've had the following in my local setup:

```tsx
const [pageSize, setPageSize] = React.useState<number>(5);
  
// ... other code omitted for brevity
  
return (
    <DataGrid
      pageSize={pageSize}
      onPageSizeChange={handlePageSizeChange}
      rowsPerPageOptions={[10, 20, 50]}
      pagination
      {...data}
    />
```
https://codesandbox.io/s/material-demo-forked-82by7?file=/demo.tsx

Due to the `pageSize` of 5 not matching the `rowsPerPageOptions` allowed values, the entire selector hides itself. Would you mind if I raise a PR to add this into the documentation in this way other developers are aware?

Alternatively, we could also consider (1) logging a warning in development or (2) showing the "Rows per page" regardless of a non-matching `pageSize`.

What do you think?

**Comment by oliviertassinari** [comment]
> (1) logging a warning in development

@tobiasbueschel It should already be present: see. The data grid shouldn't be swallowing it 💥. https://codesandbox.io/s/enhancedtable-material-demo-forked-xhhgt?file=/demo.tsx

**Comment by m4theushw** [comment]
Yeah, it should warn, but since we're doing our own validation, when an invalid `pageSize` is passed it changes `rowsPerPageOptions` to an empty array. I think that letting `TablePagination` to handle this is enough.

```diff
diff --git a/packages/grid/_modules_/grid/components/GridPagination.tsx b/packages/grid/_modules_/grid/components/GridPagination.tsx
index fa633562..726809e3 100644
--- a/packages/grid/_modules_/grid/components/GridPagination.tsx
+++ b/packages/grid/_modules_/grid/components/GridPagination.tsx
@@ -90,12 +90,7 @@ export const GridPagination = React.forwardRef<
       component="div"
       count={paginationState.rowCount}
       page={paginationState.page <= lastPage ? paginationState.page : lastPage}
-      rowsPerPageOptions={
-        options.rowsPerPageOptions &&
-        options.rowsPerPageOptions.indexOf(paginationState.pageSize) > -1
-          ? options.rowsPerPageOptions
-          : []
-      }
+      rowsPerPageOptions={options.rowsPerPageOptions}
       rowsPerPage={paginationState.pageSize}
       {...getPaginationChangeHandlers()}
       {...props}
```

**Comment by dtassone** [comment]
> Due to the pageSize of 5 not matching the rowsPerPageOptions allowed values, the entire selector hides itself. 

How about we add the missing value instead of changing it to an empty array?
In that case it becomes

```tsx
 pageSize={5}
 rowsPerPageOptions={[5, 10, 20, 50]}
```

**Comment by flaviendelangle** [comment]
I think we could split this issue into 2:

- Improve the UI do display the row per page informations even on smaller screen (see https://github.com/mui-org/material-ui-x/issues/1907#issuecomment-862420137 and  https://github.com/mui-org/material-ui-x/issues/1907#issuecomment-862282176)
- Automatically add the `pageSize` to the rowsPerPageOptions` if it is not in it (see https://github.com/mui-org/material-ui-x/issues/1907#issuecomment-863946716)

**Comment by oliviertassinari** [comment]
While @flaviendelangle is focusing on fixing the missing prop warning, I think that we could have the community to contribute on: https://github.com/mui-org/material-ui-x/issues/1907#issuecomment-861888562. I'm adding the "good to take" label for this specific CSS change.

**Comment by oliviertassinari** [comment]
I'm reopening as the solution is not whole. https://material-ui.com/components/tables/#data-table warns https://codesandbox.io/s/ts0cl

<img width="515" alt="Screenshot 2021-09-05 at 14 48 37" src="https://user-images.githubusercontent.com/3165635/132127387-aa322b3d-fc62-4e27-a440-0f5c359d2053.png">

**Comment by harshkRana7017** [comment]
initial value of the page size must be in the rowsPerPageOptions array elements. This will easily resolve the issue.

**Comment by Umair123-dot** [comment]
but my row perpageOption not shown how can I resolve this?
import React, { useState } from "react";
import { Box, Typography } from "@mui/material";
import { useProducts } from "../../config/query/usePaginatedQuery";
import { DataGrid } from "@mui/x-data-grid";
import { makeStyles } from "@mui/styles";
import MuiPagination from "@mui/material/Pagination";

const columns = [
  {
    field: "createdAt",
    headerName: "Created At",
    width: 200,
    editable: true,
  },

  {
    field: "name",
    headerName: "Name",
    width: 200,
    editable: true,
  },
  {
    field: "description",
    headerName: "Description",

    width: 400,
    editable: true,
  },
  {
    field: "pricePerUnit",
    headerName: "Price Unit",
    width: 400,
  },
  {
    field: "sold",
    headerName: "Sold",
    width: 400,
  },
  {
    field: "store",
    headerName: "Store",
    width: 400,
  },
  {
    field: "updatedAt",
    headerName: "Updated At",
    width: 400,
  },

  // {
  //   field: "_id",
  //   headerName: "Id",
  //   width: 200,
  //   editable: true,
  // },
];
const useStyles = makeStyles((theme) => ({
  root: {
    "& .MuiTablePagination-caption[id]": {
      [theme.breakpoints.up("sm")]: {
        display: "block",
      },
    },
    "& .MuiTablePagination-input": {
      [theme.breakpoints.up("sm")]: {
        display: "block",
      },
    },
  },
}));

const Profile = () => {
  const [rowsPerPage, setRowsPerPage] = React.useState(3);

  const [paginationModel, setPaginationModel] = React.useState({
    pageSize: rowsPerPage,
    page: 0,
  });
  const { data, isLoading, hasNextPage, isFetchingNextPage } = useProducts({
    limit: paginationModel?.pageSize,
    page: paginationModel?.page + 1,
  });
  const handleChangeRowsPerPage = (event) => {
    setRowsPerPage(parseInt(event.target.value, 3));
    setPage(0);
  };
  console.log(data, "new------------------------------------");

  const classes = useStyles();
  return (
    <Box sx={{ height: "300px", width: "100%" }}>
      <DataGrid
        className={classes.root}
        rows={data?.docs.map((row) => ({ ...row, id: row._id })) || []}
        columns={columns}
        loading={isLoading}
        onPageSizeChange={handleChangeRowsPerPage}
        rowsPerPageOptions={[3, 6, 9]}
        paginationModel={paginationModel}
        onPaginationModelChange={setPaginationModel}
        rowCount={data?.totalDocs}
        paginationMode="server"
      />
    </Box>
  );
};

export default Profile;

![image](https://github.com/mui/mui-x/assets/61285685/7c378952-8dd5-4a8a-8dfd-3a620183e6dc)

**Comment by danielR2001** [comment]
@Umair123-dot did you manage to resolve the issue?
