### ISSUE TITLE
[DataGrid] How to set a style base on the value of the cell (e.g. the value of the cell is the background color)

### ISSUE THREAD

**Issue by david-iccube** [mui-org/material-ui-x#1912]
Currently we can define in GridColDef with renderCell and cellClassName properties a cell renderer and classNames that are different for each row.  How could we do this with styles ? (e.g. background color)

Ideally we would have cellSX function (like the new material-ui SX property in v5).

I've been asking and trying different workarounds and ask in stackoverflow without a clean solution for the time being. 

https://stackoverflow.com/questions/67647522/material-ui-table-xgrid-how-to-set-a-different-color-for-each-cell
https://stackoverflow.com/questions/67997848/emotion-serializedstyles-not-in-dom-style

**Comment by oliviertassinari** [comment]
@david-iccube It seems that the simplest in your case would be to use `renderCell` to apply inline style or a `styled()` component.

**Comment by david-iccube** [comment]
@oliviertassinari , but the background will have the cell padding that is defined by the parent's div 

https://codesandbox.io/s/material-demo-forked-1h2hs

A workaround we use is to add a div with absolute position with the background, but we have to add relative positioning to the cell parent as well, it's a bit of a hack.

Is there any reason why you don't want to add a sx props at cell level ?

**Comment by oliviertassinari** [comment]
@david-iccube Thanks for the extra context. I can list the options I can think of:

1. We expose the whole cell in the `renderCell` API. It's what [react-virtualized](https://github.com/bvaughn/react-virtualized/blob/abe0530a512639c042e74009fbf647abdb52d661/source/List/List.example.js#L200-L212) is doing. We have also started to do it in the Autocomplete for the options: https://github.com/mui-org/material-ui/pull/22591
2. You customize the CSS of the demo to have a child of the root's cell to add the padding.
3. We add a `getCellStyle` with the same behavior as `getCellClassName` but to add inline style.

Do we have more options?

**Comment by david-iccube** [comment]
Eventually we decided using emotion/css to convert css to classNames 

       colDef.cellClassName = (cell: GridCellParams) => {
                const style = myFunctionThatReturnsCss(colIdx,rowIdx);
                 if (style) {
                      const className = css(style);
                      return className;
                   } else {
                     return "";
                 }
          }

**Comment by gnowland** [comment]
I also have need for this use case, adding a style property or data- property that is generated on-the-fly for cell background (rgba alpha value calculated from cell value). I will implement with absolutely-positioned background for now but that seems unnecessarily hacky if `getCellStyle` or were to be implemented.

**Comment by m4theushw** [comment]
@gnowland For your use case, #2138 seems to be a better solution, since you want to pass custom attributes. You can subscribe to it to know when it gets implemented.

**Comment by oliviertassinari** [comment]
Closing for https://github.com/mui-org/material-ui-x/issues/2138#issuecomment-887365483, a more generic solution.
