### ISSUE TITLE
[DataGrid] Entering value manually in a date field is not working

### ISSUE THREAD

**Issue by davidalmas** [mui-org/material-ui-x#1920]
- [x ] The issue is present in the latest release.
- [x ] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Hi, 

When I try to enter a date (eg 15/06/2021) I get an error typing the year field, it's like 1901. However, if I choose the date from the native date picker, the problem doesn't reproduce itself.

## Expected Behavior 🤔

When i type 2021 the year must be correct.

## Steps to Reproduce 🕹

You can see these materials-ui url that the error persists.

https://material-ui.com/components/data-grid/editing/

**Comment by m4theushw** [comment]
It's not working because when, for example, "2" is typed into the year it creates a `Date` in 1902. I think we should only publish `GRID_CELL_EDIT_PROPS_CHANGE` when the date is "complete" (has at least 3-digit for year) and valid. Also, we could leverage `valueParser` to do the parsing: https://github.com/mui-org/material-ui-x/pull/1785#discussion_r642119534.

**Comment by oliviertassinari** [comment]
What about https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#two_digit_years_map_to_1900_%E2%80%93_1999?

**Comment by hetanthakkar1** [comment]
@oliviertassinari I am on it!

**Comment by dtassone** [comment]
ATM, we have a simple component for editing every type of column `GridEditInputCell`. I think dates can have their own component now to manage how to handle change and other behavior specific to the `date` column type. 
Then, to render the new `GridEditDateCell`, use the `renderEditCell` prop of the native date column definition `GRID_DATE_COL_DEF`.

**Comment by Freundschaft** [comment]
has this actually been fixed? I still see the issue on the newest version
