### ISSUE TITLE
[DataGrid] Toolbar Export delimiter is not documented

### ISSUE THREAD

**Issue by IoannRove** [mui-org/material-ui-x#1924]
Hi! I 'am using Material UI DataGrid Grid Toolbar Export to export data to csv. Can i change delimiter and encoding?

Thank you!

**Comment by oliviertassinari** [comment]
@IoannRove See #1859. It looks like we need to:

1. Fix #1211 for the `GridToolbarExport` component
2. Fix #1826 for the 3. ii. we have no information on what

<img width="871" alt="Capture d’écran 2021-06-18 à 13 39 53" src="https://user-images.githubusercontent.com/3165635/122555528-b3505900-d03a-11eb-8cf3-7df0324b8f31.png">

supports
