### ISSUE TITLE
[DataGrid] `onPageSizeChange` should fire when `autoPageSize` is set and the grid size changes.

### ISSUE THREAD

**Issue by toburger** [mui-org/material-ui-x#1926]
When I combine controlled pagination with the auto page size feature I expect the `onPageSizeChange` event to trigger, when the grid's height changes (and therefore the page size updates).

- [X] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Nothing happens, the page size doesn't get updated and the pagination gets disarranged.

## Expected Behavior 🤔

`onPageSizeChange` should fire.

## Steps to Reproduce 🕹

https://codesandbox.io/s/material-demo-forked-xerxh?file=/demo.js

```jsx
    <DataGrid
      pagination
      autoPageSize
      page={page}
      pageSize={pageSize}
      rowCount={rowCount}
      paginationMode="server"
      onPageChange={(params) => setPage(params.page)}
      onPageSizeChange={(params) => setPageSize(params.pageSize)}
      columns={columns}
      rows={rows}
      loading={loading}
    />
```

## Context 🔦

Combining auto page size and controlled paging.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 14.17.0 - ~\scoop\apps\nodejs-lts\current\node.EXE
    Yarn: 1.22.5 - ~\scoop\apps\yarn\current\Yarn\bin\yarn.CMD
    npm: 6.14.8 - ~\scoop\apps\nodejs-lts\current\bin\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.48)
```
</details>

**Comment by oliviertassinari** [comment]
Ok, so I had a quick look at the issue and updated the issue to include a codesandobx. I could make it work with:

```diff
diff --git a/packages/grid/_modules_/grid/hooks/features/core/gridState.ts b/packages/grid/_modules_/grid/hooks/features/core/gridState.ts
index 4bb5d512..3921cc3c 100644
--- a/packages/grid/_modules_/grid/hooks/features/core/gridState.ts
+++ b/packages/grid/_modules_/grid/hooks/features/core/gridState.ts
@@ -63,7 +63,7 @@ export const getInitialGridState: () => GridState = () => ({
   pagination: {
     page: 0,
     pageCount: 0,
-    pageSize: 0,
+    pageSize: 100,
     paginationMode: 'client',
     rowCount: 0,
   },
diff --git a/packages/grid/_modules_/grid/hooks/features/pagination/useGridPagination.ts b/packages/grid/_modules_/grid/hooks/features/pagination/use
GridPagination.ts
index 3c7c2b77..cee8c9c9 100644
--- a/packages/grid/_modules_/grid/hooks/features/pagination/useGridPagination.ts
+++ b/packages/grid/_modules_/grid/hooks/features/pagination/useGridPagination.ts
@@ -92,6 +92,22 @@ export const useGridPagination = (apiRef: GridApiRef): void => {
   useGridApiOptionHandler(apiRef, GRID_PAGE_SIZE_CHANGE, options.onPageSizeChange);

   React.useEffect(() => {
+    const autoPageSize = containerSizes?.viewportPageSize;
+    const prevPageSize = apiRef.current.getState().pagination.pageSize;
+    let pageSize;
+
+    if (options.pageSize !== undefined) {
+      pageSize = options.pageSize;
+    } else {
+      pageSize = options.autoPageSize ? autoPageSize : prevPageSize;
+    }
+
+    if (prevPageSize !== pageSize && options.autoPageSize) {
+      apiRef.current.publishEvent(GRID_PAGE_SIZE_CHANGE, {
+        pageSize: autoPageSize,
+      });
+    }
+
     setGridState((state) => ({
       ...state,
       pagination: applyConstraints(
@@ -102,15 +118,14 @@ export const useGridPagination = (apiRef: GridApiRef): void => {
               ? options.paginationMode
               : state.pagination.paginationMode,
           rowCount: options.rowCount !== undefined ? options.rowCount : visibleRowCount,
-          pageSize:
-            (options.autoPageSize ? containerSizes?.viewportPageSize : options.pageSize) ||
-            state.pagination.pageSize,
+          pageSize,
         },
         options.page,
       ),
     }));
     forceUpdate();
   }, [
+    apiRef,
     setGridState,
     forceUpdate,
     options.paginationMode,
diff --git a/packages/grid/_modules_/grid/models/gridOptions.tsx b/packages/grid/_modules_/grid/models/gridOptions.tsx
index 17d7161f..eac9383c 100644
--- a/packages/grid/_modules_/grid/models/gridOptions.tsx
+++ b/packages/grid/_modules_/grid/models/gridOptions.tsx
@@ -522,7 +522,6 @@ export const DEFAULT_GRID_OPTIONS: GridOptions = {
   headerHeight: 56,
   infniteLoadingMode: GridFeatureModeConstant.client,
   localeText: GRID_DEFAULT_LOCALE_TEXT,
-  pageSize: 100,
   paginationMode: GridFeatureModeConstant.client,
   rowHeight: 52,
   rowsPerPageOptions: [25, 50, 100],
```

Comments:

- I have removed the default value of `pageSize`, this prop can be controlled, a default value doesn't make any sense, it would mean it's always controlled
- Always firing a `GRID_PAGE_SIZE_CHANGE` event feels strange. We have to be careful, as it doesn't mean that the size changed, but instead that an attempt was made. When pageSize is controlled, it could very well do nothing.
- On top of fixing the callback, I also had a quick look at the controlled behavior. It was wrong, `options.pageSize` should always win.

@toburger Feel free to work on a pull request :). We will need a test case, important.

**Comment by toburger** [comment]
Thanks for the codesandbox and the potential fix!

I was mixing up page/window 'size' and 'height'... Sorry for the confusion.
The correct title should be:

> `onPageSizeChange` should fire when `autoPageSize` is set and the surrounding container/window height changes.

To clarify my use case: I am using the grid in a PWA that uses the rest of the page height for the grid.

Therefore the window height (and the page size) could change:
* on desktop by resizing the window
* on mobile by rotating the device

The `pageSize` could still be needed when `autoPageSize` is not set or if `autoPageSize` is also a controlled property and changed dynamically.

**Comment by flaviendelangle** [comment]
@oliviertassinari 

In your code above, you have a small behavior change
Right now, when we have `options.autoPageSize === true`, `containerSizes?.viewportPageSize` have the priority against `options.pageSize`. 

```ts
pageSize:
  (options.autoPageSize ? containerSizes?.viewportPageSize : options.pageSize) ||
  state.pagination.pageSize,
```

But in your code the priority has switched between the two

```ts
let pageSize;

if (options.pageSize !== undefined) {
  pageSize = options.pageSize;
} else {
  pageSize = options.autoPageSize ? autoPageSize : prevPageSize;
}
```

Is it intended ?
