### ISSUE TITLE
[DataGridPro] Implement Column pinning

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#193]
### Benchmark

- https://ant.design/components/table/#components-table-demo-fixed-columns
- https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/fixed-columns/
- https://ag-grid.com/javascript-grid-pinning/
- https://www.telerik.com/kendo-react-ui/components/grid/columns/locked/
- https://demos.telerik.com/kendo-ui/grid/frozen-columns
- http://schrodinger.github.io/fixed-data-table-2/fixed-right-columns.html
- https://ej2.syncfusion.com/react/demos/#/material/grid/frozen-rows
- http://tabulator.info/docs/4.5/layout#frozen
- https://www.jqwidgets.com/react/react-grid/#https://www.jqwidgets.com/react/react-grid/react-grid-pinnedfrozencolumns.htm
- https://material-table.com/#/docs/features/fixed-columns, the issue: https://github.com/mbrn/material-table/issues/43

**Comment by oliviertassinari** [comment]
We need to find a final name for the feature. There are a bunch of options: Sticky, Frozen, Locked, or Pinned. We are leaning to Pinning.

**Comment by caitecoll** [comment]
@oliviertassinari This is cool. Two questions:

1. Is the idea that it would be a user triggered feature (user can pin interesting columns), a developer-configured feature or some combination of both?
2. Are you planning to incorporate the ability to pin columns to the right (e.g.- AntD's `fixed="right"`)?

If there's some other place I could have found this info myself, please let me know. This feature would definitely be useful for us.

**Comment by oliviertassinari** [comment]
@caitecoll 1. Which one do you need? We will start with a developer-configuration as it's simpler.
2. I think that left and right pinning should be supported.

**Comment by caitecoll** [comment]
Thanks, that sounds great. Developer configuration and right pinning are the two things we need.

**Comment by simoami** [comment]
@oliviertassinari Great feature. I've implemented a similar feature in a private grid. The challenge was to ensure keyboard navigation flows naturally when a column is moved out of order to either left or right region. The other challenge is depending on how the underlying html is rendered you may or may not have the ability to support rows with variable heights (`height="auto"`) 

Another improvement is to show soft shadow dynamically on either of the pinned columns depending on the horizontal scroll position.

**Comment by ak-mid** [comment]
For our use case it's critical that we can pin the checkbox which currently is implemented as a pseudo-column via the `checkboxSelection` prop. Do you plan to add another prop like `pinnedCheckbox`?

**Comment by oliviertassinari** [comment]
@ak-mid Do you have a visual illustration of what you mean by "pinning the checkbox"?

**Comment by ak-mid** [comment]
@oliviertassinari Sorry, I have no visual illustration at hand right now :(
The use case is that the checkbox on the left to select a row is still available (pinned, sticky) if a user scrolls horizontally inside of the grid. It's actually like pinning the first row of the grid which includes a checkbox.

**Comment by abrookie** [comment]
We really need this "Sticky" column functionality for our application.  Do we have an idea of when this will be available?

**Comment by younusway2b1** [comment]
Is this something that will prevent the checkbox from being draggable? In DataGrid it seems to be stuck in position, but in XGrid the checkbox column can be dragged and moved around. You can see it here:

https://codesandbox.io/s/gttt1?file=/demo.tsx

The checkbox column is draggable ^

**Comment by oliviertassinari** [comment]
@y2b1 What's your expected outcome? (It makes me think about #1672).

**Comment by tylerlinquata** [comment]
@oliviertassinari Is this available to work on?  It seems like the most common requests are: 

- pinning columns to the left and right
- being able to pin the checkbox "column"
- doing this from the developer side only for now

I'm being pestered about this feature and would love to contribute if possible.

**Comment by oliviertassinari** [comment]
@tylerlinquata Note that we intend to license the feature as part of the [Pro plan](https://material-ui.com/components/data-grid/getting-started/#feature-comparison). If this is not a showstopper and you are willing to sign a Copyright Assignment Agreement then we could continue the discussion further :).

**Comment by tylerlinquata** [comment]
@oliviertassinari I'm talking to my company about it, I'll update if they'd be willing to sign an agreement.

**Comment by Neonin** [comment]
Is it possible to release it a little faster - the ability to make a pin not programmatically, but only with a fix with an indication in props. example: fixedColumn
Unfortunately, due to virtualization, I could not do it with styles.

![Group 18](https://user-images.githubusercontent.com/16340041/123126396-0585e580-d452-11eb-9d47-c5f0f65da267.png)

**Comment by rlmonger** [comment]
Has anyone taken this feature up to complete?

**Comment by enlicayomer** [comment]
any progress ?

**Comment by jessq** [comment]
This was on the Q3 2021 Jul - Sep roadmap. Any updates on timeline?

**Comment by crow7m** [comment]
Hi all, thank you for cool library, small question, will the sticky(pin) column functionality be available as announced in Q4  ? 
Thank you

**Comment by flaviendelangle** [comment]
If no unexpected problem it should yes

The first working implementation (#2946) in advancing fine.

**Comment by crow7m** [comment]
> If no unexpected problem it should yes
> 
> The first working implementation (#2946) in advancing fine.

Thank you for quick reply.  
👍
