### ISSUE TITLE
[DataGrid] Implement Column reorder

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#194]
### Docs placeholder

- https://material-ui.com/components/data-grid/columns/#column-reorder

### Benchmark

- https://ag-grid.com/javascript-grid-column-moving/
- https://www.telerik.com/kendo-react-ui/components/grid/columns/reordering/
- https://demos.telerik.com/kendo-ui/grid/column-reordering
- https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/column-reordering/
- http://schrodinger.github.io/fixed-data-table-2/example-reorder.html
- https://ej2.syncfusion.com/react/demos/#/material/grid/reorder
- http://tabulator.info/docs/4.5/move
- https://www.jqwidgets.com/react/react-grid/#https://www.jqwidgets.com/react/react-grid/react-grid-columnsreorder.htm
- https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/LocalReordering/React/Light/
- https://adazzle.github.io/react-data-grid/docs/examples/reordering-columns

**Comment by PeppermintNDaisies** [comment]
Hello! Whe will this feature be available for X-Grid component?

**Comment by oliviertassinari** [comment]
@PeppermintNDaisies It's already released under https://github.com/mui-org/material-ui-x/releases/tag/v4.0.0-alpha.7.

**Comment by PeppermintNDaisies** [comment]
@oliviertassinari amazing! How can I use it? I'm currently working with the docs, but it still appears as under construction

**Comment by oliviertassinari** [comment]
Oh right, my bad, I have messed up. I'm fixing it.

**Comment by oliviertassinari** [comment]
We are currently facing some [caching issues](https://community.netlify.com/t/one-deployed-to-main-domain-random-assets-404/24519/) with Netlify. For now, you can use https://material-ui-x.netlify.app/components/data-grid/columns/#column-reorder.

**Comment by PeppermintNDaisies** [comment]
Great!! Thanks a lot!

**Comment by cq-ubaid-khan** [comment]
Hello, can't we give the column reorder values as a prop? like we have option to give `columnVisibilityModel`?
