### ISSUE TITLE
GridToolbarFilterButton filter count editable?

### ISSUE THREAD

**Issue by davidroman-hub** [mui-org/material-ui-x#1951]
Hello good day, i wanted to ask if is possible to manage the counter inside the component GridToolbarButton. the thing is im using XGrid on sever mode to fetch some data, but at the moment when i put my filters , the counters does their job i mean in the icon appears how many filters are applied, but if for any reason i refresh the page, the counters gone but the filters are in the state is just the Component is not holding the state... so i would like to handle this counter by my side. normally the numbers of filters are on my state  ``[].length``, and it will be super easy for me pass this params to the GridToolbarButton. 

someone have any idea if this is possible? or how i should handle this counter?

**Comment by dtassone** [comment]
> but if for any reason i refresh the page, the counters gone but the filters are in the state is just the Component is not holding the state... 

That sounds like an issue. Could you please provide a codesandbox, so we can really understand what you mean and look into it.

**Comment by oliviertassinari** [comment]
@davidroman-hub Here is [a **codesandbox.io** template](https://material-ui.com/r/issue-template) to help you get started.

**Comment by davidroman-hub** [comment]
@oliviertassinari  Thanks!, i will write my code in few hours, thanks for the support.

**Comment by davidroman-hub** [comment]
https://codesandbox.io/embed/material-demo-forked-xzepj?fontsize=14&hidenavigation=1&theme=dark

**Comment by davidroman-hub** [comment]
ahh mince! i think i delete my code, but basically what i want is when the user apply filters & refresh the page don't lose the state of counter , normally i use Redux for this behaviour , i think i did something bad on my code sandbox, sorry i write super fast, maybe is not the best.

**Comment by davidroman-hub** [comment]
@oliviertassinari  i found the problem and the think is i don't know how to put in the right way the filter model! maybe you can help me with this part

**Comment by oliviertassinari** [comment]
I'm closing as we don't have enough information to reproduce the issue. If you have a minimal reproduction, feel free to post it here.
