### ISSUE TITLE
[XGrid] After updating row props with an array where item was deleted, data grid stops working

### ISSUE THREAD

**Issue by vitalist82** [mui-org/material-ui-x#1958]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

After deleting row from the data source and providing it to XGrid via prop `rows` XGrid stops working correctly.

(The workaround with unmounting the grid after the data source changes and re-create it with the updated rows is unfortunately not acceptable solution since it causes unwanted flickering.)

## Expected Behavior 🤔

XGrid works correctly after changing the rows array without the need to unmount and mount the whole grid again.

## Steps to Reproduce 🕹

Example usage is on https://codesandbox.io/s/delicate-snowflake-1llbd.

Steps:

1. click the menu button in the last column of the table on any row
2. click 'Remove'
3. the row is deleted from the data source and it also disappears from the grid
4. click the menu button in the last column of the table on any row (or perform any other action on the grid like selecting a row)
5. exception is thrown

![image](https://user-images.githubusercontent.com/21025044/123267308-26574500-d4fd-11eb-8864-ff308da630f8.png)

## Context 🔦

I would like to use the grid in a way that it dynamically renders the rows passed in props even after changes to the array (deleting, adding...). If there is any way that doesn't include complete removal of the grid component from the DOM and its re-creation, I would appreciate it.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
Chrome browser was used.

 System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.3.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 91.0.4472.114
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.48)
  npmPackages:
    @emotion/styled:  10.0.27
    @material-ui/core: ^4.11.4 => 4.11.4
    @material-ui/icons: ^4.11.2 => 4.11.2
    @material-ui/styles:  4.11.4
    @material-ui/system:  4.11.3
    @material-ui/types:  5.1.0
    @material-ui/utils:  4.11.2
    @material-ui/x-grid: ^4.0.0-alpha.32 => 4.0.0-alpha.32
    @material-ui/x-license:  4.0.0-alpha.32
    @types/react: 17.0.3 => 17.0.3
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2
    styled-components: 5.2.1 => 5.2.1
    typescript: ~4.2.4 => 4.2.4
```
</details>

## Order id 💳

Will be provided once we will buy the license which we don't have yet.

**Comment by vitalist82** [comment]
@flaviendelangle with 4.0.0-alpha.33 the issue still occurs.

**Comment by flaviendelangle** [comment]
https://github.com/mui-org/material-ui-x/releases/tag/v4.0.0-alpha.33

The alpha 33 has been released 4 days before I merged this PR.
But it's indeed quite a long time between two releases.

**Comment by vitalist82** [comment]
Thanks for the information. I didn't check the dates...
