### ISSUE TITLE
[DataGrid] Implement CSV export

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#197]
We have started to work on the feature a year ago, the person that takes on this task can refer to https://github.com/mui-org/material-ui/pull/18872 and this code: [saveAs](https://github.com/mui-org/material-ui/pull/18872/files#diff-3c1e89673c8d2a5fb4a3da9c4867820f2f16fcfacdc8d08cdf55dc2c2f7bd01bR70).

### Research

UIs inspiration I could find:

1. **Google Ads**

<img width="257" alt="Capture d’écran 2021-02-11 à 18 47 10" src="https://user-images.githubusercontent.com/3165635/107676889-ebfdb180-6c99-11eb-81f2-fde532ecbc91.png">

The "More options" button opens a modal where you can select the format of the CSV file.

2. **Airtable**

<img width="267" alt="Capture d’écran 2021-02-11 à 18 48 01" src="https://user-images.githubusercontent.com/3165635/107676888-ebfdb180-6c99-11eb-95b6-594a906aa61f.png">

3. **Retool**
<img width="187" alt="Capture d’écran 2021-02-11 à 18 48 49" src="https://user-images.githubusercontent.com/3165635/107676885-eacc8480-6c99-11eb-8097-410230439b6e.png">

4. **Redash**
<img width="218" alt="Capture d’écran 2021-02-11 à 19 01 22" src="https://user-images.githubusercontent.com/3165635/107678359-94f8dc00-6c9b-11eb-8ac7-8559f6ee2a13.png">

5. **Stripe**
<img width="237" alt="Capture d’écran 2021-02-11 à 20 19 45" src="https://user-images.githubusercontent.com/3165635/107687250-8d8b0000-6ca6-11eb-9a1d-08fbafb2f7ea.png">

6. **https://try.firetable.io/table/mvpResources**

<img width="596" alt="Capture d’écran 2021-02-11 à 23 27 45" src="https://user-images.githubusercontent.com/3165635/107706529-c33ce280-6cc0-11eb-941c-9ff2d87e092d.png">

### Benchmark

- https://ag-grid.com/javascript-grid-export/#export
- https://material-table.com/#/docs/features/export
- https://www.zinggrid.com/docs/features/exporting-data
- http://tabulator.info/docs/4.7/download#csv
- https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/ExportToExcel/React/Light/
- https://www.jqwidgets.com/react/react-grid/#https://www.jqwidgets.com/react/react-grid/react-grid-dataexport.htm

**Comment by keremgocen** [comment]
What would be the recommended path for current material-ui consumer apps to design a CSV export feature? I'd like to be able to switch to material-ui table / datagrid once that's ready without doing the whole thing again if possible.

**Comment by oliviertassinari** [comment]
@keremgocen I think that you would depend on #190. We need to expose an API to integrate with the state of the data grid.

**Comment by AleKrabbe** [comment]
Hi, is there a date for this to be released? We are urgently needing to export our XGrid table into a CSV file. Thank you.

**Comment by oliviertassinari** [comment]
@AleKrabbe we aim to implement this feature Q1 2021. We mention it in the public roadmap: https://github.com/mui-org/material-ui-x/projects/1.

**Comment by DanailH** [comment]
Ok so I was thinking about how to handle the UX part and this is what I managed to come up with:

The main challenge is to make the UX in such a way that can handle also Excel export in the future if we choose to do it. I would propose to go in the direction of having a button per export option in the toolbar - my argument is that this way developers can opt-in on any option and this will also make the UI simpler since I can predict that we would need at least 2 options per export type (to export all or to export only selected rows).

Also, I propose we do a hook per export type because that way it will be easier to split them between the open-source and enterprise versions of the data grid.

On the props side, we would need a handler like `onCsvExport` for when developers would want to get the data. I don't think we would need a prop to enable or disable the feature since it will be opt-in (from the toolbar), the API will be available through the `apiRef`.

In terms of the API - most likely we would need 2 methods, one to get the data in a CSV format and one to download it.

**Comment by oliviertassinari** [comment]
- For the UX. Have you considered an hybrid approach? We could have a single component: `GridToolbarExport`. Depending on the features available, CSV, Excel, PDF, we would either display a single button or a menu. This would allow to have a denser UI and allowing end-users to prune the decision tree when navigating the interface. Basically, it would become a two steps process 1. Find the export location, 2. Pick the right format
- Regarding the code splitting. One hook/plugin per export type make sense.
- What's the use case for `onCsvExport`? I mean, what's the difference with the imperative apiRef method that returns the data in a string CSV format?

**Comment by DanailH** [comment]
> For the UX. Have you considered an hybrid approach? We could have a single component: GridToolbarExport. Depending on the features available, CSV, Excel, PDF, we would either display a single button or a menu. This would allow to have a denser UI and allowing end-users to prune the decision tree when navigating the interface. Basically, it would become a two steps process 1. Find the export location, 2. Pick the right format

First I thought of doing it like this, my argument against it is that if we want to have functionality like export all or to export only selected rows for example that would mean that we need a second level in the menu. I'm not saying it is bad but the downside is that it won't be the best experience on mobile, but if that is not a concern I prefer it that way.

> What's the use case for the onCsvExport prop? I mean, what's the difference with the imperative apiRef method that returns the data in a string CSV format?
Giving it more thoughts, it sounds like the prop will be available on the export toolbar button and allow to bypass the apiRef imperative methods. Why not.

Yes exactly - also this will allow for devs to be able to react to that action - maybe redirect or display something, etc. I can also delay adding it and see if there will be a demand for it.

**Comment by oliviertassinari** [comment]
OK, for the toolbar, we can go with a simple approach. If it doesn't work, we will hear about it.

**Comment by DanailH** [comment]
I made a draft, let's move the discussion regarding the UI there, it will be easier to follow it and address it.

**Comment by oliviertassinari** [comment]
UIs inspiration I could find:

1. **Google Ads**

<img width="257" alt="Capture d’écran 2021-02-11 à 18 47 10" src="https://user-images.githubusercontent.com/3165635/107676889-ebfdb180-6c99-11eb-81f2-fde532ecbc91.png">

The "More options" button opens a modal where you can select the format of the CSV file.

2. **Airtable**

<img width="267" alt="Capture d’écran 2021-02-11 à 18 48 01" src="https://user-images.githubusercontent.com/3165635/107676888-ebfdb180-6c99-11eb-95b6-594a906aa61f.png">

3. **Retool**
<img width="187" alt="Capture d’écran 2021-02-11 à 18 48 49" src="https://user-images.githubusercontent.com/3165635/107676885-eacc8480-6c99-11eb-8097-410230439b6e.png">

4. **Redash**
<img width="218" alt="Capture d’écran 2021-02-11 à 19 01 22" src="https://user-images.githubusercontent.com/3165635/107678359-94f8dc00-6c9b-11eb-8ac7-8559f6ee2a13.png">

**Comment by Daring-transfusion79** [comment]
> > For the UX. Have you considered an hybrid approach? We could have a single component: GridToolbarExport. Depending on the features available, CSV, Excel, PDF, we would either display a single button or a menu. This would allow to have a denser UI and allowing end-users to prune the decision tree when navigating the interface. Basically, it would become a two steps process 1. Find the export location, 2. Pick the right format
> 
> First I thought of doing it like this, my argument against it is that if we want to have functionality like export all or to export only selected rows for example that would mean that we need a second level in the menu. I'm not saying it is bad but the downside is that it won't be the best experience on mobile, but if that is not a concern I prefer it that way.
> 
> Another concern is that if someone wants to have PDF export but not CSV for example if they are in the same menu we would need to introduce a prop to disable each one of them. If we make them as separate buttons since they are all opt-in separately we will avoid that case.
> 
> > What's the use case for the onCsvExport prop? I mean, what's the difference with the imperative apiRef method that returns the data in a string CSV format?
> > Giving it more thoughts, it sounds like the prop will be available on the export toolbar button and allow to bypass the apiRef imperative methods. Why not.
> 
> Yes exactly - also this will allow for devs to be able to react to that action - maybe redirect or display something, etc. I can also delay adding it and see if there will be a demand for it.





https://reacter.space/questions/is-there-a-way-to-allow-for-clicking-on-a-row-to-redirect-to-a-new-tab-and-display-the-data-of-the-selected-row
