### ISSUE TITLE
[DataGrid] onFilterModelChange fires with invalid state

### ISSUE THREAD

**Issue by HaNdTriX** [mui-org/material-ui-x#1985]
When initialising `DataGrid` or `XGrid` with a default `filterModel` the `onFilterModelChange` invokes with an invalid state.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

On first render `onFilterModelChange` triggers 3 times when using a default `filterModel` prop.

### FilterModel prop

```jsx
    <DataGrid
      {...otherProps}
      filterModel={{
        items: [
          {
            columnField: "commodity",
            operatorValue: "contains",
            value: "rice"
          }
        ]
      }}
    />
```

### 1. Invokation `onFilterModelChange` 

The `filterModel` differs from the one passed in as a prop:

```json
{
    "items": [],
    "linkOperator": "and"
}
```

This makes it really hard to control the `filterModel` since the initial state will now get erased by this one. 
Any quick fix suggestions?

### 2. Invokation `onFilterModelChange` 

```json
{
    "items": [
        {
            "columnField": "commodity",
            "operatorValue": "contains",
            "value": "rice",
            "id": 33329
        }
    ],
    "linkOperator": "and"
}
```

### 3. Invokation `onFilterModelChange` 

```json
{
    "items": [
        {
            "columnField": "commodity",
            "operatorValue": "contains",
            "value": "rice",
            "id": 33329
        }
    ],
    "linkOperator": "and"
}
```

(see 1. Invokation `onFilterModelChange` )

## Expected Behavior 🤔

The `onFilterModelChange` should not fire at all. And if it fires it should have the right state:

```diff
{
-    "items": [],
+    "items": [
+        {
+            "columnField": "commodity",
+            "operatorValue": "contains",
+            "value": "rice",
+            "id": 33329
+        }
+    ],
    "linkOperator": "and"
}
```

## Steps to Reproduce 🕹

I have forked the codesandbox from https://material-ui.com/components/data-grid/filtering/#basic-filter and just added an `onFilterModelChange` prop.

Steps:

1. Open https://codesandbox.io/s/material-demo-forked-5sv8j?file=/demo.js
2. Open the console

## Context 🔦

I am trying to control the filter model.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  System:
    OS: macOS 11.4
  Binaries:
    Node: 15.4.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.15 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Edge: 88.0.705.74
    Firefox: 78.11.0
  npmPackages:
    @material-ui/core: ^4.11.4 => 4.11.4 
    @material-ui/data-grid: 4.0.0-alpha.32 => 4.0.0-alpha.32 
    @material-ui/icons: ^4.11.2 => 4.11.2 
    @material-ui/lab: 4.0.0-alpha.58 => 4.0.0-alpha.58 
    @material-ui/styles:  4.11.4 
    @material-ui/system:  4.11.3 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @types/react:  17.0.5 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
```
</details>

## Related

https://github.com/mui-org/material-ui-x/pull/1706#discussion_r659295801

https://github.com/mui-org/material-ui-x/blob/1da558a3ed8cb6eeb74268160dd6e5453411846f/packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx#L226-L229

#1760

**Comment by dtassone** [comment]
this will be fixed with #1909
