### ISSUE TITLE
DataGrid - rows per page dropdown is absent

### ISSUE THREAD

**Issue by maxdonetsk** [mui-org/material-ui-x#1992]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
rowsPerPage dropdown is absent in the TableFooter 

## Expected Behavior 🤔
rowsPerPage dropdown has to be present in the TableFooter 

## Steps to Reproduce 🕹
According to DataGrid Material-UI API, the rowsPerPage dropdown has to be present in the TableFooter, as in the official documentation here:
https://material-ui.com/components/data-grid/pagination/#page-size
<img width="909" alt="Screenshot 2021-06-28 at 23 25 47" src="https://user-images.githubusercontent.com/8349136/123731473-d8e22b80-d8a0-11eb-8d70-97c2687cc20b.png">
But when I open this example in CodeSandbox, this feature is absent at the UI: https://codesandbox.io/s/f8fv5
<img width="1440" alt="Screenshot 2021-06-28 at 23 26 22" src="https://user-images.githubusercontent.com/8349136/123731654-40987680-d8a1-11eb-8470-c1b342c02378.png">

**Comment by flaviendelangle** [comment]
Duplicates #1907

**Comment by flaviendelangle** [comment]
https://github.com/mui-org/material-ui-x/issues/1907#issuecomment-862420137

You can apply this style to override the current behavior.
We are looking to improve the default behavior later.
