### ISSUE TITLE
[DataGrid] Accessibility keyboard behaviour on a read-only selected cell doesn't take 'enter' to fire onCellClick.

### ISSUE THREAD

**Issue by cbazza** [mui-org/material-ui-x#2001]
When using keyboard navigation there is no way to have the same behaviour as clicking on the cell. I need <kbd>Enter</kbd> to fire `onCellClick`.

**Comment by oliviertassinari** [comment]
@cbazza We need more details. Could you expand on the problem you are trying to solve? Do you have a codesandbox or else to illustrate it?

**Comment by cbazza** [comment]
It's basically the accessibility behaviour when you tab and move the focus around with the keyboard.

Once it gets to the table, it highlights the first header and you can use the arrows to move the focus box around the table.
The problem is that when you press 'enter' on the focused cell it does nothing. 
Material UI behaviour is to fire the onClick event.

Just the very basic table with no editable cells at all. Table has onCellClick setup so that once user clicks on cell is does the callback. All I want is that exact same behaviour if user uses keyboard to navigate to cell and press 'enter', it should call onCellClick.

**Comment by oliviertassinari** [comment]
You can use `GRID_CELL_KEY_DOWN` to listen to the <kbd>Enter</kbd> on the cell. Has no supporting material for the expected behavior. So I conclude that enter should **not** trigger a click event nor do any action on a regular cell's container. Thanks for raising the frustration.

**Comment by cbazza** [comment]
From the documentation it doesn't look like `DataGrid` takes an `apiRef` prop like `XGrid`.
https://material-ui.com/components/data-grid/events/
https://material-ui.com/api/data-grid/x-grid/ 
https://material-ui.com/api/data-grid/data-grid/
So I don't see how to get access to these events.
Maybe the documentation is just outdated?

**Comment by oliviertassinari** [comment]
@cbazza This is correct, `apiRef` is only available in the Pro plan and upward. But the docs confusing https://material-ui.com/components/data-grid/events/. You don't need the apiRef to listen to an event. You can use the props too.

It looks like you have hit the frustration 1. in of #1826.
