### ISSUE TITLE
MUI dark theme switch bug with installed PWA

### ISSUE THREAD

**Issue by jbty** [mui-org/material-ui-x#2005]
- [ x ] The issue is present in the latest release.
- [ x ] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

hi, when I install my react PWA, during the first load if we try to switch between light color mode and dark color all the components disappear. The problem goes away if I close and reopen the pwa

To reproduce the bug you have to compile react in production open the pwa, install it, then directly click on the theme switch icon at the top right

https://codesandbox.io/s/fervent-water-v83mh

**Comment by oliviertassinari** [comment]
Please provide a **minimal** reproduction test case.

**Comment by jbty** [comment]
1 clone the repo 
2 run npm i
3 run npm build
4 serve the bundled app on localhost
5 on chrome click to the install pwa button on right of the top searchbar 
6 open the installed pwa from your laptop 
7 click on the "moon" button in the app, on top riht app bar

All components is strangly hidden at this point

**Comment by oliviertassinari** [comment]
@jbty This is a bug and feature request tracker. We can't debug a full-blown application. In the Premium plan we might provide some advisory services, but we aren't here yet.

**Comment by jbty** [comment]
All right, what's premium plan ?

**Comment by oliviertassinari** [comment]
A work in progress: https://next.material-ui.com/branding/pricing/.

**Comment by jbty** [comment]
@oliviertassinari I have already purchased the pro version, but what should I do to benefit from the support?

**Comment by oliviertassinari** [comment]
@jbty What do you have in mind by "support"? We accept bug reports in this issue tracker, as well as proposals for new features.

**Comment by jbty** [comment]
@oliviertassinari my bad I'dont understand correctly the "Pro" offer
