### ISSUE TITLE
[XGrid] Column resizing not working on touch devices

### ISSUE THREAD

**Issue by m4theushw** [mui-org/material-ui-x#2007]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Trying to resize a column on a touch device doesn't work.

<img width="600" src="https://user-images.githubusercontent.com/42154031/124054590-a8150a00-d9f8-11eb-8178-23c3aa9a0224.gif" alt="ijcwULWI79" style="max-width:100%;">

## Expected Behavior 🤔

It should allow to resize.

## Context 🔦

This is a regression from #1720. When the effect runs the ref below is undefined, then it doesn't add the listener.

https://github.com/mui-org/material-ui-x/blob/de37d4b92d0534bd541598d88ea0df25710de6ae/packages/grid/_modules_/grid/hooks/features/columnResize/useGridColumnResize.tsx#L313

Raised in https://github.com/mui-org/material-ui-x/pull/1989#discussion_r661894494 and https://github.com/mui-org/material-ui-x/pull/1967#issuecomment-870047282.

**Comment by oliviertassinari** [comment]
It looks like now is a great time for adding a test https://github.com/mui-org/material-ui-x/pull/537#issuecomment-723268076 😁. It was broken in https://github.com/mui-org/material-ui-x/pull/1720
