### ISSUE TITLE
[DataGrid] Implement multi-column filter

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#201]
### Plan of action

- [ ] 1. Build a column header menu, it will be used for filtering, sorting and any other feature that a column can leverage.

<img width="192" alt="Capture d’écran 2020-11-02 à 11 45 48" src="https://user-images.githubusercontent.com/3165635/97859498-fc000f80-1d00-11eb-8bce-0f87a52a9401.png">

- [ ] 2. Build the internal state filtering logic to support one type: string and one operator: contain.
- [ ] 3. Create a global filter UI popup, same as Airtable, Notion, Retool.

<img width="589" alt="Capture d’écran 2020-11-02 à 11 46 14" src="https://user-images.githubusercontent.com/3165635/97859529-08846800-1d01-11eb-9fe5-ae7fc05611ed.png">

- [ ] 4. Expose a programmatic public filtering API (3. was for end-users, 4. is for developers).
- [ ] 5. Support all the operations and types possible: date, date range, exclude, etc.
- [ ] 6. Add a toolbar component #516 (filter popup open, display density, etc.)

<img width="494" alt="Capture d’écran 2020-11-02 à 11 47 07" src="https://user-images.githubusercontent.com/3165635/97859604-2782fa00-1d01-11eb-8e7e-80b53d240ca1.png">

- [ ] 7. Implement quick filter #202 

<img width="316" alt="Capture d’écran 2020-11-02 à 11 48 42" src="https://user-images.githubusercontent.com/3165635/97859790-5f8a3d00-1d01-11eb-97e2-72638d9ed6b6.png">

- [ ] 8. Consider supporting inline filter (e.g. react-table [demo](https://react-table.tanstack.com/docs/examples/filtering)) but we might not do it.

<img width="504" alt="Capture d’écran 2020-11-02 à 11 47 44" src="https://user-images.githubusercontent.com/3165635/97859700-46818c00-1d01-11eb-93c5-59d1725c762d.png">

### Benchmark

- https://react-table.tanstack.com/docs/examples/filtering
- https://ant.design/components/table/#components-table-demo-head
- https://material-table.com/#/docs/features/filtering
- https://ag-grid.com/javascript-grid-filtering/
- https://demos.telerik.com/kendo-ui/grid/filter-row
- https://www.telerik.com/kendo-react-ui/components/grid/filtering/
- https://ej2.syncfusion.com/react/demos/#/material/grid/filter-menu
- https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/Filtering/React/Light/
- https://www.jqwidgets.com/react/react-grid/#https://www.jqwidgets.com/react/react-grid/react-grid-filtering.htm
- http://tabulator.info/docs/4.5/filter
- https://www.bryntum.com/examples/grid/filterbar/
- https://handsontable.com/examples?manual-resize&manual-move&conditional-formatting&context-menu&dropdown-menu&headers&filters
- https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/tree_grid.html
- https://baseweb.design/components/unstable-data-table/#batch-actions
- https://try.firetable.io/table/mvpResources

<details>
  <summary>Screenshots</summary>

- https://react-table.tanstack.com/docs/examples/filtering

<img width="389" alt="Capture d’écran 2020-10-01 à 00 11 07" src="https://user-images.githubusercontent.com/3165635/94745253-a095d700-037a-11eb-8f67-b7f2ea506b40.png">

- https://ant.design/components/table/#components-table-demo-head

<img width="253" alt="Capture d’écran 2020-10-01 à 00 10 03" src="https://user-images.githubusercontent.com/3165635/94745140-78a67380-037a-11eb-82d4-8344c95726f0.png">

- https://material-table.com/#/docs/features/filtering

<img width="454" alt="Capture d’écran 2020-10-01 à 00 08 11" src="https://user-images.githubusercontent.com/3165635/94745051-4bf25c00-037a-11eb-972a-d351cd93755d.png">

- https://ag-grid.com/javascript-grid-filtering/

<img width="320" alt="Capture d’écran 2020-10-01 à 00 08 36" src="https://user-images.githubusercontent.com/3165635/94745044-49900200-037a-11eb-911c-812f33140383.png">

- https://demos.telerik.com/kendo-ui/grid/filter-row
- https://www.telerik.com/kendo-react-ui/components/grid/filtering/

<img width="295" alt="Capture d’écran 2020-10-01 à 00 06 56" src="https://user-images.githubusercontent.com/3165635/94744914-0cc40b00-037a-11eb-8d9f-8e6c9063f2fb.png">
<img width="278" alt="Capture d’écran 2020-10-01 à 00 07 00" src="https://user-images.githubusercontent.com/3165635/94744919-0e8dce80-037a-11eb-99df-39d460adf654.png">

- https://ej2.syncfusion.com/react/demos/#/material/grid/filter-menu

<img width="248" alt="Capture d’écran 2020-10-01 à 00 05 20" src="https://user-images.githubusercontent.com/3165635/94744789-dbe3d600-0379-11eb-9c38-2c55114f7846.png">
<img width="277" alt="Capture d’écran 2020-10-01 à 00 05 31" src="https://user-images.githubusercontent.com/3165635/94744792-ddad9980-0379-11eb-9a56-0ea3dd3474d6.png">

- https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/Filtering/React/Light/

<img width="229" alt="Capture d’écran 2020-10-01 à 00 06 03" src="https://user-images.githubusercontent.com/3165635/94744868-f6b64a80-0379-11eb-8a7f-090a41103a8b.png">

- https://www.jqwidgets.com/react/react-grid/#https://www.jqwidgets.com/react/react-grid/react-grid-filtering.htm

<img width="365" alt="Capture d’écran 2020-10-01 à 00 03 39" src="https://user-images.githubusercontent.com/3165635/94744606-94f5e080-0379-11eb-9e52-b6cc4bf13dbb.png">

- http://tabulator.info/docs/4.5/filter

<img width="438" alt="Capture d’écran 2020-10-01 à 00 01 35" src="https://user-images.githubusercontent.com/3165635/94744449-4d6f5480-0379-11eb-9324-35afbbf3ccf1.png">

- https://www.bryntum.com/examples/grid/filterbar/

<img width="277" alt="Capture d’écran 2020-09-30 à 23 59 50" src="https://user-images.githubusercontent.com/3165635/94744326-0bdea980-0379-11eb-98d9-896dfc2c0773.png">

- https://handsontable.com/examples?manual-resize&manual-move&conditional-formatting&context-menu&dropdown-menu&headers&filters

<img width="274" alt="Capture d’écran 2020-09-30 à 23 58 38" src="https://user-images.githubusercontent.com/3165635/94744219-e356af80-0378-11eb-9161-e0af89586c18.png">

- https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/tree_grid.html

<img width="844" alt="Capture d’écran 2020-09-30 à 23 57 32" src="https://user-images.githubusercontent.com/3165635/94744101-bd310f80-0378-11eb-8b96-63e7f0c9625e.png">

- https://baseweb.design/components/unstable-data-table/#batch-actions

<img width="561" alt="Capture d’écran 2020-09-25 à 22 53 14" src="https://user-images.githubusercontent.com/3165635/94314955-eb31e080-ff81-11ea-9cf9-ae9b6391d565.png">

- https://try.firetable.io/table/mvpResources

<img width="1286" alt="Capture d’écran 2020-09-30 à 23 55 21" src="https://user-images.githubusercontent.com/3165635/94743916-6f1c0c00-0378-11eb-85c6-9a7a234cd23e.png">

</details>

**Comment by gsivak22** [comment]
I am waiting to see the column level filter in Data grid

**Comment by Darrel-Collinsworth** [comment]
👍

**Comment by oliviertassinari** [comment]
This issue includes 3 aspects:

1. the built-in capability to handle filtering in the component.
2. quick column filter (a simple filter field embedded in the column header).
3. column filter.

For 2., I would vote for going with airtable.com's approach. From my perspective, it's the best one seen so far.

---

The filtering UX of airtable.com

<img width="444" alt="Capture d’écran 2020-10-13 à 13 30 20" src="https://user-images.githubusercontent.com/3165635/95855205-52101180-0d58-11eb-98bd-00dac0028746.png">

The filtering UX of stripe.com

<img width="285" alt="Capture d’écran 2020-10-13 à 13 29 57" src="https://user-images.githubusercontent.com/3165635/95855222-576d5c00-0d58-11eb-94bb-7a47728012fb.png">

**Comment by nextglabs** [comment]
+1 for AirTable UX

**Comment by oliviertassinari** [comment]
Notion has the same UX as Airtable, it works great

<img width="1011" alt="Capture d’écran 2020-10-27 à 23 40 45" src="https://user-images.githubusercontent.com/3165635/97372120-2130f000-18b3-11eb-805d-f607c3e4fa74.png">

**Comment by bmagnette** [comment]
I would love to see the filter on this table, anyone know if this is in progress ?

**Comment by dtassone** [comment]
Yes we are working on it :)

**Comment by bmagnette** [comment]
Awesome !! Thank you for that :)

**Comment by oliviertassinari** [comment]
The UX of Retool:

<img width="656" alt="Capture d’écran 2020-11-02 à 11 39 27" src="https://user-images.githubusercontent.com/3165635/97858918-26050200-1d00-11eb-8a11-bec7b0059685.png">

---

An update the issue's descripton with a [plan of action](https://github.com/mui-org/material-ui-x/issues/201#issue-683675004).

**Comment by HichemDax** [comment]
Hi team, appreciate your efforts bringing filtering to this amazing Datagrid, any plans when to release. Critical for us to use / not to use in a coming project.

**Comment by oliviertassinari** [comment]
> when to release

@HichemDax End of the month if everything goes well, before the end of the year is likely.

**Comment by HichemDax** [comment]
Thats a good news, thanks @oliviertassinari

**Comment by ramdaniAli** [comment]
🔥

**Comment by rejoan121615** [comment]
Please make it available

**Comment by oliviertassinari** [comment]
This is our latest progress on the feature: https://codesandbox.io/s/material-demo-forked-8tryv?file=/index.js. Any early feedback would be appreciated. You can find the underlying pull request at #411 :D

**Comment by angelsvirkov** [comment]
Really looking forward to this. 🚀  . The current demo looks awesome. 

Are there any plans to add support for server-side filtering or in other words to expose the selected column filters in a public developer API? I am not sure if that is what you guys mentioned in the issue description with 
> 4. Expose a programmatic public filtering API (3. was for end-users, 4. is for developers)

**Comment by oliviertassinari** [comment]
@angelsvirkov I hear two different use cases in your message:

1. The capability to filter from the server. There are two precedent with the [server-side pagination](https://material-ui.com/components/data-grid/pagination/#server-side-pagination) and [server-side sorting](https://material-ui.com/components/data-grid/rows/#server-side-sorting) features.
2. The capability to listen to the filters applied. For instance, it could be used to implement 1. but with some limitations. We plan to allow this. @dtassone has started to work on it in #533, but nothing that can be used yet. Developers using Material-UI could consider that a feature not documented is private and could be removed at any time. In this direction, we will have a `onStateChange` API.

**Comment by paillave** [comment]
Great progress. Here are some comments based on my first impression though (we all know that the first impression counts when it is about ergonomic):

The filter should be much more straight forward. I don't mean showing a horrible textbox/drop down on top of every filterable column. The popup is indeed a good ergonomic compromise to get a grid that is visually as light as possible. According to me, the problem lie in the fact this complex filtering system that is shown by default is not user friendly regarding to the 95% of usage: quickly typing a keyword for the dedicated column to get a result asap. This advanced "intimidating" and click consuming filtering/sorting system should be accessed from somewhere else with a global dedicated button on top of the grid.
When filtered, a column should have an extra icon (or simply by changing the existing vertical triple points icon into another one) shown to know in an eyesight that this column is filtered.

## To summarize...
The software who made everybody agree with its ergonomics is Excel. What is needed 95% of times is both very simple and very fast to get. Like this: 
![image](https://user-images.githubusercontent.com/4611176/100068529-f8f7cb00-2e37-11eb-8cb3-03a9c4dc1fd0.png)
then click on the of the column you wanna filter:
![image](https://user-images.githubusercontent.com/4611176/100070219-f4ccad00-2e39-11eb-93b4-74e9975df1e5.png)

And yet... advanced features are offered, but it's a "gridwide" feature accessible with a different button (a global button some where that shows a different screen such as the one you show for now).
My belief is that you shall focus on what represents 95% (not to say 99%) of usage to start. And then, later on, as an extra feature (why not for the commercial version) implement the advanced feature shown on a different screen.

**Comment by HichemDax** [comment]
If you would like to have a powerful Filter feature stick to what @paillave said. I was about to write in the same idea.

**Comment by timonbimon** [comment]
FWIW I think the global sorting/filtering UI from Airtable/Notion is definitely the right way to go. Super glad to see you are working on it and cannot wait to integrate it in our current product. :)

**Comment by paillave** [comment]
@timonbimon this feature is indeed necessary for the grid to be complete. But still, it is according to me unacceptable to show such a complex screen to make a quick filter. I don't see myself selling such a "quick filtering" feature to my clients who are so used to the quick and straightforward excel filtering system. Once again, make common use cases very simple, and leave advanced ones complex. Making a complex screen to ensure that is covers as well what is needed only 5% of time is a big mistake. End users choose a product based on its productivity. It is ludicrous that users spend 95% of their time doing like they need a advanced filter. And still once again, users (and myself) believe that Excel just made it perfect! I would be a pity to change something that already has the approval of (nearly) the entire planet whereas it took 30 years to Excel to reach this level of ergonomic.

**Comment by oliviertassinari** [comment]
@paillave For the quick filter, would #202 be more relevant? It's the filter `<input>` that displays inside the column header.

**Comment by HichemDax** [comment]
@oliviertassinari the quick filter in #202 has a wide scope and the one in Airtable is just complex from beginning and requires much more clicks and thinking.. Excel like filter is the best sitting in the right middle.

**Comment by timonbimon** [comment]
maybe one thing to add @HichemDax : in the sandbox linked above you currently open the Airtable-like filtering from the dropdown menu of a single column (but you can then filter on all columns), which definitely seems a little awkward and complex. If I understand step 3 in @oliviertassinari plan of action correctly, the idea is to move that to a global popup (just like it is in Airtable and Notion) which I find very intuitive to use (if you ever used Airtable or Notion before, I would guess you would agree? 😬 maybe not though if you're an avid Excel user 🤷‍♂️)

**Comment by paillave** [comment]
> @paillave For the quick filter, would #202 be more relevant? It's the filter `<input>` that displays inside the column header.

The simple input is far to be sufficient as a quick filter according to me. And the filter you implement if far too complex for a quick filter according to me. Still, I believe it may be interesting to have it for "business intelligence like" applications. And you should keep on developing it. But it's a marginal use case.

Components you rely on for this development are ignoring 30 years of ergonomic try/error process that represents Excel in this matter. 
On the other hand, I understand that your actual users/clients are nerdy developers who love technical and highly evolved all in one consistent features. I also understand developers who would like to have a-datadrig-that-makes-every-crazy-thing-so-that-I-m-sure-nobody-will-ask-me-anything-more-to-develop. The thing is that *actual* endusers love the way Excel handles filters and they never requested more. So I don't really see why they would request more than excel on the datagrid of an application.

Once again, I suggest you to take the best from the bests... We can say whatever we want of Microsoft, but the ergonomics the ended up with on Excel clearly rocks. Even if it is a spreadsheet application, I believe you should get large inspiration from it about what can be related to datagrids as nobody ever questioned its ergonomic.
I am not gonna annoy with more posts about Excel as I believe I made my point. From my point of view, I expect a lot from your datagrid, and I'd love to show the best grids to my clients (simple, straightforward and still efficient features) in a near future so that I can get rid of react devextreme that is too slow, very crashy and... with a bad quick filter :smile:

**Comment by dtassone** [comment]
Obviously, guys, we can't satisfy everyone in the approach we take. But we can provide enough flexibility for you to tweak things around and make it the way you like. We are aiming for a plugin-based architecture, easily customizable.

ATM, we have a column menu that will be overridable soon, thus, you could provide your own menu and just provide excel-like filters if needed... IMHO, checkboxes are good when there are a limited number of values within a column, an autocomplete text field might be easier for a large set of values, and much faster for processing. With checkboxes, we have to extract all distinct values of each row on a column before rendering the list of values in the filter popup. Thus for 100000 rows, on some old machine, it might not be ideal to run that process on the client...

That being said, I'm not against providing an excel-like type of filter, that could be attached to certain columns. 
@paillave  Could you please create a separate issue for the excel type of filters you requested?

**Comment by paillave** [comment]
@dtassone ok, I will. 
FYI, I didn't speak about doing checkboxes like in excel. I totally understand that it can have a massive impact of performances if we have to show more than 10000 rows. I just meant that the popup should be related to the column and **very** simple. The whole Excel behavior with the checkbox list and the amount of occurrences that are related would a fantastic cherry on the cake.

**Comment by AleKrabbe** [comment]
The demos look awesome, good work! 

Will it be possible to add a locale file to translate those filters? I just purchased a license, would need to translate it to portuguese tho.

Thank you.

**Comment by oliviertassinari** [comment]
> Will it be possible to add a locale file to translate those filters?

@AleKrabbe We plan to solve this problem in #196, would the proposed solution cover your use cases?

**Comment by AleKrabbe** [comment]
> > Will it be possible to add a locale file to translate those filters?
> 
> @AleKrabbe We plan to solve this problem in #196 during the current sprint. Would the proposed solution cover your use case?

Yes, that would solve the problem, is #196 being released together with #201 ?

**Comment by GravityCube** [comment]
Any update or new demo? :(

**Comment by rlmonger** [comment]
Great feature! Once this is released, certainly purchasing material ui x for the Xgrid!

**Comment by mbrookes** [comment]
@timonbimon
> in the sandbox linked above you currently open the Airtable-like filtering from the dropdown menu of a single column (but you can then filter on all columns), which definitely seems a little awkward and complex.

This adds the specific column from which the filter is opened to the filter list. It's a shortcut of sorts, over the alternative of having a single filter option on the table, and then selecting the column to apply the filter to.

One alternative would be to scope filters selected at the column to that column (how Excel works). The disadvantage of this approach is that with large numbers of columns, it can be difficult to see which columns have filters applied, and these have to be added / cleared one-at-a-time. 

The current approach is the best of both, albeit with a UX trade-off caused by the slight cognitive dissonance of a multi-column filter apparently being attached to individual columns.

**Comment by mbrookes** [comment]
@dtassone 
> an autocomplete text field might be easier for a large set of values, and much faster for processing

Here's Excel for Mac, which has a slightly simpler UI than the one in @paillave's screenshot, (note the search box for filtering the values):

![image](https://user-images.githubusercontent.com/357702/102012255-37025380-3d41-11eb-98d1-c5a226067ff1.png)

As you suggest, a [multi-select autocomplete](https://material-ui.com/components/autocomplete/#multiple-values) with the condition (currently labelled "operator") being "One of" would be perfect.

Incidentally, I just tried it in Excel with a spreadsheet containing ~50K rows, and 32 columns, and displaying the filter was instant, on a 6 year old laptop. (Yes, in memory, with compiled code, but just for reference.)

**Comment by timonbimon** [comment]
> @timonbimon
> 
> > in the sandbox linked above you currently open the Airtable-like filtering from the dropdown menu of a single column (but you can then filter on all columns), which definitely seems a little awkward and complex.
> 
> This adds the specific column from which the filter is opened to the filter list. It's a shortcut of sorts, over the alternative of having a single filter option on the table, and then selecting the column to apply the filter to.
> 
> One alternative would be to scope filters selected at the column to that column (how Excel works). The disadvantage of this approach is that with large numbers of columns, it can be difficult to see which columns have filters applied, and these have to be added / cleared one-at-a-time.
> 
> The current approach is the best of both, albeit with a UX trade-off caused by the slight cognitive dissonance of a multi-column filter apparently being attached to individual columns.

Yes, I think once there is a UI element for the entire filter list (independent of the column) then that shortcut makes perfect sense and creates no cognitive dissonance! 🤗 

Btw here is the link to a [live Airtable example](https://support.airtable.com/hc/en-us/articles/360021501754#what-are-views) I have looked at multiple times while trying to shape a search/sort/filter-feature in the last weeks (we ended up deciding to wait until you guys release this and then build on top of DataGrid 🙌).

**Comment by mbrookes** [comment]
> here is the link to a live Airtable example

Oh, interesting: the name of the column menu option "Add filter" (rather than "Filter") combined with the presence of the table-level filter icon, makes all the difference.

cc @dtassone

**Comment by NaveenKJammula** [comment]
@oliviertassinari  is this enhancement released?

**Comment by oliviertassinari** [comment]
@NaveenKJammula Yes: https://material-ui.com/components/data-grid/sorting/#multi-column-sorting.

**Comment by NaveenKJammula** [comment]
@oliviertassinari  I see so this is only available in `DataGridPro` not in `DataGrid`?
