### ISSUE TITLE
DataGrid not executing `onEditCellChange`-handlers when using `singleSelect`-Cells

### ISSUE THREAD

**Issue by dckjnls** [mui-org/material-ui-x#2035]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When editing a `singleSelect` cell and commiting the change, the `onEditCellChangeComitted`- and `onEditCellChange`-handler of the DataGrid component aren't being executed.

## Expected Behavior 🤔

The `onEditCellChangeComitted`- and `onEditCellChange`-handler should get executed when editing/commiting a change in the DataGrid component

## Steps to Reproduce 🕹
Steps:

1. Go to the [Sandbox](https://codesandbox.io/s/relaxed-star-nl4qf?file=/src/App.tsx)
2. Open the Console
3. Change Name and see that the change is being logged in the console
4. Change the Birthyear and see that nothing is being logged in the console

## Context 🔦

I'm trying to do a Project Table where I can change Items from a Database.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  Browser: Chrome Version 91.0.4472.124 (Official Build) (64-bit)
```
npx: installed 2 in 10.847s

  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 14.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.906.0), Chromium (91.0.864.64)    
  npmPackages:
    @material-ui/core: ^4.11.4 => 4.11.4 
    @material-ui/data-grid: ^4.0.0-alpha.33 => 4.0.0-alpha.33 
    @material-ui/icons: ^4.11.2 => 4.11.2 
    @material-ui/pickers: ^3.3.10 => 3.3.10
    @material-ui/styles:  4.11.4
    @material-ui/system:  4.11.3
    @material-ui/types:  5.1.0
    @material-ui/utils:  4.11.2
    @types/react: ^17.0.0 => 17.0.10
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.1.2 => 4.3.2

```
</details>

**Comment by dtassone** [comment]
Thanks for raising this issue, the sandbox does not seem to be working.

**Comment by DanailH** [comment]
This will be fixed once that PR https://github.com/mui-org/material-ui-x/pull/1955 is merged.

**Comment by dckjnls** [comment]
> Thanks for raising this issue, the sandbox does not seem to be working.
@dtassone 

sorry, copied it wrong, link should be working now, if you still need it
