### ISSUE TITLE
[DataGrid] Example not working in /tables

### ISSUE THREAD

**Issue by dmi4uv** [mui-org/material-ui-x#2039]
Hi!
 [Data Table](https://material-ui.com/components/tables/#data-table) exampe not working in [CodeSandbox](https://codesandbox.io/s/3u8si?file=/demo.js)
![bug](https://user-images.githubusercontent.com/62292321/124470417-a35fa580-ddac-11eb-92b1-12af44c2e5fc.jpg)

**Comment by oliviertassinari** [comment]
A regression from: #1513

**Comment by oliviertassinari** [comment]
@mui-org/x Who wants to fix it? We need a fix on *next* and *master*. It's a good reminder that breaking changes have a cost.

**Comment by dtassone** [comment]
`getValue` was refactored for perf reason. You now need to pass the row id and the column field as arguments.
More about this change on https://github.com/mui-org/material-ui-x/releases/tag/v4.0.0-alpha.29

fix sandbox https://codesandbox.io/s/sweet-greider-jmudl

**Comment by dtassone** [comment]
@oliviertassinari what issue on core are you referring to?

**Comment by oliviertassinari** [comment]
https://github.com/mui-org/material-ui-x/issues/2039#issue-937081779

**Comment by dtassone** [comment]
ok closing as explained https://github.com/mui-org/material-ui-x/issues/2039#issuecomment-877064150

**Comment by oliviertassinari** [comment]
It's about fixing the demo.
