### ISSUE TITLE
[DataGrid] GridToolbarFilterButton props spread doesn't follow other Toolbar components

### ISSUE THREAD

**Issue by tifosiblack** [mui-org/material-ui-x#2083]
<GridToolbarColumnsButton color="inherit" /> render a "inherit" button, <GridToolbarFilterButton color="inherit" /> render a "primary" button.

- [x ] The issue is present in the latest release.
- [x ] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
GridToolbarColumnsButton props spreading comes before override, not after.

## Expected Behavior 🤔
Props spreading should come after.

## Your Environment 🌎

<details>
  <summary>System info</summary>

System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 14.17.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.64)
  npmPackages:
    @emotion/react: ^11.4.0 => 11.4.0
    @emotion/styled: ^11.3.0 => 11.3.0
    @material-ui/core: ^5.0.0-beta.0 => 5.0.0-beta.0
    @material-ui/data-grid: ^4.0.0-alpha.33 => 4.0.0-alpha.33
    @material-ui/icons: ^5.0.0-beta.0 => 5.0.0-beta.0
    @material-ui/lab: ^5.0.0-alpha.38 => 5.0.0-alpha.38
    @material-ui/private-theming:  5.0.0-alpha.36
    @material-ui/styled-engine:  5.0.0-alpha.34
    @material-ui/styles: ^5.0.0-beta.0 => 5.0.0-beta.0
    @material-ui/system:  5.0.0-alpha.38
    @material-ui/types:  6.0.1
    @material-ui/unstyled:  5.0.0-alpha.39
    @material-ui/utils:  5.0.0-alpha.36
    @types/react: ^17.0.13 => 17.0.13
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.3.5 => 4.3.5
</details>

**Comment by tifosiblack** [comment]
I'll provide a PR for that change, it seems easy

**Comment by DanailH** [comment]
> I'll provide a PR for that change, it seems easy

@tifosiblack That would be great, thanks ;)
