### ISSUE TITLE
Unable to Click Header of Datagrid.

### ISSUE THREAD

**Issue by mhkasif** [mui-org/material-ui-x#2105]
## Current Behavior 😯
I just Installed the Data Grid Library and the header of the table is unclickable,
which makes things not work like sorting and filtering.

https://user-images.githubusercontent.com/30750191/124941444-3a826280-e024-11eb-978b-43f5dd48092f.mov

## Expected Behavior 🤔
I looked for the CSS and found that a particular class is having a **Position: absolute** which makes things not work

https://user-images.githubusercontent.com/30750191/124942050-b5e41400-e024-11eb-8dd6-303cd2ad0c9d.mov

 <DataGrid
              hideFooter
              autoHeight
              rows={rows}
              columns={columns}
              components={{
                ColumnSortedDescendingIcon: SortedDescendingIcon,
                ColumnSortedAscendingIcon: SortedAscendingIcon,

              }}
               pageSize={5}
               checkboxSelection
              onColumnHeaderClick={(e)=>console.log(e)}
              headerHeight={35}
             
            />

**Comment by flaviendelangle** [comment]
@mhkasif  Could you please provide a codesandbox, so we can work on the exact same example.
Here is a [codesandbox.io template](https://codesandbox.io/s/material-ui-issue-next-o7xkt) to help you get started.

**Comment by mhkasif** [comment]
> @mhkasif Could you please provide a codesandbox, so we can work on the exact same example.
> Here is a [codesandbox.io template](https://codesandbox.io/s/material-ui-issue-next-o7xkt) to help you get started.

https://codesandbox.io/s/table-ipp8w
Here is the issue.
I figured out that when I'm using autoHeight and giving `*{position: relative}`, it is not working.

**Comment by dtassone** [comment]
Yes you are overriding all the internal css with this so it can't work as some elements are in absolute position. 
Just remove the * and use a selector.
