### ISSUE TITLE
[DataGrid] Broken support of core v4.12.1

### ISSUE THREAD

**Issue by NielsRavn** [mui-org/material-ui-x#2106]
in data-grid version 4.0.0-alpha.33, i cannot build my typescript project because the data-grid.d.ts:519 references Localization$1['components'] in @material-ui/core/localization, which does not exist.
I have tried with the listed version @material-ui/core@4.9.12 and the latest version @material-ui/core@4.12.1.
The problem is also in version 4.0.0-alpha.32 but not present in 4.0.0-alpha.31 as it does not reference the localization of material ui.

The error message:
Property 'components' does not exist on type 'Localization'.

Maybe it is meant to be only for material-ui@5.0.0? i havent tried with that, as it is not tagged as the latest version yet.

**Comment by DanailH** [comment]
@NielsRavn thanks for raising this. There seems to be a problem with the way we detect if the user `@material-ui/core` is v5 or v4. The `DataGrid` localizations are built for v5 even though the used version is v4.

**Comment by ddolcimascolo** [comment]
Hey guys,

Upgrading core to 4.12 has also started raising quite a lot of warnings in our test suites. Specifically tons of `Material-UI: The key `selectLabel` provided to the classes prop is not implemented in ForwardRef(TablePagination)`

Is this the same issue?

Thanks,
David

**Comment by oliviertassinari** [comment]
@ddolcimascolo Yes, same isue

**Comment by ddolcimascolo** [comment]
Guys, any news on this ?

**Comment by Delapouite** [comment]
Thanks @DanailH for your hints.

At first, I struggled understanding why the change you mention  https://github.com/mui-org/material-ui/pull/22837/files#diff-6cbc65d66b330740baa9ae285cbaca3eb3cb0ec24e6de630887ad1830e7f9fa8 which is about the switch from `fade` → `alpha` was related to the topic.

But then I had a look at the guard you also mention :

```
export function isMuiV5(): boolean {
  return 'alpha' in styles;
}
```

And now it makes sense.

**Comment by m4theushw** [comment]
To fix the error "Property 'components' does not exist on type 'Localization'.", the solution is to set [`skipLibCheck`](https://www.typescriptlang.org/tsconfig#skipLibCheck) to true in `tsconfig.json`.

```json
{
  "compilerOptions": {
    "skipLibCheck": true
  },
}
```

**Comment by oliviertassinari** [comment]
I also take care of it in #2117.
