### ISSUE TITLE
[DataGrid] Implement Master detail/panel

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#211]
### Docs

https://mui.com/components/data-grid/group-pivot/#master-detail

### Benchmark

- https://material-table.com/#/docs/features/detail-panel
- https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/detail-row/
- https://shlomiassaf.github.io/ngrid/features/built-in-plugins/detail-row
- https://www.ag-grid.com/javascript-grid-master-detail/
- https://ej2.syncfusion.com/react/demos/#/material/grid/master-detail
- https://www.telerik.com/kendo-react-ui/components/grid/advanced-features/hierarchy/

**Comment by oliviertassinari** [comment]
@ak-mid In theory, this will be inside the Pro plan. Virtualization doesn't make it a simple problem to solve.

**Comment by ak-mid** [comment]
@oliviertassinari Thanks for clarification! I already thought that this won't be an easy task.

**Comment by wmhartl** [comment]
Another example in case it helps: https://autodesk.github.io/react-base-table/examples/detail-view

**Comment by tlmader** [comment]
Hello! We are interested in using `<XGrid>` with the Pro plan for our project, and we require master/detail panel. I don't currently see this in the [Material-UI X public roadmap](https://github.com/mui-org/material-ui-x/projects/1). Do you have any ETAs regarding this feature?

**Comment by oliviertassinari** [comment]
@tlmader We will update the public roadmap in the coming 7 days. We reach the end of Q1, time to reprioritize :).

**Comment by tlmader** [comment]
@oliviertassinari Thank you for the reply!

**Comment by davidhernon** [comment]
@oliviertassinari Hello, we are in the same boat as @tlmader. I just checked the roadmap (seeing it was updated 2 days ago) but I'm not seeing anything about this feature! Are there any plans for this feature at this time? Thank you!

**Comment by oliviertassinari** [comment]
@davidhernon Hard to tell. We currently aim to improve the quality of the current feature implemented, so existing users get a great experience with. We know that we want to fix #417 and #438. Once done, this should be trivial to handle.

**Comment by davidhernon** [comment]
@oliviertassinari Thanks for the info!

**Comment by arheinjohnson** [comment]
Same as @tlmader and @davidhernon this is a highly valuable feature for us

**Comment by allidoisace** [comment]
Hi there, what would be the difference between this and the Tree Data feature?

**Comment by wmhartl** [comment]
Tree data in my experience is nested relations of the same type of data, so say a parent/child relationship between rows of data in the grid. So expanding the tree would let you see its "child" rows.

A detail panel lets you expose additional data about whatever specific item is in that row - such as in the picture above the "history" of the frozen yogurt.

**Comment by ironpfis7** [comment]
Our company is currently using the pro version of the data-grid, and we would love to use this feature. Are there any updates on when exactly this may be accessible? I see it was pushed to Q4, but was wondering if there was a specific month that was being aimed for.

**Comment by arheinjohnson** [comment]
Is there a workaround for this in the latest release? We need something to work now and can incorporate your improved feature when it's available.

**Comment by m4theushw** [comment]
@arheinjohnson This is a complex feature, a workaround is not possible. First we need to support variable row height to be able to add the master/detail row.

**Comment by arheinjohnson** [comment]
Okay, if I need something usable now, should we not go with data grid?

**Comment by Spylon** [comment]
I am attempting to implement a workaround using Dialogs.  Has anyone else tried this?

**Comment by flaviendelangle** [comment]
@arheinjohnson not currently
When we will be working on it, we will have a branch published like on every PR. 
That's something we could clarify for this kind of large feature, in order to have quick feedback with people willing to spend time testing it before the release.

**Comment by AKCodez** [comment]
As a purchaser of the Data Grid Pro component, I would love to have this feature!

**Comment by kpotter-m2** [comment]
> As a purchaser of the Data Grid Pro component, I would love to have this feature!

Second this, currently we have to use the MUI Table component & create most of what DataGridPro already does ourselves. Would be great if it had this feature so that we can move over to using DataGrid instead.

**Comment by stamahto** [comment]
This function would be highly appreciated.

**Comment by dansoftwares24** [comment]
I can't believe the pro version doesn't still have this feature. It's one of the most important ones! The team has to think about it.
