### ISSUE TITLE
[DataGrid] Single select column type not filtering with number values

### ISSUE THREAD

**Issue by Manny651** [mui-org/material-ui-x#2111]
- [x ] The issue is present in the latest release.
- [x ] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The 'singleSelect' filters everything when the column values are numbers. The valueOptions are specified as objects: [{label:"One", value:1}, {label:"Two", value: 2}]

## Expected Behavior 🤔

Should work like an equal filter.

**Comment by m4theushw** [comment]
Reproduction: https://codesandbox.io/s/material-demo-forked-tfzbe?file=/demo.js

Try to filter for any country, nothing is shown.
