### ISSUE TITLE
[DataGridPro] Implement Row Grouping by Column

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#212]
### Benchmark

- https://www.ag-grid.com/javascript-grid-grouping/
- https://material-table.com/#/docs/features/grouping
- https://www.telerik.com/kendo-react-ui/components/grid/grouping/
- https://ej2.syncfusion.com/react/demos/#/material/grid/aggregate-group
- https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/grouping/
- http://tabulator.info/docs/4.5/group
- https://www.infragistics.com/products/ignite-ui-react/react/components/data-grid-row-grouping.html
- https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--grouping
- https://adazzle.github.io/react-data-grid/docs/examples/basic-grouping

**Comment by dannycochran** [comment]
@oliviertassinari a style I think could be quite nice, if it meets the material spec, would be more like Airtable:

https://support.airtable.com/hc/en-us/articles/221747587-Guide-to-grouped-records

The groups are nested with borders around them.

**Comment by oliviertassinari** [comment]
@dannycochran Airtable seems to be a great source of inspiration for the UX, we are basing the filtering on it. They have some traffic, quite a lot, even if [negligeabled](https://www.similarweb.com/website/docs.google.com/?competitors=airtable.com) compare to the Google docs suite.

**Comment by vizardkill** [comment]
This functionality will be within the pro plan?

**Comment by oliviertassinari** [comment]
@vizardkill No, the Premium one: https://material-ui.com/components/data-grid/getting-started/#feature-comparison

**Comment by labgab** [comment]
how can you speed up the development of this functionality?

**Comment by flaviendelangle** [comment]
I will start working on the foundations of the tree structure soon.
We are currently doing some changes in our architectures to be able to do it as soon as possible.

**Comment by peterfarina** [comment]
Very exciting to see action on this issue yesterday, @oliviertassinari! Looks like @flaviendelangle is hard at work on this specific feature.

We're launching a new internal app shortly — currently in the final stages of design, now moving to prototyping — and this feature is crucial for our team's desired workflow.

I look forward to purchasing the Premium Plan as soon as it's available. Keep up the great work.

**Comment by flaviendelangle** [comment]
The MVP of the feature is advancing fine.
A [first version of the documentation](https://deploy-preview-3277--material-ui-x.netlify.app/components/data-grid/group-pivot/#row-grouping) is online is you want to take a look.
I am interested in feedbacks if some features are missing, but keep in mind that it is a first version and that I won't implement everything in it to avoid delaying to release to much (for instance the children lazy loading will come later).

This feature is part of the Premium Plan, but as this plan is not available yet (see #3135 for more details on that topic), we will release a beta version on the Pro Plan.
I can't give a release date yet, the Q4 target may be hard to achieve, but I hope we will be ready in the first weeks of January.

**Comment by flaviendelangle** [comment]
https://github.com/mui-org/material-ui-x/issues/212#issuecomment-725618155

To answer this comment
I did not implement this kind of UI. But with #2144 and heavy customization, we should be able to approach it.

**Comment by petivagyok16** [comment]
So you added the treeData in the pro, but you add a feature to it (groupingField) in premium?
At least I'm trying to group rows by one column (lets call it name), and it is even shown in the documentation that it's possible to group by a certain column:
[](https://github.com/mui/mui-x/blob/v6.11.2/docs/data/data-grid/tree-data/TreeDataFullExample.tsx#L9)

Problem is that it does not work...

**Comment by flaviendelangle** [comment]
The Row Grouping is not a feature of the Tree Data, it is a distinct features that answers different use cases.
