### ISSUE TITLE
[XGrid] Resized column state is lost when resizing column or viewport and at least on column has flex enabled

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#2129]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

https://user-images.githubusercontent.com/3165635/125062727-01430480-e0af-11eb-871f-131328f4e3f6.mp4

https://codesandbox.io/s/material-demo-forked-ch5hy?file=/demo.tsx

## Expected Behavior 🤔

https://user-images.githubusercontent.com/3165635/125063170-70b8f400-e0af-11eb-857f-7482d4f28a6f.mp4

https://plnkr.co/edit/VO2y32CCitTxbgar

## Steps to Reproduce 🕹

See above actual behavior

## Context 🔦

Found when working on #1850

## Your Environment 🌎

@material-ui/x-grid@v4.0.0-alpha.33

**Comment by flaviendelangle** [comment]
I think it is due to the `flex: 1` on the ID column.
Even without resizing the grid. If you resize a column and then try to resize it again, the ID column resets.

As soon as `updateColumnsWidth` is run, the flex columns width are recomputed to fit the width of the viewport.

**Comment by flaviendelangle** [comment]
Following on https://github.com/mui-org/material-ui-x/issues/2174#issuecomment-884487285

I remove the "waiting for :+1: " because it totally break the resize of the columns as soon as we have one flex column which is a bug important enough to fix it I think.

**Comment by oliviertassinari** [comment]
Ok, fair enough. The reason I added "waiting for upvotes" is that I assumed that end-users rarely resize their browser window. Now, the problem also triggers if the layout of the page changes, when for instance a drawers open.

**Comment by flaviendelangle** [comment]
https://github.com/mui-org/material-ui-x/issues/2129#issuecomment-878280780 it's this issue that is the most problematic for me
It's exactly the same cause as the one in your first message (= we rerun the flex allocation script whenever we want to update a column width). But it causes the resize column feature to be unusable whenever there is a flex column in the table.

The may have been better for me to open a separate issue and link the two.

**Comment by DanailH** [comment]
How would one handle that case? If I resize a column that is a `flex` column can we assume that I want to control the grid myself and I don't want to have `flex` columns at all?

If that is the case then we can simply remove the `flex` from all of the `colDef`'s even if one column is resized.

**Comment by flaviendelangle** [comment]
In #2181 , I'm removing the `flex` property of the column being resized and setting its `width` and `computedWidth` to be equal to the width of the resize process.

We could do the same for every column, as long as we update correctly the `width` of each column. But I'm not sure it has benefits over letting them as is.

**Comment by DanailH** [comment]
Actually wouldn't #2181 fix the issue? We are essentially changing the functonality. If you resize the flex is stopped.

**Comment by flaviendelangle** [comment]
#2181 is fixing this issue

But it won't be merged (see https://github.com/mui-org/material-ui-x/pull/2181#discussion_r676202491)

The new PR #2235 fixes the bug (you can resize a flex column) but the behavior is not optimal. I think that removing the `flex` from the resized columns is still interesting.
It was done in #2181 and should be done properly in a following PR.

**Comment by oliviertassinari** [comment]
I have updated the reproduction with the latest version v4.0.0-alpha.36: https://codesandbox.io/s/material-demo-forked-o4rs7?file=/demo.tsx, same issue

**Comment by flaviendelangle** [comment]
That's weird, I thought #2235 was doing a better job at fixing it.
But I'll do a PR with the last pieces of #2181 to remove the flex property when we start resizing :+1:

**Comment by Haaxor1689** [comment]
Is this supposed to be fixed? I'm on `4.0.0-alpha.37` and it still doesn't work as expected.

**Comment by Haaxor1689** [comment]
Same as the original reported issue

**Comment by Haaxor1689** [comment]
So it seems to be fixed. It was some react-scripts caching issue that did not rebuild the package correctly after upgrading until I deleted whole node_modules.
