### ISSUE TITLE
[XGrid] The header looses alignment during reordering

### ISSUE THREAD

**Issue by mindtraveller** [mui-org/material-ui-x#2132]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

the header is not aligned to the data cell when during the reordering of a column from the right end of the scrollable area to leave the scrollable area and release the dragged column there.

## Expected Behavior 🤔

The header remains aligned with the data cells.

## Steps to Reproduce 🕹

Steps:

1. Scroll the table to the right
2. Drag column
3. Scroll a couple of column to the left
4. Leave the scrollable area with that column being dragged
5. Released the column
6. Scroll to the right -- there should be misalignment with the data cells.

The steps are shown at the GIF from https://material-ui.com/components/data-grid/columns/#column-reorder (use the example on the page itself instead of codesandbox):
![example_of_issue](https://user-images.githubusercontent.com/11229620/125289777-49b92700-e328-11eb-9131-a259d1c98c23.gif)

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  System:
    OS: macOS 11.4
  Binaries:
    Node: 14.15.3 - ~/.asdf/installs/nodejs/14.15.3/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.14.9 - ~/.asdf/installs/nodejs/14.15.3/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Edge: Not Found
    Firefox: 87.0
    Safari: 14.1.1
  npmPackages:
    @material-ui/core: 4.11.1 => 4.11.1 
    @material-ui/icons: 4.5.1 => 4.5.1 
    @material-ui/lab: 4.0.0-alpha.56 => 4.0.0-alpha.56 
    @material-ui/pickers: 3.1.2 => 3.1.2 
    @material-ui/styles: 4.11.1 => 4.11.1 
    @material-ui/system:  4.11.3 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @types/react:  17.0.0 
    react: 16.12.0 => 16.12.0 
    react-dom: 16.12.0 => 16.12.0 
    typescript: 4.2.3 => 4.2.3 

  Browser:
    Google Chrome Version 91.0.4472.114

```
</details>

**Comment by oliviertassinari** [comment]
For people that need to revert, it was behaving correctly in v4.0.0-alpha.30: https://codesandbox.io/s/material-demo-forked-btylq?file=/demo.tsx. As far as I know, the regression is coming from #1720. To be more precise, this diff is wrong, it's not equivalent:

https://github.com/mui-org/material-ui-x/pull/1720/files#diff-7904e8c986f79f8bbc1627613039ba9fc46cc3f000aef6b4883c56f4aff2311aR419
