### ISSUE TITLE
[DataGrid] Header is not scrollable when all items are filtered out

### ISSUE THREAD

**Issue by mindtraveller** [mui-org/material-ui-x#2133]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

It's not possible to scroll a table when all items are filtered out and there are a lot of columns so that horizontal scroll is shown.

## Expected Behavior 🤔

I'd expect the header is scrollable nevertheless. At least you can see what column has filtering applied on.

## Steps to Reproduce 🕹

Steps:

1. Go to this table https://material-ui.com/components/data-grid/filtering/#customize-the-filters
2. Open filtering and select any column which is not visible without scrolling to the right
3. Apply a filter to filter all items out e.g. Country is Andorra
4. Now it's not possible to scroll the table

See the GIF example: 
![Jul-12-2021 16-43-34](https://user-images.githubusercontent.com/11229620/125298065-812bd180-e330-11eb-9060-f8ac3234bd8b.gif)

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
 System:
    OS: macOS 11.4
  Binaries:
    Node: 14.15.3 - ~/.asdf/installs/nodejs/14.15.3/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.14.9 - ~/.asdf/installs/nodejs/14.15.3/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Edge: Not Found
    Firefox: 87.0
    Safari: 14.1.1
  npmPackages:
    @material-ui/core: 4.11.1 => 4.11.1 
    @material-ui/icons: 4.5.1 => 4.5.1 
    @material-ui/lab: 4.0.0-alpha.56 => 4.0.0-alpha.56 
    @material-ui/pickers: 3.1.2 => 3.1.2 
    @material-ui/styles: 4.11.1 => 4.11.1 
    @material-ui/system:  4.11.3 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @types/react:  17.0.0 
    react: 16.12.0 => 16.12.0 
    react-dom: 16.12.0 => 16.12.0 
    typescript: 4.2.3 => 4.2.3 

  Browser:
    Google Chrome Version 91.0.4472.114
```
</details>

## Order id 💳

#27213

**Comment by oliviertassinari** [comment]
It was working in v4.0.0-alpha.23: https://codesandbox.io/s/material-demo-forked-yyt1x?file=/index.js.
