### ISSUE TITLE
Minor mistake in the DataGrid Controlled selection example

### ISSUE THREAD

**Issue by evermake** [mui-org/material-ui-x#2134]
I think there is a mistake in [this example](https://material-ui.com/components/data-grid/selection/#controlled-selection).
Instead of:
```jsx
<DataGrid
  checkboxSelection
  onSelectionModelChange={(newSelectionModel) => {
    setSelectionModel(newSelectionModel);
  }}
  selectionModel={selectionModel}
  {...data}
/>
```

Should be:

```jsx
<DataGrid
  checkboxSelection
  onSelectionModelChange={(newSelectionModel) => {
    setSelectionModel(newSelectionModel.selectionModel);
  }}
  selectionModel={selectionModel}
  {...data}
/>
````

Because _newSelectionModel_ is type of GridSelectionModelChangeParams which is equals to:

```jsx
{
    /**
     * The set of rows that had their selection state change.
     */
    selectionModel: GridRowId[];
}
```

Even if you run this example on CodeSandbox it will be crashed.

**Comment by ZeeshanTamboli** [comment]
The demo docs code was changed in PR #1823 which is not yet released but the docs were released I think from master.

**Comment by oliviertassinari** [comment]
@ZeeshanTamboli Thanks for raising, weird for some reason, the docs were released. I look like me and @m4theushw pushed on this branch. I can't remember why I did. I have reverted the branch.
