### ISSUE TITLE
Does not build with typescript

### ISSUE THREAD

**Issue by mrvisser** [mui-org/material-ui-x#2135]
When building, I get this error:

`Module not found: Can't resolve '@material-ui/styles' in '/Source/project/node_modules/@material-ui/data-grid/dist'`

Sure enough in the dist/index files, it tries to import makeStyles from `@material-ui/styles`. But I'm using `@material-ui@next`, and that's not a core dependency, and data-grid doesn't list @material-ui/styles as a dependency.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The build fails with this error:

`Module not found: Can't resolve '@material-ui/styles' in '/Source/project/node_modules/@material-ui/data-grid/dist'`

## Expected Behavior 🤔

The build should succeed.

## Steps to Reproduce 🕹

Steps:

Here are my versions:

```
    "@emotion/react": "^11.4.0",
    "@emotion/styled": "^11.3.0",
    "@material-ui/core": "^5.0.0-beta.0",
    "@material-ui/data-grid": "^4.0.0-alpha.33",
    "@material-ui/icons": "^4.11.2",
    "@types/react": "^17.0.14",
    "@types/react-dom": "^17.0.9",
    "@types/react-router-dom": "^5.1.8",
    "@types/react-transition-group": "^4.4.2",
```

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
npx: installed 2 in 7.679s

  System:
    OS: macOS 11.3.1
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.4/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Edge: 91.0.864.67
    Firefox: 89.0.2
    Safari: 14.1
  npmPackages:
    @emotion/react: ^11.4.0 => 11.4.0
    @emotion/styled: ^11.3.0 => 11.3.0
    @material-ui/core: ^5.0.0-beta.0 => 5.0.0-beta.0
    @material-ui/data-grid: ^4.0.0-alpha.33 => 4.0.0-alpha.33
    @material-ui/icons: ^4.11.2 => 4.11.2
    @material-ui/private-theming:  5.0.0-beta.0
    @material-ui/styled-engine:  5.0.0-beta.0
    @material-ui/system:  5.0.0-beta.0
    @material-ui/types:  6.0.1
    @material-ui/unstyled:  5.0.0-alpha.39
    @material-ui/utils:  5.0.0-beta.0
    @types/react: ^17.0.14 => 17.0.14
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript:  4.3.5
```
</details>

**Comment by TheTisiboth** [comment]
From what I [read](https://github.com/mui-org/material-ui-x/issues/441), it seems that DataGrid is not compatible with MUI 5

**Comment by mrvisser** [comment]
@TheTisiboth The docs say it's supported: https://next.material-ui.com/components/data-grid/

> The data grid components are supporting v5 and v4.

The link you provided led me to https://github.com/mui-org/material-ui-x/issues/1234, which is the same issue labelled as a bug. I didn't find that while searching.

Going to close this as, it's a duplicate.

**Comment by oliviertassinari** [comment]
Duplicate of #1234
