### ISSUE TITLE
Placing controlled input field in custom toolbar doesn't work

### ISSUE THREAD

**Issue by Suroor-Ahmmad** [mui-org/material-ui-x#2145]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
Unable to focus the input field

## Expected Behavior 🤔
Should be able to type and search with-in table data

## Steps to Reproduce 🕹

Steps:
https://codesandbox.io/s/festive-lalande-qxf3c?file=/src/Demo.tsx

## Context 🔦
I'm trying to implement global filter for datagrid but I'm not able to focus the input field, I know it has something to do with state hook, any help to implement this will be appreciated.

(I know there's already issue created in MUI-X [#202](https://github.com/mui-org/material-ui-x/issues/202). I'm just trying to implement this my own)

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  npx: installed 2 in 26.112s

  System:
    OS: Windows 7 6.1.7601
  Binaries:
    Node: 12.22.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 91.0.4472.124
  npmPackages:
    @material-ui/core: ^4.11.4 => 4.11.4
    @material-ui/data-grid: ^4.0.0-alpha.32 => 4.0.0-alpha.32
    @material-ui/icons: ^4.11.2 => 4.11.2
    @material-ui/pickers:  3.2.2
    @material-ui/styles:  4.11.4
    @material-ui/system:  4.11.3
    @material-ui/types:  5.1.0
    @material-ui/utils:  5.0.0-alpha.35
    @types/react: ^17.0.6 => 17.0.6
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    styled-components: ^5.3.0 => 5.3.0
    typescript: ^4.2.4 => 4.2.4
```
</details>

**Comment by Suroor-Ahmmad** [comment]
> It works fine when you pass props to `SearchBar` via `componentsProps`:
> 
> ```js
> components={{ Toolbar: SearchBar }}
> componentsProps={{
>   toolbar: {
>     value: searchText,
>     onChange: (searchVal: string) => requestSearch(searchVal),
>     onCancelSearch: () => cancelSearch()
>   }
> }}
> ```
> 
> See the [updated demo](https://codesandbox.io/s/exciting-neumann-026yo?file=/src/Demo.tsx).

Provided I have only `SearchBar` in the toolbar? It doesn't work if I want to retains Column Select, Filters and Exports in toolbar

**Comment by dtassone** [comment]
@Suroor-Ahmmad few issues in your code. I have refactored it to a working example 
https://codesandbox.io/s/datagrid-searchbar-1ugpl?file=/src/Demo.tsx
