### ISSUE TITLE
Do You Have Any Examples of Loading DataGrid with External Data?

### ISSUE THREAD

**Issue by jarfer** [mui-org/material-ui-x#2147]
Hi,

I've had a little trouble loading external data into the DataGrid component and knowing how best to do this (with it being asynchronous and yet the data for the DataGrid needing to be in the state on initialisation of the component to prevent an error)

Do you have an example of how this can best be done?

The examples I found on the website work fine, but only with hard coded data in the actual component itself, which avoids this issue

Many thanks for any advice!

**Comment by dtassone** [comment]
You can initialise the grid rows with `[]` in your state and call a setState once your server returns the response.
http://localhost:3001/components/data-grid/rows/#feeding-data

You can also check the link below which could be used to load data in batch or streaming.
https://material-ui.com/components/data-grid/rows/#apiref
