### ISSUE TITLE
[DataGrid]  Can't resolve '@material-ui/styles' in '...\node_modules\@material-ui\data-grid\dist'

### ISSUE THREAD

**Issue by 3hson** [mui-org/material-ui-x#2153]
hi. i'm getting this error 

Failed to compile
./node_modules/@material-ui/data-grid/dist/index-esm.js
Module not found: Can't resolve '@material-ui/styles' in 'C:\apps\arvand-panel\node_modules\@material-ui\data-grid\dist'

using [this example ](https://material-ui.com/components/data-grid/#mit-version)

with 

"@material-ui/core": "next",
"@material-ui/data-grid": "^4.0.0-alpha.33",

**Comment by oliviertassinari** [comment]
@3hson You need to install `@material-ui/core@next`. We will solve the root cause in #1234.
