### ISSUE TITLE
[DataGrid] Export selected rows

### ISSUE THREAD

**Issue by mindtraveller** [mui-org/material-ui-x#2156]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

We'd like to have the ability to export only selected rows instead of the whole set of rows.

## Motivation 🔦

Sometimes it's required to export part of the data, filtering might help, but can be a bit complex for that use case. So selecting and exporting desired entries is a better option here.

## Order id 💳

#27213

**Comment by m4theushw** [comment]
If you <kbd>CTRL</kbd> + <kbd>c</kbd> in the grid it will only copy the selected rows to the clipboard. The format of the exported data is the same of when using the Export button, but using the TAB delimiter which is perfect to paste in Excel. 

To solve this issue, we could display an "Export selection" option in the Export menu when there's one or more rows selected.

**Comment by mindtraveller** [comment]
@m4theushw 'export selection' would be perfect. API support is expected as well.

**Comment by oliviertassinari** [comment]
Would this API make sense?

```diff
diff --git a/packages/grid/_modules_/grid/models/gridExport.ts b/packages/grid/_modules_/grid/models/gridExport.ts
index f7d1bd88..1f683778 100644
--- a/packages/grid/_modules_/grid/models/gridExport.ts
+++ b/packages/grid/_modules_/grid/models/gridExport.ts
@@ -17,6 +17,10 @@ export interface GridExportCsvOptions {
    * @default `document.title`
    */
   fileName?: string;
+  /**
+   * If `true`, only the selected rows are exported.
+   * @default false
+   */
+  onlySelected?: boolean,
   /**
    * If `true`, the UTF-8 Byte Order Mark (BOM) prefixes the exported file.
    * This can allow Excel to automatically detect file encoding as UTF-8.
```

A new prop for `GridExportCsvOptions`.

But if we have pagination enabled, should it only include the current page or all the pages? So maybe we should target larger instead, and add a `rowFilter` prop to let the developers decide what to do.

**Comment by mindtraveller** [comment]
@oliviertassinari If this question is to me, then for sure such setting (`onlySelected`) is fine, but `rowFilter` is more powerful.
Regarding pagination - not sure how it works now, does it preserve selected items between page changes? if so - I'd expect them to be exported.

**Comment by flaviendelangle** [comment]
It's already the current behavior 
https://github.com/mui-org/material-ui-x/blob/master/packages/grid/_modules_/grid/hooks/features/export/serializers/csvSerializer.ts#L57

But it's buggy because of the casting to string.
I'm doing a fix :+1: 

We could add a `rowFilter` callback later to override all the default behaviors and let the user decide what to export.

**Comment by flaviendelangle** [comment]
https://user-images.githubusercontent.com/3309670/127471017-f4d212f6-e985-4e14-9daa-5b593626cb12.mp4

The current behavior (with the fix)

**Comment by flaviendelangle** [comment]
https://user-images.githubusercontent.com/3309670/127471672-a8bb2840-df9b-48d9-add7-bed5d4e9736e.mp4

The current behavior with the fix

@mindtraveller is it what you expected ?

**Comment by mindtraveller** [comment]
@flaviendelangle seems like it is. Just ensure that it's available in type definitions of API

**Comment by flaviendelangle** [comment]
It does not appear in the type definitions of the API since it's the default behavior, not something you can enable / disable through an option.

I'll add a description in the docs though

**Comment by georgesglynn** [comment]
@flaviendelangle @oliviertassinari Hey y'all! I ran into an issue for my customers where if they have one row selected and they choose to export to csv, only that one selected row is exported instead of all rows on the screen.

I see @flaviendelangle mentioned this functionality is not something you can enable/disable. Is there anyway of hacking this so that the CSV export always ignores the selected rows? 

The only way I was able to get it to work this way was by physically editing the "selectedRowIds" variable in the compiled code in my node_modules folder to always point to an empty list rather than the actual selected rows. Obviously this is not a long term solution as our node_modules folder is built dynamically when deploying.

I am currently using x-data-grid-pro@4.0.0.

**Comment by flaviendelangle** [comment]
There is currently no option to export all rows like there is for `allColumns`.
You could provide a custom Toolbar and copy / paste all the CSV logic but it will be heavy.

We can easily add the ability to pick the rows to export, but it will only available in v5, v4 is to outdated for feature improvements now :+1:

**Comment by toinhao1** [comment]
I don't see the option to disable or enable the exporting of selected rows or all rows in the docs. 

Was this implemented in V5?

I only see that I would have to get all of the rows and then pass them to the exporter if I want to accomplish this.

**Comment by toinhao1** [comment]
Exactly, so this is the only way?

It seems like a flag of onlySelected?: boolean would make this much simpler. 

I want to always export all rows.

**Comment by flaviendelangle** [comment]
That's your specific use case
But some want to export the current page, other want to export the select rows, etc...
We could have to add lots of flags.
In the end a single api seems much simpler to me.

**Comment by toinhao1** [comment]
I'll use your previous suggestion. I appreciate the prompt response. Thanks.

**Comment by Qadir134** [comment]
> @flaviendelangle @oliviertassinari Hey y'all! I ran into an issue for my customers where if they have one row selected and they choose to export to csv, only that one selected row is exported instead of all rows on the screen.
> 
> I see @flaviendelangle mentioned this functionality is not something you can enable/disable. Is there anyway of hacking this so that the CSV export always ignores the selected rows?
> 
> The only way I was able to get it to work this way was by physically editing the "selectedRowIds" variable in the compiled code in my node_modules folder to always point to an empty list rather than the actual selected rows. Obviously this is not a long term solution as our node_modules folder is built dynamically when deploying.
> 
> I am currently using x-data-grid-pro@4.0.0.

have you find out the solution for this ?

**Comment by romgrk** [comment]
See https://github.com/mui/mui-x/pull/10084
