### ISSUE TITLE
[XGrid] How do I use columnHeaderDragStart and columnHeaderDragEnd

### ISSUE THREAD

**Issue by tfcb93** [mui-org/material-ui-x#2158]
Sorry if it's a silly question, but I want to use both columnHeaderDragStart and columnHeaderDragEnd events, and I don't know how can I use it.
My idea is identify a certain column and disable the column reorder of the Xgrid. I have certain columns that I want to allow reorder and others that I don't. If there is another way of do it without using columnHeaderDragStart and columnHeaderDragEnd I appreciate as well.

**Comment by m4theushw** [comment]
The ability to disable reordering of a specific column is being implemented in #2085. About how to use events you can check this page: https://material-ui.com/components/data-grid/events. However, there's no way to prevent column reordering using events. I'll close this issue and you can follow the PR to know when it gets released
