### ISSUE TITLE
[DataGrid] Introduce `maxWidth` in `GridColDef`

### ISSUE THREAD

**Issue by DanailH** [mui-org/material-ui-x#2174]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

A follow-up issue based on this comment https://github.com/mui-org/material-ui-x/pull/2101

The goal is to provide an option for developers to have full control over the width of a column by supporting `minWidth`, `maxWidth`, and `width`. `maxWidth`. This prop would be primarily targeted to work with the flex functionalities. We would also have to consider how the combination with column resize should happen.

**Comment by flaviendelangle** [comment]
@DanailH do you plan to do it this week ?
I have a refacto of `useGridColumns` coming (I haven't started yet) but if you want to do yours soon I'll wait.

**Comment by DanailH** [comment]
Not really, I don't think it is a priority for now. I created it just so that we don't forget about it.

**Comment by oliviertassinari** [comment]
I have added the "waiting for 👍" so we can gather feedback. The label is meant to signal the community that if they want the problem to be worked on it, they have to demonstrate that it is worth our time. So yeah, let's not work on any of these issues as long as the label is in. I also that we should motivate why we remove the label (enough upvotes, a new feedback, etc.)

**Comment by oliviertassinari** [comment]
Based on the request in https://github.com/mui-org/material-ui-x/issues/1241#issuecomment-994216659

> We are using the data grid with the flex  set on each column.  We have a Boolean column and a long description column.   The flex works ok on a laptop, but our client has ultra wide monitors and the Boolean column stretches out too far.  We need to be able to set a max width for this column to maximise the area for the description column.
