### ISSUE TITLE
[DataGrid] ArrowUp jumps

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#2178]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

https://user-images.githubusercontent.com/3165635/126049490-d3dcc6de-5772-44fd-b431-adce1ba1e1d5.mp4

Jumps when using <kbd>Arrow Left</kbd> or <kbd>Arrow Up</kbd>.

## Expected Behavior 🤔

No jumps when using <kbd>Arrow Left</kbd> or <kbd>Arrow Up</kbd>.

## Steps to Reproduce 🕹

Steps:

1. Open https://master--material-ui-x.netlify.app/components/data-grid/#commercial-version

## Context 🔦

https://github.com/mui-org/material-ui-x/pull/2162

The `.focus()` call for the new active cell wrecks the correct scroll position that `apiRef.current.scrollToIndexes()` tries to set. You can also notice it in the other direction when using <kbd>Arrow Up</kbd>.

I didn't look into how to solve this. It might be a timing issue, the browser auto-scroll when focusing an element off-screen, so maybe we need to force a layout computation when we change the scroll, no idea. I will open a new GitHub issue, the current UX is not great.

For some reason <kbd>Arrow Right</kbd> and <kbd>Arrow Down</kbd> works without any issue.

## Your Environment 🌎

~v4.0.0-alpha.34~ v4.0.0-alpha.33

**Comment by m4theushw** [comment]
This is working correctly in the latest release.
