### ISSUE TITLE
[DataGrid] Leaking MUI 5 Errors

### ISSUE THREAD

**Issue by emily-ellevation** [mui-org/material-ui-x#2184]
Hello! We're using the DataGrid at 4.0.0-alpha.29 and starting to see console errors that are seemingly related to the release of v5. Many of our errors seem to originate from the styles package despite it being on `4.11.4`. Initially we started seeing errors about `createMuiTheme` being deprecated to `createTheme`. I'm wondering where in the dependency graph these are introduced so that we might lock whatever we can to stay in a stable state until ready to upgrade to 5. 
I understand this is an alpha package and it may not be reasonable to expect it to be airtight in this way but want to see if there's anything I'm missing to mitigate these issues.

I've seen https://github.com/mui-org/material-ui-x/issues/2106 and https://github.com/mui-org/material-ui-x/issues/2142 but I'm seeing additional warnings.

When running code:
<img width="543" alt="Screen Shot 2021-07-21 at 4 49 43 PM" src="https://user-images.githubusercontent.com/52083969/126558745-d7122005-c63d-4a69-9fe7-549afe9855f6.png">

When running tests:
<img width="856" alt="Screen Shot 2021-07-21 at 5 04 53 PM" src="https://user-images.githubusercontent.com/52083969/126560214-39f923f3-4c24-464a-9c37-1fb7a28d4d7c.png">
<img width="1126" alt="Screen Shot 2021-07-21 at 5 07 41 PM" src="https://user-images.githubusercontent.com/52083969/126560316-ab307483-6e1f-4aad-836d-9fbbe41a8640.png">

Could these be related to the dependence on MUI utils package @ 5?
<img width="783" alt="Screen Shot 2021-07-21 at 3 53 51 PM" src="https://user-images.githubusercontent.com/52083969/126558684-12bb4b2b-d1a6-431f-9a22-6c78cfde88ac.png">

Thanks so much, excited to get going with v5!

- [ ] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce 🕹

Steps:

1.
2.
3.
4.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
Do you still see any warning using the last alpha version? v4.0.0-alpha.34 was released yesterday to fix support with v4.

**Comment by oliviertassinari** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://material-ui.com/r/issue-template) _may_ be a good starting point. Thank you!

**Comment by oliviertassinari** [comment]
@emily-ellevation you need to upgrade to use v4.0.0-alpha.34.

**Comment by emily-ellevation** [comment]
@m4theushw @oliviertassinari upgrading to .34 resolved all errors except for 
<img width="983" alt="Screen Shot 2021-07-26 at 9 59 42 AM" src="https://user-images.githubusercontent.com/52083969/127029093-549dfa80-6d2d-44b1-81e7-f31df98aa0d8.png">

Thanks so much for the speedy resolution of this issue. While the above may be a 'leaking' error, for our purposes we can resolve by changing our internal component that wraps `<Grid>` to use `justifyContent`

**Comment by m4theushw** [comment]
This warning is coming from the Grid component, not the DataGrid.

**Comment by emily-ellevation** [comment]
> This warning is coming from the Grid component, not the DataGrid. You need to upgrade the core package.

Ah I missed https://github.com/mui-org/material-ui/pull/24078/files in 4.12 of the main pkg -- thank you!
