### ISSUE TITLE
[docs] Explain that valueFormatter can be used in the CSV export

### ISSUE THREAD

**Issue by fedyunin** [mui-org/material-ui-x#2185]
### How to Export to CSV if column value has custom format 

Hello! Probably this is wrong place for my issue. Please refer me right place for it.

I use XGrid. For some columns in my table I have custom value: object: e.g {a:200,b:400}.
I use renderCell for render these custom values - Drawing simple chart.

When I export data as csv I got for these columns next value, example:

`Name,Description,[object Object]`

This is reasonable because csvSerializer just not process this case:

```
const serialiseCellValue = (value: any, delimiterCharacter: GridExportCsvDelimiter) => {
  if (typeof value === 'string') {
    const formattedValue = value.replace(/"/g, '""');
    return formattedValue.includes(delimiterCharacter) ? `"${formattedValue}"` : formattedValue;
  }
  return value;
};
```

Is there way to setup CSV export for such case. E.g provide some exportFormatter function?

Thanks!

**Comment by m4theushw** [comment]
Yes, you can provide a [`valueFormatter`](https://material-ui.com/components/data-grid/columns/#value-formatter) to the `GridColDef`. It's applied to the CSV export too.

```jsx
<DataGrid
  rows={rows}
  columns={[
    {
      renderCell: () => ...,
      valueFormatter: (params) => {
        return params.value.foo;
      },
    },
  ]}
/>
```

I added the "docs" label because it's the second or third time we see this request. It's time to add a note in https://material-ui.com/components/data-grid/export/#csv-export.

**Comment by fedyunin** [comment]
Yes I use valueFormatter. But it not affect to export. I still getting [object Object] in the csv file.

I checked **serialiseCellValue** and not see that formattedValue used. (this value produces valueFormatter)

**Comment by oliviertassinari** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://material-ui.com/r/issue-template) _may_ be a good starting point. Thank you!

**Comment by fedyunin** [comment]
I added example here: https://codesandbox.io/s/damp-cookies-s5xtu?file=/src/Demo.tsx

**Comment by m4theushw** [comment]
Your `valueFormatter` has to return a string or number, not an element. 

We should update the `GridColDef` definition to not allow `JSX.Element` inside the value formatter.

**Comment by fedyunin** [comment]
Yes right. I noticed this and updated my value formatter.

**Comment by fedyunin** [comment]
I found my mistake. I used old Xgrid version - 4.0.0-aplha.28!
In the Codesandbox I use latest dependencies versions. So it works fine.
Now updated libs in my project, so now it works!

Thanks!

**Comment by oliviertassinari** [comment]
> Your valueFormatter has to return a string or number, not an element.

> We should update the GridColDef definition to not allow JSX.Element inside the value formatter.

Same as https://github.com/mui-org/material-ui-x/issues/1363#issuecomment-821969779
