### ISSUE TITLE
[DataGrid] The `api` property passed on event publication / callbacks should always contain the `apiRef.current`, never `apiRef`

### ISSUE THREAD

**Issue by flaviendelangle** [mui-org/material-ui-x#2189]
Follow up #2187 

- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

The `api` property passed on event publication / callbacks should always contain the `apiRef.current`.

## Examples 🌈

Currently, depending on which callback we are looking at, the `api` key can contain either the `apiRef` or the `apiRef.current`.

Sometimes, we give it `apiRef`

```ts
apiRef.current.publishEvent(GRID_COLUMN_VISIBILITY_CHANGE, {
  field,
  colDef: updatedCol,
  api: apiRef,
  isVisible,
});
```

Sometimes, we give it `apiRef.current`

```ts
const editRowParams: GridEditRowModelParams = {
  api: apiRef.current,
  model: apiRef.current.getState().editRows,
};
apiRef.current.publishEvent(GRID_ROW_EDIT_MODEL_CHANGE, editRowParams);
```

I'm in favor of doing it before beta because if we want to unify (which would be interesting I think), then it's a breaking change.

**Comment by m4theushw** [comment]
The idea is to not pass the `api` in the params. It's reserved only to XGrid. In the features that are already using the `useGridControlState` hook it's not passed anymore.

**Comment by m4theushw** [comment]
Related to #1821

**Comment by flaviendelangle** [comment]
After migrating everything that we want to migrate to the `useGridControlState` hook, you think that their would be no callback with `apiRef` or `apiRef.current` ?

**Comment by dtassone** [comment]
> The idea is to not pass the `api` in the params. It's reserved only to XGrid. In the features that are already using the `useGridControlState` hook it's not passed anymore.

Todo this, you could check the license state refactored in #2176, and add a function in publishEvent that would filter it for you. I suggest finding a way to apply `params.api = undefined` transversally and not on the case by case basis. Otherwise, it won't scale and it would be much more prone to error

**Comment by DanailH** [comment]
This is no longer relevant. `ApiRef` is removed from all callbacks but the one inside `GridColDef`. To use it one must access it through the `details` argument of the callback. The `api` is only available for `DataGridPro`
