### ISSUE TITLE
[DataGrid] Specifying a filterModel prop when using singleSelect column throws fatal error

### ISSUE THREAD

**Issue by Ryshackleton** [mui-org/material-ui-x#2199]
In the DataGrid component, setting `filterModel` in combination with using a `singleSelect` typed column type causes the filter form to crash when the user tries to change the filter to a column with `type = 'singleSelect'`

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When setting the `filterModel`, the initial table filtering functions as expected, but when the user tries to change the filtered column to a column that is `singleSelect`, the table fails with a fatal error.

## Expected Behavior 🤔

Setting a `filterModel` prop with a `singleSelect` column should function similarly to all of the other column type (`string`, `number`, `date`, etc).

## Steps to Reproduce 🕹

Forked from the `singleSelect` demo from the MaterialUI docs:
https://codesandbox.io/s/material-demo-forked-078r2?file=/demo.js

Steps:

1. Using the three-dot menu or the filter icon, open the filter options dropdown
2. Change the "Column" field to the `country` field (which is a `singleSelect` column)
3. DataGrid throws an error ('t is not iterable or t is undefined' depending on browser).

## Context 🔦

I was trying to create a table containing multiple column filters with `singleSelect` and have the table retain its `filterModel` when changing between different views.

## Your Environment 🌎
 Using Chrome: 92.0.4515.107, also reproduced the error on FireFox.
<details>

  <summary>`npx @material-ui/envinfo`</summary>

```
  System:
    OS: macOS 11.4
  Binaries:
    Node: 14.12.0 - ~/.nvm/versions/node/v14.12.0/bin/node
    Yarn: Not Found
    npm: 6.14.8 - ~/.nvm/versions/node/v14.12.0/bin/npm
  Browsers:
    Chrome: 92.0.4515.107
    Edge: Not Found
    Firefox: 87.0
    Safari: 14.1.1
  npmPackages:
    @material-ui/core: ^4.11.3 => 4.11.3
    @material-ui/data-grid: ^4.0.0-alpha.34 => 4.0.0-alpha.34
    @material-ui/lab: ^4.0.0-alpha.60 => 4.0.0-alpha.60
    @material-ui/styles:  4.11.3
    @material-ui/system:  4.11.3
    @material-ui/types:  5.1.0
    @material-ui/utils:  4.11.2
    @types/react:  17.0.3
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
```
</details>

**Comment by DanailH** [comment]
Hi, @Ryshackleton thanks for reporting this. It seems to be a regression on the latest version of `4.0.0-alpha.34`. Reverting back to `4.0.0-alpha.33` solves the problem. We'll work on fixing the problem for the future version.

You can see it working here https://codesandbox.io/s/material-demo-forked-3jwkg?file=/demo.js

**Comment by Ryshackleton** [comment]
Thanks for the quick response @DanailH. Unfortunately I'm still getting the error in my application using the `alpha.33` version, but I can't seem to reproduce the issue in a smaller project. Even more strange is that I only get the error in production builds, but not developmen builds. I suppose I'll wait on a fix for this or re-implement what I've done using a different table component. Any idea which release these fixes might be targeted for?

**Comment by DanailH** [comment]
Hmm, that is interesting indeed. Ok, I'll check.

**Comment by DanailH** [comment]
@Ryshackleton Your reproduction uses `@material-ui/core: 5.0.0-beta.2` I must have missed that when I first look at the issue.
