### ISSUE TITLE
DataGrid onEditCellChangeCommitted: value is null if committed via mouse click to another cell

### ISSUE THREAD

**Issue by nikals99** [mui-org/material-ui-x#2202]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
When using the onEditCellChangeCommitted callback function for the DataGrid component and committing changes by clicking outside of the current cell the callback is not called correctly with the current cells value but with the value set to null. When committing the changes using enter or tab it works as expected. 

## Expected Behavior 🤔
onEditCellChangeCommitted should contain the current cells value when committing via mouse.

## Steps to Reproduce 🕹
Live demo is from the official [Column with valueGetter Example](https://codesandbox.io/s/o7f8m): 
[Link to codesandbox](https://codesandbox.io/s/o7f8m)

Steps:
Working example:
1. Change value of ```Full name``` in first row
2. Commit using enter

Not working:
1. Change value of ```Full name``` in first row
2. Commit by clicking outside of the current cell
3. Application crashes

## Context 🔦
I tried to commit changes by clicking outside of the current cell. This is especially needed when dealing with mobile devices since clicking outside of the current cell to commit something should be quite common there. 

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
I tested the issue with chrome and safari mobile
 System:
    OS: macOS 11.2.3
  Binaries:
    Node: 16.5.0 - /usr/local/bin/node
    Yarn: 1.1.0 - /usr/local/bin/yarn
    npm: 7.19.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.107
    Edge: Not Found
    Firefox: 66.0.3
    Safari: 14.0.3
  npmPackages:
    @material-ui/core: ^4.12.2 => 4.12.2 
    @material-ui/data-grid: ^4.0.0-alpha.34 => 4.0.0-alpha.34 
    @material-ui/lab: ^4.0.0-alpha.60 => 4.0.0-alpha.60 
    @material-ui/styles:  4.11.4 
    @material-ui/system:  4.12.1 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @types/react: ^17.0.0 => 17.0.14 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.1.2 => 4.3.5 
```
</details>

**Comment by pashidlos** [comment]
The same for `singleSelect` type, `props` is undefined after mouse click (works on Enter though) 
https://codesandbox.io/s/material-demo-forked-88w7x?file=/demo.tsx

**Comment by HashibulAmin** [comment]
Having the same problem. +1

**Comment by HashibulAmin** [comment]
@pashidlos how are you getting event as 2nd argument, as per documentation there is only params argument?

**Comment by HashibulAmin** [comment]
Same issue persist for Boolean and date, dateTime type column.

**Comment by DanailH** [comment]
Hi, @nikals99  thanks for reporting this. It seems to be a regression on the latest version of 4.0.0-alpha.34. Reverting back to 4.0.0-alpha.33 solves the problem. We'll work on fixing the problem for the future version.

You can see it working here https://codesandbox.io/s/material-demo-forked-uuoge?file=/demo.js

**Comment by m4theushw** [comment]
@pashidlos As a workaround you can [control the state](https://material-ui.com/components/data-grid/editing/#controlled-editing) and obtain the new value from the state. Here's an example:

```diff
diff --git a/docs/src/pages/components/data-grid/editing/ValueGetterGrid.tsx b/docs/src/pages/components/data-grid/editing/ValueGetterGrid.tsx
index 63c33bce..82720127 100644
--- a/docs/src/pages/components/data-grid/editing/ValueGetterGrid.tsx
+++ b/docs/src/pages/components/data-grid/editing/ValueGetterGrid.tsx
@@ -17,10 +17,10 @@ export default function ValueGetterGrid() {
   const [rows, setRows] = React.useState<any[]>(defaultRows);

   const handleCellEditCommit = React.useCallback(
-    ({ id, field, props }: GridEditCellPropsParams) => {
+    ({ id, field }: GridEditCellPropsParams) => {
       if (field === 'fullName') {
-        const data = props; // Fix eslint value is missing in prop-types for JS files
-        const [firstName, lastName] = data.value!.toString().split(' ');
+        const value = editRowsModel[id][field].value;
+        const [firstName, lastName] = value.toString().split(" ");
         const updatedRows = rows.map((row) => {
           if (row.id === id) {
             return { ...row, firstName, lastName };
```
