### ISSUE TITLE
[DataGrid] Editing a boolean value does not persist

### ISSUE THREAD

**Issue by CAVAh** [mui-org/material-ui-x#2206]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

In a cell that allows editing and that is of the boolean type, that is, it shows a checkbox, it is not changing the "state" when checking or unchecking the checkbox, after clicking outside the cell.

## Expected Behavior 🤔

When editing a boolean cell, change the state of the checkbox and click outside the cell, the value should continue with the state informed (before clicking outside the cell).

## Steps to Reproduce 🕹

Steps:

1. Go to [Sandbox](https://codesandbox.io/s/material-demo-forked-o42br?file=/demo.tsx)
2. Double Click on cell x or check.
![image](https://user-images.githubusercontent.com/5540350/126885916-fdb20f0d-143e-4dfe-8ac9-810c5d0bb1b8.png)
3. Invert value (if is checked, uncheck)
![image](https://user-images.githubusercontent.com/5540350/126885949-0d3d4e58-0823-4392-b968-1855eb3f00ad.png)
4. Click outside the cell

## Context 🔦

I am trying to do a Project Table where I can change Items from a Database.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.19.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 91.0.4472.164
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.55), ChromiumDev (93.0.957.0)
  npmPackages:
    @material-ui/core: ^4.12.2 => 4.12.2
    @material-ui/data-grid: ^4.0.0-alpha.34 => 4.0.0-alpha.34
    @material-ui/icons: ^4.11.2 => 4.11.2
    @material-ui/lab: ^4.0.0-alpha.60 => 4.0.0-alpha.60
    @material-ui/styles:  4.11.4
    @material-ui/system:  4.12.1
    @material-ui/types:  5.1.0
    @material-ui/utils:  4.11.2
    @types/react: ^17.0.0 => 17.0.14
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.1.2 => 4.3.5

```
</details>

**Comment by DanailH** [comment]
Hi, @CAVAh  thanks for reporting this. It seems to be a regression on the latest version of `4.0.0-alpha.34`. Reverting back to `4.0.0-alpha.33` solves the problem. We'll work on fixing the problem for the future version.

You can see it working here https://codesandbox.io/s/material-demo-forked-u4g3p?file=/demo.tsx
