### ISSUE TITLE
Link can't be found

### ISSUE THREAD

**Issue by EugeneGohh** [mui-org/material-ui-x#2207]
https://next.material-ui.com/components/data-grid/layout/

**Comment by DanailH** [comment]
Seems we forgot to add the link in and navigation item in the core / v5 branch

**Comment by studyhog** [comment]
I can attempt to fix this if nobody's working on it.

**Comment by oliviertassinari** [comment]
@studyhog Thanks for the interest however solving this issue will require a deep refactoring of the codebase. 

Regarding the others that wonder how to reproduce:

1. Open https://next.material-ui.com/components/typography/
2. Click on Layout

<img width="262" alt="Capture d’écran 2021-08-07 à 00 40 54" src="https://user-images.githubusercontent.com/3165635/128577586-b5049d98-3697-49d4-a4a1-8950d31f5479.png">

---

We have been aware of this issue for some time now, see our SEO crawler:

<img width="468" alt="Capture d’écran 2021-08-07 à 00 41 19" src="https://user-images.githubusercontent.com/3165635/128577635-18cba89b-00ba-4e45-8d29-c39c037db270.png">

**Comment by oliviertassinari** [comment]
It will be fixed with #1902, but to double check.

**Comment by EugeneGohh** [comment]
In current version "**v5.0.0-rc.0**" of MaterialUI, looks like the section on **Components -> Data Grid** section. Many of the links lead to **page not found**. For example, https://next.material-ui.com/components/data-grid/style/

**Comment by m4theushw** [comment]
This was fixed after the merge of the `master` branch into `next`.

I'm closing.
