### ISSUE TITLE
DataGrid page prop not working

### ISSUE THREAD

**Issue by jinqiangg** [mui-org/material-ui-x#2209]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

DataGrid page props sets the default page, however that option will disable page navigation in v5 beta

## Expected Behavior 🤔

By setting the default page should also allow you to navigate to other pages

## Steps to Reproduce 🕹

Steps:

1. https://codesandbox.io/s/material-demo-forked-utzgf?file=/demo.js
2. Set material ui core to v5 beta and add the dependencies package
3. set page={1} in the props of DataGrid
4.The arrow buttons to navigate to other pages wont work

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
https://github.com/mui-org/material-ui-x/pull/2099

The control state for the pagination if being reworked, it should work in the next release :+1:

**Comment by DanailH** [comment]
@jinqiangg Actually what is happening is that by setting `page={1}` you are taking control of the pagination and. If you do that the grid leaves the management of the page to the developer. You can see that explained more in-depth here https://material-ui.com/components/data-grid/pagination/#controlled-pagination
