### ISSUE TITLE
Datagrid nested object client side sorting.

### ISSUE THREAD

**Issue by MalikMursaleen** [mui-org/material-ui-x#2216]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

My data in row had some ids as plain ids and some are in nested objects, which I'm using as plain string by get method of lodash. like name, title, price are plain ids and location.name, vehicle.serial are some of the nested objects being used as plain strings. but CLIENT side sorting works with name, title etc but not with location.name etc.

## Examples 🌈

https://codesandbox.io/s/exciting-swartz-5pucf?file=/src/Demo.js to see the issue in details.

 {field: "location.name", sort: "asc"} is the sortModel, which doesn't work as expected, but the sort model  {field: "title", sort: "asc"} works fine. 

## Motivation 🔦

Sometimes we have nested objects and want client side sorting, which should work perfectly.

**Comment by DanailH** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://material-ui.com/r/issue-template) _may_ be a good starting point. Thank you!

**Comment by MalikMursaleen** [comment]
Hey @DanailH thanks for your suggestion, You can check this [codesandbox](https://codesandbox.io/s/exciting-swartz-5pucf?file=/src/Demo.js). I've explained my problem here. Hope it will help to understand.

**Comment by flaviendelangle** [comment]
Duplicates #1363 

https://codesandbox.io/s/kind-ives-yt195
It seems to work with this modification https://github.com/mui-org/material-ui-x/issues/1363#issuecomment-814284132

**Comment by oliviertassinari** [comment]
`field: "location.name"` this dot is wierd

**Comment by MalikMursaleen** [comment]
> `field: "location.name"` this dot in the middle is weird.

My bad. I should've use it as plain location and department.

**Comment by oliviertassinari** [comment]
We have no special handling for the dot because it's valid in an object key: https://stackoverflow.com/questions/2577172/how-to-get-json-objects-value-if-its-name-contains-dots

**Comment by MalikMursaleen** [comment]
> We have no special handling for the dot because it's valid in an object key: https://stackoverflow.com/questions/2577172/how-to-get-json-objects-value-if-its-name-contains-dots

Actually I was using it in some other context of my project, but even if we don't use dot, it works fine.
You can see in this [Codesandbox](https://codesandbox.io/s/fragrant-cherry-b6c2t?file=/src/Demo.js)
