### ISSUE TITLE
onFilterModelChage  don’t have visibleRows

### ISSUE THREAD

**Issue by GhostBunny13** [mui-org/material-ui-x#2222]
i’m use x-grid key on 53 server but 3 server can’t get visibleRows value in onFilterModelChage
![image](https://user-images.githubusercontent.com/26898398/127133719-b70e36ea-c783-4914-b47f-dd1212d7428b.png)

**Comment by oliviertassinari** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://material-ui.com/r/issue-template) _may_ be a good starting point. Thank you!

**Comment by GhostBunny13** [comment]
ok this simple code
https://codesandbox.io/s/blissful-herschel-xpm45?file=/src/Demo.tsx, you
just try filter and view console

ในวันที่ อ. 27 ก.ค. 2021 เวลา 18:53 Olivier Tassinari <
***@***.***> เขียนว่า:

**Comment by oliviertassinari** [comment]
This is expected, the filter model is unrelated to the visible rows. This has changed in #1909, released in v4.0.0-alpha.34.

**Comment by oliviertassinari** [comment]
@GhostBunny13 See #1106.

**Comment by GhostBunny13** [comment]
thx it work!!!
