### ISSUE TITLE
[DataGrid] Using filterModel to filter extended columns throws an error

### ISSUE THREAD

**Issue by kojimagui** [mui-org/material-ui-x#2225]
The demo is displaying an error message when viewing it in Opera GX and Google Chrome.

Extended filter operators:
Error: Material-UI: No filter operators found for column 'totalPrice'.

https://material-ui.com/components/data-grid/filtering/#extend-filter-operators

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce 🕹

Steps:

1.
2.
3.
4.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
This is a regression from #1720
