### ISSUE TITLE
"Maximum update depth exceeded." when sortingMode="server" and setState inside "onSortModelChange"

### ISSUE THREAD

**Issue by gabrielprestesperini** [mui-org/material-ui-x#2226]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The function in prop onSortModelChange is called several times and cause "Maximum update depth exceeded."

## Expected Behavior 🤔

The function in prop onSortModelChange just called one time per click in "reorder" button

## Steps to Reproduce 🕹

Steps:
1. set sortingMode="server" 
2. create a state with useState, could be a bool
3. in onSortModelChange just alternate the bool like this
`
() => {
setState(p => !p)
}
`

Exemple here ==> https://codesandbox.io/s/infinite-render-sortmodel-mpcph

## Context 🔦

This make several errors and performance issues

**Comment by flaviendelangle** [comment]
https://codesandbox.io/s/infinite-render-sortmodel-forked-bwv2g?file=/src/Demo.tsx

You should always
