### ISSUE TITLE
[DataGrid] `page` prop is not behaving correctly

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#223]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The active page changes.

## Expected Behavior 🤔

The active page **shouldn't** change.

## Steps to Reproduce 🕹

Steps:

1. Open https://codesandbox.io/s/icy-sea-fchxe?file=/demo.tsx
2. Click on the arrow next pagination icon

## Context 🔦

The `page` prop should be fully controllable. If developers want to provide the default page, they should use the `defaultPage` prop (doesn't exist, to be added).

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | v0.1.67  |

**Comment by oliviertassinari** [comment]
It's fixed in the latest version: https://codesandbox.io/s/friendly-lumiere-fwcep?file=/demo.tsx. Maybe we only need to add a test case.

**Comment by dtassone** [comment]
why do we need a default page?
if page is set and onPageChange is not set then the grid can update the page state

**Comment by oliviertassinari** [comment]
> why do we need a default page?

@dtassone We don't really need to. Last time, we said that if developers want a default value for a controlled state, they can control and implement the default themselves.
