### ISSUE TITLE
[XGrid] Column widths are not maintained upon resize if flex is enabled. Also causes undesired click of column header.

### ISSUE THREAD

**Issue by jwieler** [mui-org/material-ui-x#2237]
Column widths are not maintained upon resize if flex is enabled. Also causes undesired click of column header which subsequently causes sorting of table based on that column.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Resizing columns multiple times causes column width to be reset and an undesired click of a column header.

## Expected Behavior 🤔

Flex-enabled columns' widths should be maintained after resizing.
## Steps to Reproduce 🕹

https://codesandbox.io/s/red-wind-bhd4f

Steps:

1. Resize id column to be smaller than first render.
2. Resize id column again.

## Context 🔦

Trying to use flex to fill unused space in table while still giving the user the ability to resize the columns as they want.
## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  

```
System:
    OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.10 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.107
    Firefox: 90.0
  npmPackages:
    @emotion/react: ^11.4.0 => 11.4.0 
    @emotion/styled: ^11.3.0 => 11.3.0 
    @material-ui/core: 5.0.0-beta.0 => 5.0.0-beta.0 
    @material-ui/icons: 5.0.0-beta.0 => 5.0.0-beta.0 
    @material-ui/lab: 5.0.0-alpha.39 => 5.0.0-alpha.39 
    @material-ui/private-theming:  5.0.0-beta.0 
    @material-ui/styled-engine:  5.0.0-beta.0 
    @material-ui/styles: 5.0.0-beta.0 => 5.0.0-beta.0 
    @material-ui/system: 5.0.0-beta.0 => 5.0.0-beta.0 
    @material-ui/types:  6.0.1 
    @material-ui/unstyled:  5.0.0-alpha.39 
    @material-ui/utils:  5.0.0-beta.1 
    @material-ui/x-grid: 4.0.0-alpha.34 => 4.0.0-alpha.34 
    @material-ui/x-license:  4.0.0-alpha.34 
    @types/react:  17.0.6 
    react: ^17.0.1 => 17.0.2 
    react-dom: ^17.0.1 => 17.0.2 
    typescript: ^4.3.2 => 4.3.2 
```
</details>

## Order id 💳

Order #25141

**Comment by flaviendelangle** [comment]
Duplicates #2129 

@jwieler this issue highlighted deeper problems in how we handle our columns width.
