### ISSUE TITLE
Extend filter operators

### ISSUE THREAD

**Issue by nixtortech** [mui-org/material-ui-x#2270]
This demo had a runtime error!

We would appreciate it if you report this error directly to our issue tracker.

Error: Material-UI: No filter operators found for column 'totalPrice'.

- [ ] The issue is present in the latest release.
- [ ] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce 🕹

Steps:

1.
2.
3.
4.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
The failing demo https://material-ui.com/components/data-grid/filtering/#extend-filter-operators

**Comment by flaviendelangle** [comment]
Duplicates #2225
