### ISSUE TITLE
Material-UI: The key `caption` provided to the classes prop is not implemented in ForwardRef(TablePagination). You can only override one of the following: root,toolbar,spacer,selectLabel,selectRoot,select,selectIcon,input,menuItem,displayedRows,actions. 

### ISSUE THREAD

**Issue by MihailFr** [mui-org/material-ui-x#2277]
Create new X-Grid table 
"@material-ui/core": "^5.0.0-alpha.28",
"@material-ui/lab": "^5.0.0-alpha.28",
"@material-ui/styles": "^5.0.0-alpha.28",
"@material-ui/x-grid": "^4.0.0-alpha.35",
import * as React from 'react';
import { XGrid, GridToolbar, LicenseInfo } from '@material-ui/x-grid';
import { Button } from '@material-ui/core';
import './style.css';

export default function FullFeaturedDemo() {
  const columns = [
    {
      field: 'id',
      headerName: 'ID',
      width: 90,
      // editable: true,
      sortable: false,
      disableColumnMenu: true
    },
    {
      field: 'firstName',
      headerName: 'First name',
      width: 150,
      editable: true
    },
    {
      field: 'lastName',
      headerName: 'Last name',
      width: 150,
      editable: true
    },
    {
      field: 'age',
      headerName: 'Age',
      type: 'number',
      width: 110,
      editable: true
    },
    {
      field: 'fullName',
      headerName: 'Full name',
      description: 'This column has a value getter and is not sortable.',
      sortable: false,
      width: 160,
      valueGetter: (params) =>
        `${params.getValue(params.id, 'firstName') || ''} ${
          params.getValue(params.id, 'lastName') || ''
        }`
    },
    {
      field: 'sa',
      headerName: 'sa',
      description: 'This column has a value getter and is not sortable.',
      sortable: false,
      disableColumnMenu: true,
      width: 160,
      components: <Button />
    }
  ];

  const rows = [
    { id: 1, lastName: 'Snow', firstName: 'Jon', age: 35 },
    { id: 2, lastName: 'Lannister', firstName: 'Cersei', age: 42 },
    { id: 3, lastName: 'Lannister', firstName: 'Jaime', age: 45 },
    { id: 4, lastName: 'Stark', firstName: 'Arya', age: 16 },
    { id: 5, lastName: 'Targaryen', firstName: 'Daenerys', age: null },
    { id: 6, lastName: 'Melisandre', firstName: null, age: 150 },
    { id: 7, lastName: 'Clifford', firstName: 'Ferrara', age: 44 },
    { id: 8, lastName: 'Frances', firstName: 'Rossini', age: 36 },
    { id: 9, lastName: 'Roxie', firstName: 'Harvey', age: 65 }
  ];

  return (
    <div className="table-style" style={{ paddingLeft: '20px' }}>
      <XGrid
        components={{
          Toolbar: GridToolbar
        }}
        columns={columns}
        rows={rows}
        disableSelectionOnClick
        // pageSize={5}
        pagination={true}
      />
    </div>
  );
}
And have error 
Warning: Failed prop type: Invalid prop `modifiers` of type `object` supplied to `ForwardRef(Popper)`, expected an array.

and Material-UI: The key `caption` provided to the classes prop is not implemented in ForwardRef(TablePagination).
You can only override one of the following: root,toolbar,spacer,selectLabel,selectRoot,select,selectIcon,input,menuItem,displayedRows,actions. 

I saw the same bug but the solution to update material ua core to the latest version does not suit me because some material updates break many components that I have already implemented.
Please tell me what is the possible solution with the current packages

https://codesandbox.io/s/immutable-fast-dx8k7?file=/src/index.js

**Comment by m4theushw** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://material-ui.com/r/issue-template) _may_ be a good starting point. Thank you!

**Comment by MihailFr** [comment]
https://codesandbox.io/s/immutable-fast-dx8k7?file=/src/index.js

**Comment by m4theushw** [comment]
After upgrading all packages to their latest version I couldn't see any warning: https://codesandbox.io/s/busy-kirch-0y3u9?file=/src/demo.js

**Comment by MihailFr** [comment]
I saw the same bug but the solution to update material ua core to the latest version does not suit me because some material updates break many components that I have already implemented.
Please tell me what is the possible solution with the current packages
