### ISSUE TITLE
Warning: Failed prop type: Invalid prop modifiers of type object supplied to ForwardRef(Popper), expected an array.

### ISSUE THREAD

**Issue by MihailFr** [mui-org/material-ui-x#2283]
Create new X-Grid table
"@material-ui/core": "^5.0.0-alpha.28",
"@material-ui/lab": "^5.0.0-alpha.28",
"@material-ui/styles": "^5.0.0-alpha.28",
"@material-ui/x-grid": "^4.0.0-alpha.35",
import * as React from 'react';
import { XGrid, GridToolbar, LicenseInfo } from '@material-ui/x-grid';
import { Button } from '@material-ui/core';
import './style.css';

export default function FullFeaturedDemo() {
const columns = [
{
field: 'id',
headerName: 'ID',
width: 90,
// editable: true,
sortable: false,
disableColumnMenu: true
},
{
field: 'firstName',
headerName: 'First name',
width: 150,
editable: true
},
{
field: 'lastName',
headerName: 'Last name',
width: 150,
editable: true
},
{
field: 'age',
headerName: 'Age',
type: 'number',
width: 110,
editable: true
},
{
field: 'fullName',
headerName: 'Full name',
description: 'This column has a value getter and is not sortable.',
sortable: false,
width: 160,
valueGetter: (params) =>
${params.getValue(params.id, 'firstName') || ''} ${ params.getValue(params.id, 'lastName') || '' }
},
{
field: 'sa',
headerName: 'sa',
description: 'This column has a value getter and is not sortable.',
sortable: false,
disableColumnMenu: true,
width: 160,
components:
}
];

const rows = [
{ id: 1, lastName: 'Snow', firstName: 'Jon', age: 35 },
{ id: 2, lastName: 'Lannister', firstName: 'Cersei', age: 42 },
{ id: 3, lastName: 'Lannister', firstName: 'Jaime', age: 45 },
{ id: 4, lastName: 'Stark', firstName: 'Arya', age: 16 },
{ id: 5, lastName: 'Targaryen', firstName: 'Daenerys', age: null },
{ id: 6, lastName: 'Melisandre', firstName: null, age: 150 },
{ id: 7, lastName: 'Clifford', firstName: 'Ferrara', age: 44 },
{ id: 8, lastName: 'Frances', firstName: 'Rossini', age: 36 },
{ id: 9, lastName: 'Roxie', firstName: 'Harvey', age: 65 }
];

return (
<div className="table-style" style={{ paddingLeft: '20px' }}>
<XGrid
components={{
Toolbar: GridToolbar
}}
columns={columns}
rows={rows}
disableSelectionOnClick
// pageSize={5}
pagination={true}
/>

);
}
And have error
Warning: Failed prop type: Invalid prop modifiers of type object supplied to ForwardRef(Popper), expected an array.

and Material-UI: The key caption provided to the classes prop is not implemented in ForwardRef(TablePagination).
You can only override one of the following: root,toolbar,spacer,selectLabel,selectRoot,select,selectIcon,input,menuItem,displayedRows,actions.

I saw the same bug but the solution to update material ua core to the latest version does not suit me because some material updates break many components that I have already implemented.
Please tell me what is the possible solution with the current packages

https://codesandbox.io/s/immutable-fast-dx8k7?file=/src/index.js
Requires a solution without updating @ material / core packages only possible updating @ material / x-grid

**Comment by DanailH** [comment]
Hi @MihailFr, thanks for reporting this. I tried with a couple of different versions of the `core` and it seems that the problem is solved from `5.0.0-alpha.32`. Maybe you can try updating to that version and see if your other components still break.
You can check the changelog of that version here to see if you should expect potential problems -> https://github.com/mui-org/material-ui/releases/tag/v5.0.0-alpha.32

**Comment by MihailFr** [comment]
I can't change core to beta version because I have package who doesn't
support beta version material ua

чт, 5 авг. 2021 г. в 10:12, Danail Hadjiatanasov ***@***.***>:

**Comment by m4theushw** [comment]
You're using an old alpha version of @material-ui/core. The beta is an evolution of the alpha, it should be compatible with your code without problems. Unfortunately, there's nothing we can do besides recommend to use the latest version.

**Comment by MihailFr** [comment]
notistack not support beta version

чт, 5 авг. 2021 г. в 18:26, Matheus Wichman ***@***.***>:

**Comment by m4theushw** [comment]
You can follow https://github.com/iamhosseindhv/notistack/issues/412 to be advised when notistack gets compatible with the last beta version.

**Comment by MihailFr** [comment]
using doesnt work)

чт, 5 авг. 2021 г. в 20:08, Matheus Wichman ***@***.***>:

**Comment by MihailFr** [comment]
He have issue with support material ua beta but now not implemented and
doesn't work.

чт, 5 авг. 2021 г. в 20:13, Михаил Ян ***@***.***>:

**Comment by oliviertassinari** [comment]
It's also to be noted that the versions of the author of this issue are not compatible with our peer dependency scope:

https://github.com/mui-org/material-ui-x/blob/3aad96eb90eb68569bd633f1746c654248793fef/packages/grid/data-grid/package.json#L48
