### ISSUE TITLE
[DataGrid] Show index column

### ISSUE THREAD

**Issue by OozyGrub** [mui-org/material-ui-x#2289]
It should be column that shows the index of each rows like 1., 2.

- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡
It should be column that shows the index of each rows like 1., 2.

## Examples 🌈
1. | ID | etc.

**Comment by flaviendelangle** [comment]
You can easily implement it on your side 

```ts
const columns: GridColDef[] = [
  {
    field: 'id',
  },
  ...yourOtherColumns,
]

return <DataGrid columns{columns} rows={rows} />
```

**Comment by raDiesle** [comment]
In my use case, I want to display the position of the rows.
Also when user sorts, the position should stay e.g.
1.  valueA
2. valueB
3. valueC

So user understands the position based on his sorting criteria

**Comment by flaviendelangle** [comment]
Should your index be the one relative to the current page or relative to all the rows ?

**Comment by raDiesle** [comment]
relative to all rows.
Seems like this can be done with 
params.api.getRowIndex(params.row.id) + 1

**Comment by flaviendelangle** [comment]
Yes if you have a lot of rows the performances will be terrible.

**Comment by raDiesle** [comment]
I have a very high dataset. Thanks for the improved version!

**Comment by flaviendelangle** [comment]
My code sample is the one we use internally for `apiRef.current.getRowIndex` 
If you have problems with your basic implementation `params.api.getRowIndex(params.row.id) + 1`, could you give a feedback here ?

We could probably add the `index` to the params passed to the `renderCell` for instance

**Comment by artsiadi** [comment]
Hi @flaviendelangle, any place to add the index to render cell in the near future? thanks!

**Comment by jamilakterup** [comment]
const columns = [
  {
    field: 'id',
    headerName: 'Number',
    filterable: false,
    valueGetter: (params) => {
      const { rowIndex } = params;  // Extract rowIndex from params
      if (rowIndex === undefined) {
        return 1;  // Check if rowIndex is available and return an empty string if it's not
      }
      return rowIndex + 1;  // Return 1-based index
    },
  },
  { field: 'firstName', headerName: 'First name', width: 130 },
  { field: 'lastName', headerName: 'Last name', width: 130 },
  {
    field: 'age',
    headerName: 'Age',
    type: 'number',
    width: 90,
  },
