### ISSUE TITLE
[core] Replace the options with direct prop reads

### ISSUE THREAD

**Issue by flaviendelangle** [mui-org/material-ui-x#2292]
Part of #2231 

## Goals

1. Avoid re-renders caused by props-to-state patterns

2. Avoid having synchronization issues between the values from the `options` and the values from the `props` inside hooks and components

When setting a prop, you have a render with the new prop but the old option. So if some parts of the code uses the options but other uses the props it causes bugs.

## Proposal

We can replace the options by a preprocessing of the props that accomplish the same things as `useOptionsProp` but synchronously

```ts
// useGridPropsWithDefaultValues.ts

const GRID_DEFAULT_PROPS: POCGridOptions = {
  columnBuffer: 2,
  columnTypes: getGridDefaultColumnTypes(),
  density: GridDensityTypes.Standard,
  localeText: GRID_DEFAULT_LOCALE_TEXT,
};

/**
 * Properties with a default value that can be overridden with a prop
 */
interface POCGridOptions {
  /**
   * Number of columns rendered outside the grid viewport.
   * @default 2
   */
  columnBuffer: number;
  /**
   * Extend native column types with your new column types.
   */
  columnTypes: GridColumnTypesRecord;
  /**
   * Set the density of the grid.
   */
  density: GridDensityTypes;
  /**
   * Set the locale text of the grid.
   * You can find all the translation keys supported in [the source](https://github.com/mui-org/material-ui-x/blob/HEAD/packages/grid/_modules_/grid/constants/localeTextConstants.ts) in the GitHub repository.
   */
  localeText: Partial<GridLocaleText>;
}

/**
 * Properties that do not have a default value
 */
interface POCGridOtherProps {
  /**
   * The ref object that allows grid manipulation. Can be instantiated with [[useGridApiRef()]].
   */
  apiRef?: GridApiRef;
  /**
   * The label of the grid.
   */
  'aria-label'?: string;
  /**
   * Override or extend the styles applied to the component.
   */
  classes?: GridClasses;
  /**
   * Set of columns of type [[GridColumns]].
   */
  columns: GridColumns;
  /**
   * Set of rows of type [[GridRowsProp]].
   */
  rows: GridRowsProp;
}

type POCGridInputComponentProps = POCGridOtherProps & Partial<POCGridOptions>;

type POCGridComponentProps = POCGridOtherProps & POCGridOptions;

export const useGridPropsWithDefaultValues = (
  inProps: POCGridInputComponentProps,
): POCGridComponentProps => {
  const localeText = React.useMemo(
    () => ({
      ...inProps.localeText,
      ...GRID_DEFAULT_PROPS.localeText,
    }),
    [inProps.localeText],
  );

  const classes = React.useMemo(
    () =>
      composeClasses(
        {
          root: [GRID_ROOT_CSS_CLASS_SUFFIX],
          columnHeader: [GRID_COLUMN_HEADER_CSS_CLASS_SUFFIX],
          row: [GRID_ROW_CSS_CLASS_SUFFIX],
          cell: [GRID_CELL_CSS_CLASS_SUFFIX],
        },
        getDataGridUtilityClass,
        inProps.classes as Record<string, string>,
      ),
    [inProps.classes],
  );

  return React.useMemo<POCGridComponentProps>(
    () => ({
      ...GRID_DEFAULT_PROPS,
      ...inProps,
      localeText,
      classes,
    }),
    [inProps, localeText, classes],
  );
};
```

```tsx
// DataGrid.tsx

const DataGrid = (inProps: DataGridProps) => {
  const inPropsWithForcedValues = React.useMemo<POCGridInputComponentProps>(() => {
    ...inProps,
    ...DATA_GRID_FORCED_PROPS,
  })

  const props = useGridPropsWithDefaultValues(inPropsWithForcedValues);
  const apiRef = useGridApiRef();
  useDataGridComponent(apiRef, props);

  return ()
}
```

```tsx
// XGrid.tsx
const XGrid = (inProps: XGridProps) => {
  const props = useGridPropsWithDefaultValues(inProps);
  const apiRef = useGridApiRef();
  useXGridComponent(apiRef, props);

  return ()
}
```  

### Migration plan

- [ ] Replace all the options usage with fallback handled in `.defaultProps` (#2275, #2284 , #2318 )
- [ ] Detect the scrollbar default size in `useGridComponentProps` instead of updating `options.scrollbarSize` (#2317)
- [ ] Preprocess the props to merge the default values in a hook instead of using `.defaultProps` and correctly merge `localeText`, `classes`, `components` and `componentsProps` and use them instead of `options.localeText`, `options.classes`, `apiRef.current.components`, `apiRef.current.componentsProps`
- [ ] Replace `options` with `rootProps` in `useGridSlotComponentProps`

**Comment by oliviertassinari** [comment]
We could extend the scope to `useGridComponents.tsx`, handle it with the other props

https://github.com/mui-org/material-ui-x/blob/49639ee9924517b5f1aee3d8233f0ddd669c8fdc/packages/grid/_modules_/grid/hooks/features/useGridComponents.tsx#L141-L142

Is in contradiction to the React rendering patterns. We don't do global mutations in a render phase.

**Comment by flaviendelangle** [comment]
So you would access `rootProps.components` and `rootProps.componentsProps` instead of accessing it through the `apiRef` ?
I agree that it is cleaner

**Comment by oliviertassinari** [comment]
@flaviendelangle Yes, it seems simpler.

**Comment by flaviendelangle** [comment]
First message updated with the migration plan
With the opened PR, we will have no more options usage except the ones that needs a better merge than the `.defaultProps`. I'll do them at the say time I'll write the new hook (or adapt and rename `useGridComponents`)
