### ISSUE TITLE
DataGrid - Adding Predefined Filter for filterModel prop causes 'unique "key" prop' error.

### ISSUE THREAD

**Issue by TZ97** [mui-org/material-ui-x#2309]
I'm using the DataGrid and it was all working fine with the toolbar however, when adding a predefined filter the error appears.

Upon checking example code it also has the error

Current Behavior 😯
DataGrid with predifined filter and toolbar active causes issue

Expected Behavior 🤔
No error

Steps to Reproduce 🕹
https://codesandbox.io/s/38o2c

**Comment by DanailH** [comment]
Hi, @TZ97 thanks for raising this. We noticed it last week. This PR aims to fix that issue https://github.com/mui-org/material-ui-x/pull/2281
