### ISSUE TITLE
[DataGrid] pagination cannot be deactivated

### ISSUE THREAD

**Issue by kumarunster** [mui-org/material-ui-x#2310]
- [X] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

DataGrid documentation is mentioning pagination property, which should turn pagination on or off. Setting the pagination property to undefined makes pagination footer still apear.

## Expected Behavior 🤔

DataGrid should't show pagination footer, if pagination is not set or explicitly set to undefined.

## Steps to Reproduce 🕹

Reproducer is to find in CodeSandbox: https://codesandbox.io/s/ttmyq?file=/demo.tsx

data rows are reduced to only 5 elements. Pagination property is explicitly set to undefined. Pagination is still visible on the data table.

## Context 🔦

Pagination does not make much sense, if the available data rows amount is too small.

**Comment by flaviendelangle** [comment]
Only XGrid can disable the pagination
We could add a doc example for XGrid with the pagination disabled to be more explicit.

**Comment by kumarunster** [comment]
@flaviendelangle thanks for the quick response. yes mentioning that on doc page would make lot of sense.

**Comment by oliviertassinari** [comment]
What's your use case for disabling pagination?

**Comment by kumarunster** [comment]
there is no need to show pagination, if amount of data rows is fitting into the page. it allows to reduce amount of user interface controls and make a more clean interface.

**Comment by oliviertassinari** [comment]
OK, then maybe we should allow the flag and only warn/cripple the feature if there a more than 100 rows rendered (either through the props or the apiRef).

**Comment by flaviendelangle** [comment]
I think it would make sense 
It would allow to unify the default behaviors of `XGrid` and `DataGrid` pagination.
And disabling the pagination is not a high value feature.

**Comment by flaviendelangle** [comment]
@oliviertassinari if we allow the DataGrid to disable pagination, do we want to unify the default behavior with the one in XGrid ?
And if so, do we want to set `pagination: true` or `pagination: false` to both of them by default ?

**Comment by oliviertassinari** [comment]
@kumarunster You can use https://material-ui.com/components/data-grid/components/#footer `hideFooter`
@flaviendelangle I have pushed the reasoning more on this path and I couldn't find a solid win.

**Comment by kumarunster** [comment]
@oliviertassinari thank you

**Comment by andrasistemaserp** [comment]
Use props hideFooter={true} to deactivated

**Comment by bharathi-mohans** [comment]
> Use props hideFooter={true} to deactivated

Thanks for sharing , it's working fine, and  " hideFooterPagination={true} " exact pagination has been removed.

**Comment by tnmygrwl** [comment]
I just hide the footer if rows are 20 or less

`hideFooter={rows.length <= 20}`
