### ISSUE TITLE
Rename the packages

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#2313]
We are making a change to the terminology used in the project to support the long-term direction. The high-level bit is that we are going to use `x-` as a prefix for the rich/advanced components and `-pro` as a suffix for the paid professional version.

Current:

- `@material-ui/data-grid` DataGrid MIT
- `@material-ui/x-grid XGrid` Commercial

Target:

- `@mui/x-data-grid` DataGrid MIT 
- `@mui/x-data-grid-pro` DataGridPro Commercial
- `@mui/x-tree-view` TreeView MIT 
- `@mui/x-tree-view-pro` TreeViewPro Commercial

This is the result of a longer discussion that happened in https://www.notion.so/mui-org/Rearranging-the-packages-2f700caf8b5e48559fe86ebb648ed91a.

#### 1. MUI over Material-UI

- A large part of the community is confusing Material-UI with Material Design, or even Google, MUI distinguishes ourselves
- `@mui` is shorter to write, read, and pronounce.
- The advanced components, while only currently providing a Material Design UI are meant to be heavily customizable. The features matter more than the design

#### 2. The X prefix

Pros:

- x allows the product to live on its own. Bootstrap didn't need any of the advanced components to strive, nor does the core team need them. We want to compete with the DX for instance in the core. In X we are competing with other standalone open-source UI components, react-table, Kendo-UI, AG Grid, etc. 
- x allows signaling to the developers on which repository they should seek support. We have seen too many developers opening issues on https://github.com/mui-org/material-ui while it should be here.
- x makes it easy to avoid package name collisions between the different repositories of MUI. Say x needs a codemode, `@material-ui/codemod` is already taken, what should we use?

Cons:

- Longer to write and read.
- It clearly isolates the component, it does no longer feel part of the exact same product.

#### 3. The Pro suffix 

- pro makes it clear what's not MIT. We saw too many developers confused about what is X about, is it about the paid version, or is it a different product?

## The execution steps

We will make the first step ASAP

- [x] Grant org access of the members to `@mui`
- [x] Rename the packages #2341
- [x] Rename the components: XGrid -> DataGridPro #2382 
- [x] Release beta
- [x] We deprecate the latest version of the older packages with migration instruction to check 
- [x] Rearrange docs according to https://www.notion.so/mui-org/Sitemap-and-URL-structure-rearrange-ca604f628c17438db2d987961fcb8ffe#be64fe17a857402f9b0712e5a98e3e23
- [ ] Update the demos in the core to reflect the change of the package names 
- [ ] Move the GitHub repository: https://github.com/mui-org/material-ui-x > https://github.com/mui/mui-x cc @mbrookes could you help me with this one?
- [ ] Move the folders to be consistent with the main repository: x-license -> mui-x-license-pro

cc @mui-org/x

**Comment by oliviertassinari** [comment]
@mui-org/x do you have a preference on when we make this change happen? Do you prefer alpha->beta or beta->stable?  We won't likely do any release candidates. I would personally vote for alpha->beta because the sooner the better.

**Comment by m4theushw** [comment]
> I would personally vote for alpha->beta because the sooner the better.

Me too.

**Comment by flaviendelangle** [comment]
> I would personally vote for alpha->beta because the sooner the better.
Same

**Comment by DanailH** [comment]
> I would personally vote for alpha->beta because the sooner the better.

Same

**Comment by DanailH** [comment]
This should no longer be blocking the `beta` release. Renaming folders won't cause a breaking change.

**Comment by oliviertassinari** [comment]
I have done this step " We deprecate the latest version of the older packages with migration instruction to check":

<img width="685" alt="Screenshot 2021-08-31 at 00 33 13" src="https://user-images.githubusercontent.com/3165635/131414431-25ddf4c6-f02a-4e1a-acb6-36b0d192f479.png">

https://www.npmjs.com/package/@material-ui/x-grid

**Comment by flaviendelangle** [comment]
I clause this issue, as the packages have be renamed and add a follow up issue for renaming the folder that won't be in the stable version millistone
