### ISSUE TITLE
[X-Grid] Clicking header to sort when sortModel applied is broken

### ISSUE THREAD

**Issue by oldtinroof** [mui-org/material-ui-x#2324]
I've just updated our app to use the latest alpha (v36) of x-grid, and the table sorting no longer works if a sortModel prop is supplied. 

From what I can tell, the bug first appeared in the v34 alpha release.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When I apply a simple sortModel (as per the documentation) to a grid, it applies the sorting required, but when you click a column header to sort the grid, it doesn't do anything.

## Expected Behavior 🤔

When I click the column header I expect the grid to sort by that column, whether there's an initial sortModel provided or not.

## Steps to Reproduce 🕹

https://codesandbox.io/s/quizzical-ritchie-febcb?file=/src/Demo.tsx

Steps:

1. Create grid with sortModel
2. Click a header cell to sort
3. Nothing happens
4. ...

## Context 🔦

Trying to keep up with the updates :)

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  In latest Chrome.
```
 System:
    OS: macOS 11.5
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.10.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Edge: Not Found
    Firefox: 90.0.2
    Safari: 14.1.2
  npmPackages:
    @material-ui/core: 4.12.3 => 4.12.3 
    @material-ui/icons: 4.11.2 => 4.11.2 
    @material-ui/lab: 4.0.0-alpha.60 => 4.0.0-alpha.60 
    @material-ui/pickers: 3.3.10 => 3.3.10 
    @material-ui/styles:  4.11.4 
    @material-ui/system: 4.12.1 => 4.12.1 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @material-ui/x-grid: 4.0.0-alpha.36 => 4.0.0-alpha.36 
    @material-ui/x-license:  4.0.0-alpha.36 
    @types/react: ^16.9.19 => 16.14.12 
    react: ^16.13.1 => 16.14.0 
    react-dom: ^16.12.0 => 16.14.0 
    styled-components: 5.1.0 => 5.1.0 
```
</details>

## Order id 💳

23124

**Comment by tonymamo** [comment]
Noticed this as well today, I was on alpha.34 and it was working just fine, and then upgraded to alpha.36 yesterday and experienced the same exact issue. Not sure if the issue popped up in 34 or 35 then, I'll start combing through commits to see if I can narrow it down

**Comment by m4theushw** [comment]
That's the expected behavior now. When the `sortModel` prop is present, it's always used as the source of truth. To be able to change the sorting, the `onSortModelChange` prop also has to be added.

```jsx
<DataGrid
  {...data}
  sortModel={sortModel}
  onSortModelChange={(model) => setSortModel(model)}
/>
```

**Comment by tonymamo** [comment]
Thanks for the quick reply @m4theushw. Adding a `onSortModelChange` does in fact work now. Before, on alpha.34, if I passed in my own `onSortModelChange` in the same manner, I would get a Maximum Depth Exceeded error, but found out that if I removed the prop it worked fine.

**Comment by oldtinroof** [comment]
Thanks for the clarification @m4theushw - I've had a look at the docs, and it looks like the latest version now includes the update too. Cheers :)
