### ISSUE TITLE
Data Grid

### ISSUE THREAD

**Issue by huizhong90** [mui-org/material-ui-x#2332]
How can we know which column menu is selected from the data grid? 
In order to change the filter column to the corresponding column.

**Comment by m4theushw** [comment]
We don't provide a prop or event to know when a column menu is opened. I didn't understand well what you're trying to accomplish. Could you describe in detail your use case?

**Comment by huizhong90** [comment]
For instant, I have columns A, B and C. When I click on the column menu from column B, I would like to see the filter model to show column B being selected.

**Comment by m4theushw** [comment]
https://github.com/mui-org/material-ui-x/issues/1777#issuecomment-889241181
