### ISSUE TITLE
Error: "n" is read-only

### ISSUE THREAD

**Issue by matias-retargetly** [mui-org/material-ui-x#2333]
Hi!

- [Yes ] The issue is present in the latest release.
- [ Yes ] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
when i deploy the project to GOCD ubuntu distro I got this mensaje when i m try to render de x-grid, is strange because i can't reproduce this in local, only in the server. this happen after update @material-ui/x-grid "4.0.0-alpha.24" to "4.0.0-alpha.36.
update : this happen only in 4.0.0-alpha.36

![image](https://user-images.githubusercontent.com/77464326/129355899-4fd22638-0068-49b3-a3eb-facf365fc71d.png)

![image](https://user-images.githubusercontent.com/77464326/129355924-91bce877-04e4-4fd2-a2c8-d4f3c1a7ec52.png)

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 14.15.5 - C:\Program Files\nodejs\node.EXE       
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.67)
  npmPackages:
    @emotion/styled:  10.0.27
    @material-ui/core: ^4.12.3 => 4.12.3
    @material-ui/icons: ^4.11.2 => 4.11.2
    @material-ui/lab: ^4.0.0-alpha.60 => 4.0.0-alpha.60
    @material-ui/styles:  4.11.4
    @material-ui/system:  4.12.1
    @material-ui/types:  5.1.0
    @material-ui/utils:  4.11.2
    @material-ui/x-grid: ^4.0.0-alpha.37 => 4.0.0-alpha.37
    @material-ui/x-grid-data-generator: ^4.0.0-alpha.37 => 4.0.0-alpha.37
    @material-ui/x-license:  4.0.0-alpha.37
    @types/react:  17.0.0
    react: ^17.0.1 => 17.0.1
    react-dom: ^17.0.1 => 17.0.1
    styled-components: ^5.2.1 => 5.2.1
```
</details>

**Comment by oliviertassinari** [comment]
@matias-retargetly Thanks for opening an issue, however, without a reproduction, we can't help.

**Comment by emilsandvad** [comment]
I had the exact same issue with material-ui/data-grid": "4.0.0-alpha.37". Downgrading to "4.0.0-alpha.35" solved it. Only thing that would avoid the error was using an empty array for the _columns_ prop, causing nothing to be rendered.

**Comment by dryu** [comment]
I have exactly the same issue, and downgrading doesn't really work. Only happens in production deployments (when the app is compiled), and not in the development.

I'm not sure how to provide an example here, since this only happens after you compile the code and not before.

**Comment by oliviertassinari** [comment]
I have refactored this logic in #2343. Could you try https://pkg.csb.dev/mui-org/material-ui-x/commit/24f85ee3/@material-ui/data-grid or https://pkg.csb.dev/mui-org/material-ui-x/commit/24f85ee3/@material-ui/x-grid out?

**Comment by dryu** [comment]
@oliviertassinari, I've tried with "https://pkg.csb.dev/mui-org/material-ui-x/commit/24f85ee3/@material-ui/data-grid" and it now works without errors 🥳

**Comment by matias-retargetly** [comment]
same for me!

thanks!

**Comment by Mike-Loffland** [comment]
csb install worked for us as well

**Comment by EyuphanOzdemir** [comment]
Could you please explain how I can use the link (https://pkg.csb.dev/mui-org/material-ui-x/commit/24f85ee3/@material-ui/data-grid) that you say solved the issue? Thanks

**Comment by EyuphanOzdemir** [comment]
Ok I solved the problem now. İ used alpha-20 version and it worked. İt was a very annoying problem. Thanks to all
