### ISSUE TITLE
[DataGridPro] When checkboxSelectionVisibleOnly is enabled, select all checkbox selection is limited to the first 100 rows.

### ISSUE THREAD

**Issue by jacobcarrington** [mui-org/material-ui-x#2386]
We notice since upgrading from alpha.31, that now when we use the select all when checkboxSelectionVisibleOnly is enabled, it'll only select the first 100 rows.  Demo attached...

## Current Behavior 😯

Only the first 100 rows will be selected.

## Expected Behavior 🤔

All rows (up to 100000) should be selected.

## Steps to Reproduce 🕹

https://codesandbox.io/s/material-demo-100-row-selection-bug-7w0lk

Steps:

1. Select all rows using the checkbox in the header.

## Context 🔦

I'm trying to select all rows or all visible rows after filtering and if there are more then 100 this is problematic. 

## Your Environment 🌎

System:
    OS: macOS 11.2.2
    CPU: (8) x64 Apple M1
    Memory: 84.03 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Managers:
    Composer: 1.6.5 - /usr/local/bin/composer
    Homebrew: 2.7.7 - /usr/local/bin/brew
    pip3: 21.0.1 - /usr/local/bin/pip3
    RubyGems: 3.0.3 - /usr/bin/gem
  Utilities:
    CMake: 3.19.4 - /usr/local/bin/cmake
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.30.0 - /usr/local/bin/git
    Clang: 12.0.5 - /usr/bin/clang
    Ninja: 1.10.2 - /usr/local/bin/ninja
  Servers:
    Apache: 2.4.46 - /usr/local/bin/apachectl
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
  IDEs:
    Atom: 1.58.0
    Nano: 2.0.6 - /usr/bin/nano
    Vim: 8.2 - /usr/bin/vim
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Perl: 5.28.2 - /usr/bin/perl
    PHP: 8.0.1 - /usr/local/bin/php
    Python3: 3.8.2 - /usr/bin/python3
    Ruby: 2.6.3 - /usr/bin/ruby
  Databases:
    MySQL: 10.5.6 (MariaDB) - /usr/local/bin/mysql
    SQLite: 3.32.3 - /usr/bin/sqlite3
  Browsers:
    Chrome: 92.0.4515.159
    Chrome Canary: 95.0.4612.2
    Firefox: 87.0
    Safari: 14.0.3

## Order id 💳

Order #25887

**Comment by DanailH** [comment]
Hi, @jacobcarrington thanks for raising this. Yes. `checkboxSelectionVisibleOnly` only selects the visible rows (the paginated once) and since you have 100000 rows the virtualization kicks in. There are still pages it's just that they are now virtualized.

On another note - maybe we need to strictly define which rows count as `visible`.

**Comment by jacobcarrington** [comment]
We agree this is unexpected behaviour right? Users have no concept of virtualisation and why the selection would arbitrarily stop at 100 items - they are trying to select them all. It kind of defeats the purpose.

We have this component in a production product, that has common workflows effected by this change and we'll likely not be able to update until it's addressed.

**Comment by oliviertassinari** [comment]
@jacobcarrington Sorry for the confusion. 100 is the page size of your demo, but pagination is disabled 😆. It's unrelated to how the virtualization internally paginates and is a private notion that could change at any moment.

Regarding the solution, I believe the pagination needs to compute the same state:

https://github.com/mui-org/material-ui-x/blob/badc3bd0b0443b1145d196bf3e1e79476587237c/packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboardNavigation.ts#L117

Maybe this is enough?

```diff
diff --git a/packages/grid/_modules_/grid/hooks/features/pagination/gridPaginationSelector.ts b/packages/grid/_modules_/grid/hooks/features/pagination
/gridPaginationSelector.ts
index e0a8a7b2..de53db74 100644
--- a/packages/grid/_modules_/grid/hooks/features/pagination/gridPaginationSelector.ts
+++ b/packages/grid/_modules_/grid/hooks/features/pagination/gridPaginationSelector.ts
@@ -1,6 +1,7 @@
 import { createSelector } from 'reselect';
 import { GridState } from '../core/gridState';
 import { visibleSortedGridRowIdsSelector } from '../filter/gridFilterSelector';
+import { gridContainerSizesSelector } from '../../root/gridContainerSizesSelector';
 import { GridPaginationState } from './gridPaginationState';

 export const gridPaginationSelector = (state: GridState): GridPaginationState => state.pagination;
@@ -8,9 +9,10 @@ export const gridPaginationSelector = (state: GridState): GridPaginationState =>
 export const gridPaginatedVisibleSortedGridRowIdsSelector = createSelector(
   gridPaginationSelector,
   visibleSortedGridRowIdsSelector,
-  (pagination, visibleSortedRows) => {
+  gridContainerSizesSelector,
+  (pagination, visibleSortedRows, containerSizes) => {
     const firstSelectedRowIndex = pagination.page * pagination.pageSize;
-    const lastSelectedRowIndex = firstSelectedRowIndex + pagination.pageSize;
+    const lastSelectedRowIndex = firstSelectedRowIndex + containerSizes!.virtualRowsCount;

     return visibleSortedRows.slice(firstSelectedRowIndex, lastSelectedRowIndex);
   },
```

**Comment by flaviendelangle** [comment]
The term `visible` is a bit misleading here

At first I thought `visible` was what is in the viewport. And if so, then  it should select 10 lines in the demo.
But I don't think selecting the element in the viewport is really a major usecase.

If `visible` means `in the current page` then I'm not fan of the wording, but I agree it should select the whole set when the pagination is disabled.

I'm doing a PR :+1:

**Comment by oliviertassinari** [comment]
An update on the product direction that we took. In the end, we went toward adding a warning when
```jsx
<DataGrid checkboxSelectionVisibleOnly={true} pagination={false} />
````

is set.
