### ISSUE TITLE
[DataGrid] renderHeader doesn't update GridColDef.width parameter when flex is specified in column spec

### ISSUE THREAD

**Issue by Ryshackleton** [mui-org/material-ui-x#2392]
The column spec's `renderHeader` function doesn't update the `GridColDef.width` parameter when `flex` is specified in column spec. This functionality worked in version `4.0.0-alpha.35`, but doesn't in `4.0.0-alpha.37`.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When `flex` is specified in the column specifications, the `colDef.width` property _is not updated_ when the column width changes.

## Expected Behavior 🤔

When `flex` is specified in the column specifications, the `colDef.width` property _should be updated_ when the column width changes.

## Steps to Reproduce 🕹

https://codesandbox.io/s/material-demo-forked-0yxgn?file=/demo.js

Steps:

1. Resize the page to update column widths
2. Expect column property to update when column width changes
3. In the sandbox Dependencies, change `@material-ui/data-grid` version to `4.0.0-alpha.35`.
4. Upon reload, notice that the width property now updates appropriately.

## Context 🔦

I relied on this behavior in 4.0.0-alpha.35 to handle sizing the header height for a component, now I can't use it.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
  System:
    OS: macOS 11.5.2
  Binaries:
    Node: 14.17.4 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.14 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.159
    Edge: Not Found
    Firefox: Not Found
    Safari: 14.1.2
  npmPackages:
    @material-ui/core: ^4.12.3 => 4.12.3
    @material-ui/data-grid: ^4.0.0-alpha.37 => 4.0.0-alpha.37
    @material-ui/lab: ^4.0.0-alpha.60 => 4.0.0-alpha.60
    @material-ui/styles:  4.11.4
    @material-ui/system:  4.12.1
    @material-ui/types:  5.1.0
    @material-ui/utils:  4.11.2
    @types/react:  17.0.3
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2

</details>

Chrome browser.

**Comment by ZeeshanTamboli** [comment]
The `width` property of the columns is no longer updated with the actual width of of the column. Use the new `computedWidth` property in the callbacks instead. This was mentioned and changed in `v4.0.0-alpha.36`.

Checkout `v4.0.0-alpha.36` release notes https://github.com/mui-org/material-ui-x/releases/tag/v4.0.0-alpha.36

CodeSandbox with the new `computedWidth` property: https://codesandbox.io/s/material-demo-forked-l03gq?file=/demo.js

Hope it helps.

**Comment by Ryshackleton** [comment]
Ah, excellent. Sorry I missed that. Thanks @ZeeshanTamboli!
