### ISSUE TITLE
[DataGrid] Add operator to filter for rows that contain any of the specified values

### ISSUE THREAD

**Issue by jb-thery** [mui-org/material-ui-x#2437]
hello, 

There is a lack of functionality for the xGrid, it would be necessary that when we apply filters on several columns we can also use several logical operators.

For example being able to do:

```
columnA === "valueA"   OR   columnA === "valueB"  AND   columnB === "valueX"
```

Have a nice day

**Comment by m4theushw** [comment]
Having different logical operators adds a new level of complexity. There're different forms to interpret this expression. Using the precedende, it would be read as 1, but in a practical use case I would prefer it to work as 2.

1. `columnA === "valueA"   OR   (columnA === "valueB"  AND   columnB === "valueX")`

2. `(columnA === "valueA"   OR   columnA === "valueB")  AND   columnB === "valueX"`

This notion of parenthesis is missing in the grid but it could be added in the future. For now, if you are using the `singleSelect` column type, we could add an `is one of` operator to filter for rows whose cell is equal to one of the specified values.

An example from Elastic's Kibana:

![image](https://aws1.discourse-cdn.com/elastic/original/3X/d/5/d5b6b65fb5cb499991955544217d9c2576e32330.gif)

**Comment by jbty** [comment]
```
is one of
```

that would be exactly what I would need

**Comment by flaviendelangle** [comment]
This makes me think of #670 
At one point we should work on a more powerful filtering engine but it requires to correctly think the UI and the structure to avoid creating something unusable.

**Comment by m4theushw** [comment]
I'm leaving this one for the community. If anyone wants to try to implement the new filter operator, the Autocomplete can be used. The demo https://material-ui.com/components/autocomplete/#multiple-values can be used as a guide to implement the same UX from https://github.com/mui-org/material-ui-x/issues/2437#issuecomment-903868956.

**Comment by tmurvv** [comment]
Is this on the road map yet? So far as I can tell, "isOneOf" or "isAnyOf" will not work for the following logic because there are three different fields involved. I need:

columnA === "valueA"   OR   (columnB === "valueB"  AND   columnC === "valueC")
