### ISSUE TITLE
Data Grid default props for paginationMode

### ISSUE THREAD

**Issue by danhooper** [mui-org/material-ui-x#2439]
- [X ] The issue is present in the latest release.
- [X ] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Setting paginationMode in the default theme properties does not work, this may apply to other properties as well. Some properties are picked up however.

## Expected Behavior 🤔

Setting paginationMode to server in the default theme properties should be used in DataGrid instances.

## Steps to Reproduce 🕹

https://codesandbox.io/s/material-data-grid-default-props-p7bw4?file=/demo.tsx

Steps:

1. Go to the second page of results, the result table is blank (the DataGrid instance did not use the default paginationMode set in the theme)
2. Set the paginationMode="server" on the DataGrid instance, the second page of results is no longer blank.

## Context 🔦

The DataGrid appears to ignore the default property setting as of 4.0.0-alpha.36 but it works in 4.0.0-alpha.35

## Your Environment 🌎
This is after a rollback to 4.0.0-alpha.35. Just updating datagrid causes the problem to come back.

<details>
  <summary>`npx @material-ui/envinfo`</summary>
npx @material-ui/envinfo
npx: installed 2 in 7.601s

  System:
    OS: macOS 11.5.2
  Binaries:
    Node: 14.17.4 - /usr/local/opt/node@14/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.14.14 - /usr/local/opt/node@14/bin/npm
  Browsers:
    Chrome: 92.0.4515.159
    Edge: 92.0.902.78
    Firefox: 89.0.2
    Safari: 14.1.2
  npmPackages:
    @material-ui/core: ^4.12.3 => 4.12.3
    @material-ui/data-grid: ^4.0.0-alpha.35 => 4.0.0-alpha.35
    @material-ui/icons: ^4.11.2 => 4.11.2
    @material-ui/lab: ^4.0.0-alpha.60 => 4.0.0-alpha.60
    @material-ui/pickers: ^3.3.10 => 3.3.10
    @material-ui/styles:  4.11.4
    @material-ui/system:  4.12.1
    @material-ui/types:  5.1.0
    @material-ui/utils:  4.11.2
    @types/react: ^17.0.18 => 17.0.18
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.3.5 => 4.3.5
  
```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
https://codesandbox.io/s/material-data-grid-default-props-forked-8py0n

Fixed by #2433 

We set default props to the React component above the merge with the theme properties
So we always have a default value when getting to the theme properties injection script.

My PR is dropping the default props and setting the internal default values later on so it's working.
