### ISSUE TITLE
[DataGrid] Cannot override CSS in the theme

### ISSUE THREAD

**Issue by perfectdeed** [mui-org/material-ui-x#2450]
- [x ] The issue is present in the latest release.
- [x ] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

My problem is I can not get rid of the outline of a focused cell in the datagrid. Which is in itself an issue. That outline should not be visible when the cell is not editable. But well, that's another issue.

Now, when I want to override that behavior using the theme as I do with other components using:

`const theme = createMuiTheme({
  overrides: {
    MuiDataGrid: {
      cell: {
        '&:focus': {
          outline: 'none',
        },
        '&:focus-within': {
          outline: 'none',
        },
      },
    },`
    
I got an error because the MuiDataGrid property is not define in the override type definition (override.d.ts).
Even if if I use "// @ts-nocheck" (very bad), it doesn't work.

I followed the instruction in this page:
[http://5.9.10.113/66576742/material-ui-override-muidatagrid-columnscontainer-css](http://5.9.10.113/66576742/material-ui-override-muidatagrid-columnscontainer-css) to no avail.

I don't think adding a css file only to override one class is a very good practice.

## Expected Behavior 🤔

I could override MuiDatagrid in the theme of the application.

Sorry, I already spent too much time for such a trivial task, I have no time to create a sandbox just for that. It's pretty self explanory.

I don't see the point of highlighting an element for no reason if it doesn't have a special state or action on that element.

## Order id 💳

Order #28579

**Comment by ZeeshanTamboli** [comment]
>  But if it the issue will be addressed in V5, it's OK

This works now on latest version `5.0.0-beta.1`.

CodeSandbox with the example - https://codesandbox.io/s/datagriddemo-material-demo-forked-8lyh9?file=/demo.tsx

To see how it works with TypeScript follow https://mui.com/components/data-grid/getting-started/#typescript

**Comment by Nitzperetz** [comment]
Hey there, I an interested in overriding default props/styling for GridActionsCellItem, and not only the DataGrid component.
Would that be possible in the future? could not find an open issue.

**Comment by ZeeshanTamboli** [comment]
> Hey there, I an interested in overriding default props/styling for GridActionsCellItem, and not only the DataGrid component. Would that be possible in the future? could not find an open issue.

@flaviendelangle

**Comment by flaviendelangle** [comment]
I'm not working on the data grid anymore
@cherniavskii if you want to have a look :+1:

**Comment by cherniavskii** [comment]
Hey @Nitzperetz 
Could you open a new issue describing what you are missing in the `GridActionsCellItem` customization?
Thanks!
