### ISSUE TITLE
[DataGrid] Visible / hidden columns are not preserved when reloading the page

### ISSUE THREAD

**Issue by pravinkottawar** [mui-org/material-ui-x#2466]
In most of the applications saving state or preferences specific to users is important.
I am using DataGrid which has 10 columns with show / hide functionality but it is not saving the state.
If user logs out show / hide changes will get a reset.
I am not sure if saving state of column is possible in DataGrid .
Can some community member suggest how to save column states ?

**Comment by flaviendelangle** [comment]
Duplicate #820 

It's a subject we need to address, we are currently working on removing non-serializable items from the state

In the meantime, you could use the `onStateChange` undocumented callback which is called any time the state changes.

```ts
<DataGrid {...otherProps} onStateChanges={state => console.log(state.columns.lookup)
```

**Comment by pravinkottawar** [comment]
thank you . I did get the solution by using onchange event in componentsProps
