### ISSUE TITLE
[question] Issue with jumping x-grid starting from alpha.37

### ISSUE THREAD

**Issue by bartvde** [mui-org/material-ui-x#2508]
### Order id 💳

25229

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

The grid jumps, starting with alpha.37 (alpha.36 is fine). When clicking a row and then scrolling until this row is not visible anymore, the grid jumps.

### The problem in depth 🔍

Video of what happens in alpha.36:
![Peek 2021-08-31 12-20](https://user-images.githubusercontent.com/319678/131485923-ec5cb7f8-3b96-48fb-a666-937cbccf4a61.gif)

Video of what happens in alpha.37 and later:
![Peek 2021-08-31 12-20a](https://user-images.githubusercontent.com/319678/131486022-402c38ac-2fb4-4df0-bfda-5ce5f5079280.gif)

### Your Environment 🌎

Chrome: Version 92.0.4515.159 (Official Build) (64-bit)

  System:
    OS: Linux 5.11 Ubuntu 21.04 (Hirsute Hippo)
  Binaries:
    Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v16.3.0/bin/yarn
    npm: 7.20.5 - ~/.nvm/versions/node/v16.3.0/bin/npm
  Browsers:
    Chrome: 92.0.4515.159
    Firefox: 91.0.2
  npmPackages:
    @material-ui/codemod: ^4.5.0 => 4.5.0 
    @material-ui/core: ^4.12.3 => 4.12.3 
    @material-ui/icons: ^4.11.2 => 4.11.2 
    @material-ui/lab: 4.0.0-alpha.60 => 4.0.0-alpha.60 
    @material-ui/pickers: ^3.3.10 => 3.3.10 
    @material-ui/styles:  4.11.4 
    @material-ui/system:  4.12.1 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @material-ui/x-grid: ^4.0.0-alpha.37 => 4.0.0-alpha.37 
    @material-ui/x-license:  4.0.0-alpha.37 
    @types/react: ^17.0.19 => 17.0.19 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.3.5 => 4.3.5

**Comment by m4theushw** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://material-ui.com/r/issue-template) _may_ be a good starting point. Thank you!

**Comment by bartvde** [comment]
will do today

**Comment by bartvde** [comment]
@m4theushw you can reproduce it here: https://eqrt4n.stackblitz.io

![Peek 2021-09-01 09-20](https://user-images.githubusercontent.com/319678/131629271-38cb3a3f-2b09-4dee-877a-b92314d98a3d.gif)

**Comment by zzossig** [comment]
Jumping issue still exist.
This is just happened sometimes.
In my case, when I click checkbox or when cell contains image, jumping happened.
This bug is very difficult to reproduce so thank you @bartvde for taking time.
I don't want my users experience this bug.

**Comment by bartvde** [comment]
@m4theushw any update on this one? TIA

**Comment by Primajin** [comment]
This prevents us from upgrading beyond `alpha.36` to `4.0.0` as our customers rely on the steady position of the table

**Comment by m4theushw** [comment]
We have a race condition between the selection and the focus management introduced in #2239. When a cell is clicked, the internal state is updated to store which cell received focus. The problem is that the selection is also listing to the click event. That way, whenever a cell is selected, the grid rerenders, but still with the old focused cell in the state. When the old focused cell is rendered it calls `.focus()`, which makes the browser to try to scroll to it, so the jump.

As a workaround, you can disable the selection on click with:

```jsx
<DataGridPro disableSelectionOnClick />
```

You can use the `checkboxSelection` to still be able to select rows.

**Comment by Primajin** [comment]
Great thanks - what's the anticipated release cycle for these fixes? Roughly - doesn't need to be super exact. Just for us to know when to plan for upgrading from `alpha.36` to `4.0.1`.

**Comment by m4theushw** [comment]
@Primajin This bug fix will be included in the next release (probably next week), which will be v5.0.0-beta.0. However, v4 is not dead. Some of the bug fixes added to v5 will be cherry-picked to the older version. This includes this fix. We plan to release `4.0.1` once there're enough fixes to do a big release, maybe at the end of this month.

**Comment by bartvde** [comment]
@m4theushw can you confirm if this made it into 4.0.1?

**Comment by m4theushw** [comment]
> @m4theushw can you confirm if this made it into 4.0.1?

It was not included. You can use MUI X v5 with MUI Core v4 by changing the CSS prefixes used. Here's an example of how to do it: https://codesandbox.io/s/datagriddemo-material-demo-forked-8myv0?file=/src/demo.js
