### ISSUE TITLE
Server side pagination in DataGrid

### ISSUE THREAD

**Issue by pravinkottawar** [mui-org/material-ui-x#2518]
Hi I am trying to implement server side pagination in Data Grid.
Is there any solution or example which can help ?
As I am fetching rows dynamically from db its not possible to give rowCount.
I have checked material ui datagrid pagination documentation . Here is current code

```
import * as React from 'react';
import TextField from '@material-ui/core/TextField';
import PropTypes from 'prop-types';
import {DataGrid, GridToolbarContainer, GridToolbarExport} from '@material-ui/data-grid';
import {makeStyles} from '@material-ui/styles';
import SearchIcon from '@material-ui/icons/Search';
import IconButton from '@material-ui/core/IconButton';
import ClearIcon from '@material-ui/icons/Clear';
import Button from '@material-ui/core/Button';

function escapeRegExp(value) {
	return value.replace(/[-[\]{}()*+?.,\\^$|#\s]/g, '\\$&');
}

const useStyles = makeStyles(theme => ({
	root: {
		'& .MuiDataGrid-renderingZone': {
			maxHeight: 'none !important'
		},
		'& .MuiDataGrid-cell': {
			lineHeight: 'normal !important',
			maxHeight: 'none !important',
			whiteSpace: 'normal',
			minWidth: 'none',
			marginTop: 'auto'
		},
		'& .MuiDataGrid-row': {
			maxHeight: 'none !important'
		},
		'& .MuiButton-root': {
			float: 'right'
		},
		'.MuiFormControl-root': {
			width: '90%'
		}
	}
}));
function CustomToolbar() {
	return (
		<GridToolbarContainer style={{float: 'right'}}>
			<GridToolbarExport />
		</GridToolbarContainer>
	);
}
function loadServerRows(url) {
	return new Promise(resolve => {
		fetch(url)
			// .then(resp => resp.json())
			.then(resp => {
				console.log(resp + ' page response');
				console.log(url + ' url is');
				console.log(Object.keys(resp));
				// resolve({
				// 	data: resp,
				// 	page: 1,
				// 	totalCount: 20
				// });
			});
	});
}

function QuickSearchToolbar(props) {
	const classes = useStyles();
	return (
		<div className="col-sm-12">
			<div className="col-sm-10">
				<TextField
					style={{width: '100%', marginTop: '10px', marginLeft: '-25px'}}
					variant="standard"
					value={props.value}
					onChange={props.onChange}
					placeholder="Search…"
					InputProps={{
						startAdornment: <SearchIcon fontSize="small" />,
						endAdornment: (
							<IconButton
								title="Clear"
								aria-label="Clear"
								size="small"
								style={{visibility: props.value ? 'visible' : 'hidden'}}
								onClick={props.clearSearch}
							>
								<ClearIcon fontSize="small" />
							</IconButton>
						)
					}}
				/>
			</div>
			<div className="col-sm-2">
				<GridToolbarContainer style={{float: 'right'}}>
					<GridToolbarExport />
				</GridToolbarContainer>
			</div>
		</div>
	);
}

QuickSearchToolbar.propTypes = {
	clearSearch: PropTypes.func.isRequired,
	onChange: PropTypes.func.isRequired,
	value: PropTypes.string.isRequired
};

export default function DataTable(props) {
	const [searchText, setSearchText] = React.useState('');
	const [rows, setRows] = React.useState(props.records);
	console.log(typeof rows);
	console.log(Object.keys(rows).length);
	const [page, setPage] = React.useState(0);
	const [loading, setLoading] = React.useState(false);
	const [url, setUrl] = React.useState(props.searchUrl);
	console.log(props.searchUrl);
	const classes = useStyles();
	const [columns, setColumns] = React.useState(props.headers);
	//console.log(props.showFilters + ' showFilters ');
	//var [hideCol, setHideColumns] = React.useState(props.hideCol);
	const requestSearch = searchValue => {
		setSearchText(searchValue);
		const searchRegex = new RegExp(escapeRegExp(searchValue), 'i');
		//console.log('Search Text' + searchValue);
		const filteredRows = props.records.filter(row => {
			return Object.keys(row).some(field => {
				return field && row[field] ? searchRegex.test(row[field].toString()) : '';
			});
		});
		setRows(filteredRows);
	};

	React.useEffect(() => {
		let active = true;
		console.log('inside useEffect');
		(async () => {
			setLoading(true);
			const newRows = await loadServerRows(url);

			if (!active) {
				return;
			}

			setRows(newRows);
			setLoading(false);
		})();

		return () => {
			active = false;
		};
	}, [page]);

	return (
		<div className={classes.root} style={{height: '700px', verticalAlign: 'middle'}}>
			<div className="col-sm-12" style={{float: 'right'}}>
				{!props.showFilters ? (
					<Button color="primary" onClick={() => props.saveColumnAsPreference(columns)}>
						Save as preference
					</Button>
				) : (
					''
				)}
			</div>
			<div className="col-sm-12" style={{height: '700px', verticalAlign: 'middle'}}>
				<DataGrid
					components={{Toolbar: props.showSearchBar ? QuickSearchToolbar : CustomToolbar}}
					rows={rows}
					columns={
						props.showFilters
							? columns
							: columns.map(column => ({
									...column,
									filterable: false
							  }))
					}
					pageSize={2}
					pagination
					rowsPerPageOptions={[2]}
					paginationMode="server"
					onPageChange={newPage => setPage(newPage)}
					loading={loading}
					componentsProps={{
						preferencesPanel: {
							onChange: event => {
								const tempCols = [...columns];
								//const hideCol = '';'
								tempCols.forEach((col, i) => {
									if (col.field === event.target.name) {
										tempCols[i].hide = !tempCols[i].hide;
										//	hideCol = hideCol.concat(col.field + ',');
									}
								});
								//							console.log(hideCol + ' List of Hide Columns');
								setColumns(tempCols);
								//							setHideColumns(hideCol);
							}
						},
						toolbar: {
							value: searchText,
							onChange: event => requestSearch(event.target.value),
							clearSearch: () => requestSearch('')
						}
					}}
				/>
			</div>
		</div>
	);
}

```

**Comment by DanailH** [comment]
Hi, @pravinkottawar thanks for raising this. You said you already checked the docs, so this page I assume https://material-ui.com/components/data-grid/pagination/#server-side-pagination.
If we are talking about pagination specifically you would need to provide the `rowCount` so that the grid knows how many pages there going to be.

If on the other hand there is no way of knowing what the total `rowCount` would be I would suggest you use a client-side solution. More specifically load the rows on scroll. You can check the Infinite Loading feature here for more information https://material-ui.com/components/data-grid/rows/#infinite-loading. Keep in mind that this is a paid feature.

**Comment by m4theushw** [comment]
This is a bit similar to what the user from https://github.com/mui-org/material-ui-x/issues/2509#issue-983698597 is trying to do. Basically, you have to override the pagination component.

**Comment by pravinkottawar** [comment]
@m4theushw  its not same thing friend. I am not trying to hide row count here. If you can give example of override the pagination component for DataGrid it will be helpful.

**Comment by pravinkottawar** [comment]
@DanailH Even if I have row count the material ui documentation does not give any idea of how rows are fetched and page number is updated when clicked on next and previous button . If you can give example it will make things more clear

**Comment by m4theushw** [comment]
> I am not trying to hide row count here. If you can give example of override the pagination component for DataGrid it will be helpful.

The user in https://github.com/mui-org/material-ui-x/issues/2509#issue-983698597 doesn't have the row count as you. He is setting `rowCount={Number.MAX_SAFE_INTEGER}` just to give the grid a value to work with. Then, he added [cursor-pagination](https://material-ui.com/components/data-grid/pagination/#cursor-based-pagination) but because the row count is a fake number it needs to be hidden. I think you can follow the same path and override the pagination component, here is an example: https://material-ui.com/components/data-grid/components/#pagination.

**Comment by pravinkottawar** [comment]
@m4theushw  Now I have total rows param. I have also attached code . The example which you suggested is for x datagrid which is paid version also all examples in material ui documentation does not give any idea of how rows are fetched and page number is updated when clicked on next and previous button . If you can give example it will make things more clear

**Comment by DanailH** [comment]
@pravinkottawar this example showcases how to handle fetching of rows (although it isn't a true fetch) https://codesandbox.io/s/r0biy?file=/demo.js . It's taken from here https://material-ui.com/components/data-grid/pagination/#server-side-pagination

Basically, the `DataGrid` doesn't automatically fetch the needed rows, you would need to handle that by yourself for now. In the future, we may add a data layer adaptor but for now, we don't provide such functionality.

If this is still not 100% clear it would be best if you could provide us with a CodeSandbox reproduction so we can look at the actual working (or not working) example and discuss it. You can use this [CodeSandbox template](https://codesandbox.io/s/material-ui-issue-next-o7xkt) as a starting point.
