### ISSUE TITLE
apiRef.current.setRowMode is not a function

### ISSUE THREAD

**Issue by linojon** [mui-org/material-ui-x#2521]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current Behavior 😯

Dont know if this is a bug or a misunderstanding.
Using @mui/x-data-grid-pro i'm trying to change a row to edit mode. On my page i have an Add button that adds a new row to the datagrid. I also want it to set the row to edit mode. I tried calling apiRef.current.setRowMode(newId, "edit"); but get an error apiRef.current.setRowMode is not a function

see https://codesandbox.io/s/cocky-tamas-yjbi7?file=/src/Demo.tsx:717-758

### Steps to Reproduce 🕹

Steps:

1.
2.
3.
4.

**Comment by m4theushw** [comment]
You didn't set the `apiRef` prop.

```tsx
const apiRef = useGridApiRef();

<DataGridPro apiRef={apiRef} />
```

Once you do that you can access the API. Although. in your example you're inserting a new row but the grid doesn't know about it when `apiRef.current.setRowMode` is called, so there's going to be another error. Wrapping `apiRef.current.setRowMode` in a `setTimeout` solves this other problem:

```tsx
function handleAdd() {
  const newId = rows.length + 1;
  setRows([...rows, { id: newId, color: "asd", fruit: "qwe" }]);
  setTimeout(() => {
    apiRef.current.setRowMode(newId, "edit");
  });
}
```

**Comment by m4theushw** [comment]
> With the new row in edit mode, i'd like: if the user clicks away from the row, it triggers an event i can check if the fields are blank and remove the added empty row.

When the `rowEditStop` event is fired the row already left the edit mode. What you need to do is [prevent the default behavior](https://material-ui.com/components/data-grid/events/#disabling-the-default-behavior), then call `apiRef.current.getEditRowsModel` to get the value that the user is entering and check if it's empty.

> Is there a way to force focus on a specific cell? see sandbox deno:

Yes, this [demo](https://material-ui.com/components/data-grid/editing/#control-with-external-buttons) also has an Add Record button and it focus the first cell of the new row.

**Comment by linojon** [comment]
Thank you again. That works. Here I thought I’d read the documentation thoroughly but I seem to keep missing what I’m looking for.
