### ISSUE TITLE
[DataGrid] Filters on Columns with type: 'number' do not handle 0

### ISSUE THREAD

**Issue by mmcelroy90** [mui-org/material-ui-x#2524]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current Behavior 😯

When you filter on a column with a type of 'number' and type in 0, no changes or filtering occurs. All other numbers work correctly.

### Expected Behavior 🤔

You should be able to filter on the number 0.

### Steps to Reproduce 🕹

Steps:
https://codesandbox.io/s/material-demo-forked-ke7ki

1. Filter on any number (age column) other than 0, you will received expected results
2. Filter on 0 (age column), nothing happens

### Context 🔦

I am unable to filter the number 0 on any of my number columns.

**Comment by flaviendelangle** [comment]
It seems to be a class `!value` instead of `value != null` when we check if their is a value in the cell...
I'll make a fix :+1:
