### ISSUE TITLE
[DataGrid] The DataGrid is not compatible with the new package name of the core repository

### ISSUE THREAD

**Issue by alb7h** [mui-org/material-ui-x#2527]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When you replace the old `@material-ui/*` with the newer `@mui/*` packages for the rc versions, the datagrid is breaking.

```
Could not find dependency: '@material-ui/core' relative to '/node_modules/@mui/x-data-grid/dist/index-esm.js'
```

### Expected behavior 🤔

It should work with the new package names

### Steps to reproduce 🕹

Click link https://codesandbox.io/s/vigilant-noyce-xx89p?file=/src/Demo.tsx

or alternatively:

1. Remove any `@material-ui/*` packages
2. Add `@mui/*` packages
3. Restart app
4. 💥

### Context 🔦

No context, but a simple workaround for now. 

You can add this to package.json to alias the new packages to the old
```json
    "@material-ui/core": "npm:@mui/material@5.0.0-rc.0",
    "@material-ui/styles": "npm:@mui/styles@5.0.0-rc.0",
```

You can also do this via webpack but for some reason, it worked with storybook's webpack but not with nextjs's webpack.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
npx: installed 2 in 3.184s

  System:
    OS: macOS 11.4
  Binaries:
    Node: 14.17.3 - ~/.volta/tools/image/node/14.17.3/bin/node
    Yarn: 3.0.1 - ~/.volta/tools/image/yarn/1.22.10/bin/yarn
    npm: 6.14.13 - ~/.volta/tools/image/node/14.17.3/bin/npm
  Browsers:
    Chrome: 92.0.4515.159
    Edge: Not Found
    Firefox: Not Found
    Safari: 14.1.1
```
</details>

### Order ID 💳 (optional)

28357

**Comment by Edelf** [comment]
Same is happening here:

```
<dir>/node_modules/@mui/x-data-grid/dist/index-esm.js
Module not found: Can't resolve '@material-ui/core/Badge' in '<dir>\node_modules\@mui\x-data-grid\dist'
```

**Comment by flaviendelangle** [comment]
The problem with the last version is that `x-data-grid` has `@material-ui/core` and since the last release of the core, the package is now named `@mui/material` (see https://github.com/siriwatknp/material-ui/blob/release/5.0.0-rc.0/CHANGELOG.md#muimaterial500-rc0)

The next release of the Grid should solve it

**Comment by Edelf** [comment]
Is there any temporary solution to allow @mui/x-data-grid with @mui/core? Or are we forced to keep using the @material-ui beta?

**Comment by m4theushw** [comment]
> Is there any temporary solution to allow @mui/x-data-grid with @mui/core? Or are we forced to keep using the @material-ui beta?

Yes, you can add a few aliases to your `webpack.config.js` or `babel.config.js`. We use this [trick](https://github.com/mui-org/material-ui-x/pull/2441/files#diff-2ed4f5b03d34a87ef641e9e36af4a98a1c0ddaf74d07ce93665957be69b7b09aR20) to make the docs work with the RC version.

```js
'@material-ui/core': '../node_modules/@mui/material'
'@material-ui/styles': '../node_modules/@mui/styles'
'@material-ui/icons': '../node_modules/@mui/icons-material'
'@material-ui/lab': '../node_modules/@mui/material'
```

**Comment by rart** [comment]
@m4theushw is that achievable with CRA without ejecting or using things like cra rewired and such?

**Comment by stevenkampen** [comment]
@rart No I don't believe so.

**Comment by m4theushw** [comment]
@rart @stevenkampen Yes, I managed to make it work with v5 by using https://github.com/aze3ma/react-app-rewire-aliases. I didn't have to eject. I used the following aliases:

```js
const rewireAliases = require('react-app-rewire-aliases');
const path = require('path');

module.exports = function override(config, env) {
  config = rewireAliases.aliasesOptions({
    '@material-ui/core': path.resolve(__dirname, './node_modules/@mui/material'),
    '@material-ui/styles': path.resolve(__dirname, './node_modules/@mui/styles'),
  })(config, env);
  return config;
};
```

**Comment by rart** [comment]
I was hoping not to use rewire stuff either.

I tried `yarn add @material-ui/core@npm:@mui/material@5.0.0-rc.1 @material-ui/styles@npm:@mui/styles@5.0.0-rc.1` which in theory should just work. It did give me some trouble but after clearing node modules and yarn add/remove a couple of times it seems to be working. 

At least the grid errors seem to be gone; I'm having all sorts of other issues with the upgrade in general, though. I'm a bit stuck on `theme.spacing is not a function` at the moment. 🙁

**Comment by callmeberzerker** [comment]
This is kinda stupid @material-ui team. Before release -> naming "tidying up" is non-sensical. The upgrade path from v4 to v5 should have been smoother, and while I understand that breaking changes need to happen - at least plan them accordingly and let people who migrated early on the @next train to have smooth sailing. Now it's just a clusterfuck, massive renames, semi working codemods and on top of that core libraries that don't work with each other. 🤦

Do better.

**Comment by rodrigonzalz** [comment]
> > Is there any temporary solution to allow @mui/x-data-grid with @mui/core? Or are we forced to keep using the @material-ui beta?
> 
> Yes, you can add a few aliases to your `webpack.config.js` or `babel.config.js`. We use this [trick](https://github.com/mui-org/material-ui-x/pull/2441/files#diff-2ed4f5b03d34a87ef641e9e36af4a98a1c0ddaf74d07ce93665957be69b7b09aR20) to make the docs work with the RC version.
> 
> ```js
> '@material-ui/core': '../node_modules/@mui/material'
> '@material-ui/styles': '../node_modules/@mui/styles'
> '@material-ui/icons': '../node_modules/@mui/icons-material'
> '@material-ui/lab': '../node_modules/@mui/material'
> ```

Tried this and unless I am doing it wrong (possibly xd) it is not working for me.
In my case I use Next and set up on the next.config.js the following

```
config.resolve.alias = {
      ...config.resolve.alias,
      '@material-ui/core': path.resolve(__dirname, './node_modules/@mui/material'),
      '@material-ui/styles': path.resolve(__dirname, './node_modules/@mui/styles'),
      '@material-ui/icons': path.resolve(__dirname, './node_modules/@mui/icons-material'),
      '@material-ui/lab': path.resolve(__dirname, './node_modules/@mui/lab'),
    };
```
I have tried without the whole `path.resolve` and multiple variations, but none have worked.
I think this only works with your own imports, will not work for the imports of an external dependency.
For example I get the same issue with notistack, that also hasn't made a release for the `@mui` packages.

**Comment by Khatib-Abbas** [comment]
For Next.js version  i use this config, work with 95% (litle css problem).

If you have any sugestions

{  
  "presets": \["next/babel"\],  
  "plugins": \[  
    \["module-resolver", {  
      "root": \["./"\],  
      "alias": {  
        "@material-ui/core": "../node\_modules/@mui/material",  
        "@material-ui/styles": "../node\_modules/@mui/styles",  
        "@material-ui/icons": "../node\_modules/@mui/icons-material",  
        "@material-ui/lab": "../node\_modules/@mui/material"  
      }  
    }\]  
  \]  
}

**Comment by LeoLozes** [comment]
After some testing, I got it working with:

```
    resolve: {
      alias: {
        '@material-ui/core': '@mui/material',
        '@material-ui/styles': '@mui/styles',
        '@material-ui/icons': '@mui/icons-material',
        '@material-ui/lab': '@mui/material'
      }
    }
```
in my `webpack.config.ts`. 

Thanks!

**Comment by m4theushw** [comment]
For people that need a v5 compatible version and don't want to wait for the next release, you can use packages generated by #2571. 

```json
"@mui/x-data-grid-pro": "https://pkg.csb.dev/mui-org/material-ui-x/commit/9f39f255/@mui/x-data-grid-pro",
"@mui/x-data-grid": "https://pkg.csb.dev/mui-org/material-ui-x/commit/9f39f255/@mui/x-data-grid",
```

Example: https://codesandbox.io/s/material-demo-forked-shhg4?file=/demo.js

---

@Khatib-Abbas What is your "litle css problem"? It might be some conflict between jss and emotion, it happed with me.

**Comment by rart** [comment]
Thanks, @m4theushw!

Sorry for the off-topic question but this is pretty useful: how is it that one manages to publish like that? I didn't manage to find docs or anything for `pkg.csb.dev`.

**Comment by m4theushw** [comment]
@rart https://codesandbox.io/docs/ci

**Comment by jbty** [comment]
Hello, there is any update with this issue ?

**Comment by flaviendelangle** [comment]
@jbty you can follow this comment to have the new naming today https://github.com/mui-org/material-ui-x/issues/2527#issuecomment-916062202

Otherwise, we have merged the migration.
The release should take place at the end of this week.
