### ISSUE TITLE
[DataGrid] Filters for number values are not applied when the comparison value is 0

### ISSUE THREAD

**Issue by paolololol** [mui-org/material-ui-x#2560]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When applying a filter to a numeric column in a DataGrid or DataGridPro component, inserting a value of 0 doesn't apply any comparison.

### Expected behavior 🤔

Filtering for "= 0" should select only rows in which the value is 0, same for ">", "<", etc.

### Steps to reproduce 🕹

Steps:
1. Go to https://stackblitz.com/edit/mc5823?file=demo.js
2. Filter for `age = 0`
3. All the rows are still displayed, rather than only showing Daenerys

### Context 🔦

The issue is fairly straightforward:

- In [gridNumericOperators.ts](https://github.com/mui-org/material-ui-x/blob/next/packages/grid/_modules_/grid/models/colDef/gridNumericOperators.ts) the filters are correctly defined: `filterItem.value == null` is false when `filterItem.value = 0`
- In the transpiled code, this is transformed to a truthiness check using a ternary operator on `filterItem.value`, such as
```
{
  label:"=",
  value:"=",
  getApplyFilterFn: e => 
    e.value
      ? ({value:t})=>Number(t)===e.value
      : null,
  InputComponent:Vn,
  InputComponentProps:{type:"number"}
}
```
And, clearly, `0` is falsy in JS, thus `null` is returned.

### Your environment 🌎

Irrelevant

**Comment by flaviendelangle** [comment]
Duplicates #2524 

It will be fixed in the next release
