### ISSUE TITLE
data-grid doesn't work with RTL correctly

### ISSUE THREAD

**Issue by valin0k** [mui-org/material-ui-x#2563]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
table head not scrolling

https://user-images.githubusercontent.com/8665687/132359151-0d103941-385c-46f3-a033-7df6258d7538.mov

## Expected Behavior 🤔

table head NORMAL scrolling

## Steps to Reproduce 🕹

just try code example with RTL
https://codesandbox.io/s/material-demo-forked-f4lk7?file=/index.tsx
Steps:

1.
2.
3.
4.

## Your Environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Duplicates #230 
For the scroll, it should not be to hard to do, we just need to correctly map the event keys.

I at the "good to take" if someone in the community wants to take  a look
