### ISSUE TITLE
Disabled columns virtualization - custom cell render - Error "Rendered more hooks than during the previous render"

### ISSUE THREAD

**Issue by Dot-H** [mui-org/material-ui-x#2567]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The grid crashes with the error `Rendered more hooks than during the previous render` when:
- The column virtualization is disabled
- There are columns with a custom cell render using a hook
- We toggle the visibility of a column

### Expected behavior 🤔

The grid does not crash when the visibility of a column is toggled.

### Steps to reproduce 🕹

To reproduce this bug, use [this sandbox](https://codesandbox.io/s/material-demo-forked-1z2t2?file=/demo.tsx)

Steps:
1. Open the columns selection menu
1. Toggle the visibility of a column

You will see that if you remove the prop `columnBuffer={Number.MAX_SAFE_INTEGER}`, the bug disappears.

### Context 🔦

The column virtualization was disabled in my application and I have cells using the `useTranslation` hook from `react-i18next`. Toggling the visibility of the first columns was causing the grid to crash with the error message pointing to the `useTranslation` call in the render function of the last cell.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
  System:
    OS: Linux 5.11 Ubuntu 20.04.2 LTS (Focal Fossa)
  Binaries:
    Node: 14.15.1 - /tmp/xfs-e1cf2f09/node
    Yarn: 3.1.0-rc.2 - /tmp/xfs-e1cf2f09/yarn
    npm: 6.14.8 - ~/.npm-global/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Firefox: 91.0.2
</details>

### Order ID 💳 (optional)

#29039

**Comment by flaviendelangle** [comment]
`renderCell` is not called as a component but as a function like so `column.renderCell({ ...cellParams, api: apiRef.current });`
So it should not contain any hook.

https://codesandbox.io/s/material-demo-forked-0xgsq

You can do the following to make it work

```tsx
      renderCell: (params) => <CellWithHook {...params} />
```

Duplicates #1376
Duplicates #1402

**Comment by Dot-H** [comment]
Arf, sorry for the duplicate... I researched `Rendered more hooks than during the previous render` and had found on results :confused:

Anyway, thanks for your time and explanation, it is much appreciated !
