### ISSUE TITLE
How do I use DataGridPro inside Material UI Tabs, and within a Dialog box?

### ISSUE THREAD

**Issue by hermanc-fda** [mui-org/material-ui-x#2568]
### Order ID 💳

25226

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

When I use a DataGridPro within a tab, within a Dialog (popup), the grid disappears when it re-renders.

### The problem in depth 🔍

This is very likely due to the 

`Material-UI: useResizeContainer - The parent of the grid has an empty height.
You need to make sure the container has an intrinsic height.
The grid displays with a height of 0px.`

I've tried setting height just about everywhere up the parents all the way to the DialogContent but it still doesn't work. Where do I need to set the height, and how? I've followed examples in https://material-ui.com/components/data-grid/layout/ but still doesn't work.

### Context 🔦

It is structured somethign along the lines of:

<div className={classes.wrapper}>
<IconButton
  onClick={handleOpen}
>
  <AddIcon />
</IconButton>

<Dialog maxWidth="lg" open={open} fullWidth onClose={handleClose}>
  <DialogTitle>Feature Library</DialogTitle>
  <DialogContent>
    <Card elevation={0}>
        <CardContent style={{ height: 800, width: 800 }}>
            <Tabs>...
                <Tab label="Favorites" />
                <Tab label="Basic" />
            </Tabs>
            <TabPanel index={0} value={tabIndex}>
                <div style={{ display: "flex", height: 520, width: 800 }}>
                    <div style={{ height: 520, width: "100%" }}>
                        <DataGridPro.../>
                    </div>
                </div>
            </TabPanel>
            <TabPanel index={1} value={tabIndex}>
                ... (same as above)
            </TabPanel>
        </CardContent>
    </Card>
  </DialogContent>
</Dialog>
</div>

The first tab always works but the second tab (grid) disappears on re-render sometimes. That 'useResizeContainer...' message I also can't get it to go away. I've tried adding heights/widths to the parents etc. What is the right way to do this?

### Your environment 🌎

Chrome
  
System:
    OS: macOS 10.15.7
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.0 - ~/.yarn/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 93.0.4577.63
    Edge: Not Found
    Firefox: 74.0
    Safari: 13.1.3
  npmPackages:
    @material-ui/core: ^4.12.3 => 4.12.3
    @material-ui/icons: ^4.9.1 => 4.9.1
    @material-ui/lab: ^4.0.0-alpha.60 => 4.0.0-alpha.60
    @material-ui/pickers: ^3.2.10 => 3.2.10
    @material-ui/styles:  4.11.4
    @material-ui/system:  4.12.1
    @material-ui/types:  5.1.0
    @material-ui/utils:  4.11.2
    @types/react: ^16.9.54 => 16.14.2
    react: ^17.0.1 => 17.0.1
    react-dom: ^17.0.1 => 17.0.1
    typescript: ^4.3.4 => 4.3.5

**Comment by DanailH** [comment]
Hi @hermanc-fda, thanks for raising this. 
Please provide a minimal reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/material-ui-issue-next-o7xkt) _may_ be a good starting point. Thank you!

**Comment by Jucabel** [comment]
Hello, I'm having the same issue :/

I think that it do not need a reproduction, I am just wraping the dataGrid in the 5.0.0-beta.4 version like this:

```
<Grid item xs={12} style={{ width: "100%", height: 450 }}>
<DataGrid ...  />
</Grid>
```

Some one can help with this? I think that I have tryed everything.
