### ISSUE TITLE
[DataGrid] Extra space is added in server side pagination when rows per page are changed

### ISSUE THREAD

**Issue by pravinkottawar** [mui-org/material-ui-x#2573]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Extra space is added in server side pagination when rows per page are changed. I have added image

![image](https://user-images.githubusercontent.com/11690379/132661238-16306a65-b897-468b-b685-8e4d8a1d9eff.png)

### Expected behavior 🤔

There should not be an extra space. It gives wrong impression to user 

### Steps to reproduce 🕹

Steps:

1. Open following link [https://codesandbox.io/s/material-demo-forked-nmkz4](url)
2. Change page size and rowsPerPageOptions to 10 and save.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by pravinkottawar** [comment]
In server side pagination extra div is getting added which is not the case in client side pagination

![image](https://user-images.githubusercontent.com/11690379/132665693-7a3e2d98-3bef-4736-9166-5d11db11250d.png)

**Comment by flaviendelangle** [comment]
We compute the size of the container based on a number of information (the amount of rows to display for instance)
Their is probably some mistake in this size computation.

I'll have a look :+1:

**Comment by pravinkottawar** [comment]
> We compute the size of the container based on a number of information (the amount of rows to display for instance)
> Their is probably some mistake in this size computation.
> 
> I'll have a look 👍

Thank you for quick reply. It works fine for client side pagination. In server side pagination extra div is getting added

**Comment by flaviendelangle** [comment]
You are giving `pageSize=10` to the grid but you give the rows in group of 5, is it intended ? 
This is not the bug you are describing, even when putting `pageSize=5` their is some space.

Concerning your bug
I have the same behavior in client side pagination : https://codesandbox.io/s/material-demo-forked-jd86p

![image](https://user-images.githubusercontent.com/3309670/132679918-2be41200-86f1-406a-9bd5-6118e5897e05.png)

If you want the grid height to match the lines, you can use the prop `autoHeight`

**Comment by pravinkottawar** [comment]
If you see 2nd image attached from myside I have pageSize and rowsPerPageOptions = 100. There the space is even more.
This space is not good .

**Comment by flaviendelangle** [comment]
Something like that ?

https://codesandbox.io/s/material-demo-forked-66qtp

![image](https://user-images.githubusercontent.com/3309670/132690083-8766e7ce-9ed2-4d65-afc0-9565bc2fade3.png)


With a similar setup in client side pagination

https://codesandbox.io/s/material-demo-forked-ombq8?file=/demo.js

![image](https://user-images.githubusercontent.com/3309670/132690710-da970880-1643-4a04-897d-bd1dbc63ade3.png)

_____

You are giving 5 rows but telling the Grid that their is 100 rows per page and 100 rows in total.
So the Grid will be sized to display those 100 rows.

**Comment by pravinkottawar** [comment]
> Something like that ?
> 
> https://codesandbox.io/s/material-demo-forked-66qtp
> 
> ![image](https://user-images.githubusercontent.com/3309670/132690083-8766e7ce-9ed2-4d65-afc0-9565bc2fade3.png)
> 
> With a similar setup in client side pagination
> 
> https://codesandbox.io/s/material-demo-forked-ombq8?file=/demo.js
> 
> ![image](https://user-images.githubusercontent.com/3309670/132690710-da970880-1643-4a04-897d-bd1dbc63ade3.png)
> 
> You are giving 5 rows but telling the Grid that their is 100 rows per page and 100 rows in total.
> So the Grid will be sized to display those 100 rows.

YES. There is huge space after last row

**Comment by flaviendelangle** [comment]
Why are you only giving 5 rows per page and setting `pageSize={100}` ?

**Comment by pravinkottawar** [comment]
That is an example code . In my code I am giving rows per page and pageSize = 100. You can change row size and pageSize = 10 then also issue will be reproducible

**Comment by flaviendelangle** [comment]
Server pagination pageSize = 10: 

https://codesandbox.io/s/material-demo-forked-nfdwe?file=/demo.js

![image](https://user-images.githubusercontent.com/3309670/133058385-1d5fa373-6b3f-402b-a04a-7056549816dc.png)

Client pagination pageSize = 10: 

https://codesandbox.io/s/material-demo-forked-mh71e?file=/demo.js

![image](https://user-images.githubusercontent.com/3309670/133058488-7546b04f-a98a-4e33-85c1-5deebc026810.png)

Server pagination pageSize = 100:

https://codesandbox.io/s/material-demo-forked-sw48g?file=/demo.js

![Uploading image.png…]()


Client pagination pageSize = 100:

https://codesandbox.io/s/material-demo-forked-xuy0z?file=/demo.js

![image](https://user-images.githubusercontent.com/3309670/133058718-a8ae1137-c77c-4c63-aa3a-3f73a0977385.png)

**Comment by pravinkottawar** [comment]
Sir if you are fine we can have a zoom call where I can show exact details

**Comment by flaviendelangle** [comment]
Could you first give me a valid example on Codesandbox ?
