### ISSUE TITLE
[Data Grid] Simple Search Implementation

### ISSUE THREAD

**Issue by cwbuecheler** [mui-org/material-ui-x#2583]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Hello, I'd like to suggest a simple searchbox functionality that looks through all of the data in the grid and filters against the search term, preferably in realtime as it's being typed.

### Examples 🌈

Material-Table's implementation of this is really solid: https://material-table.com/#/docs/features/search

### Motivation 🔦

While the individual filters are immensely powerful and useful, sometimes it's nice to just be able to type something quickly in a single box (eg "Italy" when dealing with a big list of cities from several countries) and have the grid do the thinking for you. Similar functionality exists in some other Material-UI-based data grids (see "examples"), and I've found it very helpful in the past, but as far as I can tell it doesn't exist in Xgrid.

### Order ID 💳 (optional)

#27624

**Comment by m4theushw** [comment]
Thank you for the suggestion. We don't have a built-in generic search yet, but we have a demo showing how to add this functionality: https://material-ui.com/components/data-grid/filtering/#quick-filter.

Duplicate of #202. You can subscribe to it to get notified when this feature lands.

**Comment by cwbuecheler** [comment]
@m4theushw - Fantastic, thank you! And apologies for the duplicate. I really did do a bunch of issue searching before posting this!
