### ISSUE TITLE
[DataGrid] How to make checkbox and first column fixed (Horizontal scrollbar starts after certain column)

### ISSUE THREAD

**Issue by chloesun** [mui-org/material-ui-x#2584]
![datagrid](https://user-images.githubusercontent.com/13730281/132916779-6ad1729c-8057-47c2-a6f5-37e5e84c959e.PNG)
I want to make the checkbox and first column (the button) fixed, so the horizontal scroll bar starts after the first column. How to do that? Thank you!

**Comment by m4theushw** [comment]
The feature you're looking for is the column pinning. Unfortunately, it's not implemented yet. You can subscribe to #193 to be notified when it gets released.
