### ISSUE TITLE
[question]  [DataGrid] Is there a way to make the grid focusable by rows instead of cells?

### ISSUE THREAD

**Issue by JPTeasdale** [mui-org/material-ui-x#2585]
### Order ID 💳

28858

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I would like to use DataGridPro as a list of rows instead of a table of cells. 

### The problem in depth 🔍

I am using DataGridPro to render a list of rows. I love the ability to navigate with the arrow keys, but it doesn't make sense to highlight an existing cell for my use case. 

What I would like to do is have the up and down arrow highlight the up and down rows. But, AFAIK there is no way to modify the row css since the focused class is only added at the cell level. 

Do you have any ideas about how this could be done?

### Your environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>

```
System:
    OS: macOS 11.4
  Binaries:
    Node: 16.4.0 - ~/.nvm/versions/node/v16.4.0/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.18.1 - ~/.nvm/versions/node/v16.4.0/bin/npm
  Browsers:
    Chrome: 93.0.4577.63
    Edge: Not Found
    Firefox: Not Found
    Safari: 14.1.1
  npmPackages:
    @emotion/react: ^11.4.0 => 11.4.0 
    @emotion/styled: ^11.3.0 => 11.3.0 
    @material-ui/core: npm:@material-ui/core@next => 5.0.0-beta.5 
    @material-ui/icons: npm:@material-ui/icons@next => 5.0.0-beta.5 
    @material-ui/lab: ^5.0.0-alpha.44 => 5.0.0-alpha.44 
    @material-ui/private-theming:  5.0.0-beta.5 
    @material-ui/styled-engine:  5.0.0-beta.5 
    @material-ui/styles: ^5.0.0-beta.2 => 5.0.0-beta.5 
    @material-ui/system:  5.0.0-beta.5 
    @material-ui/types:  6.0.2 
    @material-ui/unstyled:  5.0.0-alpha.44 
    @material-ui/utils:  5.0.0-beta.5 
    @types/react: ^17.0.11 => 17.0.14 
    react: ^16.4.1 => 16.14.0 
    react-dom: ^16.4.1 => 16.14.0 
    typescript: ^4.3.4 => 4.3.5 
```
</details>

**Comment by m4theushw** [comment]
You can get this "focused row" by targeting the row that contains the focused cell. The `:focus-within` selector can be used. Here's an example of how to remove the outline from the cell and apply it to the row.

```js
const useStyles = makeStyles(
  (theme) => ({
    root: {
      "& .MuiDataGrid-cell:focus-within": {
        outline: "none"
      },
      "& .MuiDataGrid-row:focus-within": {
        outline: `solid ${fade(theme.palette.primary.main, 0.5)} 1px`,
        outlineWidth: 1,
        outlineOffset: -1
      }
    }
  }),
  { defaultTheme }
);
```

**Comment by JPTeasdale** [comment]
This works perfectly. Thank you very much.
