### ISSUE TITLE
How to add Image/Avatar in rows as in example https://material-ui.com/components/data-grid/filtering/

### ISSUE THREAD

**Issue by khanakhun** [mui-org/material-ui-x#2587]
Hello Devs,
I Need Help with a Query related to mui-x-grid table, so in this example  https://material-ui.com/components/data-grid/filtering/
they are using avatars, now I want to have a table with avatars in it but with avatars coming from an array, I see that there's generateData( function which is passed in a column of avatar ( something like this 
{
		field: 'avatar',
		headerName: 'Avatar',
		generateData: () => {},
		width: 150,
		filterable: false,
		editable: true,
	},
)
and renderCell()

any tip will he helpful for me , THanks for your Time

**Comment by ZeeshanTamboli** [comment]
Can you provide a CodeSandbox example with what you need? With the avatars array data that you are trying to render?
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/material-ui-issue-next-o7xkt) _may_ be a good starting point. Thank you!

**Comment by khanakhun** [comment]
> Can you provide a CodeSandbox example with the avatars array data that you are trying to render?
> A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/material-ui-issue-next-o7xkt) _may_ be a good starting point. Thank you!

The Is Comming from an API and I'm rendering them into rows and Columns, so it will be hard to put examples in Code Sandbox
When i consoled the  data from "const { data } = useDemoData({ dataSet: 'Employee', rowLength: 100 }) " , this is the Current Data on MUI x-data-grid where they have rendered avatars  and when i console this data it has to objects { columns , rows }
![image](https://user-images.githubusercontent.com/64289221/132981863-9f208567-0fbc-4758-90de-35849cd21118.png)

in the above screenshot, you can see the Columns have a different functions in them and I believe generateData() is responsible for the data  like: 
![image](https://user-images.githubusercontent.com/64289221/132981915-cbf18ca0-ea80-4169-a076-a87964028638.png)

**Comment by khanakhun** [comment]
Fixed it and to Use  renderCell function and Pass a function with parm data and return an Element
