### ISSUE TITLE
DataGrid filter input doesn't work in a drawer

### ISSUE THREAD

**Issue by atomicpages** [mui-org/material-ui-x#2604]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Input is blocked using standard filters in the data grid when the grid is mounted inside a `Drawer` from `@material-ui-core`.

### Expected behavior 🤔

You should be able to type stuff in

### Steps to reproduce 🕹

See for a minimum verifiable repro https://codesandbox.io/s/elated-bassi-isu7u?file=/src/App.tsx

### Your environment 🌎

N/A, see codesandbox for repo

**Comment by flaviendelangle** [comment]
Hi @atomicpages, thanks for raising this. 
Please provide a minimal reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/material-ui-issue-next-o7xkt) _may_ be a good starting point. Thank you!

**Comment by DanailH** [comment]
@flaviendelangle there is a reproduction added. The issue is visible there 😉

**Comment by flaviendelangle** [comment]
:facepalm: my bad sorry

**Comment by flaviendelangle** [comment]
https://codesandbox.io/s/quiet-wildflower-m9xy6?file=/package.json

@atomicpages @DanailH it seems to work with the latest version of the core.

**Comment by flaviendelangle** [comment]
Duplicates #2230

**Comment by atomicpages** [comment]
What about getting v4 support?

**Comment by flaviendelangle** [comment]
https://github.com/mui-org/material-ui/issues/15694

It's a bug in the core library in v4
I don't think they intend to do updates on this version anymore.
