### ISSUE TITLE
Unable to suppress default behaviour of handleColumnHeaderClick while in sorting mode.

### ISSUE THREAD

**Issue by pranavdxl** [mui-org/material-ui-x#2612]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by DanailH** [comment]
Hi @pranavdxl, thanks for raising this. 
Please provide a minimal reproduction test case with the latest version along with a short explanation of the problem. This would help a lot 👷 .
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/material-ui-issue-next-o7xkt) _may_ be a good starting point. Thank you!

**Comment by pranavdxl** [comment]
> Hi @pranavdxl, thanks for raising this.
> Please provide a minimal reproduction test case with the latest version along with a short explanation of the problem. This would help a lot 👷 .
> A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/material-ui-issue-next-o7xkt) _may_ be a good starting point. Thank you!

Let's say we want to only perform sorting by selecting menuitem from column menu and we want to suppress sorting on header click.

**Comment by pranavdxl** [comment]
https://stackblitz.com/edit/react-1iszlk?file=demo.js

**Comment by pranavdxl** [comment]
Any update on this?

**Comment by m4theushw** [comment]
You can [disable the default behavior](https://mui.com/components/data-grid/events/#disabling-the-default-behavior) of the `columnHeaderClick` event setting `defaultMuiPrevented` to true. There's also a prop mapped to this event.

```tsx
<DataGridPro
  onColumnHeaderClick={(params, event) => {
    event.defaultMuiPrevented = true;
  }}
/>
```

**Comment by pranavdxl** [comment]
Thanks this worked.
