### ISSUE TITLE
Controlled Multi-Selection doesn't work unless `checkboxSelection` is enabled

### ISSUE THREAD

**Issue by mwarger** [mui-org/material-ui-x#2616]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using the controlled selection mode for multi-select, it is necessary to have `checkboxSelection` enabled.

### Expected behavior 🤔

`checkboxSelection` should not be required - you should be able to select multiple items in a controlled way without checkboxes in the grid.

### Steps to reproduce 🕹

https://codesandbox.io/s/material-demo-forked-8dodw?file=/demo.tsx

Reproduction there - comment or uncomment the `checkboxSelection` flag to see the difference in behavior.  With it applied, controlled multi-selection works.  If it's commented out, controlled multi-selection doesn't work.

### Context 🔦

I'd like to be able to hold down Cmd/Ctrl and multi-select items in a controlled way without showing checkboxes on my grid.

**Comment by ZeeshanTamboli** [comment]
Multi-selection (controlled or uncontrolled) without `checkboxSelection` (no checkboxes) is only available in Pro version. 
See https://material-ui.com/components/data-grid/selection/#multiple-row-selection

CodeSandbox with `DataGridPro`: https://codesandbox.io/s/material-demo-forked-4gqfy

See https://material-ui.com/components/data-grid/getting-started/#licenses to upgrade to `DataGridPro`.
