### ISSUE TITLE
Column menu hide on esc key throwing error 

### ISSUE THREAD

**Issue by pranavdxl** [mui-org/material-ui-x#2623]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

click on column menu icon.  then press esc key. Its throwing error "Cannot read property 'stopPropagation' of undefined"

demo Link: https://codesandbox.io/s/we0fk?file=/demo.tsx

### Expected behavior 🤔

It should close column menu.

### Steps to reproduce 🕹

Steps:

1. Go to https://codesandbox.io/s/we0fk?file=/demo.tsx
2. click on dots to open column menu.
3. press esc key to close that it will throw error.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by DanailH** [comment]
duplicate #2463 

Hi, @pranavdxl thanks for reporting this.
We already noticed the problem. This is the PR fixing it https://github.com/mui-org/material-ui-x/pull/2463. It is fixed in the latest release (`v5.0.0-beta.0`).

@mui-org/x this is a good example of shipping bugfixes for `v4.0.*`
