### ISSUE TITLE
Can't install @mui/x-data-grid-pro v5.0.0-beta.0

### ISSUE THREAD

**Issue by destegabry** [mui-org/material-ui-x#2624]
### Order ID 💳

29385

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I'm trying to update to `v5.0.0-beta.0` from a working copy of `4.0.0`, but getting an error during `npm install`

### The problem in depth 🔍

I've tried deleting `node_modules` folder and `package-lock.json` file, always getting:

```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /[...]/node_modules/@mui/x-license-pro/bin/license-gen-script.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/[...]/node_modules/@mui/x-license-pro/bin/license-gen-script.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2021-09-17T10_38_40_865Z-debug.log
```

I don't have `@mui/x-license-pro` in my package json as it's not required in [the instructions](https://mui.com/components/data-grid/getting-started/#license-key-installation).

### Context 🔦

I'm trying to upgrade to latest material-ui-x without success. Version 4 was working flawlessy.

### Your environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>

```

  System:
    OS: macOS 11.5.2
  Binaries:
    Node: 16.9.1 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 7.21.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: Not Found
    Edge: 92.0.902.78
    Firefox: 86.0.1
    Safari: 14.1.2
```
</details>

**Comment by flaviendelangle** [comment]
You should indeed not have to install explicitly `@mui/x-license-pro` in your `package.json`
Can you try resetting your `node_modules` ?

I just did a new application with the following deps and it's working

```json
  "dependencies": {
    "@emotion/react": "^11.4.1",
    "@emotion/styled": "^11.3.0",
    "@mui/material": "^5.0.0",
    "@mui/styles": "^5.0.0",
    "@mui/x-data-grid-pro": "^5.0.0-beta.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3"
  },
  "devDependencies": {
    "@habx/eslint-config-client": "^6.3.0",
    "@types/node": "^12.0.0",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "typescript": "^4.3.5"
  },
```

**Comment by destegabry** [comment]
This is the relevant part of `my package.json`:

```
  "dependencies": {
    "@emotion/react": "^11.4.1",
    "@emotion/styled": "^11.3.0",
    "@mui/lab": "^5.0.0-alpha.47",
    "@mui/material": "^5.0.0",
    "@mui/x-data-grid-pro": "^5.0.0-beta.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "typescript": "^4.4.3",
  },
  "devDependencies": {
    "@types/node": "^16.9.2",
    "@types/react": "^17.0.21",
    "@types/react-dom": "^17.0.9",
  },
```

Running `rm -Rf node_modules && rm package-lock.json && npm install` less to the same error:

```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /[...]/node_modules/@mui/x-license-pro/bin/license-gen-script.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/[...]/node_modules/@mui/x-license-pro/bin/license-gen-script.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!    ~/.npm/_logs/2021-09-17T11_02_30_034Z-debug.log
```

**Comment by flaviendelangle** [comment]
```
  "peerDependencies": {
    "@mui/material": "^5.0.0",
    "@mui/styles": "^5.0.0",
    "react": "^17.0.2"
  },
```

It should not be related but you are missing `@mui/styles`

____

I don't have the `bin` folder either on my test... I'll check why :+1:

**Comment by flaviendelangle** [comment]
OK I have the same error with `npm` but it's working with `yarn`

**Comment by destegabry** [comment]
It makes more sense than being related to the missing styles package!

**Comment by flaviendelangle** [comment]
For the style package it clearly does not impact your bug, it was just a remark because it will probably cause bugs afterward

**Comment by flaviendelangle** [comment]
https://mui.com/components/data-grid/getting-started/#installation

> npm install @mui/material @mui/styles

Are you on this page ?

**Comment by destegabry** [comment]
My bad, was referring to the main package

**Comment by flaviendelangle** [comment]
For the `bin` missing folder, I'll dive into the issue and come back :+1:

**Comment by flaviendelangle** [comment]
@destegabry 

https://github.com/mui-org/material-ui-x/releases/tag/v5.0.0-beta.1
The new release should solve your issue

**Comment by destegabry** [comment]
It works! Thank you for your support!
