### ISSUE TITLE
Material-UI -> MUI renaming in the codebase

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#2631]
There are multiple instances where we can rename the new project's name

https://github.com/mui-org/material-ui-x/blob/e9a9ecc3bf932d38c8a1cf5edbd1abc8eb3de11d/packages/grid/data-grid/src/DataGrid.tsx#L88

https://github.com/mui-org/material-ui-x/blob/e9a9ecc3bf932d38c8a1cf5edbd1abc8eb3de11d/packages/grid/data-grid/package.json#L13

**Comment by flaviendelangle** [comment]
For the error, I'll do a PR adding / renaming the `Material-UI` prefix on everyone of them.
Some do not have `Material-UI` at all
