### ISSUE TITLE
[DataGridPro] onSortModelChange firing multiple times and also while table initially renders

### ISSUE THREAD

**Issue by thuatole** [mui-org/material-ui-x#2635]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

- Current behaviour introduced a bug that fires onSortModelChange event multiple times

### Steps to reproduce 🕹

Source [https://codesandbox.io/s/material-demo-forked-t5tq0?file=/demo.js](https://codesandbox.io/s/material-demo-forked-t5tq0?file=/demo.js)
Steps:

1. Reload the template, you can see onSortModelChange event firing thrice.

### Context 🔦

Due to multiple onSortModelChange event firing app is re-rendering eventually causing performance issues.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.12 - /usr/local/bin/npm
  Browsers:
    Chrome: 93.0.4577.82
    Edge: Not Found
    Firefox: Not Found
    Safari: 14.0.3
  npmPackages:
    @emotion/react: ^11.4.1 => 11.4.1 
    @emotion/styled: ^11.3.0 => 11.3.0 
    @mui/core:  5.0.0-alpha.46 
    @mui/lab: ^5.0.0-alpha.46 => 5.0.0-alpha.46 
    @mui/material: ^5.0.0-rc.1 => 5.0.0-rc.1 
    @mui/private-theming:  5.0.0-rc.1 
    @mui/styled-engine:  5.0.0-rc.1 
    @mui/system:  5.0.0-rc.1 
    @mui/types:  7.0.0-rc.1 
    @mui/utils:  5.0.0-rc.1 
    @mui/x-data-grid-pro: ^4.0.0 => 4.0.0 
    @mui/x-license-pro:  4.0.0 
    @types/react: 16.14.5 => 16.14.5 
    react: 16.14.0 => 16.14.0 
    react-dom: 16.14.0 => 16.14.0 
    styled-components: 5.2.1 => 5.2.1 
    typescript: 4.2.3 => 4.2.3 
```
</details>

**Comment by trickreich** [comment]
why this is priority low?
for us the library isn't usable at all, because we have dynamic columns, then this is a infinite loop!

**Comment by elyesbenabdelkader** [comment]
I agree with trickreich, this is a blocker.

**Comment by flaviendelangle** [comment]
@trickreich can you provide an example that causes the inifinite loop ?

**Comment by trickreich** [comment]
I've built something similiar to our project: https://codesandbox.io/s/mui-x-data-grid-onsortmodelchange-infinite-loop-t72pm
Click on one column and you will see the infinite loop.

![image](https://user-images.githubusercontent.com/16644200/135079156-2432478e-c15a-4ae0-a6c4-d4b6c8dcae88.png)

**Comment by flaviendelangle** [comment]
#2724 fixes the problem describes in the first message. I does not call `onSortModelChange` on mount or on prop change but only when you change the value through the UI or the imperative API.

I think it also fixes your bug but I'll wait for the publication of the package on Codesandbox to check :+1:

**Comment by flaviendelangle** [comment]
https://codesandbox.io/s/mui-x-data-grid-onsortmodelchange-infinite-loop-forked-20qrb

@trickreich #2724 does seems to fix your bug

**Comment by trickreich** [comment]
Pretty nice, thanks for the quick response and help.
Yeah, I've used `useMemo` before, but that's not working out of the box. (reference equality).

**Comment by karanaditya993** [comment]
@flaviendelangle any update on when #2724 will be merged? Thanks

**Comment by flaviendelangle** [comment]
I will be in the  next release
Not sure they will be one this week, so probably next Thursday

**Comment by elyesbenabdelkader** [comment]
@flaviendelangle can we please have this in v4.0.2 ASAP?

**Comment by maurosbu** [comment]
@flaviendelangle in order to temporary fix the problem I'm considering using the following approach:

    import _ from 'lodash';
    
    const [sortModel, setSortModel] = useState([
         // default filters
    ]);

    <DataGrid
        sortModel={sortModel}
        onSortModelChange={(model) => {
            if (!_.isEqual(model, sortModel)) {
                setSortModel(model);
            }
        }}
    />

@m4theushw I know that this is far to be optimal, but it seems to work. What do you think?

Many thanks.

Mauro N.

**Comment by karanaditya993** [comment]
@flaviendelangle do you have an estimate as to when v5 will be released?
