### ISSUE TITLE
Missing Dependency: Can't resolve '@material-ui/core/Badge

### ISSUE THREAD

**Issue by TimothyDalbey** [mui-org/material-ui-x#2654]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Failed to compile.

./node_modules/@mui/x-data-grid/dist/index-esm.js
Module not found: Can't resolve '@material-ui/core/Badge' in '{path to project}/node_modules/@mui/x-data-grid/dist'

### Expected behavior 🤔

Successful compilation

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by rayfarer** [comment]
In README.MD for this component it says:

`  "@material-ui/core": "^4.12.0 || ^5.0.0-beta.0",`

Once I did this, it worked. If you're using the data-grid-generator, you'll need to install the icons and lab packages from the old @material-ui too.

**Comment by TimothyDalbey** [comment]
The issue is that `@material-ui/core` screws up styling of the new components.

**Comment by m4theushw** [comment]
> The issue is that @material-ui/core screws up styling of the new components.

Are you also using @mui/material in your project?

**Comment by kanonirbrest** [comment]
the same issue, @material-ui/core screws up styling of the new components.

**Comment by TimothyDalbey** [comment]
> > The issue is that @material-ui/core screws up styling of the new components.
> 
> Are you also using @mui/material in your project?

Yes -  underwent the migration process from @material-ui to @mui this weekend and was forced to revert due to the conflicts introduced by having both dependencies as peers.

**Comment by m4theushw** [comment]
I suppose you're using `@mui/x-data-grid` v4 with `@mui/material`. The latest version (5.0.0-beta.1) of `@mui/x-data-grid` supports `@mui/material` without hacks.

**Comment by m4theushw** [comment]
We've updated our installation instructions. Please see https://mui.com/components/data-grid/getting-started/#installation

**Comment by TheMegafuji** [comment]
if someone is still getting this in the latest versions, try running `npm audit fix --force`, it fixed for me
