### ISSUE TITLE
datagrid mit version

### ISSUE THREAD

**Issue by mehranml** [mui-org/material-ui-x#2658]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

hey "@mui/x-data-grid"  have wrong imports and its pakeges doesnt changed from material-ui to mui tnx 

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://material-ui.com/r/issue-template) _may_ be a good starting point. Thank you!

**Comment by gauravdirectdigitalus** [comment]
I am having the same issue. Here is the sandbox https://codesandbox.io/s/beautiful-knuth-vdj2b
