### ISSUE TITLE
DataGridPro requires @material-ui

### ISSUE THREAD

**Issue by mattroccolucciola** [mui-org/material-ui-x#2660]
Using DataGrid and DataGridPro requires older @material-ui libraries to be installed rather than using the v5 ones.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

I have to add @material-ui/lab @material-ui/icons and @material-ui/core rather than the module just using the already downloaded @mui/... versions.

## Expected Behavior 🤔

None.  I should not have to install the v4 (or older) packages.

## Steps to Reproduce 🕹

1. Install @mui/x-data-grid `yarn add @mui/x-data-grid`
2. Load it into my React component `import { useDemoData } from '@mui/x-data-grid-generator';`
3. Error gets thrown
```
Failed to compile

src/components/creatorsListView/EmptyDataGrid.jsx
  Line 46:6:   'GridOverlay' is not defined  react/jsx-no-undef
  Line 100:8:  'DataGrid' is not defined     react/jsx-no-undef

Search for the keywords to learn more about each error.
```

## Context 🔦

Want to just have a more seamless user experience using Material-UI.  It's my favorite styling library and has helped save countless hours building and designing sites.

## Your Environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
  
```
Using Firefox 91.0.2

  System:
    OS: macOS 11.5.2
  Binaries:
    Node: 16.6.1 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 7.20.5 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Edge: Not Found
    Firefox: 91.0.2
    Safari: 14.1.2
  npmPackages:
    @emotion/react: ^11.4.1 => 11.4.1 
    @emotion/styled: ^11.3.0 => 11.3.0 
    @mui/core:  5.0.0-alpha.47 
    @mui/icons-material: ^5.0.0 => 5.0.0 
    @mui/material: ^5.0.0 => 5.0.0 
    @mui/private-theming:  5.0.0 
    @mui/styled-engine:  5.0.0 
    @mui/styled-engine-sc: ^5.0.0 => 5.0.0 
    @mui/styles: ^5.0.0 => 5.0.0 
    @mui/system:  5.0.0 
    @mui/types:  7.0.0 
    @mui/utils:  5.0.0 
    @mui/x-data-grid: ^4.0.0 => 4.0.0 
    @mui/x-data-grid-generator: ^4.0.0 => 4.0.0 
    @types/react:  17.0.21 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    styled-components: ^5.3.1 => 5.3.1 
```
</details>

**Comment by m4theushw** [comment]
You have to update `@mui/x-data-grid-pro` and `@mui/x-data-grid-generator` to v5 to support MUI v5 without the old libraries. The last released version is `5.0.0-beta.1`.

**Comment by SaeedBoroo** [comment]
I use `@mui/x-data-grid` v4.0.0. why when run project it fails. it requires `@material-ui/core/styles`.
**`Module not found: Can't resolve '@material-ui/core/styles' `**

what can I do?

**Comment by m4theushw** [comment]
We've updated our installation instructions. Please see https://mui.com/components/data-grid/getting-started/#installation
