### ISSUE TITLE
[DataGrid] Module not found: Can't resolve '@material-ui/core/styles'

### ISSUE THREAD

**Issue by EliseyKoney** [mui-org/material-ui-x#2661]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Failed to compile
./node_modules/@mui/x-data-grid/dist/index-esm.js:1:107
Module not found: Can't resolve '@material-ui/core/styles'

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
Which version of `@mui/x-data-grid` are you using? If you're using MUI v5 you also need to install MUI X v5. The latest version is 5.0.0-beta.1.

**Comment by EliseyKoney** [comment]
The latest version is 5.0.0-beta.1 works
