### ISSUE TITLE
[DataGrid] Single Select operators should be exported

### ISSUE THREAD

**Issue by jeremyalan** [mui-org/material-ui-x#2666]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

First off - I'm loving the Material-UI Data Grid, thanks for all your hard work, we will likely become a Pro customer soon, and I look forward to seeing functionality continue to improve over time.

---

Here's an issue I ran into:

The Data Grid should expose operators for "single select" filters, making it easier to wire up drop-down filters allowing the user to select from a list of options, rather than typing in a free-text field.

In particular, this file should include exporting values from `gridSingleSelectOperators`:
https://github.com/mui-org/material-ui-x/blob/next/packages/grid/_modules_/grid/models/colDef/index.ts

If this is already supported in another way, please improve (or point me to) the documentation on how to implement this properly, I could only get it to work by copying source code from the repository into my application.

### Examples 🌈

I was able to wire up the column definition, using the following sample.
```
{
  field: "status",
  // ... other fields omitted for brevity

  valueOptions: [
    "Pending",
    "Approved",
    "Active",
  ],
  filterOperators: [{
    value: 'is',
    getApplyFilterFn: (filterItem: GridFilterItem) => {
      if (filterItem.value == null || filterItem.value === '') {
        return null;
      }

      return ({ value }): boolean => {
        if (typeof value === 'object') {
          return filterItem.value === (value as { value: any; label: string }).value;
        }
        return filterItem.value === value;
      };
    },
    InputComponent: GridFilterInputValue,
    InputComponentProps: { type: 'singleSelect' },
  }]
}
```

The `filterOperators' was copied from the original source.  It would have been better to leverage the exported operators, similar to the other operators that are exposed by the API, e.g.:

```
{
  field: "status",
  // ... other fields omitted for brevity

  valueOptions: [
    "Pending",
    "Approved",
    "Active",
  ],
  filterOperators: getSingleSelectOperators()
    .filter(a => a.value === "is")
}
```

### Motivation 🔦

I'm looking for a way to create a "Drop Down" filter, for certain columns in my data set.  In particular, we have a "Status" field that has a discrete list of values, so a Text field doesn't make sense, the user just needs to pick a value from the list.

I didn't see this example in the docs, so I went through the source code to see how I would plug this in, I saw a lot of help around different filterOperators, and input components, and start wiring those up, before I realized that the Data Grid already has support for "singleSelect" types, it just didn't expose the necessary components to include the filters.

**Comment by m4theushw** [comment]
Yes, we can add the missing exports. Do you want to open a PR with the following diff?

```diff
diff --git a/packages/grid/_modules_/grid/models/colDef/index.ts b/packages/grid/_modules_/grid/models/colDef/index.ts
index e5b9b220..756cd3be 100644
--- a/packages/grid/_modules_/grid/models/colDef/index.ts
+++ b/packages/grid/_modules_/grid/models/colDef/index.ts
@@ -11,3 +11,5 @@ export * from './gridColTypeDef';
 export * from './gridDefaultColumnTypes';
 export * from './gridStringOperators';
 export * from './gridActionsColDef';
+export * from './gridSingleSelectColDef';
+export * from './gridSingleSelectOperators';
```

**Comment by jeremyalan** [comment]
Thanks, @m4theushw!

PR is here: https://github.com/mui-org/material-ui-x/pull/2677
