### ISSUE TITLE
@mui/x-data-grid Not working with properly @mui/material v.5

### ISSUE THREAD

**Issue by leehoog** [mui-org/material-ui-x#2670]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I recently upgraded material-ui to the latest version v.5.
After that I started receiving some errors from **@mui/x-data-grid** for ex. 
`Module not found: Can't resolve '@material-ui/core/Badge' in '/{path}/{project}/node_modules/@mui/x-data-grid/dist'`

So I went ahead and installed **@material-ui/core** since it seems to be a dependency for the data-grid. But this seems override styling in components used in **@mui/x-data-grid** for ex **Toolbar**, since Im now using 2 instances of material-ui.

Example of styles overwritten: 
```
const LinkToolbar = styled(Toolbar)(() => `
  display: flex;
  align-items: center;
  justify-content: space-between;
`)
```

In the docs you mention that the only dependencies are **@mui/material @mui/styles**
But in the npm package I can see that ** @material-ui/core** is a dependency.
https://mui.com/components/data-grid/getting-started/#installation
https://www.npmjs.com/package/@mui/x-data-grid

### Expected behavior 🤔

**@mui/x-data-grid** Should work only with **@mui/material @mui/styles** like described in the docs
https://mui.com/components/data-grid/getting-started/#installation

### Steps to reproduce 🕹

Steps:

1. Add some styling to the **Toolbar** component with **styled** from **@mui/material**
2. Use @mui/x-data-grid somewhere in the project
3. Your custom styles in the Toolbar component should now been overwritten

### Context 🔦

Trying to use the **@mui/x-data-grid** with **@mui/material** without **@material-ui/core**

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 11.5.2
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v14.17.6/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
  Browsers:
    Chrome: 93.0.4577.82
    Edge: Not Found
    Firefox: Not Found
    Safari: 14.1.2
  npmPackages:
    @emotion/react: ^11.4.1 => 11.4.1
    @emotion/styled: ^11.3.0 => 11.3.0
    @mui/core:  5.0.0-alpha.47
    @mui/icons-material: ^5.0.0 => 5.0.0
    @mui/material: ^5.0.0 => 5.0.0
    @mui/private-theming:  5.0.0
    @mui/styled-engine:  5.0.0
    @mui/styled-engine-sc: ^5.0.0 => 5.0.0
    @mui/system:  5.0.0
    @mui/types:  7.0.0
    @mui/utils:  5.0.0
    @mui/x-data-grid: ^4.0.0 => 4.0.0
    @types/react: ^17.0.0 => 17.0.20
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    styled-components: ^5.3.1 => 5.3.1
    typescript: ^4.1.2 => 4.4.2```
</details>


### Order ID 💳 (optional)

_No response_

**Comment by ZeeshanTamboli** [comment]
You're using `@mui/x-data-grid` v4 with `@mui/material`. The latest version (5.0.0-beta.1) of `@mui/x-data-grid` supports `@mui/material` only. To only support MUI v5 without `@material-ui/core` v4 in the datagrid, install with the `next` tag by doing
 ```
npm install @mui/x-data-grid@next
```
By default, the `latest` tag is used by npm which is datagrid v4.

We will update the docs in #2663
