### ISSUE TITLE
Data-Grid breaks styling of components

### ISSUE THREAD

**Issue by knopkem** [mui-org/material-ui-x#2674]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Using the latest version of Data-Grid with material-ui 5 breaks styling of other material-ui elements e.g. Buttons rendered on the same page.

### Expected behavior 🤔

Data-Grid should not affect the styling of other elements.

### Steps to reproduce 🕹

https://codesandbox.io/s/busy-shadow-4l50v

### Context 🔦

Would like to upgrade to mui5 and x-grid

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 16.6.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.19.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 94.0.4606.54
    Edge: Spartan (44.18362.1593.0)
  npmPackages:
    @emotion/react: ^11.4.1 => 11.4.1
    @emotion/styled: ^11.3.0 => 11.3.0
    @mui/core:  5.0.0-alpha.47
    @mui/icons-material: ^5.0.0 => 5.0.0
    @mui/material: ^5.0.0 => 5.0.0
    @mui/private-theming:  5.0.1
    @mui/styled-engine:  5.0.0
    @mui/styles: ^5.0.1 => 5.0.1
    @mui/system:  5.0.0
    @mui/types:  7.0.0
    @mui/utils:  5.0.1
    @mui/x-data-grid: ^4.0.0 => 4.0.0
    @types/react:  17.0.24
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
```
</details>

**Comment by TomDoesbRUG** [comment]
I experienced the same thing,  but this was solved in 5.0.0-beta-1

**Comment by EliuTimana** [comment]
I had the same issue, upgrading to `5.0.0-beta.1` solved the problem, ` @material-ui/core` isn't needed anymore, you will need `@mui/styles` to get it working:
```json
    "@mui/styles": "^5.0.1",
    "@mui/x-data-grid": "^5.0.0-beta.1",
```

**Comment by ZeeshanTamboli** [comment]
Install latest version `5.0.0-beta.1` with the `next` tag
```
npm install @mui/x-data-grid@next
```
It will be mentioned in the docs in the next release.
