### ISSUE TITLE
Data Grid: Checkbox ignores custom theme

### ISSUE THREAD

**Issue by mus-samar** [mui-org/material-ui-x#2678]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Checkbox uses default theme regardless, including the defaultProps overrides.
`
{
...
  palette: {
       primary: {
       ... custom colors
      },
  },
  components: {
   MuiCheckbox: {
        defaultProps: {
          disableRipple: true,
          disableFocusRipple: true,
          disableTouchRipple: true
        },
       },
  }
...
}
...
`

Example of the Checkbox on the table with the same theme:
<img width="79" alt="datagrid-checkbox" src="https://user-images.githubusercontent.com/65939218/134610093-4117fc4c-0044-4e2b-8323-688fa988d0fe.png">
``

Below example of how the Checkbox should look like on the Data Grid based on theme overrides.
<img width="70" alt="custom-theme-checkbox" src="https://user-images.githubusercontent.com/65939218/134609727-8c6c3401-e683-44a4-a890-d70be76c56ed.png">

### Expected behavior 🤔

The checkbox on the data table should behave and appear the same as the Checkbox throughout the application based on the users applied Theme.

### Steps to reproduce 🕹

Steps:

1. Create custom theme with a custom pallet and override the default props on the checkbox to disable ripple.
2. Create data grid

### Context 🔦

I want to ensure consistency in look and feel of all components throughout the app. However, the data grid seems to ignore custom themes.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://material-ui.com/r/issue-template) _may_ be a good starting point. Thank you!
