### ISSUE TITLE
[DataGridPro] Column reorder does not work when `DataGridPro` is a child of react-dnd-html5-backend

### ISSUE THREAD

**Issue by sebastianfrey** [mui-org/material-ui-x#2680]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When the component tree, which contains the DataGrid, is wrapped with `react-dnd-html5-backend`, the column reorder functionality breaks.

### Expected behavior 🤔

Reordering columns should work, even when the DataGrid is wrapped with a third party dnd library like `react-dnd`.

### Steps to reproduce 🕹

Steps:

1. Go to https://codesandbox.io/s/kind-pine-tostw
2. Try to reorder the columns by Drag n Drop.

### Context 🔦

The problem is, that the HTML5Backend of `react-dnd` hijacks all out of context `draggable` elements: https://github.com/react-dnd/react-dnd/issues/3304. And since the grid leverages this API, its column reorder feature breaks when used with `react-dnd`.

One solution that seems to work is described here https://github.com/react-dnd/react-dnd/issues/2868:

It suggests to stop event propagation in `onDragStart`, `onDragEnd` and `onDrag` event listeners.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

22075

**Comment by agoodisman** [comment]
Apologies if this has been raised elsewhere. 

I am still seeing this exact issue:  That is, DataGridPro inside HTML5Backend throws "Uncaught Invariant Violation: Cannot call hover while not dragging." when dropping a dragged column header.  

Environment: 
react-dnd-html5-backend@16.0.1
react-dnd@16.0.1
@mui/x-data-grid-pro@6.16.2
Desktop Windows Chrome 117.0.5938.150

What is the version number of DataGridPro that includes this fix?

I tried listening for the events columnHeaderDragStart, etc. via apiRef.current.subscribeEvent and calling stopPropagation() on them, but although I received the events, this did not change the behavior.

The column reordering does work; it just displays the error to the browser dev console.

**Comment by romgrk** [comment]
@agoodisman I suggest that you open a new bug report. Provide a reproducible codesandbox example, you can find a template in the bug report issue interface.
