### ISSUE TITLE
Default sort does not work properly

### ISSUE THREAD

**Issue by jakeleventhal** [mui-org/material-ui-x#2681]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

https://codesandbox.io/s/muddy-violet-ugffc?file=/src/App.tsx
The error goes away if you comment out the line that adds the `sortModal` prop

### Expected behavior 🤔

Default sort doesn't crash

### Steps to reproduce 🕹

See code sandbox

### Context 🔦

n/a

### Your environment 🌎

Code sandbox

### Order ID 💳 (optional)

2021-8393

**Comment by flaviendelangle** [comment]
```tsx
/**
 * The model used for sorting the grid.
 */
export type GridSortModel = GridSortItem[];
```

The `sortModel` property must be an array even if you just want a single sort item

https://codesandbox.io/s/awesome-napier-zywof?file=/src/App.tsx
