### ISSUE TITLE
[DataGrid] Filter panel shows "undefined" when is open for the first time

### ISSUE THREAD

**Issue by m4theushw** [mui-org/material-ui-x#2687]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

<img width="500" src="https://user-images.githubusercontent.com/42154031/134754584-f8b23a37-3dee-4356-98c5-5013e1dc42b3.png" alt="image" style="max-width: 100%;">

### Expected behavior 🤔

The filter value field should start as empty.

### Steps to reproduce 🕹

Steps:

1. Open https://mui.com/components/data-grid/demo/
2. Add a filter

### Context 🔦

Regression from #2581.

The OR operator should be inside the cast.

https://github.com/mui-org/material-ui-x/blob/609248ea030cf6ca657bfae92f23bea3ba868c2b/packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterInputValue.tsx#L81

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by chunming-c** [comment]
Thanks for fixing. This also break filter for `number` type with message `"The specified value "undefined" cannot be parsed, or is out of range."`
