### ISSUE TITLE
Material UI v5 DataGrid breaking Drawer CSS.

### ISSUE THREAD

**Issue by gkbaby** [mui-org/material-ui-x#2688]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Mini Drawer sample code : https://mui.com/components/drawers/#MiniDrawer.js
DataGrid: https://mui.com/components/data-grid/#DataGridDemo.js
I've combined both these code and while adding the datagrid code breaks the normal working of minidrawer.
Please see the code https://codesandbox.io/s/upbeat-williamson-nqu48?file=/src/Drawer.js
comment line no 153 to see how it looks normally.
This used to work normally before upgrading to muiv5

### Expected behavior 🤔

The mini drawer's appearance should not be affected by datagrid.

### Steps to reproduce 🕹

Steps: https://codesandbox.io/s/upbeat-williamson-nqu48?file=/src/Drawer.js

1. Please uncomment line 153 and reload the output tab to see how drawer looks normally.
2.
3.
4.

### Context 🔦

muiv5 upgrade caused this trouble

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by gkbaby** [comment]
updating o a mui datagrid pre-release branch which used v5 mui fixed this issue. so closing this issue.

**Comment by 3210jr** [comment]
This worked for me with the latest release.

Here is where to find it for reference: https://github.com/mui-org/material-ui-x/releases
