### ISSUE TITLE
 Reference error in MaterialUI Pro(4.0.0) version of the library

### ISSUE THREAD

**Issue by rishav-ameyo** [mui-org/material-ui-x#2713]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I created a simple program to delete rows from data which is being showed in table on click of button,instead of deleting row it showed reference error. For refernce check https://codesandbox.io/s/datagridprodemo-material-demo-forked-bfrqc?file=/demo.js

### Expected behavior 🤔

data should have been deleted from the array provided to table.

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
You should avoid to mutate variables used as props in React.
Like a lot of React components, the Grid rely on the fact that the Grid `rows` prop has a new reference to rerun behaviors.
If you `pop` the array, we can't know that the array has changed.

https://codesandbox.io/s/datagridprodemo-material-demo-forked-eio6q?file=/demo.js
