### ISSUE TITLE
[docs] No row with id #1 found

### ISSUE THREAD

**Issue by rishav-ameyo** [mui-org/material-ui-x#2714]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Populate data in table, in action column we have a delete button on click of which a row is deleted, now when I click on delete button it shows error "No row with id #1 found". I tested it on the example provided on Material Page itself. Whenever I run the example  on sandbox  it shows the error 

### Expected behavior 🤔

On click of delete button row should be deleted.

### Steps to reproduce 🕹

Steps:

1. Open https://mui.com/components/data-grid/columns/#column-types
2. On material page itself try to delete a row button provided in action column, it would delete row without any issue
3. Now try to open the same example in sandbox , and try to delete row,
4.It will show error.

### Context 🔦

Unable to delete rows or rows, it is showing id error

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
This error happens because there's a race condition. After the click, the grid tries to set the focus, but the row was already removed. Wrapping the state update in a `setTimeout` as below solves the problem:

```ts
const deleteUser = React.useCallback(
  (id: GridRowId) => () => {
    setTimeout(() => {
      setRows((prevRows) => prevRows.filter((row) => row.id !== id));
    });
  },
  [],
);
```

**Comment by bestickley** [comment]
I ran into a similar issue trying to delete an item. Fix for me was wrapping the functions (specifically `getRowId`) I was passing to `DataGrid` with `useCallback`. Documenting here for anyone else who runs into this issue.

**Comment by kochcj1** [comment]
The suggested solution didn't work for me:
```ts
const deleteUser = React.useCallback(
  (id: GridRowId) => () => {
    setTimeout(() => {
      setRows((prevRows) => prevRows.filter((row) => row.id !== id));
    });
  },
  [],
);
```

But a slight variation of it did (see the second line):
```ts
const deleteUser = React.useCallback(
  (id: GridRowId) => {
    setTimeout(() => {
      setRows((prevRows) => prevRows.filter((row) => row.id !== id));
    });
  },
  [],
);
```

**Comment by nickmaddren** [comment]
A solution that worked for me was to stop propagation:

```
  const handleRemoveRow = (e: MouseEvent<HTMLButtonElement>) => {
    e.stopPropagation();
    dispatch({ type: 'DELETE_USER', id });
  };
```

**Comment by mubarakalmustpha** [comment]
The suggested solution didn't work for me:

const deleteUser = React.useCallback(
  (id: GridRowId) => {
    setTimeout(() => {
      setRows((prevRows) => prevRows.filter((row) => row.id !== id));
    });
  },
  [],
);

**Comment by joaobraganca555** [comment]
My problem was having this prop on the DataGrid  `isRowSelectable={(data) => data.row.status !== 'populating'}`

**Comment by Suazodev** [comment]
> My problem was having this prop on the DataGrid `isRowSelectable={(data) => data.row.status !== 'populating'}`

Exactly same problem here!

**Comment by alaa-m1** [comment]
I solved this issue by adding to the DataGrid the following prop:
`isRowSelectable={(data) => data.row !== undefined}`

**Comment by mhuggins** [comment]
> I ran into a similar issue trying to delete an item. Fix for me was wrapping the functions (specifically `getRowId`) I was passing to `DataGrid` with `useCallback`. Documenting here for anyone else who runs into this issue.

I wrapped all remaining props in useMemo & useCallback, and it fixed the issue for me.

**Comment by Brycetastic** [comment]
I'm still unable to prevent the error from being thrown when clicking multiple times quickly. debouncing helped a little but still I can consitently get that error to fire.
```const removeProductById = (id: number) => debounce(() => dispatch(removeProduct(id)), 200)();```
Results in this error message with multiple clicks: No row with id #### found

It is for sure a race condition where the first click removes the "row" data but the second click happens quick enough before the componet can catch up to the data changing. Here is the source code:
```  
   const getCellValue = react__WEBPACK_IMPORTED_MODULE_0__.useCallback((id, field) => {
    const colDef = apiRef.current.getColumn(field);
    if (!colDef || !colDef.valueGetter) {
      const rowModel = apiRef.current.getRow(id);
      if (!rowModel) {
        //**** This is where the error is thrown
        throw new MissingRowIdError(`No row with id #${id} found`);
      }
      return rowModel[field];
    }
    return colDef.valueGetter(getBaseCellParams(id, field));
  }, [apiRef, getBaseCellParams]);
```
I don't think a full error needs to happen here it could fail silently with a log warrning...

**Comment by Aberkati** [comment]
> `useCallback`

Do you have an example code please ? I have this error..
Thanks

**Comment by alfi-dim** [comment]
None of solution above is work for me, in my case, the error occurs when i interacted with any element on my page **AFTER** i delete selected rows (yes, i select rows first and delete them)

my code

```js
const onDeleteHandler = async (e, confirm) => {
    e.stopPropagation();

    setResAlert({
      open: false,
      message: ''
    });

    if (!confirm) {
      openDeleteDialog();
      return;
    }
    closeDeleteDialog();
    setLoading(true);

    await fetcher('/api/transactions/list', 'PATCH', { transactionsNumber: selectedRows })
      .then((res) => {
        setResAlert({
          open: true,
          message: res.message
        });
      })
      .catch((e) => {
        setLoading(false);
        setResAlert({
          open: true,
          message: e?.message ?? 'Failed to delete data',
          error: true,
        });
      });
    setTimeout(async () => {
      setSelectedRows([]);
      await mutate()
        .then((res) => {
          setData(res.data);
        });
    });
    setLoading(false);
  };
```

any solution for this? thanks!

**Comment by MasakiFUJISAWA** [comment]
Any solutions specified above are not worked in my case.
In every case, error message is same and is occurred in GridRow object. ("apiRef.current.getRowParams" function tries to get a row by id but it is already removed.)

<img width="595" alt="Image" src="https://github.com/user-attachments/assets/30c13567-edf5-43e4-8b95-d649bf355650" />

So I avoided this error by updating a value of key for DataGrid tag when I delete one ore more existing row in it like this.

<img width="577" alt="Image" src="https://github.com/user-attachments/assets/777068bf-2094-440c-afd5-014888275e4b" />

**Comment by FrontierJarrodVerhagen** [comment]
I'm using React. I am experiencing this issue when I change the rows array passed into the datagrid which happens when an external filter is changed. Of course the rows are now missing, I am trying to show different rows. This causes the error which breaks rows in the datagrid and they will no longer re-render. None of the fixes people have suggested work. I really need a way to fix this that asap.
