### ISSUE TITLE
[DataGrid] Unable to show columns again after all columns were hidden

### ISSUE THREAD

**Issue by esskar** [mui-org/material-ui-x#2718]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When all columns are hidden, there is no way to reshow them again.

### Expected behavior 🤔

The UI should have a option to reshow columns again after the last column was hidden.

### Steps to reproduce 🕹

Steps:

1. Hide the last column or choose to hide all columns.

### Your environment 🌎

System:
    OS: macOS 11.5.2
  Binaries:
    Node: 16.3.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.15.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 93.0.4577.82
    Edge: Not Found
    Firefox: 90.0.2
    Safari: 14.1.2
  npmPackages:
    @mui/x-data-grid-pro: ^4.0.0 => 4.0.0 
    @mui/x-license-pro:  4.0.0 
    @types/react: ^17.0.14 => 17.0.17 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.3.5 => 4.3.5 

### Order ID 💳 (optional)

210020 - ITB14401

**Comment by flaviendelangle** [comment]
Hi @esskar , thanks for raising this. 
Please provide a minimal reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/material-ui-issue-next-o7xkt) _may_ be a good starting point. Thank you!

**Comment by esskar** [comment]
It is a general behaviour of the grid. If the columns get manually hidden, there is no way to show them again once they all have  been hidden as there is no context menu available anymore.

**Comment by DanailH** [comment]
If I understand the problem correctly you can enable the toolbar and open the column menu from there. Also if you are using the `DataGridPro` you can use the `apiRef` to programmatically show/hide the columns.

**Comment by m4theushw** [comment]
For the "choose to hide all columns" part, adding the toolbar allows to re-show all columns as pointed by @DanailH 

For the case where the last column gets manually hidden and the toolbar is not available, we could disable the "Hide" button in the column menu when there's only one visible column. This closes this issue.

**Comment by flaviendelangle** [comment]
We also have the "Hide all" button on the "Show columns" menu that is unusable without a Toolbar because if you click on it you can't show the columns after.

**Comment by esskar** [comment]
Is there a timeline on this?

**Comment by flaviendelangle** [comment]
Would disabling the "Hide" button on the column menu when all but one columns are hidden work for you ?
That should be easy to do.

I think we have deeper changes to make to have a great hiding behavior but this quick fix may be enough at first.

**Comment by esskar** [comment]
yes, that would my customers happy. thanks. :)
