### ISSUE TITLE
[DataGrid] Sorting not working with valueGetter

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#272]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Sorting doesn't work with `valueGetter`.

## Expected Behavior 🤔

Sorting should work with `valueGetter`.

## Steps to Reproduce 🕹

Steps:

1. https://codesandbox.io/s/pedantic-shaw-s5v2p
2. Try sorting on the last column 

## Context 🔦

Working on the documentation for this feature.

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | v0.1.67  |

**Comment by oliviertassinari** [comment]
No matter the solution we go with, we should make sure that https://material-ui.com/components/data-grid/rendering/#value-getter is free of this issue.

**Comment by dtassone** [comment]
> No matter the solution we go with, we should make sure that https://material-ui.com/components/data-grid/rendering/#value-getter is free of this issue.

Fair enough, we just need to add a customComparator to the last column. I will fix it after this issue on typings

**Comment by oliviertassinari** [comment]
> Fair enough, we just need to add a customComparator to the last column. I will fix it after this issue on typings

Will we also need to implement a custom filterMethod and quickSearchMethod once we add these features?
