### ISSUE TITLE
[DataGrid] Expose formatted value (valueFormatter) in renderCell

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#273]
The `valueFormatter` prop has a very close use case to `renderCell`. From what I understand, the only reason we have the two is that we might format the value of a cell outside of a cell. Like in a filtered view or grouping view. This leads me to my issue.

Shouldn't `renderCell` receive the output of `valueFormatter`?

**Comment by warrenspe** [comment]
+1 on this

As a workaround however,

```
function renderCell(params) {
    let value = params.value;
    if (params.colDef.valueFormatter) {
      value = params.colDef.valueFormatter(params);
    }
    ... // Use value
}
```

**Comment by dtassone** [comment]
How about I add `formattedValue` in `CellParams`? So if you need the core value you have it and you also have the formatted one

**Comment by warrenspe** [comment]
Sounds reasonable - backwards compatible too

**Comment by oliviertassinari** [comment]
> How about I add formattedValue in CellParams?

@dtassone **If** we plan on keeping the `valueFormatter` option in the stable release, then this sounds great. I can't remember we have ever discussed this one: 

Should we remove the `valueFormatter` option? It doesn't seem that the data grid leverages this option, nor that we have identified real use case for it. But maybe I'm wrong. Maybe it will be relevant for the future aggregation or pivot functions?

**Comment by oliviertassinari** [comment]
@dtassone OK, let me ask the question differently. What problem does `valueFormatter` solve that `renderCell` can't?

As far as I understand it, the answer is none.
It also seems that ag-Grid made the distinction for two reasons: 1. for performance considerations, ag-Grid needs to bridge react > native > react when renderCell is used, however, they can do react > native when only valueFormatter is used. 2. for rendering the cell's value in the filter view.
