### ISSUE TITLE
[v5] Drop the @mui/styles dependency

### ISSUE THREAD

**Issue by Haaxor1689** [mui-org/material-ui-x#2746]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Since MUI is moving away from using the `makeStyles` approach and even the official migration guide suggests migrating to `sx` or `styled` are you planning to do the same? Also it would be great if the grid's components supported `sx` prop as is now the case with all other MUI components.

### Motivation 🔦

I've upgraded to MUI v5 and also upgraded grid to v5. I have also migrated styles to the new preferred MUI styling solution but am still required to leave `@mui/styles` in as a dependency because of grid.

Also related issue about styling migration of MUI [here](https://github.com/mui-org/material-ui/issues/22342).

### Order ID 💳 (optional)

#28342

**Comment by m4theushw** [comment]
Yes, we plan to support the `sx` prop and remove the dependency on @mui/styles. You can subscribe to #1234 to get notified when the migration is done.
