### ISSUE TITLE
Rollout of v5 :rocket: 

### ISSUE THREAD

**Issue by flaviendelangle** [mui-org/material-ui-x#2748]
This issue is here to discuss what we should finish before release the 1st stable version of the v5.

The issues we decide to include in the v5 will be listed in [the v5 milestone](https://github.com/mui-org/material-ui-x/milestone/16)

____

To summerize, the v5 version only supports the v5 version of the core (no more `@material-ui/core@4.X`, [see Migration Guide](https://mui.com/guides/migration-v4/#main-content))

**Comment by flaviendelangle** [comment]
@m4theushw do you intend to finish the new virtualization implementation before the launch of the stable version ?

**Comment by Jucabel** [comment]
Hello.

[DataGrid]

I'm having this:

<img width="928" alt="Screen Shot 2021-10-01 at 09 31 10" src="https://user-images.githubusercontent.com/36972766/135637879-819a3047-d58c-480f-b5af-2c5350284d62.png">

Just for the info, I already migrated to mui v5.

**Comment by DanailH** [comment]
@flaviendelangle thanks for the summary. I checked the linked issues but I don't think that the v5 release is dependant on all of them. 
For example this one:
- [DataGrid] Print export #2519 @DanailH
It is not really related to v5. It's a standalone feature. There set are ok, I think as they involve potential breaking changes

On another note - we can just repurpose this one https://github.com/mui-org/material-ui-x/issues/1902 and add/link all the relevant issues (maybe you already discussed it on Friday during the retro). I think we should aim to avoid having multiple tickets to track the same thing.

**Comment by flaviendelangle** [comment]
For #2519 their is nothing that forces us to merge it before the major release.
I think it will be merged before because we have 3 issues (#1902 , #2293 and #1933) that must be merged before the release. #1902 to be consistent with the core and the two others because they should cause a lot of small breaking changes / behavior changes and it would be better to do them before the major. So the major swill probably not be in the next 2-3 weeks, which gives us time.

**Comment by JStevens127** [comment]
Any chance https://github.com/mui-org/material-ui-x/issues/193 could be included? Thanks!

**Comment by flaviendelangle** [comment]
@JStevens127, we only add to the millestone things that would cause breaking changes.
#193 should not cause any.

But I think it is the next product feature we are going to focus on, so it should not take too long before being release.
We release every week or every two weeks so whenever the feature will be ready, it will quickly be released.

**Comment by oliviertassinari** [comment]
v5 is now officially released https://github.com/mui-org/material-ui-x/releases/tag/v5.0.0.
