### ISSUE TITLE
[core] Rename the package folders to match package names

### ISSUE THREAD

**Issue by flaviendelangle** [mui-org/material-ui-x#2749]
I am removing the `grid` level since the data grid packages will now be next to one another in the alphabetical order so even if we introduce 20 other components, it will be easy to find them.

- `packages/grid/data-grid` => `packages/mui-x-data-grid`
- `packages/grid/x-grid` => `packages/mui-x-data-grid-pro`
- `packages/grid/x-grid-data-generator` => `packages/mui-x-data-grid-generator`
- `packages/x-license` => `packages/mui-x-license-pro`

**Comment by m4theushw** [comment]
What about the `_modules_` which is shared between the two? The `grid` folder also groups the rollup config files.

I think we should first rename `packages/grid/data-grid` ->  `packages/grid/x-data-grid`.

**Comment by flaviendelangle** [comment]
I would split the work in two disctinct steps

1) Rename the top level folders (`packages/grid/data-grid` and `packages/grid/x-grid`)
2) Remove the `_modules_` folder and put the content shared by `DataGrid` and `DataGridPro` into the `x-data-grid` folder and the content exclusive to `DataGridPro` into the `x-data-grid-pro` folder.

**Comment by oliviertassinari** [comment]
I have extended the initial proposal with:

1. `@mui/x-license-pro` the folder is also not matching the folder name on git
2. In the main repository, we use the full npm pathname, including `mui`. Should we do the same here too?

**Comment by flaviendelangle** [comment]
For the exact name of the folder, I am open to suggestion

@oliviertassinari would go for `packages/mui-x-data-grid-pro`
@m4theushw would go for `packages/grid/x-data-grid-pro`
(from what I understand)

I would follow the core structure, which is prefixing everything with `mui-*` and not grouping by theme (they have `packages/mui-style-engine` and `packages/mui-style-engine-sc` for instance, not `packages/style/mui-style-engine` and `packages/style/mui-style-engine-sc`). 
If the argument for keeping `grid` is just to help during the transition before removing `_modules_` (my point 2.) then fine for me.
