### ISSUE TITLE
[RFC] Remove cellClassRules

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#275]
With the same motivation as #274. I think that we can remove `cellClassRules`. We can turn a new API:

```js
cellClassRules: {
  negative: {value} => value < 0,
  positive: {value} => value > 0,
},
```

into something we already teach to developers:

```jsx
cellClassName: (params) => clsx({
  negative: params.value < 0,
  positive: params.value > 0,
})
```

simpler.

**Comment by dtassone** [comment]
Well `params.value` needs to be checked at the time of rendering, not when you configure the grid.

**Comment by oliviertassinari** [comment]
I have created a demo with the proposed approach: https://deploy-preview-267--material-ui-x.netlify.app/components/data-grid/rendering/#styling-cells. Does it work correctly?

**Comment by dtassone** [comment]
Ah yes I didn't notice that the prop was a function so it works.
