### ISSUE TITLE
DataGrid bug?

### ISSUE THREAD

**Issue by wang-jian-yu** [mui-org/material-ui-x#2752]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I just want to change the content of the GridToolbarColumnsButton and I can't change it  

### Expected behavior 🤔

I just want to change the text

### Steps to reproduce 🕹

Steps:

1.Use the DataGrid component and then customize the contents of the Toolbar  
2.
3.
4.

### Context 🔦

![image](https://user-images.githubusercontent.com/56787673/135699168-b87da730-b8d3-4195-9965-dcb632cca3d5.png)
![image](https://user-images.githubusercontent.com/56787673/135699186-76b1956a-8e04-4e4d-8bd5-c56623e9fff4.png)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

````
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>


### Order ID 💳 (optional)

#8888

**Comment by wang-jian-yu** [comment]
![image](https://user-images.githubusercontent.com/56787673/135699248-e8de7bfa-7b05-43cc-be50-e3d649f2cfbf.png)
But I can't change the writing

**Comment by ZeeshanTamboli** [comment]
>I just want to change the text

If you want to change the text of the columns toolbar you can use the `localeText` prop. 
```jsx
    <DataGrid
        {...data}
        localeText={{
          toolbarColumns: 'test'
        }}
        components={{
          Toolbar: GridToolbar,
        }}
      />
```

See the localization section for more details: https://mui.com/components/data-grid/localization/ 

Supported translation keys: https://github.com/mui-org/material-ui-x/blob/HEAD/packages/grid/_modules_/grid/constants/localeTextConstants.ts
