### ISSUE TITLE
[DataGrid] Wrong CSS specifity for column headers, CSS override not possible

### ISSUE THREAD

**Issue by SeanMengis** [mui-org/material-ui-x#2796]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Using the `headerClassName` prop when defining columns for the data grid or when overriding the global class `.MuiDataGrid-columnHeaderTitle` creates a new CSS class with less specifity than the one injected by Material-UI. This makes it impossible to override props that are pre-defined like font-weight.

### Expected behavior 🤔

The class given in `headerClassName` should be prioritized.

### Steps to reproduce 🕹

Steps:

1. Open my example
2. Inspect the column header and check the CSS order

[Codesandbox](https://codesandbox.io/s/wizardly-firefly-q5tgq?file=/src/App.tsx:275-305)

### Context 🔦

I'd like to be able to modify all column header CSS properties.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
    System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    Yarn: Not Found
    npm: 7.8.0 - /usr/local/bin/npm
  Browsers:
    // Tested on Chrome and Firefox
    Chrome: 86.0.4240.198
    Firefox: 92.0
```
</details>

**Comment by m4theushw** [comment]
Fixed by #3012
