### ISSUE TITLE
[Datagrid] onRowClick is not fired on keyboard enter

### ISSUE THREAD

**Issue by PraveenPeri** [mui-org/material-ui-x#2797]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Configure onRowClick on the datagrid and it doesn't fire on keyboard hits - enter, shift + space, etc.

### Expected behavior 🤔

The same behavior should be available for the keyboard users. It isn't accessible otherwise.

### Steps to reproduce 🕹

Steps:

1. Go to the below sandbox and click on a row to see the console.log statement
2. Now try to select the row through keyboard and see you can't get it work by any way

https://codesandbox.io/s/material-demo-forked-27d9n?file=/demo.js

### Context 🔦

Building a web application that is supposed to be accessible.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Linux 4.14 Amazon Linux 2
    CPU: (4) x64 AMD EPYC 7571
    Memory: 11.11 GB / 15.53 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 14.15.4 - /usr/bin/node
    npm: 7.10.0 - /usr/bin/npm
  Managers:
    pip2: 18.0 - /usr/bin/pip2
    pip3: 9.0.3 - /usr/bin/pip3
    Yum: 3.4.3 - /usr/bin/yum
  Utilities:
    Make: 3.82 - /usr/bin/make
    GCC: 7.3.1 - /usr/bin/gcc
    Git: 2.23.3 - /usr/bin/git
  Virtualization:
    Docker: 19.03.13 - /usr/bin/docker
  IDEs:
    Emacs: 25.3.1 - /usr/bin/emacs
    Nano: 2.9.8 - /usr/bin/nano
    VSCode: 1.60.2 - /home/pperi@huronconsultinggroup.com/.vscode-server/bin/7f6ab5485bbc008386c4386d08766667e155244e/bin/code
    Vim: 8.1 - /usr/bin/vim
  Languages:
    Bash: 4.2.46 - /usr/bin/bash
    Perl: 5.16.3 - /usr/bin/perl
    Python: 2.7.18 - /usr/bin/python
    Python3: 3.7.9 - /usr/bin/python3
  Databases:
    SQLite: 3.7.17 - /usr/bin/sqlite3
  Browser: Edge/Chrome
```
</details>

**Comment by m4theushw** [comment]
The `onRowClick` prop is meant to be called only when there's a mouse click, not for keyboard interactions. 

If you want to get notified every time a row is selected (whether clicking or pressing <kbd>Shift</kbd> + <kbd>Space</kbd>) you can use the `onSelectionModelChange` prop. See https://mui.com/components/data-grid/selection/#controlled-selection for an example.

**Comment by m4theushw** [comment]
In the free version no, you have to iterate through the `rows` prop to find the equivalent row to the id received. In the Pro version, you can call `apiRef.current.getSelectedRows`.

**Comment by PraveenPeri** [comment]
We are using Pro version. I will give it a try and get back.

**Comment by flaviendelangle** [comment]
For the free version it is a limitation that I think we should improve someday.
But for the paid version, it should work fine with @m4theushw solution :+1: , you have the full documentation here https://mui.com/components/data-grid/selection/#apiref

**Comment by corneliushka** [comment]
Much simpler: apiRef.current.getRow(ROWID)
