### ISSUE TITLE
Please add onRowSelected API to the data grid

### ISSUE THREAD

**Issue by PraveenPeri** [mui-org/material-ui-x#2798]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

onRowSelected was able in the alpha release of x-grid but was removed in the official release. It worked great in two aspects

1. Works with keyboard navigation(Shift + space)
2. Has the isSelected boolean in the GridRowSelectionParams depending on which, we could implement certain logic

With the API now gone, there isn't a way to do either of the above. Could you add it back? or is there a way to achieve these with the existing API?

### Examples 🌈

`<DataGridProp onRowSelected={p => console.log(p.isSelected)}` />

### Motivation 🔦

We have a use-case in our application to do things based on if a row is selected or deselected in a datagrid with checkbox selection.

**Comment by PraveenPeri** [comment]
@flaviendelangle I did look at onSelectionModelChange but it returns an array of row Ids. What I need is the entire row information of the selected rows. Is there a way to get that information?

**Comment by flaviendelangle** [comment]
I'm closing this issue to centralize the answers in https://github.com/mui-org/material-ui-x/issues/2797 :+1:
