### ISSUE TITLE
[DataGrid] renderEditCell method not found in  "@material-ui/x-grid": "^4.0.0-alpha.27",

### ISSUE THREAD

**Issue by robsilva** [mui-org/material-ui-x#2799]
- [ ] The issue is present in the latest release.
- [ X] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
I am following the documentation found here https://v4.mui.com/components/data-grid/editing/ in order to implement a custom component to update the cell value, but I am getting this error saying renderEditCell is not a function.
```
 { 
      field: "groups", 
      headerName: "Primary Group", 
      width: 300, 
      editable: true,
      // renderCell: param => <Chip label={param.value} color="primary"/> 
      renderEditCell: <PrimaryGroupSelector/>
    },
```

## Steps to Reproduce 🕹

Steps:

1.
2.
3.
4.

## Your Environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
  
  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 18.13 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.3 - /usr/local/bin/node
    npm: 6.14.4 - /usr/local/bin/npm
  Managers:
    Homebrew: 3.2.5 - /usr/local/bin/brew
    pip3: 20.2.1 - /Library/Frameworks/Python.framework/Versions/3.8/bin/pip3
    RubyGems: 3.0.3 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 10.15. - /usr/bin/gcc
    Git: 2.24.3 - /usr/bin/git
    Clang: 1200.0.32.27 - /usr/bin/clang
  Servers:
    Apache: 2.4.46 - /usr/sbin/apachectl
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 30
      Build Tools: 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    IntelliJ: 2021.2
    Nano: 2.0.6 - /usr/bin/nano
    Sublime Text: Build 3211
    Vim: 8.1 - /usr/bin/vim
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 1.8.0_121 - /usr/bin/javac
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.3.11 - /usr/bin/php
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.8.6 - /Library/Frameworks/Python.framework/Versions/3.8/bin/python3
    Ruby: 2.6.3 - /usr/bin/ruby
  Databases:
    MongoDB: 4.2.8 - /usr/local/bin/mongo
    PostgreSQL: 13.3 - /usr/local/bin/postgres
    SQLite: 3.28.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 94.0.4606.71
    Edge: 94.0.992.38
    Firefox: 75.0
    Safari: 14.1.2
```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by DanailH** [comment]
Hi, @robsilva thanks for raising this.

Can it be because you are not respecting the type of the `renderEditCell`? You can check it here https://v4.mui.com/api/data-grid/grid-col-def/

If that doesn't work it would be great if you can provide a minimal reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/material-ui-issue-next-o7xkt) _may_ be a good starting point. Thank you!
