### ISSUE TITLE
Data Grid component produces error

### ISSUE THREAD

**Issue by PeterHua888** [mui-org/material-ui-x#2809]
## Current Behavior 😯

The data grid component of the latest version produces the following error
`RangeError: Maximum call stack size exceeded`

## Expected Behavior 🤔

No error

## Steps to Reproduce 🕹

I used the exact same code from the website example 
https://mui.com/components/data-grid/

## Context 🔦

I tried run it on different OS and browser and got the same issue. Can anyone advise on it?

## Your Environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
  
```
  System:
    OS: macOS 11.5.2
  Binaries:
    Node: 16.10.0 - /opt/homebrew/bin/node
    Yarn: Not Found
    npm: 7.24.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 94.0.4606.61
    Edge: Not Found
    Firefox: Not Found
    Safari: 14.1.2
  npmPackages:
    @emotion/react: ^11.4.1 => 11.4.1 
    @emotion/styled: ^11.3.0 => 11.3.0 
    @mui/core:  5.0.0-alpha.49 
    @mui/icons-material: ^5.0.1 => 5.0.1 
    @mui/material: ^5.0.2 => 5.0.2 
    @mui/private-theming:  5.0.1 
    @mui/styled-engine:  5.0.1 
    @mui/system:  5.0.2 
    @mui/types:  7.0.0 
    @mui/utils:  5.0.1 
    @mui/x-data-grid: ^4.0.0 => 4.0.0 
    @mui/x-data-grid-pro: ^4.0.0 => 4.0.0 
    @mui/x-license-pro:  4.0.0 
    @types/react:  17.0.24 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
```
</details>

**Comment by m4theushw** [comment]
Could you provide a reproduction test case. The latest version was released yesterday so it might have already fixed the bug since I can't see the error when opening the page. [This **codesandbox.io** template](https://mui.com/r/issue-template-latest) _may_ be a good starting point.

**Comment by hh-lohmann** [comment]
I suppose it's this error: "MUI: GridErrorHandler - An unexpected error occurred. Error: Maximum call stack size exceeded. RangeError: Maximum call stack size exceeded". Ran into it after pushing from a dev env with @mui/x-data-grid 5.6.1 to a production env with 5.9.0. Four DataGrids in same view with same data, displaying different aspects of data, first table produces error, other three tables after it OK. Table 1 with error uses renderCell with params.row, but table 4 in the same view with more complex renderCell with params.row works fine. Had to downgrade production to 5.6.1 to make things work, no time for deeper investigation, sorry.
