### ISSUE TITLE
[DataGrid] Extend components API to support custom checkbox

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#281]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Provide a new entry point in the `components` prop to customize the checkbox

## Examples 🌈

```jsx
<DataGrid
  components={{
    Checkbox: MyCheckbox
  }}
/>
```

<img width="221" alt="Capture d’écran 2020-09-13 à 19 27 44" src="https://user-images.githubusercontent.com/3165635/93024490-3bf72000-f5f7-11ea-88ae-f736ce000f98.png">

## Motivation 🔦

I was working on a customization example to match the Ant Design specification. Such an API could make customization easier. I'm not sure it's a frequent request, hence the "waiting for upvotes" label so we don't rush into implementation if it doesn't solve a strong pain.

**Comment by dtassone** [comment]
The way you could achieve this is by creating a column and passing a react component in the cell rendering. Then you could use the apiRef to do the behaviour bit.

**Comment by oliviertassinari** [comment]
Oh great, nice it hear there is a workaround. Snoozing until we get users reporting it :).

**Comment by dtassone** [comment]
How about we allow users to pick their underlying components library and icons. So it comes with MUI by default but you can also remove it and just use the grid with antd for example, what do you think?

**Comment by oliviertassinari** [comment]
@dtassone So basically:

```diff
diff --git a/packages/grid/x-grid-modules/src/models/gridComponentOverridesProp.tsx b/packages/grid/x-grid-modules/src/models/gridComponentOverridesProp.tsx
index fb482e5e..ffd3f77b 100644
--- a/packages/grid/x-grid-modules/src/models/gridComponentOverridesProp.tsx
+++ b/packages/grid/x-grid-modules/src/models/gridComponentOverridesProp.tsx
@@ -5,6 +5,10 @@ import { ComponentProps } from './params';
  * Grid components React prop interface containing all the overridable components.
  */
 export interface GridComponentOverridesProp {
+  /**
+   * The checkbox component used in the grid.
+   */
+  Checkbox?: React.ElementType<React.InputHTMLAttributes<HTMLInputElement>>;
   /**
    * Pagination component rendered in the grid footer by default.
    */
```

**Comment by nextglabs** [comment]
Upvote 👍

**Comment by oliviertassinari** [comment]
The latest direction on the components API we are taking is described in https://github.com/mui-org/material-ui/issues/23043#issuecomment-708283809.

**Comment by nextglabs** [comment]
> The latest direction on the components API we are taking is described in [mui-org/material-ui#23043 (comment)](https://github.com/mui-org/material-ui/issues/23043#issuecomment-708283809).

Thanks! But are you sure about the link?

**Comment by oliviertassinari** [comment]
@nextglabs Yes, we will apply the same API everywere.

**Comment by EdmundsEcho** [comment]
Nice work on the DataGrid; impressive.  

The work-around for customizing the checkbox seems like trouble if we don't connect the event listeners correctly.  

It seems like a small but important gap in the range of icons we can customize.  The checkbox is fundamental and as of now, does not match what I'm using elsewhere (the MUI check and clear icons without any other structure or background).

Is there an update on how to go about making this change?

\- E

**Comment by oliviertassinari** [comment]
We have explored a bit more this topic in #1457.

**Comment by lysoff** [comment]
hey @oliviertassinari, great job on this!
is it possible to pass a row as a prop for `Checkbox` component, so dev has more flexibility on customising it?

real world scenario: for a checkbox we have a component that is a row specific icon which turning into checkbox on hover
thanks!

**Comment by oliviertassinari** [comment]
@lysoff This issue is purely about customizing the look in the nominal use cases. I don't understand the question.

**Comment by lysoff** [comment]
@oliviertassinari i see the idea
the question is - is it possible to render specific `Checkbox` based on row data?

**Comment by oliviertassinari** [comment]
This is off scope for this issue.

**Comment by Redskinsjo** [comment]
I'd like to have change the checkbox by a select with options, that would select all the rows corresponding to the option selected.
