### ISSUE TITLE
[DataGrid] The intermediate state is lost when scrolling

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#283]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

<img width="101" alt="Capture d’écran 2020-09-14 à 12 18 32" src="https://user-images.githubusercontent.com/3165635/93074314-735fde00-f684-11ea-9569-3d62d43f89f0.png">

## Expected Behavior 🤔

<img width="99" alt="Capture d’écran 2020-09-14 à 12 18 35" src="https://user-images.githubusercontent.com/3165635/93074313-72c74780-f684-11ea-875a-017178d820f5.png">

## Steps to Reproduce 🕹

Steps:

1. https://master--material-ui-x.netlify.app/components/data-grid/#commercial-version
2. ![intermediate](https://user-images.githubusercontent.com/3165635/93074452-ac984e00-f684-11ea-8f30-94bf45457f88.gif)

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | v0.1.67  |

**Comment by dtassone** [comment]
I will take a look at this one too
