### ISSUE TITLE
[DataGrid] Fails to edit field of type `singleSelect` when paired with `editRowsModel`

### ISSUE THREAD

**Issue by TeoTN** [mui-org/material-ui-x#2836]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Given that there's an editable column defined with type `singleSelect`, 
and the DataGrid has controlled edit model (uses `editRowsModel` and `onEditRowsModelChange` props), 
when user double clicks on the field to edit the cell and selects an option from the dropdown
then the cell is not updated

(see below for reproduction) 

### Expected behavior 🤔

Cell should be editable

### Steps to reproduce 🕹

Minimal reproduction: https://codesandbox.io/s/mui-datagrid-bug-option-editing-updny?file=/demo.tsx
Copied an example from docs page and added single select column to demonstrate editing this cell won't work.

### Context 🔦

I'd like to have client-side validation when some fields are enums

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

  System:
    OS: Linux 4.19 Ubuntu 20.04.2 LTS (Focal Fossa)
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.15 - ~/.yarn/bin/yarn
    npm: 7.10.0 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @emotion/react: 11.4.1 => 11.4.1
    @emotion/styled: 11.3.0 => 11.3.0
    @mui/core:  5.0.0-alpha.49
    @mui/icons-material: 5.0.1 => 5.0.1
    @mui/lab: 5.0.0-alpha.49 => 5.0.0-alpha.49
    @mui/material: 5.0.2 => 5.0.2
    @mui/private-theming:  5.0.1
    @mui/styled-engine:  5.0.1
    @mui/styles: 5.0.1 => 5.0.1
    @mui/system:  5.0.2
    @mui/types:  7.0.0
    @mui/utils:  5.0.1
    @mui/x-data-grid: 5.0.0-beta.3 => 5.0.0-beta.3
    @types/react: 17.0.3 => 17.0.3
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2
    typescript: 4.3.5 => 4.3.5
</details>

**Comment by TeoTN** [comment]
I did a little bit of poking around and it seems that the issue is also present when using custom `renderEditCell`. The issue seems to be that committed value is empty - when I added `onCellEditCommit`, the committed value was empty.
However, if I scheduled the commit for a bit later, it worked like a charm:
```
setTimeout(() => {
  api.commitCellChange({ id, field });
  api.setCellMode(id, field, 'view');
}, 100)
```
I presume that there's a re-render missing between when edit model state updates and commit phase pulling the state.

**Comment by m4theushw** [comment]
Your investigation is correct. We commit the value synchronously while the prop is updated asynchronously. As a workaround, wrapping the two operations with a `setTimeout` fixes this bug. Do you want to open a PR?

```diff
diff --git a/packages/grid/_modules_/grid/components/cell/GridEditSingleSelectCell.tsx b/packages/grid/_modules_/grid/components/cell/GridEditSingleSelectCell.tsx
index 7965db86..99ea4856 100644
--- a/packages/grid/_modules_/grid/components/cell/GridEditSingleSelectCell.tsx
+++ b/packages/grid/_modules_/grid/components/cell/GridEditSingleSelectCell.tsx
@@ -64,8 +64,10 @@ function GridEditSingleSelectCell(props: GridRenderEditCellParams & SelectProps)
     setOpen(false);
     api.setEditCellValue({ id, field, value: event.target.value }, event);
     if (!event.key && rootProps.editMode === 'cell') {
-      api.commitCellChange({ id, field }, event);
-      api.setCellMode(id, field, 'view');
+      setTimeout(() => {
+        api.commitCellChange({ id, field }, event);
+        api.setCellMode(id, field, 'view');
+      });
     }
   };
```

For a definitive solution and also to fix the pointed raised by @flaviendelangle, I think we should not to allow to control the edit state. As more components that have this self-commit behavior (don't require to click outside to commit) we add, more situations like that will happen. Since the `editRowsModel` is only used for validation, we could replace it with a new `validateRow` prop which receives the internal state and returns an object with the fields that contain errors. For async validation, it can return a promise. That way, the editing state becomes synchronously again while validating is still possible.

**Comment by m4theushw** [comment]
> If you think the best solution is to drop this control state altogether, when do you think we should do it ? For the 6.0 release ? I think we should gather feedbacks of people using it to check if they don't use it in a way that we did not anticipate.

This can be postponed to v5.1 maybe. We can add the `validateRow` now and start promoting its usage in place of the controlled mode.

**Comment by mfaheemakhtar** [comment]
I am unable to get the `singleSelect` working using this code. This works fine with text and checkbox. The newModel is `{}`.

```
async ({ id, field, props }: GridEditCellPropsParams, event) => {
  let newModel = apiRef.current.getEditRowsModel();
}
```

I think my issue is similar/same to this issue? Or should I create a new one?

Is there a temporary workaround?

**Comment by flaviendelangle** [comment]
Could you give me a reproduction case, you can use this [template](https://codesandbox.io/s/datagridpro-v5-quick-start-5pjhc) as a starting point ?

**Comment by mfaheemakhtar** [comment]
@flaviendelangle , sorry nevermind. Turns out the debounce wrapper is causing the issue not the grid.

If you still want to see: https://codesandbox.io/s/datagridpro-v5-quick-start-forked-dnzdl?file=/src/App.tsx

**Comment by m4theushw** [comment]
Starting in v5.0.1, there's a new API for validation which solves the problem mentioned here. You can use `preProcessEditCellProps` instead of `editRowsModel`.

See https://mui.com/components/data-grid/editing/#client-side-validation for more information.

**Comment by mfaheemakhtar** [comment]
Thanks, @m4theushw! This is wonderful.

The `singleSelect` is calling the edit function twice. Its not a big deal for me because of debounce but the second call overwrites the new updated value.

Small Reproduction: https://codesandbox.io/s/datagridpro-v5-quick-start-forked-pxc4e?file=/src/App.tsx
