### ISSUE TITLE
DataGrid Column Inline Example missing closing JSX Slash

### ISSUE THREAD

**Issue by dstarner** [mui-org/material-ui-x#2838]
## Summary

[Two lines in the Column documentation](https://github.com/mui-org/material-ui-x/blob/next/docs/src/pages/components/data-grid/columns/columns.md?plain=1#L281-L282) concerning the `actions` type are missing their closing `/>`, instead they incorrectly have `>` with no actually closing.

```tsx
  {
    field: 'actions',
    type: 'actions',
    getActions: (params: GridRowParams) => [
      <GridActionsCellItem icon={...} onClick={...} label="Delete">,
      <GridActionsCellItem icon={...} onClick={...} label="Print" showInMenu>,
    ]
  }
```

### Present In

`@mui/x-data-grid: "5.0.0-beta.3"`

### Category

Documentation

---

This seems like a super small PR that I would like to implement if allowed.

**Comment by ZeeshanTamboli** [comment]
Hi @dstarner . Thanks for raising this.

Yes, you can go ahead and fix the docs by forking the repo and raising a PR. Thanks for helping. I will assign you.
