### ISSUE TITLE
[docs] Infinite documentation page reloading for non-eng OS 

### ISSUE THREAD

**Issue by venik2007** [mui-org/material-ui-x#2844]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

For my (Russian) OS docs pages are infinitely reloads.
Example of pages:
https://mui.com/components/data-grid/getting-started/

Reproduced for two laptops with Windows 10, for IPhone 7plus (iOS) and Xiaomi Redmi (Android 11)
Browsers: Chrome/Firefox/Mobile safari
Incognito mods has been tested too.

![image](https://user-images.githubusercontent.com/52424112/136852809-190177b2-be33-4063-b560-9c02409a8e93.png)
![image](https://user-images.githubusercontent.com/52424112/136852824-9af69932-cbc4-401f-a445-1941c59103e9.png)

### Expected behavior 🤔

Docs pages loads correctly

### Steps to reproduce 🕹

Steps (easiest way to test it on phone OS, for ex. Android):

1. Switch system language to Russian (Русский)
2. Open link https://mui.com/components/data-grid/getting-started/

PS. To switch back to Eng locale type in settings search `Язык и ввод` -> `Языки` and choose English (`Английский`)
or
Open settings and walk through that steps:
![image](https://user-images.githubusercontent.com/52424112/136853539-f16bf115-a9fa-4ad7-823f-b5e624af5793.png)
![image](https://user-images.githubusercontent.com/52424112/136853697-27b9dc6a-05f7-4c74-85bb-91fe0440f406.png)
![image](https://user-images.githubusercontent.com/52424112/136853740-3fd4db29-c360-4cae-aec4-07d5114b468d.png)

### Context 🔦

I can't read mui docs, even on english, even if i'll switch docs language to english. Current workaround for me is to switch my smartphone language to english and read docs there, but it is much slower then just do it on my work laptop

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Reproduced for two laptops with Windows 10, for IPhone 7plus (iOS) and Xiaomi Redmi (Android 11)
  Browsers: Chrome/Firefox/Mobile safari
  Incognito mods has been tested too.
```
![image](https://user-images.githubusercontent.com/52424112/136854825-a6a757f6-5d2c-41ed-b65a-eb458c96b2b0.png)
</details>

**Comment by ivankhm** [comment]
I just encountered this problem too, even though I have eng OS (geographically I'm in Russia). I noticed, that my browser's language was still `Russian`, so I changed it to `English (USA)` and now DataGrid's pages open normally! 

I didn't test if only the browser's language was the issue, or the system's+ browser's language.

**Comment by mbrookes** [comment]
The language menu still lists all the previously supported languages on the data grid pages, and the infinite reload happens if you select any unsupported language.

I'm guessing it would also be a problem for anyone that had previously selected a now unsupported language, and still has the `userLanguage` cookie.

**Comment by mbrookes** [comment]
As a workaround for both causes you can visit a non-data-grid docs page and select English as the preferred language to set the userLanguage cookie to 'en', overriding the browser language setting, or any previously chosen language.

**Comment by oliviertassinari** [comment]
We keep getting report of this, something is wrong.

**Comment by mvictorl** [comment]
People!
Are you discussing how to set up your system to display a website ?!
Not a application, not a library - **WEB-F-SITE** !!!
**Let them change the Front-end developer !!!**

**Comment by flaviendelangle** [comment]
Updating the monorepo was not enough, we had a copy / paste of the old constants on our repo.
I am opening a PR to check if using the core constants fixes it.

**Comment by oliviertassinari** [comment]
Right https://github.com/mui-org/material-ui-x/blob/5f80fd03ff18e64bc270f5a31248e0e8a4a6c30b/docs/pages/_app.js#L87. Also, I have updated the content of the _app file on the core repository, it will likely break again. It sounds like we should import the bulk of the _app from the main repository, not copy paste.

**Comment by flaviendelangle** [comment]
On #3143 I am re-exporting all the constants from the core AND applying the same `acceptLanguages.languages(LANGUAGES)` fix as the core did.

But I agree that we should limit the copy pasted code in the future :+1:

**Comment by flaviendelangle** [comment]
Update: I confirm, my fix works

**Comment by flaviendelangle** [comment]
It should now be fixed https://mui.com/components/data-grid/
