### ISSUE TITLE
[question] - Infinite Loading Server Side.

### ISSUE THREAD

**Issue by vsspt** [mui-org/material-ui-x#2845]
### Order ID 💳

#28950

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [x] I have tested the latest version

### Summary 💡

I'm using Infinite Loading, with loading being done server side.
Although the loading in chunks is being correctly executed, and the number of row reflects it, the Grid is not rendering all the rows, and just a small subset of them.

### The problem in depth 🔍

I've researched Infinite Loading, having found two resources:
- https://github.com/mui-org/material-ui-x/issues/1247
- https://github.com/mui-org/material-ui-x/pull/1199

These resources provide two examples:
- Documentation: https://deploy-preview-1199--material-ui-x.netlify.app/components/data-grid/rows/#infinite-loading
- Demo: https://deploy-preview-1199--material-ui-x.netlify.app/storybook/?path=/story/x-grid-tests-rendering--infinite-loading

Based on these examples, i create a Sandbox that loads the data from an Backend API that provides paging:
- https://codesandbox.io/s/billowing-platform-mq6tl?file=/src/App.js

Unfortunately, although loading in chunks is being correctly executed, and the number of row reflects it, the Grid is not rendering all the rows, and just a small subset of them.

I must be missing some small detail, but i cannot find what it is.

What am i missing?

Thank you!

### Context 🔦

Replacing all the regular Paging with Infinite Loading on all grids.

### Your environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>

```
  ←[4mBinaries:←[0m
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  ←[4mUtilities:←[0m
    Git: 2.29.2.
  ←[4mBrowsers:←[0m
    Edge: Spartan (44.19041.1023.0), Chromium (94.0.992.38)
    Internet Explorer: 11.0.19041.1202
  ←[4mMonorepos:←[0m
    Yarn Workspaces: 1.22.15
    Lerna: 4.0.0
```
</details>

**Comment by oliviertassinari** [comment]
I'm closing for #1247. This issue is indeed about, having pages of up to 100,000 rows, and lazy loading rows as they are visible in the viewport. This avoid using a footer pagination.
