### ISSUE TITLE
[DataGrid] Recreating columns while DataGrid is closed doesn't render content

### ISSUE THREAD

**Issue by ronnyroeller** [mui-org/material-ui-x#2853]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Recreating the `column` of a DataGrid (which contains a `renderCell` function) while the DataGrid is hidden, doesn't render the content wants the DataGrid is again visible.

## Expected Behavior 🤔

Content of DataGrid renders when the DataGrid becomes again visible.

## Steps to Reproduce 🕹

Steps:

1. Open codesandbox: https://codesandbox.io/s/dawn-hooks-lh58v?file=/src/Demo.tsx:624-636
2. Click [Hide] button
3. Click [Recreate columns] button
4. Click [Show] button
=> Now the grid content doesn't show

5. Click [Recreate columns] button
=> Now the grid shows again

Uploading Screen Recording 2021-10-12 at 3.24.10 PM.mov…

## Context 🔦

We have a splitscreen layout with the main content on the left column and support column in the smaller right column. The right column contains a DataGrid. The user can collapse the right support column to get more space for the main column. While working in the main column, the user can make changes that do import the DataGrid. If the user afterwards reopens the right column, the DataGrid doesn't show.

## Workaround

Hide the DataGrid with `opacity: 0` instead of `display: none`.

## Your Environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
  npx: installed 2 in 4.191s

  System:
    OS: macOS 11.6
  Binaries:
    Node: 14.17.0 - ~/n/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
  Browsers:
    Chrome: 94.0.4606.81
    Edge: 91.0.864.37
    Firefox: 93.0
    Safari: 15.0
  npmPackages:
    @emotion/react: ^11.4.1 => 11.4.1 
    @emotion/styled: ^11.3.0 => 11.3.0 
    @mui/core:  5.0.0-alpha.49 
    @mui/icons-material: ^5.0.1 => 5.0.1 
    @mui/lab: ^5.0.0-alpha.50 => 5.0.0-alpha.50 
    @mui/material: ^5.0.2 => 5.0.2 
    @mui/private-theming:  5.0.1 
    @mui/styled-engine:  5.0.1 
    @mui/styles: ^5.0.1 => 5.0.1 
    @mui/system:  5.0.2 
    @mui/types:  7.0.0 
    @mui/utils:  5.0.1 
    @mui/x-data-grid-pro: ^v5.0.0-beta.2 => 5.0.0-beta.2 
    @mui/x-license-pro:  5.0.0-beta.2 
    @types/react: ^16.14.14 => 16.14.16 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: 4.2.2 => 4.2.2 
```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
I'm closing this one. The content now correctly displays.
