### ISSUE TITLE
[DataGrid] Cell edit with date(or datetime) types not working properly

### ISSUE THREAD

**Issue by zzossig** [mui-org/material-ui-x#2854]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When I double click a cell that is date(dateTime) type, key inputs are scramble.

### Expected behavior 🤔

strings should be typed correctly.

### Steps to reproduce 🕹

MUI document also doesn't work correctly. See and try edit a cell your self(with keyboard).
https://mui.com/components/data-grid/editing/#cell-editing

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

#27772

**Comment by m4theushw** [comment]
What do you mean by "key inputs are scramble"? Also, which date format you use, e.g. American style (yyyy-mm-dd)?

**Comment by flaviendelangle** [comment]
@zzossig Could you please confirm that my fix is correcting your failing use case ? 
https://deploy-preview-2918--material-ui-x.netlify.app/components/data-grid/editing/#cell-editing

**Comment by zzossig** [comment]
It looks good for me only if edit cell accept just `date`.
But when I try to edit `Last Login` cell, which is accept not only `date` but also `time`,
transition to time input not going smoothly.
That means, the year part(`yyyy`) accept 6 character instead of 4

**Comment by flaviendelangle** [comment]
I agree that it feels weird
But it's the HTML input that is doing it, I don't think we should try to override it
See https://developer.mozilla.org/fr/docs/Web/HTML/Element/Input/datetime-local#valeur

**Comment by m4theushw** [comment]
@flaviendelangle Can you record again the video but also showing the key strokes? Which locale and date format did you use?

https://user-images.githubusercontent.com/42154031/139683549-563fac89-539c-4b16-bbda-a610588c9f01.mp4

**Comment by flaviendelangle** [comment]
Without my PR:

https://user-images.githubusercontent.com/3309670/139706271-456fbf72-b484-4557-b27a-19ec6413e3d2.mp4

https://user-images.githubusercontent.com/3309670/139706296-43b0393d-e12b-4d0e-88d8-882002edd1d7.mp4

**Comment by flaviendelangle** [comment]
With my PR: 

https://user-images.githubusercontent.com/3309670/139706528-6785d260-c250-4a12-bbee-6cf5b348a825.mp4

https://user-images.githubusercontent.com/3309670/139706535-a5b2ac58-a22a-4349-8b4d-6001a7cbb4f0.mp4


Local: en
Date format: mm/dd/yyyy I'd say
