### ISSUE TITLE
[DataGrid] Calendar icon is almost invisible when in dark mode

### ISSUE THREAD

**Issue by zzossig** [mui-org/material-ui-x#2855]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

![Screen Shot 2021-10-13 at 8 15 01 PM](https://user-images.githubusercontent.com/52706977/137122916-df1a6e54-19b0-4966-aa3e-53201915c6d7.png)

When a date cell is in edit mode, calendar icon is almost invisible when in dark mode.

### Expected behavior 🤔

Icon color should be changed when in dark mode.

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

#27772

**Comment by flaviendelangle** [comment]
https://stackoverflow.com/questions/62162645/change-color-of-chromes-calendar-icon-in-html-date-input

It is the browser icon and it does not follow our theme.
I have a quick fix to have it turn to white when in dark mode. It's not perfect but at least it would be reable.
I'm checking with the team managing this component if they have a better fix to apply on their side :+1:

**Comment by m4theushw** [comment]
This can be solved with https://github.com/mui-org/material-ui/issues/25016.
