### ISSUE TITLE
[docs] Full featured CRUD demo is committing changes when clicking outside the cell

### ISSUE THREAD

**Issue by Pavel-Ilmenkov** [mui-org/material-ui-x#2861]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Editing of the data grid cell on the example of DataGrid "Control with external buttons" on page:
https://mui.com/components/data-grid/editing/#control-with-external-buttons
After two iterations of the cell editing with clicking on some another row between iteration, the row edition cancelling results in cell value from the first iteration.

### Expected behavior 🤔

Cancelling of the row edition should return the cell to its initial value which was at the moment of very beginning of row editing.

### Steps to reproduce 🕹

Example is on MUI doc site: [https://mui.com/components/data-grid/editing/#control-with-external-buttons](https://mui.com/components/data-grid/editing/#control-with-external-buttons)
Steps:

1. Press "Edit" Action icon on the first row (which has the value of the "Name" cell "Trevor Parker")
2. Add " 1" to the value of the "Name" cell to be "Trevor Parker 1"
3. Click mouse on any other row
4. Return to the first row and add " 2" to the value of the "Name" cell to be "Trevor Parker 1 2"
5. Press "Cancel" Action icon on the first row

The value of Name cell becomes "Trevor Parker 1" instead of "Trevor Parker"

### Context 🔦

The user may save wrong data if did several iterations of cell editing and cancelled her work, expecting to keep data unchanged. 

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
npx: installed 2 in 2.879s

  System:
    OS: Windows Server 2012 6.3.9600
  Binaries:
    Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 94.0.4606.81
```
</details>

### Order ID 💳 (optional)

#30246

**Comment by m4theushw** [comment]
I'm opening since we need to apply the same fix to the docs.
