### ISSUE TITLE
[DataGrid] The DataGrid is not displaying results on first render when parent has no height

### ISSUE THREAD

**Issue by Senadtm87** [mui-org/material-ui-x#2867]
### Duplicates

-  Possible duplicate of https://github.com/mui-org/material-ui-x/issues/2002
### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Does not show row results, only items count.

### Expected behavior 🤔

It should render results (rows), not only items count.

### Steps to reproduce 🕹

DataGrid component shows number of results but does not display results (but shows count correctly) when I add classes={{root:{height:"80vh"}}} .
If i use autoheight it shows results.

I used this example https://codesandbox.io/s/suspicious-hoover-8508i?file=/src/Demo.tsx:0-9655
and added timeout function call to update rows.

`import * as React from "react";
import {
  /* the components you used */
  Typography
} from "@material-ui/core";
import { useState, useRef, useEffect } from "react";
import { DataGrid } from "@material-ui/data-grid";

const rows1 = [
  {
    id: "16fcd686-bae9-4232-813e-f1a9b5ae438b",
    first_name: "Nannette"
  },
  {
    id: "88e28157-456f-486a-a137-e1246bae03df",
    first_name: "Valaree"
  },
  {
    id: "9d3c813e-ddad-4395-8fcb-edf416d33d2c",
    first_name: "Stanislaus"
  },
  {
    id: "058c17b3-6291-4a3a-87fa-2f79dacebde8",
    first_name: "Melodie"
  },
  {
    id: "6a611b86-76b5-4cef-b992-657d0d8c69d7",
    first_name: "Cassi"
  },
  {
    id: "53a5b1ea-6c58-47f5-bad6-db3aff6a8bc3",
    first_name: "Terra"
  },
  {
    id: "12cb2ea0-c802-413c-86ed-3d6cc83c8ce8",
    first_name: "Dionisio"
  },
  {
    id: "b73c1b71-4479-4f2b-afee-db6349afc267",
    first_name: "Francesca"
  },
  {
    id: "c2cf6dbe-7aae-4f39-8489-ce7fa7cd0c9e",
    first_name: "Marin"
  },
  {
    id: "3ca54f91-e698-4868-b9cc-cb0995aac180",
    first_name: "Elly"
  },
  {
    id: "bd8ee8d8-f6f0-4a03-a54a-53decad17e35",
    first_name: "Arte"
  },
  {
    id: "be4d45bc-e06b-409c-b979-689edfc1e0be",
    first_name: "Cathee"
  },
  {
    id: "9ef3703d-02c7-4898-b308-04a161fd098d",
    first_name: "Clay"
  },
  {
    id: "60f01d8a-a150-4979-9518-519ddf8d0c47",
    first_name: "Coralyn"
  },
  {
    id: "68290ca7-07c5-4435-ba17-0b6bf7a11276",
    first_name: "Stacee"
  },
  {
    id: "1a738176-9d07-474d-ae5e-396ab5decdf7",
    first_name: "Lars"
  },
  {
    id: "0852b586-ed9e-476e-914e-b1693dc65583",
    first_name: "Nert"
  },
  {
    id: "fb66abdf-1b18-4ec2-911d-e03263692e27",
    first_name: "Matthus"
  },
  {
    id: "ed059673-18c9-4961-b271-b3384fd49d0d",
    first_name: "Janet"
  },
  {
    id: "ff4b216b-0d25-4538-9bf4-762de80303f4",
    first_name: "Ennis"
  },
  {
    id: "6b7521e3-789f-459a-ac08-9ce4404fda13",
    first_name: "Leonhard"
  },
  {
    id: "ebbebc3b-78bd-480e-ba37-fed6324616de",
    first_name: "Zacharia"
  },
  {
    id: "75a32b00-562e-4f9d-9d48-e68db532e7be",
    first_name: "Vern"
  },
  {
    id: "c572a5ab-ba43-406d-b6d5-cf3bfc111a1f",
    first_name: "Lynn"
  },
  {
    id: "db307311-4655-4e99-94b3-4212641a9ecd",
    first_name: "Lodovico"
  },
  {
    id: "fd34599f-4662-4a80-80ab-48786ef67dea",
    first_name: "Whittaker"
  },
  {
    id: "bbc77a20-a6d9-4b70-8c46-88bcc76f9ed4",
    first_name: "Carlotta"
  },
  {
    id: "32cba8b2-f84d-43c1-9917-fda4f99d418e",
    first_name: "Quinlan"
  },
  {
    id: "d7bdac51-223e-49b1-97f6-b5312ed26fe9",
    first_name: "Buck"
  },
  {
    id: "1ddae610-8e1c-4f58-8c1e-5206975a2ed2",
    first_name: "Ilka"
  },
  {
    id: "42b7f1a9-2f8d-4f05-88f9-21e0a0a65eb8",
    first_name: "Danika"
  },
  {
    id: "bce39251-7391-4f0f-89f4-37a285d41c79",
    first_name: "Janette"
  },
  {
    id: "859d5095-6dd9-4c60-ba10-7dcededb07a3",
    first_name: "Virgilio"
  },
  {
    id: "e74eded3-3e42-4ff0-a114-3f48c6626e53",
    first_name: "Christian"
  },
  {
    id: "ba3604ea-f7de-498a-8014-0f6cf3a9cd41",
    first_name: "Elwyn"
  },
  {
    id: "6f83d827-85d0-4f93-965e-4cadde12a81b",
    first_name: "Dame"
  },
  {
    id: "99d60874-6667-4486-9207-43c204364a34",
    first_name: "Addia"
  },
  {
    id: "4b1892be-1f85-4ed0-af3a-d1b62d265735",
    first_name: "Danita"
  },
  {
    id: "6de8e0ce-d26f-4598-ab95-60e8bacf5e61",
    first_name: "Kayley"
  },
  {
    id: "918db727-f270-4024-8249-ce2000515f80",
    first_name: "Dorry"
  },
  {
    id: "abbd4212-36f9-4225-9f10-5d5de03bfcf3",
    first_name: "Johannah"
  },
  {
    id: "06c9d984-9b48-49b6-9b21-80b4245221ee",
    first_name: "Dorry"
  },
  {
    id: "13853ef9-5f2e-4ead-a927-081826515c8c",
    first_name: "Pauli"
  },
  {
    id: "e4b6a89f-7514-4248-8e24-61fa4b7f36d1",
    first_name: "Staffard"
  },
  {
    id: "d8e66349-7362-490e-8543-347a569a27ec",
    first_name: "Dulsea"
  },
  {
    id: "14065734-babf-4045-8c7e-592cd8be397d",
    first_name: "Jacinthe"
  },
  {
    id: "943e7c4b-f426-4b38-9889-b3b80fa24d18",
    first_name: "Merl"
  },
  {
    id: "4c65d2d9-c7b6-4a88-b6fa-9a88d7389b50",
    first_name: "Emlyn"
  },
  {
    id: "b58697e2-4c07-4bd2-a545-1363ac5b1104",
    first_name: "Christie"
  },
  {
    id: "6174953a-e21e-440f-8bd9-29bfe86cef09",
    first_name: "Cindie"
  },
  {
    id: "542089ac-eca6-44bd-91b2-2bad5b9f8d5e",
    first_name: "Cookie"
  },
  {
    id: "39f55e67-acd7-46c6-8509-a7bdafd76ecb",
    first_name: "Aksel"
  },
  {
    id: "74d7b4c2-491e-4977-86f3-961ee9c8cb84",
    first_name: "Birgitta"
  },
  {
    id: "b8795a59-1693-4c35-8b46-0275245c2de9",
    first_name: "Clarisse"
  },
  {
    id: "e590d289-74c3-494e-9dd4-47021002dc1c",
    first_name: "Gene"
  },
  {
    id: "405e0db1-cfd6-48b7-a760-fcd62fdeee84",
    first_name: "Sly"
  },
  {
    id: "8458c6d8-fbed-4ad2-8d4c-2a4ce1c7d27c",
    first_name: "Lilas"
  },
  {
    id: "f4f9040e-1631-450d-b732-358e075c88d9",
    first_name: "Parsifal"
  },
  {
    id: "c0c60fb8-4a1d-4b70-9da6-fbfe8d58acc7",
    first_name: "Bert"
  },
  {
    id: "a49b6c63-05f5-42da-9fec-a5b79953f569",
    first_name: "Corbie"
  },
  {
    id: "ab9f86a4-87ab-4a39-88b8-76e34c012b42",
    first_name: "Maria"
  },
  {
    id: "43d8e3ef-b2ac-4b56-a0fc-20c6c8852ef0",
    first_name: "Paddie"
  },
  {
    id: "262a1200-7a85-4a5a-bc35-9e3297335ece",
    first_name: "Rurik"
  },
  {
    id: "540580a1-ae7e-408b-97f4-596dc64ec793",
    first_name: "Lyell"
  },
  {
    id: "c480cf21-09cd-41f7-aa35-8074a9146ead",
    first_name: "Gena"
  },
  {
    id: "395fe238-2d2f-4334-8ba2-4a0f364283ad",
    first_name: "Wilow"
  },
  {
    id: "a22138b8-019e-41b1-bab5-69b8c819508e",
    first_name: "Brenna"
  },
  {
    id: "8c11115d-21ac-4fd4-911d-8907e92ab594",
    first_name: "Jdavie"
  },
  {
    id: "412d1273-7a26-4b3a-a2a9-a6f852b0bd6c",
    first_name: "Carissa"
  },
  {
    id: "2da7014b-de13-4005-9b8d-bb553052f2cb",
    first_name: "Anselma"
  },
  {
    id: "b215001b-08c7-411f-ab78-63aa00513499",
    first_name: "Willi"
  },
  {
    id: "091b2fe6-8711-465b-b5b7-ab0761847c7d",
    first_name: "Wilhelm"
  },
  {
    id: "203a2362-3d72-4b3c-bcf6-fb14c3c032fd",
    first_name: "Gayla"
  },
  {
    id: "80dbb042-d686-4c6e-a870-c231324ea079",
    first_name: "Culver"
  },
  {
    id: "a19c1881-c6a3-4281-ae80-942e1b8f9a4b",
    first_name: "Emmalyn"
  },
  {
    id: "f4443ed1-c02d-4221-9d3b-03db6d46cc95",
    first_name: "Gaile"
  },
  {
    id: "96e42ddd-7745-451e-be97-731577fbc9eb",
    first_name: "Lurlene"
  },
  {
    id: "f53f49bd-6e4e-4f32-a0f5-6f79a81add91",
    first_name: "Zak"
  },
  {
    id: "cee2a351-08ce-4ef6-93e9-fb324ab4121a",
    first_name: "Gert"
  },
  {
    id: "0fea58f5-9a2c-46cf-8d05-83741a6cac70",
    first_name: "Chadd"
  },
  {
    id: "34e23955-d7cc-43af-8557-7a1bbccd055f",
    first_name: "Mercedes"
  },
  {
    id: "81310d37-423d-45d2-8995-96cf029b3aa7",
    first_name: "Drew"
  },
  {
    id: "110593c0-c456-4a0f-bb54-2525870a3add",
    first_name: "Kristos"
  },
  {
    id: "acee8154-0e56-440a-83d3-f79f99c04af6",
    first_name: "Montgomery"
  },
  {
    id: "a4f84e32-e634-46b5-8ce0-9c3912a65968",
    first_name: "Roseanna"
  },
  {
    id: "d1aa77cd-5952-4afa-9542-bacb267cb591",
    first_name: "Kenton"
  },
  {
    id: "1fbea0e7-8500-4c1c-81d0-dd38233f4db1",
    first_name: "Salmon"
  },
  {
    id: "f5eed919-4ffb-439c-9252-e4a6d9114191",
    first_name: "Tiena"
  },
  {
    id: "f8173183-02be-4f99-9303-c95d7f9d6934",
    first_name: "Iago"
  },
  {
    id: "84659bf3-701b-4e60-acb5-632019cd4e48",
    first_name: "Debbi"
  },
  {
    id: "d8edc69b-63e5-4606-92ab-5bba3505b300",
    first_name: "Ameline"
  },
  {
    id: "9f827b64-68af-4ac2-9052-afd1d74ce77d",
    first_name: "Bernie"
  },
  {
    id: "8ad88fcf-522e-4d85-a20c-89c6bb64c94b",
    first_name: "Corine"
  },
  {
    id: "6f2b9647-3f7e-45ea-84c1-ceb59f6a641a",
    first_name: "Krissie"
  },
  {
    id: "5aba7910-cf69-425d-ace3-18544ac647ea",
    first_name: "Terza"
  },
  {
    id: "281117a8-73d8-42e2-99d7-dbd378e326dc",
    first_name: "Bertha"
  },
  {
    id: "0acc817f-62b0-471d-a58a-ccd97424c502",
    first_name: "Aaron"
  },
  {
    id: "37438cdf-f20f-4491-ba87-0efff3acb7e2",
    first_name: "Denna"
  },
  {
    id: "e716be9b-3317-4257-9ffa-e6f73c8756d8",
    first_name: "Zaria"
  },
  {
    id: "8816048b-2785-4c6b-a21e-8418596da82f",
    first_name: "Diarmid"
  }
];

const rows2 = [
  {
    id: "9295d9e4-f5ec-4964-9737-6f38f5011816",
    first_name: "Jilli"
  }
];

/**
 * how you used the components
 */
export default function Demo() {
  useTimeout(() => {
    setCurrentRows(rows2);
  }, 3000);
  const columns = [
    { field: "id", headerName: "ID", width: 300 },
    { field: "first_name", headerName: "Name", width: 300 }
  ];
  const [currentRows, setCurrentRows] = useState([]);

  const changeRows = () => {
    setCurrentRows(rows2);
  };
  return (
    <div>
      <DataGrid
        classes={{ root: { height: "80vh" } }}
        pageSize={10}
        columns={columns}
        rows={currentRows}
      />
      <button onClick={changeRows}>Change Rows</button>
    </div>
  );
}

function useTimeout(callback: () => void, delay: number | null) {
  const savedCallback = useRef(callback);

  // Remember the latest callback if it changes.
  useEffect(() => {
    savedCallback.current = callback;
  }, [callback]);

  // Set up the timeout.
  useEffect(() => {
    // Don't schedule if no delay is specified.
    if (delay === null) {
      return;
    }

    const id = setTimeout(() => savedCallback.current(), delay);

    return () => clearTimeout(id);
  }, [delay]);
}
`

### Your environment 🌎

` "@material-ui/core": "^4.12.3",
    "@material-ui/data-grid": "^4.0.0-alpha.37",
    "@material-ui/icons": "^4.11.2",
    "@material-ui/lab": "^4.0.0-alpha.60",
    "@material-ui/x-grid-data-generator": "^4.0.0-alpha.37",`

**Comment by flaviendelangle** [comment]
I'm closing this one since we don't have any feedback
