### ISSUE TITLE
MUI v5 select menu items merged horizontally

### ISSUE THREAD

**Issue by jamintz** [mui-org/material-ui-x#2879]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Going through the v4 -> v5 upgrade guide, and my dropdown menus all now look like:
<img width="136" alt="Screen Shot 2021-10-15 at 11 59 12 AM" src="https://user-images.githubusercontent.com/3538254/137519976-20fb0233-059d-4a4b-a56f-ccaa17999cf4.png">

### Expected behavior 🤔

Vertical dropdown as in v4:
<img width="119" alt="Screen Shot 2021-10-15 at 12 16 45 PM" src="https://user-images.githubusercontent.com/3538254/137520046-1f94d06c-b70d-431b-a5b9-8b1b5ec6c467.png">

### Steps to reproduce 🕹

Code sample:

<Select
displayEmpty
value={value || ''}
onChange={doChange}
>
Choose
{[1,2,3,4,5].map((val,ind) =>
{val}
)}

Here's a CodeSandbox that captures the issue: https://codesandbox.io/s/positionedmenu-material-demo-forked-pul8o

### Context 🔦

Breaks menu dropdowns

### Your environment 🌎

Packages:
"@mui/icons-material": "^5.0.4",
"@mui/lab": "^5.0.0-alpha.51",
"@mui/material": "^5.0.4",
"@mui/styles": "^5.0.1",

### Order ID 💳 (optional)

21172

**Comment by jamintz** [comment]
I also posted this in https://github.com/mui-org/material-ui/ so apologies if it's duplicated, thought it might get a quicker response here

**Comment by JeremyRubin** [comment]
@m4theushw what if it's not an option to remove `@material-ui/core` since we have another dependency requiring it (e.g. react jsonschema forms)?

**Comment by m4theushw** [comment]
@JeremyRubin You can try configuring `@mui/material` to not conflict with `@material-ui/core`. See https://mui.com/components/data-grid/migration-v4/#using-mui-x-v5-with-mui-core-v4.
