### ISSUE TITLE
[DataGrid] apiGridRef subscribeEvent is undefined

### ISSUE THREAD

**Issue by wesyao** [mui-org/material-ui-x#2904]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version (in v4)

### Current behavior 😯

We're currently on `@material-ui/x-grid@4.0.0-alpha.37` (we're currently working on the v5 migration) and using the paid xgrid component. `@material-ui/core@4.12.3` as well. I'm trying to subscribe to some table events for some additional logic. I've followed the [tutorial](https://codesandbox.io/s/material-demo-forked-7qrl7?file=/demo.tsx), even forked my own to test and read the [docs](https://v4.mui.com/components/data-grid/events/) many times. It appears to be quite trivial, however I am getting an exception that is being throw with this set code:
```
  const apiRef = useGridApiRef();
  useEffect(() => {
    apiRef.current.subscribeEvent(GridEvents.columnsChange, (params) => {
      console.log(params);
    });
  }, [apiRef]);
  
```
an error occurs and crashes react rendering:
```
  TypeError: apiRef.current.subscribeEvent is not a function

```
`subscribeEvent` is undefined and I cannot subscribe to a grid event. This causes an exception to be thrown. I haven't been able to find anyone talking about it on the issues as well as stackoverflow. Looking for some help here!

Thanks in advance!

### Expected behavior 🤔

I expect to be able to print out the params.

### Context 🔦

I am trying to use use `apiRef.current.subscribeEvent` to subscribe to some grid event changes.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
    System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 3.92 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.11.1 - ~/.nvm/versions/node/v16.11.1/bin/node
    npm: 8.0.0 - ~/.nvm/versions/node/v16.11.1/bin/npm
    Watchman: 2021.09.13.00 - /usr/local/bin/watchman
```
</details>

### Order ID 💳 (optional)

idk right now

**Comment by flaviendelangle** [comment]
Hi, @wesyao  thanks for raising this. Can you please provide the codesabdox reproduction? You can use this template https://codesandbox.io/s/material-ui-issue-next-o7xkt as a starting point.

A reason could be if you do not render the `DataGrid` during the 1st render.

**Comment by TimOwe** [comment]
Running into this on my end too, here's a codesandbox:
https://codesandbox.io/s/zen-panka-ex5d6?file=/src/Demo.tsx

**Comment by flaviendelangle** [comment]
@TimOwe the `apiRef` is currently a pro-only feature and therefore only available for `DataGridPro`.

If you have a pro-license, here is the fixed code : https://codesandbox.io/s/practical-benz-es6zs?file=/src/Demo.tsx
I passed the `apiRef` prop to the Grid and changed the installed package.

If you don't have a pro-license, could you please describe what is that you are trying to achieve ?

**Comment by TimOwe** [comment]
> @TimOwe the `apiRef` is currently a pro-only feature and therefore only available for `DataGridPro`.

Ah, gotcha. The structure of the docs I'm looking at confused me a bit,
Thanks

**Comment by flaviendelangle** [comment]
@TimOwe can you please link me the doc page you are talking about ? I can probably improve the formulation :+1:

**Comment by wesyao** [comment]
> Hi, @wesyao thanks for raising this. Can you please provide the codesabdox reproduction? You can use this template https://codesandbox.io/s/material-ui-issue-next-o7xkt as a starting point.
> 
> A reason could be if you do not render the `DataGrid` during the 1st render.

Hey @flaviendelangle thanks for getting back. I might have been a bit confusing, but the "tutorial" link I posted above was a fork of the demo sandbox and I put in my own package versions to test if it worked.

**Comment by flaviendelangle** [comment]
I'm closing this issue from lack of feedback

**Comment by lowly2005** [comment]
@flaviendelangle I'm getting the same error and I have the premium datagrid license. Using this [documentation](https://mui.com/x/react-data-grid/row-grouping/#hide-the-grouped-columns)

**Comment by flaviendelangle** [comment]
Hi,

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) might be a good starting point.

**Comment by lowly2005** [comment]
@flaviendelangle  This is how I'm using the row grouping [here](https://codesandbox.io/s/data-grid-community-forked-orvu11?file=/src/App.tsx) 
In the code sandbox I don't have any issue but I get this error in my project : 
```
Uncaught TypeError: props.apiRef.current.subscribeEvent is not a function
    at useKeepGroupedColumnsHidden.js:33:26
```

```
    "@mui/x-data-grid-premium": "^5.17.2",
    "@mui/x-license-pro": "^5.16.0",
```

**Comment by flaviendelangle** [comment]
Are you passing the `apiRef` both to `useKeepGroupedColumnsHidden` and `DataGridPremium` ?
Without a reproduction of the bug it will be hard for me to help.

**Comment by lowly2005** [comment]
@flaviendelangle yes I am

**Comment by flaviendelangle** [comment]
Is your `DataGridPremium` component renderer conditionally ? 
In other words, could the `useEffect` in `useKeepGroupedColumnsHidden` run before the 1st rendering of the grid ?

**Comment by lowly2005** [comment]
@flaviendelangle yes it seems that it's running before the 1st rendering of the grid.

**Comment by lowly2005** [comment]
Could you share an example of a wrapper with only useKeepGroupedColumnsHidden and useGridApiRef?

**Comment by flaviendelangle** [comment]
[Here you are](https://codesandbox.io/s/elastic-lewin-47x4gp?file=/demo.tsx)

**Comment by pythonruss** [comment]
Could the team consider revisiting this? was forced to completely re-write my component just to hide the columns (because of the hook aspects mentioned above).
Not a good upgrade experience for premium -- grouping was why we purchased the library

**Comment by yasin-shaikh** [comment]
I have fixed this issue by passing the creating new component for DataGridPremium and pass in my parent component then it fixed 
![Screenshot 2024-08-21 at 2 41 32 PM](https://github.com/user-attachments/assets/58b78262-e3a5-4c4b-aa3a-f32a3d1034cb)
  and the initialize state pass inside DataGridPremium 
import { Alert, Box, Card, CardContent, Grid, Typography, } from '@mui/material';
import { grey } from '@mui/material/colors'
import { DataGridPremium, GridToolbarColumnsButton, GridToolbarContainer, GridToolbarDensitySelector, gridClasses, GridToolbarFilterButton, useGridApiRef, useKeepGroupedColumnsHidden } from '@mui/x-data-grid-premium';
import Markdown from 'markdown-to-jsx'
import React from 'react'
interface CommonProps {
    data: any, props: any, builder: any, columnGroupingModel: any, rowGroupingModel: any, pinnedRows: any, setRowGroupingModel: any
}
const DataGridComp: React.FC<CommonProps> = ({ data, props, builder, columnGroupingModel, rowGroupingModel, pinnedRows, setRowGroupingModel }) => {
    const apiRef = useGridApiRef();

    const initialState = useKeepGroupedColumnsHidden({
        apiRef,
        initialState: {
            rowGrouping: {
                model: ['question'],
            },
        },
    });
    const CustomToolbar = () => {
        return (
            <GridToolbarContainer>
                <GridToolbarColumnsButton slotProps={{ button: { sx: { color: '#2B7BA7' } } }} />
                <GridToolbarFilterButton slotProps={{ button: { sx: { color: '#2B7BA7' } } }} />
                <GridToolbarDensitySelector
                    slotProps={{ button: { sx: { color: '#2B7BA7' } } }}
                />
                <Box sx={{ flexGrow: 1 }} />

            </GridToolbarContainer>
        );
    }

    return (
        <Grid>
            <Card className="card-decoration">
                <CardContent>
                    <Grid container spacing={2} sx={{ mb: 2 }}>
                        <Grid item xs={12}>
                            <Typography sx={{ fontSize: 16 }}>{data?.name}</Typography>
                            {(data?.dataset || props.dataset) == 'simulated' && (
                                <Alert severity="warning" sx={{ mt: 1 }}>
                                    Simulated data
                                </Alert>
                            )}
                        </Grid>
                    </Grid>
                    <Box sx={{ height: '100% !important' }}>
                        <DataGridPremium
                            apiRef={apiRef}
                            initialState={initialState}
                            rows={builder.rows}
                            columns={builder.getColumns()}
                            columnGroupingModel={columnGroupingModel}
                            checkboxSelection={false}
                            rowHeight={35}
                            columnHeaderHeight={35}
                            hideFooter
                            pinnedRows={pinnedRows}
                            slots={{
                                toolbar: CustomToolbar,
                            }}
                            resizeThrottleMs={0}
                            sx={{
                                [`& .${gridClasses.columnHeader}`]: {
                                    bgcolor: grey[200], borderInlineEnd: `1px solid #ddd`, borderBlockEnd: `1px solid #ddd`
                                },
                                [`& .${gridClasses.columnHeaderTitle}`]: {
                                    color: 'black', fontSize: 14, fontWeight: 900, textTransform: 'capitalize', bgcolor: grey[200]
                                },
                                [`& .${gridClasses['row--borderBottom']}`]: { bgcolor: ` ${grey[200]} !important`, },
                                [`& .${gridClasses.cell}`]: {
                                    borderInlineEnd: `1px solid #ddd`
                                },
                                [`& .${gridClasses.toolbarContainer}`]: {
                                    borderBlockEnd: `1px solid #ddd`,
                                },
                                [`& .${gridClasses.cellEmpty}`]: {
                                    bgcolor: 'white ', border: `none  !important`
                                },
                                [`& .${gridClasses.virtualScroller}`]: {
                                    overflowY: 'auto !important',
                                    maxHeight: 'calc(100vh - 10px) !important',

                                },
                                [`& {.super-app-theme--auto-generated-row-question/Brand Rating}`]: { bgcolor: `${grey[200]} !important` }


                            }}
                            defaultGroupingExpansionDepth={-1}
                            rowGroupingModel={rowGroupingModel}
                            onRowGroupingModelChange={(model) => { setRowGroupingModel(model) }}
                        />
                    </Box>
                    {data?.insights && (
                        <Markdown className="markdown">{data?.insights}</Markdown>
                    )}
                </CardContent>
            </Card>
        </Grid>)
}

export default DataGridComp

**Comment by igortas** [comment]
I need help wth this too, I have wrapper on top of mui x grid, it have condition statement that returns null, and above is the ```useKeepGroupedColumnsHidden``` hook. It's so bad that conditional breaks the shared wrapper for mui x grid.

**Comment by flaviendelangle** [comment]
@michelengelen I'm adding you to the loop :pray:

**Comment by michelengelen** [comment]
This seems very clear to me:
<img width="839" alt="Screenshot 2024-09-30 at 15 43 27" src="https://github.com/user-attachments/assets/513bb44e-7e83-4e9a-9d46-e541c484a2ef">
Maybe discoverability is not high enough for this. We use the `apiRef` very frequently in the examples and have near 0 explanations regarding this specific behavior other than [here](https://mui.com/x/react-data-grid/api-object/#outside-the-data-grid).

@alelthomas @samuelsycamore tagging you as well as this is clearly docs related.

**Comment by flaviendelangle** [comment]
I would be in favor of going in this direction indeed, not sure what the exact wording should be
