### ISSUE TITLE
How can i use the classes support on MUI 5 since makeStyles will be eventually deprecated?

### ISSUE THREAD

**Issue by erickbelfy** [mui-org/material-ui-x#2913]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I would like to understand how can we have the support for classes object that every component has and stop using makeStyles

### Expected behavior 🤔

How can i properly use Styled or some other tool to keep using the classes overrides that MUI provide

### Steps to reproduce 🕹

Steps:

1. remove makeStyles from codebase
2. use a different tool to compile the classes object

### Context 🔦

Since MUI5 is going to deprecate makeStyles from the codebase how can we compile the classes object that MUI has exposed to devs in order to override the style of its components?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
Before:
const useStyles = makeStyles((theme) =>
  createStyles({
    textIcon: {
      textDecoration: 'none',
      '&:hover, &:focus, &.Mui-focusVisible': {
        textDecoration: 'underline',
      },
    },
    text: {
      textDecoration: 'underline',
      '&:hover, &:focus, &.Mui-focusVisible': {
        textDecoration: 'none',
      },
    },
    startIcon: {
      marginLeft: -theme.spacing(0.5),
      marginRight: theme.spacing(1),
    },
    startIconStandalone: {
      marginLeft: 0,
      marginRight: 0,
    },
    endIcon: {
      marginLeft: theme.spacing(1),
      marginRight: -theme.spacing(0.5),
    },
    endIconStandalone: {
      marginLeft: 0,
      marginRight: 0,
    },
  })
);
```

and with MUI5 we can do something like?

```
const useStyles = Styled((Button)(theme) =>
  ({
    textIcon: {
      textDecoration: 'none',
      '&:hover, &:focus, &.Mui-focusVisible': {
        textDecoration: 'underline',
      },
    },
    text: {
      textDecoration: 'underline',
      '&:hover, &:focus, &.Mui-focusVisible': {
        textDecoration: 'none',
      },
    },
    startIcon: {
      marginLeft: -theme.spacing(0.5),
      marginRight: theme.spacing(1),
    },
    startIconStandalone: {
      marginLeft: 0,
      marginRight: 0,
    },
    endIcon: {
      marginLeft: theme.spacing(1),
      marginRight: -theme.spacing(0.5),
    },
    endIconStandalone: {
      marginLeft: 0,
      marginRight: 0,
    },
  })
);
```
</details>

**Comment by DanailH** [comment]
Hi, @erickbelfy thanks for raising this. We are currently working on unifying the way the grid handles styling to be the same as in the core. You can check this PR to track the progress https://github.com/mui-org/material-ui-x/pull/2784

**Comment by m4theushw** [comment]
Here's an example using `styled`: https://codesandbox.io/s/stylingcellsgrid-material-demo-forked-oeu92?file=/demo.tsx

```tsx
import { styled } from "@mui/material/styles";

const StyledDataGrid = styled(DataGrid)({
  "& .super-app-theme--cell": {
    backgroundColor: "rgba(224, 183, 60, 0.55)",
    color: "#1a3e72",
    fontWeight: "600"
  },
}

<StyledDataGrid rows={rows} columns={columns} />;
```
