### ISSUE TITLE
[DataGrid Pro] Keyboard navigation not working on actions column

### ISSUE THREAD

**Issue by Isarstyle** [mui-org/material-ui-x#2914]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

when using keyboard navigation with arrow keys, 
on entering the actions column the keyboard navigation is broken, 
i can only move down to the next row to the action column with the down arrow key.

left/right switches between the buttons i have in the column, but i cannot leave the column anymore

Here is the example of my actions column.

` {
        headerName: 'Aktionen',
        field: 'actions',
        type: 'actions',
        disableExport: true,
        getActions: (rowData) => [
          <GridActionsCellItem
            icon={<DeleteIcon color="error" />}
            label="Delete"
            onClick={() => setUserDeleteDialogOpen(rowData.row)}
          />,
          <GridActionsCellItem
            icon={<EditIcon color="secondary" />}
            label="Edit"
            onClick={() => history.push(`/usercreator/${rowData.row._id}`)}
          />,
        ],
      },`

ADDITIONAL INFO:
when i click into the cell and use the arrow navigation it works as intended, but as soon as the focus get set on one of the button items it does not work anymore.

### Expected behavior 🤔

 i would expect that left arrow in the actions column again would bring me back to the previous column.

### Steps to reproduce 🕹

using arrow keys to navigate through the columns.

### Your environment 🌎

google chrome browser v 94.0.4606.81 (Offizieller Build) (arm64)

**Comment by m4theushw** [comment]
This was also raised in https://github.com/mui-org/material-ui-x/pull/2862#issuecomment-944094261.

I opened #2880 to track a similar bug involving the Select inside the cell. The solution for #2880 will also fix the actions column.
