### ISSUE TITLE
Test failures in v5.0.1

### ISSUE THREAD

**Issue by ddolcimascolo** [mui-org/material-ui-x#2945]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

We have 70 tests failing when upgrading from v5.0.0-beta.4 to v5.0.0-beta.5.

This is a loooooot higher than the usual failures that we expect (because you're still in beta). Most (probably all, but I need to dig deeper) failures are related to columns being invisible while they were in beta4, columns being absent from the DOM while there were present in beta4, or other similar assertions....

Can you advise on what might have changed in beta5 causing so many failures? I'm OK to fix these on my side, but I'd apreciate guidance on where to start :)

Thx a lot !

David 

### Expected behavior 🤔

No failures?

### Steps to reproduce 🕹

I've no reproduction, but I can try to setup one if that's required. Basically we've lots of tests doing stuff like `expect(column).toBeVisible()` or `expect(column).toBeInTheDocument()` that are now failing.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: Linux 5.11 Linux Mint 20.2 (Uma)
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: Not Found
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Browsers:
    Chrome: 95.0.4638.54
    Firefox: 93.0

```
</details>

**Comment by ddolcimascolo** [comment]
Hi @flaviendelangle @m4theushw

v5.0.1 brings back unexpected failures, though this time you released v5 so breaking things is clearly not expected in minor releases, let alone patch ones.

As usual, I'm in to refactor my tests but I'd like some guidance on what might be causing the regressions, as @m4theushw did last time. The failures apparently are related to some rows not being rendered, while they were in 5.0.0. Anything related to size or whatever again?

Thx

David

**Comment by m4theushw** [comment]
It could be related to https://github.com/mui-org/material-ui-x/pull/3007.

Which tests are you doing that are failing with v5.0.1?

When testing with jsdom, these kind of errors are expected since it doesn't have the capability to infer the size of an element. We only test layout stuff with a real browser to avoid having to mock the dimensions.

**Comment by ddolcimascolo** [comment]
Yeah, and I know I should change the failing tests. I'll dig more tomorrow morning and get back to you. I'll also check #3007, thanks for the hint

**Comment by flaviendelangle** [comment]
Yeah much likely #3007
I would be very interested to see actual failing tests to have more context about which types of tests users create and have struggle maintaining when we rework our internals.

**Comment by ddolcimascolo** [comment]
Hi @flaviendelangle @m4theushw 

Actually this time tests are right, we do have one grid that does not render anymore. It's a simple one with static rows and columns. We do have other grids that render fine.

One thing I noticed is that now we have this warning in the console

```
react_devtools_backend.js:2540 MUI: useResizeContainer - The parent of the grid has an empty width.
You need to make sure the container has an intrinsic width.
The grid displays with a width of 0px.
```

Side note: we do have a license for your product, we're a french company

Thx,
David

**Comment by flaviendelangle** [comment]
This warning is fired when to grid does not have a height.
As explained on [this doc page](https://mui.com/components/data-grid/layout/#predefined-dimensions), by default the grid takes the size of its parent
But in JSDOM this does not work. So we advise you to use the `autoHeight` for testing.

I see you found a workaround https://github.com/mui-org/material-ui-x/issues/2945#issuecomment-950160335 and I suppose that this workaround does not work anymore since you have the error again.
The reason may be because I don't call `clientHeight` / `clientWidth` anymore but rely purely on our `GridAutoSizer`.

If you are passing props to your Grid directly in your test, you could bypass the issue by publishing a `resize` event with the dimensions.
Something like:

```tsx
let apiRef: GridApiRef

describe('', () => {
  it('', () => {
    const Wrapper = (props) => {
      apiRef = useGridApiRef();
      return <DataGridPro {...props} apiRef={apiRef} />
    }

    render(<Wrapper rows={rows} />)
    apiRef.current.publishEvents('resize', { height: 300, width: 300 });
  });
});
```

But depending on how your tests are structured, it can be tricky to access the `apiRef`
There is probably also ways to trick our `GridAutoSizer` to fire the `onResize` callback but I did not try it.

If you can give me a repo with a small reproduction case I can spend some time finding a solution (and documenting it properly for everyone).

**Comment by ddolcimascolo** [comment]
Thx for your reply, but I was unclear sorry. It's the actual production app that suffers the regression... We do have one table that don't render in the app anymore when upgrading the lib

**Comment by ddolcimascolo** [comment]
I'm currently trying to repro in a repo, or a codesandbox. I'll keep you posted

**Comment by ddolcimascolo** [comment]
So the `width` warning is something else, I know how to fix that. For a reason the component wrapping the grid renders a first time without a width, I detected that with a resize observer. We do use React Suspense a lots to load translations, etc. so it might be related.

Using a simple hack like `widthIsNotZero && <DataGrid ... />` makes the warning disappear and removes a "flickering" due to the rerender of the grid when parent resizes. So it's a "bug" on our side and can be fixed.

However, in 5.0.1 I still have the table that does not render. I'll try to reproduce this issue and get back to you

**Comment by ddolcimascolo** [comment]
I moved on a bit, but still can't reproduce outside my app. My findings are
* The non rendered table uses `autoHeight` and is under a React `<Suspense />` but before a component that actually suspend 
* The grid parent is a MUI `<Grid item xs />`
* The table uses a static list of columns and a static list of rows. `autoHeight` is only used to make the parent grow and adapt to the number of rows, when we change the static list of rows 
* The warning about width or height happens when the grid renders while the UI suspends because of another component in the tree. I can confirm this is unrelated to the actual issue of the table not rendering. Removing `<Suspense />` or waiting before rendering the grid removes the warning but the table still does not render
* Setting a height to the parent of the grid makes it render fine

I have 6 remaining failing tests that are all failures because in 5.0.1 the data grid does not render the same number of rows. All data Grids under test use `autoHeight`. I can probably fix them but I still don't understand why the number of rendered rows is not the same as in 5.0.0...

Cheers,
David

**Comment by ddolcimascolo** [comment]
OK @flaviendelangle @m4theushw I finally managed to reproduce, and it was dumber than expected. As often you may say!

Closing this one in favor of https://github.com/mui-org/material-ui-x/issues/3233 that I just created

**Comment by ddolcimascolo** [comment]
For the record, the failing tests were due to missing mocks of `offsetHeight` / `offsetWidth` that **were not** needed before 5.0.1. If someone comes by, here's what we do

```
  Object.defineProperties(HTMLElement.prototype, {
    offsetWidth: { get: () => /* Your width here */ },
    offsetHeight: { get: () => /* Your height here */ }
  });
```

**Comment by m4theushw** [comment]
Could you share all of the properties you had to mock to be able to unit test with jsdom? We want to add a page to help to set up a testing environment in https://github.com/mui-org/material-ui-x/issues/1151.
