### ISSUE TITLE
[DataGrid] Implement Column groups

### ISSUE THREAD

**Issue by mchelen** [mui-org/material-ui-x#295]
The fixed header option in https://material-ui.com/components/tables/#fixed-header is not compatible with multiple header rows from this example https://github.com/mui-org/material-ui/blob/master/docs/src/pages/components/tables/SpanningTable.js

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
The second header row is sticky, but not the first.

## Expected Behavior 🤔
Both first and second header row should be sticky.

## Steps to Reproduce 🕹

Steps:

1.  Create a `<Table>` with `stickyHeader` prop (reference: https://material-ui.com/components/tables/#fixed-header )
2.  Create multiple `<TableRow>` inside `<TableHead>` (reference: https://github.com/mui-org/material-ui/blob/master/docs/src/pages/components/tables/SpanningTable.js )
3.  Scroll down, and second `<TableRow>` content will replace first
            
https://codesandbox.io/s/material-demo-vo8qp

## Context 🔦

We want to display a table with multiple header rows, and have all those rows be fixed "sticky" when scrolling.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Material-UI | v4.5.1  |
| React       |  16.11.0       |
| Browser     |   Chrome      |

**Comment by ndtreviv** [comment]
Why is this issue title prefixed with `[DataGrid]` when it's not about DataGrid at all?
