### ISSUE TITLE
[DataGrid] Implement Column sticky

### ISSUE THREAD

**Issue by jelteliekens** [mui-org/material-ui-x#297]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Just like having a prop `stickyHeader` but for a specific column. Add a property to TableCell in the header of the column you would like to be sticky or add a propery to Table where you can specify which column(s) you would like to be sticky.

```
<Table>
  <TableHead>
    <TableRow>
      <TableCell stickyColumn>Column0</TableCell>
      <TableCell>Column1</TableCell>
    </TableRow>
  </TableHead>
  <TableBody>
    {/* ... */}
  </TableBody>
</Table>
```
or
```
<Table stickyColumn={0}>
  <TableHead>
    <TableRow>
      <TableCell>Column2</TableCell>
      <TableCell>Column1</TableCell>
    </TableRow>
  </TableHead>
  <TableBody>
    {/* ... */}
  </TableBody>
</Table>
```

## Examples 🌈

<img width="784" alt="Screenshot 2020-01-10 13 32 59" src="https://user-images.githubusercontent.com/3418474/72153317-e1455e80-33ad-11ea-8edc-a50c88303e89.png">

## Motivation 🔦

The table should take the full width of its container and should start overflowing horizontally because the sum of the column widths exceed the width of the container. When it start overflowing a column that is configured to be sticky (or the one where `scope=row` is set) (ex. name column) should be kept visible when scrolling horizonally. By doing this it is easier to see where the data belongs to.

**Comment by AlfredoMora06** [comment]
> @oliviertassinari if you want some help on this I recently implemented something similar and could help out. Let me know!

Would you still be able to help me with this? Or anyone? Appreciate the help!
