### ISSUE TITLE
[core] `test-e2e` failing on "should implement the roving tabindex pattern"

### ISSUE THREAD

**Issue by flaviendelangle** [mui-org/material-ui-x#2984]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

https://app.circleci.com/pipelines/github/mui-org/material-ui-x/8970/workflows/8923e343-479d-48cb-a0ca-55d60c8b5ba2/jobs/50445

We get the following error on a significant amount of our `test-e2e` runs on CircleCI

```
[0]   7 passing (3s)
[0]   1 failing
[0] 
[0]   1) e2e
[0]        <DataGrid />
[0]          should implement the roving tabindex pattern:
[0] 
[0]       AssertionError: expected 'Adidas' to equal '100'
[0]       + expected - actual
[0] 
[0]       -Adidas
[0]       +100
[0]       
[0]       at Context.<anonymous> (test/e2e/index.test.ts:94:81)
[0] 
[0] 
[0] 
[0] error Command failed with exit cod
```

**Comment by flaviendelangle** [comment]
@alexfauquette if your pr #3062 fixes this issue, please link them

**Comment by alexfauquette** [comment]
@m4theushw does #3027 solve this error?

**Comment by m4theushw** [comment]
@mui-org/x I ask everyone, does the `test:e2e` task is failing less or the same?

**Comment by flaviendelangle** [comment]
I saw fails since you merged it but it was maybe on outdated branches.
I'll tell you if I see any fails on branches that have your fix.

**Comment by alexfauquette** [comment]
This test is still failing. On PR #3087 which is up to date, and modify only a markdown file, I get the famous `AssertionError: expected 'Adidas' to equal '100'`

https://app.circleci.com/pipelines/github/mui-org/material-ui-x/9457/workflows/d6d348e0-0838-44a9-bb6a-d9a86ec8ad2d/jobs/53647

**Comment by m4theushw** [comment]
I feel that `test:e2e` is failing less after #3145. At least on my PRs I don't remember it failing recently. I'll close this and if the problem happens again you can re-open it.
