### ISSUE TITLE
DataGrid breaking with @mui/styles jss styles. Potentially related to recent jss release.

### ISSUE THREAD

**Issue by mfaheemakhtar** [mui-org/material-ui-x#2993]
- [ ] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Project compiles fine but screen with data grid breaks with a replaceURL or similar error.
See my issue here: https://github.com/cssinjs/jss/issues/1565

## Steps to Reproduce 🕹

Could not reproduce it and I am short of time at the moment. Posting here for other facing similar issue.

The issue was fixed with yarn resolutions:

```
"resolutions": {
    "jss": "10.8.0",
    "jss-plugin-camel-case": "10.8.0",
    "jss-plugin-default-unit": "10.8.0",
    "jss-plugin-global": "10.8.0",
    "jss-plugin-nested": "10.8.0",
    "jss-plugin-props-sort": "10.8.0",
    "jss-plugin-rule-value-function": "10.8.0",
    "jss-plugin-vendor-prefixer": "10.8.0"
  }
```

Steps:

1.
2.
3.
4.

## Your Environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by seiyab** [comment]
I'm wondering about why jss plugin nested v10.8.1 and older jss are installed together though jss plugins specify jss with same version as a dependency in package.json.

**Comment by oliviertassinari** [comment]
I'm closing as we have no reproductions.

**Comment by kof** [comment]
Is this still the case with 10.9.0?
