### ISSUE TITLE
[question] Entire table in edit mode

### ISSUE THREAD

**Issue by Edelf** [mui-org/material-ui-x#3016]
### Order ID 💳

#28950

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

We need to set all rows to editMode whenever the user presses Enter.
Is it possible to set the entire grid as editMode?

Otherwise, what would be the best approach to achieve this? 
Perhaps listening to `onRowEditStart` and loop through the records and call `apiRef.current.setRowMode(id, 'edit');` ?

### Your environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
Here's the demo with the ability to navigate between cells with <kbd>TAB</kbd>: https://codesandbox.io/s/fullfeaturedcrudgrid-material-demo-forked-zf38f

**Comment by Edelf** [comment]
Thank you very much guys!

**Comment by socramm9** [comment]
If someone else is also using this note that `columnIndex` was renamed to `colIndex`

> Here's the demo with the ability to navigate between cells with TAB: https://codesandbox.io/s/fullfeaturedcrudgrid-material-demo-forked-zf38f
> 
> In this example, the navigation from "Field 3" to the first cell also works.
> 
> ```tsx
> const handleCellKeyDown = (params, event: MuiEvent<React.KeyboardEvent>) => {
>   if (event.key !== 'Tab') {
>     return;
>   }
> 
>   const rowIds = gridVisibleSortedRowIdsSelector(apiRef.current.state);
>   const visibleColumns = apiRef.current.getVisibleColumns();
> 
>   const nextCell = {
>     rowIndex: rowIds.findIndex((id) => id === params.id),
>     colIndex: apiRef.current.getColumnIndex(params.field),
>   };
> 
>   if (
>     nextCell.colIndex === visibleColumns.length - 1 &&
>     nextCell.rowIndex === rowIds.length - 1 &&
>     !event.shiftKey
>   ) {
>     // Do nothing if we are at the last cell of the last row
>     return;
>   }
> 
>   if (nextCell.colIndex === 0 && nextCell.rowIndex === 0 && event.shiftKey) {
>     // Do nothing if we are at the first cell of the first row
>     return;
>   }
> 
>   event.preventDefault();
>   event.defaultMuiPrevented = true;
> 
>   if (!event.shiftKey) {
>     if (nextCell.colIndex < visibleColumns.length - 1) {
>       nextCell.colIndex += 1;
>     } else {
>       nextCell.rowIndex += 1;
>       nextCell.colIndex = 0;
>     }
>   } else if (nextCell.columnIndex > 0) {
>     nextCell.colIndex -= 1;
>   } else {
>     nextCell.rowIndex -= 1;
>     nextCell.colIndex = visibleColumns.length - 1;
>   }
>   apiRef.current.scrollToIndexes(nextCell);
> 
>   const field = visibleColumns[nextCell.colIndex].field;
>   const id = rowIds[nextCell.rowIndex];
>   apiRef.current.setCellFocus(id, field);
> };
> ```
