### ISSUE TITLE
Typescript Error:  error TS2314: Generic type 'OutputSelector' requires 4 type argument(s).

### ISSUE THREAD

**Issue by Moskowitza** [mui-org/material-ui-x#3017]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Build fails with Typescript. 40 errors related to  `error TS2314: Generic type 'OutputSelector' requires 4 type argument(s)`

node_modules/@mui/x-data-grid/data-grid.d.ts:3013:35 - error TS2314: Generic type 'OutputSelector' requires 4 type argument(s).

3013 declare const gridScrollSelector: reselect.OutputSelector<GridState, GridScrollParams, (res: GridRenderingState) => GridScrollParams>;               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

### Expected behavior 🤔

I expect reselect.OutputSeletor to take 3 type argument and for the site to build.

### Steps to reproduce 🕹

Steps:

1. Pull down example repo https://github.com/Moskowitza/muiGridTs
2. nvm use node (v16.10.0)
3. install node modules
4.npm run build

### Context 🔦

I'm trying to use build my Material UI application with Typescript

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```

  System:
    OS: macOS 11.5.2
  Binaries:
    Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
    Yarn: Not Found
    npm: 7.15.1 - ~/.nvm/versions/node/v16.3.0/bin/npm
  Browsers:
    Chrome: 95.0.4638.54
    Edge: 95.0.1020.30
    Firefox: 93.0
    Safari: 14.1.2
  npmPackages:
    @emotion/react: ^11.5.0 => 11.5.0
    @emotion/styled: ^11.3.0 => 11.3.0
    @mui/core:  5.0.0-alpha.53
    @mui/material: ^5.0.6 => 5.0.6
    @mui/private-theming:  5.0.1
    @mui/styled-engine:  5.0.2
    @mui/system:  5.0.6
    @mui/types:  7.0.0
    @mui/utils:  5.0.1
    @mui/x-data-grid: ^5.0.0-beta.5 => 5.0.0-beta.5
    @types/react: ^17.0.0 => 17.0.33
    react: ^17.0.0 => 17.0.2
    react-dom: ^17.0.0 => 17.0.2
    typescript: ^4.3.2 => 4.4.4

```
</details>
<details>
  <summary>`tsconfig.json`</summary>

```
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "allowJs": false,
    "skipLibCheck": false,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": ["./src"]
}

```
</details>

**Comment by flaviendelangle** [comment]
@Moskowitza upgrading `@mui/x-data-grid` to `v5.0.0-beta.7` seems to do the trick.
I don't understand why it was not working in the `v5.0.0-beta.5` :thinking:
