### ISSUE TITLE
[DataGrid] Changing `columns` when using `sortModel` throws exception if the previously sorted column is missing

### ISSUE THREAD

**Issue by longzheng** [mui-org/material-ui-x#3020]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using the `<DataGrid>`, it is expected and understood that changing the `columns` prop may throw an exception if the `sortModel` prop is applying a sort on a column that no longer exists. You would see the following exception
```
Error sorting: column with field 'age' not found. 
```

However, if both the `columns` and `sortModel` props are updated at the same time to ensure the `sortModel` is appropriate for the new `columns` definition, it still throws the "error sorting" exception which is unexpected.

I suspect that the `columns` update is taking precedence and it is still trying to apply the previous `sortModel`.

### Expected behavior 🤔

Render the new columns and sort.

### Steps to reproduce 🕹

 I have created a repro test case here https://codesandbox.io/s/datagriddemo-material-demo-forked-ft5j6?file=/demo.tsx

This repro has two column definitions as `Columns1` and `Columns2` with some overlapping columns (`ID`, `First name`), but the last column is different (either `Last name` or `Age`).

Steps:
1. Start with "Column1"
2. Click on the last column "Last name" to apply a sort
3. Then click on "Set Column2"
4. See exception

I've discovered a workaround which uses `setTimeout()` to force updating the `sortModel` first and then `columns` in a separate render cycle.

```typescript
    // set sort model first
    setSortModel(DefaultSort);
    // at next render, update columns
    setTimeout(() => {
      setColumns(columns);
    });
```

### Context 🔦

I'm creating a dashboard which allows users to switch between different datasets (with different columns) in the same DataGrid.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 16.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.21.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 95.0.4638.54
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.30), ChromiumDev (96.0.1054.2)
  npmPackages:
    @emotion/react: ^11.4.1 => 11.4.1
    @emotion/styled: ^11.3.0 => 11.3.0
    @mui/icons-material: ^5.0.4 => 5.0.4
    @mui/material: ^5.0.4 => 5.0.4
    @mui/styled-engine:  5.0.1
    @mui/utils:  5.0.1
    @mui/x-data-grid: ^4.0.1 => 4.0.1
    @types/react: 17.0.27 => 17.0.27
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2
    typescript: 4.4.3 => 4.4.3
```
</details>

Using Chrome 95.0.4638.54

**Comment by DanailH** [comment]
I would like to get the opinion of @m4theushw and @alexdanilowicz on this. If we decide it is a bug then we can proceed with updating the behavior. For me, the current behaviour is expected since the `sortModel` is "controlled"

**Comment by flaviendelangle** [comment]
I simplified the demo to describe the bug https://codesandbox.io/s/datagriddemo-material-demo-forked-r27yc?file=/demo.tsx
