### ISSUE TITLE
[docs] Endless page refresh in Russian language

### ISSUE THREAD

**Issue by hd321kbps** [mui-org/material-ui-x#3060]
Infinite refresh of pages in the Data Grid section
![mui](https://user-images.githubusercontent.com/9886849/139644524-2e833a44-0933-4481-bc8f-3fae60270f0a.gif)

**Comment by flaviendelangle** [comment]
@m4theushw it was fixed in the release `5.0.3` of the core.
Since we are using your fork for the monorepo, did you merge it with the `mui` repo since ?
We really need to stop using the fork, I pinged Michal on Twitter for a review of the PR causing it.
