### ISSUE TITLE
[DataGrid] Uncaught Error: No filter operator found

### ISSUE THREAD

**Issue by stamahto** [mui-org/material-ui-x#3071]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I'm saving the filter model into localStorage (with onFilterModelChange property), and  I´m providing that saved filterModel to the dataGrid, so the filter remains active after refresh the page. But when I need to change some column type (for example 'string' to 'number'), the table drops and log this error to console.
![image](https://user-images.githubusercontent.com/57343418/139820478-62987e7a-16b2-4d91-9b24-e95cf363da64.png)
It would be great to handle this exception into 'onError' function, so I can clear my localStorage and refresh the page if this error occures.

### Expected behavior 🤔

The function 'onError' should be fired.

### Steps to reproduce 🕹

Steps:

1. Save filterModel into localStorage from function 'onFilterModelChange'.
2. Provide stored filterModel into dataGrid.
3. Change any column type to have different filter operators.
4. Refresh page

### Context 🔦

The customer wants the filters to remain even after the page is refreshed.

### Your environment 🌎

"@mui/icons-material": "^5.0.3",
"@mui/material": "^5.0.3",
"@mui/styles": "^5.0.1",
"@mui/x-data-grid-pro": "^5.0.0-beta.6"

**Comment by DanailH** [comment]
Please provide a minimal reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) _may_ be a good starting point. Thank you!

**Comment by stamahto** [comment]
Hi, thanks to provide starting point. Please check this example: https://codesandbox.io/s/datagrid-v5-quick-start-forked-88uee?file=/src/App.tsx
Firstly, filter some column to fire 'onFilterModelChange' function to save filter state to localStorage, then change type: "string" to type: "number" on line 32.

**Comment by jacobcarrington** [comment]
I've run into the same issue, but it only effects columns that have a custom operator. If you add a filter to the filter model it throws an error on mount: `Material-UI: No filter operators found for column 'id'.`

**Comment by jacobcarrington** [comment]
A much simpler demo that illustrate the issue: https://codesandbox.io/s/datagrid-v5-quick-start-forked-lv9tr?file=/src/App.tsx

**Comment by flaviendelangle** [comment]
```ts
{ field: "id", hide: true, type: "number" },

items: [
  {
    columnField: "id",
    operatorValue: "contains",
    value: 1
  }
],
```

Do we agree that you give an operator that do not exist for the type `number` and that the crash is expected @jacobcarrington ?

For the `onError`, currently it is only a wrapper around `componentDidCatch`.
We could make it work with other errors.
