### ISSUE TITLE
Multiselect within DataGrid cell

### ISSUE THREAD

**Issue by jamintz** [mui-org/material-ui-x#3075]
### Order ID 💳

21172

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I'm trying to implement a multi-select within a DataGrid column. Following the advice [here](https://github.com/mui-org/material-ui-x/issues/2739) I implemented it using Autocomplete. Functionally it pretty much works, but I'm looking for some suggestions or help on styling.

### The problem in depth 🔍

Specifically, it looks OK when only one or two items are selected:
<img width="223" alt="Screen Shot 2021-11-02 at 2 29 48 PM" src="https://user-images.githubusercontent.com/3538254/139924654-c9858622-adef-4fa0-ba3c-6149d65ff460.png">

However, when a bunch are added the select arrow drops further and further down and everything's trapped within the cell – no way to scroll lower etc. Changing the cell width allows more to be displayed at a time but I'm looking for a more general solution, that would hit a limit as well.
<img width="245" alt="Screen Shot 2021-11-02 at 2 29 39 PM" src="https://user-images.githubusercontent.com/3538254/139925116-84d84f1a-a271-4bcd-a376-45aa228ca43e.png">

Reproduction here: https://codesandbox.io/s/renderratingeditcellgrid-material-demo-forked-te5iw?file=/demo.js

### Context 🔦

It'd be useful to have a nice looking multi-select

### Your environment 🌎

   "@mui/icons-material": "^5.0.4",
    "@mui/lab": "^5.0.0-alpha.51",
    "@mui/material": "^5.0.4",
    "@mui/styles": "^5.0.1",
    "@mui/x-data-grid-generator": "^5.0.0-beta.4",
    "@mui/x-data-grid-pro": "^5.0.0-beta.4",

**Comment by m4theushw** [comment]
You have to use a Portal to allow the Autocomplete to exceed the cell boundaries. In https://github.com/mui-org/material-ui-x/issues/2851#issuecomment-942773183 I showed how to create a textarea-like component with this capability. The approach is the same here.

**Comment by jamintz** [comment]
Perfect, thanks
