### ISSUE TITLE
[DataGrid] Selecting all 100k rows takes too much time

### ISSUE THREAD

**Issue by m4theushw** [mui-org/material-ui-x#3076]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Selecting all 100k is taking too much time.

### Expected behavior 🤔

It should be faster. In https://v4.mui.com/components/data-grid/#commercial-version it's almost immediately.

### Steps to reproduce 🕹

Steps:

1. Open https://mui.com/components/data-grid/#commercial-version
2. Select all 100k rows

### Context 🔦

It started in #2781

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by oliviertassinari** [comment]
😱
