### ISSUE TITLE
[DataGrid] Can't focus the column header with the keyboard on page > 0

### ISSUE THREAD

**Issue by m4theushw** [mui-org/material-ui-x#3083]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Pressing <kbd>Arrow Up</kbd> or <kbd>Page Up</kbd> on the first row of second page doesn't move the focus to the column header, as it happens on the first page.

<img width="500" src="https://user-images.githubusercontent.com/42154031/140105487-ee3714f6-bed5-406d-b0a6-68dfbb2e87b1.gif" alt="4QShbJtcdw" style="max-width: 100%;">

### Expected behavior 🤔

It should focus the column header.

### Steps to reproduce 🕹

Steps:

1. Open https://next--material-ui-x.netlify.app/components/data-grid/#mit-version
2. Go to the second page
3. Press <kbd>Arrow Up</kbd> or <kbd>Page Up</kbd> on any cell of the first row

### Context 🔦

I noticed while reviewing https://github.com/mui-org/material-ui-x/pull/3074. This bug has been since forever. I can reproduce it in https://v4.mui.com/components/data-grid/#mit-version

The `rowIndex` below is relative to all visible rows. So the calculated index on page > 0 will be equal to the last row of the previous page. One solution is to check if `rowIndex` is smaller than the index of the first row in the current page.

https://github.com/mui-org/material-ui-x/blob/6273301d2972637b6ea1187e0677dfb7d0835f0e/packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboardNavigation.ts#L140

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Same thing the other way around, when you are on the header, you can't go down on page > 0
