### ISSUE TITLE
[DataGridPro] Expanding a Row

### ISSUE THREAD

**Issue by lebaphi** [mui-org/material-ui-x#3093]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I see we have an example of the Sticky Header, Filter and Sorting here https://codesandbox.io/s/datatable-material-demo-forked-2zw8u?file=/demo.tsx:1452-1460
And an example with the expanding row at https://codesandbox.io/s/6plud?file=/demo.tsx:4765-4844.
So I have a demand to combine these feature together in 1 table. Can we do that?

**Comment by flaviendelangle** [comment]
Your 2nd example is using the `Table` component not the `DataTable`.
But in the `DataTable`, this feature is not available yet. It is called #211 and should be developed this quarter.

**Comment by m4theushw** [comment]
Please subscribe to #211 to be notified when it gets released.

I'll close this one.
