### ISSUE TITLE
[DatagridPro] `onSelectionModelChange` called when page changed

### ISSUE THREAD

**Issue by perfectdeed** [mui-org/material-ui-x#3134]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Here the code I use:
I am on version 4.x, I don't really have time to break something that is working.

...
const selections = useSelector((state: Store) => state.selected[entity] || []);
...
const handleOnSelect = (selected:GridSelectionModel) => {
    dispatch(setSelection({
      entity,
      selected,
    }));
  };
  ...
   <XGrid
          disableColumnMenu
          rows={getRows()}
          columns={getColumns()}
          onColumnWidthChange={handleColumnWidthChange}
          onColumnOrderChange={handleColumnOrderChange}
          paginationMode="server"
          rowCount={data.count}
          pagination
          pageSize={pageSize}
          onPageSizeChange={handlePageSizeChange}
          onPageChange={handlePageChange}
          onSelectionModelChange={handleOnSelect}
          selectionModel={selections}
        />

When I change page, the handleOnSelect function is called with an empty array as an argument.

### Expected behavior 🤔

The onSelectionModelChange handler should not be called when the page change?
The only source of truth should be the store. Anyway, there is no reason for the selection to be resetted when we change page. 

### Context 🔦

I just want the selected rows to be persistent accross all the datagrid. I want to store the selected ids in the store to be use by other components. 

### Order ID 💳 (optional)

28579

**Comment by flaviendelangle** [comment]
Thank you for your feedback
Could you please give us a full reproduction case, this [template](https://codesandbox.io/s/datagridpro-v5-quick-start-5pjhc) could be a good starting point.

We probably have cases were the Grid tries to remove some rows from the selection. But I need more context to fix the issue if it is on our side or help you if the behavior is intended :+1:

**Comment by perfectdeed** [comment]
I so don't have time to write code for you. I gave you the relevant code and I already fixed it by using onRowClick and managing the state myself. I wont track back my code. Thank you anyway.
