### ISSUE TITLE
[DataGridPro] Editing cell based on other cell onCellEditCommit

### ISSUE THREAD

**Issue by jamintz** [mui-org/material-ui-x#3147]
### Order ID 💳

21172

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Attempting to use apiRef to set the value of a cell when a different cell changes

### The problem in depth 🔍

I'm using `onCellEditCommit` to fire when a cell is changed. I then want to run some logic / methods and update a different cell in the same row based on the first cell that was changed. However, the way I'm trying to do it doesn't seem to be working so looking for a suggestion or alternative.

A simplified demo is [here](https://codesandbox.io/s/basiceditinggrid-material-demo-forked-wlw3l?file=/demo.js), in this example if a row's "name" is edited I'm trying to set the "age" to 0. Specific error I'm seeing in the example is `Cannot read properties of undefined (reading 'name')`, making it seem like it's trying to get the "name" of an undefined object, potentially from the fact that I'm running apiRef cell updates from within the `onCellEditCommit`, so any suggestions helpful.

### Context 🔦

Table feature, I have some dynamic columns where new data is fetched / the cells are updated based on changing selection in a different cell.

### Your environment 🌎

"@mui/icons-material": "^5.0.4",
"@mui/lab": "^5.0.0-alpha.51",
"@mui/material": "^5.0.4",
"@mui/styles": "^5.0.1",
"@mui/x-data-grid-generator": "^5.0.0-beta.4",
"@mui/x-data-grid-pro": "^5.0.0-beta.4",

**Comment by m4theushw** [comment]
In this case is better to override the entire logic of the `cellEditCommit` event. We don't have yet a event fired after the row is updated. The following code should be sufficient.

```ts
const handleCellEditCommit = (params, event) => {
  if (params.field === "name") {
    event.defaultMuiPrevented = true;
    const model = apiRef.current.getEditRowsModel();
    const { value } = model[params.id].name;
    const row = apiRef.current.getRow(params.id); // The row before start editing
    const rowUpdate = { ...row, name: value, age: 0 }; // Merge the old row with the new value
    apiRef.current.updateRows([rowUpdate]);
  }
};
```

**Comment by jamintz** [comment]
This works perfectly, thank you
