### ISSUE TITLE
[DataGrid] Change icon and title of `GridToolbarColumnsButton`

### ISSUE THREAD

**Issue by cagosto** [mui-org/material-ui-x#3148]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I would like to be able to control the icons and text for this component `<GridToolbarColumnsButton />` I don't see any prop that will allow me to change those values. 

### Examples 🌈

<GridToolbarContainer>
      <GridToolbarColumnsButton title="test" />
      <GridToolbarFilterButton />
    </GridToolbarContainer>

This give you an output of this
<img width="767" alt="Screen Shot 2021-11-09 at 1 44 19 PM" src="https://user-images.githubusercontent.com/1731744/140985429-50a0b05a-3654-46a1-817d-6d657d016f04.png">

### Motivation 🔦

Trying to add some customizations to the `<DataGrid />` toolbar component.

**Comment by flaviendelangle** [comment]
For the text, you can override the locals via the `localeText` prop of the `DataGrid` component
For the other props of this component, you will have to provide your own toolbar. It is a very basic component so copy pasting it is not a big issue. 

Here is an example: https://codesandbox.io/s/datagrid-v5-quick-start-forked-d3s3r?file=/src/App.tsx

**Comment by cagosto** [comment]
Well this is amazing thanks you very much for taking the time to responded to the question and supplying an example.

**Comment by jandresfg** [comment]
Hi @flaviendelangle! could you please provide the code of the example? the codesandbox link is broken
