### ISSUE TITLE
[DataGrid] Show a cell only when hovering the row

### ISSUE THREAD

**Issue by konerunaveena** [mui-org/material-ui-x#3152]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

when we hover on row, column should appear else column should not be visible

![image](https://user-images.githubusercontent.com/16998899/141104385-a31ac176-ddf1-417c-b9b8-85db7ca274ea.png)

**Comment by flaviendelangle** [comment]
https://codesandbox.io/s/datagrid-v5-quick-start-forked-gsi94?file=/src/App.tsx

I can be done with CSS :+1: 
Their is no way in the grid to properly render or not based on the hover status of the row.
You could listen to the `onMouseEnter` / `onMouseLeave` of the row (docs [here](https://mui.com/components/data-grid/components/#row)) and store the information in a state outside. But you would re-render the whole Grid which is really not optimal.
