### ISSUE TITLE
[DataGrid] Control positions of filters and column pop over

### ISSUE THREAD

**Issue by cagosto** [mui-org/material-ui-x#3155]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I am wondering if there is current support or support coming for controlling were the "Filters" button opens the pop over controls. For example https://codesandbox.io/s/09dte?file=/demo.js if I wanted to move the menu that opens when I click "Filters" button to be under the "Filter" button and not under the Table Header. Is there a way to control that? I looked at the Data Grid API but not seeing a way to control that component.

### Examples 🌈

https://codesandbox.io/s/09dte?file=/demo.js

### Motivation 🔦

Would like to control where the pop over gets displayed.

**Comment by m4theushw** [comment]
> if I wanted to move the menu that opens when I click filters to be under the filter button and not under the Toolbar

I didn't understand this part. The filter panel (menu as you refer) already opens below both the "Filters" button and the toolbar. Do you want to open it anchored the "Filters" button? Where it should be anchored when the filter panel is opened by clicking on "Filter" button inside the column menu?

**Comment by cagosto** [comment]
@m4theushw I am sorry that my question was unclear so let me try to clear things up.  Yes I would like to anchor the menu to the "Filters" button. So for example when you click on "Density" as seen below the menu show up right under the "Density" button.
<img width="717" alt="Screen Shot 2021-11-11 at 1 00 55 PM" src="https://user-images.githubusercontent.com/1731744/141346841-90815481-2dae-4088-97ae-0c22efa440a8.png">

When you click on "Filter" as seen below is show up over the data right under the data column headers.

<img width="582" alt="Screen Shot 2021-11-11 at 1 02 40 PM" src="https://user-images.githubusercontent.com/1731744/141347109-70b1f567-0355-407c-a53e-ce2b225a5308.png">

I would like to change the anchor for the menu to work more like the "Density" button.

**Comment by m4theushw** [comment]
Here's an example of how to do it:

```tsx
const [filterButtonEl, setFilterButtonEl] = React.useState(null);

const CustomToolbar = React.useCallback(() => {
  return (
    <GridToolbarContainer>
      <GridToolbarFilterButton ref={setFilterButtonEl} />
    </GridToolbarContainer>
  );
}, []);

return (
  <div style={{ height: 400, width: "100%" }}>
    <DataGrid
      {...data}
      components={{
        Toolbar: CustomToolbar
      }}
      componentsProps={{
        panel: {
          anchorEl: filterButtonEl
        }
      }}
    />
  </div>
);
```

**Comment by cagosto** [comment]
👍 thanks for getting back to me.

**Comment by flaviendelangle** [comment]
I'm closing since an answer has been given :+1:

**Comment by rawatrupesh** [comment]
Late to the party, but this changes the `anchorEl` for all panels, including the column selection panel and the filter panel. How would I do this if I only wanted to change it for a specific one? In my case, the datagrid toolbar has the column selection button, but does not have the filters button, so I want to change the anchor element only for the column selection panel

**Comment by BrentFarese** [comment]
> 

Plus 1 to this.  We are trying to attach a custom filter panel to a filter button and columns panel to a columns button but it seems the `anchorEl` prop is for all panels?  Any ideas @flaviendelangle?  Thanks.

**Comment by BrentFarese** [comment]
@rawatrupesh maybe try this approach (change the `anchorEl` based on grid state).  Seems to work for me:

```
panel: {
              anchorEl:
                preferencePanelState.openedPanelValue === GridPreferencePanelsValue.filters
                  ? filtersEl
                  : columnsEl,
            },
```

**Comment by aress31** [comment]
@BrentFarese that solution adds a lot of boilerplate code and is not straightforward,  why not just using the `filterPanel` and `columnPanel` slots to pass the anchor? That would be more dev friendly.

Also, I am failing to see the point of these slots as of now as passing the `anchor` has only an effect on the global panel slots but again that's not granular enough when using both the `column` **and** `filter` panels.
