### ISSUE TITLE
Update `@mui/core` to `@mui/base` on grid-generator

### ISSUE THREAD

**Issue by siriwatknp** [mui-org/material-ui-x#3157]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Due to https://github.com/mui-org/material-ui/pull/29585.

~`@mui/core` should not be a dependency because~
~- the package is not used directly~
~- `@mui/material` is already a peer dependency (`@mui/core` is a dependency of this package)~

~I believe that this is a mistake from the migration when we changed the package name.~

### Expected behavior 🤔

~`@mui/core` is not listed as a dependency.~

### Steps to reproduce 🕹

~https://github.com/mui-org/material-ui-x/blob/56610e553ef32afab69ac169c78674430aa2a4ce/packages/grid/x-data-grid-generator/package.json?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L31~

### Context 🔦

~I found it in yarn.lock on this PR. https://github.com/mui-org/material-ui/pull/29464#discussion_r746424792~

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by siriwatknp** [comment]
If this makes sense, I can submit a PR to remove it.

**Comment by oliviertassinari** [comment]
It's used here: https://github.com/mui-org/material-ui-x/blob/0fd81307c6ffdc1031726680a5f302bb280058c4/packages/grid/x-data-grid-generator/src/renderer/renderEditProgress.tsx#L5

**Comment by siriwatknp** [comment]
> It's used here:
> 
> https://github.com/mui-org/material-ui-x/blob/0fd81307c6ffdc1031726680a5f302bb280058c4/packages/grid/x-data-grid-generator/src/renderer/renderEditProgress.tsx#L5
> 
> so it should likely be present. Implicit transitive dependencies are borderline (and not supported by yarn v2). For example, say `@mui/material` changes its dependency from `@mui/core` to `@mui/base`, then `@mui/x-data-grid-generator` is broken.
> 
> _I have unsubscribed, mention me directly (@oliviertassinari) if you want to see something._

@oliviertassinari Thanks for pointing that out. I have changed the title to update `@mui/core` to `@mui/base` instead.
