### ISSUE TITLE
Include column headers in copy/paste

### ISSUE THREAD

**Issue by jaginn** [mui-org/material-ui-x#3164]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Currently selected grid records can be copied/pasted but the copied data does not include column headers. Can an option please be included to include column headers when copying/pasting records.

### Motivation 🔦

Without column headers included users do not have any context for data pasted into a text editor, spreadsheet or other client.

### Order ID 💳 (optional)

31318

**Comment by m4theushw** [comment]
Pressing <kbd>ALT</kbd> + <kbd>C</kbd> instead will also copy the headers. See https://mui.com/components/data-grid/accessibility/

**Comment by jaginn** [comment]
> Pressing ALT + C instead will also copy the headers. See https://mui.com/components/data-grid/accessibility/

Thankyou m4theushw, I'd missed this.

**Comment by jaginn** [comment]
Closing as already implemented

**Comment by fabianf92** [comment]
Hi @jaginn and @m4theushw ,

is it really implemented? I tried copying the header and rows with `ALT` + `C`, but it is not working.
I used the example table here: [](https://mui.com/x/react-data-grid/clipboard/)

Thank you for any help!

**Comment by EmilianoLam** [comment]
Hello there!
I have created issue #14178 related to this feature.
Any support is welcome!
Thanks!
