### ISSUE TITLE
How can I use grid action in Data Grid Pro

### ISSUE THREAD

**Issue by minhtly1** [mui-org/material-ui-x#3168]
### Order ID 💳

29525

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

How can I display field with type: "actions" in DataGridPro with latest stable version of "@mui/x-data-grid-pro": "^4.0.2", 

I was successfully parse those actions type fields into DataGridPro when using "@mui/x-data-grid-pro": "^5.0.0-beta.6". But by doing so, all the built in components' styling starting to run out of whack. 
For example "GridToolbarDensitySelector" and "GridPagination" all displayed their options in same line instead of a list. I don't want to overwrite styling either. 

So how should I have fields with type:"actions" to display correctly in the latest stable version of @mui/x-data-grid-pro

### Your environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 14.17.0 - C:\Program Files (x86)\nodejs\node.EXE
    Yarn: 1.22.11 - ~\git\doforms-workforce-manager\node_modules\.bin\yarn.CMD
    npm: 8.1.2 - C:\Program Files (x86)\nodejs\npm.CMD
  Browsers:
    Chrome: 95.0.4638.54
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.44)
  npmPackages:
    @emotion/react: latest => 11.4.1
    @emotion/styled: latest => 11.3.0
    @material-ui/core: ^4.12.3 => 4.12.3
    @material-ui/icons: ^4.11.2 => 4.11.2
    @material-ui/lab: ^4.0.0-alpha.60 => 4.0.0-alpha.60
    @material-ui/pickers: 4.0.0-alpha.7 => 4.0.0-alpha.7
    @material-ui/styles: ^4.11.4 => 4.11.4
    @material-ui/system:  4.12.1
    @material-ui/types:  5.1.0
    @material-ui/utils:  4.11.2
    @material-ui/x-license: ^4.0.0-alpha.37 => 4.0.0-alpha.37
    @types/react:  17.0.15
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2

```
</details>

**Comment by flaviendelangle** [comment]
The `actions` columns have been added in `v5.0.0-beta.0` so they are not available in the versions below.
If you can't migrate the X part to `v5` yet, you can take a look at [this guide](https://mui.com/components/data-grid/migration-v4/#using-mui-x-v5-with-mui-core-v4) to have `@mui/x-data-grid-pro@5.X` and `@material-ui/core@4.X`
