### ISSUE TITLE
[DataGrid] Virtualization not working with `autoHeight` prop 

### ISSUE THREAD

**Issue by merisbahti** [mui-org/material-ui-x#3186]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Codesandbox:

https://codesandbox.io/s/datagrid-quick-start-forked-ksik9?file=/src/App.tsx

I have 100+ rows. Enough to create a scrollbar to the right.

If I inspect element, like this:

![image](https://user-images.githubusercontent.com/2946728/141755817-86da3b09-70c4-4cd9-add9-88353ff50569.png)

The 100:th row is rendered in the dom. 

### Expected behavior 🤔

I expected the row to not be rendered, maybe a placeholder with the default row height, but otherwise empty in the dom.

### Steps to reproduce 🕹

Steps:

1. go to https://codesandbox.io/s/datagrid-quick-start-forked-ksik9?file=/src/App.tsx
2. Inspect element, and scroll down to 100th row
3. See that it exists

### Context 🔦

I want to have a table, that makes the document bigger, and adds "scrollbar" to the document if the table grows.

I don't want to have pagination, and I don't want to have a small scrollbar in the table itself.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Memory: 75.05 MB / 16.00 GB
    Shell: 3.2.2 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.10.0 - /usr/local/bin/node
    Yarn: 1.21.1 - ~/.npm-global/bin/yarn
    npm: 7.24.0 - /usr/local/bin/npm
  Managers:
    Cargo: 1.56.0 - ~/.cargo/bin/cargo
    Homebrew: 3.2.17 - /opt/homebrew/bin/brew
    Maven: 3.8.1 - /opt/homebrew/bin/mvn
    pip3: 21.1 - /usr/local/Caskroom/miniforge/base/bin/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.30.1 - /usr/bin/git
    Clang: 12.0.5 - /usr/bin/clang
  Servers:
    Apache: 2.4.48 - /usr/sbin/apachectl
  Virtualization:
    Docker: 20.10.8 - /usr/local/bin/docker
    Parallels: 17.0.1 - /usr/local/bin/prlctl
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
  IDEs:
    Nano: 2.0.6 - /usr/bin/nano
    Vim: 8.2 - /usr/bin/vim
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 11.0.10 - /Users/merisb/.sdkman/candidates/java/current/bin/javac
    Perl: 5.30.3 - /usr/bin/perl
    Python: 3.8.10 - /usr/local/Caskroom/miniforge/base/bin/python
    Python3: 3.8.10 - /usr/local/Caskroom/miniforge/base/bin/python3
    Ruby: 2.6.8 - /usr/bin/ruby
    Rust: 1.56.0 - /Users/merisb/.cargo/bin/rustc
  Databases:
    PostgreSQL: 14.0 - /opt/homebrew/bin/postgres
    SQLite: 3.35.5 - /usr/local/Caskroom/miniforge/base/bin/sqlite3
  Browsers:
    Chrome: 93.0.4577.63
    Safari: 15.1
  Monorepos:
    Yarn Workspaces: 1.21.1
    Lerna: 4.0.0
```
</details>

I'm using chrome.

**Comment by m4theushw** [comment]
> I expected the row to not be rendered, maybe a placeholder with the default row height, but otherwise empty in the dom.

Why the 100th should not exist? The page size is 100.

> I don't want to have pagination, and I don't want to have a small scrollbar in the table itself.

The pagination can only be fully disabled using DataGridPro.

**Comment by flaviendelangle** [comment]
Can we close that one since we did not have any answer in 3 weeks ?
