### ISSUE TITLE
[DataGrid] Export Option can turn transparent on FireFox

### ISSUE THREAD

**Issue by supidupicoder2** [mui-org/material-ui-x#3190]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If you press Export in a datagrid view, and then wiggle your cursor around on the menu that appears (with the export csv or pdf options), the menu sometimes turns transparent, if you place your cursor in the right spot. you can than see the background and the menu at the same time.

happens on firefox, but not chrome
![wiggle cursor transparent](https://user-images.githubusercontent.com/94068428/141816224-a30f02e0-70db-447e-97d4-06123b6bade7.png)

### Expected behavior 🤔

Should not turn transparent

### Steps to reproduce 🕹

Steps:

1. Go To https://codesandbox.io/s/4j418?file=/demo.js with firefox 94.0.1
2. press on export
3. move your cursor around slowly on the menu that appears. sometimes the background (so the labels of the table) will appear. This does not happen always and instantly, but after a few seconds of trying it does usually happen.

### Context 🔦

If you try to provide export options, this causes usability inconveniences

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
   Browser: Firefox 94.0.1
  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 14.18.0 - C:\Program Files\nodejs\node.EXE        
    Yarn: Not Found
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.44)
  npmPackages:
    @emotion/react: ^11.4.1 => 11.4.1 
    @emotion/styled: ^11.3.0 => 11.3.0 
    @mui/core:  5.0.0-alpha.50 
    @mui/icons-material: ^5.0.3 => 5.0.3
    @mui/lab: ^5.0.0-alpha.50 => 5.0.0-alpha.50
    @mui/material: ^5.0.6 => 5.0.6
    @mui/private-theming:  5.0.1
    @mui/styled-engine:  5.0.1
    @mui/styles: ^5.0.1 => 5.0.1
    @mui/system:  5.0.3
    @mui/types:  7.0.0
    @mui/utils:  5.0.1
    @mui/x-data-grid: next => 5.0.0-beta.7
    @types/react:  17.0.3
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
```
</details>

**Comment by m4theushw** [comment]
Could you record a video showing the cursor movement? I have Firefox 94.0.2 and I couldn't reproduce it.

**Comment by supidupicoder2** [comment]
Hello, 2 weeks later and several restarts of my PC, i can not reproduce this anymore, seems to work fine now.
