### ISSUE TITLE
x-data-grid TypeScript definitions broken in v5.0.0

### ISSUE THREAD

**Issue by bzuu-ic** [mui-org/material-ui-x#3195]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

After upgrading from `@mui/x-data-grid@5.0.0-beta.7` to `@mui/x-data-grid@5.0.0` TypeScript compilation fails. It seems the typescript definitions file in `node_modules/@mui/x-data-grid/data-grid.d.ts` was renamed to `x-data-grid.d.ts`, but the `package.json` was not updated accordingly.

When trying to compile my project I get the following error:
```
Failed to compile.

/workspaces/frontend/src/components/SingleSelectEditor.tsx
TypeScript error in /workspaces/frontend/src/components/SingleSelectEditor.tsx(1,68):
Could not find a declaration file for module '@mui/x-data-grid'. '/workspaces/frontend/node_modules/@mui/x-data-grid/index-cjs.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/mui__x-data-grid` if it exists or add a new declaration (.d.ts) file containing `declare module '@mui/x-data-grid';`  TS7016

  > 1 | import { GridEditSingleSelectCell, GridRenderEditCellParams } from "@mui/x-data-grid"
      |                                                                    ^
    2 | 
    3 | export const SingleSelectEditor = (params: GridRenderEditCellParams) => (
    4 |     <GridEditSingleSelectCell {...params} variant="standard" />
```

### Expected behavior 🤔

TypeScript compilation should work

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
:fearful: I'll fix it

**Comment by m4theushw** [comment]
We missed renaming here:

https://github.com/mui-org/material-ui-x/blob/7f4cf1eb1a47708436f7ca1006daf3c11932a8f5/packages/grid/rollup.x-data-grid.config.js#L74

**Comment by flaviendelangle** [comment]
Yes, we could take the information in the `package.json` in a future PR to avoid having several places to update.

I'll release v5.0.1 with the fix

**Comment by flaviendelangle** [comment]
v5.0.1 is published and should solve the issue

**Comment by krallj** [comment]
Updated my package to ^5.0.1 and confirm that the compilation error above is no longer appearing when I run my project.
