### ISSUE TITLE
[DataGrid] setting columns dynamically won't render headers fully

### ISSUE THREAD

**Issue by Liooo** [mui-org/material-ui-x#3200]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

[codesandbox](https://codesandbox.io/s/datagriddemo-material-demo-forked-8vn1b?file=/demo.tsx)

The headers won't show fully until scrolling.

![header](https://user-images.githubusercontent.com/1630378/142036823-21cfe438-44c6-404a-998d-8fed369c5a79.gif)

### Expected behavior 🤔

headers render even if rows are empty

### Steps to reproduce 🕹

1. open [codesandbox](https://codesandbox.io/s/datagriddemo-material-demo-forked-8vn1b?file=/demo.tsx)
2. click cols button

### Context 🔦

loading rows and cols from different api, and showing headers before rows are ready

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
Browser: Brave Browser Version 1.31.88 Chromium: 95.0.4638.69 (Official Build) (x86_64)  

System:
    OS: macOS 11.6
  Binaries:
    Node: 16.8.0 - ~/.asdf/installs/nodejs/16.8.0/bin/node
    Yarn: 1.22.11 - ~/.asdf/installs/nodejs/16.8.0/.npm/bin/yarn
    npm: 7.21.0 - ~/.asdf/installs/nodejs/16.8.0/bin/npm
  Browsers:
    Chrome: 95.0.4638.69
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.0
  npmPackages:
    @emotion/react: 11.4.1 => 11.4.1
    @emotion/styled: 11.3.0 => 11.3.0
    @mui/core:  5.0.0-alpha.51
    @mui/icons-material: 5.0.4 => 5.0.4
    @mui/material: 5.0.4 => 5.0.4
    @mui/private-theming:  5.0.1
    @mui/styled-engine:  5.0.1
    @mui/system: 5.0.4 => 5.0.4
    @mui/types:  7.0.0
    @mui/utils:  5.0.1
    @mui/x-data-grid: 5.0.0 => 5.0.0
    @types/react: 17.0.19 => 17.0.19
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2
    typescript: 4.4.2 => 4.4.2
```
</details>

**Comment by masbaehr** [comment]
Same issue - Rollback fixes the issue if you need a quick fix until it is solved

 "@mui/x-data-grid": "^4.0.2",
