### ISSUE TITLE
Could not find a declaration file for module '@mui/x-data-grid'.

### ISSUE THREAD

**Issue by evgenoid** [mui-org/material-ui-x#3203]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

```
Could not find a declaration file for module '@mui/x-data-grid'. '/Users/evgeniy/www/faction/react-portal/node_modules/@mui/x-data-grid/index-cjs.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/mui__x-data-grid` if it exists or add a new declaration (.d.ts) file containing `declare module '@mui/x-data-grid';`  TS7016
```
```
  > 1 | import { GridColumns, GridRenderCellParams } from '@mui/x-data-grid';
```  

### Context 🔦

"@mui/icons-material": "5.1.1",
"@mui/material": "5.1.1",
"@mui/styles": "5.1.1",
"@mui/utils": "5.1.1",
"@mui/x-data-grid": "5.0.0",

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
v5.0.1 is published and should solve the issue

**Comment by kodeschooler** [comment]
I'm getting this error and I installed v5.0.7. What would cause this?

**Comment by flaviendelangle** [comment]
Can you log me all your mui deps version with `npx @mui/envinfo` please ?
