### ISSUE TITLE
Add new row in datagrid when clicked on  button/link

### ISSUE THREAD

**Issue by konerunaveena** [mui-org/material-ui-x#3205]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Expected behavior 🤔

i want to add a new row when we click on the button 

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
I will need some information here
Which button ?
