### ISSUE TITLE
onColumnVisibilityChange doesn't trigger from the "show all / hide all" buttons

### ISSUE THREAD

**Issue by ivoiv** [mui-org/material-ui-x#3207]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

onColumnVisibilityChange doesn't trigger from the "show all / hide all" buttons

ticking individual columns triggers it, but not the "show all / hide all" 

### Expected behavior 🤔

onColumnVisibilityChange should trigger from the "show all / hide all" buttons

Perhaps add a new callback? Something like `onColumnVisibilityChangeAll` that only triggers from the "show all / hide all" buttons ?
Perhaps change onColumnVisibilityChange so it returns an array of objects instead of a single one, for each field changed during the trigger?

### Steps to reproduce 🕹

Steps:

1. Visit https://codesandbox.io/s/basicfilteringgrid-material-demo-forked-78j8g?file=/demo.js
2. Open console in CodeSandbox
2. Click the Columns button in the up-left corner
3. Click on Show all / Hide all
4. Nothing happens in console

### Context 🔦

I'm trying to react to changes in selected columns but I can only detect changes to individual selections and not a "all" selection.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Duplicates #2198 

I will try to take some time to work on this issue :+1:
