### ISSUE TITLE
[feature] GridToolbarFilterButton: Customize Tooltip's Value

### ISSUE THREAD

**Issue by jpgilchrist** [mui-org/material-ui-x#3210]
https://github.com/mui-org/material-ui-x/blob/ae6b73459488d7ee96ef4d9ce0dfe10b522b419c/packages/grid/_modules_/grid/components/toolbar/GridToolbarFilterButton.tsx#L88

Here I'd like to essentially add a valueFormatter to the filterOperator. So something like this:

```js
      filterOperators: [
        {
          label: 'Equals',
          value: 'equals',
          InputComponent: LocationSearch,
          valueFormatter: (value) => value.name || value.id
        },
      ],
```

Essentially I'm using an Autocomplete that selects an object as the value because I want the input to show the name, but the value used for actually filtering server side is the id.

**Comment by m4theushw** [comment]
The `valueFormatter` is only used for rendering, not on input fields. In this case, I would pass a `getOptionalLabel` prop to the Autocomplete to customize how each option is rendered.

**Comment by jpgilchrist** [comment]
@m4theushw thanks for the idea. I'll try that.
