### ISSUE TITLE
[DataGrid] Flickering on grid initialization when using `flex` columns

### ISSUE THREAD

**Issue by hoangbn** [mui-org/material-ui-x#3212]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When the table is first rendered, flex columns have some small fixed width, then they expand. This happens very quickly, so it looks like it flickers. 
The following gif shows the difference between navigating between 2 different tables (4.0.1 vs 5.0.1). The flickering one is v5

![image-loading-issue](https://user-images.githubusercontent.com/38968280/142279457-44bd6839-9228-466d-8470-2dd2764c06b8.gif)

### Expected behavior 🤔

It should not flicker (it did not do this before I migrated to v5 - 4.0.1)

### Steps to reproduce 🕹

The issue can be viewed in the official example sandbox https://codesandbox.io/s/3q8ue?file=/demo.js taken from https://mui.com/components/data-grid/columns/#fluid-width

Steps:

1. Reload the sandbox render area
2. See it flicker

**Comment by flaviendelangle** [comment]
An example in the version `5.0.0-beta.7` without the flickering
https://codesandbox.io/s/columnfluidwidthgrid-material-demo-forked-bvyg6?file=/package.json

I will have a look :+1:

**Comment by flaviendelangle** [comment]
We are debouncing the resize event to avoid resizing the grid dozens of time when resizing the window.

But debouncing even the 1st resize event mean that the initialization is debounced, causing a render to squeeze between the column init without there flex size (to now if we need a scrollbar) and there update with there flex size.

**Comment by ddolcimascolo** [comment]
Can this be related to my issue in #2945 ?

**Comment by flaviendelangle** [comment]
At first glance I don't think so but it's not impossible

**Comment by ddolcimascolo** [comment]
OK. Cause I do see the flicker too

**Comment by flaviendelangle** [comment]
The flicker probably have the same cause
