### ISSUE TITLE
MUI: useGridRootProps should only be used inside the DataGrid/DataGridPro component

### ISSUE THREAD

**Issue by kh-mubashar** [mui-org/material-ui-x#3228]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

getting this error as trying the data grid pro with the proper license

### Expected behavior 🤔

everything should be fine and work properly as like before the data grid pro version

### Steps to reproduce 🕹

Steps:

1. just added the license and imported the data grid pro
2. used the old data grid implementation 
3.
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Are you in the scenario of 2245 ? (trying to run an component from `x-data-grid` inside de `DataGridPro` or vice-versa.

**Comment by kh-mubashar** [comment]
Hi @flaviendelangle  yes we added  "@mui/x-data-grid": "^5.0.0-beta.2", and now shifting to datagrid Pro

**Comment by flaviendelangle** [comment]
So you have imports of `@mui/x-data-grid` for pages with the free version of the Grid.
And one import of `@mui/x-data-grid-pro` to start using the pro version. But this usage of `DataGridPro` does not have any `props.components` that would be using `@mui/x-data-grid` ?

**Comment by kh-mubashar** [comment]
yes @flaviendelangle

**Comment by kh-mubashar** [comment]
@flaviendelangle  thanks for the quick help I got it to work by completely removing the @mui/x-data-grid package from the app.
just had to update the license and remove the old package replace it with new and update the component

**Comment by viniciusalvess** [comment]
I have the same issue with the  "@mui/x-data-grid": "^5.11.1" package. I'm not using the pro version, and there are no pro version imports in the project and when I build the app with vite, it gives me the following error on the production error, but everything works well running the project on localhost.

Error:
MUI: GridErrorHandler - An unexpected error occurred. Error: MUI: useGridRootProps should only be used inside the DataGrid/DataGridPro component..  Error: MUI: useGridRootProps should only be used inside the DataGrid/DataGridPro component.

**Comment by flaviendelangle** [comment]
Hi,
Thanks for your contribution.

Could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) might be a good starting point.

Maybe on a new issue, because this error can hide very different problems :+1:

**Comment by viniciusalvess** [comment]
@flaviendelangle 

I was able to get the grid working after few tests. The issue is with the custom toolbar I'm using. When remove the custom toolbar everything works as expected. I'm adding the custom toolbar code below. I hope it helps to find the issue.


```
export function CustomToolbar(props) {
  return (
    <GridToolbarContainer>
      <Button variant="text" size={'small'} color={"success"} onClick={props.onNewClick}><Add/> New</Button>
      <GridToolbarColumnsButton/>
      {/*<GridToolbarFilterButton />*/}
      {/*<GridToolbarDensitySelector/>*/}
      <GridToolbarExport/>
    </GridToolbarContainer>
  );
}

<DataGrid 
  ...
  components={{
              Toolbar: CustomToolbar,
            }}
  componentsProps={{toolbar: {onNewClick: handleNewClick}}}
  ...
/>
```

**Comment by darrenbarklie** [comment]
I encountered this error when I had imported `DataGrid` and not `DataGridPro` whilst trying to use "X" features, resulting in this Uncaught Error. Aligning all imports from "@mui/x-data-grid-pro" resolved my issue.

**Comment by adamduren** [comment]
For us it turned out to be an issue in our `yarn.lock` file and was resolved by:

 1. Removing the data grid package
 1. Running `yarn`
 1. Adding the package back
 1. Running `yarn`

If that doesn't work check to make sure that you are not mixing imports from the various DataGrid packages (pro, premium, etc) and that the version numbers between `mui` and `DataGrid` are aligned.

**Comment by flaviendelangle** [comment]
Mixing import between pro / premium and community should not be an issue, as long as you always have the same version across the 3 packages :+1:

**Comment by dvZignuts** [comment]
> @flaviendelangle
> 
> I was able to get the grid working after few tests. The issue is with the custom toolbar I'm using. When remove the custom toolbar everything works as expected. I'm adding the custom toolbar code below. I hope it helps to find the issue.
> 
> ```
> export function CustomToolbar(props) {
>   return (
>     <GridToolbarContainer>
>       <Button variant="text" size={'small'} color={"success"} onClick={props.onNewClick}><Add/> New</Button>
>       <GridToolbarColumnsButton/>
>       {/*<GridToolbarFilterButton />*/}
>       {/*<GridToolbarDensitySelector/>*/}
>       <GridToolbarExport/>
>     </GridToolbarContainer>
>   );
> }
> 
> <DataGrid 
>   ...
>   components={{
>               Toolbar: CustomToolbar,
>             }}
>   componentsProps={{toolbar: {onNewClick: handleNewClick}}}
>   ...
> />
> ```

Have you got any solution for this thing
@flaviendelangle , @viniciusalvess

**Comment by flaviendelangle** [comment]
Hi,

I would advise you to open a new issue with a reproduction case
I'm not working on the grid anymore and with a new issue you will get help from the current members of the grid team :+1:
