### ISSUE TITLE
[DataGrid] No rows overlay overlaps with the header

### ISSUE THREAD

**Issue by hbabuka** [mui-org/material-ui-x#3229]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [x] I have tested the latest version

### Current behavior 😯

This overlapping happens in two scenarios:

### Scenario 1
`<DataGridPro rows={rows} columns={columns} autoHeight />`
- When there are no rows to be shown, the NoRowsOverlay component overlaps the header.
- The problem causing this is that the element with class `.MuiDataGrid-overlay` has `height: 0px`
Screenshot 1 :
![Screenshot 2021-11-19 at 18 32 00](https://user-images.githubusercontent.com/53868474/142666054-c6e540bc-2d5c-4802-b61a-44fbcf74ed82.png)
Screenshot 2:
![Screenshot 2021-11-19 at 18 33 08](https://user-images.githubusercontent.com/53868474/142666177-2fca26b5-ef06-4ecb-bbdb-4366da9228a1.png)
### Scenario 2
`<DataGridPro rows={rows} columns={columns} />`
- When there are no rows, the same problem as above occurs.
Screenshot 1:
![Screenshot 2021-11-19 at 18 34 29](https://user-images.githubusercontent.com/53868474/142666384-db645fe2-9b40-4602-ae6a-4f6b79362b0a.png)

**_The reason why I show these as two different scenarios is because it seems that what happens to work fine for one scenario, does not work fine for the other scenario in a particular environment and vice versa._**

### Expected behavior 🤔

No rows should take up `height: auto;` and be vertically centered and appear within `.MuiDataGrid-virtualScrollerContent`

### Scenario 1

Steps:

1. Use `<DataGridPro>` component with `autoHeight` prop and show it without rows so the default NoRowsOverlay could appear
2. You can see the same problem in this storybook: https://material-ui-x.netlify.app/storybook/?path=/story/datagridpro-test-dataset--no-rows-auto-height

### Scenario 2
https://codesandbox.io/s/datagridpro-v5-no-rows-ogh17

### Context 🔦

It is obvious here since it looks broken, I am trying to have No rows not overlapping the header and be centered inside the DataGrid body.

### Scenario 1

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 11.6
  Binaries:
    Node: 15.12.0 - ~/.nvm/versions/node/v15.12.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v15.12.0/bin/yarn
    npm: 7.6.3 - ~/.nvm/versions/node/v15.12.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.55  <--- happens in Chrome
    Edge: Not Found
    Firefox: 94.0.1 <--- happens in Firefox
    Safari: 15.1 <--- happens in Safari
```
</details>

**Dependencies:**
- MUI 5.1.1,
- React 17.0.0
- styled-components 5.3.3
- TypeScript 4.5.2

**Comment by ddolcimascolo** [comment]
Yep, looks like yet another regression linked to changes in resizing / size detection algorithm... Maybe the famous #3007?

See also #3233 that might be related

**Comment by flaviendelangle** [comment]
So me this problem was not introduced recently.
Here is an example in the `5.0.0-beta-5` which is one month old today: https://codesandbox.io/s/datagridpro-v5-no-rows-forked-ytnls

**Comment by flaviendelangle** [comment]
https://github.com/mui-org/material-ui-x/blob/master/packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx#L259

The virtualization have a behavior to save some space when there is no rows and `autoHeight` for the overlay.
But the overlay itself don't use the dimensions of its parent because it needs to behave correctly when there is scrollbars.
I will see to improve the behavior :+1:

**Comment by fryck** [comment]
My workaround 'til for now is:

```
const theme = createTheme(
  {
    components: {
      ...MuiDataGrid.components,
      MuiDataGrid: {
        styleOverrides: {
          root: {
            '.MuiDataGrid-overlay': {
              height: 'auto !important',
            },
          },
        },
      },
    },
  },
);
```

**Comment by flaviendelangle** [comment]
Do you have the issue on the last version of the DataGrid or a you stuck in a previous version ?

**Comment by EvgenyArtemov** [comment]
> 

Where do you export it from? I'm using Data-grid-pro and same problem, can't find

**Comment by flaviendelangle** [comment]
@MBilalShafi I let you that one :+1:

**Comment by anthonysapien** [comment]
Did this perhaps come back? I'm seeing a zero height overlay on the latest version. The workaround above works.

**Comment by Leehaeun0** [comment]
I'm using @mui/x-data-grid and found a solution, though it's not clean.

```
const theme = createTheme({
  components: {
    ...MuiDataGrid.components,
    MuiDataGrid: {
      styleOverrides: {
        root: {
          '.MuiDataGrid-overlayWrapper': {
            height: 'auto !important',
          },
          '.MuiDataGrid-overlayWrapperInner': {
            height: 'auto !important',
          },
        },
      },
    },
  },
});
```

**Comment by aentwist** [comment]
This has to be a bug. When the data grid is loaded with no rows, the thing collapses. When rows are added it expands for them, and when they are removed it appears to stay expanded. But forget about that second behavior, can it at least have a min-height of 1 row when it is given `rows={[]}`?

[codesandbox](https://codesandbox.io/p/sandbox/react-dev-forked-g6cpqx?file=%2Fsrc%2FApp.js%3A12%2C17&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clyou2fwu00072a6dsx1gemkk%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clyou2fwu00032a6dv37zjtif%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clyou2fwu00042a6d24o42emg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clyou2fwu00062a6dy27gmb59%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clyou2fwu00032a6dv37zjtif%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyou2fwu00022a6doohkkg8k%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A17%252C%2522endLineNumber%2522%253A12%252C%2522endColumn%2522%253A17%257D%255D%257D%255D%252C%2522id%2522%253A%2522clyou2fwu00032a6dv37zjtif%2522%252C%2522activeTabId%2522%253A%2522clyou2fwu00022a6doohkkg8k%2522%257D%252C%2522clyou2fwu00062a6dy27gmb59%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyou2fwu00052a6d9dn2j4md%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clyou2fwu00062a6dy27gmb59%2522%252C%2522activeTabId%2522%253A%2522clyou2fwu00052a6d9dn2j4md%2522%257D%252C%2522clyou2fwu00042a6d24o42emg%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clyou2fwu00042a6d24o42emg%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by azyouness** [comment]
The official MUI documentation explains how to customize the overlay height [here](https://mui.com/x/react-data-grid/layout/#overlay-height). This solution was working perfectly in previous versions, but after updating to the latest version (7.22.0), the `--DataGrid-overlayHeight` variable alone stopped working for me.

The workaround is to add an `overlayWrapper` height setting of 'auto'. 
Here's the working solution:

```jsx
styleOverrides: {
  root: {
    '--DataGrid-overlayHeight': '350px',
  },
  overlayWrapper: {
    height: 'auto',
  },
}
