### ISSUE TITLE
Material UI Data Grid Filter not working for float numbers

### ISSUE THREAD

**Issue by kh-mubashar** [mui-org/material-ui-x#3268]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Currently in the Pro version the material Ui is working with numberic filters but if we try to pass float value i.e **41.965** the filter doesnt work properly and return no record 
![image](https://user-images.githubusercontent.com/19286998/143030049-601e1203-b986-48dd-97a2-22152fd5fcd0.png)
 as we can see the record exists 
but as soon as we switch to equal sign to pin point the record the filter doesnt work
![image](https://user-images.githubusercontent.com/19286998/143030260-ee6e1e80-7104-48b8-b582-7b967b7a3484.png)
 is there any additional config required for the float numbers

### Expected behavior 🤔

the number type  definition in `GridColDef` should cover all the numeric types float and int

### Steps to reproduce 🕹

Steps:

1. add filters option
2. run filer on float time values
3.
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

32896

**Comment by m4theushw** [comment]
Could you provide a reproduction, I couldn't see the bug. [This **codesandbox.io** template](https://mui.com/r/issue-template-latest) _may_ be a good starting point.

The demo in https://mui.com/components/data-grid/demo/ has some columns with floating numbers (e.g. Unit Price). I tried to filter them using the equals operator and it worked.

**Comment by kh-mubashar** [comment]
sorry found the issue its just if you define some of your one custom filter options your essentially overwriting some of them just have to change that and it fixed the issue.
Thanks for the example that helped a lot
