### ISSUE TITLE
[Datagrid] isRowSelectable={false}  / disableSelectionOnClick={true}

### ISSUE THREAD

**Issue by hangryernest** [mui-org/material-ui-x#3272]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Cannot disable row selection on the datagrid using the following two props when using the keyboard (shift + space)
isRowSelectable={false}
disableSelectionOnClick={true}

### Expected behavior 🤔

above properties should work the same for mouse click and keyboard control
in this case the rows should not be selectable

### Steps to reproduce 🕹

https://codesandbox.io/s/disablerowselection-material-demo-forked-fu98t?file=/demo.js

Steps:
1. Click on the row with a mouse
2. No selection
3. Use the keyboard and move to another row
4. press space + keybaord
5. row will be selected

### Context 🔦

trying to disable row selection for table

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
```
  Don't forget to mention which browser you used.
  Browser:  Chrome - Version 96.0.4664.45 (Official Build) (64-bit)

  Output from `npx @mui/envinfo` goes here.
System:
    OS: Windows 10 10.0.22000
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22000.120.0), Chromium (96.0.1054.29)
  npmPackages:
    @emotion/react: 11.5.0 => 11.5.0 
    @emotion/styled: 11.3.0 => 11.3.0 
    @mui/core:  5.0.0-alpha.54 
    @mui/icons-material: 5.1.0 => 5.1.0 
    @mui/lab: 5.0.0-alpha.54 => 5.0.0-alpha.54 
    @mui/material: 5.1.0 => 5.1.0 
    @mui/private-theming:  5.1.0 
    @mui/styled-engine:  5.1.0 
    @mui/styles: 5.1.0 => 5.1.0 
    @mui/system:  5.1.0 
    @mui/types:  7.1.0 
    @mui/utils:  5.1.1 
    @mui/x-data-grid-pro: 5.0.1 => 5.0.1 
    @mui/x-license-pro:  5.0.1 
    @types/react:  17.0.1 
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2
```
</details>

### Order ID 💳 (optional)

319##

**Comment by alexfauquette** [comment]
Hi @hangryernest, I just realized that this is not a bug.

`isRowSelectable` is expecting a function which for a given row returns a boolean. If you set `isRowSelectable={() => false}` rows will not be selected by mouse or keyboard events.

About `disableSelectionOnClick` I think, this is more about allowing end-user to focus on a cell without modifying the selection, which is a problem that does not exist with keyboard interaction because arrows move the focus without modifying the selection.

Does it solve your issue?

**Comment by hangryernest** [comment]
HI @alexfauquette 

I'll give this a try and let you know. Thank you for looking into this
