### ISSUE TITLE
[DataGrid] Setting `autoHeight` prop or parent element style prop `height` causes potential memory leak

### ISSUE THREAD

**Issue by rtetelbaum** [mui-org/material-ui-x#3276]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Observed in x-data-grid 5.0.1 with material 5.2.0 and 5.1.0, Chrome  96.0.4664.45

When setting `autoHeight={true}` on DataGrid component such as:

```
<div id="grid-parent">
    <DataGrid rows={rows} columns={columns} autoHeight={true} />
</div>
```

-OR-

Setting a dynamic height on the parent element such as:

```
<div id="grid-parent" style={{ height: 'calc(100vh - 90px)' }}>
    <DataGrid rows={rows} columns={columns} />
</div>
```

Then immediately upon resizing the browser window, React StrictMode warning appears in browser console:

"Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function."

Removing the autoHeight prop, or removing the dynamic calculated height on the parent div, the memory leak no longer occurs.

Changing the parent div height to a static value e.g. ` style={{ height: 300 }}` will cause the error, but only when the window is resized to a point where the bottom window border begins to touch the bottom grid border which enables the horizontal scroll for the entire window.

While this warning only appears in React StrictMode (and therefore only in development mode) it would still presumably be a problem in production even though the warning is not present, which is expected behavior since StrictMode warnings are meant to indicate problems to the developer.

### Expected behavior 🤔

Setting the autoHeight prop on DataGrid or setting a height in the inline style prop of the DataGrid parent div element should not cause a React state update on an unmounted component memory leak warning.

### Steps to reproduce 🕹

Steps:

1. Set autoHeight prop on DataGrid component
2. OR set inline style prop with height on DataGrid parent div element
3. Resize window by dragging bottom window border
4. If using static value for height in inline style, resize window by dragging bottom window border up past DataGrid bottom border
5. React StrictMode warning in console appears

### Context 🔦

Trying to accomplish setting dynamic height to DataGrid in order to auto resize DataGrid as user resizes their browser window. While the feature does work, underlying state and memory management seems to be affected.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
Browser Used: Chrome  96.0.4664.45

    System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 96.0.4664.45
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.29)
  npmPackages:
    @emotion/react: ^11.6.0 => 11.6.0
    @emotion/styled: ^11.6.0 => 11.6.0
    @mui/base:  5.0.0-alpha.56
    @mui/icons-material: ^5.2.0 => 5.2.0
    @mui/material: ^5.2.0 => 5.2.0
    @mui/private-theming:  5.2.0
    @mui/styled-engine:  5.2.0
    @mui/system:  5.2.0
    @mui/types:  7.1.0
    @mui/utils:  5.1.1
    @mui/x-data-grid: ^5.0.1 => 5.0.1
    @types/react:  17.0.35
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
```
</details>

**Comment by DanailH** [comment]
Hi @rtetelbaum, thanks for raising this!
Please provide a minimal reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This codesandbox.io template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) _may_ be a good starting point. Thank you!

That being said I have noticed the warning as well but having a codesadbox example will be very beneficial.

**Comment by rtetelbaum** [comment]
Hi Danail,

I modified the Codesandbox (see line 21 and line 27), however does Codesandbox run React in development mode? The warning will only by visible in console in development mode. Either way I can't seem to reproduce it in Codesandbox.

https://codesandbox.io/s/datagrid-v5-quick-start-forked-t2sms

**Comment by paulo-propylon** [comment]
This also happens when the parent has a dynamic width. It's the only thing blocking us from migrating our tables to the datagrid.

**Comment by m4theushw** [comment]
@paulo-propylon Can you see the warning when using v5.2.1? In #3310 I proposed a modification to avoid this message. Notice that it may still occur but it's not a memory leak like React says, the subscription that causes the warning will be cleaned at some point.

**Comment by paulo-propylon** [comment]
@m4theushw sorry for the late reply. Yes, I can still see the error using v5.2.1 

I was able to reproduce it [here](https://codesandbox.io/s/datagrid-v5-quick-start-forked-yy9o8).
The grid is on line 172.

The grid lives inside a drawer, so wait until the data "loads" (mocking with an useEffect) and expand the drawer. You will see the memory leak warning in the console. The same happens if you resize the window, it's not necessarily linked to the drawer.

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at eval (https://yy9o8.csb.app/node_modules/@mui/x-data-grid/index-esm.js:3756:21)
```

**Comment by m4theushw** [comment]
@paulo-propylon I could also see the warning in your example. It may still occur but now it's not something that will always occur. For instance, I opened it in Chrome (in Edge I always see the warning) and the warning appeared a couple of times but in others no. It depends on when the browser decides to run the garbage collector. To be clear, it's not a real memory leak and you can upgrade to DataGrid normally. To never display the warning, we would have to sacrifice the capability of the grid to synchronously subscribe to internal events, which could cause other side effects.

![pjhwpRXlef](https://user-images.githubusercontent.com/42154031/147796511-bab4b040-fa5e-481a-b2a6-603abb79b58b.gif)
