### ISSUE TITLE
Expandable row

### ISSUE THREAD

**Issue by jmcpeak** [mui-org/material-ui-x#3279]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

The new data grid looks great, our use case is that when a user finds the row of data there interested in, they can optionally "expand the row" (imagine that selecting the row expands an your Accordion component) to see further details about the row. We started by having the row click open a temporary Drawer with the more details, but users prefer staying within the context of the table.

**Comment by flaviendelangle** [comment]
@jmcpeak I think this resonates a lot with #211 
In which case it should be implemented in the coming months and be released on the pro plan.
