### ISSUE TITLE
Datagrid button not found by react test library

### ISSUE THREAD

**Issue by datasmithadvtech** [mui-org/material-ui-x#3280]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

- using rendercell to render buttons in datagrid
- unit tests cannot find buttons using react test library 

### Expected behavior 🤔

react test library should find buttons so we can fire events and validate behavior

### Steps to reproduce 🕹

Steps:

- using rendercell to render buttons in datagrid
- write unit tests to find buttons using react test library 
- fire events and validate behavior

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
Could you detail what you're trying to assert? A test case example would be helpful.

**Comment by oliviertassinari** [comment]
I'm jumping ahead to assume a duplicate of #1151. react test library makes me believe @datasmithadvtech is using JSDOM, which has no layout support, hence failing with the virtualization.
