### ISSUE TITLE
x-data-grid data-colindex = 0 is not showing on scroll 

### ISSUE THREAD

**Issue by mvmidhun92** [mui-org/material-ui-x#3284]
- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When there is a horizontal scroll included data-col index = 0 (first column) is not showing if the horizontal scroll is on the far-right position of Datagrid. which result in visually breaking the grid column alignment 

![issue2](https://user-images.githubusercontent.com/95064665/143528281-4a60dd44-476f-4c60-a8d8-f6f4b16ffc71.jpg)
![issue1](https://user-images.githubusercontent.com/95064665/143527556-3b93750a-3049-49c6-9e47-f7b9351cf0cd.JPG)

### Duplicates

Also if I am in 16–20 of 75 in-page navigation and then I redefine my search with new data, the grid pagination will change to 16–20 of 153 instead of resetting the pagination to 1–5 of 153

Current version I am using is
"@mui/x-data-grid": "^5.0.1"
"@mui/material": "^5.1.1",

### Expected behavior 🤔

Always show all columns even in the scroll. 
Also on the new grid new data reload the pagination should reset to first page ,

### Steps to reproduce 🕹

Steps:

1. Grid should have horizontal scroll, Pass data on button click, before binding the data to grid go to the far right of the grid using the horizontal scroll.
2. You can see last column's data will bind to one column before. because on inspect element could see in such cases data-colindex = 0 is missing. but on scroll back to left data-colindex = 0 re-appears again

2nd issue:
1. upon new search pagination page is not resetting back to first page

### Context 🔦

From a user perspective, the grid will cause discomfort to user

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 96.0.4664.45
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.34)

</details>

**Comment by m4theushw** [comment]
> When there is a horizontal scroll included data-col index = 0 (first column) is not showing if the horizontal scroll is on the far-right position of Datagrid. which result in visually breaking the grid column alignment

This could be understood as the normal behavior of the virtualization. Depending on the scroll position, different DOM elements are rendered. However, looking at the screenshot I see that the last column is misaligned. Could you provide a example so we can reproduce this bug? [This **codesandbox.io** template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) _may_ be a good starting point.

> Also if I am in 16–20 of 75 in-page navigation and then I redefine my search with new data, the grid pagination will change to 16–20 of 153 instead of resetting the pagination to 1–5 of 153

Are you using the `rowCount` prop? It could be related to https://github.com/mui-org/material-ui-x/issues/2321.
