### ISSUE TITLE
[DataGrid] Error handling overlay not showing correctly.

### ISSUE THREAD

**Issue by Arisha** [mui-org/material-ui-x#3286]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The error handling overlay is positioned wrongly upon refresh of the page.
![image](https://user-images.githubusercontent.com/76226338/143556363-dafb977e-f2d9-4be4-9de2-a86ec7002563.png)

### Expected behavior 🤔

Error handling overlay to be positioned in the middle/center

### Steps to reproduce 🕹

Steps:

1. add error prop to the DataGrid Component
2. refresh the page

CodeSandbox: https://codesandbox.io/s/datagrid-v5-quick-start-forked-zlz66?file=/src/App.tsx

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Duplicates #3229, it will be fixed in the next release
