### ISSUE TITLE
[DataGrid] - singleSelect is calling the preProcessEditCellProps twice. The second call has wrong value.

### ISSUE THREAD

**Issue by mfaheemakhtar** [mui-org/material-ui-x#3304]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

singleSelect column type is calling the preProcessEditCellProps twice. The second call has invalid value, which overwrites the new selection value. Probably blur event?

### Expected behavior 🤔

All calls should have the new selected value.

### Steps to reproduce 🕹

Steps:

1. Add a singleSelect type column
2. Use preProcessEditCellProps

Example:
https://codesandbox.io/s/datagridpro-v5-quick-start-forked-pxc4e?file=/src/App.tsx

### Context 🔦

I am trying to validate the new value of singleSelect from server. Should commit the value only if the server responds with 200.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

#30063

**Comment by m4theushw** [comment]
It should be called once, when the value is changed. The problem is that the `api.setEditCellValue` below is calling the promise, when `editCellPropsChange` is published, but it's not waiting for its completion. Then, immediately after that, `api.commitCellChange` is called triggering the promise again, but now waiting for it to be resolved. The second value is wrong because it was called without waiting for the first promise.

https://github.com/mui-org/material-ui-x/blob/d8d7cf98af58e3369f9accb72223bcc808f3ebc7/packages/grid/_modules_/grid/components/cell/GridEditSingleSelectCell.tsx#L73-L75

We need to improve the interaction of the editing feature with a server. I made some proposals in https://github.com/mui-org/material-ui-x/issues/3101#issuecomment-963107684 and #3304 is another thing we need to consider. I think we should fix `api.setEditCellValue` to return a promise, so when it resolves, we know that the props were processed. It may require `editCellPropsChange` to be removed (in v6), or a method is added to not impact existing users.

**Comment by bryce0516** [comment]
same here

**Comment by mfaheemakhtar** [comment]
@m4theushw , is there any ETA or temp workaround?

**Comment by m4theushw** [comment]
No ETA yet because it may require breaking changes. As workaround, `<DataGridPro editMode="row" />` can be used instead. That way, it calls the callback with the right value.

**Comment by mfaheemakhtar** [comment]
Row editing is not something we can use. I believe this should be prioritized as it is affecting of the core features.

Anyway, I have written a small workaround which fixes the second call value, if the second call is made in 50ms (just a random number). Right now, I don't know if it has any side-effects but its better than using wrong values.

**Workaround function:**

```ts
export const getDataGridValueFactory = (fields: string[]) => {
  const ignore: { [key: string]: { time: number; value: any } } = {};

  return (field: string, value: any): any => {
    if (!fields.includes(field)) {
      return value;
    }

    if (ignore[field] && Date.now() - ignore[field].time < 50) {
      return ignore[field].value;
    } else {
      ignore[field] = { time: Date.now(), value };
      return ignore[field].value;
    }
  };
};
```

**onEditCell:**

```ts
const onEditCell = (
    field: string,
    { props, row }: GridPreProcessEditCellProps
  ) =>
    new Promise<GridEditCellProps>((resolve) => {
      const value = getDataGridValue(field, props.value);

      clearTimeout(promiseTimeout);
      clearTimeout(keyStrokeTimeoutRef.current);

      keyStrokeTimeoutRef.current = setTimeout(async () => {
        try {
         // API call here

          resolve({ ...props, error: false });
        } catch (error: any) {
          enqueueSnackbar(error.message, { variant: "error" });
        }
      }, 100);
    });
```

**Comment by m4theushw** [comment]
I opened #3612 with a proposal to fix this bug. To make `preProcessEditCellProps` be called only once by default, it requires a breaking change. To avoid that, there would be a new prop which needs to be enabled to prevent the commit while processing the props.

CodeSandbox with the fix: https://codesandbox.io/s/datagridpro-v5-quick-start-forked-rzyrl?file=/src/App.tsx

I would like a feedback if it solves the problem raised here.

**Comment by Algie37** [comment]
@m4theushw I have implemented your above workaround and enabled <DataGrid experimentalFeatures={{ preventCommitWhileValidating: true }} /> as below `<DataGrid
        rows={rows}
        columns={columns}
        editMode='row'
        rowModesModel={rowModesModel}
        onRowEditStart={handleRowEditStart}
        onRowEditStop={handleRowEditStop}
        processRowUpdate={processRowUpdate}
        components={{
          Toolbar: EditToolbar,
          NoRowsOverlay: CustomNoRowsOverlay,
        }}
        componentsProps={{
          toolbar: {setRows, setRowModesModel},
        }}
        experimentalFeatures={{newEditingApi: true, preventCommitWhileValidating: true}}
      />`
The singleSelect still calls twice though as screensot in console. Please assist. 
![2022-07-30 08_13_23-MORTMAN and 36 more pages - Personal - Microsoft​ Edge](https://user-images.githubusercontent.com/16317334/181875818-22c4d337-8851-4300-b0d0-ee2cb554fd15.png)

**Comment by m4theushw** [comment]
@Algie37 Since this issue was opened, we released a new editing API fixing many bugs, including this one. Could you try using it? https://mui.com/x/react-data-grid/editing/

**Comment by mainfraame** [comment]
@m4theushw i'm also experiencing this issue with using the latest editing api (as suggested).
