### ISSUE TITLE
[DataGrid] Can't pick February in `date` column

### ISSUE THREAD

**Issue by ProfHercules** [mui-org/material-ui-x#3305]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If you have a "date" type column for the DataGrid, selecting any day in February (for any year), returns the same day in March instead.

Basically the same as this issue: #3061 
I posted a comment there, but I'm not sure if "Closed" issue actually receive any attention so I'm making a new issue.

### Expected behavior 🤔

Selecting a date returns the selected date.

### Steps to reproduce 🕹

Steps:

1. Add a "date" type column to any DataGrid.
2. Try picking a day in February

Check out [this](https://codesandbox.io/s/sweet-pasteur-dtjx6?file=/src/App.js) codesandbox.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Tested on Safari & Chrome.

  System:
    OS: macOS 12.0.1
  Binaries:
    Node: 14.17.5 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.1.4 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Edge: Not Found
    Firefox: Not Found
    Safari: 15.1
```
</details>

**Comment by alexfauquette** [comment]
Thanks for reporting this bug. Funny story, tomorrow the bug will be resolved even if I do nothing. Look at the code bellow:

```js
newParsedDate = new Date();
newParsedDate.setFullYear(Number(year));
newParsedDate.setMonth(Number(month) - 1);
newParsedDate.setDate(Number(day));
newParsedDate.setHours(0, 0, 0, 0);
```

The variable `newParsedDate` is initialized at the date of today (the 30th of November). Then, the year and the month are set. So it is the 30th of February. Since it does not exist, the `Date` object moves to the next month.

I propose to solve this by using 
```js
newParsedDate = new Date(Number(year), Number(month) - 1, Number(day)); 
```

**Comment by flaviendelangle** [comment]
Be careful with `new Date(year)` when `year < 1900`
`new Date(1)` creates a date in `1901`.

But you can do something like:

```ts
const newParsedDate = new Date(Number(year), Number(month) - 1, Number(day)); 
newParsedDate.setFullYear(Number(year));
```

**Comment by alexfauquette** [comment]
I do not see the problem. As long a the input year is larger than 100, it will be ok, so the `setFullYear` will not change anything.

For years before 100, I'm not sure it is important

Is there a reason why we do not use the input starting to set the Date, like that: `new Date("0099-01-01")` This would solve the problem for dates before 100

**Comment by flaviendelangle** [comment]
> For years before 100, I'm not sure it is important

It was causing bugs when editing because to type 1999 for instance, you type `1` then `19` then `199` then `1999`. And it was not working correctly with the intermediary states.

The original code was done before my arrival so I honestly don't know why we don't use the string notation.

**Comment by ProfHercules** [comment]
> I do not see the problem. As long a the input year is larger than 100, it will be ok, so the `setFullYear` will not change anything.
> 
> For years before 100, I'm not sure it is important
> 
> Is there a reason why we do not use the input starting to set the Date, like that: `new Date("0099-01-01")` This would solve the problem for dates before 100

Using this suggestions I made [this](https://codesandbox.io/s/magical-zeh-w9lkx?file=/src/App.js) codesandbox. 
I'm using `new Date("0000-01-01")` instead of `new Date()` produces consistent results and requires minimal changes.

Is there a difference between `new Date("0099-01-01")` and `new Date("0000-01-01")` that I'm not realising?

**Comment by alexfauquette** [comment]
@flaviendelangle Ok, this does not occur anymore because the value is `valueState.formatted` which is not modified (it's `event.target.value`)

I think the easiest way is to trust native `input` and `Date` as follows.
```
const [date, time] = newFormattedDate.split('T');
newParsedDate = new Date(`${date}T00:00:00`);
```

@ProfHercules as long as you initialize a date with day 1, it will solve the bug. The year does not matter.
