### ISSUE TITLE
[DataGrid]Can't define 'DataGrid' 'components' property of createTheme

### ISSUE THREAD

**Issue by skrg-kotani** [mui-org/material-ui-x#3322]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I try to createTheme 'MuiDataGrid'
https://mui.com/api/data-grid/data-grid/
please show below code.

```
export const theme = createTheme({
  components: {
    MuiDataGrid: {
      styleOverrides: {
        cell: {
          lineHeight: '1.5rem',
          whiteSpace: 'normal',
          wordBreak: 'break-all'
        }
      }
    }
  }
})
```

But VSCode shows  this  error!!
`Object literal may only specify known properties, and 'MuiDataGrid' does not exist in type 'Components`

version per package

```
"@emotion/react": "^11.7.0",
"@emotion/styled": "^11.6.0",
"@mui/icons-material": "^5.2.0",
"@mui/material": "^5.2.1",
"@mui/x-data-grid": "^5.0.1",
```

please give me some advice or new information!

### Expected behavior 🤔

I can define  createTheme 'MuiDataGrid'!

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
Did you use the `themeAugmentation` to let our package expand the interface from the core ?

https://mui.com/components/data-grid/getting-started/#typescript

**Comment by junhuhdev** [comment]
@flaviendelangle how does that work for non-typescript projects? im having the same issue

**Comment by skrg-kotani** [comment]
@flaviendelangle oh...Thank you very match!  my issue has been resolved!

**Comment by flaviendelangle** [comment]
Perfect

For non-typescript projects, which IDE are you using @junhuhdev ?

**Comment by junhuhdev** [comment]
@flaviendelangle i am using intelij latest version

**Comment by junhuhdev** [comment]
also when i go inside the MuiDataGrid I see this highlighted with red 

![image](https://user-images.githubusercontent.com/45692017/144604487-7a497670-d3be-4c65-8d80-3ed66ad671fc.png)
