### ISSUE TITLE
[docs] DataGridPro link (to API) does not exist

### ISSUE THREAD

**Issue by gustavozirbes** [mui-org/material-ui-x#3324]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Pointing to https://mui.com/data-grid/data-grid-pro/ instead of https://mui.com/api/data-grid/data-grid-pro/.

### Expected behavior 🤔

The link should point to https://mui.com/api/data-grid/data-grid-pro/.

### Steps to reproduce 🕹

Steps:

1. Go to https://mui.com/components/data-grid/#overview
2. Click on **DataGridPro** link

**Comment by flaviendelangle** [comment]
Thank you for your report, I'll fix this in the next release :+1:
