### ISSUE TITLE
[DataGridPro] Unable to save row value when using `preProcessEditCellProps` and external buttons

### ISSUE THREAD

**Issue by svo35** [mui-org/material-ui-x#3333]
### Order ID 💳

33396

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I'm trying to edit the datagrid with external buttons as described here - https://mui.com/components/data-grid/editing/#control-with-external-buttons but when I add a simple validation to one of the columns using preProcessEditCellProps, the row doesn't get saved after editing but if I remove the validation, it works just fine. Here is a code sandbox link for example - https://codesandbox.io/s/fullfeaturedcrudgrid-material-demo-forked-bn3xr?file=/demo.js

### Your environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

**Comment by DanailH** [comment]
Hi, @svo35 thanks for raising this. Indeed there is a problem with the `preProcessEditCellProps` callback.
I also noticed another weird behavior - if you have the `preProcessEditCellProps` set for a specific column and you try and add a new row to the `DataGrid` only the value of the column that has `preProcessEditCellProps` is being saved. Also if the value of the newly added row doesn't pass the validation an empty row is inserted. It's reproducible on the same demo.

**Comment by svo35** [comment]
@DanailH - Thanks for looking into this. Is there any other way to validate row data built into the DataGrid?

**Comment by DanailH** [comment]
I don't think there is but to be sure I'm tagging @m4theushw as he is more knowledgeable about that feature.

**Comment by m4theushw** [comment]
Sorry for the delay. `commitRowChange` returns a promise when `preProcessEditCellProps` is defined. You need to wait for it to be resolved before changing the row mode. I'll fix this demo to make easier to add validation to it.

```diff
diff --git a/docs/src/pages/components/data-grid/editing/FullFeaturedCrudGrid.tsx b/docs/src/pages/components/data-grid/editing/FullFeaturedCrudGrid.tsx
index 2cde5ceef..e78b8f259 100644
--- a/docs/src/pages/components/data-grid/editing/FullFeaturedCrudGrid.tsx
+++ b/docs/src/pages/components/data-grid/editing/FullFeaturedCrudGrid.tsx
@@ -122,13 +122,15 @@ export default function FullFeaturedCrudGrid() {
     apiRef.current.setRowMode(id, 'edit');
   };
 
-  const handleSaveClick = (id) => (event) => {
+  const handleSaveClick = (id) => async (event) => {
     event.stopPropagation();
-    apiRef.current.commitRowChange(id);
-    apiRef.current.setRowMode(id, 'view');
+    const isValid = await apiRef.current.commitRowChange(id);
+    if (isValid) {
+      apiRef.current.setRowMode(id, 'view');
 
-    const row = apiRef.current.getRow(id);
-    apiRef.current.updateRows([{ ...row, isNew: false }]);
+      const row = apiRef.current.getRow(id);
+      apiRef.current.updateRows([{ ...row, isNew: false }]);
+    }
   };
 
   const handleDeleteClick = (id) => (event) => {
```
