### ISSUE TITLE
[docs] Codesandbox demos using the `Button` component are no working with `@mui/material@v5.2.3`

### ISSUE THREAD

**Issue by DanailH** [mui-org/material-ui-x#3371]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

As far I can see demos that use the `Button` component from the Core are broken after the latest release of 5.2.3 from the core.

https://codesandbox.io/s/hb6rm?file=/demo.tsx

### Expected behavior 🤔

Demos should work as expected.

**Comment by ZeeshanTamboli** [comment]
Related to a util function (resolveProps) added in https://github.com/mui-org/material-ui/pull/29982. Not sure what's the fix.

**Comment by m4theushw** [comment]
The `@mui/x-data-grid-pro` dependency is pointing to `next` which resolves with the latest beta. I can't see any error with the latest stable release. See https://codesandbox.io/s/fullfeatureddemo-material-demo-forked-qo1sn?file=/demo.tsx

Can we close this issue?

**Comment by oliviertassinari** [comment]
Similar to #3389.
