### ISSUE TITLE
[DataGridPro] Close the filter panel when a filter is added

### ISSUE THREAD

**Issue by simbahandiane** [mui-org/material-ui-x#3373]
After filtering the DataGridPro, the filter pop-up doesn't hide. Is there a configuration/way to hide the filter menu after loading the result.

![image](https://user-images.githubusercontent.com/24405994/145043165-3ff927d2-a502-459c-a0c2-6553e094df85.png)

**Comment by DanailH** [comment]
Hi, @simbahandiane thanks for raising this!

The filter panel doesn't auto-close because the user may want to add multiple filters. That being said if you want to hide it after a filter is added you can use the `onFilterModelChange` to react to the change and then use the `apiRef.current.hideFilterPanel()` to hide it manually. Hope this helps.

**Comment by simbahandiane** [comment]
Is there a way to relocate/reposition the filter panel?

**Comment by DanailH** [comment]
You can provide your own `FilterPanel` and overwrite the one that we have out of the box by using the `components` prop. You can find more about how to do that as well as getting access to specific component props here https://mui.com/components/data-grid/components/#getting-props

**Comment by m4theushw** [comment]
Here there's an example of how to position the filter panel next to the "Filter" button: https://github.com/mui-org/material-ui-x/issues/3155#issuecomment-973180753

**Comment by simbahandiane** [comment]
Thanks for pointing out the solution. I'll check it.

**Comment by simbahandiane** [comment]
I've tried using the solution that you've given then add anchorOrigin and transformOrigin but didn't work as expected. Can you confirm if anchorOrigin and transformOrigin is not working on Data Grid's componentsProps?

**Comment by m4theushw** [comment]
@simbahandiane The props passed to `componentsProps.panel` are spread into a component based on the [Popper](https://mui.com/api/popper/), not a Popover. The props `anchorOrigin` and `transformOrigin` don't exist on it. You can use `placement` to control the position, see https://github.com/mui-org/material-ui-x/blob/0b23cdd82d671fa7be52f9622de8cfe0ef1cd747/packages/grid/_modules_/grid/components/panel/GridPanel.tsx#L77

**Comment by simbahandiane** [comment]
I'll be closing this one. I've found a solution for the repositioning of the Panel. Thank you!
