### ISSUE TITLE
[DataGrid] Setting edit cell value to anything results in undefined value

### ISSUE THREAD

**Issue by VicHofs** [mui-org/material-ui-x#3376]
### Duplicates

- [x] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Using the DataGrid API to update cell value in custom edit cell results in the cell's value being set to `undefined`. This does not happen if directly passing `value` from `GridRenderEditCellParams` to the `setEditCellValue` API method but still happens if the value passed is identical to that `value` parameter.

### Expected behavior 🤔

The edited cell value should be set to the value passed into the `value` parameter of the `setEditCellValue` API method.

### Steps to reproduce 🕹

1. Create a new `DataGrid` component and set up a column with cells that hold an `Array` type value, e.g. `[{weekday: 0, openingTime: '08:00', closingTime: '20:00'}]`
2. Create a custom component for editing the cell value that implements the Grid API method `setEditCellValue` in its change handler
3. Interact with the component to change its value and call the `setEditCellValue` method

[Live example here](https://codesandbox.io/s/data-grid-set-cell-value-issue-example-m8oek)

### Context 🔦

I am attempting to modify data of a weekday schedule array through a custom component to make the process more readable. I want to keep the data in this same format throughout the program to streamline integration with my API.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.22000
  Binaries:
    Node: 15.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 96.0.4664.93
    Edge: Spartan (44.22000.120.0), Chromium (95.0.1020.40)
  npmPackages:
    @emotion/react: ^11.4.1 => 11.4.1
    @emotion/styled: ^11.3.0 => 11.3.0
    @mui/core:  5.0.0-alpha.51
    @mui/icons-material: ^5.0.4 => 5.0.4
    @mui/material: ^5.0.4 => 5.0.4
    @mui/private-theming:  5.0.1
    @mui/styled-engine: ^5.0.1 => 5.2.0
    @mui/styles: ^5.0.1 => 5.0.1
    @mui/system:  5.0.4
    @mui/types:  7.0.0
    @mui/utils:  5.0.1
    @mui/x-data-grid: ^5.0.0-beta.4 => 5.0.0-beta.4
    @types/react: ^17.0.0 => 17.0.29
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    styled-components: ^5.3.1 => 5.3.1
    typescript: ^4.1.2 => 4.4.4
```

I am using Windows 11, not sure why that isn't reflected accurately. I am running the app on an instance of Microsoft Edge.
</details>

**Comment by DanailH** [comment]
Hi, @VicHofs thanks for raising this.

I played a bit with your demo and maybe I don't understand the problem, but I what you are trying to do is achievable by just updating what you are passing to the `setEditCellValue` API `api.setEditCellValue({ id, field, value: newValue });`.
Also, I see you are using a `renderCell` where for your particular use case a `valueFormatter` is better suited.
You can check the updated demo here: https://codesandbox.io/s/data-grid-set-cell-value-issue-example-forked-or3rw?file=/src/Demo.tsx:3186-3239

**Comment by VicHofs** [comment]
Sorry about this. I was using newValue directly through the shorthand property, which led to an object with no `value` key but a `newValue` key being passed as the function argument.

Just so this issue isn't _completely_ pointless, as a side note, could it not be beneficial to have the object keys as parameters instead to avoid this sort of thing?
