### ISSUE TITLE
[DataGrid] The grid not scrollable after shift select multiple rows

### ISSUE THREAD

**Issue by xiaoyu-tamu** [mui-org/material-ui-x#3397]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Steps:

1.https://mui.com/components/data-grid/demo/
2.shift select multiple rows
3.scroll the grid

### Context 🔦

v 5.2.0

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
Hi @xiaoyu-tamu I do not manage to reproduce your bug. Please, could you do a recording, or at least provide a precise list of actions such as "click here, pressed this key, ..."

The browser you're using can also be useful to catch such a bug

file:///home/alexandre/Vid%C3%A9os/Screencast%20from%2013-12-2021%2018:04:26.webm.mp4

**Comment by xiaoyu-tamu** [comment]
Sorry about that

https://user-images.githubusercontent.com/33362998/145868066-dbd2e53f-1844-4cdf-8817-3fd8115a869f.mov

Chrome Version 96.0.4664.93 (Official Build) (arm64)
OS: macOS Monterey 12.0.1

Hope this help

**Comment by xiaoyu-tamu** [comment]
not sure if this is related to checkbox focus.

https://github.com/mui-org/material-ui-x/issues/3382
https://github.com/mui-org/material-ui-x/issues/3383

**Comment by xiaoyu-tamu** [comment]
> Hi @xiaoyu-tamu I do not manage to reproduce your bug. Please, could you do a recording, or at least provide a precise list of actions such as "click here, pressed this key, ..."
> 
> The browser you're using can also be useful to catch such a bug
> 
>  Screencast.from.13-12-2021.18.04.26.webm.mp4

I don't have linux, can you try to scroll down the grid 5~10 rows and try the above steps?

**Comment by m4theushw** [comment]
@oliviertassinari and @DanailH could you try to reproduce the bug on macOS?

**Comment by alexfauquette** [comment]
Thanks @xiaoyu-tamu 

I can reproduce it on ubuntu, To do so I have to scroll slowly, and far enough to make the focus cell disappear. I will have a look

**Comment by alexfauquette** [comment]
@m4theushw The problems seem to come from virtualization. In `getRows()`, the array index is used as a key. Then, when the range of rows is modified, it gets a new key and so React considers it as a new component. Leading to a new focus event that triggers the scroll when the cell is hidden.

Is there a reason for not using `rowId` as a key?

**Comment by m4theushw** [comment]
@alexfauquette I fail to understand but it's running the effect below again, even if the focused element is not visible anymore. Each time it runs, `input!.focus()` is called which scrolls the viewport to make it visible. This same problem was occurring in #2558.

https://github.com/mui-org/material-ui-x/blob/1ed95e17aa46cd1298957b428d2d3b3173acf673/packages/grid/_modules_/grid/components/columnSelection/GridCellCheckboxRenderer.tsx#L53

**Comment by alexfauquette** [comment]
Yes, but why this useEffect is called? I think it's because the virtualization buffer changed.

### Example
Let imagine, the focused cell is at index 5 in the buffer. I scroll, and at some point, the buffer is updated such that now the selected row is at the index 1 in the buffer.

React trust your keys (which are the indexes), so it says: "I already have a row with key 1, but all its props have changed. let update all the components inside" And then the CellCheckbox sees its `hasFocus` prop modified from `false to `true`

### Profiler

I had a look at the profiler to see why rows are updating: There is a hook changed, and multiple props update:

- row
- rowId
- renderedColumns
- index

If I replace `key={index}` by `key={rowId}` the only props that changed is `renderedColumns` because it is obtained from `slice`

### Solution

By setting `key={rowId}` React manages to match Row components to the correct props even when the buffer order is modified. Such that the `SelectCheckBox` which has focus stay the same

**Comment by m4theushw** [comment]
I used `key={index}` to avoid creating new elements and to reuse the ones already in the DOM. However, it seems that this doesn't make any difference in performance. Do you want to proposes the change? #3455 can be closed later.

```diff
diff --git a/packages/grid/_modules_/grid/components/GridRow.tsx b/packages/grid/_modules_/grid/components/GridRow.tsx
index fa2c282e3..9eb8d04f3 100644
--- a/packages/grid/_modules_/grid/components/GridRow.tsx
+++ b/packages/grid/_modules_/grid/components/GridRow.tsx
@@ -205,7 +205,7 @@ function GridRow(props: React.HTMLAttributes<HTMLDivElement> & GridRowProps) {
 
     cells.push(
       <rootProps.components.Cell
-        key={i}
+        key={column.field}
         value={cellParams.value}
         field={column.field}
         width={column.computedWidth}
diff --git a/packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx b/packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx
index 9f2cc71df..d15c83ee3 100644
--- a/packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx
+++ b/packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx
@@ -274,7 +274,7 @@ export const useGridVirtualScroller = (props: UseGridVirtualScrollerProps) => {
 
       rows.push(
         <rootProps.components.Row
-          key={i}
+          key={id}
           row={model}
           rowId={id}
           rowHeight={rowHeight}
```
