### ISSUE TITLE
[DataGrid] Compatibility with Webpack 3

### ISSUE THREAD

**Issue by jmorc** [mui-org/material-ui-x#3421]
### Order ID 💳

20020

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

We upgraded from XGrid (@material-ui/x-grid 4.0.0-alpha.24) to DataGrid (@mui/x-data-grid 5.0.1) and found that the DataGrid component throws a console error and fails to render in one of our applications.  It is a legacy application bundled with webpack 3.   We have DataGrid running without error on other apps bundled with webpack 4. I cannot find any report of this issue, my question is whether DataGrid incompatibility with webpack 3 is a known issue?

### The problem in depth 🔍

The issue is explored in this test repo: https://github.com/jmorc/webpack-datagrid

When using DataGrid (4.0.0) in a webpack 3 app, a `Uncaught RangeError: Maximum call stack size exceeded` error is thrown at render.

When using DataGrid (5.0.1) in a webpack 3 app, a `Uncaught ReferenceError: e is not defined` and `The above error occurred in the <ForwardRef> component` error is thrown at render.

### Context 🔦

We are trying to use DataGrid in a legacy (webpack 3) application.  We are currently upgrading the application to webpack 4, which I expect will solve the issue, but I am hoping to confirm that is true.  I also would like to know if this is a known issue with any workaround to unblock our team while the webpack 3 -> 4 upgrade is in progress.

### Your environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>

```
 Using Chrome 96

 $ npx @material-ui/envinfo                                                   
npx: installed 2 in 1.313s

  System:
    OS: macOS 11.6.1
  Binaries:
    Node: 12.22.0 - ~/.nvm/versions/node/v12.22.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.22.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.93
    Edge: Not Found
    Firefox: Not Found
    Safari: 14.1.2
  npmPackages:
    @emotion/react: ^11.7.0 => 11.7.0
    @emotion/styled: ^11.6.0 => 11.6.0
    @types/react:  17.0.37
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2
```
</details>

**Comment by m4theushw** [comment]
Webpack 3 was released way before the first DataGrid so we never tested on this version. To answer your question, we never had other issue about incompatibilities with this webpack version. 

I cloned the example and ran it using a non-minified DataGrid and it worked. Maybe the solution is to stop shipping minified code. @eps1lon raised this some time ago through Slack.
