### ISSUE TITLE
[DataGrid] Add `hideable` field to GridColDef

### ISSUE THREAD

**Issue by xiaoyu-tamu** [mui-org/material-ui-x#3426]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

We are missing a hideable flag in the column definition.

For other menu options, we have sortable, filterable, pinnable etc.

### Motivation 🔦

allow blocking any column from being hidden.

**Comment by alexfauquette** [comment]
On my side, I do not see any reason for not adding this field.

To do it, we have to observe the value of the `hideable` field to:
- remove the `<HideGridColMenuItem />`
- disable the toggle in `<GridColumnsPanel />`
- block the behavior of `setColumnVisibility`

**Comment by m4theushw** [comment]
Actually, AG Grid still allows to toggle visibility through their API, so it could work the same way here. The `hideable` flag only impacts the columns panel and the column menu.
