### ISSUE TITLE
Control which columns appear listed in the "Show columns" menu

### ISSUE THREAD

**Issue by mwarger** [mui-org/material-ui-x#3432]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I would like to be able to hide which "show column" options are available in the column menu.

### Motivation 🔦

I would like an option to control which columns are listed in the "show columns" menu.  For example, I may want the ID of a row to be available in the data for that row so I can use it, but I want the column hidden and I don't want a user to be able to show the column, either.  If I hide the column programmatically, it is hidden, but can still be shown via the "show columns" menu.

**Comment by alexfauquette** [comment]
Hi @mwarger what is the `hidable` option proposed in #3426 what you are looking for?

I do not understand in which use case you could need to define a column and neither show it

**Comment by mwarger** [comment]
I had hoped I was missing something simple.  Thank you, that should cover it.
