### ISSUE TITLE
[DataGridPro] Export the tree data grouping column field constant

### ISSUE THREAD

**Issue by socramm9** [mui-org/material-ui-x#3434]
### Order ID 💳

#26327

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I found in the documentation how to pin the checkbox to the right using `GRID_CHECKBOX_SELECTION_COL_DEF.field`

```
<DataGridPro
        rows={rows}
        columns={columns}
        checkboxSelection
        initialState={{
          pinnedColumns: {
            left: [GRID_CHECKBOX_SELECTION_COL_DEF.field],
            right: ['actions'],
          },
        }}
      />
```
But I am unable to find COL_DEF for "Group" column using TreeData.

I would like to pin "Job Title" and "Group" column for example.

<img width="669" alt="Bildschirmfoto 2021-12-14 um 16 45 26" src="https://user-images.githubusercontent.com/52098754/146031217-df988cd5-12c9-4e17-95aa-7db378fff092.png">
https://codesandbox.io/s/wgyrh?file=/demo.tsx

### Your environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>

```
 System:
    OS: macOS 12.0.1
  Binaries:
    Node: 14.17.2 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.20.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 96.0.4664.93
    Edge: 96.0.1054.53
    Firefox: 92.0
    Safari: 15.1
  npmPackages:
    @emotion/react: ^11.7.1 => 11.7.1 
    @emotion/styled: ^11.6.0 => 11.6.0 
    @material-ui/styles: ^4.11.1 => 4.11.4 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @types/react: ^17.0.37 => 17.0.37 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^3.7.5 => 3.9.10 
```
</details>

**Comment by alexfauquette** [comment]
The quick answer is `"__tree_data_group__"`. See here for an example: https://codesandbox.io/s/basictreedata-material-demo-forked-lm7oo?file=/demo.tsx

But hard coding a string will expose you to bugs if we change it.

For now, this constant is defined as a property of `GRID_TREE_DATA_GROUP_COL_DEF_FORCED_PROPERTIES` which is not accessible from '@mui/x-data-grid-pro'. @flaviendelangle do you think we should export `GRID_TREE_DATA_GROUP_COL_DEF_FORCED_PROPERTIES` or only the column name?

**Comment by flaviendelangle** [comment]
I would go for only exposing the column name.
I have the same issue with an additional layer of complexity in #3277 (https://github.com/mui-org/material-ui-x/pull/3277#discussion_r765685904)

In the meantime, hardcoding is fine, this value should not change anytime soon and not in a minor release. But I agree that we should avoid :+1:

**Comment by m4theushw** [comment]
Forcing users to use `GRID_TREE_DATA_GROUP_COL_DEF_FORCED_PROPERTIES` is not viable, this variable name is too long. It's better to expose only a constant with the field name. I have the same problem in #3387.

**Comment by socramm9** [comment]
> The quick answer is `"__tree_data_group__"`. See here for an example: https://codesandbox.io/s/basictreedata-material-demo-forked-lm7oo?file=/demo.tsx
> 
> But hard coding a string will expose you to bugs if we change it.
> 
> For now, this constant is defined as a property of `GRID_TREE_DATA_GROUP_COL_DEF_FORCED_PROPERTIES` which is not accessible from '@mui/x-data-grid-pro'. @flaviendelangle do you think we should export `GRID_TREE_DATA_GROUP_COL_DEF_FORCED_PROPERTIES` or only the column name?

Thanks for the fast replay. I will go with `"__tree_data_group__"` for now. :)

**Comment by konrazem** [comment]
Note that hardcoded "__tree_data_group__" may change and may cause bugs 😥We will need to check what is the problem and what is the new name.
