### ISSUE TITLE
Column width "jiggles" back and forth

### ISSUE THREAD

**Issue by shanemiller89** [mui-org/material-ui-x#3439]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

In what seems to be random instances, the column widths of the data grid rapidly change back and forth.

This sometimes is fixed with a page refresh, however it has also persisted after several page refreshes as well.

This has also led to the page crashing, as I'm guessing we're seeing some instance of an infinite loop.

At first, I thought this was related to [this ticket](https://github.com/mui-org/material-ui-x/issues/2508). Think this is a different issue.

![column_shake](https://user-images.githubusercontent.com/2695797/146209420-923adc49-fb4d-41b4-825b-36de5947284e.gif)

### Expected behavior 🤔

For the widths to not rapidly adjust.

### Steps to reproduce 🕹

I have no discernible way to reproduce this bug.

This issue has mainly been reported by our users, and has been difficult to replicate. 

We haven't been able to have a clear way to easily reproduce the issue as well. As the few times I have witnessed the bug locally, a refresh usually cleared the issue.

Currently using `"@mui/x-data-grid-pro": "^4.0.1"`

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
  
  Currently using Chrome

```
  System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.97 GB / 15.44 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 7.16.0 - /usr/local/bin/npm
    Watchman: 20200816.222424.0 - /usr/local/bin/watchman
  Managers:
    Apt: 2.3.9 - /usr/bin/apt
    Composer: 1.9.1 - /usr/local/bin/composer
    pip3: 20.3.4 - /usr/bin/pip3
    RubyGems: 2.7.6.2 - /usr/local/bin/gem
  Utilities:
    Make: 4.3 - /usr/bin/make
    GCC: 11.2.0 - /usr/bin/gcc
    Git: 2.32.0 - /usr/bin/git
    FFmpeg: 4.4 - /usr/bin/ffmpeg
  Servers:
    Apache: 2.4.48 - /usr/sbin/apachectl
  Virtualization:
    VirtualBox: 6.1.26 - /usr/bin/vboxmanage
  IDEs:
    Nano: 5.6.1 - /usr/bin/nano
    VSCode: 1.63.1 - /snap/bin/code
  Languages:
    Bash: 5.1.8 - /usr/bin/bash
    Elixir: 1.12.3 - /home/shanemiller89/.asdf/shims/elixir
    Erlang: 24.1.1 - /home/shanemiller89/.asdf/shims/erl
    Java: 11.0.12 - /usr/bin/javac
    Perl: 5.32.1 - /usr/bin/perl
    PHP: 8.0.8 - /usr/bin/php
    Python: 2.7.18 - /usr/bin/python
    Python3: 3.9.7 - /usr/bin/python3
    Ruby: 2.5.7 - /usr/local/bin/ruby
  Databases:
    MySQL: 0.21.10.1 - /usr/bin/mysql
    PostgreSQL: 13.4 - /home/shanemiller89/.asdf/shims/postgres
    SQLite: 3.35.5 - /usr/bin/sqlite3
  Browsers:
    Chrome: 96.0.4664.45
    Firefox: /home/shanemiller89/.mozilla/firefox
Found default profile: xu2qdwoy.default-release
Import done in 0.414 s
Mozilla Firefox 95.0

```
</details>

### Order ID 💳 (optional)

20297

**Comment by flaviendelangle** [comment]
Looks like #1775 
If you can migrate to `v5.0` it should fix the problem.

**Comment by shanemiller89** [comment]
> Looks like #1775 If you can migrate to `v5.0` it should fix the problem (see https://mui.com/components/data-grid/migration-v4/#main-content)

That looks identical to what we are experiencing. We are in the process of working towards upgrading to v.5. Thank you for the quick response!

**Comment by TheMoonDawg** [comment]
@flaviendelangle Is there a reason this fix wasn't back ported to v4 (especially since this is a paid service)? It's hard to just drop everything and migrate our entire code base over to MUI v5 when users are experiencing this annoying issue today.

**Comment by flaviendelangle** [comment]
@TheMoonDawg I did not exactly fix it. The fix came as a side effect of the rework of the whole grid dimension computation.

In the linked I put above, you have ways of migrating only X to v5 while keeping the core in v4.
I will have a look to see if there is a simple fix for this issue in v4, but I fear it is to deep inside the old dimension computation system which was very imperfect.

**Comment by TheMoonDawg** [comment]
I had a fear that was the case. I had to ask anyway. :D Thanks for the quick response!

**Comment by TheMoonDawg** [comment]
@flaviendelangle I also didn't realize that we could migrate DataGrid to v5 while still using v4 Core. That alone is super helpful and much more achievable in the short term.

As Shane said, we're working to get to v5 Core, but it's gonna take time to get there. Thanks again!

**Comment by flaviendelangle** [comment]
Your welcome !
I'm closing this issue, see #1775 for more details.
