### ISSUE TITLE
[DataGrid] Height increase in an endless loop

### ISSUE THREAD

**Issue by mattixittam** [mui-org/material-ui-x#344]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When initializing a DataGrid, the height increases rapidly

## Expected Behavior 🤔

The size should be enough for the presented rows and not increase

## Steps to Reproduce 🕹

https://codesandbox.io/s/infallible-wave-3v0d2?file=/src/Demo.js

## Context 🔦

I'm trying to display the table :)

## Your Environment 🌎

See the codesandbox. Chrome 85.0.4183.102 on OSX.

I tried going back to 0.1.67, but that complains of a missing dependency 'styled-components'. Do I need to go back to a previous version of material-ui/core as well? If so, which?

**Comment by oliviertassinari** [comment]
Thanks for opening the issue, the documentation covers how to handle this case: https://material-ui.com/components/data-grid/rendering/#layout. However, I agree, I think that in your case, the table should have a height of 0 and print a warning to the documentation on how to handle the case. Something is wrong.

**Comment by mattixittam** [comment]
I would expect the `autoHeight` behaviour to be the default tbh, coming from other component libraries (with the table taking up as much space as is needed for its `pageSize` to be shown or for the number of rows if `pageSize` is not set).

However, if it is not, it should then use the closest parent with a height (or, failing that, the <body> height) for its sizing, right?

**Comment by oliviertassinari** [comment]
When `autoHeight` is true, the grid grows with its content. If you have 100 rows, it will be 5400px high. I don't think that it should be the default. The default is meant to accommodate the requirement of virtulization: the grid to know the size of its container.

I would definitely expect a grid of height 0px (or something like 10px and a warning so developers can see it something is wrong) in your example.
