### ISSUE TITLE
Pinning of columns for MIT version

### ISSUE THREAD

**Issue by TriPSs** [mui-org/material-ui-x#3440]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Hi,

Not sure if here is the right place (I could not open anything in discussions) but will column pinning or a (light) version of it become available for the MIT version?

**Comment by alexfauquette** [comment]
Hi @TriPSs, for now, there is no discussion going in that direction.

**Comment by oliviertassinari** [comment]
I have added the "waiting for upvote" label to get a sense of the popularity of this request and closing to be transparent with the default answer to this type of request.

@TriPSs Note that we are reevaluating the pricing strategy for Q1 2022, it's possible that we will make important changes. One year in, we have more data than when we designed the pricing in a vacuum. For this purpose, I would love to learn more about the context you are in to use the column pinning feature.

- Part of a company? How many developers?
- Type of application that you are building?

Thanks.
