### ISSUE TITLE
[DataGrid]: Inconsistent GridCellEditCommitParams sent to onCellEditCommit handler via outside mouse click vs tab/enter

### ISSUE THREAD

**Issue by neemski** [mui-org/material-ui-x#3442]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The first argument passed to the `onCellEditCommit` handler yields different results if you begin editing a cell and exit via mouse click vs exiting with Enter or Tab:
```tsx
<DataGrid
  rows={rows}
  columns={columns}
  onCellEditCommit={(params: GridCellEditCommitParams) => {
    // Clicking outside the cell vs enter/tab yields different results.
    console.log(params);
  }}
/>
```

The first output is what happens when you mouse click outside of the editing cell. The second output is what happens when you hit Tab/Enter while editing a cell:

<img width="584" alt="Screen Shot 2021-12-15 at 7 28 27 PM" src="https://user-images.githubusercontent.com/6894781/146303317-015b7c32-21e9-4abb-86fb-974322f31337.png">

### Expected behavior 🤔

I would expect the param passed to this method to have the same `GridCellEditCommitParams` type, aka containing only `id`, `value` and `field` props.

### Steps to reproduce 🕹

Steps:

1. CodeSandbox: https://codesandbox.io/s/basiceditinggrid-material-demo-forked-d6u0m?file=/demo.tsx
2. Open the console.
3. Double-click into a cell, and click out of it. Observe the output.
4. Double-click into the same cell, and hit enter or tab. Observe the output.

### Context 🔦

I'm just getting started with DataGrid and editing behavior and noticed this. [From the docs](https://mui.com/components/data-grid/editing/#stop-editing), it's not super clear what will happen when you mousedown outside the cell (aka, is it supposed to save, or rollback?):

<img width="692" alt="Screen Shot 2021-12-15 at 7 43 59 PM" src="https://user-images.githubusercontent.com/6894781/146304565-666a341c-2d89-4b72-8dc5-d8b8fbd109a0.png">

Also, from the [component docs](https://mui.com/components/data-grid/editing/#server-side-persistence) and [API docs](https://mui.com/api/data-grid/data-grid/), it's not clear that `onCellEditCommit` will fire even if the cell value **hasn't** changed? Is there any way to know/prevent that from happening? I would rather prevent a PATCH call from happening if the cell value hasn't changed, but I don't see any clear way to do so at the moment.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 12.1
  Binaries:
    Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
    Yarn: 3.0.2 - ~/.nvm/versions/node/v16.3.0/bin/yarn
    npm: 7.15.1 - ~/.nvm/versions/node/v16.3.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Edge: Not Found
    Firefox: 95.0
    Safari: 15.2
  npmPackages:
    @emotion/react: ^11.7.1
    @emotion/styled: ^11.6.0
    @mui/icons-material: ^5.2.4
    @mui/material: ^5.2.4
    @mui/styles: ^5.2.3
    @mui/x-data-grid: ^5.2.0
    @mui/x-data-grid-generator: ^5.2.0
    @types/react: ^17.0.37
    @types/react-dom: ^17.0.11
    react: ^17.0.2
    react-dom: ^17.0.2
    typescript: ^4.5.4
```
</details>

**Comment by neemski** [comment]
Adding this very similar issue here for completeness: https://github.com/mui-org/material-ui-x/issues/2202

**Comment by alexfauquette** [comment]
Thanks for reporting this bug.

The keyboard events commit cleaned parameters named `commitParams`. Whereas the other events commit directly the `params` without any cleaning.

https://github.com/mui-org/material-ui-x/blob/5ff2983d8f024c2a74aa34891d4fa2263b1e5646/packages/grid/_modules_/grid/hooks/features/editRows/useGridEditRows.ts#L546

https://github.com/mui-org/material-ui-x/blob/5ff2983d8f024c2a74aa34891d4fa2263b1e5646/packages/grid/_modules_/grid/hooks/features/editRows/useGridEditRows.ts#L97

As you observed, clicking outside of the cell saves the modification, we will add the information to the doc.


To check if the cell has been modified, the easiest way is probably to use `onCellEditStart` to save `id`, `field` and `value` when starting the editing. If the `onCellEditCommit` has the same `id`, `field` but a different `value` then it has changed.

**Comment by neemski** [comment]
Thanks @alexfauquette!
