### ISSUE TITLE
[DataGrid] Can't enter 0 on numeric columns

### ISSUE THREAD

**Issue by evoinea** [mui-org/material-ui-x#3478]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

On a numeric column, 0 can't be displayed ( either typing the value or using the stepper).  An work around when typing is to type 0 twice, so the second time 0 value will be displayed. 
The issue is just displaying the 0, the value will be set correctly.

### Steps to reproduce 🕹

https://mui.com/components/data-grid/demo/

![OvI7d8eB5R](https://user-images.githubusercontent.com/42154031/147003866-f667a9c2-2b25-41f8-bcb5-26782ea833b7.gif)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by evoinea** [comment]
Thank you very much for the fix.

**Comment by dmbarry86** [comment]
@m4theushw or others do you know when the next release will be made that includes this fix?

**Comment by dmbarry86** [comment]
> @m4theushw or others do you know when the next release will be made that includes this fix?

Thanks for the new release and quick fix.
