### ISSUE TITLE
[DataGrid] onSortModelChange gets called twice on initialization if the sortModel contains a column, which doesn't exist in columns

### ISSUE THREAD

**Issue by mvpindev** [mui-org/material-ui-x#3479]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Hey, 
pretty much what's in the title.

If you have a sortModel like this:
![image](https://user-images.githubusercontent.com/49334712/146753367-817795e5-4fcd-442b-8364-88c0e0d3e528.png)
and the sorted column doesn't exist on the grid-columns:
![image](https://user-images.githubusercontent.com/49334712/146754863-746f9c7e-43ba-43a5-8a60-390eb8c2d338.png)
...then 'onSortModelChange' gets called twice with an empty 'newSortModel'.
![image](https://user-images.githubusercontent.com/49334712/146753338-dc0feefd-1867-4899-b1a8-be5ff47f61c4.png)

![image](https://user-images.githubusercontent.com/49334712/146753310-444071d4-e07a-47d8-8147-dc68ad7a65a9.png)

### Expected behavior 🤔

onSortModelChange should not be called.

Sortmodel should not be empty in onSortModelChange

### Steps to reproduce 🕹

Code Sandbox
(https://codesandbox.io/s/busy-tree-04o6d?file=/src/App.js)

**Comment by m4theushw** [comment]
You need to memoize the columns, as said in the [docs](https://mui.com/components/data-grid/columns/#column-definitions). When `onSortModelChange` is called for the first time, it triggers a rerender by updating the state. Then, in the second rerender, the reference of the `columns` prop also changes so it needs to trigger `onSortModelChange` again. The grid relays on the reference, not the actual value. Here's the updated CodeSandbox: https://codesandbox.io/s/eloquent-http-7jfyt?file=/src/App.js

**Comment by mvpindev** [comment]
Thanks! That solves the trigger issue.

Is it also expected behavior, that the sortModel given to the onSortModelChange handler is empty?

I encountered this when we removed visible grid-columns like "createdUtc", while still using it for sorting on the backend.

The initial trigger to onSortModelChange then set the sortModel from "createdUtc" to an empty array, which made the grid not being sorted at all.

My current 'workaround' is adding the column "createdUtc" as a hidden column like this:
![image](https://user-images.githubusercontent.com/49334712/147101640-82bbc9b2-b124-4c93-8428-929f971d6c32.png)

**Comment by m4theushw** [comment]
> Is it also expected behavior, that the newSortModel-parameter given to the onSortModelChange handler is empty? (i forgot to add that to "expected behavior")

Yes, during initialization the grid will sanitize the values provided to `sortModel` keeping only the columns that exist in the `columns` prop.

> My current 'workaround' is adding the column "createdUtc" as a hidden column like this:

Actually, this is the right way to do. The `columns` prop is not only for the visible columns, but also for the columns that can be sorted/filtered. To prevent this column you added from being toggled through the columns panel, in the next release there will be a `hideable` flag which you can also use. https://github.com/mui-org/material-ui-x/pull/3433

I'm closing this issue, but it's still open for comments.
