### ISSUE TITLE
[DataGridPro] Tree data gaps are editable

### ISSUE THREAD

**Issue by alexfauquette** [mui-org/material-ui-x#3482]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Gap rows generated by the tree data are editable, but editing them leads to an error, because these rows have no id

### Expected behavior 🤔

I assume that if there are missing rows in the tree data it is because the rows do not make sense at this hierarchical level, so the cell should no editable.

The other solution is to insert rows, but I think such a behavior (let datagrid add rows by itself) will be hard to manage for developers

### Steps to reproduce 🕹

Steps:

1. Go to https://codesandbox.io/s/treedatawithgap-material-demo-forked-1i144?file=/demo.tsx
2. Edit cells of a row

**Comment by flaviendelangle** [comment]
We should probably totally block the edition for auto-generated rows.
