### ISSUE TITLE
MUI Translation doesn't work

### ISSUE THREAD

**Issue by justdvl** [mui-org/material-ui-x#3514]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Hello.
Mui Data Grid Pro translations doesn't work. They work on free version up to a point (footer is translated, the header menu not).
Please see codesandbox example: https://codesandbox.io/s/datagridprodemo-material-demo-forked-21t6w?file=/demo.tsx
Also, [codesandbox example](https://codesandbox.io/s/ezl3l?file=/demo.tsx) of MUI translation you link to on your [Localization page](https://mui.com/guides/localization/#Locales.tsx) doesn't even run.

### Expected behavior 🤔

I expect full table (including header menu) to be translated when nested in Theme which has localization set. For Pro version of data grid.

### Steps to reproduce 🕹

Steps:

1. Open https://codesandbox.io/s/datagridprodemo-material-demo-forked-21t6w?file=/demo.tsx
2. Hover over the header cell
3. Click menu icon to open the menu
4. Texts are not translated

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
System:
    OS: macOS 11.6
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/Documents/github/bergversetzer-fe/node_modules/.bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Edge: Not Found
    Firefox: 95.0.2
    Safari: 14.1.2
  npmPackages:
    @emotion/react: ^11.7.1 => 11.7.1 
    @emotion/styled: ^11.6.0 => 11.6.0 
    @mui/base:  5.0.0-alpha.61 
    @mui/icons-material: ^5.2.5 => 5.2.5 
    @mui/lab: ^5.0.0-alpha.61 => 5.0.0-alpha.61 
    @mui/material: ^5.2.5 => 5.2.5 
    @mui/private-theming:  5.2.3 
    @mui/styled-engine:  5.2.5 
    @mui/styles:  5.1.1 
    @mui/system:  5.2.5 
    @mui/types:  7.1.0 
    @mui/utils:  5.2.3 
    @mui/x-data-grid-pro: ^5.2.1 => 5.2.1 
    @mui/x-license-pro:  5.2.1 
    @types/react: ^17.0.35 => 17.0.35 
    react: 17.0.2 => 17.0.2 
    react-dom: 17.0.2 => 17.0.2 
    typescript: ^4.5.2 => 4.5.2 
```
</details>

**Comment by alexfauquette** [comment]
The DataGrid has its own locale files. So to get translations, you need to import both the core locale and the DataGrid one.
The documentation specific to localization is https://mui.com/components/data-grid/localization/

Here is a correction of one of the code sandbox (notice that the footer is now in french).
https://codesandbox.io/s/datagridprodemo-material-demo-forked-mbvz6?file=/demo.tsx

**Comment by alexfauquette** [comment]
About the codeSandbox that does not works, it is due to the outer them which is provided in the doc but not in the codeSandbox. I'm opening another issue for this special case

**Comment by justdvl** [comment]
Thank you, works well. There is translations missing for pin left, pin right, I assume those can be provided by localeText prop.

**Comment by alexfauquette** [comment]
All the missing keys are listed in a special issue. If you can translate some of them, do not hesitate to make a PR :)

https://github.com/mui-org/material-ui-x/issues/3211
