### ISSUE TITLE
[docs] Custom pagination demo not working

### ISSUE THREAD

**Issue by Janushan** [mui-org/material-ui-x#3523]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If you head over to: [https://mui.com/components/data-grid/components/#pagination](https://mui.com/components/data-grid/components/#pagination)
and open it on codesandbox: [https://codesandbox.io/s/ioqlj?file=/demo.tsx](https://codesandbox.io/s/ioqlj?file=/demo.tsx)

then the following error is shown: 
```(0 , _xDataGrid.useGridSlotComponentProps) is not a function```

I think the demo just needs to be updated based on the recent changes to the package.

### Expected behavior 🤔

The demo should work correctly

### Steps to reproduce 🕹

Steps:

1. Head over to: [https://mui.com/components/data-grid/components/#pagination](https://mui.com/components/data-grid/components/#pagination)
2. Open the demo on codesandbox: [https://codesandbox.io/s/ioqlj?file=/demo.tsx](https://codesandbox.io/s/ioqlj?file=/demo.tsx)

### Context 🔦

I found this issue whilst reading through the documentation.
I am interested in adding the pagination component to my mui data grid.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by DanailH** [comment]
Hi @Janushan thanks for raising this, but If I go to the demo you mentioned in the docs and click the `Edit in CodeSandbox` button under it the code sandbox that is opened is correct? I'm unsure how you got this link but the one in the docs seems to be working correctly.

**Comment by Janushan** [comment]
> Hi @Janushan thanks for raising this, but If I go to the demo you mentioned in the docs and click the `Edit in CodeSandbox` button under it the code sandbox that is opened is correct? I'm unsure how you got this link but the one in the docs seems to be working correctly. Maybe I'm missing something?
> 
> This is the PR that did the change #2856.

Thanks @DanailH for your quick response! : )

Not sure what happened there
Perhaps I was looking at an outdated version of the docs and found the codesandbox link there

I'll close this issue now
