### ISSUE TITLE
[DataGridPro] Pinned column overlap non-pinned column

### ISSUE THREAD

**Issue by cq-ubaid-khan** [mui-org/material-ui-x#3531]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I have both checkbox and row menu column pinned on left side but as you can see from the picture below my "Role" column gets bit of hidden behind row menu column. 

### Expected behavior 🤔

No need to explain!

### Steps to reproduce 🕹
https://codesandbox.io/s/loving-danny-7vdw7?file=/src/Demo.tsx

![image](https://user-images.githubusercontent.com/58769931/147740843-833dfa04-aaa2-44b1-904e-02f7a6421bf7.png)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by m4theushw** [comment]
By default, the grid adds a padding of 10px on each side of the cell. The `minWidth` value set in the example is less than the minimum necessary to correctly render the cell. Internally, the DataGrid calculates the column width considering 5px, but CSS forces the cell to take more than that. That's way the pinned columns overlap the first non-pinned column.

![image](https://user-images.githubusercontent.com/42154031/147989156-14a37822-963c-441e-a43b-f6ad36186c41.png)

There're two possible fixes:
1. Increase `minWidth` to at least 50px, which leaves 30px for the button and 10px for the padding on each side
2. Remove the padding with the code below and set `minWidth` to at least 30px

```tsx
const columns: GridColumns = [
  {
    field: 'actions',
    type: 'actions',
    cellClassName: 'actions',
    minWidth: 30,
    width: 30,
    resizable: false,
    getActions: () => actions,
  },
]

<DataGrid sx={{ '& .actions': { padding: 0 } }} />
```

If you still need a shorter column I would suggest to create a custom one, not based on MUI `IconButton`. Doing that, you don't have the width limitation imposed by this component.
