### ISSUE TITLE
[question] Changes in MUI Grid Scroller in Dark Mode? 

### ISSUE THREAD

**Issue by tielushko** [mui-org/material-ui-x#3555]
### Order ID 💳

31986

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I have found a little inconsistency with the way the scroller looks in Dark mode from version 4 of the grid as compared to version 5.2.1. Even when I was using v5.0.0.beta.5 I still had the original look of the scroller. 

Please checkout my sandbox here: https://codesandbox.io/s/data-grid-pro-color-toggle-mode-issue-jlh25 

Feel free to switch the package version to v5.0.0.beta.5 and v5.2.1 of the x-data-grid-pro and see the difference that happens when the toggle of the dark mode/light mode happens. 

For details on the problem, feel free to checkout below! 

Thank you :)
### The problem in depth 🔍

Hello MUI Team,

I have found a little inconsistency with the way the scroller looks in Dark mode from version 4 of the grid as compared to version 5.2.1. Even when I was using v5.0.0.beta.5 I still had the original look of the scroller. 

Here is an example of how the scroller looked like prior to v5.2.1:
![Screenshot 2022-01-05 145128](https://user-images.githubusercontent.com/46033508/148280051-7c124f6c-e1b6-4507-8a12-6c511938e1ad.png)
https://v4.mui.com/components/data-grid/#commercial-version

Here's however how it looks on the most recent version:
![image](https://user-images.githubusercontent.com/46033508/148280113-f3e10a67-f7ad-444e-8af8-a5c71fa4aaa2.png)
https://mui.com/components/data-grid/#commercial-version

I was wondering whether there was a change made to the styles of the scroller, the older version looked like a much cleaner one. I would greatly appreciate your help in this matter.

### Context 🔦

I liked the older version of the scroller, at the moment, my website has a worse-looking version of the scroller which doesn't change color to dark when toggling the theme mode to dark in ThemeProvider.

### Your environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```

  System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 7.13.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 97.0.4692.71 - browser that was used.
    Edge: Spartan (44.19041.906.0), Chromium (95.0.1020.53)
  npmPackages:
    @emotion/react: ^11.4.1 => 11.5.0
    @emotion/styled: ^11.3.0 => 11.3.0
    @types/react: ^17.0.21 => 17.0.34
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.3.2 => 4.4.4
    

</details>

**Comment by tielushko** [comment]
I've isolated the problem with the scroller appearing in v5.0.1. 

v5.0.0 is still good with the scroller, however in v5.0.1 it breaks. Please see the sandbox attached. Would greatly appreciate your help!

**Comment by tielushko** [comment]
#3231 I noticed that the scrollbar has been changed. I need to set the enableColorScheme property to true in my CssBaseline. 

It is unfortunate you guys got rid of such a beautiful scrollbar :(

**Comment by m4theushw** [comment]
You can restore the old scrollbar by applying the customizations that were removed in https://github.com/mui-org/material-ui-x/pull/3146/files#diff-a74a2b513d13f6e3ea9d8ced450888cd56a75169315fd549c456a8177d50ad4a. Notice that these styles should only be applied when on the dark mode.

**Comment by tielushko** [comment]
Thank you for your response @m4theushw, I will keep the changes in mind and if we decide to restore the old scrollbar, I will make sure to apply these. 

I will close the issue now :)
