### ISSUE TITLE
DataGrid Error "r is readonly" when deployed to production

### ISSUE THREAD

**Issue by iocuydi** [mui-org/material-ui-x#3556]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

DataGrid component is blank with "an error occurred" displayed in the middle. This only happens when deployed to production on AWS Amplify or Netlify. When testing locally, DataGrid works as intended.

### Expected behavior 🤔

DataGrid should work as intended in production as well as in test.

### Steps to reproduce 🕹

Steps:

1. Write any component containing a datagrid with some data, either static or dynamic rows.
2. Deploy to production on AWS Amplify or Netlify
3. Observe DataGrid component
4.

### Context 🔦

I want to use DataGrid in my deployed app. I have used it in another app before hosted on amplify where this didn't happen, I suspect it has to do with the interaction of other libraries in my current project. I don't know much about the inner workings of React but seems similar to this issue:
https://github.com/facebookexperimental/Recoil/issues/122

### Your environment 🌎

All browsers affected

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.12.3 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 96.0.4664.110
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.62)
  npmPackages:
    @emotion/react: ^11.7.1 => 11.7.1
    @emotion/styled: ^11.6.0 => 11.6.0
    @mui/base:  5.0.0-alpha.62
    @mui/material: ^5.2.6 => 5.2.6
    @mui/private-theming:  5.2.3
    @mui/styled-engine:  5.2.6
    @mui/system:  5.2.6
    @mui/types:  7.1.0
    @mui/utils:  5.2.3
    @mui/x-data-grid: ^5.2.1 => 5.2.1
    @types/react:  16.9.44
    react: ^16.14.0 => 16.14.0
    react-dom: ^16.13.1 => 16.13.1
```
</details>

**Comment by iocuydi** [comment]
Closed as I saw someone reported the same thing in the last few hours after I'd typed up my issue

**Comment by tafadzwajdube** [comment]
Any solution to this issue?
