### ISSUE TITLE
[DataGrid] Row edit commit is not working when preProcessEditCellProps is defined

### ISSUE THREAD

**Issue by stamahto** [mui-org/material-ui-x#3557]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If in any column is defined 'preProcessEditCellProps' function, the commit of the row in table by pressing Enter encountered an error: _MUI: Row at id: x is not being edited._

Demo: https://codesandbox.io/s/roweditcontrolgrid-material-demo-forked-04sci?file=/demo.tsx

If you comment lines 50-53, commiting by enter will work fine.

### Expected behavior 🤔

Should be working as usual without defined preProcessEditCellProps function in column.

### Steps to reproduce 🕹

Steps:

1. Try edit any cell in demo
2. Press enter to commit changes

### Order ID 💳 (optional)

31956

**Comment by flaviendelangle** [comment]
Thank you for your clear reproduction case
When `preProcessEditCellProps`, the commit phase becomes asynchronous but the row leaves the edit mode synchronously so we are leaving the row before committing the value (thus the error you reported).
