### ISSUE TITLE
[question] I don't know how to use the "GridCsvExportOptions" lib and it is not being exported

### ISSUE THREAD

**Issue by lincolnmqs** [mui-org/material-ui-x#3563]
### Order ID 💳

35305

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I am unsure how to use the GridCsvExportOptions component (I don't have examples in the documentation) and when I try to import this package, it returns the error message: "GridCsvExportOptions is not exported from @mui/x-data-grid-pro".

Note: @mui/x-data-grid-pro packages are installed correctly with the latest version.

### The problem in depth 🔍

I'm trying to apply uft8 settings to CSV data export, but the "GridCsvExportOptions" lib returns an error that is not being exported from "x-data-grid-pro". I also don't know if I'm using this lib correctly.

Code used:

`   ...
    import { GridCsvExportOptions } from '@mui/x-data-grid-pro';
    ...
    CustomToolbar = () => {
        return (
            <GridToolbarContainer className={gridClasses.toolbarContainer}>
                <GridToolbarColumnsButton />
                <GridToolbarFilterButton />
                <GridToolbarExport>
                    <GridCsvExportOptions utf8WithBom={true} />
                </GridToolbarExport>
            </GridToolbarContainer>
        );
    }
    ...`

Problem:
`Failed to compile ./src/components/Report/DetailedRegister/index.js
Attempted import error: 'GridCsvExportOptions' is not exported from '@mui/x-data-grid-pro'.`

### Context 🔦

I'm trying to configure DataGrid export to uft8. But when using the lib "GridCsvExportOptions", it returns an error that the lib cannot be exported from "x-data-grid-pro". I also don't know if I'm using the lib correctly, I couldn't find any examples. But even so, I was supposed to find this lib, no?

### Your environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
`GridCsvExportOptions` is a TypeScript interface not a component.

https://codesandbox.io/s/datagridpro-v5-quick-start-forked-skj31?file=/src/App.tsx

You have to override the `GridToolbar` component to pass custom options to `GridToolbarExport`
We could make this more straightforway by adding `csvOptions` as a prop to `GridToolbar` so that devs could do

```tsx
<DataGridProps
  componentsProps={{ toolbar: { csvOptions: { utf8WithBom: true } } }}
/>
```

But for now you have to override the whole toolbar.

**Comment by lincolnmqs** [comment]
@flaviendelangle what would the GridToolbar look like?

`<GridToolbarContainer className={gridClasses.toolbarContainer} 
                componentsProps={{ toolbar: { csvOptions: { utf8WithBom: true, fileName: 'teste', allColumns: true } } }}
            >
                <GridToolbarColumnsButton />
                <GridToolbarFilterButton />
                <GridToolbarExport />
            </GridToolbarContainer>`

Same as above code, or would you change GridToolbarContainer to DataGridProps?

**Comment by lincolnmqs** [comment]
@flaviendelangle Do I have any JavaScript example instead of TS?

**Comment by lincolnmqs** [comment]
@flaviendelangle Thank you very much!
