### ISSUE TITLE
[question] Limit of columns to be displayed in the data grid

### ISSUE THREAD

**Issue by lincolnmqs** [mui-org/material-ui-x#3565]
### Order ID 💳

35305

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I am unsure how to limit the number of columns to be displayed in the data grid.

### The problem in depth 🔍

I've seen some examples that uses makeStyles with a field called "maxColumns", I imagined it would be the limit of columns to display, but I didn't get the desired result.

### Context 🔦

I want to limit the number of columns to be displayed in the data grid. Currently the table has several columns, I wanted to put a maximum limit to display and not harm the display of data.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
Do you still have the link to the solution with `makeStyles` and `maxColumns` such that we could have a look?

The behavior you want is not really clear. How does your user add a column, and how do you want to prevent them from adding more than the limited number of columns?

I can imagine use cases, where you want to only show a subsample of columns by default, and let the user add other columns. But I do not understand in which case you would like to forbid exceeding a given number of columns. Could you provide a bit more of information on why you are looking for such a feature?

**Comment by lincolnmqs** [comment]
@alexfauquette I'm looking for the resource precisely because of what you wrote above, I just want to leave a sample that doesn't make the table too voluminous. But if the user wants to display all or select more columns, he is free to do so.

**Comment by alexfauquette** [comment]
So you don't want to limit the number of columns, you want to display a subsample by default. 

Here in the following example column "age" i not shown and user can add it: https://mui.com/components/data-grid/columns/#hiding

**Comment by lincolnmqs** [comment]
Thank you very much!
