### ISSUE TITLE
TreeData - lazy load children

### ISSUE THREAD

**Issue by david-ic3** [mui-org/material-ui-x#3569]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Add feature to lazy load children

### Motivation 🔦

Sometimes the cost to retrieve the whole tree is huge. 

### Order ID 💳 (optional)

#19458

**Comment by flaviendelangle** [comment]
Duplicate #3377 
If you have more details about you need that could be interesting to list them on #3377.

**Comment by david-ic3** [comment]
Upps, désolé
