### ISSUE TITLE
TreeData - change icons for expand/collapse

### ISSUE THREAD

**Issue by david-ic3** [mui-org/material-ui-x#3570]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Ability to change icons for expand/collapse (couldn't find the the documentation how to do it)

### Order ID 💳 (optional)

#19458

**Comment by flaviendelangle** [comment]
Our documentation for the custom components is very light, we are planning to work on it.
Here is an example with custom icons: https://codesandbox.io/s/datagridpro-v5-quick-start-forked-x46hh?file=/src/App.tsx

With #3277 we will fix the default icons to have the following output:

![Uploading image.png…]()
