### ISSUE TITLE
[DataGrid] Arrows appear as repeating background for column actions

### ISSUE THREAD

**Issue by raDiesle** [mui-org/material-ui-x#3589]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

You open the column action menu. it shows to user weird arrows as background, which makes it almost unusable

![arrows_column_action_dropdown](https://user-images.githubusercontent.com/878397/148775673-470fc006-a6f8-4350-b734-ed2ef2d465fd.png)

### Expected behavior 🤔

It should not show those arrows.

### Steps to reproduce 🕹

Steps:

1. Simple setup no special configurations
3. open column menu by mouse click
3. arrows appear

### Context 🔦

just default usage of material-ui-x DataGrid

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.55)
  npmPackages:
    @emotion/react: 11.7.1 => 11.7.1
    @emotion/styled: 11.6.0 => 11.6.0
    @mui/base:  5.0.0-alpha.63
    @mui/icons-material: 5.2.5 => 5.2.5
    @mui/material: 5.2.7 => 5.2.7
    @mui/private-theming:  5.2.3
    @mui/styled-engine:  5.2.6
    @mui/styles: 5.2.3 => 5.2.3
    @mui/system:  5.2.6
    @mui/types:  7.1.0
    @mui/utils:  5.2.3
    @mui/x-data-grid: 5.2.1 => 5.2.1
    @types/react:  17.0.38
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2

Chrome 97.0.4692.71
```
</details>

**Comment by m4theushw** [comment]
Please provide a **minimal** reproduction test case with the latest version. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) _may_ be a good starting point. Thank you!
