### ISSUE TITLE
[docs] Demo ScrollPlayground crashes

### ISSUE THREAD

**Issue by BangrongGao** [mui-org/material-ui-x#3598]
- [ ] I have [searched for similar issues](https://github.com/mui-org/material-ui/issues?q=is%3Aissue%20%5Bdocs%5D%20Demo%20ScrollPlayground%20crashes) in this repository and believe that this is not a duplicate.

## Steps to Reproduce
1. Visit https://mui.com/components/data-grid/scrolling/#scrolling-to-specific-cells
2. ??
3. demo *ScrollPlayground* crashes

## Your Environment
| Tech         | Version |
|--------------|---------|
| MUI  | v5.2.6  |
| netlify deploy | undefined |
| Browser      | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36 |

**Comment by joserodolfofreitas** [comment]
@BangrongGao, do you think you could describe the step "2" to reproduce the issue?
Maybe you can also expand on what you meant by "crash". Is the browser unresponsive? is the scroll unresponsive? do you see the grid empty? Is there a JS/React Message displayed (screen or console)?

**Comment by m4theushw** [comment]
@joserodolfofreitas A quick note: the "on hold" label is meant for when a pull requests is blocked or another issue needs to be fixed first. The "incomplete" label is sufficient for issues that lack information on how to reproduce. There's a bot that will close this issue if it stays inactive for more than 7 days.
