### ISSUE TITLE
[DataGrid] Cell focus is lost when scrolling with the keyboard

### ISSUE THREAD

**Issue by DanailH** [mui-org/material-ui-x#3613]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When you select a cell and start scrolling the grid using the keyboard arrow keys the focus is lost after a new set of rows is rendered.

Check the video for more info:

https://user-images.githubusercontent.com/5858539/149294303-e77ff11a-18e4-4f7c-89cf-b04d98dd578a.mov

### Expected behavior 🤔

The cell focus should be set correctly when scrolling using the keyboard arrow keys.

### Steps to reproduce 🕹

Steps:

1. Go to https://mui.com/components/data-grid/demo/#main-content
2. Select a cell
3. Start scrolling down using the keyboard arrow keys until a new set of rows is rendered

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Cannot reproduce on `DataGrid` - only on `DataGridPro`
