### ISSUE TITLE
Rows per page dropdown doesn't work when selecting option

### ISSUE THREAD

**Issue by paulhan221** [mui-org/material-ui-x#3616]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When selecting a "rows per page" option the table does not update with the new amount of rows.

Replicable here: https://codesandbox.io/s/datagriddemo-material-demo-forked-jbnqs?file=/demo.js:1498-1516

### Expected behavior 🤔

When selecting a rows per page option, the number of rows per page should reflect what was selected.

**Comment by flaviendelangle** [comment]
You are controlling the amount of rows on the page.
You need to define a `onPageSizeChange` to change the value given to the grid as documented [here](https://mui.com/components/data-grid/pagination/#controlled-page-size)

Alternatively you can just initialize the page size, in which case the grid internal state will be updated when you change the page size through the UI, see the documentation [here](https://mui.com/components/data-grid/pagination/#initialize-the-page-size)

**Comment by paulhan221** [comment]
thank you!
