### ISSUE TITLE
[DataGridPro] Is there any callback for applying the filter? 

### ISSUE THREAD

**Issue by lincolnmqs** [mui-org/material-ui-x#3652]
### Order ID 💳

35305

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I want to identify the moment when the user applies the filter to call a function. Is there any method for this?

### The problem in depth 🔍

Filling the input and then applying the filter

![image](https://user-images.githubusercontent.com/30248434/149828255-95b7d9ed-dd45-4df5-91be-ff36b9a56dbe.png)

### Context 🔦

I want to identify the moment when the user applies the filter to call a function. Is there any method for this?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
The filtering process is basically:

```
deleteFilterItem -----------------
                                               |
upsertFilterItem -----------------  -------------------> setFillterModel ----------------> applyFilters
                                               |
setFilterLinkOperator -----------
```

Any UI filter change triggers a `filterModel` change which trigger a re-run of the row filtering
So you just have to listen to filter model changes with `onFilterModelChange`. 
This callback is triggered even when you are not controlling the filter model.

**Comment by lincolnmqs** [comment]
@flaviendelangle Thank you very much!
