### ISSUE TITLE
[DataGridPro] Clicking on a component inside the `renderHeader` triggers sorting

### ISSUE THREAD

**Issue by jaballogian** [mui-org/material-ui-x#3655]
### Order ID 💳

29446

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Clicking component inside `renderHeader` prop for MUI `DataGridPro` changes the `sortModel`

### The problem in depth 🔍

I want to create custom filtering view.

The red box in the image below is an `IconButton` for the filtering view and the blue box is for the column showing/hiding view.

[![enter image description here][2]][2]

I want to change the behavior of the custom filtering view.

If the filter icon is clicked, then the `DataGridPro` header will show some `Select` and `TextField` components as the filter fields like this image below.

[![enter image description here][3]][3]

If we click one of the `Select` and `TextField` components, the `Data Grid Pro` component will trigger the `onSortModelChange` prop to change the `sortModel` value like this image below.

[![enter image description here][4]][4]

So now the `Data Grid Pro` component is sorted based on the column.

  [1]: https://mui.com/components/data-grid/#commercial-version
  [2]: https://i.stack.imgur.com/moYyu.png
  [3]: https://i.stack.imgur.com/rNP7s.png
  [4]: https://i.stack.imgur.com/n8Sll.pnga 

### Context 🔦

**Here is the condition I want:**
if we click one of the `Select` and `TextField` components inside the `Data Grid Pro` header, the `Data Grid Pro` will not trigger the `onSortModelChange` prop which means that the `sortModel` value is not changed

Here is the playground: https://codesandbox.io/s/stackoverflow-mui-data-grid-render-header-xmwf0?file=/src/App.js

I have tried to add `sortable: false` for every column but it will not show the arrow icon inside the `Data Grid Pro` header and prevent the column to be sorted. That's not what I want.

I also have added `sortModel` and `onSortModelChange` props for the `Data Grid Pro` component to control the `sortModel` value but it hasn't worked.

**How to reach the condition I want using the shortest way?**

Should I add an arrow inside each `Select` and `TextField` components with `onClick` prop to change the `sortModel` value?

### Your environment 🌎

<details>

Browser: Chrome 97
NPM: version 8.1.2
Node: version 16.13.1
Dependencies: stated in the playground
</details>

**Comment by DanailH** [comment]
Hi @jaballogian thanks for raising this!

Am I understanding this correctly - you want to prevent sorting a column when you click on the custom component you render inside the `renderHeader`? If that is the case then adding a `event.stopPropagation()` when `onClick` solves this issue -> https://codesandbox.io/s/stackoverflow-mui-data-grid-render-header-forked-urjez?

**Comment by jaballogian** [comment]
> Hi @jaballogian thanks for raising this!
> 
> Am I understanding this correctly - you want to prevent sorting a column when you click on the custom component you render inside the `renderHeader`? If that is the case then adding a `event.stopPropagation()` when `onClick` solves this issue -> https://codesandbox.io/s/stackoverflow-mui-data-grid-render-header-forked-urjez?

Yes, you're right.
Thank you 👍🏻
