### ISSUE TITLE
[DataGrid] `ALT+C` keyboard shortcut doesn't work

### ISSUE THREAD

**Issue by cherniavskii** [mui-org/material-ui-x#3658]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

`Alt+C` (`Option+C`) on selected rows does nothing (at least on MacOS).

### Expected behavior 🤔

`Alt+C` (`Option+C`) should copy currently selected rows with headers (as per https://mui.com/components/data-grid/accessibility/#selection)

### Steps to reproduce 🕹

Steps:

1. Go to https://codesandbox.io/s/6upyt?file=/demo.tsx
2. Select any row
3. Press `Alt+C` (`Option+C`)
4. Paste copied content somewhere to see that clipboard content hasn't changed

### The problem
On Mac, `Option` is a modifier key that allows to type modified letters (e.g. letters with accent) depending on keyboards layout.
For example, on British keyboard layout `Option+c` would print `ç`, and on Ukrainian layout - `≠`.

This is how `Alt+C` shortcut is handled:
https://github.com/mui-org/material-ui-x/blob/85c16c1d240fc5741bdc1fd8bf2325dfe6d59793/packages/grid/_modules_/grid/hooks/features/clipboard/useGridClipboard.ts#L57-L60

In this case, `event.key.toLowerCase()` returns `ç`, not `c` and condition won't pass.

### Proposed solution

For this specific case I would propose to use `event.code`.
It represents a physical key rather than an actual letter, so `event.code` would have a value `KeyC`.
You can use https://w3c.github.io/uievents/tools/key-event-viewer.html for experiments.

It's not ideal though, because:

> For example, the code returned is "KeyQ" for the Q key on a QWERTY layout keyboard, but the same code value also represents the ' key on Dvorak keyboards and the A key on AZERTY keyboards.
Source: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code

So the solution would be to check `event.code` in addition to `event.key`:
```diff
-if (event.key.toLowerCase() !== 'c' || !isModifierKeyPressed) {
+if ((event.key.toLowerCase() !== 'c' && event.code !== 'KeyC') || !isModifierKeyPressed) {
  return;
}
```

I'm pretty sure this problem doesn't exist on Windows, because left ALT doesn't alter the letter pressed.
Would love to get some feedback on this, especially from people using different keyboard layouts and operating system.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>  

```
  MacOS Monterey 12.1
  Browser: Brave, Safari

  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by oliviertassinari** [comment]
I don't follow the issue. What does <kbd>Alt</kbd> refers to? I'm not aware that macOS has such a key.

What I read in the docs is:

<img width="254" alt="Screenshot 2022-01-19 at 00 33 10" src="https://user-images.githubusercontent.com/3165635/150035626-6d32a1e2-a75d-44a1-9569-7aa77200d9c4.png">

then combined with https://mui.com/components/data-grid/accessibility/#key-assignment-conventions

<img width="724" alt="Screenshot 2022-01-19 at 00 33 32" src="https://user-images.githubusercontent.com/3165635/150035654-ed15418c-6914-4a1e-9b8d-0b8b16c57927.png">

<kbd>⌘ Command<kbd> + <kbd>C</kbd> work for me on an AZERTY fr-FR keyboard.
