### ISSUE TITLE
[DataGrid] Horizontal scroll with keyboard stops when a column is too large

### ISSUE THREAD

**Issue by edouardruiz** [mui-org/material-ui-x#3659]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When one of my column has a large width, if I navigate to the right of my data grid with the right arrow key, the columns stop appearing at some point. I don't observe this when using the horizontal scrollbar or my touchpad to navigate (the next columns appear correctly).

### Expected behavior 🤔

I would expect to see additional columns when scrolling to the right.

One workaround could be to set a `maxWidth` in the `GridColDef` but the prop doesn't exist.

### Steps to reproduce 🕹

Steps:

1. Go to this sandbox using Chrome or Safari: https://codesandbox.io/s/datagrid-v5-quick-start-forked-lgqis
2. Click on one of the cell to select it
3. Navigate to the right using the right arrow key
4. Observe that columns stop appearing at some point (after column 8 on my current screen)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 12.1
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - ~/Documents/Projects/next/next-frontend/node_modules/.bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Edge: Not Found
    Firefox: 95.0.2
    Safari: 15.2
  npmPackages:
    @emotion/react: ^11.7.1 => 11.7.1 
    @emotion/styled: ^11.6.0 => 11.6.0 
    @mui/base:  5.0.0-alpha.65 
    @mui/icons-material: ^5.3.0 => 5.3.0 
    @mui/lab: 5.0.0-alpha.65 => 5.0.0-alpha.65 
    @mui/material: ^5.3.0 => 5.3.0 
    @mui/private-theming:  5.3.0 
    @mui/styled-engine:  5.3.0 
    @mui/system: ^5.3.0 => 5.3.0 
    @mui/types:  7.1.0 
    @mui/utils:  5.3.0 
    @mui/x-data-grid: ^5.2.2 => 5.2.2 
    @types/react: ^17.0.38 => 17.0.38 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.5.4 => 4.5.4 
```
</details>

**Comment by DanailH** [comment]
Hi, @edouardruiz thanks for raising this!

I tried to reproduce the issue but I wasn't able to do it consistently. I only managed to break it once. Probably it is related to the overall width of the grid.
Either way, regarding the `maxWidth` - we are already working in it and the PR is ready. You can track the progress here https://github.com/mui-org/material-ui-x/pull/3550

**Comment by edouardruiz** [comment]
Hi @DanailH,

Thanks for your answer!

You don't observe the described behavior in the code sandbox? In the screen recording attached nothing is displayed after the column 8.

https://user-images.githubusercontent.com/6425333/150092648-bcaedfb9-c3bb-457c-8265-2dd865538b1b.mov

I'll follow the progress regarding the `maxWidth` thanks!

**Comment by DanailH** [comment]
Ah ok, I see. I confirm that the issue does occur.

**Comment by m4theushw** [comment]
It appears to be a duplicated of #3436.

You can fix by using `columnThreshold=0`:

```tsx
<DataGrid rows={rows} columns={columns} columnThreshold={0} />
```

**Comment by DanailH** [comment]
I'm closing this one in favor of #3436
