### ISSUE TITLE
[DataGridPro] Problem using Tree Data

### ISSUE THREAD

**Issue by lincolnmqs** [mui-org/material-ui-x#3661]
### Order ID 💳

35305

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I'm using Tree Data. When listing data in DataGridPro, "Uncaught TypeError: Cannot read properties of undefined (reading 'children')" error appears on some occasions.

### The problem in depth 🔍

Erro: Uncaught TypeError: Cannot read properties of undefined (reading 'children')

![image](https://user-images.githubusercontent.com/30248434/149969453-555fe429-66bc-48d5-9f29-3a5922dcc2f9.png)

### Context 🔦

The error happens whenever I fetch the api data in the interval greater than 1 day and list it in DataGridPro. When setting the start and end range of the data for both on the same day, the error does not occur. But when setting to two different dates, this error appears.

Do you know what it could be? The TreeData configuration is correct, see in the image:
![image](https://user-images.githubusercontent.com/30248434/149969631-81fec4f5-21e9-4aef-913f-ca8aea730df9.png)

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by jaballogian** [comment]
> ### Order ID 💳
> 35305
> 
> ### Duplicates
> * [x]  I have searched the existing issues
> 
> ### Latest version
> * [x]  I have tested the latest version
> 
> ### Summary 💡
> I'm using Tree Data. When listing data in DataGridPro, "Uncaught TypeError: Cannot read properties of undefined (reading 'children')" error appears on some occasions.
> 
> ### The problem in depth 🔍
> Erro: Uncaught TypeError: Cannot read properties of undefined (reading 'children')
> 
> ![image](https://user-images.githubusercontent.com/30248434/149969453-555fe429-66bc-48d5-9f29-3a5922dcc2f9.png)
> 
> ### Context 🔦
> The error happens whenever I fetch the api data in the interval greater than 1 day and list it in DataGridPro. When setting the start and end range of the data for both on the same day, the error does not occur. But when setting to two different dates, this error appears.
> 
> Do you know what it could be? The TreeData configuration is correct, see in the image: ![image](https://user-images.githubusercontent.com/30248434/149969631-81fec4f5-21e9-4aef-913f-ca8aea730df9.png)
> 
> ### Your environment 🌎
> `npx @mui/envinfo`

Hello, could I know the solution you used?
I also face the same issue.
