### ISSUE TITLE
[DataGridPro] Set multiple saved filters 

### ISSUE THREAD

**Issue by lincolnmqs** [mui-org/material-ui-x#3662]
### Order ID 💳

35305

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I want to save the filter history for when I leave the page and come back, set the filters previously configured.

### The problem in depth 🔍

Code used to loop through an object's keys and apply the "upsertFilterItem" method to insert an item into the filter:
![image](https://user-images.githubusercontent.com/30248434/150024801-3ac2cf6d-25d7-4539-8d79-9ea5c370df3c.png)

Object added to filter:
![image](https://user-images.githubusercontent.com/30248434/150024917-717cc762-c32c-4b12-837b-3e336ca68c53.png)

In this example, the object being applied inside the "upsertFilterItem" method, is not adding the apiRef filter list.

### Context 🔦

Is it possible to do it this way? Cycle through an object by entering previously saved filters before exiting the page.

This would be very useful to not have to configure filters all the time and be able to apply them to other pages.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by flaviendelangle** [comment]
You can use `apiRef.current.setFilterModel` to pass to update the whole model at once.
Your usecase look a lot like #3593 which should be available in `v5.4` in a few weeks.

**Comment by lincolnmqs** [comment]
@flaviendelangle Is it just to throw all this object from the photo below inside the method "setFilterModel"? 

![image](https://user-images.githubusercontent.com/30248434/150128111-687e2c34-23e8-4629-adef-fe1acaa485ca.png)

**Comment by flaviendelangle** [comment]
Yes
This object *is* the `filterModel`

**Comment by lincolnmqs** [comment]
@flaviendelangle It's because this error is appearing, and I'm throwing the object inside.

![image](https://user-images.githubusercontent.com/30248434/150132068-27e88b61-df75-428f-92ca-547915b404d0.png)

Code:
![image](https://user-images.githubusercontent.com/30248434/150132137-aef75b73-f11a-4592-8c38-1e9a06754129.png)

**Comment by flaviendelangle** [comment]
Please provide a reproduction case, working with screenshots is not great.

If you want to initialize the filter when mounting the grid, use the `initialState` prop
If you want to set the filter model later, use `apiRef.current.setFilterModel`, but never inside the render method since it will not be ready for the 1st render

**Comment by xiaoyu-tamu** [comment]
@flaviendelangle  Thank you for spending time to improve the docs

**Comment by lincolnmqs** [comment]
@flaviendelangle Sorry I didn't send all the code.

I managed to run the method, thanks.

Is it possible to execute a function after the DataGridPro is rendered? Because I need to call this function after rendering, so I can use "apiRef" and its "setFilterModel" method.

**Comment by flaviendelangle** [comment]
I feel like you are doing something wrong.
If you follow the doc page I linked above, you should not have a listen to `onStateChange` or call a function after the rendering of the grid.

**Comment by lincolnmqs** [comment]
@flaviendelangle I can't access the doc you linked above.

![image](https://user-images.githubusercontent.com/30248434/150210292-7f1850f5-dcae-4c07-83c4-f32dd3e34c83.png)

**Comment by flaviendelangle** [comment]
Weird, it works on my computer... perhaps a problem with the preview on your browser language.

____

If you want to share your filters between your chart and your table tab, you should probably control the filters

```tsx
<DataGrid
  filterModel={this.state.filters}
  onFilterModelChange={newModel => this.setState(prevState => ({ ...prevState, filters: newModel })
/>
```

And if the format of the filters is not the same for the table and the charts, you can add a conversion step (which would be a lot easier with hooks, I must admit that I'm not used to work with classes anymore).
Something like:

```tsx
<DataGridWithChartFilterModel
  filterModel={this.state.filters}
  onFilterModelChange={newModel => this.setState(prevState => ({ ...prevState, filters: newModel })
/>


// And then `DataGridWithChartFilterModel` is just a wrapper to convert the filterModel
class DataGridWithChartFilterModel {
  static getDerivedStateFromProps(nextProps, prevState) {
    if (prevState.rawFilters !== nextProps.filterModel) {
      return {
        rawFilters: nextProps.filterModel,
        filterModel: convertFilterModelFromChartFormatToGridFormat(nextProps.filterModel),
    }
  }

  handleFilterModelChange = (newModel) => {
    const rawFilters = convertFilterModelFromGridFormatToChartFormat(newModel);
    this.props.onFilterModelChange(rawFilters);
  }

  render() {
    return (
      <DataGrid
        {...this.props}
        onFilterModelChange={this.handleFilterModelChange}
        filterModel={this.state.filterModel}
      />
    )
  }
}
```

____

But you should avoid using imperative apis unless you absolutely need to.

**Comment by flaviendelangle** [comment]
But we are entering React related topics, not DataGrid related topics here
For the DataGrid part, you should be good by passing a valid `filterModel` to the `filterModel` prop and updating your state with the `onFilterModelChange` prop.

**Comment by flaviendelangle** [comment]
- Do not access the state directly, always use a selector

```diff
-const filterModel = this.apiRef.current.state.filters.filterModel;
+const filterModel = gridFilterModelSelector(this.apiRef.current.state)
```

- Why use `deleteFilters` AND update manually your state ?

 Either  call `apiRef.current.deleteFilters` and the Grid will call `onFilterModelChange` to tell you to update your state
Or you update manually your state without calling `apiRef.current.deleteFilters`
But in your screen, you are calling `apiRef.current.deleteFilters`, the grid does not update its internal model because you are controlling it, instead it is calling your `onFilterModelChange`. 

Are you familiar with what a control mode is ?
