### ISSUE TITLE
Filter and sort state should be reset when providing new data (or at least ability to clear it)

### ISSUE THREAD

**Issue by kodeschooler** [mui-org/material-ui-x#3670]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I have a page with a drop down that fetches different data when an option is selected. And then it passes that _new_ data to the rows prop and shows the grid. I just noticed that if I set a filter/sort and then go get new data, the filter and sort are still active. I understand the reasoning behind this, but there must be a way to alter the behavior. Particularly because it's difficult to see that you have an active filter.

How can I simply remove the filter ? I want to access whatever logic runs when you click the delete icon in the default filter window (the x icon).

Or is there another way around this? I don't see any props or configurations to control this.  

It seems like such a small and useful option among tons of options provided in the library. 

### Expected behavior 🤔

It should remove a filter when I provide the grid with new data, or better yet, give me the option to do what the delete filter button does so I can do it on the user's behalf.  Or, lastly, provide an indication that a filter is set that the user can clearly see.  

Here is the basic idea of the component.

```
function GridExample() {
  const [data, setData] = useState([]); // for grid
  const [selectedData, setSelectedData] = useState(""); //id in dropdown

  useEffect(() => {
    async function getData() {
       const payload = await getGridData(selectedData);
       setData(payload.data); //replace w/new data
    }

    if (selectedData !== "") {
       getData();
    }
  }, [selectedData]);

  function handleDataSelectionChange(e){
     setSelectedData(e.target.value);
  }

  const gridColumns: GridColumns = [
     {
       field: "Id",
       headerName: "Id",
       width: 300,
       hide: true,
       hideable: false,
       filterable: false,
     },
     { field: "name", headerName: "Name", width: 300 },
     { field: "description", headerName: "Desc", width: 500 },
     {
       field: "enabled",
       headerName: "Enabled",
       type: "boolean",
       width: 150
       },
     ];

     if (data) {
       return (
           <div style={{ height: 650, width: "100%" }}>
              <div style={{ display: "flex", height: "100%" }}>
                 <div style={{ flexGrow: 1 }}>
                    <DataGrid 
                      columns={gridColumns} 
                      rows={data} 
                     />
                 </div>
               </div>
            </div>
         )
      }
  }
```

### Steps to reproduce 🕹

Steps:

1. Add a select menu with options to choose on a page with the DataGrid
2. Choose an option and onChange, run an effect to go get a list of data for the option selected: /api/things/{customerCode}
3. Put the response data into state and pass those rows into the rows prop of the DataGrid
4. Set a filter on a column. 
5. Choose a different option that runs the effect again to go get new data for the selected value.
6. Notice that the new data is filtered and that it's hard to see you have an active filter. 

### Context 🔦

We decided to use this grid and I replaced our old grid on all our list pages before I realize that the filter sticks. We love the grid. It would be fantastic if I could remove a filter! I hope it's just something I missed. 

### Your environment 🌎

<details>
  <summary>
    using Chrome
</summary>

```
  System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 97.0.4692.71
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.55)
  npmPackages:
    @emotion/react: ^11.6.0 => 11.6.0
    @emotion/styled: ^11.6.0 => 11.6.0
    @mui/base:  5.0.0-alpha.55
    @mui/icons-material: ^5.2.4 => 5.2.4
    @mui/lab: ^5.0.0-alpha.60 => 5.0.0-alpha.60
    @mui/material: ^5.1.1 => 5.1.1
    @mui/private-theming:  5.1.1
    @mui/styled-engine:  5.1.1
    @mui/styles: ^5.1.1 => 5.1.1
    @mui/system:  5.1.1
    @mui/types: ^7.1.0 => 7.1.0
    @mui/utils:  5.1.1
    @mui/x-data-grid: ^5.2.2 => 5.2.2
    @types/react: ^17.0.20 => 17.0.20
    react: ^17.0.2 => 17.0.2
    react-dom: ^17.0.2 => 17.0.2
    typescript: ^4.4.3 => 4.4.3
```
</details>

**Comment by kodeschooler** [comment]
@xiao why the thumbs down, what did I do or not do? A thumbs down isn't very helpful without a reason.

**Comment by flaviendelangle** [comment]
It depends a lot on your usecase.
If you paginate on the server and go the the next page, you clearly don't want to reset the filtering and sorting models.

You can control those models and clear them when you update the rows with `sortModel` / `onSortModelChange` and `filterModel` / `onFilterModelChange`.

**Comment by kodeschooler** [comment]
@flaviendelangle thanks for the helpful response. That makes sense. I will try this tonight.

**Comment by kodeschooler** [comment]
@flaviendelangle  that doesn't work. getDefaultFilterModel() does clear the filter data. The filterModel looks like: items[] after resetting to default, but the UI does not reflect this state. When I bring up a new filter after resetting, it shows the previous text I inserted into the value field.

**Comment by flaviendelangle** [comment]
Could you give me an example using [Codesandbox](https://codesandbox.io/s/datagridpro-v5-quick-start-54iz1) ?

**Comment by kodeschooler** [comment]
@flaviendelangle  This did work, it was something wrong with my complicated component. Thanks so much!
