### ISSUE TITLE
Data Grid Pro component with treeData prop returns error "TypeError: Cannot read properties of undefined (reading 'children')"

### ISSUE THREAD

**Issue by jaballogian** [mui-org/material-ui-x#3672]
### Order ID 💳

29446

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

`DataGridPro` component with `treeData` prop returns error:
```
TypeError
Cannot read properties of undefined (reading 'children')
```

### The problem in depth 🔍

I'm using a `Switch` component to switch the `DataGridPro` component mode between grouped and ungrouped as seen in the screenshot below.

![image](https://user-images.githubusercontent.com/24468466/150354967-5e54d586-c93d-4fa2-8545-1ea3fcdf8651.png)

If the `Switch` is false, the `DataGridPro` doesn't group the rows by column.
If the `Switch` is true, the `DataGridPro` groups the rows by status column ("offline" and "online").

The initial `Switch` component state is false. So the `DataGridPro` component doesn't group the rows.

Here is one of the initial row items:
```javascript
{
    status: "ONLINE",
    hierarchy: ["Sarah"],
    jobTitle: "Head of Human Resources",
    recruitmentDate: new Date(2020, 8, 12),
    id: 0
},
```

and here is the modified row item if the `Switch` component state is true:
```javascript
{
    status: ["ONLINE"],
    hierarchy: ["Sarah"],
    jobTitle: "Head of Human Resources",
    recruitmentDate: new Date(2020, 8, 12),
    id: 0
},
```
I change the status property into an array to support the `DataGridPro` row group by column feature.

The first run was fine, but there would be an error below if we turn the `Switch` component state into true.
```
TypeError
Cannot read properties of undefined (reading 'children')
```

If we print the value of the updated rows (using `useMemo` hook from the `Demo` component or using `useEffect` hook from the `NewDemo` component in the playground/codesandbox below), the rows value was updated (from `status: "ONLINE"` into status: `["ONLINE"]`)

### Context 🔦

**Here is the condition I want:**
I want to group the rows by status column if the `Switch` component state is true and ungroup the rows if the `Switch` component state is false.

Here is the playground: https://codesandbox.io/s/github-mui-data-grid-grouping-lu7bp

### Your environment 🌎

<details>

Browser: Chrome 97
NPM: version 8.1.2
Node: version 16.13.1
Dependencies: stated in the playground
</details>

**Comment by jaballogian** [comment]
This issue is similar to this issue https://github.com/mui-org/material-ui-x/issues/3661#issue-1107066651 but I think that issue doesn't provide enough information, explanation, and solution.

**Comment by flaviendelangle** [comment]
I agree that the error message is not explicit enough.
I will look at the part that crashes and add a clear error :+1:

**Comment by flaviendelangle** [comment]
Concerning the crash itself, the issue was that you had several identical paths.
I will add a clear error message :+1:

**Comment by jaballogian** [comment]
Thanks a lot for the demo and the explanation.
