### ISSUE TITLE
[DataGridPro] Box with number of selected filters does not update

### ISSUE THREAD

**Issue by lincolnmqs** [mui-org/material-ui-x#3683]
### Order ID 💳

35305

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I created a list of filters to facilitate removal and display, but when excluding them, do not add the box with the number of filters. It doesn't update.

### The problem in depth 🔍

The code is incomplete for data display, but all the DataGrid, filter list display and filter functionality are present: 
https://codesandbox.io/s/xenodochial-newton-qj6fv?file=/src/App.js

Box with number of selected filters does not update:
![image](https://i.ibb.co/DgYBC0h/Peek-20-01-2022-17-01.gif)

### Context 🔦

I created a list of filters to facilitate removal and display, but when excluding them, do not add the box with the number of filters. It doesn't update.

I'm using manipulating the filters manually through a state of the filterModel, and using the onFilterModelChange to monitor the actions.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by DanailH** [comment]
@lincolnmqs thanks for reporting this! I checked it and at first, glance thought that using `apiRef.current.setFilterModel` will fix the issue but no. We will need to have e further investigation.

**Comment by lincolnmqs** [comment]
@DanailH i thank you for the support. Is it a problem with the way I developed it? I thought that using the filterModel to listen to my state, I would have this sync.

**Comment by flaviendelangle** [comment]
Several issues here:

1. You should never mutate the state. Even if you do a `setState` to force a re-render. Components can listen to reference change on this objects and not trigger a refresh if you mutate.

```diff
  selectedFilters = () => {
    let filterModel = this.state.objFilters;
    const selectedFilters = {};

    if (filterModel.items.length) {
      filterModel.items.forEach((filter) => {
-        this.state.selectedFilters[filter.columnField] = this.filtersName[ // do
+       selectedFilters[filter.columnField] = this.filtersName[ // do
          filter.columnField
        ];
      });
    }

    this.setState({ selectedFilters });
  };
```

Same on `deleteFilter`

2. `setState` in sometime async, so accessing the `this.state.objFilters` in `selectedFilters` just after setting it in `onFilterChange` can't work, you'll get the previous value.


Here is a fixed example: https://codesandbox.io/s/amazing-https-u7zvl?file=/src/App.js

With all my respect, I think you strengthen your React basics.
Being able to spot anti-pattern will help you a lot in this kind of scenario.

**Comment by lincolnmqs** [comment]
Thank you very much for the examples and explanations!
