### ISSUE TITLE
[question] CSV Format read instantly by Excel

### ISSUE THREAD

**Issue by bjarnewilhelm** [mui-org/material-ui-x#3689]
### Order ID 💳

#30058

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

In some languages (e.g. German), the .csv format of Data Grid Pro cannot be opened with Excel by double-clicking on file.

### The problem in depth 🔍

The .csv file is formatted with comma. In some languages, the .csv will only be recognized by Excel if it's formatted with a semicolon.
Is there a way you can help? Can this be connected to the localisation of the Data Grid maybe?
![image](https://user-images.githubusercontent.com/72257068/150565781-57a71136-ae73-42d9-b66d-e3d45d49a2a1.png)
a 

### Context 🔦

For our user, it is just very complicated to reformat the file to be able to see it as a table in Excel.
There are ways in Excel to do this but it's just not an acceptable way.
The .csv export is very critical for us and our product and we had a lot of customers already complaining about this.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by cherniavskii** [comment]
Hey @bjarnewilhelm 
You can change CSV export delimiter like this:
```jsx
<DataGrid componentsProps={{ toolbar: { csvOptions: { delimiter: ';' } } }} />
```

Here's a demo: https://codesandbox.io/s/exportdefaulttoolbar-material-demo-forked-0xq2i?file=/demo.tsx
