### ISSUE TITLE
[DataGrid] Focus reverts to last focused DataGrid cell on re-rendering component

### ISSUE THREAD

**Issue by mike-prom** [mui-org/material-ui-x#3712]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If you click into a cell inside the DataGrid, then tab to focus on a new element, a state update on the parent component will cause focus to revert to the last focused cell in the DataGrid.

### Expected behavior 🤔

Focus should remain on the element you tabbed to.

### Steps to reproduce 🕹

Steps:

1. Open https://codesandbox.io/s/datagriddemo-material-demo-forked-gwzvw?file=/demo.tsx with Chrome.
2. Click into any cell within the table body.
3. Tab to the "+" button below the table.
4. Hit Enter to activate the button. This will cause the counter state to update, which has the side effect of reverting focus to the last focused cell in the table

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Linux 5.10 Debian GNU/Linux 9 (stretch) 9 (stretch)
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/src/app/node_modules/.bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @emotion/react: ^11.6.0 => 11.6.0
    @emotion/styled: ^11.6.0 => 11.6.0
    @mui/base:  5.0.0-alpha.55
    @mui/icons-material: ^5.2.1 => 5.2.1
    @mui/lab: ^5.0.0-alpha.55 => 5.0.0-alpha.55
    @mui/material: ^5.1.1 => 5.1.1
    @mui/private-theming:  5.1.1
    @mui/styled-engine:  5.1.1
    @mui/system:  5.1.1
    @mui/types:  7.1.0
    @mui/utils:  5.1.1
    @mui/x-data-grid: ^5.2.1 => 5.2.1
    @types/react:  17.0.11
    react: ^16.13.1 => 16.14.0
    react-dom: ^16.13.1 => 16.14.0
    typescript: ^4.3.5 => 4.3.5```
</details>


### Order ID 💳 (optional)

_No response_

**Comment by alexfauquette** [comment]
Hi, thanks for the nice minimal example you provided :)
