### ISSUE TITLE
[DataGrid] Adding Select component to each row cause the error when pagination

### ISSUE THREAD

**Issue by minhnhat10** [mui-org/material-ui-x#3713]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I want to add select component to each row in datagrid. It work fine, but when I paginate it's still save the select state of previous page. 
![Screen Shot 2022-01-23 at 9 54 18 PM](https://user-images.githubusercontent.com/33271256/150684431-99e99c25-f9de-41dd-b360-61b0c15ce96b.png)
![Screen Shot 2022-01-23 at 9 54 58 PM](https://user-images.githubusercontent.com/33271256/150684468-f40ab584-4ded-43b7-b0b1-01698c87cbfc.png)

### Expected behavior 🤔

It should be a fresh state for each row. How can I fix this behavior. Thank you very much for any advice

### Steps to reproduce 🕹
https://codesandbox.io/s/datagrid-v5-quick-start-forked-3y7qm?file=/src/App.tsx1.
2.
3.
4.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Comment by alexfauquette** [comment]
Hi,

I'm wondering, why do you not use the column type [`'singleSelect'`](https://mui.com/components/data-grid/columns/#column-types) instead of writing your own select cell?

Without a code sandbox minimal example, it will be impossible for use to reproduce and fix your bug.

**Comment by minhnhat10** [comment]
Hi, that's my bad. I missed that part. Thank you for you suggestion. Anyway, I updated my code above. Could you take a look at it why this bug is occurred. I don't understand why behavior of this working differently on my browser. In the sandbox, you scroll and your select will disappear but when on my browser it work as I describe above. I'm sorry if my code look silly. Thank you again for your answer.

**Comment by alexfauquette** [comment]
You never save the selected data, so when the component is unmounted, it lost its value
That is a question about state management, you will find more help from the community by asking your questions on https://stackoverflow.com/
