### ISSUE TITLE
Class pinnedColumns can't be overwritten

### ISSUE THREAD

**Issue by ak-mid** [mui-org/material-ui-x#3716]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I try to style the pinnedColumns class with a customer style via createTheme and ThemeProvider.
Other styles can be overwritten but the pinnedColumns class doesn't seem to be accessible.

```javascript
 MuiDataGrid: {
          styleOverrides: {
            // This works
            root: {
              backgroundColor: '#fff',
            },
            // This works too
            pinnedColumnHeaders: {
              backgroundColor: '#fff',
              boxShadow: 'none',
            },
            // This doesn't work
            pinnedColumns: {
              backgroundColor: '#fff',
              boxShadow: 'none',
            },
          },
        },
```

### Expected behavior 🤔

We should be able to theme pinnedColumns too.

### Order ID 💳 (optional)

35878

**Comment by alexfauquette** [comment]
Thanks for reporting this bug. If someone of team is interested in having a look I made a minimal reproduction

https://codesandbox.io/s/disablecolumnpinningbuttons-material-demo-forked-33vk5?file=/demo.tsx

**Comment by m4theushw** [comment]
We forgot to add the overrides resolver to allow these classes to be overridden by the theme.

https://github.com/mui-org/material-ui-x/blob/7a2e380c01a67b8ad16a7a3443bf3ecebd93706e/packages/grid/x-data-grid-pro/src/DataGridProVirtualScroller.tsx#L86-L88

As a workaround, you can do the following:

```tsx
const theme = createTheme({
  components: {
    MuiDataGrid: {
      styleOverrides: {
        root: {
          backgroundColor: "#ad2424",
          "& .MuiDataGrid-pinnedColumns": {
            backgroundColor: "blue"
          }
        }
      }
    }
  }
});
```

**Comment by ak-mid** [comment]
Thanks for the workaround and for fixing the issue so quickly.
