### ISSUE TITLE
onColumnVisibilityModelChange gets triggered when columnVisibilityModel is provided and column width is changed.

### ISSUE THREAD

**Issue by tielushko** [mui-org/material-ui-x#3725]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The onColumnVisibilityModelChange event gets fired when provided with initial columnVisibilityModel and resizing column width.

In my application, I have the custom width preferences that I store for the columns. When I use the controlled columnVisibilityModel however, the resize of the column triggers the onColumnVisibilityModelChange.

Please see the sandbox here: 
[Sandbox](https://codesandbox.io/s/columnvisibilitymodelchange-triggers-oncolumn-resize-70ji9?file=/demo.js:9570-9597 )

### Expected behavior 🤔

Resizing the column should not trigger the onColumnVisibilityModelChange event.

### Steps to reproduce 🕹

Steps:

1. Hide any controlled column.
2. Resize any column.
3. In console, check the triggered column event and noticed that the changes applied to visibility got reset.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

31986

**Comment by tielushko** [comment]
Update: Here is the cleaner sandbox that indicates the issue with visibility change getting triggered on resize of the column. Using DataGridPro.

https://codesandbox.io/s/visiblecolumnsmodelcontrolled-material-demo-forked-sisyo?file=/demo.js

**Comment by cherniavskii** [comment]
Thanks @tielushko !
It's a regression introduced in v5.3.0. Cannot reproduce the issue in 5.2.2 or earlier.

**Comment by flaviendelangle** [comment]
Good catch, I'm resetting the visibility status of all the columns when updating just on column.
I'll make a quick fix on the next release :+1:

**Comment by tielushko** [comment]
Thanks @flaviendelangle for your quick effort!

**Comment by joaquim21acj** [comment]
I have this version on my project and the issue still remains. 

"@mui/x-data-grid-premium": "^5.17.26",

**Comment by sandronominal** [comment]
@flaviendelangle I'm also experiencing same issue.
"@mui/x-data-grid-premium": "^7.21.0",

**Comment by flaviendelangle** [comment]
@michelengelen I let you handle this one :pray:
