### ISSUE TITLE
[DataGrid] Wrong error when columns.type is unknown

### ISSUE THREAD

**Issue by FedeBev** [mui-org/material-ui-x#3749]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

If `colums[n].type` is unknown, the following error is thrown:

```Warning: `NaN` is an invalid value for the `width` css style property.```

### Expected behavior 🤔

Appropriate error message, such as `Unknown column type 'wrong'`

### Steps to reproduce 🕹

```tsx
const columns: GridColDef[] = [
  { field: "id", headerName: "ID" },
  { field: "foo", headerName: "Foo", type: "strin" // <- wrong type},
];

const data = [
  { id: "1", foo: "bar" },
  { id: "2", foo: "bar" },
];

function Test() {
  return (
    <div style={{ height: "100%", width: "100%" }}>
      <DataGrid rows={data} columns={columns} />
    </div>
  );
}
```

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Linux 5.13 Ubuntu 20.04.3 LTS (Focal Fossa)
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Firefox: Not Found
  npmPackages:
    @emotion/react: ^11.7.1 => 11.7.1 
    @emotion/styled: ^11.6.0 => 11.6.0 
    @mui/base:  5.0.0-alpha.66 
    @mui/icons-material: ^5.3.1 => 5.3.1 
    @mui/material: ^5.3.1 => 5.3.1 
    @mui/private-theming:  5.3.0 
    @mui/styled-engine:  5.3.0 
    @mui/system: ^5.3.0 => 5.3.0 
    @mui/types:  7.1.0 
    @mui/utils:  5.3.0 
    @mui/x-data-grid: ^5.3.0 => 5.3.0 
    @types/react: ^17.0.38 => 17.0.38 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ^4.5.5 => 4.5.5 
```
</details>

**Comment by alexfauquette** [comment]
When populating the column definition using its type, we check is `type` property is defined. We should also check that `columnTypes[type]` is defined. If it is not defined, I propose to throw the error and use `DEFAULT_GRID_COL_TYPE_KEY` in production enviromnment

https://github.com/alexfauquette/material-ui-x/blob/master/packages/grid/_modules_/grid/hooks/features/columns/gridColumnsUtils.ts#L79:L90

**Comment by jpgilchrist** [comment]
I've run into this from time to time myself. I was very confused at first, but I keep typing `type: 'timestamp'` instead of `type: 'dateTime'` and having found this issue (was about to submit an issue), it all makes sense now. 

A better error, would be helpful to someone new, otherwise they'll hopefully find this issue.
