### ISSUE TITLE
[DataGrid] Move the ColumnsPanel to the right side of the DataGrid?

### ISSUE THREAD

**Issue by zprpic** [mui-org/material-ui-x#3755]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

DataGrid or a custom ColumnPanel component should contain a prop that allows you to move the ColumnPanel to a different position. 
 
At the moment, the ColumnPanel's default position is in the top-left corner of the DataGrid below the ColumnHeaders.
 
I have discovered two ways to move the ColumnPanel, but both ways mess with the rendering of the ColumnPanel and must be hardcoded. What if you are using your DataGrid in two different places in your app and in one place the table is shorter/smaller/tighter? The styling from the code examples is going to mess up everything even more.

### Examples 🌈

```
div[role='tooltip'] {
    inset: 0px 0px 50px 75% !important;
}
```

and

```
div[role="tooltip"] {
  right/top/etc: -60px !important;
}
```

**Comment by alexfauquette** [comment]
You can have a look at the demo on how to move the filter panel
https://mui.com/components/data-grid/filtering/#custom-filter-panel

The idea is to use `componentsProps` to pass new props to the panel. Modifications are applied to both the filter panel and the column panel. 

In the example, we set `anchorEl: filterButtonEl`. But you can override other props of the [Popper component](https://mui.com/components/popper/)

**Comment by zprpic** [comment]
Great solution! Works flawlessly. Thank You!

**Comment by vishnumurugesh03** [comment]
@alexfauquette  I am also facing the same issue but the tool tip is only coming but the drop down is not found,
