### ISSUE TITLE
Should MUI provide an Emoji picker?

### ISSUE THREAD

**Issue by nigel-loops** [mui-org/material-ui-x#3759]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I was intrigued to see how much interest there might be for supporting a MUI v5 emoji picker like "emoji-mart" or "emoji-picker-react"  in the premium components for MUI.

The current react libraries which are 'Emoji mart' and 'emoji-picker'react'  seem heavily influenced by Slacks emoji picker. 
Looking at the very basic foundations from a UI perspective- mui v5 seems to have a component for most elements to create the basic UI/UX of a picker. Now, I completely understand the complexity of how advanced and feature heavy an emoji picker can get, but I was wondering if this has been discussed by staff or contributors with in the mui community.

I feel an emoji picker maybe a good addition to attract more customers to purchase the premium version of mui. At the moment some of the "advanced components" are very table and data heavy and this maybe a nice component to consider later on for your road map.

### Examples 🌈

https://github.com/missive/emoji-mart

https://www.npmjs.com/package/emoji-picker-react ( https://stackblitz.com/edit/emoji-picker-react?file=index.js )

### Motivation 🔦

I am currently migrating from material ui v4 to v5 and implementing light and dark themes as a new feature to a platform I currently maintain. We use emoj-mart to allow users to add emojis to their comments. Now the issue is that tweaking the light and dark styles from an external css file to match my mui them is very labouring and feels messy.

**Comment by joserodolfofreitas** [comment]
Thanks for taking the time to put up the suggestion, @nigel-loops! 
We currently don't have plans for an "Emoji Picker" component, but I understand your pain in adapting third-party libraries.
I'm adding the "waiting for 👍 (upvotes) " label, to confirm this is a pain shared by other users in the community as well.

**Comment by oliviertassinari** [comment]
I'm closing to signal that it's unlikely. Still, the "waiting for upvotes" label is still applied, so up for considerations.

**Comment by nigel-loops** [comment]
Was checking back on this whether anything has changed with this request. I compared other "waiting for 👍" marked issues and a lot don't have many thumbs up. this original feature request now has 39.

@joserodolfofreitas 

thanks for all your effort with MUI!

**Comment by oliviertassinari** [comment]
Interesting, it's more upvotes than what I would have expected.

**Comment by oliviertassinari** [comment]
Ok, maybe we should work on this.

We have an example in https://base-ui.com/react/components/autocomplete#grid-layout

https://github.com/user-attachments/assets/748cd4cd-0c50-48b8-8572-159c4da7141f

We could imagine a more developed version.
