### ISSUE TITLE
Data Grid on focusout for checkbox

### ISSUE THREAD

**Issue by radu-nicoara-bayer** [mui-org/material-ui-x#3767]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Inside of a `DataGrid` with component with `checkboxSelection`, after selecting a checkbox, on `focusout`, the focus comes back to the selected checkbox. 
But this interfere with our users, as if they select some rows, and then click on an input on another side of the page (in order to continue their data import) the focus switches back to the previously selected row.

Could there be a way to turn this property off?

### Motivation 🔦

We have an application that we use for data import. The users select a list of files in the data grid, and then need to fill in some data about the import. Every time that they click on the textarea for the description, they get scrolled back to the checkbox, so they have to go to the textarea again, which is not ideal.

**Comment by cherniavskii** [comment]
Hi @radu-nicoara-bayer 
Please provide a minimal example reproducing the issue.
You can start with [this template](https://codesandbox.io/s/datagrid-v5-quick-start-54iz1) or create one from scratch.
Thank you!

**Comment by radu-nicoara-bayer** [comment]
I pulled the new version this morning, and the issue is gone. Please close the ticket

**Comment by cherniavskii** [comment]
@radu-nicoara-bayer Great to hear!
I think it was fixed by #3501
