### ISSUE TITLE
[DataGrid] Create prop to map required id to another field in the data set

### ISSUE THREAD

**Issue by scollins33** [mui-org/material-ui-x#378]
- [x ] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Related to: https://github.com/mui-org/material-ui-x/issues/342#issuecomment-700760440

As a Developer my data set may contain a uniquely identifying field that is not called "id" (i.e. "application_id"). If the data set is missing an "id" field you receive and error: 

> Uncaught Error: Material-UI: The data grid component requires all rows to have a unique id property. A row was provided without in the rows prop:

Ideally we should be able to pass some kind of id override as a prop to set the field that should be used as the unique identifier.

## Examples 🌈

In the below data example, the "app_id" is the unique field:

{
"__typename":"Application",
"app_id": "...",
"app_business_id": "...",
"app_support_team_dl": "...",
"app_support_model": "...", 
app_status": "..."
}

How to implement as a prop:

<DataGrid rows={data} columns={columns} id="app_id" />

## Motivation 🔦

The backend team has provided me data without an "id" field. So either I have to run a loop to add an "id" field or DB changes need to be made. It feels like an odd work around to have to run a potentially performance taxing loop just to add a fake field to each entry. Requesting DB changes is also potentially a nightmare depending on team requirements.

**Comment by oliviertassinari** [comment]
Benchmark:

- no row id requirement: https://www.telerik.com/kendo-react-ui/components/grid/data-operations/local-operations/
- get row id method: https://ag-grid.com/javascript-grid-row-node/#application-assigned-ids

**Comment by denvercoder** [comment]
I had the same issue. I was getting "examId" from the API and I had to basically map over our dataset and create a new field like this:

```
result.map((exam) => {
    exam['id'] = exam.examId
})

```

I did a performance analysis, (console logged the time in and time out)
and found that this only took 2ms for 1680 rows so I'm okay with the solution for now
but it would be nice to have a construct like this:

```
const columns = [
    {
        field: 'application_id',
        hide: true,
        identity: true
    },
]

```

**Comment by denvercoder** [comment]
Couldn't we just do something like this?

```
function getIdField(params) {
    return `${params.getValue('examId') || ''`
}

const columns = [
    {
        field: 'id',
        hide: true,
        valueGetter: getIdField
    }
]
```

**Comment by denvercoder** [comment]
> Couldn't we just do something like this?
> 
> ```
> function getIdField(params) {
>     return `${params.getValue('examId') || ''`
> }
> 
> const columns = [
>     {
>         field: 'id',
>         hide: true,
>         valueGetter: getIdField
>     }
> ]
> ```

Nope, this doesn't work. I still get that error:

Error: Material-UI: The data grid component requires all rows to have a unique id property.

**Comment by oliviertassinari** [comment]
I have added the `waiting for users upvotes` tag. I'm closing the issue as we are not sure enough people are looking for such capability. So please upvote this issue if you are. We will prioritize our effort based on the number of upvotes.

**Comment by shanemiller89** [comment]
Our team is looking to transition to using this grid, however some data sets lacking a field named `id` was the first issue we ran into. 
 
 It would be much easier for us to simply change which column should be used as the unique identifier, rather than change our data sets to accommodate this naming convention, as those data sets in particular already have a column being used as the unique identifier.

**Comment by oliviertassinari** [comment]
The next release will include a `getRowId` prop (v4.0.0-alpha.19). Using it comes with two drawbacks: the grid needs to clone each row to add the `id` key, which adds CPU pressure. It also change the reference of the input row so referential comparison can't be done. We have identified way to solve these drawback in the grid but didn't as too costly. We need to know more about the value it could have for developers first.

**Comment by me82852578** [comment]
# PR

## Summary 💡
Provide an API to specify a customized row data id.



## Examples 🌈
```javascript
import * as React from 'react';
import { DataGrid } from '@material-ui/data-grid';

export default function RowIdAccessorDemo() {
  return (
    <div style={{ height: 250, width: '100%' }}>
      <DataGrid
        rowIdAccessor="customUniKey"
        columns={[
          { field: 'customUniKey', width: 150 },
          { field: 'name', width: 200 },
        ]}
        rows={[
          { customUniKey: 'uniNo-1', name: 'React' },
          { customUniKey: 'uniNo-2', name: 'Material-UI' },
        ]}
      />
    </div>
  );
}
```




## Motivation 🔦

Like everyone else, I also encountered this problem. The data obtained from the server doesn't have an id.
Therefore I fork source, solved and make a pr, hope to provide some help.

- Pros:
 1. Increase the level of customizability
 2. Simpler to customize the logic

- Cons:

**Comment by fluxquantum** [comment]
@oliviertassinari Thank you for the quick turnaround on this and trying to address the potential performance concerns. I appreciate the value that the datagrid module provides. 

I wanted to express that this is an extremely helpful feature to have as many users will be using this tabular display for visualizing their database result sets. Several of our data models have unique key fields that are also functional values. 

Without getting too deep into data architecture there are many tables that are designed with sequence generated ids but those columns per best practice will often being named after the table. Being able to map the database model with the data structure in the front end application will be a helpful feature semantically as well.

Thank you again for your time and contribution.

**Comment by oliviertassinari** [comment]
@fluxquantum Thanks for sharing your use case. 

A note, we have a follow up bug with the current implementation: #1119.
