### ISSUE TITLE
isRowSelectable option brakes rerendering of a table with a new set of data

### ISSUE THREAD

**Issue by olegbolden** [mui-org/material-ui-x#3797]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Hello all.
First of all, I'd like to thank all who is working on this awsome framework that saved me a lot of time!
I use `checkboxSelection` prop to select rows in order to remove them from the table.
After sending api call with the selected ids I get a new set of data without selected items and rerender my table.
It worked fine in many places of my project.
Some time ago I needed to restrict selection of specific rows with `isRowSelectable` prop of the DataGrid in order to prevent them from deleting. And it also works. But now, when I select rows allowed for selection (and therefore for deleting) and make api call I get an error like `Uncaught Error: No row with id #108275096 found` and table crashes. This very row id is deleted and of course absent in a new set of data. I wonder why DataGrid tries to render this item.
If I remove `isRowSelectable` prop, deleting works flawlessly. 
I appreciate any help on solving this problem.

![error](https://user-images.githubusercontent.com/18537369/151766470-362c0022-f7b2-437b-ae7f-4cde66e4f25e.png)

**Comment by flaviendelangle** [comment]
Hi,

Which version are you using ?
You problem looks somehow like #3647 which was fixed in v5.4

**Comment by olegbolden** [comment]
Thank you!
It works after upgrading to 5.4.0
I was using 5.3.0 and thought it was the latest version.
