### ISSUE TITLE
[DataGrid] Doesn't seem to work within a Grid component

### ISSUE THREAD

**Issue by denvercoder** [mui-org/material-ui-x#382]
- [x ] The issue is present in the latest release.
- [ x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When you add the DataGrid inside of a Grid container it does what you would suspect. But if you nest it inside of

Grid container
    Grid item

It doesn't show up on the page.

Even adding a div around it with a height and width doesn't help.

## Expected Behavior 🤔

I would expect that if I am using Grid to layout my entire website adding a DataGrid control
to that Grid layout wouldn't affect the DataGrid.

## Steps to Reproduce 🕹

If you look at this CodeSandbox (https://codesandbox.io/s/musing-lalande-8e6bx?file=/src/Demo.js)

I have three examples. 

1) DataGrid inside of Grid container -> Grid item and it has a div with height and width but doesn't show the DataGrid
2) DataGrid inside of JUST a Grid container and it displays
3) DataGrid with no Grid just a wrapping div and it does display.

Steps:

1. Add Grid, DataGrid components to import
2. Add Grid, DataGrid components to file
3. Nest the DataGrid inside of Grid container and Grid item tags

## Context 🔦

We're using Grid to layout the entire project. When I nest the DataGrid inside of 

Grid container
    Grid item

tags the DataGrid doesn't display. This means I might have to just wrap the DataGrid in a div which
could effect how my page looks responsively.

## Your Environment 🌎

I see the behavior using the Official Material UI Codesandbox:

https://codesandbox.io/s/musing-lalande-8e6bx?file=/src/Demo.js

**Comment by oliviertassinari** [comment]
@denvercoder Nice, thanks for the report. There are a couple of elements we can improve here.

First we can display a warning:

```diff
diff --git a/packages/grid/_modules_/grid/GridComponent.tsx b/packages/grid/_modules_/grid/GridComponent.tsx
index a6900c2e..259c6428 100644
--- a/packages/grid/_modules_/grid/GridComponent.tsx
+++ b/packages/grid/_modules_/grid/GridComponent.tsx
@@ -132,6 +132,19 @@ export const GridComponent = React.forwardRef<HTMLDivElement, GridComponentProps
         );
       }

+      if (size.width === 0) {
+        gridLogger.warn(
+          [
+            'The parent of the grid has an empty width.',
+            'You need to make sure the container has an intrinsic width.',
+            'The grid displays with a width of 0px.',
+            '',
+            'You can find a solution in the docs:',
+            'https://material-ui.com/components/data-grid/rendering/#layout',
+          ].join('\n'),
+        );
+      }
+
       gridLogger.info('resized...', size);
       apiRef!.current.resize();
     },
diff --git a/packages/grid/_modules_/grid/components/AutoSizer.tsx b/packages/grid/_modules_/grid/components/AutoSizer.tsx
index aa697681..143b4f53 100644
--- a/packages/grid/_modules_/grid/components/AutoSizer.tsx
+++ b/packages/grid/_modules_/grid/components/AutoSizer.tsx
@@ -18,12 +18,10 @@ export interface AutoSizerProps extends Omit<React.HTMLAttributes<HTMLDivElement
   children: (size: AutoSizerSize) => React.ReactNode;
   /**
    * Default height to use for initial render; useful for SSR.
-   * @default 0
+   * @default null
    */
   defaultHeight?: number;
   /**
    * Default width to use for initial render; useful for SSR.
-   * @default 0
+   * @default null
    */
   defaultWidth?: number;
   /**
@@ -55,8 +53,8 @@ export const AutoSizer = React.forwardRef<HTMLDivElement, AutoSizerProps>(functi
 ) {
   const {
     children,
-    defaultHeight = 0,
-    defaultWidth = 0,
+    defaultHeight = null,
+    defaultWidth = null,
     disableHeight = false,
     disableWidth = false,
     nonce,
@@ -65,7 +63,7 @@ export const AutoSizer = React.forwardRef<HTMLDivElement, AutoSizerProps>(functi
     ...other
   } = props;

-  const [state, setState] = React.useState({
+  const [state, setState] = React.useState<{ height: number | null; width: number | null }>({
     height: defaultHeight,
     width: defaultWidth,
   });
@@ -153,7 +151,7 @@ export const AutoSizer = React.forwardRef<HTMLDivElement, AutoSizerProps>(functi
       }}
       {...other}
     >
-      {state.height === 0 && state.width === 0 ? null : children(childParams)}
+      {state.height === null && state.width === null ? null : children(childParams)}
     </div>
   );
 });
```

<img width="463" alt="Capture d’écran 2020-10-06 à 19 04 18" src="https://user-images.githubusercontent.com/3165635/95236074-c271dc80-0806-11eb-95db-77693cfb3e19.png">

Second, we can improve the documentation.

```diff
diff --git a/docs/src/pages/components/data-grid/rendering/rendering.md b/docs/src/pages/components/data-grid/rendering/rendering.md
index 65af84e4..b58ebe40 100644
--- a/docs/src/pages/components/data-grid/rendering/rendering.md
+++ b/docs/src/pages/components/data-grid/rendering/rendering.md
@@ -176,6 +176,12 @@ const columns: Columns = [

 By default, the grid has no intrinsic dimensions. It occupies the space its parent leaves.

+> ⚠️ When using % (**percentage**) for your height or width.<br>
+<br>
+You need to make sure the container you are putting the grid into also has an intrinsic dimension.
+The browsers fit the element according to a percentage of the parent dimension.
+If the parent has no dimensions, then the % will be zero.
+
 ### Flex layout

 It's recommended to use a flex container to render the grid. This allows a flexible layout, resizes well, and works on all devices.
```

<img width="884" alt="Capture d’écran 2020-10-06 à 19 11 17" src="https://user-images.githubusercontent.com/3165635/95236876-c5b99800-0807-11eb-8496-6863c24a6ce4.png">

So in your case, set the `<Grid item>` a width

```diff
      <Grid container>
-       <Grid item>
+       <Grid item xs>
          <div style={{ height: "400px", width: "100%" }}>
            <DataGrid rows={rows} columns={columns} />
          </div>
        </Grid>
      </Grid>
```

**Comment by oliviertassinari** [comment]
I have added the "good first issue" label. It's up for grab by any member of the community, it will improve the DataGrid as well as the XGrid components. Note that if you work on the problem, we will ask you to sign a CLA, similar to https://code.facebook.com/cla/ before merging.

**Comment by RobertAron** [comment]
Hey, I think I'd like to pick this up!
