### ISSUE TITLE
[DataGrid] Lazy loading, Infinite Loading

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#404]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Provide a way to only load a fraction of the data, to prioritize data loading for the visible parts of the screen **without pagination**.

## Examples 🌈

During the very first iteration on the data grid https://github.com/mui-org/material-ui/pull/18872, we come up with the following API: 

```tsx
export interface DataProviderGetListParams {
  sorting: SortingType;
  pagination: {
    start: number;
    end: number;
  };
}

export interface DataProviderType {
  getList: (params: DataProviderGetListParams) => Promise<any[]>;
}

export interface DataGridProps extends StandardProps<React.HTMLAttributes<HTMLDivElement>, DataGridClassKey> {
  /**
   * Manage the communication with the data store.
   */
  dataProvider?: DataProviderType;
```

Where the `dataProvider` default to a value dedicated to client-side operations with the `rows` prop. It can probably be improved.

## Motivation 🔦

It's a sub-problem of #240.

## Benchmark

- https://bvaughn.github.io/react-virtualized/#/components/InfiniteLoader
- https://ag-grid.com/javascript-grid-server-side-model/
- https://www.telerik.com/kendo-react-ui/components/grid/data-operations/odata-server-operations/
- https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/remote_data_operations.html
- https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/lazy-loading/

**Comment by dtassone** [comment]
We already handle server side pagination
 > /story/x-grid-tests-pagination--server-pagination-with-api
 > /story/x-grid-tests-pagination--server-pagination-with-event-handler

You can override the number of rows in `options.rowCount`

We don't have the infinite scrolling behaviour, which will just consist of hooking the virtualisation to the user server, so we will tell the server which index range we need to render.
We also need to add the infinite rowCount behaviour, so the scrollbar can resize the more we add rows...

**Comment by austinlangdon** [comment]
We just started using XGrid and it's a terrific component! But no infinite scroll API is disappointing to see - we happen to utilize infinite scroll over pagination in most of our app.

We've been using this library for infinite scrolling needs. Perhaps something to benchmark?

https://github.com/danbovey/react-infinite-scroller

**Comment by mbrookes** [comment]
> no infinite scroll API is disappointing to see

@austinlangdon Glad to have you as a user, and thanks for the feedback. We do try to make it clear that the product is still in development, both on the product page in the store, and in the documentation. Is there something we should change to make that clearer?

**Comment by jlil** [comment]
I was going through the docs and this was not clear to me either.
Reading `rows virtualization` and `Server-side data` makes one believe infinite scroll/loading is supported. 
This feature is also a blocker for our project.

**Comment by vd-yasir** [comment]
@austinlangdon  can you share how you used xgrid with 
https://github.com/danbovey/react-infinite-scroller

**Comment by austinlangdon** [comment]
> @austinlangdon can you share how you used xgrid with
> https://github.com/danbovey/react-infinite-scroller

Our solution was to update our API request to get a large amount of data from our API as recommended (~1000 records). Most likely the user will never scroll past the first couple hundred rows

**Comment by DanailH** [comment]
As I started working on this problem it would be interesting to hear what are your thoughts on the infinite/lazy loading with a combination of the `autoHeight` prop. Should this case be possible and if yes how would the interaction look?

**Comment by oliviertassinari** [comment]
> Should this case be possible

I don't think so, it doesn't make any sense to me. IMHO autoHeight if meant to reduce the gap with a regular `<Table>`.

**Comment by DanailH** [comment]
After discussing it further this is what it will be delivered in the first iteration:

- A callback that will be invoked when the scroll reaches or gets near the last currently loaded row. This will provide a way for the rows to be updated and essentially load more rows
- A way to alter the default threshold of when that callback is invoked (at the very bottom, or X pixes before the bottom of the grid)
- If the `autoHeight` prop is set that callback will not be called
- An example of how to use the provided functionality to achieve an infinite scroll functionality

**Comment by oliviertassinari** [comment]
> An example of how to use the provided functionality to achieve an infinite scroll functionality

I would propose we add it into https://material-ui.com/components/data-grid/rows/#updating-rows as it also where we have the streaming demo. Then, in the future, once the page is too long, we could maybe move both into a new https://material-ui.com/components/data-grid/data/ page for data loading?

**Comment by oliviertassinari** [comment]
A subset of the issue was fixed, the cursor pagination with infinite loading.

We have #1247 as a follow-up. It's not very clear to me, but #1247 might be what most people are looking for. I'm not soo sure. With PostgreSQL when you have 10,000 rows, it's quite easy to get a total row count. However, when you have 1,000,000 it becomes a real challenge. In the former case #1247 would yield a better UX. In the latter case, you might not have the choice but to leverage the solution in #1199.
