### ISSUE TITLE
[DataGrid] Follow class name convention 

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#408]
- [ ] 1. We have a `dataGridClasses.ts` pattern in the core components, that we will want to use here too. It will allow removing all the `XX_CSS_CLASS` consts, e.g. 

https://github.com/mui-org/material-ui-x/blob/2f61504f49e0b269279fa00b5e971b2a26267ddf/packages/grid/_modules_/grid/constants/cssClassesConstants.ts#L9
- [x] 2. Fixed in #1872
@DanailH has started an interesting discussion in https://github.com/mui-org/material-ui-x/pull/165#discussion_r499653998. The class name convention is: `Mui` as a prefix for Material-UI, `DataGrid` as a prefix for the name of the component, and a camelCase value for the element the class name is supposed to refer to. This convention leads to class names like `MuiDataGrid-colCellDraggable`, which covers all the public components.
An example where we don't follow the convention,  `GridFooterContainer` is a public component, its class name should be: `GridFooterContainer-root`, and have its dedicated classes file: `gridFooterContainerClasses.ts`

https://github.com/mui-org/material-ui-x/blob/801ba0e1f3d9dca01174c44d69d48f8308a8c354/packages/grid/_modules_/grid/components/containers/GridFooterContainer.tsx#L10

#### Option 1 (standalone). MuiGridToolbarExport-root

```jsx
import { GridToolbarExport, gridToolbarExportClasses } from '@material-ui/data-grid';

const gridToolbarExportClasses = {
  root: 'MuiGridToolbarExport-root,
};

const theme = {
  components: {
    MuiGridToolbarExport: {
      defaultProps: {
        csvExport: {
          delimiter: ',',
        },
      },
      styleOverrides: {
        root: {
          color: 'blue',
        }
      },
    },
  }
};
```

#### Option 2 (sub-component). MuiDataGrid-toolbarExport

```jsx
import { GridToolbarExport, dataGridClasses } from '@material-ui/data-grid';

const dataGridClasses = {
  toolbarExport: 'MuiDataGrid-toolbarExport',
};

const theme = {
  components: {
    MuiDataGrid: {
      defaultProps: {},
      styleOverrides: {
        toolbarExport: {
          color: 'blue',
        }
      },
    },
  }
};
```

- [x] ~3. For sub-components, we might want to introduce a second layer of `-`.
For instance, we could have `MuiDataGrid-ColumnHeader-titleContainer` instead of `MuiDataGrid-columnHeaderTitleContainer`. ColumnHeader being a reference to the `GridColumnHeaderItem` component (Item is no needed, we could remove it).~ We give up on the idea to not be depending on how the internal components of the data grid are structured. It will allow us to refactor with minimal breaking changes in the public CSS API.
- [x] 4. Add modifier prefix. Fixed in #1872 

`MuiDataGrid-columnHeaderTitle--center`

https://github.com/mui-org/material-ui-x/blob/801ba0e1f3d9dca01174c44d69d48f8308a8c354/packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx#L128

**Comment by dtassone** [comment]
We could  use BEM http://getbem.com/naming/

**Comment by oliviertassinari** [comment]
There is one constraint that I think is important: we have taught developers a pattern in v4. The closer we stay to it, the fewer breaking changes they will need to handle. I recall a similar discussion with @mnajdova.

**Comment by oliviertassinari** [comment]
Another note, we now have a `xxClasses` pattern in the core components, that we will want to use here too.

**Comment by dtassone** [comment]
Solution discussed.
- MuiDataGrid-columnHeader
- MuiDataGrid-columnHeaderItem--sorted
- MuiDataGrid-columnHeaderItemTitle--sorted

-ComponentNamespace-subComponent--modifier
Would that work?

**Comment by oliviertassinari** [comment]
The current convention in the core is: `[lib prefix][component name]-[element name]`. For instance:

https://github.com/mui-org/material-ui-x/blob/801ba0e1f3d9dca01174c44d69d48f8308a8c354/packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaders.tsx#L30

- lib prefix: `Mui`
- component name: `DataGrid`
- element name: `columnHeaderWrapper`

I have updated the issue description to contain more information and refine the proposal.

**Comment by dtassone** [comment]
As agreed we want to move forward with the `MuiPrefix-component--modifier`.
We leave the slots out for the next iteration.

**Comment by oliviertassinari** [comment]
One small diff we can do:

```diff
diff --git a/packages/grid/_modules_/grid/components/toolbar/GridToolbarFilterButton.tsx b/packages/grid/_modules_/grid/components/toolbar/GridToolbarFilterButton.tsx
index 32428e8d..7ec4368c 100644
--- a/packages/grid/_modules_/grid/components/toolbar/GridToolbarFilterButton.tsx
+++ b/packages/grid/_modules_/grid/components/toolbar/GridToolbarFilterButton.tsx
@@ -27,7 +27,7 @@ const useStyles = makeStyles(
       padding: theme.spacing(0, 1),
     },
   }),
-  { name: 'MuiDataGridToolbarFilterButton', defaultTheme },
+  { name: 'MuiGridToolbarFilterButton', defaultTheme },
 );

 export const GridToolbarFilterButton = React.forwardRef<HTMLButtonElement, ButtonProps>(
```

**Comment by DanailH** [comment]
Using the diff from @oliviertassinari I was thinking - how about we solve the problem with the style container as follows:

```diff
--- a/packages/grid/_modules_/grid/components/containers/GridToolbarContainer.tsx
+++ b/packages/grid/_modules_/grid/components/containers/GridToolbarContainer.tsx
@@ -12,7 +12,7 @@ export const GridToolbarContainer = React.forwardRef<HTMLDivElement, GridToolbar
     }

     return (
-      <div ref={ref} className={clsx('MuiDataGrid-toolbar', className)} {...other}>
+      <div ref={ref} className={clsx('MuiGridToolbarContainer', className)} {...other}>
         {children}
       </div>
     );

**Comment by dtassone** [comment]
It seems that we are going off track now of what we agreed on in the meeting on Monday.

**Comment by oliviertassinari** [comment]
> It seems that we are going off track now of what we agreed on in the meeting on Monday.

@dtassone What do you mean, it's not clear? Are you making a reference to https://github.com/mui-org/material-ui-x/issues/408#issuecomment-856032291? This diff is meant to fix the current inconsistent convention. It's none of the two conventions we talk about (on the meeting) and are using. Meaning, it's neither the "standalone" approach where the class names are specific to one component nor the "sub-component" approach where the class names match the ones from the root.

**Comment by dtassone** [comment]
Well I didn't expect so many standalone components at this stage. I thought we would prefix everything with MuiDataGrid.
And I thought we would leave the slots for another iteration. Standalone components mean that they can be used outside the grid or does it mean that we treat them as extensions of the grid? It seems the latter?

**Comment by oliviertassinari** [comment]
>  Standalone components mean that they can be used outside the grid or does it mean that we treat them as extensions of the grid? It seems the latter?

In this issue's description, the *standalone* terminology is used to describe the structure of the class name. Not how the component is used. It's up to us to define it.

**Comment by m4theushw** [comment]
> We could do two PRs, true. Maybe it one of these cases where we need to have a holistic view to see if the changes fit together.

If we hold these two PRs to be released together it's okay, but #1872 already renamed inner components, which caused breaking changes. To prevent two releases with breaking changes in the same component I would also rename the slots now. My proposal is the following:

`.MuiDataGrid-[componentName]--[modifier]` - root

`.MuiDataGrid-[componentName]__[slot]--[modifier]` - slot

**Comment by oliviertassinari** [comment]
> My proposal is the following:

Is it the same as 3. in this issue' description?

**Comment by m4theushw** [comment]
> Is it the same as 3. in this issue' description

The idea is the same but following the BEM style.

The main point from my comment is that I think is better to also rename components that use slots now.

**Comment by oliviertassinari** [comment]
Point 1. is yet to be solved. It's a breaking change in theory since we export everything, but we also don't document the variables so I think that we can do it during, later on, during a minor.

**Comment by oliviertassinari** [comment]
Closing for #1950
