### ISSUE TITLE
[DataGrid] Missing keys in classes prop

### ISSUE THREAD

**Issue by cmeeren** [mui-org/material-ui-x#420]
As shown on the image below, all rule names (except `root`) for [DataGrid](https://material-ui.com/api/data-grid/#css) and [XGrid](https://material-ui.com/api/x-grid/#css) are missing.

![image](https://user-images.githubusercontent.com/7766733/94375068-32021080-0111-11eb-80c7-7765aacb8428.png)

This is causing me some consternation since I'm using the docs to automatically create F# Fable bindings for MUI. Seems like a quick fix, though. :)

**Comment by bengobeil** [comment]
Hi, material newbie here. 

Is there an issue to track this issue's blocking issue?

**Comment by m4theushw** [comment]
We added support for the `classes` prop and a couple of slots: https://material-ui.com/api/data-grid/data-grid/#css

**Comment by oliviertassinari** [comment]
This issue makes me think about https://github.com/mui-org/material-ui-x/issues/1755#issuecomment-875454927 and #1950.

From what I understand, to close it, we need to have all the class names have a corresponding overridable classes's key, so no holes.

**Comment by m4theushw** [comment]
For the those classes that include dashes do we want to: 1. use the same class name as the key or 2. replace the dashes with underscores?

The problem with classes like `columnHeader--dragging` is that users have to wrap the key in single quotes to use it in the `classes` prop:

```jsx
<DataGrid classes={{ 'columnHeader--dragging': 'foobar' }} />
```

When applying the class, the bracket syntax has to be used as well:

```jsx
<div className={gridClasses['cell--withRenderer']} />
```

The idea in 1 is to replace the dashes with underscores:

```jsx
<DataGrid classes={{ columnHeader__dragging: 'foobar' }} />
```

The dashes will be kept will outputting the HTML.

**Comment by oliviertassinari** [comment]
@m4theushw We don't encourage using the classes API. I don't think that we should care.
