### ISSUE TITLE
[DataGrid] Responsive layout problem with flex container

### ISSUE THREAD

**Issue by VolkerFried** [mui-org/material-ui-x#437]
Within a flex container, the DataGrid adjusts its size correctly if the browser window is enlarged. However, the DataGrid does not get any smaller when the browser window is made smaller again. As a result, the browser has to display a horizontal scrollbar, which destroys the entire page layout.

- [x ] The issue is present in the latest release.
- [x ] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

DataGrid keeps its size when the browser window is dragged smaller and the browser shows a horizontal scrollbar.

## Expected Behavior 🤔

DataGrid should get smaller with the size of the browser window.

## Steps to Reproduce 🕹

[DataGrid sandbox -> Problem](https://codesandbox.io/s/material-ui-flex-datagrid-problem-p4dgu?file=/src/Demo.js)

[Box sandbox -> OK](https://codesandbox.io/s/material-ui-flex-boxtry-works-hdcme?file=/src/Demo.js)

Steps:

1. Open above DataGrid codesandbox link. 
2. Maximize the browser window horizontally.
3. Make the browser window smaller horizontally.
4. DataGrid retains its size and the browser scrollbar is displayed => PROBLEM

5. Open above Box codesandbox link. 
6. Maximize the browser window horizontally.
7. Make the browser window smaller horizontally.
8. Box element is reduced again => OK

## Context 🔦

I use the flex container because of the paperbase theme:
[Paperbase theme](https://github.com/mui-org/material-ui/blob/master/docs/src/pages/premium-themes/paperbase/Paperbase.tsx)

`const styles = createStyles({
  root: {
    display: 'flex',
    minHeight: '100vh',
  },`
...
`app: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
  },
  main: {
    flex: 1,
    padding: theme.spacing(6, 4),
    background: '#eaeff1',
  },`

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | 4.0.0-alpha.6  |
| React         |   16.13.1      |
| Browser       |    Tested: Firefox, Chrome    |
| TypeScript    |    yes     |
| etc.          |         |

**Comment by oliviertassinari** [comment]
@VolkerFried Thanks for reporting the issue. I have noticed it too. The problem was solved in #350. You can confirm that on https://codesandbox.io/s/material-ui-flex-datagrid-problem-forked-6kcyx?from-embed=&file=/package.json

**Comment by VolkerFried** [comment]
I have created a version locally with the new source code. Flex Container Problem is solved when the DataGrid has its own Flex Container again as dealt with in the documentation.
[DataGrid > Rendering > Layout > Flex Layout](https://material-ui.com/components/data-grid/rendering/)
`<div style={{ height: 400, width: '100%' }}>`
` <div style={{ display: 'flex', height: '100%' }}>`
`  <div style={{ flexGrow: 1 }}>`
`    <DataGrid {...data} />`
`  </div>`
` </div>`
`</div>`
