### ISSUE TITLE
[DataGrid] Variable row height

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#438]
This is a sequel of #417 to focus on the variable height problem. Variable height is a simpler problem than dynamic height. 

### Benchmark

- https://react-window.now.sh/#/examples/list/variable-size `itemSize` (function) 
- https://bvaughn.github.io/react-virtualized/#/components/Grid `rowHeight` (function)
- https://www.ag-grid.com/javascript-grid-row-height/#getrowheight-callback `getRowHeight` (function)
- https://github.com/tannerlinsley/react-virtual#options `estimateSize`.

**Comment by flaviendelangle** [comment]
Follow up here #3737
