### ISSUE TITLE
[DataGrid] On last column miss padding

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#442]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

**mobile**
<img width="333" alt="Capture d’écran 2020-10-15 à 12 39 13" src="https://user-images.githubusercontent.com/3165635/96112845-8d8b1700-0ee3-11eb-8c7a-f0b26815075d.png">

**desktop**
<img width="273" alt="Capture d’écran 2020-10-15 à 12 40 15" src="https://user-images.githubusercontent.com/3165635/96112950-b3182080-0ee3-11eb-9c55-0c30089eea8b.png">

## Expected Behavior 🤔

<img width="196" alt="Capture d’écran 2020-10-15 à 12 44 46" src="https://user-images.githubusercontent.com/3165635/96113269-3b96c100-0ee4-11eb-8b5a-5d239f73111e.png">

## Steps to Reproduce 🕹

Steps:

1. https://material-ui.com/components/data-grid

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | v4.0.0-alpha.6  |

**Comment by m4theushw** [comment]
I couldn't reproduce this bug. I think #1253 fixed it [here](https://github.com/mui-org/material-ui-x/pull/1253/files#diff-b067e2d006d18d8c1214e487d80d2a267f8bc6e8b163055fb0c381317db7010fL178).

Current behavior running the demo in the storybook:

<img src="https://user-images.githubusercontent.com/42154031/112780252-d6143800-901e-11eb-93e8-cda56b730029.png" width="350">

**Comment by oliviertassinari** [comment]
@m4theushw Indeed, it looks like we can close
