### ISSUE TITLE
[DataGrid] iOS freeze on drag

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#443]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

![stuck](https://user-images.githubusercontent.com/3165635/96113535-97614a00-0ee4-11eb-85d4-bdbc4008f824.gif)

## Expected Behavior 🤔

Doesn't get stuck

![stuck ok](https://user-images.githubusercontent.com/3165635/96113649-c24b9e00-0ee4-11eb-9398-c5e3f0016cf1.gif)

(*react-virtual*)

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | v4.0.0-alpha.6  |
| Browser       | iOS Safari 14.0 |

**Comment by oliviertassinari** [comment]
@lenolib Thanks for the feedback. We have #1933 to gather the constraint on what we need to do next for the virtualization. I suspect that this issue means that we have to give up on the current logic (that is not relying on the native scroll behavior), but to dive deeper and challenge.

**Comment by DanailH** [comment]
Just checked it - it works as expected - tested it on iPhone 12, IOS 15.1.1. It works both on Chrome and Safari.

**Comment by oliviertassinari** [comment]
Same, it seems fixed one iPhone 13, iOS 15.0.0.

@m4theushw However we have a different issue, see the header:

![iOS](https://user-images.githubusercontent.com/3165635/142609007-f01e0323-331e-4986-940f-f699faeb69b6.gif)

I can reproduce the same issue on AG Grid, it's not sure if we can fix this.

**Comment by m4theushw** [comment]
> However we have a different issue, see the header:

This is the trade-off of using the native scroll. See https://github.com/mui-org/material-ui-x/pull/2673#issue-1004950963 for an explanation.
