### ISSUE TITLE
[DataGrid] is flickering while scrolling on iphone 11 / safari

### ISSUE THREAD

**Issue by mentierd** [mui-org/material-ui-x#451]
When I attempt to scroll the demos for the new data-grid component on my iPhone 11 / safari, the grid flickers and is not smoothly scrolling. It seems to jump around.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When I use touch on my iPhone to scroll the grid itself flickers and doesn’t respond thoroughly to my intentions. Eg, I touch and drag to the left to get the grid to scroll horizontally to the right. Whenever I move my finger, the grid flickers and doesn’t fully respond to the leftward gesture.  This occurs for all directions. Almost like it’s unmounting and re rendering.

## Expected Behavior 🤔

The grid should behave the same way on mobile as it does on non touch devices.

## Steps to Reproduce 🕹

As described above, all u need is an iPhone and ios. This behavior is visible in the demos provided for the data-grid on the official material ui webpage.

## Context 🔦

I’m interested in using this as an alternative to ag-grid for a work related project, but mobile support is a must.

## Your Environment 🌎

iPhone 11
IOS 14
Safari

| Tech        | Version |
| ----------- | ------- |
| Material-UI | v4.11.0?|
| Browser     |   Safari / IOS      |

**Comment by oliviertassinari** [comment]
Which one is it, #443 or #269?

**Comment by mentierd** [comment]
Neither of those. Like I described there’s is a flickering effect while attempting to scroll. The behavior described in #443 may be what I was describing as the inability to smoothly scroll. Technically it does scroll, but it’s choppy.

**Comment by oliviertassinari** [comment]
Do you have a screen recording or a link to a specific demo where you can see the issue? This would help a lot.

**Comment by mentierd** [comment]
I do not have a video. The bug is visible in all data-grid demos at https://material-ui.com/components/data-grid/

Here’s a screenshot I was able to grab; capturing the flickering. 

![C0B2DA79-4F14-4157-890C-0278E72DAC8C](https://user-images.githubusercontent.com/5190439/96347555-6f9eed00-1070-11eb-9b42-4cdb272e38cf.png)

**Comment by oliviertassinari** [comment]
yeah ok, that #269. Can you confirm that it's fixed under https://master--material-ui-x.netlify.app/components/data-grid/#mit-version?
