### ISSUE TITLE
[DataGrid] Give access to the sorted rows

### ISSUE THREAD

**Issue by brmscheiner** [mui-org/material-ui-x#481]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Since sort is managed internally, it can be difficult to recover which item is immediately before or after the selected element. 

## Examples 🌈

My use case: clicking a row opens a dialog in which the user can take some actions. I want to add "Previous" and "Next" buttons to this Dialog so that users can move from item to item without repeatedly opening and closing the dialog. 

## Motivation 🔦

Reduce clicks for our beloved users =)

**Comment by oliviertassinari** [comment]
@brmscheiner Considering that we need to come up with an API that can support virtualization, maybe we could allow developers to lookup rows per index. The index would be linked to what's displayed it starts at 0 and end with the total number of rows -1. So if a sort is applied a getRowByIndex(0) would return a different row.

Would it cover your problem? @mui-org/x what do you think?

**Comment by brmscheiner** [comment]
Hmm, that would do a trick if the `rowIndex` provided in event handlers matches the current (sorted) index of the item!

**Comment by mathmoth** [comment]
@oliviertassinari  a related question to this topic:
My use case is that I want to select the top X rows in XGrid where X = user input. It should always select from the top, respecting current sort order. This actually worked perfectly when I was using version alpha.6 like this:
```
const allRows = apiRef.getAllRowIds();
const toBeSelected = allRows.slice(0, userInputCount);
apiRef.selectRows(toBeSelected, undefined, true);
```
In version alpha.6 `apiRef.getAllRowIds()` would return an array with Ids respecting current sort order. But after updating to alpha.12 it no longer respects sort order. Is this a bug or a feature change? As it stands I had to revert back to alpha.6 in order for this to be possible.

**Comment by oliviertassinari** [comment]
It also seems to be an issue related to allowing better integration with the state: #190.

The proposal I had in https://github.com/mui-org/material-ui-x/issues/481#issuecomment-713848219 was inspired by the API of ag-Grid. However, at this point, we came to the conclusion that what ag-Grid is best to be used for is to benchmark the technical implementation, not really for the API, which suffers from having to make tradeoffs to support other frameworks and that wasn't designed for the unidirectional declarative paradigm shift that React promotes (making nay imperative logics something for run away from, unless the use case really justifies it).

@mathmoth if you want to hook into the internals, one more time, you could find the sorted key in the state. However, at this point, please consider anything not documented as private.

**Comment by mathmoth** [comment]
Thank you!

Accessing the state solves my use case: `apiRef.state.sorting.sortedRows`

**Comment by oliviertassinari** [comment]
@dtassone In #1113, we are solving the same problem for the filtering state. Would it make sense to apply the same solution for the sorted state with a new key in `onSortModelChange` callback?

I have also noticed that #1113 barely documents the feature. But I guess it's a broader issue with the documentation of the API. apiRef and the callback params.

**Comment by Tamono** [comment]
Has this been solved? I'm asking because I have the same problem as OP rn that I'm trying to get access to the next and previous row of a selected row.
