### ISSUE TITLE
[DataGrid] CSP nonce does not get passed to AutoSizer component

### ISSUE THREAD

**Issue by tmikoss** [mui-org/material-ui-x#541]
DataGrid component does not pass CSP nonce to AutoSizer component at https://github.com/mui-org/material-ui-x/blob/069daa728084f53db049544f70922af66f740568/packages/grid/_modules_/grid/GridComponent.tsx#L96, which in turn does not get passed to resize observer at https://github.com/mui-org/material-ui-x/blob/069daa728084f53db049544f70922af66f740568/packages/grid/_modules_/grid/components/AutoSizer.tsx#L117

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Error `Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' https://fonts.googleapis.com 'nonce-R29+/m4IVse+cw3MIfe57A=='". Either the 'unsafe-inline' keyword, a hash ('sha256-deDIoPlRijnpfbTDYsK+8JmDfUBmpwpnb0L/SUV8NeU='), or a nonce ('nonce-...') is required to enable inline execution.` appears in browser console when trying to render DataGrid component, despite `<meta property="csp-nonce" name="csp-nonce" content="LJ6WDXdsQlWY/6YSN9P/Mw==">` being present in page header as per https://material-ui.com/styles/advanced/#what-is-csp-and-why-is-it-useful.

## Expected Behavior 🤔

Generated styles use CSP nonce and error does not appear.

## Steps to Reproduce 🕹

Steps:

1. Configure web server to serve `Content-Security-Policy` header with `nonce` value for `style-src`;
2. Add csp-nonce meta tag as per https://material-ui.com/styles/advanced/#what-is-csp-and-why-is-it-useful
3. Try to render DataGrid component in page;
4. Observe error.

## Context 🔦

I'm trying to follow best CSP practices and MUI guidelines.

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| @material-ui/data-grid | 4.0.0-alpha.8  |
| React         |    17.0.1     |
| Browser       |   Chrome @ latest      |
| TypeScript    |    4.0.5     |

**Comment by oliviertassinari** [comment]
This is related to https://github.com/mui-org/material-ui/issues/19938. We could have almost removed the need for the nonce with the [ResizeObserver](https://caniuse.com/?search=ResizeObserver) API but we still [support](https://next.material-ui.com/getting-started/supported-platforms/#browser) Safari 12.2 so it won't cut it. I think that we can add this prop.

What do you think of this diff?

```diff
diff --git a/packages/grid/_modules_/grid/GridComponent.tsx b/packages/grid/_modules_/grid/GridComponent.tsx
index f4c77126..1ace84eb 100644
--- a/packages/grid/_modules_/grid/GridComponent.tsx
+++ b/packages/grid/_modules_/grid/GridComponent.tsx
@@ -93,7 +93,7 @@ export const GridComponent = React.forwardRef<HTMLDivElement, GridComponentProps
     );

     return (
-      <AutoSizer onResize={onResize}>
+      <AutoSizer onResize={onResize} nonce={props.nonce}>
         {(size: any) => (
           <GridRoot
             ref={handleRef}
diff --git a/packages/grid/_modules_/grid/GridComponentProps.ts b/packages/grid/_modules_/grid/GridComponentProps.ts
index cebe717b..6bedbdc6 100644
--- a/packages/grid/_modules_/grid/GridComponentProps.ts
+++ b/packages/grid/_modules_/grid/GridComponentProps.ts
@@ -41,4 +41,8 @@ export interface GridComponentProps extends GridOptionsProp {
    * An error that will turn the grid into its error state and display the error component.
    */
   error?: any;
+  /**
+   * Nonce of the inlined stylesheets for [Content Security Policy](https://www.w3.org/TR/2016/REC-CSP2-20161215/#script-src-the-nonce-attribute).
+   */
+  nonce?: string;
 }
```

Do you want to work on a pull request? :)

**Comment by ZeeshanTamboli** [comment]
Hi @oliviertassinari, I would like to work on this!

**Comment by oliviertassinari** [comment]
@ZeeshanTamboli Great, note that we also need to update the docs of the api pages.
