### ISSUE TITLE
[DataGrid] Not to swallow keyboard events

### ISSUE THREAD

**Issue by ypresto** [mui-org/material-ui-x#572]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Currently all keydown events are swallowed at below code.
https://github.com/mui-org/material-ui-x/blob/f279d9ee85fb0ed55bb8c8f5a7a0c47679ca0558/packages/grid/_modules_/grid/hooks/features/keyboard/useKeyboard.ts#L236

It prevents an input tag in a cell from accepting keyboard inputs.
Because DataGrid uses addEventListener() (although on gridRoot, an ancestor of the input), React (which listens all events at top-level listener) does not receive events on input tag.

Possible solutions:

- Use react's onKeyDown instead of addEventListener()
- Ignore events from (uncontrolled) cell children.

## Examples 🌈

![image](https://user-images.githubusercontent.com/400558/98898328-b9081e00-24f0-11eb-8125-89b64e6bbae4.png)

TextField placed in cell using renderCell should accept keyboard input.
Currently caret will appear but text won't be changed on key type.

## Motivation 🔦

Same as #509.

**Comment by namlulu** [comment]
Did you solve this issue?
