### ISSUE TITLE
[DataGrid] controlled sortModel is not working

### ISSUE THREAD

**Issue by etomanon** [mui-org/material-ui-x#598]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
When you set `sortModel` as `[ ]` or `undefined` from e.g. `[{"field":"subject","sort":"desc"}]` then the Data Grid keeps the old `sortModel` instead of removing any previous sort.

## Expected Behavior 🤔
`sortModel` should work as controlled state

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | 4.0.0-alpha.9

**Comment by oliviertassinari** [comment]
Related to https://github.com/mui-org/material-ui-x/issues/190

**Comment by etomanon** [comment]
@oliviertassinari Is there any workaround in the free version to set the `sortModel` ?
I guess you can fix it in the paid version with the `apiRef` ?

**Comment by oliviertassinari** [comment]
@etomanon We have started to work on a `state` prop to allow doing such #533. I'm not sure when it will land.

**Comment by oliviertassinari** [comment]
@etomanon Could you provide a reproduction? It would help a lot. Thanks

**Comment by oliviertassinari** [comment]
Same issue as #223
