### ISSUE TITLE
[DataGrid] Fluid column does not take into account checkbox

### ISSUE THREAD

**Issue by BrentFarese** [mui-org/material-ui-x#611]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The `XGrid` fluid column support using the `flex` prop does not take into account the checkbox width when `checkboxSelection` is true.  See [Codesandbox](https://codesandbox.io/s/material-ui-data-grid-bug-csdge?file=/src/App.tsx).  Uncomment the `checkboxSelection` prop and the grid renders the correct width, but with `checkboxSelection` the grid has a horizontal scroll equal to the checkbox width.

## Expected Behavior 🤔

Grid should have a width 100% of it's container with equal flex item widths even with `checkboxSelection` true.

## Steps to Reproduce 🕹

See above and Codesandbox to reproduce.

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | v4.0.0-alpha.10  |
| React         |    17     |
| Browser       |    Chrome     |
| TypeScript    |    Y     |

**Comment by ronnyroeller** [comment]
I'm running into the same issue. I can reproduce it in `XGrid` and `DataGrid`. Here codesandbox for `DataGrid`: https://codesandbox.io/s/material-demo-forked-z635n?file=/demo.js

**Comment by dtassone** [comment]
Ok thanks for creating this issue. We will fix it very soon
