### ISSUE TITLE
[DataGrid] Review on the filtering feature

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#633]
This is a follow-up after https://github.com/mui-org/material-ui-x/pull/411. I have tried to list all the improvement opportunities we can potentially leverage. This is meant to polish the feature so we can release it. By somewhat order of importance:

- [x] 0. Move multi-filtering support to XGrid
- [ ] 1. Add documentation
- [x] 2. Add tests
- [x] 3. I think that the toolbar should be opt-in. This is too opinionated to be displayed by default. It's only something we should probably only include in XGrid, considering the pain around react-table is about the painful integration with the UI and that ag-Grid makes its toolbar paid.
- [x] 4. The menu should open over the column, taking into account the alignment:

<img width="400" alt="position" src="https://user-images.githubusercontent.com/3165635/99917365-0a45b800-2d10-11eb-8465-e0195c2ff007.png">
<img width="399" alt="position 2" src="https://user-images.githubusercontent.com/3165635/99917364-09ad2180-2d10-11eb-8d12-2e526f2cf415.png">

- [x] 5. There is a double border on the toolbar

<img width="832" alt="Capture d’écran 2020-11-22 à 22 10 26" src="https://user-images.githubusercontent.com/3165635/99917286-8f7c9d00-2d0f-11eb-8d6c-9c0cf20595e3.png">

- [x] 6. The menu jumps when closing, the content should stay identical. It feels cheap:

![jump](https://user-images.githubusercontent.com/3165635/99917487-f0f13b80-2d10-11eb-8cbf-c85598abba75.gif)

- [x] 7. The toolbar actions should get a description. At least, at `title` in addition to the `aria-label`. We might want to inline the description inside it or allow developers to do such if they need to.
- [x] 8. The clear filter icon is not correctly aligned:
<img width="243" alt="Capture d’écran 2020-11-22 à 22 24 18" src="https://user-images.githubusercontent.com/3165635/99917592-88568e80-2d11-11eb-9ab6-b4a583be7492.png">

- [x] 9. I would suggest we remove the clear button, individual arrows are likely enough:

<img width="106" alt="Capture d’écran 2020-11-22 à 22 25 59" src="https://user-images.githubusercontent.com/3165635/99917636-d075b100-2d11-11eb-917e-b5954f21b8f0.png">

- [x] 10. The description of the add filter button is confusing. I think that it should be "Add filter", instead of "Filter".
<img width="105" alt="Capture d’écran 2020-11-22 à 22 27 36" src="https://user-images.githubusercontent.com/3165635/99917670-01ee7c80-2d12-11eb-8b8f-83ee3a7b3bf6.png">

- [x] 11. The padding should be inside the scroll container

<img width="240" alt="Capture d’écran 2020-11-22 à 22 30 34" src="https://user-images.githubusercontent.com/3165635/99917725-69a4c780-2d12-11eb-8086-0706e17337c9.png">

- [x] 12. I think that we should remove the tabs. It won't scale and doesn't fit into the use cases. For instance with the column picker. It will be better to have a denser display vertically longer and horizontally shorter

<img width="618" alt="Capture d’écran 2020-11-22 à 22 31 44" src="https://user-images.githubusercontent.com/3165635/99917744-880ac300-2d12-11eb-9fd7-92275f5fbc16.png">

- [x] 13. The columns should be displayed in 1D, the mental model is one dimensional. I go confused, I miss interpreted the order I thought the list was collapsing vertically, but it collapses horizontally as it turns out

<img width="490" alt="Capture d’écran 2020-11-22 à 22 33 24" src="https://user-images.githubusercontent.com/3165635/99917806-eafc5a00-2d12-11eb-9ed0-06853869601d.png">

- [x] 14. The column picker should have a search field.
- [x] 15. There are two scrollbars:

<img width="597" alt="Capture d’écran 2020-11-22 à 22 35 44" src="https://user-images.githubusercontent.com/3165635/99917831-1da65280-2d13-11eb-879c-b2f1ad7ca22b.png">

- [x] 16. A switch would work better than a checkbox: https://next.material-ui.com/components/switches/#when-to-use for the column picker.
- [ ] 17. A drag & drop for the column picker to reorder the columns would be 👌  but I think I should open a new issue for it. It's outside of the scope of the filters
- [x] 18. The popup should have rounded borders

<img width="46" alt="Capture d’écran 2020-11-22 à 22 40 42" src="https://user-images.githubusercontent.com/3165635/99917912-d1a7dd80-2d13-11eb-97c6-eb82b91f48b2.png">

- [x] 19. The popup should leverage the existing components (change the elevation) not apply custom CSS, to replace:

<img width="616" alt="Capture d’écran 2020-11-22 à 22 42 20" src="https://user-images.githubusercontent.com/3165635/99917953-13388880-2d14-11eb-95ff-3bc2b8191902.png">

- [x] 20. We likely want to have a min-height for the popup, in the following configuration, the useful area is too small. We can only see one row, and the others are hidden:

<img width="626" alt="Capture d’écran 2020-11-22 à 22 44 38" src="https://user-images.githubusercontent.com/3165635/99918003-627eb900-2d14-11eb-9a49-50afe2e5b55a.png">

- [x] 21. `.panelMainContainer` or `.panelFooter` isn't a class name we can allow, it breaks the convention.
- [x] 22. We should try to replace `padding: 10` with a value that fits the 4px spacing grid, for design consistency. 
- [x] 23. This inline style duplicates with the CSS, we can drop it:

https://github.com/mui-org/material-ui-x/blob/b6e9a68edf32b3bcb143fa12f48df89bdec058bc/packages/grid/_modules_/grid/components/tools/FilterForm.tsx#L128

- [x] 24. All stylesheets should be named, assuming we want them to be public and allow customizations.

https://github.com/mui-org/material-ui-x/blob/b6e9a68edf32b3bcb143fa12f48df89bdec058bc/packages/grid/_modules_/grid/components/tools/FilterForm.tsx#L24

- [x] 25. The style of `.panelFooter` can be simplified, there are CSS properties that have no effect. I also think that 8px instead of 12px for the padding would work better, a higher density would probably be fine. [Blueprint](https://blueprintjs.com/docs/#table/features) and [Elastic UI](https://elastic.github.io/eui/#/tabular-content/data-grid) are all-in.
- [x] 26. I feel that the icon menu draws too much attention when hovering the column header. I think that we could might it lighter and its current color only when hovered. In the following screenshot, I hover the arrow, not the icon button:

<img width="267" alt="Capture d’écran 2020-11-22 à 23 01 43" src="https://user-images.githubusercontent.com/3165635/99918378-c1ddc880-2d16-11eb-9411-c25e537c869e.png">

- [x] 27. We miss a max-height for the popup. It becomes unusable once too large. This one is too high:

<img width="632" alt="Capture d’écran 2020-11-22 à 23 04 58" src="https://user-images.githubusercontent.com/3165635/99918458-47fa0f00-2d17-11eb-8639-9720265940ea.png">

Same problem with the column picker view in worse when the data table is tall (~1000px), I can't use it:

<img width="845" alt="Capture d’écran 2020-11-22 à 23 08 30" src="https://user-images.githubusercontent.com/3165635/99918526-c35bc080-2d17-11eb-9ae2-519567606b71.png">

- [ ] 28. Assuming the toolbar is opt-in and only available in XGrid, I would encourage this API for the developers:

```jsx
function Header() {
  return (
    <GridToolbar>
      <GridToolbarFilter />
      <GridToolbarColumn />
      <GridToolbarDensity />
    </GridToolbar>
  );
}

<XGrid component={{ Header }} />
```
- [ ] 29. Maybe add negation operators (not equal, etc). Not sure, maybe it should only be available with a customization API.

**Comment by oliviertassinari** [comment]
- [ ] 30. https://codesandbox.io/s/material-demo-forked-991f4?file=/demo.js

![open ](https://user-images.githubusercontent.com/3165635/100141760-2faeff00-2e93-11eb-93f6-153620477c7c.gif)

**Comment by dtassone** [comment]
Server-side filters as well

**Comment by dtassone** [comment]
[ ] 32. Component customisation. A user should be able to render a certain column menu or filters for a column.

**Comment by dtassone** [comment]
- [ ] 33. String filter input value can be an autocomplete field

**Comment by dtassone** [comment]
- [ ] 34. Add prop to preset the filter (same as sortModel)

**Comment by oliviertassinari** [comment]
- [ ] 35. `.MuiDataGrid-root .MuiDataGrid-toolbar` padding: 4px 4px 0
- [ ] 36. Add an indicator in the header cell if toolbar is disabled.

**Comment by oliviertassinari** [comment]
- [ ] 39. on hide column, menu anchor is lost ![39](https://user-images.githubusercontent.com/3165635/100471089-d97fcd00-30d9-11eb-9ca1-d90f8d76993d.gif)

**Comment by oliviertassinari** [comment]
- [ ] 40. https://codesandbox.io/s/zealous-stallman-ybrvu?file=/pages/index.js. Try to open the filter

<img width="556" alt="Capture d’écran 2020-11-30 à 01 05 24" src="https://user-images.githubusercontent.com/3165635/100557262-3d57f080-32a8-11eb-85b8-f63e30ec4de2.png">

**Comment by oliviertassinari** [comment]
- [ ] 41. I got confused a couple of times now. I think that clicking the filter button should toggle the popup, not only open it.

![close](https://user-images.githubusercontent.com/3165635/100647586-0cc39580-3340-11eb-9886-ede6d9d980d4.gif)

**Comment by dtassone** [comment]
- [ ] 42. User should be able to select filter operators with a string ie `column.filterOperators = {['contains', 'startWith']}`

**Comment by oliviertassinari** [comment]
I have created a new issue for toolbar #726, tests & documentation are work in progress. For the other improvements, I think that it's best to ship the filters and get real feedback from developers, with the frequency, we can know what's more important, a lot better than guessing.
