### ISSUE TITLE
[DataGrid] When the vertical scrollbar appears, the horizontal scrollbar is shown as well

### ISSUE THREAD

**Issue by Tetedeiench** [mui-org/material-ui-x#660]
When the Datagrid has more elements that can be displayed in its current height, the vertical scrollbar appears. This causes the horizontal scrollbar to appear automatically.

- [X ] The issue is present in the latest release.
- [X ] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When the vertical scrollbar appears, the horizontal scrollbar appears.

## Expected Behavior 🤔

The horizontal scrollbar should not appear.

## Steps to Reproduce 🕹

(not sure about using this link, sorry, first timer and noob here - it's easy using the steps though)
https://codesandbox.io/s/datagrid-quick-start-forked-1w5mk?file=/src/App.tsx

Steps:

1. start with the demo sandbox : https://codesandbox.io/s/datagrid-quick-start-d3ex9?from-embed
2. copy & paste rows to get more than 3 rows
3. See the vertical scrollbar appear, and the horizontal one as well

## Context 🔦

I was trying to get a Datagrid with a fixed height displaying a random number of rows :)

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | v4.0.0-alpha.10  |
| React         |    17.0.1     |
| Browser       |    Chrome 86     |
| TypeScript    |         |
| etc.          |         |

**Comment by oliviertassinari** [comment]
@Tetedeiench Thanks for the report. I can definitely reproduce on https://material-ui.com/components/data-grid/pagination/#basic-example

<img width="854" alt="Capture d’écran 2020-11-29 à 17 26 33" src="https://user-images.githubusercontent.com/3165635/100547616-0cf06200-3268-11eb-87ba-ce692ff5d53f.png">

It seems specific to Windows, I can't see it on macOS.

**Comment by jzecca** [comment]
> It seems specific to Windows, I can't reproduce it on macOS.

It is indeed specific to Windows, since its scrollbars are bigger than OSX (or in my case, Xubuntu) ones.
- OSX/Xubuntu: **15px** (default `scrollbarSize` value)
- Windows: **17px**

Ideally, calculations should probably not rely on a fixed scrollbar size, as it may vary between OSes, desktops, themes, browsers... and scrollbars can also be customized through CSS.

#### Workaround (only tested on Chrome)
```
<DataGrid scrollbarSize={17} />
````
This adds a small 2px gap on OSX/Xubuntu, but works properly on Windows 10.

**Comment by oliviertassinari** [comment]
@jzecca Oh great, thanks for isolating the source of the issue, the assumed scrollbar width, in the main repository, we have two distinct approaches for this problem:

- The fire and forget approach: [getScrollbarSize](https://github.com/mui-org/material-ui/blob/6cc38f98d7168f82913f199c36c8b1bba57bf341/packages/material-ui-utils/src/getScrollbarSize.ts). It works for simple cases, and when the session is short like the modal
- The listener approach: [ScrollbarSize](https://github.com/mui-org/material-ui/blob/6cc38f98d7168f82913f199c36c8b1bba57bf341/packages/material-ui/src/Tabs/ScrollbarSize.js). It works better when the component is continuously mounted on screen, like the tabs.

The size scrollbar changes with the zoom level too. So I can reproduce the same bug on macOS by reducing my zoom level to 90%

**Comment by marthaerm** [comment]
Hi! @oliviertassinari I would like to give this issue a try, is it already taken?

**Comment by oliviertassinari** [comment]
@marthaerm It's not already taken you are free to go :)

**Comment by Tetedeiench** [comment]
I have to admit i'm not used to reporting issues on github and such, and seeing this getting so much attention and good will deserves a comment saying "wow !" 🥇

**Comment by gpodliegaiev** [comment]
Material-UI X | v4.0.0-alpha.36 (but the same behavior and for v4.0.0)
React | 17.0.2
Browser | Chrome 93.0.4577.82

Hi @oliviertassinari! 
Is there difference between trial and license version?
Currently I have a scroll issue on my prod env where license is applied (MuiDataGrid-viewport **includes** scroll width), but locally (trial version) it is okay (MuiDataGrid-viewport **excludes** scroll width).

**Comment by Tiberriver256** [comment]
Any chance the patch for this could be added to v4? We're using the pro version but it's looking like it'll be a while before we can upgrade to v5.

**Comment by lutzseverino** [comment]
I'm experiencing this and the proposed fix is not working. At least in my Arch Linux machine in Google Chrome. However, adding `flex: 1` to at least the first column does work, for some reason.
