### ISSUE TITLE
[DataGrid] Select all checkbox should be indeterminate

### ISSUE THREAD

**Issue by rubenstolk** [mui-org/material-ui-x#667]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

- When you select all rows and then deselect one, the select all checkbox remains checked
- When you select all rows and then deselect all rows manually, the select all checkbox should toggle to its `unchecked` state
- When you deselect all rows and then manually select each row one by one, the select all checkbox remains unchecked

## Expected Behavior 🤔

- When you select all rows and then deselect one, the select all checkbox should toggle to its `indeterminate` state
- When you select all rows and then deselect all rows manually, the select all checkbox should toggle to its `unchecked` state
- When you deselect all rows and then manually select each row one by one, the select all checkbox should toggle to `checked` state
- The above works perfectly well here: https://muix-preview.netlify.app/#/grid

## Steps to Reproduce 🕹

Version with "Current Behavior":
- https://material-ui.com/components/data-grid/#commercial-version and also when you implement a simple grid based of `^4.0.0-alpha.10`

Version with Expected Behavior:
- https://material-ui.com/components/data-grid/#commercial-version

(I am using the commercial version)

**Comment by oliviertassinari** [comment]
@rubenstolk Thanks for raising, we got a regression between v4.0.0-alpha.9 and v4.0.0-alpha.10. We miss a test case

**Comment by oliviertassinari** [comment]
It was fixed in v4.0.0-alpha.12.
