### ISSUE TITLE
[DataGrid] Scroll position in the data grid lost

### ISSUE THREAD

**Issue by rlebranchu** [mui-org/material-ui-x#680]
## Problem
Hello everybody !
I have a question about the scrolls on Mui-Datagrid.
I use the DataGrid to list an editable dataset in a form (below the datagrid).

When I click on a row, I fill the form with the data of the chosen row. I modify some data then confirm: this updates the state variable (on which the props rows are based).

In this case, the number of rows displayed in the DataGrid remains the same, so :
The data is updated correctly
We stay on the right page
Scrolls stay in place 

But in this case I delete a line.The state variable on which the props rows are based loses an element, and :
The data are updated correctly
We stay on the right page
**The scrolls are reset to the initial state (top left).**

So I guess it's due to the change of the total number of rows in the table: so to the change of the ID field (required).

## Question
So I wanted to know if you had any idea how to keep the scrolls in their place in any case.

Thank you very much.
Robin L.

**Comment by rlebranchu** [comment]
@oliviertassinari 
I prepare this as soon as possible and share you back the link !
Thx for your reponse !

**Comment by oliviertassinari** [comment]
I'm closing for now, happy to reopen once we have enough information to investigate
