### ISSUE TITLE
[XGrid] apiRef with pagination create prop type warning

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#685]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

> Warning: Failed prop type: Material-UI: The page prop of a TablePagination is out of range (0 to 0, but page is 1).

## Expected Behavior 🤔

No warnings

## Steps to Reproduce 🕹

Steps:

1. https://codesandbox.io/s/material-demo-forked-wv7y4?file=/demo.js:0-555

## Context 🔦

I keep repeating it, I think that it's important. I think that we should drop all `apiRef` APIs to one exception: https://material-ui.com/components/data-grid/rows/#the-apiref. Only make them public when we see a problem that undeniably needs it, I think that we should treat all these imperative APIs as harmful for developers (encouraging bad imperative control flow practices). In the event, developers comes with use cases that we can't ignore, and we need to re-add these props, I think that they should be done in a systematic manner and with a clear boundary between what's public and private, the opposite to what we do now.

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | v4.0.0-alpha.11  |

**Comment by dtassone** [comment]
fix #1021
