### ISSUE TITLE
[XGrid] column resize handles are not keyboard accessible

### ISSUE THREAD

**Issue by petermikitsh** [mui-org/material-ui-x#699]
- [X] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

- Mouse must be used to resize columns

## Expected Behavior 🤔

- Keyboard tab focus column resizers
- Left/right arrow keys shift column size some small amount, say, 5px

## Steps to Reproduce 🕹

Steps:

1. Go to https://material-ui.com/components/data-grid/#commercial-version
2. Observe resize behavior needing mouse

## Context 🔦

This is partially an accessibility question, and may not be a bug.

I'm not an a11y expert, but my understanding is all controls should at least be keyboard focusable.

But the broader question remains: what should the acceptance criteria be for column resizers and a11y? It may be possible this current implementation is considered accessible, and there is no bug.

**Comment by oliviertassinari** [comment]
Coming back to this. I personally think that we should close as "won't fix". @petermikitsh Do you have an example of a data grid that supports it? In my context, if you need a screenreader, you don't care about how the cells are layout, the SR will read the content for you.

**Comment by petermikitsh** [comment]
I took a look at a few other implementations. None supported keyboard-driven column resizing.

- DevExtreme: https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/ColumnResizing/jQuery/Light/
- Kendo: https://www.telerik.com/kendo-react-ui/components/grid/columns/resizing/
- Ignite: https://www.igniteui.com/grid/column-resizing

**Comment by oliviertassinari** [comment]
cc @dtassone

**Comment by oliviertassinari** [comment]
I have added the `waiting for users upvotes` tag. I'm closing the issue as we are not sure enough people are looking for such capability. So please upvote this issue if you are. We will prioritize our effort based on the number of upvotes.
