### ISSUE TITLE
Setting selected rows in XGrid declaratively

### ISSUE THREAD

**Issue by fsommers** [mui-org/material-ui-x#703]
In DataGrid, there is a `selected` property for Row. That allows one to declaratively make a row as selected upon the grid rendering.  How can the same be achieved with XGrid?

- [X] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

**Comment by oliviertassinari** [comment]
@fsommers XGrid was designed to it can be swapped from DataGrid with almost no changes required. If you get it working with DataGrid, it should also work with XGrid. 

The root issue sounds identical to #246.

**Comment by fsommers** [comment]
Thanks, that's the answer so I'm closing this ticket.
