### ISSUE TITLE
[DataGrid] 'flex' fluid width column property not being applied

### ISSUE THREAD

**Issue by shyam-vijayakumar** [mui-org/material-ui-x#716]
Since 4.0.0-alpha.12, the 'flex' fluid width column property is not being applied correctly. 

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

If the 'rows' property on DataGrid is initially given all the data, 'flex' works, but if the 'rows' property is given an array, say after an API call is made to get the data, then the column width defaults to 100. After the data grid is loaded, changing the size of the window fixes the issue. 

## Expected Behavior 🤔

The value given as the 'flex' property for a column should be applied regardless of when the rows are loaded. 

## Steps to Reproduce 🕹

https://codesandbox.io/s/material-ui-issue-forked-iotgl?file=/src/Demo.js

The column in the example above should take up the entire width of the data grid. 

Steps:
1. Change the size of the window to see the 'flex' property being applied. 

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | v4.0.0-alpha.12  |
| React         |    v16.14.0     |
| Browser       |    Chrome     |
| TypeScript    |    v3.9.7      |

**Comment by oliviertassinari** [comment]
@dtassone Something related to a recent refactorization?

**Comment by DanailH** [comment]
Just a note, this may be related to #708 as they are both present when something in the data set changes over time.

**Comment by sebastianfrey** [comment]
This CodeSandbox reproduces the issue: https://codesandbox.io/s/material-demo-forked-5dd42.

**Comment by mwillbanks** [comment]
Note that this also happens anytime that you define an event such as `onRowSelected` or `onRowClick`

**Comment by ronnyroeller** [comment]
Seeing the same issue. I can confirm that rolling back to alpha.11 (from alpha.13) made the issue disappear for us.
