### ISSUE TITLE
[DataGrid] Doesn't do the job. sortingMode="server" 

### ISSUE THREAD

**Issue by clianor** [mui-org/material-ui-x#720]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Row alignment does not change
The data is stored in Redux storage.

## Expected Behavior 🤔

According to the official documentation, the server side sort should change according to rows.

## Steps to Reproduce 🕹

I wrote the code below, but the rows are not sorted.
The code below uses code similar to the official documentation.
```ts
<DataGrid
  rows={[...rows]}
  columns={columns}
  onRowSelected={(param: RowSelectedParams) => {
    param.data.name === "..." || param.data.name === param.data.path
      ? setSelection([])
      : setSelection([param.data]);
  }}
  sortingMode="server"
  sortModel={sortModel}
  onSortModelChange={handleSortModelChange}
  loading={loading}
/>
```

This part is the same as the official documentation.
```
  sortingMode="server"
  sortModel={sortModel}
  onSortModelChange={handleSortModelChange}
  loading={loading}
```

Steps:

1. Row alignment does not change

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | v4.11.2  |
| Material-UI data-grid | v4.0.0-alpha.12  |
| React         |  17.0.1  |
| Browser       |  Chrome  |
| TypeScript    |  4.0.5  |
| etc.          |         |

**Comment by clianor** [comment]
I solved this by explicitly changing the id value of rows in the loadServerRows function.

**Comment by oliviertassinari** [comment]
Please provide a minimal reproduction test case. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://material-ui.com/r/issue-template) _may_ be a good starting point. Thank you!

**Comment by etomanon** [comment]
@oliviertassinari The fix in 4.0.0-alpha.12 does not work. It still sorts rows on client and the sorting works incorrectly for `number`  columns (with decimal places).
You can go here: https://maturoid.info/results sort by "Percentilová úspěšnost" DESC - server returns correctly sorted rows but it is sorted wrong on client.
![image](https://user-images.githubusercontent.com/17390813/101990982-ebe93180-3ca9-11eb-8d12-c3aff30add82.png)

Table component:
https://github.com/etomanon/cermat/blob/master/client/src/components/table/table.tsx#L139
Columns definition:
https://github.com/etomanon/cermat/blob/master/client/src/pages/results/use-results-columns.ts

**Comment by oliviertassinari** [comment]
@etomanon Please provide a minimal live reproduction with codesandbox so we can look into it.

**Comment by clianor** [comment]
@etomanon 
I solved it by inserting the following code below and below the server loading function.

```ts
sortedRows = [
      ...sortedRows.map((row: any, index: number) => {
        row["id"] = index;
        return row;
      }),
    ];
```

**Comment by clianor** [comment]
@oliviertassinari 
I think etomanon's example is better than me.

It would be nice to ask him for help.
