### ISSUE TITLE
[DataGrid] Make toolbar composable

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#726]
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Move away from boolean props toward a composable component API for the toolbar.

## Examples 🌈

```jsx
function Header() {
  return (
    <GridToolbar>
      <GridToolbarFilter />
      <GridToolbarColumn />
      <GridToolbarDensity />
    </GridToolbar>
  );
}

<XGrid component={{ Header }} />
```

It also means we can remove the `showToolbar`  prop and the others to hide controls from the toolbar.

## Motivation 🔦

The closer the API is to the DOM nodes, the better. There is a tradeoff to find between how verbose an API is and how painful it's to customize it. So far, our experience has shown that developers prefer, by a large margin, to have as much control over the rendered content as possible. While it's technically very hard to expose a true composable API with the main rendering area of the grid, and will little customization potential. It's a completely different story for the toolbar. The action buttons are simple, very often customized. It was first raised in #633.

@gregnb having worked on the toolbar of [mui-datatables](https://github.com/gregnb/mui-datatables),  what do you think?

## Benchmark

Elastic has exactly what I think that we should avoid: https://elastic.github.io/eui/#/tabular-content/data-grid:

```jsx
    // Optional. Allows you to configure what features the toolbar shows.
    // The prop also accepts a boolean if you want to toggle the entire toolbar on/off.
    toolbarVisibility={{
      showColumnSelector: false
      showStyleSelector: false
      showSortSelector: false
      showFullScreenSelector: false
    }}
```

> `toolbarVisibility` : Accepts either a boolean or EuiDataGridToolBarVisibilityOptions object. When used as a boolean, defines the visibility of entire toolbar. When passed an object allows you to turn off individual controls within the toolbar.

**Comment by gregnb** [comment]
> So far, our experience has shown that developers prefer, by a large margin, to have as much control over the rendered content as possible. 

@oliviertassinari this was exactly my experience on pretty much any project. in the end, developers are going to want to control it all. best to just design it that way
