### ISSUE TITLE
rowHeight and headerHeight properties don't work

### ISSUE THREAD

**Issue by dmitryKochergin** [mui-org/material-ui-x#746]
Properties headerHeight and rowHeight don't work as expected.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Defining headerHeight and rowHeight props doesn't affect on header and rows height in result HTML. DataGrid always uses default height for header (56px) and row (52px).

## Expected Behavior 🤔

Properties headerHeight and rowHeight should define header and rows height accordingly.

## Steps to Reproduce 🕹

https://codesandbox.io/s/material-ui-issue-rows-and-headerheight-krbmd?file=/src/Demo.js

In this example I tried to use a custom header and row height

Steps:

1. Change headerHeight prop
2. Change rowHeight prop

## Context 🔦

In alpha.11 all works fine, but in alpha.12 something goes wrong.

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | v4.0.0-alpha.12  |
| React         |  16.13.1    |
| Browser       |   Chrome   |

**Comment by oliviertassinari** [comment]
Oh nice, great report! For a first, we could have spotted this regression with a visual test. It's broken here too https://material-ui.com/components/data-grid/rows/#row-height.

**Comment by oliviertassinari** [comment]
@DanailH fixed it on `master`: https://master--material-ui-x.netlify.app/components/data-grid/rows/#row-height already. 

I'm hesitating to add an end-to-end test, it might be overkill, simply bringing Argos-CI from the main repository should to the trick. Should we close?

**Comment by dmitryKochergin** [comment]
I think yes. Thank you!
