### ISSUE TITLE
[DataGrid] getValue error in valueGetter

### ISSUE THREAD

**Issue by westhouseit** [mui-org/material-ui-x#749]
I'm struggling with errors when handling dynamic data that uses valueGetter. The first bug was fixed in alpha.10, but alpha.11 introduced this new one. The code below works in alpha.10 or in alpha.12 by removing the column that uses getValue().

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

All rows are replaced by "An error occurred"

## Expected Behavior 🤔

New data is rendered/displayed

## Steps to Reproduce 🕹

https://codesandbox.io/s/material-ui-issue-forked-z7s0l

Steps:

1. Click **Set Data 1** to load 4 rows

## Context 🔦

Providing user add/edit/delete options.

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | v4.0.0-alpha.12  |
| React         |  16.13.1 & 17.0.1 |

**Comment by oliviertassinari** [comment]
@westhouseit Thanks for reporting this issue.

```diff
diff --git a/packages/grid/_modules_/grid/utils/paramsUtils.ts b/packages/grid/_modules_/grid/utils/paramsUtils.ts
index d305a51b..ba3d969b 100644
--- a/packages/grid/_modules_/grid/utils/paramsUtils.ts
+++ b/packages/grid/_modules_/grid/utils/paramsUtils.ts
@@ -27,7 +27,7 @@ export function buildCellParams({
     getValue: (field: string) => {
       // We are getting the value of another column here, field
       const col = api.getColumnFromField(field);
-      if (!col.valueGetter) {
+      if (!col || !col.valueGetter) {
         return rowModel[field];
       }
       return col.valueGetter(
```

What do you think about the above fix?

cc @dtassone

**Comment by westhouseit** [comment]
@oliviertassinari Thanks for tracking that quickly. Looks good to me.

BTW, what's the easiest way for me to swap to using the dev version of DataGrid alongside my codebase? I'm thinking I'd then see the actual error origin and can just fix where easy like this and submit a pull request.

**Comment by oliviertassinari** [comment]
@westhouseit As far as I know, we don't support this yet. We would likely get it for free once we use the main repository npm package release strategy.
