### ISSUE TITLE
[DataGrid] Sorting order of input rows isn't respected when sortModel is empty

### ISSUE THREAD

**Issue by mathmoth** [mui-org/material-ui-x#753]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Rendering a simple XGrid with the following rows prop:
```js
const myData = [{ id: 10 }, { id: 0 }, { id: 5 }];
```

Results in XGrid rendering the items sorted in ascending order like this:
0
5
10

## Expected Behavior 🤔

Expect it to render in the same order as the data that was provided, ie:
10
0
5

## Steps to Reproduce 🕹

https://codesandbox.io/s/material-demo-forked-f1egh?file=/demo.js

## Context 🔦

The data is passed down from our server in a particular "initial order". Re-ordering via clicking columns is fine, but the initial render should not make its own ordering assumptions.

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | v4.0.0-alpha.13

**Comment by oliviertassinari** [comment]
I could reproduce with `DataGrid` too: https://codesandbox.io/s/material-demo-forked-uzek8?file=/demo.js.
The initial order isn't respected anymore. It's a regression from v4.0.0-alpha.10. It works well in v4.0.0-alpha.9: https://codesandbox.io/s/material-demo-forked-3yjpn.

**Comment by nt-adrianmiranda** [comment]
Same example, different values, [new version](https://github.com/mui/mui-x/releases/tag/v4.0.0):
https://codesandbox.io/s/material-demo-forked-ljfl24?file=/demo.js:0-472
