### ISSUE TITLE
Material UI datagrid cannot be shown on IE11

### ISSUE THREAD

**Issue by lodatol** [mui-org/material-ui-x#775]
- [ X] The issue is present in the latest release.
- [ X] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When using datagrid, IE 11 won't load the React views because of use array functions

## Expected Behavior 🤔

Loading the datagrid also in IE11 as for supported platform

## Steps to Reproduce 🕹
<DataGrid className={this.classes.data_table} rows={this.state.data} columns={this.columns} pageSize={10} rowsPerPageOptions={[10, 25, 50, 100]} checkboxSelection />

**Comment by oliviertassinari** [comment]
@lodatol So far we don't plan to support IE 11 on this component.

**Comment by lodatol** [comment]
Hi @oliviertassinari thanks for your answer, if this is the reason then ok, before opening I see the ticket and it was already open so I decided to raise this up because I saw this link https://material-ui.com/getting-started/supported-platforms/ which state that IE 11 is supported.

Just to know the issue would not arise if the material ui utils instead of import via dependencies , it will be imported via **peerdependencies** since the current version does not use array function.
I just can't modify the code because I have only the compiled one but the solution in this case is really simple.
By the way all other component work within IE11, since it's just an import that cause the error, so I think that we can use just a regular table and implement the same function on it.

**Comment by oliviertassinari** [comment]
@lodatol The issue with the arrow function is only the tip of the iceberg. If we do want to support IE 11, we would need to fix the build infrastructure (use the one from the main repository), but also a bunch of CSS and JavaScript issues. It's not worth the effort for us. I agree that the current documentation can be confused. The ImageList component doesn't support IE 11 either.
