### ISSUE TITLE
[XGrid] Resizing XGrid columns breaks application when StyleProvider's disableGlobal is set to true.

### ISSUE THREAD

**Issue by VandekerkhoveBertil** [mui-org/material-ui-x#790]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
When using the XGrid component and I try to resize a column (which should be working as standard) the application crashes with the following error:

![image](https://user-images.githubusercontent.com/32326988/103215802-b46abe00-4914-11eb-9e40-fe3b131e0c41.png)

While investigating it more, this error appears when the StyleProvider's disableGlobal is set to true.

## Expected Behavior 🤔
The columns should resize.

## Steps to Reproduce 🕹

Steps:

1.  Go this sandbox: https://codesandbox.io/s/material-demo-forked-71yub?file=/demo.js:1524-1543
2. Try to resize a column and the error should occur

## Context 🔦
Trying to use the XGrid component in our application while still being able to keep the StyleProvider's disableGlobal property.

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | v4.0.0-alpha.13  |

**Comment by DanailH** [comment]
Thanks for reporting this @VandekerkhoveBertil . What do you thing about this solution? It breaks because when you use the theme the `MuiDataGrid-root` class is replaces with `MuiDataGrid-root-*`.

```
export function findCellElementsFromCol(col: HTMLElement): NodeListOf<Element> | null {
   const field = col.getAttribute('data-field');
-  const root = findParentElementFromClassName(col, 'MuiDataGrid-root');
+  const root = col.closest('div[class*="MuiDataGrid-root"]');
   if (!root) {
     throw new Error('Material-UI: The root element is not found.');
   }
@@ -47,7 +47,7 @@ export function findGridRootFromCurrent(elem: Element): HTMLDivElement | null {
   if (elem.classList.contains('MuiDataGrid-root')) {
     return elem as HTMLDivElement;
   }
-  const root = findParentElementFromClassName(elem, 'MuiDataGrid-root');
+  const root = elem.closest('div[class*="MuiDataGrid-root"]');
   return root as HTMLDivElement;
 }
