### ISSUE TITLE
[DataGrid] Poor performance when container is resized

### ISSUE THREAD

**Issue by inancatil** [mui-org/material-ui-x#799]
Animations are stuttering when using Datagrid.
 
- [ ] The issue is present in the latest release.
version:  "@material-ui/core": "^4.11.2",
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Opening/Closing navigation Drawer stutters.
Resizing window stutters.

## Expected Behavior 🤔

Animations expected to be smooth when there are less than 100 data.

## Steps to Reproduce 🕹
All codes are taken from sample codes.

https://codesandbox.io/s/material-demo-forked-hb1k4?file=/demo.tsx

Steps:

1.Opening navigation Drawer stutters when using  Posts  component.
2.Change Posts to  EnhancedTable in demo.tsx
3.Stutter disappers and works as expected .

## Context 🔦

Trying to achive smooth animations when using DataGrid component. 

## Your Environment 🌎
 
  
```
 System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 87.0.4280.88
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.66) (Using Edge browser)
  npmPackages:
    @material-ui/core: ^4.11.2 => 4.11.2
    @material-ui/data-grid: ^4.0.0-alpha.14 => 4.0.0-alpha.14
    @material-ui/icons: ^4.11.2 => 4.11.2
    @material-ui/lab: ^4.0.0-alpha.57 => 4.0.0-alpha.57
    @material-ui/styles:  4.11.2
    @material-ui/system:  4.11.2
    @material-ui/types:  5.1.0
    @material-ui/utils:  4.11.2
    @types/react: ^16.14.2 => 16.14.2
    react: ^17.0.1 => 17.0.1
    react-dom: ^17.0.1 => 17.0.1
    typescript: ^4.1.2 => 4.1.2
```
</details>

**Comment by mattcarlotta** [comment]
Just wanted to chime in on this issue and state that the more columns that are rendered by the table, the worse the performance and choppier the resize animation seems to get.

For example, I'm opening and closing and a side menu, which causes the entire table to resize (and its children re-rendered about 40 times). I've memoized the children to reduce the re-renders, but the net result is still a rather choppy animation...

When there are less columns, it's smoother: https://youtu.be/og-pdQEGGtc
vs.
When there are more columns, it becomes noticeably choppier: https://youtu.be/dgbMokCsHWM

This comparison demo showcases the performance difference between resizing an Ant Design `Table` vs a MUI `DataGrid`:
Ant Design: https://wl00d.csb.app/
MUI: https://w3l37.csb.app/

When resizing both tables using the ```toggle device bar``` in Chrome or ```Responsive Design Mode``` in Firefox, Ant's table feels smoother and responsive while the MUI table feels laggy and jittery (unfortunately, this only increases as the amount of columns increase). I'm also noticing quite a large load spike on my CPU when resizing the MUI DataGrid. I'm running a 16C/32T processor and when resizing a MUI DataGrid one of the cores can hit up to 100% while the rest hover around 1-15%; whereas resizing Ant's Table one core hits around 25% or less while the rest hover around 1-15% .

**Comment by oliviertassinari** [comment]
@mattcarlotta thanks for the details exploration.

**Comment by yairEO** [comment]
### This is still an ongoing issue even in latest version `v8`.

Especially with rows virtualization, so when the height of the grid changes, it's quite laggy.  

Possible reasons for grid (or its wrapper) `height` changes:
- `flex`/`grid` layout where other sections on the page can expand/collapse with animation
- page has multiple sections which allow the user to drag and resize their ratio of visible portions

I would like to have exposed control over the `resizeObserver` used internally (in DataGrid) so I could debounce it
