### ISSUE TITLE
[DataGrid] 3dot menu appears in column header and there is no doc support or way to remove it

### ISSUE THREAD

**Issue by VandekerkhoveBertil** [mui-org/material-ui-x#813]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
After the latest release (v4.0.0-alpha.14) I saw that there is a 3dot menu present now on each column header. After looking into the docs I couldn't find anything about it (mostly how to remove it) so I think this is a bug (correct me if i'm wrong).

![image](https://user-images.githubusercontent.com/32326988/103520062-d913e800-4e76-11eb-8366-3903e2e2ce3c.png)

## Expected Behavior 🤔
In my opinion there are two ways to go here, a possible solution is that the 3dot menu is removed again or there you could add documentation and a possibility to remove it.

## Steps to Reproduce 🕹
Steps:

1. https://codesandbox.io/s/material-demo-forked-71yub?file=/demo.js:1524-1543
2. Hover over a column

## Context 🔦
Think this was caused by my previous issue with the [fix for custom class name generators](https://github.com/mui-org/material-ui-x/pull/793) 

## Your Environment 🌎

| Tech          | Version |
| ------------- | ------- |
| Material-UI X | v4.0.0-alpha.14  |

**Comment by jzecca** [comment]
Looks like you can disable it by adding this:

```jsx
<DataGrid disableColumnMenu />
```

**Comment by VandekerkhoveBertil** [comment]
That did, the job. Thanks! But there is still no documentation for it as far as I can see.
