### ISSUE TITLE
[DataGrid] Popper wrong z-index

### ISSUE THREAD

**Issue by Grzegorzsa** [mui-org/material-ui-x#844]
When you place DataGrid in Dialog component filter options are not showing.

- [X] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Dialog has z-index  set to 1300 and div that filter is placed in has no z-index, so it is invisible. In console or CSS file I can manually set z-index of that div to 1400 and then I can see the filters, but I cannot type anything in input field anyway. (The same applies to XGrid)

## Expected Behavior 🤔

DataGrid placed in Dialog should work correctly with filters available.

## Steps to Reproduce 🕹

Steps:

1. Create Dialog and DataGrid or XGrid inside
2. Open the dialog
3. Click on 3 dots column menu - nothing happens
4. Click  filter icon or Density icon in Toolbar - nothing happens
5. Add to CSS `div[role="tooltip"] { z-index: 1400;}`
6. Now you can see filter and density options when you click on icons
7. Open filters and try to type any value - doesn't work

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 87.0.4280.141
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.75)
  npmPackages:
    @material-ui/core: 4.11.1 => 4.11.1
    @material-ui/data-grid: ^4.0.0-alpha.15 => 4.0.0-alpha.15
    @material-ui/icons: 4.11.2 => 4.11.2
    @material-ui/lab: 4.0.0-alpha.57 => 4.0.0-alpha.57
    @material-ui/pickers: 3.2.10 => 3.2.10
    @material-ui/styles:  4.11.2
    @material-ui/system:  4.11.2
    @material-ui/types:  5.1.0
    @material-ui/utils:  4.11.2
    @material-ui/x-grid: ^4.0.0-alpha.15 => 4.0.0-alpha.15
    @material-ui/x-grid-data-generator: ^4.0.0-alpha.15 => 4.0.0-alpha.15
    @material-ui/x-license:  4.0.0-alpha.15
    @types/react:  17.0.0
    react: ^16.13.1 => 16.14.0
    react-dom: 16.13.1 => 16.13.1
    styled-components:  4.4.1
    typescript:  3.9.7
</details>

**Comment by oliviertassinari** [comment]
@Grzegorzsa Thanks for reporting the issue. We can apply the same fix as we did for the Autocomplete component. What do you think about?

```diff
diff --git a/packages/grid/_modules_/grid/components/panel/Panel.tsx b/packages/grid/_modules_/grid/components/panel/Panel.tsx
index 8b723cd..e2e5d01 100644
--- a/packages/grid/_modules_/grid/components/panel/Panel.tsx
+++ b/packages/grid/_modules_/grid/components/panel/Panel.tsx
@@ -8,6 +8,9 @@ import { ApiContext } from '../api-context';
 const useStyles = makeStyles(
   (theme: Theme) => ({
     root: {
+      zIndex: theme.zIndex.modal,
+    },
+    paper: {
       backgroundColor: theme.palette.background.paper,
       minWidth: 300,
       maxHeight: 450,
@@ -59,6 +62,7 @@ export function Panel(props: PanelProps) {
   return (
     <Popper
       placement="bottom-start"
+      className={classes.root}
       open={open}
       anchorEl={anchorEl}
       modifiers={{
@@ -68,7 +72,7 @@ export function Panel(props: PanelProps) {
       }}
     >
       <ClickAwayListener onClickAway={handleClickAway}>
-        <Paper className={classes.root} elevation={8}>
+        <Paper className={classes.paper} elevation={8}>
           {children}
         </Paper>
       </ClickAwayListener>
```

Do you want to work on a pull request? :)

**Comment by dtassone** [comment]
Does that also fix 7.?

**Comment by oliviertassinari** [comment]
I didn't notice point 7. It's likely related to the support of nested Portal with TrapFocus. It's fixed in v5. So I believe covered in #441

**Comment by Grzegorzsa** [comment]
@oliviertassinari Thank you Olivier for quick response, I didn't expect it - that's impressive :) I think I'll leave the pull request for you, I'm not very familiar with your codebase. Great work all MUI team. XGrid is awesome. I presented it yesterday to my customer - he was delighted :)

**Comment by m14d3n** [comment]
@oliviertassinari  Will you fix point 7 in v4 or XGrid in Dialog will require v5?

**Comment by oliviertassinari** [comment]
@m14d3n We were talking about the version of `@material-ui/core`, not the data grid. It's only fixed in v5. v4 is in development freeze.

**Comment by m14d3n** [comment]
@oliviertassinari Thank you for the fast response. We are using @material-ui/core v4 for our current project - will move XGrid from dialog to separate page for now and in the future we will migrate to v5.

**Comment by m4theushw** [comment]
@oliviertassinari A possible solution for point 7 instead of using V5 would be passing `disablePortal` to the Popper [here](https://github.com/mui-org/material-ui-x/blob/master/packages/grid/_modules_/grid/components/panel/GridPanel.tsx#L75). This could be done via `componentsProps.panel`. We just have to spread the rest of the props into the root (sanitizing them first, of course). Is it worth?

**Comment by oliviertassinari** [comment]
@m4theushw The portal behavior was added in the first to help with the usage of the component in a dialog. It's unfortunate that it has the opposite effect in v4 😆. This point 7. was specifically raised in #1140.

I would propose we use this policy for the peer dependencies: @material-ui/data-grid is compatible with @material-ui/core v4 and v5. However, this doesn't mean that everything works well. The best support is provided on the latest version. For instance, dialog support, it's v5 only.

---

This makes me think about a discussion we had with @eps1lon on what peer dependency implies. From what I understood, we had a different vision of what the implications are (the warranties). To put it simply, you can either assume:

1. that the software warrants that it behaves correctly end-to-end, accounting for "flaws" in the peer dependency
2. or that it integrates well with the peer dependency, only warranting that that integration is correct, not the end-to-end behavior

I personally think that between 1 and 2 there is a grey area and that I would expect 2 from a package I install. But that's doesn't mean this is the correct answer.

**Comment by m4theushw** [comment]
@oliviertassinari I agree with you that the package should work end-to-end at least with the latest version. However, I think it would be valuable to offer the user some flexibility to fix flaws without overriding components. 

In this particular case of point 7 the solution for V4 is to duplicate `GridPanel` to pass `disablePortal` prop to the Popper. This prevents the TrapFocus from trying to move the focus.

**Comment by oliviertassinari** [comment]
@m4theushw Ok, no strong preferences

**Comment by m4theushw** [comment]
For anyone using Material-UI V4, I created a [codesandbox](https://codesandbox.io/s/compassionate-sun-e1r4o?file=/src/CustomGridPanel.js) showing the solution I mentioned [above](https://github.com/mui-org/material-ui-x/issues/844#issuecomment-800676791).
