### ISSUE TITLE
[DataGrid] Footer count not showing in "official" demo itself

### ISSUE THREAD

**Issue by zehawki** [mui-org/material-ui-x#847]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The demo shown here https://material-ui.com/components/data-grid/pagination/#server-side-pagination shows a grid with count shown at the bottom, ie 1-5 of 100 etc, which changes upon pagination.
However, the same in CSB (https://codesandbox.io/s/6etw1) using the link provided doesnt show the count at all.

I discovered this issue when using this component, and came back here to see that its also easily reproducible with the code provided.

## Expected Behavior 🤔

Should show the count in the footer, as shown in 1 or more demos,

## Steps to Reproduce 🕹

Editing the same in CSB (https://codesandbox.io/s/6etw1) using the link provided doesn't show the count at all.

**Comment by dtassone** [comment]
Have you tried increasing the size of the rendering panel in CSB?

**Comment by oliviertassinari** [comment]
Is the breakpoint used in the component correct?

**Comment by zehawki** [comment]
I'm not sure that should matter - I'm talking about the official examples provided, which AFAICS is the same code as given in the docs, and hence it looks like something in the component has changed. By way of illustrating via SS:

![image](https://user-images.githubusercontent.com/8095144/104436321-77105c80-55b3-11eb-9fac-fd581092f105.png)
As seen in the docs

![image](https://user-images.githubusercontent.com/8095144/104436371-87283c00-55b3-11eb-9666-fd8debbd8875.png)
As seen in the demo. Please note the missing count, whereas the arrows are there just fine.

**Comment by dtassone** [comment]
This is due to the screen size
![image](https://user-images.githubusercontent.com/936978/104437195-cbedac00-558e-11eb-9df0-892cb61d9319.png)

**Comment by zehawki** [comment]
Ohhh, I see. Thank you.

So would MUI consider changing this behavior, since it seems like a waste not to show that. The entire footer row is available, why hide this (very useful bit) in particular?

Conversely, I could not find any setting to force show this, from here https://material-ui.com/components/data-grid/rendering/#footer

**Comment by oliviertassinari** [comment]
@DanailH The current logic inherits from #508. We already had a first polish in #676. What do you think about making the input and the input label (to change the row per page) only visible on `md` while keeping the total count always visible?

```diff
diff --git a/packages/grid/_modules_/grid/components/Pagination.tsx b/packages/grid/_modules_/grid/components/Pagination.tsx
index 8516a55..c56db2c 100644
--- a/packages/grid/_modules_/grid/components/Pagination.tsx
+++ b/packages/grid/_modules_/grid/components/Pagination.tsx
@@ -8,13 +8,14 @@ import { ApiContext } from './api-context';

 // Used to hide the drop down select from the TablePaginagion
 const useStyles = makeStyles((theme: Theme) => ({
+  spacer: {},
   caption: {
-    display: 'none',
-    [theme.breakpoints.up('md')]: {
-      display: 'block',
-    },
-    '& ~ &': {
-      display: 'block',
+    // input label
+    '$spacer + &': {
+      display: 'none',
+      [theme.breakpoints.up('md')]: {
+        display: 'block',
+      },
     },
   },
   input: {
```

Do you want to take care of this issue?

**Comment by DanailH** [comment]
> @DanailH The current logic inherits from #508. We had a first polish in #676. What do you think about making the input and the input label (to change the row per page) only visible on `md` while keeping the total count always visible?

@oliviertassinari we can do that, no problem, but the reason why it is like this is that as far as I remember we also show the label for selected rows on a smaller resolution so there may be a conflict with that.

On the other node, there seems to be some other issue related to the way viewport sizes are triggered, because if I test it by resizing the screen manually the bug is reproducible but if I open it on a mobile device directly or select a mobile device from the Chrome Dev tools emulator directly the page and page size labels are visible 🤔. I would need to debug it further.

![IMG_1845](https://user-images.githubusercontent.com/5858539/104568021-cd32dd80-564f-11eb-9f2e-0ef486492d4f.PNG)

**Comment by oliviertassinari** [comment]
> we also show the label for selected rows on a smaller resolution

I recall we decided against display the selected rows because it was a secondary type of information.

> if I test it by resizing the screen manually the bug is reproducible but if I open it on a mobile device directly or select a mobile device from the Chrome Dev tools emulator directly the page and page size labels are visible 🤔

Follow the reproduction instructions more carefully, the behavior changes weather the rows per page control is visible or not.
