### ISSUE TITLE
[DataGrid] onPageSizeChange shouldn't trigger on mount

### ISSUE THREAD

**Issue by nghiepit** [mui-org/material-ui-x#848]
Hi guys,

`onPageSizeChange` trigger immediately the `DataGrid` is mounted.

```jsx
 <DataGrid
        rows={rows}
        columns={columns}
        pageSize={pageSize}
        onPageSizeChange={handlePageSizeChange} <=== TRIGGER ON MOUNT
 />
```

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce 🕹

https://codesandbox.io/s/material-demo-forked-ck54o?file=/demo.tsx

Steps:

1. Check `Console` tab
2.
3.
4.

## Your Environment 🌎
"@material-ui/data-grid": "^4.0.0-alpha.15"

**Comment by DanailH** [comment]
@nghiepit thanks for reporting this. We have a similar issue but related to the `onPageChange` event.

@oliviertassinari @dtassone this seems similar to [#816](https://github.com/mui-org/material-ui-x/issues/816) in a way that it is not expected for those events to fire on initial render. I'm not 100% sure that it falls into the same bucket but it is worth checking.
