### ISSUE TITLE
[DataGrid] Pagination is 1-based but should be 0-based

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#852]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The pagination is 1-based.

## Expected Behavior 🤔

The pagination is 0-based.

## Steps to Reproduce 🕹

Steps:

1. https://material-ui.com/components/data-grid/pagination/#controlled-pagination

## Context 🔦

1. The `Pagination` component, which is meant for SEO starts at page 1. This is simpler for mapping with the URL: (`?page=2`).
2. The `TablePagination` component which is meant for data grid use cases starts at page 0: https://material-ui.com/components/pagination/#table-pagination. This is simpler to match with the default index of JavaScript arrays.

I believe it would make more sense for the data grid to match `TablePagination` rather than `Pagination`. It also seems to be a common convention: [ag-Grid](https://ag-grid.com/documentation/javascript/row-pagination/#example-customising-pagination) is 0-based, and [react-table](https://react-table.tanstack.com/docs/examples/row-selection-and-pagination) is 0-based too. However, I haven't look further than these two comparison points.

It might be related to #685.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  System:
    OS: macOS 11.1
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.9 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 87.0.4280.141
    Edge: 87.0.664.75
    Firefox: 84.0.2
    Safari: 14.0.2
  npmPackages:
    @emotion/react: ^11.0.0 => 11.1.4
    @emotion/styled: ^11.0.0 => 11.0.0
    @material-ui/codemod:  5.0.0-alpha.22
    @material-ui/core:  5.0.0-alpha.22
    @material-ui/docs:  5.0.0-alpha.22
    @material-ui/envinfo:  1.1.4
    @material-ui/icons:  5.0.0-alpha.22
    @material-ui/lab:  5.0.0-alpha.22
    @material-ui/styled-engine:  5.0.0-alpha.22
    @material-ui/styled-engine-sc:  5.0.0-alpha.22
    @material-ui/styles:  5.0.0-alpha.22
    @material-ui/system:  5.0.0-alpha.22
    @material-ui/types:  5.1.4
    @material-ui/unstyled:  5.0.0-alpha.22
    @material-ui/utils:  5.0.0-alpha.22
    @types/react: ^17.0.0 => 17.0.0
    react: ^16.14.0 => 16.14.0
    react-dom: ^16.14.0 => 16.14.0
    styled-components:  5.2.1
    typescript: ^4.1.2 => 4.1.3
```
</details>

**Comment by McGern** [comment]
It's probably just me, but I ended up here wishing that the tablepagination was indexed from 1 as well to make it consistent with the paging component.  I am using url paging for my table data and it's a real pain keeping track of the +/- 1 thing because the server, which delivers to both paged and tablepaged components, is 1 indexed.

**Comment by oliviertassinari** [comment]
@McGern Yeah, it's a tradeoff. Keeping the page in the URL, when there is a single data grid, this is definitely a good UX pattern. We have bet on 0-page as covering more use cases.

**Comment by ridl27** [comment]
they really should give us some parameter, like 'basedPagination={0|1|10|100500}' so we can easily use pagination that we want...

**Comment by oliviertassinari** [comment]
@ridl27 I would recommend not allowing this to be customized, on the basis that it will complexity the code for most users while benefitting a few.

**Comment by chunsenye** [comment]
hi, brother

@mui/material/Pagination  is 1-base 
[DataGrid] Pagination is 0-based 
Api Pagination is 1-base  

```
   } else if (key === 'page') {
      // DataGrid Pagination is 0-base but Api Pagination is 1-base  https://github.com/mui/mui-x/issues/852
      parameters.append(key, String(Number(value) + 1))
    } else if (value !== undefined && value !== '') {
      parameters.append(key, value.toString())
    }
```

so maybe set a default: 0-base
and custom to 1-base



so

@oliviertassinari
