### ISSUE TITLE
[DataGrid] Column selector crashes with 3 hidden columns

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#856]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Crash

## Expected Behavior 🤔

No crash

## Steps to Reproduce 🕹

Steps:

1. Open https://material-ui.com/components/data-grid/columns/#column-selector
2. Have 3 columns hidden
3. <img width="855" alt="Capture d’écran 2021-01-16 à 01 19 58" src="https://user-images.githubusercontent.com/3165635/104790910-ff9c2200-5798-11eb-90d2-b8fe93615bda.png">

It fails here

<img width="931" alt="Capture d’écran 2021-01-16 à 01 20 46" src="https://user-images.githubusercontent.com/3165635/104790947-1a6e9680-5799-11eb-87b9-e137e51b9d47.png">

## Context 🔦

It's a follow-up on #345, @DanailH was leading the effort on it.

**Comment by DanailH** [comment]
Ok this is strange as when I tested it I wasn't able to reproduce that error but I'll check it now and aim to fix it ASAP.
