### ISSUE TITLE
[DataGrid] When the row id is a number type, the rowIds returned by the onSelectionChange event are of type string[]

### ISSUE THREAD

**Issue by zj9495** [mui-org/material-ui-x#874]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
When the row id is a number type, the rowIds returned by the onSelectionChange event are of type string[]

## Expected Behavior 🤔
Should return number type instead of being converted to string type

## Steps to Reproduce 🕹

https://codesandbox.io/s/material-demo-forked-yi86n?file=/demo.js

Steps:

1.Open the codesandbox link above
2.Open the console
3.Click on any row in the table
4.Console will print string type id

## Your Environment 🌎

v4.0.0-alpha.24

  System:
    OS: Linux 4.19 Ubuntu 20.04.1 LTS (Focal Fossa)
  Binaries:
    Node: 12.20.0 - ~/.nvm/versions/node/v12.20.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.20.0/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v12.20.0/bin/npm
  Browsers:
    Chrome:  87.0.4280.141
    Firefox: Not Found

**Comment by zj9495** [comment]
It seems that Object.keys is used here, and Object.keys only returns string[] type
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys#return_value
https://github.com/mui-org/material-ui-x/blob/682c544430e146e7cd013a537b6ad5fd9f13f0f8/packages/grid/_modules_/grid/hooks/features/selection/useSelection.ts#L79-L88

**Comment by oliviertassinari** [comment]
@zj9495 Interesting, we are storing the selection in an object:

<img width="396" alt="Capture d’écran 2021-01-19 à 21 11 56" src="https://user-images.githubusercontent.com/3165635/105087606-05e11580-5a9b-11eb-8c72-caeda2c78497.png">

Objects can only store strings. It sounds like we should have used `Set`, as we aim to support both types:

https://github.com/mui-org/material-ui-x/blob/8a26d4b31dc4e82d433164897ed6e317cb16adf1/packages/grid/_modules_/grid/models/rows.ts#L10-L13

**Comment by oliviertassinari** [comment]
Humm, but a Set can't be serialized and stored in a data base

```
let mySet = new Set();
mySet.add(1);
JSON.stringify({ mySet }); // "{"mySet":{}}"
```

**Comment by zj9495** [comment]
@oliviertassinari Thanks for your reply!
use a Set looks very cool, it would be a pity if cannot use it. Maybe we could convert Set to a Array when the onSelectionChange event return rowIds?

**Comment by oliviertassinari** [comment]
I have updated the reproduction to fail with the latest version of the package.
