### ISSUE TITLE
[DataGrid] If page != 1, onPageChange gets fired on mount

### ISSUE THREAD

**Issue by palfrey** [mui-org/material-ui-x#885]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

If page != 1, onPageChange gets fired on mount, and with the default settings for pageCount/pageSize, etc. I then also get the informative error `TypeError: r.current.scrollTo is not a function` from somewhere in dataGrid (although I'm not able to reproduce that one in sandbox yet...)

## Expected Behavior 🤔

onPageChange should probably not be called, or should at least be delayed until all the parameters are set

## Steps to Reproduce 🕹

https://codesandbox.io/s/onpagechange-bug-forked-zfxp3?file=/demo.tsx:1809-1825

1. Run sandbox
2. see console with pageSize as 100, even though it's set as 50
3.
4.

## Context 🔦

Mostly this was a test configuration, trying to check rendering of later pages, but it was still surprising to see the breaks

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  System:
    OS: macOS 10.15.7
  Binaries:
    Node: 15.2.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.10 - /usr/local/bin/npm
  Browsers:
    Chrome: 87.0.4280.141
    Edge: Not Found
    Firefox: 84.0
    Safari: 14.0.2
  npmPackages:
    @material-ui/core: ^4.11.0 => 4.11.0
    @material-ui/data-grid: ^4.0.0-alpha.14 => 4.0.0-alpha.14
    @material-ui/icons: ^4.9.1 => 4.9.1
    @material-ui/lab: ^4.0.0-alpha.56 => 4.0.0-alpha.56
    @material-ui/styles:  4.10.0
    @material-ui/system:  4.9.14
    @material-ui/types:  5.1.0
    @material-ui/utils:  4.10.2
    @types/react: ^16.9.34 => 16.9.35
    react: ^16.13.1 => 16.13.1
    react-dom: ^16.13.1 => 16.13.1
    typescript: ^4.0.2 => 4.0.2
```
</details>

**Comment by palfrey** [comment]
The `scrollTo` thing is a jsdom bug, which Jest uses. Hence my lack of being able to make it break in a browser. See also https://github.com/jsdom/jsdom/pull/2626

**Comment by oliviertassinari** [comment]
@palfrey Thanks for reporting the callback issue, we had a first iteration on the problem in #838 with @dtassone but we didn't get to the bottom of it. 

I think that:

1. `onPageChange` should have two arguments (event, page). It shouldn't include unrelated state, like pageCount, pageSize, etc.
2. `onPageChange` should only fire when the underlying state change, it doesn't change when the component mount, so this test is wrong:

https://github.com/mui-org/material-ui-x/blob/b1397e8397976ede6bc0b398927791f51fe51aff/packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx#L71-L80

3. `onPageSizeChange` shouldn't fire, the state didn't change, same logic as 2.

@palfrey What do you think?

**Comment by oliviertassinari** [comment]
@palfrey Also, could you make sure you upgrade to use @material-ui/data-grid@4.0.0-alpha.17? It seems you are on alpha.14 in your local env.

**Comment by palfrey** [comment]
> @palfrey What do you think?

Sounds good to me.

**Comment by dtassone** [comment]
> @palfrey Thanks for reporting the callback issue, we had a first iteration on the problem in #838 with @dtassone but we didn't get to the bottom of it.
> 
> I think that:
> 
> 1. `onPageChange` should have two arguments (event, page). It shouldn't include unrelated state, like pageCount, pageSize, etc.
> 2. `onPageChange` should only fire when the underlying state change, it doesn't change when the component mount, so this test is wrong:

What if you update the page prop? Should `onPageChange` fire?

**Comment by oliviertassinari** [comment]
> What if you update the page prop? Should onPageChange fire?

Does `onChange` fire when something changes the value prop in an `<input >`? No, I think that it should be the same
