### ISSUE TITLE
[DataGrid] Keyboard shortcut to select a row (Shift+Space) not working

### ISSUE THREAD

**Issue by wouter-leistra** [mui-org/material-ui-x#889]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Datagrid renders and a cell has tab focus, using the shortcut SHIFT+SPACE as per [docs](https://material-ui.com/components/data-grid/accessibility/) to select the row, results in nothing to happen. Tested on latest Chrome and Firefox releases.

## Expected Behavior 🤔

The row of the cell that had focus after using the shortcut is selected.

## Steps to Reproduce 🕹
See current behavior
https://codesandbox.io/s/material-ui-issue-latest-forked-njidy?file=/src/Demo.js

## Context 🔦

Aim: Make the datagrid accessible again.

## Your Environment 🌎
  Chrome: Version 87.0.4280.141 (Official Build) (x86_64)
  Firefox: 84.0.2 (64-bit)
  
<details>
  <summary>`npx @material-ui/envinfo`</summary>
```
 System:
    OS: macOS 11.1
  Binaries:
    Node: 14.14.0 - ~/.nvm/versions/node/v14.14.0/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.14.0/bin/npm
  Browsers:
    Chrome: 87.0.4280.141
    Edge: Not Found
    Firefox: 84.0.2
    Safari: 14.0.2
  npmPackages:
    @material-ui/core: ^4.11.0 => 4.11.0 
    @material-ui/data-grid: ^4.0.0-alpha.17 => 4.0.0-alpha.17 
    @material-ui/icons: ^4.9.1 => 4.9.1 
    @material-ui/lab: ^4.0.0-alpha.56 => 4.0.0-alpha.56 
    @material-ui/styles:  4.10.0 
    @material-ui/system:  4.9.14 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.10.2 
    @types/react: ^16.9.32 => 16.9.55 
    react: 16.14.0 => 16.14.0 
    react-dom: ^16.12.0 => 16.14.0 
    styled-components: ^5.2.1 => 5.2.1 
    typescript: ^3.8.3 => 3.9.7 
```
</details>

**Comment by DanailH** [comment]
Hi, @wouter-leistra thanks for catching this. I tested it, it is also reproducible on the MUI website.

**Comment by dtassone** [comment]
That's a regression

**Comment by oliviertassinari** [comment]
- We document the shortcut in https://material-ui.com/components/data-grid/accessibility/#selection
- The regression happened between v4.0.0-alpha.14 (working) and v4.0.0-alpha.15 (broken)
- The regression happened in #794
