### ISSUE TITLE
Resizing an XGrid column after removing another crashes the app

### ISSUE THREAD

**Issue by vktrl** [mui-org/material-ui-x#920]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Resizing under certain circumstances throws errors  `Cannot read property 'width' of undefined`

## Expected Behavior 🤔

It shouldn't

## Steps to Reproduce 🕹

https://codesandbox.io/s/xgrid-overflow-c038i?file=/src/index.tsx

Steps:

1. Hide any column
2. Resize any column to produce overflow
</details>

**Comment by oliviertassinari** [comment]
Fixed in #875. Confirmation: https://codesandbox.io/s/xgrid-overflow-forked-wwdd5
