### ISSUE TITLE
[docs] Update keys supported by the components prop

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#926]
## Current Behavior 😯

The list in https://material-ui.com/components/data-grid/rendering/#components-prop for the `components` prop is outdated:

<img width="664" alt="Capture d’écran 2021-01-25 à 23 30 26" src="https://user-images.githubusercontent.com/3165635/105774209-535ef600-5f65-11eb-9bbd-3d38049cf6b5.png">

## Expected Behavior 🤔

We barely document the `components` on the API page. We should keep the list in sync and provide more details. I think that we could reproduce the content of https://github.com/mui-org/material-ui-x/blob/8b942a4de6f0b20de989f2abdd6d3c97aed034d1/packages/grid/_modules_/grid/models/gridSlotsComponent.ts#L33 (icons included)

=> update https://material-ui.com/api/data-grid/ with a new `## Slots`, before `## CSS`.
=> Replace the bullet points of https://material-ui.com/components/data-grid/rendering/#components-prop with a link to https://material-ui.com/api/data-grid/#slots

---

cc @mui-org/core-team I wonder how we will solve this problem with the core components.

**Comment by eps1lon** [comment]
> I wonder how we will solve this problem with the core components.

Not sure I understand what the problem is. Can't we treat `components` just like `classes` regarding documentation?

**Comment by oliviertassinari** [comment]
> Not sure I understand what the problem is. Can't we treat components just like classes regarding documentation?

We could, it sounds like a promising approach 👍

**Comment by hellpirat** [comment]
What version should I use for ColumnMenu component? 🤔

**Comment by dtassone** [comment]
> What version should I use for ColumnMenu component? 🤔

v4.0.0-alpha.18
