### ISSUE TITLE
[XGrid] Support removing rows with the streaming API

### ISSUE THREAD

**Issue by yehudagoldner** [mui-org/material-ui-x#935]
Hi, 
I purchased  XGrid for the rows live update feature.
The new rows with the same id getting updated.
But i can't find a way to delete or hide the previous records which are not on the new array without refreshing the all grid.

Please help me
Thank you in advanced

**Comment by dtassone** [comment]
Hi @yehudagoldner, 

Thanks for opening the issue. Yes atm we only handle adding new rows and updating values. The current update rows api does not handle deleting rows.

**Comment by dtassone** [comment]
A workaround could be to do it with the grid state, and update the row state to remove the row you don't want.
something along...
```
const apiRef = useApiRef();
const [gridState, setGridState, update] = useGridState(apiRef);
....
setGridState(state=> {
  const index = state.rows.all.indexOf(myId);
  delete state.rows.all[index];
  delete state.rows.lookup[myId];
  return {...state};
})
forceUpdate();
...
```

We need to add an api method to delete rows, and maybe a way to delete rows via the update api so the backend guys can send the update accordingly.
```
// For the api method
apiRef.current.deleteRows([id1, id2])

// For the streaming api
apiRef.current.updateRows({id: myId, _action_: 'delete'}); 
// => _action_ would be a special property that let the component knows how to treat the update, default merge, it could be delete or replace 🤔 
```
Let me know what you think

**Comment by oliviertassinari** [comment]
@yehudagoldner What type of API do you envision to solve your problem? Is there one between the two proposed that would best fit your use case?

> We need to add an api method to delete rows

@dtassone why do we need two different APIs?

**Comment by yehudagoldner** [comment]
thank you! 
this would be very convenient 
`apiRef.current.updateRows({id:` myId, _action_: 'delete'}); `

**Comment by yehudagoldner** [comment]
actually maybe somethime like this (i'm not a native english speaker so maybe you can find better naming)
apiRef.current.updateRows({rows: myNewArr, remove_absentee_rows: true})

**Comment by dtassone** [comment]
> @yehudagoldner What type of API do you envision to solve your problem? Is there one between the two proposed that would best fit your use case?
> 
> > We need to add an api method to delete rows
> 
> @dtassone why do we need two different APIs?

Well the first use case (deleteRows) is the classic approach where users need to delete a row with an action button for example.
The second use case is for grids driven by the backend where they constantly stream data and needs to update rows, so removing rows can be done by just sending an update to the stream

**Comment by oliviertassinari** [comment]
@dtassone I was under the assumption that `setRows` would be good enough for the classic use case. What do you think about only solving @yehudagoldner's problem and wait for another user to come up with an issue to consider `deleteRows`. Basically, optimizing for exposing as little API as possible.

**Comment by yehudagoldner** [comment]
so how do i use it?

**Comment by oliviertassinari** [comment]
I'm reopening as no documentation was added.

**Comment by Mistes974** [comment]
It seems that it is not working well

 ` Uncaught TypeError: Cannot read property 'action' of undefined`
 
```
 const DeleteRow = ({ id, api }) => {
  const onDelete = () => {
    api.updateRows([{ id, _action: "delete" }]);
  };

  return <Button onClick={onDelete}>{i18n.t("common.delete")}</Button>;
};

const columns = [
  ...
  {
    field: "custom",
    headerName: " ",
    filterable: false,
    hideSortIcons: true,
    sortable: false,
    resizable: false,
    disableColumnMenu: true,
    editable: false,
    cellClassName: "remove-outline",
    renderCell: (props) => {
      return <DeleteRow {...props} />;
    },
  },
];
```

**Comment by oliviertassinari** [comment]
@Mistes974 Please open a new issue with a reproduction. This thread is closed.
