### ISSUE TITLE
[XGrid] columns are reordered when onSelectionChange modifies some unbound datagrid data

### ISSUE THREAD

**Issue by McFoggy** [mui-org/material-ui-x#936]
- [X] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When `onSelectionChange` update some data (even unrelated to what is bound to the datagrid) then the column order is reset

See reproducer from fork of your sample XGrid example : https://codesandbox.io/s/material-demo-forked-r36ci

## Expected Behavior 🤔

The selection does not change the column ordering.

## Steps to Reproduce 🕹

* open https://codesandbox.io/s/material-demo-forked-r36ci
* change the order of the columns
* click on a row to select it

The columns are reordered to the default state for no reason.

## Context 🔦

In a trial to evaluate your product we faced this issue.

## Your Environment 🌎

A fork of your sample on codesandbox

**Comment by dtassone** [comment]
I can't reproduce your issue 🤔

**Comment by oliviertassinari** [comment]
@dtassone You need to uncomment `// setMyState(!myState);`

**Comment by McFoggy** [comment]
sorry didn't realized that I have saved the comment.
I have removed it.

**Comment by oliviertassinari** [comment]
I have created a new reproduction to show that it's not an issue with the selection feature: https://codesandbox.io/s/material-demo-forked-4s6qs?file=/package.json, it's related to the column reorder feature.
