### ISSUE TITLE
[DataGrid] Controlled filtering via filterModel is broken

### ISSUE THREAD

**Issue by McFoggy** [mui-org/material-ui-x#938]
- [X] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

FilterModel with no items inside needs an array with an empty item otherwise it is broken.

## Expected Behavior 🤔

When setting the filterModel with an empty items array the filtering should be reset.

## Steps to Reproduce 🕹

Steps:

1. use https://codesandbox.io/s/material-demo-forked-rez18
2. in the TextField oin top of Grid type some text
3. the grid is filtered accordingly
4. empty the Textfield 
5. the FilterModel is not cleaned correctly

If you comment line 16 and uncomment line 14 instead, it works.

## Context 🔦

Testing your components.

## Your Environment 🌎

Copy of your sandbox demo project

**Comment by oliviertassinari** [comment]
@McFoggy Thanks for raising, it seems to be a simple logical mistake in the update logic. What do you think about this fix? Do you want to submit a pull request? :)

```diff
diff --git a/packages/grid/_modules_/grid/hooks/features/filter/useFilter.ts b/packages/grid/_modules_/grid/hooks/features/filter/useFilter.ts
index ba93942e..6c87be78 100644
--- a/packages/grid/_modules_/grid/hooks/features/filter/useFilter.ts
+++ b/packages/grid/_modules_/grid/hooks/features/filter/useFilter.ts
@@ -287,7 +287,7 @@ export const useFilter = (apiRef: ApiRef, rowsProp: RowsProp): void => {
   React.useEffect(() => {
     const filterModel = options.filterModel;
     const oldFilterModel = apiRef.current.state.filter;
-    if (filterModel && filterModel.items.length > 0 && !isDeepEqual(filterModel, oldFilterModel)) {
+    if (filterModel && !isDeepEqual(filterModel, oldFilterModel)) {
       logger.debug('filterModel prop changed, applying filters');
       // we use apiRef to avoid watching setFilterModel as it will trigger an update on every state change
       apiRef.current.setFilterModel(filterModel);
```

**Comment by McFoggy** [comment]
> What do you think about this fix? 

It looks good and enough to solve the issue.

> Do you want to submit a pull request? :)

Thanks but I have already difficulties to maintain my projects ;-)
