### ISSUE TITLE
Material UI DataGrid renders with width 0px 

### ISSUE THREAD

**Issue by constantineMelios** [mui-org/material-ui-x#941]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
When I use renderCell to pass Right React objects on a grid's cell.

DataGrid with autoPageSize === true && dataGrid's columns total width > browser width:
MuiDataGrid-viewport initializes with min-width: 0 width: 0. So no data shown.

DataGrid with pageSize === number && dataGrid's columns total width > browser width:
It creates extra height with empty rows or does not display a vertical scrollbar at all.

Both fix when you resize the browser window.

## Expected Behavior 🤔
Display normally as when browser width > grids width.

## Your Environment 🌎
  
```
 System:
    OS: macOS 11.1
  Binaries:
    Node: 15.6.0 - ~/.nvm/versions/node/v15.6.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v15.6.0/bin/yarn
    npm: 7.4.0 - ~/.nvm/versions/node/v15.6.0/bin/npm
  Browsers:
    Chrome: 88.0.4324.96
    Edge: Not Found
    Firefox: Not Found
    Safari: 14.0.2
  npmPackages:
    @material-ui/core: 4.11.2 => 4.11.2 
    @material-ui/data-grid: 4.0.0-alpha.17 => 4.0.0-alpha.17 
    @material-ui/icons: 4.11.2 => 4.11.2 
    @material-ui/pickers: 3.2.10 => 3.2.10 
    @material-ui/styles:  4.11.2 
    @material-ui/system:  4.11.2 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.11.2 
    @types/react:  17.0.0 
    react: 17.0.1 => 17.0.1 
    react-dom: 17.0.1 => 17.0.1 
```
</details>

**Comment by oliviertassinari** [comment]
Please provide a minimal reproduction test case. This would help a lot 👷 .
A live example would be perfect. [This **codesandbox.io** template](https://material-ui.com/r/issue-template-next) _may_ be a good starting point. Thank you!
