### ISSUE TITLE
DataGrid custom components not working

### ISSUE THREAD

**Issue by Novi-Greg** [mui-org/material-ui-x#944]
The components property of the datagrid is not working in the latest version (4.0.0-alpha.18).  I have a custom footer that is no longer displaying.  I reverted the version of the datagrid and the customer footer is now working again.

- [X ] The issue is present in the latest release.
- [X ] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Custom footer is not displayed and apparently not included in the source.

## Expected Behavior 🤔

Custom footer should be displayed in place of the standard footer

## Steps to Reproduce 🕹
Use a datagrid with a custom component and see that the component does not display.  Issue occurs in both Chrome and Safari.

Steps:

1.
2.
3.
4.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

**Comment by dtassone** [comment]
Could you provide a codesandbox please so we understand your issue.

**Comment by oliviertassinari** [comment]
@Novi-Greg Make sure you have handled the breaking changes documented in https://github.com/mui-org/material-ui-x/releases/tag/v4.0.0-alpha.18. You need to capitalize the key: `pagination -> Pagination`.
