### ISSUE TITLE
[XGrid] Column Selector breaks within a Custom Toolbar

### ISSUE THREAD

**Issue by shanemiller89** [mui-org/material-ui-x#946]
When Rendering <GridToolbar /> Within a custom toolbar, the column selector modal no longer opens. The column density modal still opens and works fine.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

- The column chooser button is clicked, and it's associated modal does not open. However the column density modal still function as expected.

## Expected Behavior 🤔

- The column chooser functions the same when rendered in a custom toolbar.

## Steps to Reproduce 🕹

https://codesandbox.io/s/material-ui-issue-latest-forked-lnexl?file=/src/Demo.js

Steps:

1. Create a custom toolbar component, render <GridComponent /> within Custom Toolbar
2. Render CustomToolbar in XGrid Header
3. Click Column Chooser button.

## Context 🔦

We need several custom components rendered inside the toolbar component, including a custom filter component, and some action buttons associated to the table. We also want to utilize the built in column chooser and density functionality, and be able to render all these components in a single toolbar.

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.9 - /usr/local/bin/npm
  Browsers:
    Chrome: 87.0.4280.141
    Firefox: 84.0.2
  npmPackages:
    @material-ui/core: ^4.11.3 => 4.11.3 
    @material-ui/icons: ^4.9.1 => 4.9.1 
    @material-ui/lab: ^4.0.0-alpha.56 => 4.0.0-alpha.56 
    @material-ui/pickers: ^3.2.10 => 3.2.10 
    @material-ui/styles:  4.11.3 
    @material-ui/system:  4.11.3 
    @material-ui/types:  5.1.0 
    @material-ui/utils:  4.10.2 
    @material-ui/x-grid: ^4.0.0-alpha.18 => 4.0.0-alpha.18 
    @material-ui/x-license:  4.0.0-alpha.18 
    @types/react:  16.9.43 
    react: ^16.14.0 => 16.14.0 
    react-dom: ^16.14.0 => 16.14.0 
    styled-components: ^5.2.1 => 5.2.1 
```
</details>

**Comment by dtassone** [comment]
That's because the `GridToolbar` does not contain the `PreferencesPanel`.
So you can either fix by calling `GridHeader` instead of `GridToolbar` in your custom toolbar or you add `PreferencesPanel`
```
function CustomToolbar() {
  return (
    <>
      <div>This is my custom Toolbar!</div>
      <GridHeader />
    </>
  );
}
// or
function CustomToolbar() {
  return (
    <>
      <div>This is my custom Toolbar!</div>
     <PreferencesPanel />
      <GridToolbar />
    </>
  );
}
```
I think we are missing a slot dedicated to the toolbar. So your approach works, and we could render the toolbar anywhere.
```
   <XGrid
        showToolbar
        components={{
          Toolbar: CustomToolbar
        }}
   />
```

**Comment by oliviertassinari** [comment]
> fix by calling GridHeader

👍 

A couple of extra notes:

- Why is `PreferencesPanel` rendered in the Header? Shouldn't it be **inside the main grid**? For instance:

  ```jsx
      <DataGrid
        components={{
          Header: () => null
        }}
  ```

  is breaking the column menu actions. https://codesandbox.io/s/material-ui-issue-latest-forked-qyii7?file=/src/Demo.js:369-430

- Should `PreferencesPanel` be exported, what's the use case? If it should, the name is wrong, it should be `GridPreferencesPanel`.

-  I don't think that it would make sense to add a `components.Toolbar` support given that @DanailH is removing this slot with #726.

- @dtassone I think that developers would appreciate if we could always use the syntax colors when commenting. Here, if you could do, it would be great:

````
```jsx
```
````

**Comment by dtassone** [comment]
1. By rendering it inside the header, it could easily be moved around, removed or overwritten. How can you render it in the footer...?
2. Yes so it can be used outside the grid.
3. I don't think it makes sense. I would add the slot, it makes things easier.
4. done

**Comment by oliviertassinari** [comment]
1. I don't follow the reasoning. What seems to maximize the flexibility is to render the PreferencesPanel inside the main grid container, **without being a child of another customization slot**. If we do such, we open the door for being disabled by mistake without, it's what happens with @shanemiller89.
Then if a developer wants to render it inside the footer. We can:
- PreferencesPanel: () => null
- Disable the Popper inside the Panel
- Import and mount `GridPreferencesPanel` inside the footer.

2. Ok, so we only need to rename the export.
3. Again, there will be no toolbar slot after #726, developers will systematically create their own toolbar. It won't come by default. The `showToolbar` prop is also going away.
4. 👌

**Comment by shanemiller89** [comment]
Thank you for the assistance! Very much appreciated.

Just to give a little feedback, we use data grids pretty heavily throughout our applications.

We have been using DevExtreme Reactive Grid as our main DataGrid. Beside's not being a react first centered component, customization always proved overtly complex and difficult.

The XGrid has been a much friendlier component to work with thus far (and has been a real breath of fresh air coming from using the devExtreme Grid) . So in regards to the toolbar, yes customization is key for us, while still being able to leverage built in functionality of the Grid (Like the column Chooser). Many of our grids have different toolbar compositions for various reasons, so easily compose-able toolbars is a definite desire for our team.

**Comment by oliviertassinari** [comment]
@shanemiller89 Thanks for bringing in your perspective on the problem. I have shared a proposal in https://github.com/mui-org/material-ui-x/pull/948#discussion_r567043403 for solving this problem.

On a different note, I think that we can also pool on a problem we have been wondering with @DanailH. In the docs, say, https://material-ui.com/components/data-grid/columns/#column-selector. Would you rather see a demo with only the `<GridToolbarColumnSelector>` or with all the toolbars, say something like `<GridToolbars />`?

**Comment by oliviertassinari** [comment]
Actually, this demo is broken too: https://material-ui.com/components/data-grid/rendering/#header.
