### ISSUE TITLE
[DataGrid] disableClickEventBubbling prevents onRowClick from firing

### ISSUE THREAD

**Issue by rahiparikh** [mui-org/material-ui-x#947]
- [X] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The documents suggest that one should use `disableClickEventBubbling` to stop event bubbling and disable control selection (such as checkbox) on row click. While this is helpful, it prevents `onRowClick` from firing.

## Expected Behavior 🤔

While the `disableClickEventBubbling` is desired property to prevent automatic selection, `onRowClick` should fire independently to allow one to take another action (that is not row selection) upon row click.

## Steps to Reproduce 🕹

https://codesandbox.io/s/material-ui-issue-latest-forked-qzrru?file=/src/Demo.js

**Comment by oliviertassinari** [comment]
Ohh, interesting problem. We have a related issue (constraint) in #891. I can think of two different paths for the solution. Either we can

1. go down of road that makes us closer to how native events work. We implement https://github.com/mui-org/material-ui-x/issues/891#issuecomment-764795190. We remove `disableClickEventBubbling`. We add the support of `event.defaultMuiPrevented` to have the grid ignore checkbox selection. My main concern with this approach is that the cell will require more custom logic handling as we add cell editing or range selection. I'm not sure `event.defaultMuiPrevented` can scale or is simple enough to use. We use the pattern in: https://next.material-ui.com/components/autocomplete/#events
2. go further down the weird attraction layer, add new booleans for new behaviors. My main concern is that the more we push this direction, the less we and developers will understand what's going on. The event model is already relatively simple and known among developers.

**Comment by rahiparikh** [comment]
@oliviertassinari Thank you for looking into this request. I do not have preference for either option.

**Comment by dtassone** [comment]
@rahiparikh have you tried using the prop `disableSelectionOnClick`? This option will allow you to use the onRowClick without selecting the row.
`disableClickEventBubbling` allows to handle events yourself. Ie if you pass your component in renderCell, you can handle your click events...

**Comment by tarochipz** [comment]
👋 having the same issue and was able to resolve using the `disableSelectionOnClick` prop @dtassone suggested. But I want the row highlight to still appear onRowClick, is there an easy way I can do that via available props? or do I need to do something custom like add a custom className onRowClick.

**Comment by dtassone** [comment]
depends if you want to select the row or not. 
If you want to, you can use the `selectionModel` prop to pass the new selected row or you could do with the css class as you suggested

**Comment by tarochipz** [comment]
So our use case might be a little bit unique. We have two _different_ selected states:

1. If checkbox is selected we render a footer for actions to be taken on the row - we don't want the row highlight to appear for this state (we refer to this as selected)
2. If a row is clicked, we render a side panel with details on the row - we want the row highlight to appear for this state but the checkbox to not be selected (we refer to this as active)

Since there's only one selected state for the XGrid, we need to be able to add the custom active class to the clicked row element.

**Comment by tarochipz** [comment]
Following up here, is there a way we can add classes to rows?  Our workaround of using the element.classList property is becoming pretty messy and messes with the grid checkbox interactions.

**Comment by dtassone** [comment]
@tarochipz atm you can add css classes on cells? Would that work? 
https://material-ui.com/components/data-grid/rendering/#styling-cells

**Comment by m4theushw** [comment]
I'm closing this because `disableClickEventBubbling` was removed by #1910.

To solve https://github.com/mui-org/material-ui-x/issues/947#issuecomment-784532142 the controlled selection can be used: https://material-ui.com/components/data-grid/selection/#controlled-selection
