### ISSUE TITLE
ESLint error in DataGrid columns definition

### ISSUE THREAD

**Issue by montclairskiclub** [mui-org/material-ui-x#951]
In the following columns definition for DataGrid

```
  const columns = [
    {
      field: 'fileType'
      , headerName: 'Type'
      , flex: 1
      // eslint-disable-next-line react/display-name
      , renderCell: (params: ValueFormatterParams) => (
        <FileIcon fileType={params.value as GDFileType} />
      )
    },
    {
      field: 'name'
      , headerName: 'Name'
      , flex: 1
    },
    {
      field: 'modifiedTime'
      , headerName: 'Modified'
      , flex: 1
    },
    {
      field: 'size', headerName: 'Size'
      , flex: 1
    },
  ];

```
the RenderCell column definition

```
      // eslint-disable-next-line react/display-name
      , renderCell: (params: ValueFormatterParams) => (
        <FileIcon fileType={params.value as GDFileType} />
      )
```
if the " // eslint-disable-next-line react/display-name" is not included ESLint produces an error that prevents TypeScript from compiling the code.

_(ESLint) react-display-name: Component definition is missing display name:_

**Comment by oliviertassinari** [comment]
@montclairskiclub Interesting feedback, `renderCell` isn't expecting a component, but a render function. This warning is a false-positive. I would recommend you disable the rule:

https://github.com/yannickcr/eslint-plugin-react/blob/4881bae2c644ca835353c3570aabd0eeb2befcf6/docs/rules/display-name.md

it's legacy.

**Comment by montclairskiclub** [comment]
Would you please elaborate on what you mean by “it’s legacy”? How is this
error prevented w/o the additional eslint comment? I have the latest build
of DataGrid.

Thanks
Chris

**Comment by kr1201** [comment]
Is there another to fix this issue? I don't find it very elegant to "solve" problems by disabling rules.
