### ISSUE TITLE
[XGrid] Updating the rows will change the column width back to the default width

### ISSUE THREAD

**Issue by zj9495** [mui-org/material-ui-x#970]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
Updating the rows will change the column width back to the default width

## Expected Behavior 🤔
When updating rows, keep the column width to the previously reszied size

## Steps to Reproduce 🕹

Steps:

1.open https://codesandbox.io/s/material-demo-forked-b43j6?file=/demo.tsx
2.reszie  the columns width
3.click 'UPDATE ROWS'

https://user-images.githubusercontent.com/17064586/106564167-d5ec4480-6567-11eb-8990-c72278d1e2cc.mov

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

**Comment by DanailH** [comment]
@zj9495 thanks for reporting this. It looked like that it might be related to https://github.com/mui-org/material-ui-x/issues/936 but I've tested it and it is reproducible in `master`.

**Comment by dtassone** [comment]
the grid works on the principle of immutability. Every time you rerender you create a new array of columns. 
If you put the columns in a state, they won't be reset.

**Comment by oliviertassinari** [comment]
Ok so, it's a question and we can close? https://codesandbox.io/s/material-demo-forked-hxn3s?file=/package.json
