### ISSUE TITLE
[DataGrid] "Select All" checkbox selects all rows instead of filtered rows

### ISSUE THREAD

**Issue by pekingdux** [mui-org/material-ui-x#976]
- [ x] The issue is present in the latest release.
- [ x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
After adding one or more column filters, the "Select All" checkbox will select all rows instead of the filtered rows. (Screenshot of current behavior below)

## Expected Behavior 🤔
"Select All" checkbox should only select filtered rows. 

## Steps to Reproduce 🕹
Steps:

1. https://codesandbox.io/s/material-demo-forked-d9y71?file=/demo.js
2. "Select All" checkbox

<img width="696" alt="Capture d’écran 2021-02-04 à 22 50 10" src="https://user-images.githubusercontent.com/3165635/106959724-5d3de180-673b-11eb-85bc-766d61663290.png">

## Context 🔦

We are trying to be able to capture groups of individuals based on filtered criteria, and need to often be able to select hundreds of active rows at a time.

We are running this in Chrome and Edge.

**Comment by pekingdux** [comment]
![Screen Shot 2021-02-03 at 8 43 59 AM](https://user-images.githubusercontent.com/78493817/106772499-4e511500-65fd-11eb-9b13-339246201289.png)

**Comment by oliviertassinari** [comment]
@pekingdux Thanks for opening this issue. This issue is somewhat related to #605. However, in our case, it's worse as the selection + filtering feature are effectively useless when used in combination.
