### ISSUE TITLE
Server-side rendering support

### ISSUE THREAD

**Issue by oliviertassinari** [mui-org/material-ui-x#98]
Rending the grid on the server fails on: 

https://github.com/mui-org/material-ui-x/blob/da5e83aa69291821e14218184d05a2c1c313bfd6/packages/grid/x-grid-modules/src/hooks/utils/useLogger.ts#L4

> ReferenceError: localStorage is not defined

This makes me also wonder. Do we want to bundle the `useLogger` package in production? Is there a way we could make is a noop when `process.env.NODE_ENV === 'production'`?

**Comment by oliviertassinari** [comment]
Solving this issue is required to render the grid on https://material-ui.com/. Once fixed, we get:

<img width="1121" alt="Capture d’écran 2020-07-23 à 13 03 18" src="https://user-images.githubusercontent.com/3165635/88279791-eaac6d80-cce4-11ea-816c-132ea6b81ab1.png">

However, the usage of styled-components causes issue:

<img width="920" alt="Capture d’écran 2020-07-23 à 13 04 59" src="https://user-images.githubusercontent.com/3165635/88279909-20515680-cce5-11ea-85e7-15b0ebfa3932.png">

I really think that we should drop styled-components for the first MVP to gain:

- Simpler configuration
- Leverage values from the theme
- Reduce bundle size

**Comment by oliviertassinari** [comment]
For context, this is a blocker with https://github.com/oliviertassinari/material-ui/tree/experiement-with-data-grid and adding pages under https://material-ui.com/components/data-grid/.

**Comment by dtassone** [comment]
I think a logger can be useful in production. Track user journey...

Can we check if localStorage exist? ie `localstorage?.getItem?(Debug)` something like that?

**Comment by oliviertassinari** [comment]
I don't think that it's enough, you can throw errors like this, prefer

```jsx
/* eslint-disable import/prefer-default-export */

function isSupported() {
  try {
    const key = '__some_random_key_you_are_not_going_to_use__'
    window.localStorage.setItem(key, key)
    window.localStorage.removeItem(key)
    return true
  } catch (err) {
    return false
  }
}

export const useLocalStorage = process.browser ? isSupported() : false // => true | false
```

**Comment by oliviertassinari** [comment]
> Track user journey.

I would personally use tools like https://heap.io/, or https://sentry.io/, or https://newrelic.com/ for that but it can be interesting to explore with our custom logger :).

**Comment by dtassone** [comment]
Not in an analytics way but more in a debugging way :)
