### ISSUE TITLE
[DataGrid] with useState and useEffect generates an error

### ISSUE THREAD

**Issue by jackjwilliams** [mui-org/material-ui-x#982]
Originally I thought it was just my code. But when I remove the usage of useEffect - it works fine (the grid displays as expected).

I was also able to reproduce this in codesandbox.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Using MIT DataGrid with useEffect / useState generates a "TypeError: Cannot read property 'length' of undefined" error.

![image](https://user-images.githubusercontent.com/1746015/106989303-80669200-6737-11eb-8e52-1cce1b9bbc30.png)

## Expected Behavior 🤔

Grid should render correctly. If you remove the useEffect, and just paste the array of data into useState(...), the grid renders fine.

## Steps to Reproduce 🕹

Codesandbox: https://codesandbox.io/s/material-ui-issue-forked-v7uwr?fontsize=14&hidenavigation=1&theme=dark&file=/src/Demo.js

Steps:

1. Import DataGrid
2. Import useState, useEffect
3. Make grid according to example, utilizing useState and useEffect
4. Error is generated

## Context 🔦

Just trying to use the DataGrid in combination with useEffect and useState

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  System:
    OS: Windows 10 10.0.18363
  Binaries:
    Node: 12.8.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 88.0.4324.104
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @material-ui/core: 4.11.3 => 4.11.3
    @material-ui/data-grid: 4.0.0-alpha.18 => 4.0.0-alpha.18
    @material-ui/docs: 4.0.0-beta.3 => 4.0.0-beta.3
    @material-ui/icons: 4.11.2 => 4.11.2
    @material-ui/lab: 4.0.0-alpha.57 => 4.0.0-alpha.57
    @material-ui/pickers: 3.2.10 => 3.2.10
    @material-ui/styles: 4.11.3 => 4.11.3
    @material-ui/system: 4.11.3 => 4.11.3
    @material-ui/types:  5.1.0
    @material-ui/utils:  4.11.2
    @types/react: ^17.0.0 => 17.0.0
    react: ^17.0.1 => 17.0.1
    react-dom: ^17.0.1 => 17.0.1
    styled-components: 5.2.1 => 5.2.1
    typescript: ^4.1.3 => 4.1.3
```
</details>

**Comment by dtassone** [comment]
That issue happens because you pass `undefined` in rows prop. Default value should be `[]`

**Comment by oliviertassinari** [comment]
considering that the prop is required, I would commend the following solution:

1. We sort the required props to the top of the file: https://material-ui.com/api/data-grid/. As it was done by Sebastian in #24526.
2. We add a prop-types for the `rows` prop to be `.isRequired` so that the codesanbox throw a warning explaining what's wrong.

It's also to be noted that point 1. and 2. come for free by updating the documentation stack of the main repository (1. and .2 are autogernated).

**Comment by jackjwilliams** [comment]
Ahh ok, it has been awhile since I worked with react. I didn't think about it being undefined on first render. I can fix my solution accordingly. Thank you!
