### ISSUE TITLE
[DataGrid]: colCell and colCellTitle Styles Apply to All Cells and Not Just Header

### ISSUE THREAD

**Issue by gvanriper** [mui-org/material-ui-x#989]
When I'm trying to apply a background color to only the **DataGrid** header, it seems to set the background color to all cells.

I checked the issues and didn't see this a a duplicate so I apologize if I missed one.

Currently I'm trying to apply a background color to only the cell title. I looked through the API and found possibly **colCell** and **colCellTitle** to be what I'm looking for. These seem to apply to apply to all cells.

I am on version **4.0.0-alpha.18** for the **DataGrid**.

This is how I produced the issue:

**const useStyles = makeStyles(theme => ({
      colCellTitle: {
          backgroundColor: "#002D72"
        }
}));**

or 

**const useStyles = makeStyles(theme => ({
      colCell: {
          backgroundColor: "#002D72"
        }
}));**

Code:

**<DataGrid className={classes.colCell}
  columns={[...data]}**

or

**<DataGrid className={classes.colCellTitle}
  columns={[...data]}**

Here is a sandbox to what I did to reproduce:

https://codesandbox.io/s/datagrid-colcell-and-colcelltitle-styles-apply-to-all-cells-and-not-just-header-2iwc5?file=/src/Demo.js 

Please let me know if you need anything else or if there is already a solution to this that I just simply missed. Thanks!

**Comment by oliviertassinari** [comment]
A working solution:

```css
    & .MuiDataGrid-columnsContainer {
      background-color: #002D72;
    }
```

https://codesandbox.io/s/datagrid-colcell-and-colcelltitle-styles-apply-to-all-cells-and-not-just-header-forked-ixvk6?file=/src/Demo.js:280-359

<img width="375" alt="Capture d’écran 2021-02-06 à 17 14 47" src="https://user-images.githubusercontent.com/3165635/107123628-d570e800-689e-11eb-8bdb-a32e216232da.png">

**Comment by gvanriper** [comment]
Is there somewhere in the API documentation that shows this? I couldn’t find a clear sample but maybe I’m missing something.

**Comment by oliviertassinari** [comment]
https://material-ui.com/api/data-grid/#css was meant to document this. We are fullying the transition to this customization pattern in v5. We don't encourage using the `classes` anymore (only for special use cases)

**Comment by gvanriper** [comment]
Oh, gotcha. I guess I’m still doing old school classes way and wasn’t aware of the change. I’ll look into it. I appreciate the solution and response.
